
strings = {
    "academy": "[http://www.youtube.com/user/osuacademy إضغط هنا] للذهاب إلى أكادمية osu! - دورات تعليمية في كل مجالات osu!",
    "achievements": "يمكنك الحصول على الإنجازات بالقيام بمهمة محددة , كالحصول على نقاط متتالية عالية في تصميم أو أن تلعب كل التصاميم في حزمة تصاميم محددة. يمكنك رؤية إنجازاتك في ملفك الخاص. أغلب الإنجازات من الواضح كيفية الحصول عليها , ولكن بعضهم يجب أن تفكر بنفسك في كيفية الحصول عليهم .",
    "add-skin": "[https://osu.ppy.sh/forum/t/3580 كيفية إضافة مظهر خاص.]",
    "advertising": "الإعلان عن أي شيء غير متعلق بosu! محظور.\nالمكررين للمخالفة أو الجديين فيها أقلها سيعاقبون بصمت .",
    "answer": "إذا لم يجاوب أحدُ على سؤالك , فإن الناس على الأغلب لا يعرفون \nالإجابة أو لا يريدون إجابتك بـنعم.",
    "appeal": "لإزالة صمت , أرسل رسالة خاصة في المنتدى إلى [[admin]] مع \nالأسباب التي تظن أنك تلقيت عقوبة الصمت ظلما .\nالإزالة الناجحة ستحذف المخالفة في ملفك وتزيل الصمت أيضا \nإن كان لا زال فعالاً.\nيجب الملاحظة أن الصمت لا يُلقى عبثاً , وأن محاولة الإزالة لا \nتضمن لك حذف المخالفة . تأكد من وجود الأسباب المقعنة او الدلائل\nالواضحة قبل فعل ذلك .",
    "approved": "الـApproved beatmap هي في الواقع أغنية غير قابلة للتصنيف\n(بسبب المدة , النقاط , إلخ..), ولكن تم التفكير في الموضوع من قبل\nأعضاء فريق تصنيف الأغاني بأن يتم تصنيفها .\nالأغاني المتفق عليها لديها قائمة المتصدرين الخاصة بها,\nمثل الأغاني المصنفة. الأغاني المتفق عليها يمكن تمييزها بأيقونة\nلهب بدل أيقونة الفلب (أيقونة القلب هي أيقونة الأغاني المصنفة)\n",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "فقط إسأل , لا تكن خجولاً! .",
    "attention": "يتبين أنه لا أحد يهتم لما تقوله. من الأفضل أن تتوقف.",
    "avatar-change": "يمكنك تغيير صورتك الشخصية :\n[https://osu.ppy.sh/home/account/edit#avatar هنا]",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "أنا آلي.\nأيضا, Bancho هو الخادم الرئيسي لـosu! .",
    "beatmapping": "إقرا [[Beatmapping]] لإيجاد بعض النصائح العامة.",
    "beginner": "[https://osu.ppy.sh/forum/t/5456 تدريب المبتدئين!]",
    "bn": "",
    "bored": "إذا كنت حقاً ضجراً , إفعل شيئاً آخراً.\nهنالك العديد من الأشياء على الإنترنت.\nالضجر ليس عذراً لك لتبكي او تخالف القوانين في osu!.",
    "bug": "فضلاً أبلغ عن المشاكل التقنية هنا [https://osu.ppy.sh/forum/5 forum],\nليس في الدردشة .",
    "bulgarian": "s",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Not applicable for the Arabic language.",
    "caps": "Not applicable for the Arabic language.",
    "change-modes": "لتغيير نمط اللعب إلى نمط آخر , إما أن تضغط على Mode في الجانب السفلي في اليسار أو أن تضغط Ctrl + 1-4. لا تنسى أن بعض التصاميم محددة النمط! (أي لا يوجد نمط آخر لها إلا النمط المصمم).",
    "change-name": "لتغيير إسمك المستخدم, أولا يجب ان تكون مساعداً لــosu! :\n[https://osu.ppy.sh/p/support مساعد لـosu!] بعد ذلك \nإقرأ هذا : [https://osu.ppy.sh/forum/t/34694] للتعلم اكثر \nعن التغيرات للإسم !",
    "changelog": "الإضافات الجديدة و اصلاحات المشاكل التقنية مرتبة في :\n[https://osu.ppy.sh/p/changelog صفحة التطوير] ",
    "chars": "فضلاً إستخدم الرموز الأساسية في الغرف الغير محددة اللغة",
    "charts": "تنزل مخططات osu! كل شهر . هم عبارة عن مجموعة من التصاميم\nالمختارة شهرياً أو تتناسب مع موضوع او فكرة معينة.\n يمكنك إيجادهم: [https://osu.ppy.sh/p/chart هنا]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "أصفر فاتح : مستخدم عادي\nأصفر : [https://osu.ppy.sh/p/support مساعد]\nأحمر : [https://osu.ppy.sh/wiki/QAT QAT] أو [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nأبيض : أنت, أو رسالة /me .\nأزرق : رسالة خاصة.\nأخضر : كتابة من مستخدم آخر تحتوي على إسمك (تسليط الضوء على).\nوردي : BanchoBot .",
    "colour": "أصفر فاتح : مستخدم عادي\nأصفر : [https://osu.ppy.sh/p/support مساعد]\nأحمر : [https://osu.ppy.sh/wiki/QAT QAT] أو [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nأبيض : أنت, أو رسالة /me .\nأزرق : رسالة خاصة.\nأخضر : كتابة من مستخدم آخر تحتوي على إسمك (تسليط الضوء على).\nوردي : BanchoBot .",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "",
    "comment": "لإضافة رد في تصميم, إضغط على الإطار المسمى Discussion \nعلى اليمين في حال مشاهدة إعادة لعب .\nإملىء الصناديق للمجالات التي تريد لردك أن يظهر فيها,\nثم أكتب الذي تريد قولها ثم إضغط Enter .\nإذا لم تظهر الردود, إضغط Show Comments. \nإنتبه, بعض التصاميم فيها ردود يمكنها حجب المشاهدة .",
    "comment-color": "",
    "conferencemode": "لمعرفة كيفية إبطال رسائل الإنضمام والخروج في مشغلات الـIRC\nإضغط [http://wiki.xkcd.com/irc/Hide_join_part_messages هنا]",
    "country-ranking": "[https://osu.ppy.sh/p/countryranking ترتيب الدولة]",
    "critic": "",
    "ctb": "[https://osu.ppy.sh/wiki/Catch_the_Beat أسئلة و أجوبة Catch the Beat]",
    "cutting-edge": "",
    "cwc": "بطولة عالمية في osu! لـCatch the Beat!\n[https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 أنقر هنا للمزيد من المعلومات.]",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\r\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\r\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "الرجاء الإلتزام بالآداب والأخلاق الطيبة في الدردشة إذا كنت\nتريد أن تعامل بإحترام.\nإمتنع عن إزعاج المستخدمين الآخرين الأخرين, وضع روابط لتصاميمك, دعوة كثير من الأشخاص العشوائيين الى غرفة اللعب , إلخ .. ",
    "disable-this": "لا , لن أعطل هذه الميزة او أي ميزة أخرى بدون أن تؤثر على\nالأداء بشكل سلبي وبتأثير حرج على اللعب.",
    "distance-snap": "أسهل طريقة لتأكيد أن المسافة بين كل إيقاع صحيحة في تصميمك هي بإستخدام خاصية تباعد المسافة في محرر التصاميم, يتواجد في الجهة اليمنى السفلية في المحرر.\nيمكن ضبط المسافات المتقاربة بين الدوائر بعجلة الفأرة. إذا إستعملت خاصية تباعد المسافة في الأغنية كلها, تباعد الصحيح بين الدوائر لمضمون!",
    "dont-ask-peppy": "السؤال الذي سألته يمكن الإجابة عليه من أي أحد في هذه القناة. فضلاً لا تسأل peppy في المرة القادمة.",
    "douche": "",
    "download": "[https://osu.ppy.sh/p/beatmaplist حمّل التصاميم هنا!]\n[https://osu.ppy.sh/beatmaps/packs مرتبة حزمة التصاميم الرسمية]",
    "drugs": "تتكلم عن المخدرات ممنوع.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "إقرأ [[Beatmapping#Keyboard_Shortcuts]] لمعرفة إختصارات تحرير التصاميم .",
    "english": "",
    "evade": "محاولة تفادي الصمت تعدي للقوانين قد يحظر حسابك بسببه , لا تفعله!",
    "fallback": "",
    "faq": "أنت تستعمل الآن نظام osu!bancho للأسئلة والأجوبة.\nويكبيديا osu! : https://osu.ppy.sh/wiki",
    "feature": "طلب الميزات يكتب في [https://osu.ppy.sh/forum/4 هذا القسم من المنتدى]",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "رجاءً عدم تفادي حاجب الكلمات البذيئة بتعمد .",
    "foul-play": "",
    "percolate": "رجاءً عدم تفادي حاجب الكلمات البذيئة بتعمد .",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "لإضافة مستخدم كصديق , إضغط على لوحة المستخدم في نمط F9\nأو على إسمهم في الدردشة وأختر Add as friend.\nبالإضافة يمكننك إضافتهم عن طريق الذهاب لملفهم\nوالضغط على Become friends!.\nيمكنك أيضاً كتابة الأمر /addfriend ملحوقا بإسم المستخدم .",
    "friends-list": "لرؤية قائمة الأصدقاء المتواجدين في اللعبة, إضغط F9 ثم غير\nالفارز في الأعلى إلى Friends.\nيمكنك أيضا رؤية قائمة كاملة لأصدقائك, كانوا متواجدين أم لا,\nفي الموقع بالضغط على Settings.\n(يجب أن تكون مسجلاً الدخول.)",
    "fullscreen": "يمكنك التغيير إما أن تكون شاشة اللعبة نافذة أو أن تحوي الشاشة بأكملها\nعن طريق إطار Graphics في قائمة الخيارات .\nيمكنك أيضاً التبديل عن طريق الضغط على Alt+Enter بلوحة المفاتيح.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "يمكنك إيجاد العديد من المصطلحات في osu!\n[[glossary]].",
    "gmt": "فريق المدراء العالمي , بإختصار  [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\n مجموعة من المستخدمين الذين يساعدون osu!. أسمائهم حمراء في الدردشة وخضراء في المنتدى.\nهؤلاء الأشخاص يساعدون في إدارة المنتدى والدردشة.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 سهلُ جداً , حتى أنت يمكنك فعل هذا.. ربما.]",
    "grammar": "رجاءً إستعمل قواعد اللغة الصحيحة. الأخطاء الصغيرة مثل نسيان حرف او عدم كتابة الفواصل مقبولة, لكن لا تستعمل المصطلحات الغريبة. هذا الشيء يجعلك كالغبي.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "لا تعرف كيفية اللعب ؟ تريد إستكشاف عالم التصميم والتعديل ؟\nستجد جميع الأجوبة [https://osu.ppy.sh/wiki/Guides هنا]",
    "hacked": "إذا كنت تعتقد أن حسابك قد أخترق, فضلاً تراسل مع هذا البريد الإلكتروني :\naccounts@ppy.sh\nإذا لم تتراسل فهنالك إحتمالية أن يحذف حسابك.",
    "hard": "",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "إذا أردت طلب المساعدة في أي شيء له صلة بـosu!, إنضم لقناة #help وأسأل أسئلتك.",
    "hitsound-library": "إذهب [https://osu.ppy.sh/forum/p/164927 هنا] للحصول على صوتيات خاصة لتصميمك.",
    "hl": "توقف عن التذمر بسبب تسليط الضوء على كلمة توجد في إسم مستخدمك.\nإنها غلطتك. إذا لم يعجبك الوضع, فأحذف الكلمة.",
    "how-to-get-modded": "إذا كنت تريد أن تعرف كيف يمكن لتصميمك أن يفحص, أضغط هنا :\n[[Getting_Your_Map_Modded]]",
    "how-to-bn": "يمكنك الترقي إلى الـBN على حسب جودة تعديلك في التصاميم ونشاطك.\nإذا سألت ان تكون BN , من المتوقع أنك لن تكون واحداً.\nولكن, إذا كنت مهتماً , إقرأ هذا [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator]\n",
    "how-to-gmt": "إذا كنت مهتماً بأن تكون من الإداريين , فالمتوقع أنك لن تكون واحداً.\nبمعنى آخر : سنرى إن كنت مستحقاً للإدارة.",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F إضغط هذا الرابط لتتعلم كيفية اللعب!]",
    "how-to-rank": "لمعرفة ذلك , أقرأ هذا :  [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "الإندفاع الخارق يحدث عندما تلتقط فاكهة تشع باللون الأحمر.\nستندفع أسرع من العادة في هذه اللحظة. ستنبطل الخاصية عندما\nتصل إلى الفاكهة اللاحقة, أو أن تخطأ في إلتقاطها .",
    "ignore": "لتجاهل شخصٍ ما, إكتب /ignore ثم إسم المستخدم.\nلن تتمكن من رؤية ما يكتبه المستخدم,\nبالإضافة لأي رسالة خاصة ترسل إليك عن طريقهم.\nسينتهي التأثير عند كتابة /unignore (إسم المستخدم) أو عند إغلاق اللعبة.",
    "import": "[http://i.imgur.com/kpX2N3m.jpg إقرأ هذا لمعرفة كيفية إدخال التصاميم في osu!]",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "عند وضع علامة صح في الصندوق inherit previous timing settings\nفي نافذة الـF6 في المحرر, قسم التوقيت لن يؤثر على التوقيت بعد الآن,\nوهذا مفيد للأقسام التي فقط تغير حجم الصوت و المؤثرات.\nأيضاً, من الممكن نسخ أقسام التوقيت التي ضاعفت الـBPM مرتين او نصفته.\nإذا كنت تجد نفسك تستعمل قسم التوقيت هكذا, فضلاً إنسخ!",
    "irc": "IRC خادم: irc.ppy.sh\nمنفذ: 6667\nكلمة المرور: https://osu.ppy.sh/p/irc",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "",
    "kiai": "نمط الكياي هو تأثير ضوئي يمكنك إضافته في أقسام التوقيت\n بإستخدام لوحة ضبط التوقيت.\nأقسام التوقيت مع نمط الكياي يستخدمون تأثيرات مرئية متعددة\nلجعل التصميم أكثر ملحميةً. تأكد من إستعماله بإعتدال!",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "عدل في تصاميم الأشخاص الآخرين لتحصل على نقاط [https://osu.ppy.sh/wiki/Kudosu kudosu].",
    "lag": "Lag هو مصطلح عام جداً, ويستخدم لوصف أي خطأ في أي شيء.\nإذا كنت ستتذمر من الـLag, رجاءً كن دقيقاً في أين يحدث الـLag,\nوماذا يتضمن (بطئ الإنترنت؟ تعطل الشاشة؟ بطئ في العرض؟).\nأذكر أيضا متى حدث الـLag, إذا كانت هنالك أي حالات\nخاصة ليحدث, وإذا كانت لديك أي أدنى فكرة ماهي الأسباب\nالتي سببت في حصوله. أيضاً تأكد من عدم وجود برامج مفتوحة قد \nتؤثر في المعالج/الذاكرة/إستخدام الإسطوانة.",
    "language": "فضلا كن محترما في الدردشة.",
    "language-specific": "",
    "lazer": "",
    "level": "مستواك يستند على محصلة نقاطك.\nهذا يشمل اي نقاط مصنفة, أكانت فشل أو فوز.\nسوف يزداد مستواك تدرجيا فقط باللعب.",
    "lines": "رجاءً تعلم الكتابة في خط واحد لتفادي الصمت.",
    "link": "لكتابة الرسالة كرابط , إستخدم الأمر التالي : [address text]. \naddress : هو مكان الرابط المراد كتابته.\ntext : هو الكلام الذي يعبر عن الرابط. \n[https://osu.ppy.sh/ مثل هكذا!] لا تنسى كتابة http:// .\nالإستخدام السيء لهذه لميزة, كوضع روابط مخلة للقوانين او تسليط\nالضوء على الناس بكتابة مخفية, لقابل للعقاب.",
    "lobby": "رجاءً إستخدم #lobby  للإعلان والنقاش في اللعب المتعدد.\nأيضاً, #lobby هي قناة اللعب المتعدد.",
    "localisation": "يمكنك إيجاد مشروع ترجمة الى لغات متعددة [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 هنا].",
    "long-link": "الرجاء عدم إستخدام روابط طويلة في الدردشة. إستعمل القاعدة  [الرابط النص]  إذا كنت حقا مضطرا إليها",
    "long-text": "رجاءً لا تلصق الروابط الطويلة في الدردشة.",
    "loved": "",
    "mac": "[https://osx.ppy.sh إلعب أوسو في الماكنتوش]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "المصممين هم أشخاص مشغولين, والتصميم هو عمل شاق.\n الطلبات على الأرجح لن يوافق عليهم.",
    "mapping": "إضغط [https://osu.ppy.sh/forum/p/988111 هنا] لتعليمات التصاميم.",
    "mat": "كان فريق مساعدة التصميم مجموعة قديمة التي ساعدت مجموعة الـBAT في عملية التصنيف",
    "modhelp": "لكل استفساراتك عن التصاميم, توجه إلى #mapping !",
    "modqueue": "[https://osu.ppy.sh/forum/60 طابور التعديل]",
    "modreqs": "رجاءً إذهب إلى #modreqs لأي طلبات للتعديل.\nتذكر أن الـBAT قد لا يحصلون على الوقت و أن لديهم طلبات أخرى, ففضلاً إسأل المستخدمين العاديين لتعديل تصميمك. شكراً.",
    "multi-invite": "للتمكن من دعوة أحد إلى اللعب المتعدد, في أثناء كونك رئيس الغرفة,\nإضغط على المستخدم المراد دعوته في قائمة المستخدمين المتواجدين\nواختر invite to game.\n",
    "multi-link": "",
    "multiaccounting": "عمل حسابات متعددة مخالف للقانون بشدة.",
    "multiplayer": "رجاءً  أعلن عن غرفتك في #lobby.\nإذا لم يكن هنالك لاعبون آخرون, لماذا لا تلعب بمفردك وتجرب لاحقاً ؟",
    "mwc": "",
    "nat": "",
    "news": "",
    "nightcore": "إستمتع بالتصميم المفضل لديك بنمط الـNightcore!\nببساطة اضغط مرتان على نمط الـDoubletime لإظهار نمط الـNightcore!",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "إكتب /np لإخبار الناس بالأغنية التي تستمع إليها أو بالتصميم الذي تلعبه.",
    "nsfw": "المحتويات والنقاشات الإباحية غير مرغوب فيها بشدة في الدردشة.",
    "osu": "#osu هو للتكلم عن osu!. رجاءً ناقش اللعب هناك. ليس في هذه القناة",
    "osu!tablet": "",
    "osu!talk": "",
    "osucore": "مزحة أبريل في عام 2011. جميع التصاميم ضبطت إلى DoubleTime أساسيا و رفع الموجات الصوتية لهم.\nبعد مدة صمم كنمط الـNightcore, والذي لديه نفس التأثيرات للـDoubletime.",
    "osu!droid": "",
    "osumania": "رجاءً إنضم إلى #osumania لمناقشة أي موضوع له صلة بـosu!mania.",
    "osustream": "[http://www.osustream.com osu!stream] هو osu! لأجهزة الويندوز المحمولة.",
    "osz": "تمدد ملف التصميم الذي تحمّله لـosu! هو osz. هذه الملفات يجب دائما أن يفك ضغطه من osu! نفسها, وإلا يمكن للمشاكل أن تحدث! ",
    "osz2": "تمدد ملف تصميم جديد وهذا يعني أن كل ملف يمكن أن يشفر,\n محدثة بإستقلال بين جميع الملفات الآخرى.\nلن يكون هنالك أي حاجة لفك ضغط ملفات الـ.osz2 وسوف دائما\nيظلون كملفات .osz2 في ملف الأغاني.",
    "owc": "بطولة osu! العالمية.\n[https://osu.ppy.sh/wiki/OWC إقرأ هذا الموضوع للمزيد من المعلومات.]",
    "peppy": "ألا تعرف ؟ peppy هو قائد [https://osu.ppy.sh/p/team فريق osu!]",
    "perfect": "لم تحصل على الـSS ؟ هذا النمط تلقائياً يعيد اللعبة إذا عملت أي خطأ.\nيمكنك إيجاده بالضغط مرتين على SuddenDeath في شاشة إختيار النمط.",
    "ping": "Pong!",
    "pippi": "هو الشخصية الجالبة للحظ في osu!\nPippi-don هو نسخة الـTaiko لـPippi.",
    "piracy": "لا تطلب أو تناقش عن المواد المقرصنة في الدردشة!",
    "play-shortcuts": "قائمة كاملة لإختصارات لوحة المفاتيح: [[Shortcut_Key_Reference]]",
    "pm": "لمراسلة أحدهم رسالة خاصة, إضغط على إسمهم في الدردشة\n أو في لوحة المستخدم في شاشة المستخدمين المتواجدين,\n ثم إضغط Start Chat.\nيمكنك أيضاً إستخدام الأمر /msg <إسم المستخدم> <رسالة>\nأو إستخدم /chat <إسم المستخدم> أو /query <إسم المستخدم>,\nوالذي سوف يفتح إطار منفصل في الدردشة.\nللرد السريع على آخر رسالة خاصة رُسِلَت إليك, يمكنك إسخدام\n/r <الرسالة>. لا تنسى إزالة الـ< >.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "[https://osu.ppy.sh/wiki/Performance_Points Performance Points] (pp) هو النظام الأساسي للتصنيف في osu!",
    "pp-rework-lazer": "",
    "preview": "نقطة المعاينة هي النقطة في الأغنية التي تبدأ بتشغيل الأغنية في شاشة الإختيار.\nنقطة المعاينة الصحيحة هي نقطة في الأغنية تعبر عنها بشكل جيد.\nإذهب إلى التوقيت في عمود الأدوات وأضغط على Set Current Position as Preview Point لإختيار النقطة.",
    "qat": "",
    "qualified": "",
    "ranked": "التصميم المصنف هو التصميم الذي وافق عليه مجتمع osu!.\nعندما تلعب تصميماً مصنفاً, النقاط المكتسبة منه تحتسب تجاه\nمحصلة النقاط.\nهذه التصاميم لديها مدرج المتصدرين الخاص بها, ويمكن تمييزه \nبأيقونة القلب.",
    "ranking-criteria": "للمعلومات على معايير التصنيف, فضلاً قم بزيارة الويكي : [[RC]]",
    "redname": "",
    "report": "المدراء ليسوا متوافرين في بعض الأحيان, إنهم إنس ولا يمكنهم مشاهدة الدردشة طوال اليوم. في حال لاحظت أن أحداً يفعل شيئاً غبياً ولا يوجد مدير ليوقفه عن حده, فضلاً إستعمل الأمر !report! سوف يأتي أحدٌ ما لمساعدتك عاجلاً.\nالرجاء عدم الإبلاغ في رسالة خاصة إلى BanchoBot, وإستخدام !report <المستخدم> <السبب>.",
    "report-abuse": "الرجاء عدم إرسال إبلاغات متعددة واحدة تلو الأخرى, فهذا لا يساعد على جلب العدالة بسرعة. حتى الإبلاغات بدون سبب.\nفي الواقع, من الممكن أن تتلقى الصمت لإرسال إبلاغات غير مرغوب فيها لمدراء الدردشة. ",
    "request": "أتبحث عن تصميم لتعدل فيه؟ إضغط  [https://osu.ppy.sh/p/beatmaplist&r=8 هنا] \nأو أكتب !request لرابط تصميم عشوائي.",
    "respect": "",
    "roll-abuse": "رجاءً لا تبالع في إستعمال أمر الـ!roll , الأغلب أنك ستتلقى عقوبة الصمت!",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "يمكنك عمل غرفتك الخاصة إن لم تتواجد الغرف.",
    "rp": "",
    "rules": "[https://osu.ppy.sh/wiki/Rules الشروط الرسمية]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "",
    "sb": "الإرشاد للـStoryboarding :  https://osu.ppy.sh/forum/t/1869\nكيف يمكنك إستعمال محرر الـStoryboard : https://osu.ppy.sh/forum/t/8145",
    "scorev2": "",
    "scoring": "كيف يتم حساب النقاط في osu ! :\n [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "الصمت يعني أنه لا يمكنك التواصل في الدردشة أو الرد في المنتدى, بإستثناء المساعدة التقنية.\nالصمت يبدأ بـ5 دقائق لأول مخالفة, ثم يتضاعف مع كل مخالفة تصدر.يمكن للمخالفات الكبيرة أن تضاعف الصمت أكثر من المخالفات السابقة.\nتلقى عقوبة الصمت للمخالفين لقوانين اللعبة, فإلتزم بقوانينها وستكن على ما يرام.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 أسئلة و أجوبة لتصميم المظاهر الخاصة.]",
    "sleep": "لا تسهر إلى ما بعد منتصف الليل. النوم مهم جدا!",
    "songs-not-appearing": "إذا لم تتواجد أغانيك في قائمة الإختيار . جرب الضغط على F5 .",
    "spaces": "",
    "spam": "الرسائل الغير مرغوب فيها يمكن تلقي الصمت بسببها , لا ترسلها.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "لمشاهدة لاعبٍ آخر, اكتب /watch <إسم المستخدم>, أو إضغط على إسمهم في الدردشة أو في لوحة المستخدم وأختر Start Spectating.\nكن متأكداً بأن لديك التصميم الذي يُلعب ذاته!",
    "spoiler": "",
    "status": "",
    "store": "[https://osu.ppy.sh/p/market مرحباً بك في سوق osu!] المكان الذي يمكنك فيه شراء بدلات osu! وأشياء أخرى رائعة!",
    "submit": "[https://osu.ppy.sh/wiki/Submission أسئلة و أجوبة رفع التصاميم]",
    "suck": "لا تقلق, ستتحسن مع التدريب.",
    "supporter": "كن [https://osu.ppy.sh/p/support مساعداً لـosu!].",
    "supporter-please": "",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "إقرأ [https://osu.ppy.sh/forum/t/87301 هذا] إن كنت تواجه صعوبات في لعب osu! باللوحة والقلم.",
    "tag": "في نمط اللعب المتعدد المشترك, يأخذ كل لاعبٍ دوره لضغط على مجموعة واحدة من الدوائر.\nلا يوجد خاسرٌ أو فائز, الجميع يلعب في نفس الفريق.\nفي التدويرات, يتشارك كل فرد من الفريق. لو فشل أحدهم في إكمال التدوير, فسيعاد العد للضغط الناجح. كل إضافة للاعب في التدويرات تضاف إلى نقاط الفريق.",
    "taiko": "طبل ياباني بارز في سلسلة الألعاب من Bandai-Namco. نمط الـTaiko يحاكي هذه الألعاب, ويجبر اللاعب على التركيز في إيقاع التصميم فقط. [https://osu.ppy.sh/forum/t/4363 هنا كيفية اللعب!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 تعليمات للتصميم لنمط Taiko]",
    "taiko-maps": "يمكنك إيجاد التصاميم الأصلية لـTaiko no Tatsujin من [https://osu.ppy.sh/forum/t/5397 هنا.]",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "من فضلكم, هل يمكنكم التكلم عن شيء أخر الأن؟",
    "training": "[https://osu.ppy.sh/forum/t/4280 تدريب James.]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 قائمة متجددة للبرامج التعليمية في التصميم وفي osu!.] \nيمكنك صنع المقطع الخاص بك ورفعه في الموضوع.\n[https://osu.ppy.sh/forum/t/60228 قائمة مفيدة للمصممين والمعدلين.]",
    "twc": "بطولة Taiko العالمية.\n[https://new.ppy.sh/wiki/Tournaments/TWC/2017/ إضغط الرابط للمزيد من العلومات.]",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "فضلاً إستخدم الرموز الأساسية في الغرف الغير محددة اللغة",
    "upload-cap": "لتقصير عدد التصاميم المرفوعة , وُضع حد لإبقاء المصممين \nيعملون في تصاميمهم المتواجدة .\nاللامساعدين لديهم حد 3 الى 6 تصاميم فعالة, \nوالمساعدين لديهم حد 5 - 10 تصاميم فعالة ,\nإعتماداً على عدد التصاميم المصنفة .",
    "utf8": "يرجى ضبط مشغل الـIRC الى رمز الـUTF-8 ليتمكن المستخدمون الآخرون من فهمك.",
    "videogames": "فضلاً ناقش الألعاب مثل : Touhou, Pokemon, SC, LoL, والألعاب الأخرى في #videogames.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "مرحباً بك في osu!. إذا كنت تواجه أي مشكلة أو لديك أي سؤال, فضلاً قم بزيارة #help. إستمتع بوقتك!",
    "when": "عندما يكون جاهزاً",
    "wiki": "[https://osu.ppy.sh/wiki/ الويكي لـosu!]",
    "wiki-link": "يمكنك إضافة روابط للويكي بكتابة إسم المدخل بين أقواس مزدوجة : [[ ]]\nكمثال, [[Kudosu]] تصنع بكتابة Kudosu بين [[ ]].",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 181 active FAQs (out of a possible 217) in the Arabic (العربية) language.",
    "completion": "The Arabic (العربية) FAQ as of last update is 83.41% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
