
strings = {
    "academy": "[http://www.youtube.com/user/osuacademy Кликни тук]\nза да отидете във осу!академията - Инструкции на\nвсички основни неща в осу!",
    "achievements": "",
    "add-skin": "",
    "advertising": "",
    "answer": "",
    "appeal": "",
    "approved": "",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "",
    "attention": "",
    "avatar-change": "",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "",
    "beatmapping": "",
    "beginner": "",
    "bn": "",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Ако наистина ти е скучно, намери нещо, което да правиш. Има достатъчно неща за правене онлайн.]\nСкуката не е извинение да цивриш и спамиш в osu!",
    "bug": "",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "",
    "caps": "Писането на главни букви се смята за викане. Следователно, е най-добре да намалите използването на Caps Lock, за да не изглежда грубо.",
    "change-modes": "",
    "change-name": "",
    "changelog": "",
    "chars": "",
    "charts": "",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "",
    "colour": "",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "",
    "comment": "",
    "comment-color": "",
    "conferencemode": "",
    "country-ranking": "",
    "critic": "",
    "ctb": "",
    "cutting-edge": "",
    "cwc": "",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "",
    "disable-this": "",
    "distance-snap": "",
    "dont-ask-peppy": "",
    "douche": "",
    "download": "",
    "drugs": "",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "",
    "english": "",
    "evade": "",
    "fallback": "",
    "faq": "",
    "feature": "",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "",
    "foul-play": "",
    "percolate": "",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "",
    "friends-list": "",
    "fullscreen": "",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "",
    "gmt": "",
    "english-help": "",
    "grammar": "",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "",
    "hacked": "",
    "hard": "",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "",
    "hitsound-library": "",
    "hl": "",
    "how-to-get-modded": "",
    "how-to-bn": "",
    "how-to-gmt": "",
    "how-to-play": "",
    "how-to-rank": "",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "",
    "ignore": "",
    "import": "",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "",
    "irc": "",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "",
    "kiai": "",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "",
    "lag": "",
    "language": "",
    "language-specific": "",
    "lazer": "",
    "level": "",
    "lines": "Моля научете се да пишете на една линия, за да не бъдете автоматично заглушени.",
    "link": "",
    "lobby": "Моля използвайте #lobby, за съобщаване и обсъждане на мултиплейър игри.",
    "localisation": "",
    "long-link": "",
    "long-text": "",
    "loved": "",
    "mac": "",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "",
    "mapping": "",
    "mat": "",
    "modhelp": "",
    "modqueue": "",
    "modreqs": "",
    "multi-invite": "",
    "multi-link": "",
    "multiaccounting": "",
    "multiplayer": "",
    "mwc": "",
    "nat": "",
    "news": "",
    "nightcore": "",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "",
    "nsfw": "",
    "osu": "",
    "osu!tablet": "",
    "osu!talk": "",
    "osucore": "",
    "osu!droid": "",
    "osumania": "",
    "osustream": "",
    "osz": "",
    "osz2": "",
    "owc": "",
    "peppy": "",
    "perfect": "",
    "ping": "Pong!",
    "pippi": "",
    "piracy": "",
    "play-shortcuts": "",
    "pm": "",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "",
    "pp-rework-lazer": "",
    "preview": "",
    "qat": "",
    "qualified": "",
    "ranked": "",
    "ranking-criteria": "",
    "redname": "",
    "report": "",
    "report-abuse": "",
    "request": "",
    "respect": "",
    "roll-abuse": "",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "",
    "rp": "",
    "rules": "",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "",
    "sb": "",
    "scorev2": "",
    "scoring": "",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "",
    "sleep": "",
    "songs-not-appearing": "",
    "spaces": "",
    "spam": "",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "",
    "spoiler": "",
    "status": "",
    "store": "",
    "submit": "",
    "suck": "Не се тревожи, ще се подобриш с упражнение.",
    "supporter": "",
    "supporter-please": "",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "",
    "tag": "",
    "taiko": "",
    "taiko-mapping": "",
    "taiko-maps": "",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Моля прекратете тази тема и говорете за нещо друго.",
    "training": "",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "",
    "twc": "",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "",
    "upload-cap": "",
    "utf8": "",
    "videogames": "",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "",
    "when": "",
    "wiki": "",
    "wiki-link": "",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 49 active FAQs (out of a possible 217) in the Bulgarian (Български) language.",
    "completion": "The Bulgarian (Български) FAQ as of last update is 22.58% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
