
strings = {

    "academy": "[http://www.youtube.com/user/osuacademy Feu clic ací] per a anar a la osu!academy - Tutorials per a allò més bàsic d'osu!",
    "achievements": "Pots aconseguir assoliments fent alguna cosa especial durant una cançó, com per exemple aconseguir un enorme combo o jugant tots els beatmaps en un paquet temàtic. El teu perfil mostra quins assoliments tens, i el que necessites conseguir. Alguns dels noms són pistes del que has de fer per a aconseguir l'assoliment! ",
    "add-skin": "Per a afegir una nova skin, descarrega-la i arrosega l'arxiu a la finestra d'osu!, o bé feu doble clic.",
    "advertising": "Anunciar contingut no relacionat amb osu! no està permés i pots ser silenciat.",
    "answer": "Si ningú no et contesta, és possible que ningú no sàpiga la resposta! Intenta buscar als fòrums si està relacionat amb osu!.",
    "appeal": "Si ets silenciat i creus que fou injust, contacta els administradors enviant un correu electrònic a accounts@ppy.sh explicant la teua situació. Recorda no obstant, els administradors són persones també! Si ets amable amb ells, hi haurà més probabilitats de que se solucione la situació, si és possible.",
    "approved": "Els maps Aprovats no poden ser rankejats per qualsevol raó - normalment són maps de més de 5 minuts i una sola dificultat, que compta amb marcador i tot! Sabràs que és un map Aprovat si en lloc d'un cor com a icona, hi és una flama. No obstant, aquesta categoria ja no s'utilitza i és obsoleta.  ",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire és el concurs de beatmapping d'alt nivell que retorna al 2017 amb una cançó de Helblinde. [http://osu.ppy.sh/news/156171674413 Fes-li una ullada aquí!]",
    "ask": "La millor manera d'obtenir una resposta és preguntar directament. Puc fer una pregunta? ja és per sí mateixa una pregunta. ",
    "attention": "Per favor, pots parar? Ningú no t'està fent cas...",
    "avatar-change": "[https://osu.ppy.sh/home/account/edit#avatar Ací] pots canviar el teu avatar.",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Hola! Sóc BanchoBot! Un plaer. Sóc un bot, no obstant, així que no puc mantenir una conversa amb tu :(",
    "beatmapping": "Aquí hi ha uns quants consells per al [https://osu.ppy.sh/wiki/Beatmapping beatmapping!]",
    "beginner": "Clica [http://t.co/f8CKexMv aquí] si estàs buscant maps per a principiants.",
    "bn": "El [[Beatmap Nomination Group]] és un grup de persones encarregades de ranquejar els maps i són responsables d'administrar la moderació dels maps en pendent (Pending) al cicle del rànquing. Pots parlar amb ells si tens qualsevol dubte o pregunta sobre el mapeig o el modeig. Són persones ocupades, així que evita molestar-los!",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY No té cap sentit dir-li als altres que estàs avorrit. Pren-te un descans o juga qualsevol altra cosa!] Estar avorrit no significa que pugues queixar-te o molestar en osu!.",
    "bug": "Si creus que has trobat un bug, indica-ho [https://osu.ppy.sh/forum/5 aquí]. Però assegura't que ningú no l'haja mencionat anteriorment. ",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Per favor no utilitzes una lletra majúscula al començament de cada paraula. Fa que tot el que escrius semble un desastre.",
    "caps": "Per favor no escrigues tot en majúscules. És molest i pots ser silenciat.",
    "change-modes": "Per a canviar el mode de joc, ve a la pantalla de selecció de cançons i clica a Mode al baix esquerra, o bé prem Ctrl + 1-4. Tin en compte que alguns maps son específics per a un mode.",
    "change-name": "Per a canviar el teu nom d'usuari, primer has de ser un [https://osu.ppy.sh/p/support osu! supporter]. Aleshores, podràs canviar el teu nom [https://store.ppy.sh/store/product/32 aquí]! Per a demanar una reversió al teu anterior nom d'usuari, canvis menors o ajuda, contacta amb accounts@ppy.sh amb els detalls.",
    "changelog": "Totes les actualitzacions al joc, Bancho i el lloc web poden ser trobades a la [https://osu.ppy.sh/p/changelog secció de canvis de desenvolupament]!",
    "chars": "Intenta evitar usar caracters unicode/no-estàndar en el xat general.",
    "charts": "Les osu!charts són paquets temàtics que ixen cada mes. Pots trobar-los [https://osu.ppy.sh/p/chart aquí!]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Groc pàl·lid: usuari normal | Groc: [https://osu.ppy.sh/p/support Supporter] | Roig: membre del [https://osu.ppy.sh/wiki/QAT QAT] o [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] | Blanc: tu mateix, o un missatge amb /me | Blau oscur: missatge privat | Verd: línia en la que has sigut mencionat | Rosa: BanchoBot",
    "colour": "",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Mentre que els comands de xat són de fàcil ús, no abuses d'ells. És considerat spam i pots ser silenciat.",
    "comment": "Si desitges fer un comentari en directe en la repetició d'un beatmap, prem Discussion i escriu alguna cosa, i prem Enter. \nSi no hi ha cap comentari en la pantalla, selecciona Show Comments en el panel de discussió.",
    "comment-color": "",
    "conferencemode": "",
    "country-ranking": "",
    "critic": "",
    "ctb": "Necessites ajuda amb osu!catch?  [https://osu.ppy.sh/wiki/Catch_the_Beat Aquí] tens la pàgina de la wiki!",
    "cutting-edge": "Cutting-edge és la versió experimental d'osu! usada per a provar noves característiques abans que siguen implementades en la versió estable. Pots canviar-ho en les opcions.\nLlegeix [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues aquest article] si tens qualsevol problema actualitzant el teu client.",
    "cwc": "Un torneig mundial d'osu!catch. Visita [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 aquesta pàgina] per a més informació.",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\r\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\r\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Tracta a la resta com desitjaries que et tractaren a tu. Si ets algun tipus de masoquista verbal, assumeix que ningú més ho és.",
    "disable-this": "",
    "distance-snap": "",
    "dont-ask-peppy": "",
    "douche": "Com a mesura de seguretat, intentar evitar l'ordre i el civisme via buits legals en les regles és castigable a discreció de l'equip administratiu. Una regla oficial diguent que no deuries ser un imbècil no deuria ser necessària perquè no sigues un imbècil, però per si de cas: no sigues un imbècil.",
    "download": "",
    "drugs": "",
    "dutch": "",
    "editor-shortcuts": "",
    "english": "",
    "evade": "",
    "fallback": "",
    "faq": "",
    "feature": "",
    "filipino": "",
    "filter": "",
    "foul-play": "",
    "percolate": "",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "",
    "friends-list": "",
    "fullscreen": "",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "",
    "gmt": "",
    "english-help": "",
    "grammar": "",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "",
    "hacked": "",
    "hard": "",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "",
    "hitsound-library": "",
    "hl": "",
    "how-to-get-modded": "",
    "how-to-bn": "",
    "how-to-gmt": "",
    "how-to-play": "",
    "how-to-rank": "",
    "hungarian": "",
    "hyperdash": "",
    "ignore": "",
    "import": "",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "",
    "irc": "",
    "italian": "",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "",
    "kiai": "",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "",
    "lag": "",
    "language": "",
    "language-specific": "",
    "lazer": "",
    "level": "",
    "lines": "",
    "link": "",
    "lobby": "",
    "localisation": "",
    "long-link": "",
    "long-text": "",
    "loved": "",
    "mac": "",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "",
    "mapping": "",
    "mat": "",
    "modhelp": "",
    "modqueue": "",
    "modreqs": "",
    "multi-invite": "",
    "multi-link": "",
    "multiaccounting": "",
    "multiplayer": "",
    "mwc": "",
    "nat": "",
    "news": "",
    "nightcore": "",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "",
    "nsfw": "",
    "osu": "",
    "osu!tablet": "",
    "osu!talk": "",
    "osucore": "",
    "osu!droid": "",
    "osumania": "",
    "osustream": "",
    "osz": "",
    "osz2": "",
    "owc": "",
    "peppy": "",
    "perfect": "",
    "ping": "Pong!",
    "pippi": "",
    "piracy": "",
    "play-shortcuts": "",
    "pm": "",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "",
    "pp-rework-lazer": "",
    "preview": "",
    "qat": "",
    "qualified": "",
    "ranked": "",
    "ranking-criteria": "",
    "redname": "",
    "report": "",
    "report-abuse": "",
    "request": "",
    "respect": "",
    "roll-abuse": "",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "",
    "rp": "",
    "rules": "",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "",
    "sb": "",
    "scorev2": "",
    "scoring": "",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "",
    "sleep": "",
    "songs-not-appearing": "",
    "spaces": "",
    "spam": "",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "",
    "spoiler": "",
    "status": "",
    "store": "",
    "submit": "",
    "suck": "",
    "supporter": "",
    "supporter-please": "",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "",
    "tag": "",
    "taiko": "",
    "taiko-mapping": "",
    "taiko-maps": "",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "",
    "training": "",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "",
    "twc": "",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "",
    "upload-cap": "",
    "utf8": "",
    "videogames": "",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "",
    "when": "",
    "wiki": "",
    "wiki-link": "",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 70 active FAQs (out of a possible 217) in the Catalan (Català) language.",
    "completion": "The Catalan (Català) FAQ as of last update is 32.26% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
