
strings = {
    "academy": "[https://www.youtube.com/user/osuacademy Klikni zde] pro zobrazení osu! akademie - Videonávody o všech věcech ohledně osu!",
    "achievements": "Dostáváš achievementy předvedením něčeho speciálního v průběhu skladby, jako např. získání velkého komba nebo hraním všech beatmapů v jednom tématovém balíčku. Tvůj profil ukazuje které acheivementy jsi dostal a které zatím ne. Některá jména achievementů jsou vodítka k tomu co musíš pro získání daného achievementu udělat!",
    "add-skin": "Pro přídání nového skinu ho stáhni z internetu a přetáhni do osu! okna nebo na něj dvakrát poklepej.",
    "advertising": "Zviditelňování obsahu, který se k osu! nijak nevzatahuje není dovoleno a může ti obstarat umlčení v chatu.",
    "answer": "Pokud ti nikdo neodpoví, je možné že nikdo nezná odpověď! Zkus hledat na fórech pokud se tvá otázka vztahuje k osu!",
    "appeal": "",
    "approved": "",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "Nejlepší způsob jak získat odpověd je se prostě položit otázku - nedává moc smysl pokládat otázku o pokládání otázky!",
    "attention": "Přestaň psát a drž se tématu.",
    "avatar-change": "Svůj avatar můžeš změnit na [https://osu.ppy.sh/home/account/edit#avatar here].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Ahoj! Jsem BanchoBot! Rád tě poznávám! Bohužel jsem bot, takže se s tebou nemůžu bavit. :(",
    "beatmapping": "Zde je pár užitečných tipů na [https://osu.ppy.sh/wiki/Beatmapping beatmapování!]",
    "beginner": "Klikni [https://osu.ppy.sh/forum/t/5456 sem], pokud hledáš mapy pro začátečníky..",
    "bn": "",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Nedává smysl ostatním říkat, že se nudíš. Dej si pauzu nebo si zkus zahrát něco jiného!]",
    "bug": "Chyby treba nahlásiť na [https://osu.ppy.sh/forum/5 fórume], nie v chate.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Prosím, nepoužívej velké písmeno na začátku každého slova - všechno pak vypadá katastrofálně.",
    "caps": "Nepiš prosím velkými písmeny - v chatu je to nežádoucí a můžeš za to být umlčen.",
    "change-modes": "",
    "change-name": "",
    "changelog": "",
    "chars": "Prosím vyhni se používání nestandartních/unicode znaků (např. čínština/japonština/česká diaktrika) v obecném chatu.",
    "charts": "",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Bledě žlutá: Normální uživatel | Žlutá: A [https://osu.ppy.sh/p/support Supporter] | Červená: Člen [https://osu.ppy.sh/wiki/QAT QAT] nebo [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nBílá: Ty nebo /me zpráva | Tmavě modrá: PM | Zelená: Řádek, kde jsi zmíněn (highlight) | Růžová: BanchoBot\n\n",
    "colour": "Bledě žlutá: Normální uživatel | Žlutá: A [https://osu.ppy.sh/p/support Supporter] | Červená: Člen [https://osu.ppy.sh/wiki/QAT QAT] nebo [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nBílá: Ty nebo /me zpráva | Tmavě modrá: PM | Zelená: Řádek, kde jsi zmíněn (highlight) | Růžová: BanchoBot\n\n",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "",
    "comment": "",
    "comment-color": "Normální uživatel může komentovat jen bíle. [https://osu.ppy.sh/p/support osu!supporter] si může zvolit barvu komentáře.",
    "conferencemode": "",
    "country-ranking": "",
    "critic": "",
    "ctb": "",
    "cutting-edge": "",
    "cwc": "Celosvětový osu! Catch the Beat turnaj. Podívej se na tuto [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 wiki stránku] pro více informací.",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Chovej se tak, jak chceš, aby se ostatní chovali k tobě. Jestli jsi nějaký druh slovního masochisty, předpokládej, že všichni ostatní nejsou.",
    "disable-this": "",
    "distance-snap": "",
    "dont-ask-peppy": "Neptej se pořád peppyho, je docela zaneprádněný. Klidně se ale zeptej kohokoliv jiného na tomto kanálu!",
    "douche": "",
    "download": "[https://osu.ppy.sh/p/beatmaplist Tu sťahuj mapy]\n[https://osu.ppy.sh/beatmaps/packs Official Beatmap Pack List]",
    "drugs": "Diskuze o drogách, nebo užívání drog je zkázána! Toto je all-ages hra.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "",
    "english": "",
    "evade": "",
    "fallback": "",
    "faq": "",
    "feature": "",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "",
    "foul-play": "",
    "percolate": "",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "",
    "friends-list": "",
    "fullscreen": "",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "",
    "gmt": "",
    "english-help": "",
    "grammar": "",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "",
    "hacked": "",
    "hard": "",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "",
    "hitsound-library": "",
    "hl": "",
    "how-to-get-modded": "",
    "how-to-bn": "",
    "how-to-gmt": "",
    "how-to-play": "",
    "how-to-rank": "",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "",
    "ignore": "",
    "import": "",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "",
    "irc": "",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "",
    "kiai": "",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "",
    "lag": "",
    "language": "",
    "language-specific": "",
    "lazer": "",
    "level": "",
    "lines": "Pokus se psát do jednoho řádku, pokud nechceš být potrestaný.",
    "link": "",
    "lobby": "",
    "localisation": "",
    "long-link": "",
    "long-text": "Nepíšte dlhé texty do chatu.",
    "loved": "",
    "mac": "[https://osx.ppy.sh Hraj osu! na svém Macu]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "",
    "mapping": "",
    "mat": "",
    "modhelp": "",
    "modqueue": "",
    "modreqs": "",
    "multi-invite": "Pokud chceš někoho pozvat do multiplayeru klikni na tú osobu a zvol Pozvat do hry",
    "multi-link": "",
    "multiaccounting": "Vytváření více učtú je přísne proti pravidlům.",
    "multiplayer": "Prosím nezviditelňuj multiplayerové hry na žádném jiném kanále než #lobby.",
    "mwc": "",
    "nat": "",
    "news": "",
    "nightcore": "",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Napíš /np aby sme vedeli čo počúvaš alebo hráš.",
    "nsfw": "",
    "osu": "",
    "osu!tablet": "",
    "osu!talk": "",
    "osucore": "",
    "osu!droid": "",
    "osumania": "",
    "osustream": "\n",
    "osz": "",
    "osz2": "",
    "owc": "osu! svetový šampionát. [https://osu.ppy.sh/wiki/OWC Pre více informací navštiv]",
    "peppy": "Ty to nevíš? peppy je [https://osu.ppy.sh/p/team osu! team] leader!",
    "perfect": "",
    "ping": "Pong!",
    "pippi": "",
    "piracy": "",
    "play-shortcuts": "",
    "pm": "",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "",
    "pp-rework-lazer": "",
    "preview": "",
    "qat": "",
    "qualified": "",
    "ranked": "",
    "ranking-criteria": "",
    "redname": "",
    "report": "",
    "report-abuse": "",
    "request": "",
    "respect": "",
    "roll-abuse": "",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "",
    "rp": "",
    "rules": "",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "",
    "sb": "",
    "scorev2": "",
    "scoring": "Takto sa počítaju body v osu! [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Skinning FAQ]",
    "sleep": "",
    "songs-not-appearing": "",
    "spaces": "",
    "spam": "Spam se trestá.Nerob to.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "",
    "spoiler": "",
    "status": "",
    "store": "",
    "submit": "",
    "suck": "",
    "supporter": "Staň sa [https://osu.ppy.sh/p/support osu! supporterom]",
    "supporter-please": "",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "",
    "tag": "",
    "taiko": "",
    "taiko-mapping": "",
    "taiko-maps": "",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "",
    "training": "",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "",
    "twc": "",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Prosím vyhni se používání nestandartních/unicode znaků (např. čínština/japonština/česká diaktrika) v obecném chatu.",
    "upload-cap": "",
    "utf8": "",
    "videogames": "",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "",
    "when": "Když to bude hotový.",
    "wiki": "",
    "wiki-link": "",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 82 active FAQs (out of a possible 217) in the Czech/Slovak (Česky/Slovensky) language.",
    "completion": "The Czech/Slovak (Česky/Slovensky) FAQ as of last update is 37.79% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
