
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy Klik her] for at se osu! academy - Video-guides til alt osu!-relateret. ",
    "achievements": "Du opnår milepæle ved at gøre noget specielt i en sang, som at få en lang combo, eller ved at spille alle beatmaps i en temapakke. Din profil viser, hvilke milepæle du har opnået, og hvilke du mangler at få. Nogle af navnene er ledetråde til hvad du skal gøre for at opnå milepælen.",
    "add-skin": "For at tilføje et nyt skin, download det og træk filen ind i osu! vinduet eller dobbeltklikke på det.",
    "advertising": "At reklamere for noget der ikke er osu!-relateret er ikke tilladt og kan føre til at du mister evnen til at chatte.",
    "answer": "Hvis der ikke er nogen der svarer dig, så er det muligt at ingen kender svaret! Prøv at søge på forummerne hvis det er osu!-relateret. ",
    "appeal": "Hvis du bliver muted fra chatten og mener at det ikke er retfærdigt, så send en privat meddelelse til en [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GM] hvor du forklarer situationen. Bare husk, at GMs også er mennesker. Hvis du er venlig mod dem, er de mere villige til at prøve at fjerne dit mute, hvis det er muligt. ",
    "approved": "En Approved beatmap er en beatmap som ikke kan blive rangeret, enten på grund af længde, sværhedsgrad, etc., men som er god nok til at få en pointtavle. Du kan se, om en beatmap er approved hvis ikonet er en flamme i stedet for et hjerte. ",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire, Den førende højniveau osu! beatmapping konkurrence vender tilbage i 2017 med en sang fra Helblinde. [https://osu.ppy.sh/home/news/2017-01-21-aspire-returns-for-2017 Tjek den ud her!]",
    "ask": "Den bedste måde at få et svar på er bare at stille dit spørgsmål - der er ingen grund til at spørge om man må stille et spørgsmål. ",
    "attention": "Vil du være venlig at spørge? Der er ingen der lytter til hvad du siger...",
    "avatar-change": "[https://osu.ppy.sh/home/account/edit#avatar Her] kan du ændre dit profilbillede.",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Hej! Jeg er BanchoBot! Godt at møde dig! Jeg er desværre en bot, så jeg kan ikke snakke rigtigt med dig :(",
    "beatmapping": "Læs wikien om [https://osu.ppy.sh/wiki/Beatmapping beatmapping] for at få gode råd!",
    "beginner": "Klik [https://osu.ppy.sh/forum/t/5456 her] for nogle gode beatmaps for begyndere. ",
    "bn": "Gruppen [[Beatmap Nomination Group]] består af personer som bestemmer bestämmer og administrerer rangerede beatmaps. De er ansvarlige for at håndtere hvilke beatmaps som skal være med i ranking-processen. Kontakt dem gerne hvis du har nogle spørgsmål, eller behøver råd, angående mapping eller modding. ",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Hvis du keder sig, så tag en pause og lav noget andet. Der er ingen grund til at skrive det i chatten.]",
    "bug": "Hvis du tror du har fundet en fejl (bug), så rapportér det [https://osu.ppy.sh/forum/5 her]. Vær bare sikker på, at problemet ikke er blevet rapporteret før. ",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Lad venligst være med at skrive kun i STORE BOGSTAVER - det er træls at læse, og kan få dig muted.",
    "caps": "Lad venligst være med at skrive kun i STORE BOGSTAVER - det er træls at læse, og kan få dig muted.",
    "change-modes": "For at skifte til andre spiltilstande, skal man gå til sangvalgsskærmen og enten klikken på Mode nederst til venstre eller bruger Ctrl + 1-4. Husk på at nogle beatmaps kun fungerer i én spiltilstand. ",
    "change-name": "For at ændre dit brugernavn skal du først blive en [https://osu.ppy.sh/p/support osu! supporter]. Derefter må du ændre dit navn [https://store.ppy.sh/store/product/32 her]!\nVil du anmode om at vende tilbage til dit gamle navn, lave små ændringer eller få hjælp, send en mail til accounts@ppy.sh med detaljer.",
    "changelog": "Alle opdateringer til spillet, Bancho og hjemmesiden kan findes i osu!'s  [https://osu.ppy.sh/p/changelog ændringslog!]",
    "chars": "Undgå venligst at bruge unicode / ikke-almindelige tegn i den generelle chat.",
    "charts": "osu! charts er temapakker som udgives hver måned. Du kan finde dem [https://osu.ppy.sh/p/chart her!]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Lys gul: En normal bruger | Gul: En [https://osu.ppy.sh/p/support Supporter] | Rød: En [https://osu.ppy.sh/wiki/QAT QAT] eller [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] \nHvid: Dig, eller en /me besked | Mørkeblå: En PM | Grøn: En linje der indeholder dit brugernavn (et highlight) | Pink: BanchoBot",
    "colour": "Lys gul: En normal bruger | Gul: En [https://osu.ppy.sh/p/support Supporter] | Rød: En [https://osu.ppy.sh/wiki/QAT QAT] eller [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] \nHvid: Dig, eller en /me besked | Mørkeblå: En PM | Grøn: En linje der indeholder dit brugernavn (et highlight) | Pink: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "ens chat kommandoer er nemme at bruge, så overbrug dem ikke. Dette er set som spam, og kan resultere i at du mister din ret til at tale i chatten.",
    "comment": "Hvis du gerne vil lave livekommentering på et beatmap-replay, så tryk på Discussion-knappen, skriv noget og tryk Enter!\nHvis der ikke allerede er nogen kommentarer på skærmen, tryk på Show Comments-boksen i Discussion-panelet.",
    "comment-color": "En normal bruger kan kun kommentere i hvidt. En [https://osu.ppy.sh/p/support supporter] kan ændre deres kommentarfarve.",
    "conferencemode": "Drukner du i Join/Quit beskeder i IRC? [http://wiki.xkcd.com/irc/Hide_join_part_messages Dette] kan være en hjælp!",
    "country-ranking": "Se pointtavlen over de forskellige lande [https://osu.ppy.sh/p/countryranking her]. ",
    "critic": "Hold kritikken konstruktiv. Foreslå alternativer og løsninger på problemer som du er bekymret over.",
    "ctb": "Har du brug for hjælp med Catch the Beat? [https://osu.ppy.sh/wiki/Catch_the_Beat Her] er wikisiden!",
    "cutting-edge": "Cutting egde er en eksperimental stream af osu! som bliver brugt til at teste nye tilføjelser inden de bliver live i det stabile build. Skift til det i indstillinger! Du kan [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues læse denne artikel] hvis du har nogen problemer med at opdatere din klient.",
    "cwc": "En verdensomspendende osu! Catch the Beat turnering. Se dette [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 wiki side] for mere information.",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Behandl andre som du ønsker at blive behandlet. Hvis du er en slags verbal masochist, så gå ud fra at ikke alle er det.",
    "disable-this": "Toggles tilføjes sjældent til funktioner. Du kan dog anmode om en via [https://osu.ppy.sh/forum/4 Feature Requests] forummet.",
    "distance-snap": "Distance Snap er et værktøj, som sørger for at afstanden mellem notes er korrekt, baseret på deres position på tidslinjen. Mere information:[[Distance_Snap]]",
    "dont-ask-peppy": "Spørg venligst ikke peppy hele tiden - han har ret travlt. Føl dig dog gerne fri til at spørge hvilken some helst anden i denne kanal!",
    "douche": "",
    "download": "Du kan hente flere beatmaps [https://osu.ppy.sh/p/beatmaplist her] eller beatmap-pakker [https://osu.ppy.sh/beatmaps/packs her].\nI tilfælde af, at du ikke ved hvordan man importere dem, kan du læse [https://i.imgur.com/kpX2N3m.jpg dette] for at finde ud af det!",
    "drugs": "Diskutér venligst ikke narkotika af nogen slags i osu! chat.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Læs [[Beatmapping#Keyboard_Shortcuts]] for at finde listen med editorens genvejstaster.",
    "english": "#english er til general diskussion omkring hvad som helst hvilket ikke har en dedikeret kanal. Ja, dette inkluderer anime/manga.",
    "evade": "At undgå en silence vil få din konto begrænset for en lang tidsperiode, hvis ikke udelukket på stedet!",
    "fallback": "Stable (Fallback) er en forældet version af osu! I forskell af Fallback, nyeste udgivelser fjerner DirectX-understøttelsen for at simplificere vores framework. Hvis du skiftede til denne version, er din PC for gammel, og vil ikke understøtte nyeste og fremtidige versioner.\nHvis du vil spille nuværende versioner nu, skal du opgradere dine grafikkort og de skal kunne undersøtte OpenGL, det mest krævet komponent for disse versioner. [https://osu.ppy.sh/wiki/GL_Support_Issues Klik her for at vide hvordan].",
    "faq": "Du anvender osu!Bancho FAQ systemet lige nu. osu! wiki: https://osu.ppy.sh/wiki",
    "feature": "Hvis du har en ide for spillet, kan du poste det i [https://osu.ppy.sh/forum/4 Feature Requests] subforum.",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "At undgå chat filtrene kan føre til en silence. Vær venlig ikke at gøre det.",
    "foul-play": "Vær venlig at rapportere snydere ved at bruge Report User knappen på deres profil, placeret [https://i.imgur.com/GG9xlLA.png her].\nVær sikker på at du skaffer så mange detaljer som muligt. Du kan også repport deres scorere ved et beatmaps top-50 highscores side.\nLAD VÆRD med at diskutere dette i offenlig chat, da det måske giver dig en silence.",
    "percolate": "At undgå chat filtrene kan føre til en silence. Vær venlig ikke at gøre det.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Denne artikel] vil hjælpe dig med at forstå mapping flow ",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "",
    "friends-list": "",
    "fullscreen": "",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "",
    "gmt": "",
    "english-help": "",
    "grammar": "",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "",
    "hacked": "",
    "hard": "",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "",
    "hitsound-library": "",
    "hl": "",
    "how-to-get-modded": "",
    "how-to-bn": "Hvis du gerne vil blive en BN, så se [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator her] - oftest vælges nye BNs af eksisterende BNs på grundlag af ting som kvaliteten af mods og aktivitet. ",
    "how-to-gmt": "",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#how-to-play Klik her for at lære hvordan man spiller!",
    "how-to-rank": "",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "",
    "ignore": "",
    "import": "",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "",
    "irc": "",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "",
    "kiai": "",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "[[Kudosu]]",
    "lag": "",
    "language": "",
    "language-specific": "",
    "lazer": "",
    "level": "",
    "lines": "",
    "link": "",
    "lobby": "",
    "localisation": "",
    "long-link": "",
    "long-text": "",
    "loved": "",
    "mac": "",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "",
    "mapping": "",
    "mat": "",
    "modhelp": "",
    "modqueue": "",
    "modreqs": "",
    "multi-invite": "",
    "multi-link": "",
    "multiaccounting": "",
    "multiplayer": "",
    "mwc": "",
    "nat": "",
    "news": "",
    "nightcore": "",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "",
    "nsfw": "",
    "osu": "",
    "osu!tablet": "",
    "osu!talk": "",
    "osucore": "",
    "osu!droid": "",
    "osumania": "",
    "osustream": "",
    "osz": "",
    "osz2": "",
    "owc": "",
    "peppy": "",
    "perfect": "",
    "ping": "Pong!",
    "pippi": "",
    "piracy": "",
    "play-shortcuts": "[[Shortcut_Key_Reference]]",
    "pm": "",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "",
    "pp-rework-lazer": "",
    "preview": "",
    "qat": "",
    "qualified": "",
    "ranked": "",
    "ranking-criteria": "",
    "redname": "",
    "report": "",
    "report-abuse": "",
    "request": "",
    "respect": "",
    "roll-abuse": "",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "",
    "rp": "",
    "rules": "",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "",
    "sb": "",
    "scorev2": "",
    "scoring": "",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "",
    "sleep": "",
    "songs-not-appearing": "",
    "spaces": "",
    "spam": "",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "",
    "spoiler": "",
    "status": "",
    "store": "",
    "submit": "",
    "suck": "",
    "supporter": "",
    "supporter-please": "",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "",
    "tag": "",
    "taiko": "",
    "taiko-mapping": "",
    "taiko-maps": "",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "",
    "training": "",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "",
    "twc": "",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Undgå venligst at bruge unicode / ikke-almindelige tegn i den generelle chat.",
    "upload-cap": "",
    "utf8": "",
    "videogames": "",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "",
    "when": "",
    "wiki": "",
    "wiki-link": "",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 98 active FAQs (out of a possible 217) in the Danish (Dansk) language.",
    "completion": "The Danish (Dansk) FAQ as of last update is 45.16% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
