
strings = {
    "academy": "",
    "achievements": "Du erhältst Erfolge durch das Erfüllen bestimmter Aufgaben, z.B. durch eine hohe Combo oder das Spielen aller Beatmaps eines Theme Packs. Du siehst deine Erfolge in deinem Profil. Bei den meisten sind die Bedingungen offensichtlich, alle anderen musst selbst herausfinden.",
    "add-skin": "Um einen neuen Skin hinzuzufügen, lade ihn herunter und ziehe die Datei in das osu! Fenster oder doppelklicke ihn.",
    "advertising": "Werbung für Dinge, die nichts mit osu! zu tun haben, ist verboten. Zuwiderhandlungen haben eine Chat-Sperre zur Folge.",
    "answer": "Sollte keine Reaktion auf deine Frage kommen, weiß wohlmöglich niemand die Antwort oder niemand will dir antworten.",
    "appeal": "Wenn du glaubst, dass du eine ungerechtfertigte Chat-Sperre bekommen hast, schicke eine E-Mail an accounts@ppy.sh. Falls dir recht gegeben wird, wird die Chat-Sperre komplett rückgängig gemacht.\nChat-Sperren werden nicht willkürlich verteilt. Du solltest also SEHR gute Gründe angeben können.",
    "approved": "Eine Map mit dem Status Approved sind meist aus verschiedensten Gründen nicht Ranked, erfüllt aber dennoch alle anderen qualitativen Standards - und besitzen auch eine Rangliste! Man erkennt sie daran, dass sie statt eines Herzens eine Flamme als Icon besitzen.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire, ein hochrangiger osu! Beatmapping-Wettbewerb, kehrt im Jahr 2017 mit einem Song von Helblinde zurück. [http://osu.ppy.sh/news/156171674413 Mehr dazu hier!]",
    "ask": "Frage nicht, ob du eine Frage stellen kannst. Frag einfach.",
    "attention": "Niemanden interessiert es, was du gerade sagst. Hör besser auf.",
    "avatar-change": "[https://osu.ppy.sh/home/account/edit#avatar Du kannst deinen Avatar hier ändern].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Hi, ich bin der BanchoBot! Ich bin der Hauptserver von osu!. Allerdings kann ich keine richtige Unterhaltung führen. :(",
    "beatmapping": "Lies [[Beatmapping]], um ein paar allgemeine Tipps zu erhalten.",
    "beginner": "[https://osu.ppy.sh/forum/t/5456 Training für Anfänger]\n",
    "bn": "Mitglieder des [[DE:Beatmap Nomination Group]] sind für das Ranken von Beatmaps zuständig, sowie verantwortlich für das Modden von Pending Beatmaps während des Rankingzyklus. BNs sind Leute, die man anschreiben kann, wenn es um das Modding geht oder um Meinungen und Tipps bezüglich Mapping oder Gameplay herholen zu möchten.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Wenn dir wirklich so langweilig ist, such dir eine andere Beschäftigung. Im Internet gibt es so viel zu sehen, also versuche dein Glück woanders.]",
    "bug": "Bitte melde Fehler im [https://osu.ppy.sh/forum/5 Forum], nicht im Chat.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "So Zu Schreiben Ist Nicht Cool, Richtig Oder Vorteilhaft Für Irgendjemanden. Tu dir selbst einen Gefallen und hör damit auf - und entferne die Shift- und Capslock Taste von deiner Tastatur.",
    "caps": "Alles durchgängig großzuschreiben ist im Chat unerwünscht und kann geahndet werden.",
    "change-modes": "Um den Spielmodus zu ändern, gehe in das Liederauswahlmenü und klicke entweder unten links auf Modus oder benutze Strg + 1-4. ",
    "change-name": "Um deinen Benutzernamen zu ändern, musst du erst ein [https://osu.ppy.sh/p/support osu! Supporter] werden.\n[https://store.ppy.sh/store/product/32 Lies hier], wenn du deinen Namen ändern möchtest!",
    "changelog": "Kürzliche Neuerungen und Fehlerbehebungen sind im [https://osu.ppy.sh/p/changelog Changelog] verzeichnet.",
    "chars": "Die übertriebene Benutzung von Unicode-Zeichen, etwa zur Erstellung von Emoticons ist nicht erlaubt.",
    "charts": "osu! Charts erscheinen jeden Monat. Sie sind eine Zusammenstellung aus Maps, die jeden Monat nominiert werden oder in ein bestimmtes Thema passen. Du kannst [https://osu.ppy.sh/p/chart Charts hier] finden.",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Weiß: Du. Hellgelb: Normaler Nutzer. Gelb: [osu.ppy.sh/p/support osu! Supporter]. Rot: [https://osu.ppy.sh/wiki/People/The_Team/Nomination_Assessment_Team NAT] oder [https://osu.ppy.sh/wiki/People/The_Team/Global_Moderation_Team GMT].\nBlau: Eine private Nachricht. Grün: Zeile, die deinen Nutzernamen enthält (Highlight). Rosa: BanchoBot.",
    "colour": "Weiß: Du. Hellgelb: Normaler Nutzer. Gelb: [https://osu.ppy.sh/p/support osu! Supporter]. Rot: [https://osu.ppy.sh/wiki/DE:QAT QAT] oder [https://osu.ppy.sh/wiki/DE:GMT GMT].\nBlau: Eine private Nachricht. Grün: Zeile, die deinen Nutzernamen enthält (Highlight). Rosa: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Bitte spamme keine Chat-Kommandos wie /np oder /me. Der Chat wird dadurch nur unnötig zugespammt und es kann ein Silence daraufhin folgen.",
    "comment": "Um eine Beatmap zu kommentieren, klicke auf den Knopf Discussion, während du ein Replay schaust.\nWähle eine der drei Boxen, um auszuwählen, was genau du kommentieren willst, schreibe deinen Kommentar und drücke Enter.\nAktiviere die Checkbox Show Comments, um die Kommentare anzuzeigen. Manche Maps haben so viele Kommentare, dass man fast nichts mehr sehen kann.",
    "comment-color": "Die Farbe eines normalen Users ist weiß. Supporter können ihre Farbe individuell ändern.",
    "conferencemode": "Wie man Join-/Quit-Nachrichten in den meisten IRC-Clients abschaltet, erfährst du [http://wiki.xkcd.com/irc/Hide_join_part_messages hier]. ",
    "country-ranking": "[https://osu.ppy.sh/p/countryranking Länderranglisten]",
    "critic": "Wenn du deine Meinung äußerst, tu dies bitte konstruktiv. Etwas einfach nur als scheiße zu bezeichnen, führt unweigerlich zu Konsequenzen und hilft keinem.",
    "ctb": "[https://osu.ppy.sh/forum/t/7405&p=60690 Catch the Beat-FAQ]",
    "cutting-edge": "Cutting Edge ist ein Update, dass den alten osu!test Client ersetzt.\n[https://osu.ppy.sh/wiki/Help_Center#Updater_Issues Diesen Artikel] kannst du dir durchlesen, sofern du Probleme beim Updaten hast.",
    "cwc": "Ein weltweites Catch the Beat-Turnier. [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 Hier erfährst du mehr.]",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Behandle andere, wie du selbst behandelt werden möchtest. Falls du jedoch ein sprachlicher Masochist bist, gehe davon aus, dass es alle anderen nicht sind.",
    "disable-this": "Nein, ich werde keinen Ausschalter für dieses oder jenes Feature hinzufügen, solange es keinen negativen Einfluss auf die Performance oder ERNSTHAFTEN Einfluss auf die Spielbarkeit hat.",
    "distance-snap": "Einen konstanten Abstand zwischen den Hitcircles kannst du am Einfachsten mit der Funktion Distance Snapping erreichen. Du findest sie in der Ecke rechts unten im Editor. Mit dem Mausrad kannst du den Abstand anpassen.",
    "dont-ask-peppy": "Die gerade gestellte Frage kann von fast jedem in diesem Channel beantwortet werden. Bitte sieh davon ab, peppy das nächste Mal zu fragen.",
    "douche": "Nur weil es in den Regeln nicht explizit genannt wurde, ist es trotzdem verboten Recht und Ordnung zu stören und kann bestraft werden.\nEine offizielle Regel kein Arschloch zu sein ist nicht notwendig, um vorauszusetzen, dass ihr keine Arschlöcher sein sollt.\nAber für den Fall der Fälle: Seid keine Arschlöcher!",
    "download": "[https://osu.ppy.sh/p/beatmaplist Lade dir hier Beatmaps herunter!]\n[https://osu.ppy.sh/beatmaps/packs Liste von Beatmap Packs], falls du Probleme beim Importieren hast, schau dir [http://i.imgur.com/kpX2N3m.jpg diesen Guide an].",
    "drugs": "Diskussionen über Drogen oder andere Betäubungsmittel sind nicht gestattet.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Liste mit Tastenkürzeln für den Editor: [[Beatmapping#Keyboard_Shortcuts]]",
    "english": "If you want to speak English, please go to #english. #german is a German-only channel.",
    "evade": "Versuch unter keinen Umständen, deine Chat-Sperre zu umgehen. Dafür kannst du komplett gesperrt werden!",
    "fallback": "Stable (Fallback) ist eine veraltete Version von osu!. Im Gegensatz zu Fallback werden neuere Versionen den DirectX-Support entfernen, um unser Framework zu vereinfachen. Falls du zu dieser Version gewechselt wirst, ist dein PC zu alt und wird die neusten und zukünftige Versionen nicht unterstützen.\nFalls du aktuellere Versionen spielen möchstest, upgrade deine Grafikkarte zu einer, die OpenGL unterstützt, die am meisten benötigte Schnittstelle für diese Versionen.\n[https://osu.ppy.sh/wiki/GL_Support_Issues Klicke hier um zu mehr zu erfahren].",
    "faq": "Du benutzt gerade das FAQ-System von osu!Bancho.\n[https://osu.ppy.sh/forum/t/353291 Häufig gestellte Fragen], \nosu! Wiki: https://osu.ppy.sh/wiki",
    "feature": "Vorschläge für Features gehören in das Unterforum [https://osu.ppy.sh/forum/4 Feature Requests].",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Bitte versuche nicht die Wortfilter bewusst zu umgehen.",
    "foul-play": "Du kannst Cheater melden indem du die Melde-Funktion auf dessen Profil benutzt. Du findest den Button [https://i.imgur.com/GG9xlLA.png hier]. Gebe bitte so viele Informationen wie möglich an. Du kannst ercheatete Highscores auch direkt bei den Top 50 Highscores auf der Seite des Beatmaps melden.",
    "percolate": "Bitte versuche nicht die Wortfilter bewusst zu umgehen.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/forum/t/86329 Dieser Thread wird dir helfen Flow beim Mappen besser zu verstehen.]",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Benutze das Kommando /addfriend <username>, um jemanden als Freund hinzuzufügen.\nAlternativ kannst du im Online-Panel (F9) auf einen Spieler klicken und Add as Friend wählen oder Add as Friend im Profil des Spielers benutzen.",
    "friends-list": "Um eine Liste deiner Freunde im Spiel zu sehen, drücke F9 und ändere den Filter oben auf Freunde.\nDu kannst auch eine vollständige Liste deiner Freunde, online und offline, auf der Webseite sehen, indem du auf Settings klickst. Dafür musst du natürlich eingeloggt sein.",
    "fullscreen": "Du kannst in den Optionen unter der Schaltfläche Grafik zwischen Fenster- und Vollbildmodus wechseln.\nAlternativ kannst du aber auch mit der Tastenkombination Alt + Enter zwischen Fenster- und Vollbildmodus wechseln.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Viele Begriffe werden im [https://osu.ppy.sh/wiki/Glossary osu! Glossar] erklärt.",
    "gmt": "Das [https://osu.ppy.sh/wiki/DE:GMT Global Moderation Team], kurz GMT, ist eine Gruppe von Nutzern, die osu! am Laufen halten. Sie besitzen rote Namen im Chat und grüne Namen im Forum. Sie moderieren das Forum und den Chat.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 So einfach, selbst du schaffst das... glaube ich.]",
    "grammar": "Gib dir Mühe dabei, korrekte Grammatik zu verwenden. Gegen ein paar Tipp- oder Zeichensetzungsfehler hat niemand was, aber du solltest es vermeiden, wie in einer SMS zu schreiben, wenn du nicht wie ein Idiot wirken möchtest.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Du weißt nicht, wie das Spiel funktioniert? Möchtest du mehr über Modden und Mappen erfahren?\n[https://osu.ppy.sh/forum/t/73377 Hier] findest du die Antworten.",
    "hacked": "Wenn du denkst, dass du gehackt wurdest, dann sende bitte eine E-Mail an accounts@ppy.sh, um es zu melden.\nFehlerhaftes Melden kann zu einer Löschung deines Accounts führen.",
    "hard": "Git gud, skrub.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Du kannst dem #help Channel beitreten, wenn du ein Problem bezüglich osu! hast. Lies dir vorher [https://osu.ppy.sh/forum/t/658727 diesen Thread] durch - vielleicht wurde dein Problem dort ja schon genannt?\nIn #help darfst du auf Deutsch fragen, bevorzugt wird aber Englisch, damit dich dort auch jeder verstehen kann.",
    "hitsound-library": "Geh auf [https://osu.ppy.sh/forum/p/164927 diese Seite], um alternative Hitsounds für deine Map zu bekommen.",
    "hl": "Beschwere dich nicht, wenn du wegen eines Wortes gehighlighted wirst, dass du selbst hinzugefügt hast. Wenn es dir nicht gefällt, entferne das Wort wieder. Ansonsten schalte die Benachrichtigungen in den Optionen aus.",
    "how-to-get-modded": "Wenn du wissen möchtest, wie du Mods für deine Maps erhältst, lese hier:\n[[Getting_Your_Map_Modded]]",
    "how-to-bn": "BNs werden aufgrund von Modding Qualität und Aktivität gewählt. Falls du dich fragst, wie du ein BN werden kannst, dann lese dir [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator das hier] durch.",
    "how-to-gmt": "Global Moderators werden auserwählt und kümmern sich um die Moderation für die Community. Wenn du helfen möchtest, dann kannst du dies machen, indem du mit dem !report Kommando Fehlverhalten meldest.",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F Klicke hier, um zu erfahren, wie man spielt!]",
    "how-to-rank": "[https://osu.ppy.sh/forum/t/210406 Klicke hier, um zu erfahren, wie du deine Map gerankt bekommst!]",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Ein Hyperdash taucht dann auf, wenn eine Frucht rot leuchtet. Du wirst dich schneller als sonst bewegen. Der Effekt läuft ab, sobald du die nächste Frucht fängst oder verfehlst.",
    "ignore": "Um einen User zu ignorieren, schreib /ignore und den Usernamen dahinter. Du kannst die Nachrichten von diesem User nicht mehr sehen und keine PMs empfangen.\nSchreibst du /unignore (username) oder beendest du osu!, wird der Block aufgehoben. Um jemanden dauerhaft zu ignorieren, schau dir [http://help.ppy.sh/article/141/how-do-i-completely-block-another-user-from-contacting-me diesen Guide] an.",
    "import": "[http://i.imgur.com/kpX2N3m.jpg Klicke hier, um zu erfahren, wie du Beatmaps in osu! importieren kannst!]",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Wenn du einen Timing-Abschnitt benötigst, der das Timing nicht verändert, sondern beispielsweise nur die Lautstärke der Hitsounds ändert, setze im Timing-Menü (F6) des Editors für den betreffenden Timing-Abschnitt die Checkbox Inherit previous timing settings.\nWenn du die BPM verdoppeln oder halbieren möchtest, solltest du ebenfalls untergeordnete Timing-Abschnitte verwenden.",
    "irc": "IRC-Server: irc.ppy.sh:6667\nPasswort: https://osu.ppy.sh/p/irc\nWeitere Informationen findest du [https://osu.ppy.sh/wiki/DE:Internet_Relay_Chat hier].",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Du kannst Deine Tastenbelegung in der Kategorie Tastatur der Optionen anpassen. Um die Tasten und das Layout der Tasten in osu!mania zu ändern, benutze den osu!mania-Layout-Knopf.",
    "kiai": "Der 'Kiai Time' Modus ist ein Stilmittel in Beatmaps, den du im Timing Panel einstellen kannst. Kiai Times aktivieren diverse visuelle Effekte um eine bestimmte Stelle des Liedes epischer wirken zu lassen. Benutze es sparsam!",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Erhalte [[Kudosu]], indem du die Beatmaps anderer Nutzer moddest.\n",
    "lag": "Lag ist ein ziemlich allgemeiner Begriff, der für fast alles verwendet werden kann, was nicht so ganz richtig läuft.\nWenn du dich über Lag beschwerst, gib bitte an, WO der Lag auftritt und WAS genau passiert (langsame Übertragungsgeschwindigkeit? Grafikfehler? Niedrige Framerate? Eingabe-Lag?).\nFalls es bestimmte Voraussetzungen gibt, unter denen der Lag auftritt, sind diese ebenfalls wichtig. Stelle sicher, dass gleichzeitig nichts anderes auf deinem Computer läuft, was die Performance beeinträchtigen könnte.",
    "language": "Bitte seid nett und höflich im Chat.",
    "language-specific": "Bitte verwende die richtige Sprache in den Chats, denen du betrittst. Schriftzeichen zu umgehen ist hier keine Ausnahme.",
    "lazer": "osu!lazer is der Codename für die zukunftige Open-Source-Version des osu!. Erfahren Sie [https://github.com/ppy/osu hier] mehr darüber!",
    "level": "Dein Level steigt mit deinem Total Score. Bei diesem werden alle Punkte gezählt, die du auf Maps mit Ranglisten erreicht hast, selbst wenn du die Map nicht geschafft hast. Dein Level wird automatisch steigen, während du osu! spielst. Level haben keine tiefere Bedeutung.",
    "lines": "Bitte beziehe in Betracht nicht so viele Zeilen zu benutzen, wenn du es auch nur bei einer Zeile belassen kannst. Sowas kann zu einem Silence führen.",
    "link": "Um einen Link zu erzeugen, benutze folgendes Format: [Adresse Text]. So wie in diesem [https://osu.ppy.sh/ Beispiel]. Vergesse das http:// nicht. Missbrauch dieser Funktion wird bestraft (Verlinken von nicht jugendfreien Material, mit dem versteckten Text Leute highlighten).",
    "lobby": "Verwende #lobby zum Werben deiner Lobby und nutze #multiplayer für deine Unterhaltungen dort. Und ja, in #lobby kannst du auch auf Deutsch schreiben.",
    "localisation": "[https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24Hier ist das osu! Lokalisierungsprojekt zu finden.]",
    "long-link": "Bitte füge keine langen Links in den Chat ein!\nBenutze die [Link Text] Formel, wenn es unbedingt sein muss.",
    "long-text": "Bitte füge keine langen Texte in den Chat ein.",
    "loved": "Loved ist eine neue Beatmapkategorie. Sie beinhaltet Beatmaps, die unter normalen Bedingungen den Ranked-Status nicht erreichen würden.  [https://osu.ppy.sh/news/151925254083 Klicke hier für mehr Informationen!]",
    "mac": "[https://osx.ppy.sh So verwendest du osu! auf deinem Mac.]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Mapper sind beschäftigte Menschen und das Mappen kostet viel Zeit und Arbeit. Warum versuchst du nicht selber etwas zu mappen?",
    "mapping": "[https://osu.ppy.sh/forum/t/50050 Tutorials zum Mappen.]",
    "mat": "Das 'Mapping Assistance Team' war eine Gruppe handerlesener Modder, welche hilfreiche Beiträge zur Erstellung und Verbesserung von Beatmaps leisteten und dem BAT behilflich waren.\nRIP MAT 23.04.2013",
    "modhelp": "Gehe zu #mapping für all deine Beatmap Modding Probleme/Fragen.",
    "modqueue": "Schaue dich [https://osu.ppy.sh/forum/60 hier] nach Modding Queues um.",
    "modreqs": "Bitte benutzt #modreqs für Modding Anfragen jeglicher Art. Bitte beachtet, dass BATs und MATs nicht immer Zeit haben und sie bereits viel zu tun haben könnten. Stell also bitte sicher, dass du auch reguläre Nutzer nach Mods fragst. Danke.",
    "multi-invite": "Wähle den Nutzernamen des Spielers aus und wähle die entsprechende Option, um jemanden zu deiner Lobby einzuladen, während du das Spiel leitest.",
    "multi-link": "[https://osu.ppy.sh/community/forums/topics/338482 Wie man einen direkten Link zu deinem Mehrspieler Raum erstellt]",
    "multiaccounting": "[https://osu.ppy.sh/wiki/Help_Center#Can_I_make_more_than_one_account_for_a_fresh_start_or_play_on_another_person.27s_account.3F Mehrere Accounts pro Benutzer zu erstellen ist streng verboten!]",
    "multiplayer": "Bitte wirb für deine Lobby ausschließlich in #lobby. Wenn es keine Spieler gibt, warum spielst du nicht erst einmal alleine und versuchst es später erneut?",
    "mwc": "Offizielles, weltweites osu!mania Turnier. Für mehr Informationen, klicke [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 hier].",
    "nat": "Das [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] moderiert die Beatmap-Nominatoren und überwacht den Beatmap-Ranking-Prozess.\nSie sind verantwortlich für die Bewertung aktueller und angehender Beatmap-Nominatoren, sowie für die Schlichtung von Beatmap-Vetos und anderen Mapping-/Modding-bezogenen Streitigkeiten.",
    "news": "",
    "nightcore": "Genieße deine Lieblingsbeatmap im Nightcore-Style! Doppelter Linksklick oder ein Rechtsklick auf den DoubleTime-Mod, um den Nightcore-Mod aktivieren!",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Schreibe /np, um Leuten mitzuteilen, welches Lied du gerade hörst oder welche Beatmap du gerade spielst.",
    "nsfw": "Nicht jugendfreie Inhalte sind in jedem Chat zu jeder Tageszeit streng verboten. Sie werden meist ohne Vorwarnung geahndet.",
    "osu": "#osu ist dafür da, um über osu! zu reden. Bitte diskutiert Gameplaybezogenes dort, nicht in diesem Channel!",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 Der osu!tablet Thread] - Lese ihn für alle Informationen über das Tablet und die Bestellmöglichkeiten.",
    "osu!talk": "osu!talk ist eine Talkshow, die von den Usern deadbeat und ztrot veranstaltet wird. Dabei werden die verschiedensten User der Community interviewt oder auch über Events wie den Worlds Cups unterhalten. Jede Folge findet auf den Teamspeak-Server osu.corin.me statt, für weitere Details, schau [https://osu.ppy.sh/forum/t/225111 hier nach].",
    "osucore": "Ein Aprilscherz von 2011. Alle Maps wurden standardmäßig auf DoubleTime gesetzt und ihre Tonhöhe wurde erhöht. Dieses Verhalten wurde später als Nightcore-Mod fest eingebaut.",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] ist ein Port des Originals für Androidgeräte. Die App befindet sich aufgrund schlechter Rezensionen und Inaktivität der offiziellen Entwickler seit 2015 nicht mehr im Google Play Store.",
    "osumania": "Bitte verwende #osumania für Diskussionen über osu!mania.",
    "osustream": "[http://www.osustream.com osu!stream ist osu! für iOS Geräte!]",
    "osz": "Hierbei handelt es sich um das Dateiformat für Beatmaps. osz-Dateien müssen immer von osu! selbst augepackt werden, um mögliche Fehler zu vermeiden.",
    "osz2": "Das neue Dateiformat für Beatmaps. osz2-Dateien muss nicht mehr entpackt werden. Alle beinhalteten Dateien können unabhängig voneinander verschlüsselt, aktualisiert oder gestreamt werden.",
    "owc": "Ein weltweites osu!-Turnier.\n[https://osu.ppy.sh/wiki/OWC Lies hier für mehr Informationen.]",
    "peppy": "Wie kannst du das nicht wissen? peppy ist der [https://osu.ppy.sh/p/team osu! team] Leiter!",
    "perfect": "Kein SS geschafft? Dieser Mod startet die Map automatisch beim kleinsten Fehler neu! Du findest diesen Mod, wenn du SuddenDeath doppelklickst.",
    "ping": "Pong!",
    "pippi": "Das Maskottchen von osu!\nPippi-don ist die Taiko-Version von Pippi.",
    "piracy": "Es ist nicht gestattet, im Chat nach raubkopierten Materialien zu fragen oder zu Seiten zu linken, die diese bereitstellen.",
    "play-shortcuts": "Vollständige Liste der Tastenkürzel: [[DE:Shortcut_Key_Reference]]",
    "pm": "Um jemanden eine private Nachricht zu schreiben, benutze /msg <Nutzername> <Nachricht>, um eine neue Schaltfläche zu öffnen. Du kannst auch auf den gewünschten Benutzer klicken, um einen neuen Chat zu starten.\nUm schnell auf die letzte Private Nachricht zu antworten, kannst du den Befehl /re <Nachricht> verwenden.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "[https://osu.ppy.sh/wiki/DE:Performance_Points Performance Points (pp) sind das Standardmaß für das Ranking in osu!]",
    "pp-rework-lazer": "",
    "preview": "Ein Preview-Point (Vorschaupunkt) ist die Stelle eines Liedes, die im Menü ertönt, wenn die betreffende Map ausgewählt wird.\nEin guter Preview-Point ist eine Stelle im Lied, die die Map gut repräsentiert, z.B. der Anfang des Refrains. \nIm Editor unter Timing und Set Current Position as Preview Point zu finden.",
    "qat": "",
    "qualified": "Beatmap Nominators nominieren Maps als qualifiziert, sodass ihr dazu bereit seid, darauf zu Ränge zu bekommen, jedoch ohne Performance Points.\nFalls die Maps eine Woche lang qualifiziert ist und keine Fehler aufweist, wird sie eingestuft. (Ranked)\nWenn dies nicht der Fall ist, werden die Scores gelöscht und wird wieder ausstehend.",
    "ranked": "Eine Ranked Beatmap ist eine Beatmap, die von der Community zugelassen wurde.\nWenn du eine Ranked Beatmap spielst, geht sie in deine Wertung ein. Sie besitzen eine eigene Rangliste und haben ein Herz-Symbol.",
    "ranking-criteria": "[https://osu.ppy.sh/wiki/DE:Ranking_Criteria Ranking Kriterien]",
    "redname": "Benutzer mit einem roten Namen sind entweder [https://osu.ppy.sh/wiki/People/The_Team/Global_Moderation_Team Moderatoren] oder Mitglieder des [https://osu.ppy.sh/wiki/People/The_Team/Nomination_Assessment_Team NAT].",
    "report": "Um Fehlverhalten im Chat oder im Forum oder betrügerisches Spielen zu melden, benutze den Befehl !report <Nutzername> <Beschreibung>",
    "report-abuse": "Bitte vermeide es, viele Reports mehrfach hintereinander zu senden. Das gleiche gilt für unbegründete Reports.\nMissbrauch dieser Funktion wird bestraft!",
    "request": "Suchst du nach etwas zum Modden? Klicke  [https://osu.ppy.sh/p/beatmaplist&r=8 hier] oder schreibe !request für einen zufälligen Link zu einer Map.",
    "respect": "Bitte verhalte dich respektvoll gegenüber anderen Spielern.",
    "roll-abuse": "Bitte übertreibe es nicht mit dem !roll Befehl - Das wird sehr wahrscheinlich in einem Silence für dich enden.",
    "romaji": "Bitte verwenden Sie keine Romaji (Romanized Japanese) übermäßig. Sie könnten zum Schweigen gebracht werden.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Sollte keiner vorhanden sein, kannst du einen eigenen Raum erstellen.",
    "rp": "Du darfst gerne Rollenspiele in den geeigneten osu! Channel spielen aber pass auf, dass du die anderen Leute im Channel nicht zu sehr störst.",
    "rules": "[https://osu.ppy.sh/forum/t/117460 Forum- und Chat-Regeln]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "Von Zeit zu Zeit wird osu! von einer DDoS-Attacke angegriffen. Während dieser Zeit könnte Bancho instabil oder unerreichbar sein.\nInformiere dich bitte auf Twitter  [https://twitter.com/osustatus @osustatus] oder [https://status.ppy.sh hier].",
    "sb": "Storyboarding Anleitung: https://osu.ppy.sh/forum/t/1869\nWie man den Storyboard Editor bedient: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "scorev2 ist das neue Punktesystem, welches den Score für alle Spielemodi auf eine Million begrenzt, ausgenommen Spinner und Mods. Es ändert auch das Verhalten der Slider, so haben diese das selbe Timing wie einzelne Noten.",
    "scoring": "Wie osu! die Punktzahl berechnet: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Ein Silence bedeutet, dass du weder im Chat schreiben noch im Forum posten kannst, außer im Technical-Support-Board. Silences beginnen bei 5 Minuten und verdoppeln sich bei weiteren Vergehen. Größere Vergehen werden höher bestraft. \nSilences werden für grobes Fehlverhalten vergeben, also benimm dich - dann ist alles okay.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Skinning-FAQ]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Halte dich nicht bis 4 Uhr früh mit osu! wach. Schlaf ist wichtig!]",
    "songs-not-appearing": "Wenn deine Lieder nicht im Auswahlmenü erscheinen, versuche F5 zu drücken.",
    "spaces": "Bitte setzen Sie keine Leerzeichen zwischen die Buchstaben, Ihre Ästhetik lässt den Chat chaotisch aussehen und kann zur Stille führen.",
    "spam": "Im Chat zu spammen ist nervtötend und wird bestraft.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Um einen anderen Spieler zu beobachten, schreibe /watch <Benutzername>, oder klicke auf ihren Namen im Chat oder Benutzermenü und klicke Beobachten starten. Stelle sicher, dass du die gleiche Beatmap wie der Spieler hast!",
    "spoiler": "Bitte vermeide es Details über Filmen, Serien, Spielen, etc. zu spoilern. Dies könnte ansonsten zu einem Silence führen.",
    "status": "Für osu! Statusinformationen, besucht den [https://twitter.com/osustatus osu!status Twitter feed].",
    "store": "[https://osu.ppy.sh/p/market Willkommen im osu! Markt], der Ort, an dem du großartige osu! T-Shirts und andere tolle Sachen kaufen kannst!",
    "submit": "[https://osu.ppy.sh/wiki/Submission Beatmap Submission FAQ]\n(in englisch)",
    "suck": "Hey, jeder war mal am Anfang schlecht, genau so wie du! Aber lass den Kopf nicht hängen: Du wirst schon mit der Zeit besser, einfach dranbleiben!",
    "supporter": "Werde ein [https://osu.ppy.sh/p/support osu! Supporter]",
    "supporter-please": "Bitte fordere andere Leute nicht zum Supporten auf, wenn sie nicht wollen. Damit gehst du anderen nur auf die Nerven. [https://osu.ppy.sh/p/support Warum kaufst du es dir nicht selber?]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "[https://osu.ppy.sh/forum/t/87301 Lies das], wenn du Probleme damit hast osu! mit einem Tablet zu spielen.",
    "tag": "Im Tag-Multiplayer-Modus wechseln sich alle Spieler ab. Es gibt keinen Gewinner oder Verlierer, da jeder im selben Team spielt. Spinner werden von allen gleichzeitig bewältigt.\nWenn ein Spieler den Spinner nicht beenden kann, wird die Kombo zurückgesetzt. Der Spinnerbonus von jedem Spieler wird auf den Endpunktestand gutgeschrieben.",
    "taiko": "Eine japanische Trommel, die in einer Spielserie von Bandai-Namco benutzt wird.\nosu!s Taiko-Modus simuliert diese Spiele, indem die Bewegung von Circle zu Circle eliminiert wird und nur der Rhythmus der Beatmap zählt.\n[https://osu.ppy.sh/forum/t/4363 Wie es gespielt wird!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Taiko Mapping Handbuch]",
    "taiko-maps": "Du kannst authentische Taiko no Tatsujin Maps  [https://osu.ppy.sh/forum/t/5397 hier] finden.",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Könntest du bitte das Thema wechseln und über irgendetwas anderes reden?",
    "training": "[https://osu.ppy.sh/forum/t/4280 James Training]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 Liste von aktuellen Tutorials für osu! und Mapping.] Du kannst gerne deinen eigenen Guide erstellen und es im Topic posten. [https://osu.ppy.sh/forum/t/60228 Liste von praktischen Guides für Mapper/Modder]",
    "twc": "Ein weltweites osu! Taiko Turnier.\n[https://new.ppy.sh/wiki/Tournaments/TWC/2017/ Lies hier für mehr Informationen.]",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Bitte vermeide das Benutzen von Nicht-standardisierten Zeichen im öffentlichen Chat. Diesen können von manchen Usern nicht richtig gelesen werden und für Probleme im Client sorgen.",
    "upload-cap": "Alle Benutzer haben ein Limit an Maps, die sie hochladen dürfen.\nAbhängig davon, wieviele deiner Maps bereits gerankt sind, darfst du zwischen 3 und 6 nicht gerankte Maps besitzen.\nMaps im Graveyard zählen nicht zum Limit. Supporter besitzen ein höheres Limit (5-10).",
    "utf8": "Bitte setze deinen IRC Clienten auf UTF-8 der Codeseite, damit dein Text von allen osu! Spielern und IRC-Benutzern verstanden wird.",
    "videogames": "Bitte diskutiere Themen wie Touhou, Pokémon, SC, LoL, Visual Novels und andere videospielbezogene Themen in #videogames. ",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Willkommen in osu! Wenn du Fragen oder Probleme haben solltest, besuche bitte #german oder #help. Viel Spaß!",
    "when": "Dann, wenn es soweit ist.",
    "wiki": "https://osu.ppy.sh/wiki/ - lasst es groß und mächtig werden.",
    "wiki-link": "Du kannst Wiki-Seiten verlinken, indem du den Namen des Wiki-Eintrags in Doppelklammern legst: [[ ]]\nBeispielsweise wird der Wiki-Link [[DE:Kudosu]] erstellt, indem du DE:Kudosu zwischen [[ ]] schreibst.",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 213 active FAQs (out of a possible 217) in the German (Deutsch) language.",
    "completion": "The German (Deutsch) FAQ as of last update is 98.16% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
