
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy Κλικ εδώ] για να δείτε το osu! academy - Μαθήματα βίντεο για ό,τι σχετίζεται με το osu!",
    "achievements": "Παίρνετε επιτεύγματα κάνοντας κάτι ειδικό σε ένα τραγούδι, όπως να κάνεις τεράστιο combo, ή να παίξεις όλα τα maps σε ένα θεματικό πακέτο. Το προφίλ σου δείχνει ποια επιτεύγματα έχεις κατακτήσει και ποια απομένουν. Μερικά από τα ονόματα είναι στοιχεία για το τι πρέπει να κάνεις για να πάρεις το επίτευγμα!",
    "add-skin": "Για να προσθέσετε ένα νέο skin, κατεβάστε το και σύρετε το αρχείο στο παράθυρο του osu! ή κάντε το διπλό κλικ.",
    "advertising": "Η διαφήμιση προϊόντων/περιεχομένου άσχετου με το osu! δεν επιτρέπεται και μπορεί να τιμωρηθεί με σίγαση.",
    "answer": "Αν κανένας δεν σας απαντήσει, είναι πιθανό να μην ξέρει κανένας την απάντηση! Δοκιμάστε να ψάξετε τα φόρουμ αν πρόκειται για θέματα του osu!",
    "appeal": "Αν όντως καταλήξετε με σίγαση και νομίζετε ότι ήταν άδικο, επικοινωνήστε με τους διαχειριστές στέλνοντας ένα e-mail στο accounts@ppy.sh εξηγώντας την κατάσταση. Μόνο θυμηθείτε, οι διαχειριστές είναι κι αυτοί άνθρωποι! Αν είστε ευγενικοί, είναι πιο πιθανό να προσπαθήσουν περισσότερο για να αφαιρέσουν την σίγαση, αν είναι δυνατόν.",
    "approved": " ",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "Ο καλύτερος τρόπος για να πάρεις μια απάντηση είναι να κάνεις την ερώτηση σου - δεν υπάρχει λόγος να ρωτάς αν μπορείς να κάνεις μια ερώτηση!",
    "attention": "Σταμάτα να γράφεις, και μείνε στο θέμα.",
    "avatar-change": "Μπορείς να αλλάξεις το avatar σου [https://osu.ppy.sh/home/account/edit#avatar εδώ].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Χαίρετε! Είμαι το BanchoBot! Χάρηκα για την γνωριμία! Είμαι bot όμως, οπότε δεν μπορώ να ανοίξω συζήτηση μαζί σου :(",
    "beatmapping": "Εδώ είναι μερικές χρήσιμες συμβουλές για το [https://osu.ppy.sh/wiki/Beatmapping beatmapping!]",
    "beginner": "Κλικάρετε [https://osu.ppy.sh/forum/t/5456 εδώ] αν ψάχνετε για maps για αρχάριους.",
    "bn": "",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Δεν υπάρχει λόγος να λες στους άλλους πως έχεις βαρεθεί. Κάνε ένα διάλειμμα, ή προσπάθησε να παίξεις κάτι άλλο!]",
    "bug": "Αν νομίζετε οτι βρήκατε ένα bug, δηλώστε το [https://osu.ppy.sh/forum/5 εδώ]. Μόνο βεβαιωθείτε ότι κανένας άλλος δεν έχει αναφέρει το πρόβλημα πρην από εσάς.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Παρακαλώ μην χρησιμοποιείτε κεφαλαία γράμματα στην αρχή κάθε λέξης που γράφετε -  κάνει ό,τι γράφετε να μοιάζει καταστροφικό.",
    "caps": "Παρακαλώ μην γράφετε τα πάντα με κεφαλαία - είναι ανεπιθύμητο στο chat, και μπορεί να τιμωρηθείτε.",
    "change-modes": "Για να αλλάξετε στους άλλους τρόπους παιχνιδιού, μεταβείτε στην οθόνη επιλογής τραγουδιού και είτε κάντε κλικ στο Mode στο κάτω μέρος αριστερά ή χρησιμοποιήστε τα πλήκτρα Ctrl + 1-4. Λάβετε υπόψη ότι ορισμένα maps είναι ειδικά για συγκεκριμένα μόνο modes. ",
    "change-name": "Για να αλλάξεις το username σου, πρέπει πρώτα να γίνεις [https://osu.ppy.sh/p/support υποστηρικτής του osu!]. Έπειτα, μπορείς να αλλάξεις το όνομά σου [https://store.ppy.sh/store/product/32 εδώ]! Για να ζητήσεις επαναφορά στο παλιό σου όνομα χρήστη, μικρο-αλλαγές, ή βοήθεια, παρακαλώ στείλε ένα e-mail στο accounts@ppy.sh με λεπτομέρειες. ",
    "changelog": "Όλες οι ενημερώσεις του παιχνιδιού, του Bancho και της ιστοσελίδας μπορούν να βρεθούν στο osu! development [https://osu.ppy.sh/p/changelog changelog!]",
    "chars": "Παρακαλούμε αποφύγετε τη χρήση Unicode / μη-τυπικών χαρακτήρων στο γενικό chat.",
    "charts": "",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Χλωμό Κίτρινο: Ένας φυσιολογικός χρήστης. | Κίτρινο: Ένας [https://osu.ppy.sh/p/support Υποστηρικτής] | Κόκκινο: Ένα μέλος του [https://osu.ppy.sh/wiki/QAT QAT] ή του [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] | Άσπρο: Εσύ, ή ένα μήνυμα /me | Σκούρο Μπλέ: Ένα ΠΜ | Πράσινο: Μια γραμμή στην οποία αναφέρθηκε το όνομά σου (ένα highlight) | Ροζ: Το BanchoBot",
    "colour": "Χλωμό Κίτρινο: Ένας φυσιολογικός χρήστης. | Κίτρινο: Ένας [https://osu.ppy.sh/p/support Υποστηρικτής] | Κόκκινο: Ένα μέλος του [https://osu.ppy.sh/wiki/QAT QAT] ή του [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] | Άσπρο: Εσύ, ή ένα μήνυμα /me | Σκούρο Μπλέ: Ένα ΠΜ | Πράσινο: Μια γραμμή στην οποία αναφέρθηκε το όνομά σου (ένα highlight) | Ροζ: Το BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Ενώ οι εντολές συζήτησης είναι για ευκολία στην χρήση, παρακαλώ μην τις καταχράστε. Αυτό θεωρείται spam, και μπορεί να οδηγήσει σε σίγαση.",
    "comment": "",
    "comment-color": "Ένας φυσιολογικός χρήστης μπορεί να σχολιάσει μόνο με άσπρο χρώμα. Ένας [https://osu.ppy.sh/p/support υποστηρικτής] μπορεί να προσαρμόσει το χρώμα του σχολίου του. ",
    "conferencemode": "Σε πλημμυρίζουν τα μηνύματα Συνδέθηκε/Αποσυνδέθηκε στο IRC; [http://wiki.xkcd.com/irc/Hide_join_part_messages Αυτό] ίσως να σε βοηθήσει!",
    "country-ranking": "",
    "critic": "Παρακαλώ κρατήστε την κριτική εποικοδομητική. Προτείνετε εναλλακτικές λύσεις ή τρόπους για να διορθώσετε τα προβλήματα που σας ανησυχούν.",
    "ctb": "Χρειάζεστε βοήθεια με το Catch the Beat; [https://osu.ppy.sh/wiki/Catch_the_Beat Εδώ είναι] η σελίδα του στο wiki!",
    "cutting-edge": "",
    "cwc": "Ένα παγκόσμιο τουρνουά osu! Catch the Beat. Δες αυτή την [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 σελίδα του wiki]για περισσότερες πληροφορίες.",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\r\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\r\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Να φέρεσαι στους άλλους όπως θες να σού φέρονται. Αν είσαι κάποιο είδος λεκτικού μαζοχιστή, υπόθεσε πως οι άλλοι δεν είναι.",
    "disable-this": "",
    "distance-snap": "",
    "dont-ask-peppy": "Παρακαλώ μην ρωτάτε τον peppy όλη την ώρα - είναι αρκετά απασχολημένος. Μη διστάσετε όμως να ρωτήσετε οποιονδήποτε άλλον σε αυτό το κανάλι! ",
    "douche": "",
    "download": "Μπορείς να κατεβάσεις περισσότερα beatmaps [https://osu.ppy.sh/p/beatmaplist?q= εδώ] ή beatmap packs [https://osu.ppy.sh/beatmaps/packs εδώ].\r\nΣε περίπτωση που δεν ξέρετε πώς να τα εισάγετε, μπορείτε να διαβάσετε [http://i.imgur.com/kpX2N3m.jpg αυτό] και να μάθετε!",
    "drugs": "Η συζήτηση ναρκωτικών και η χρήση τους οπουδήποτε στο osu! είναι απαγορευμένη. Πρόκειται για παιχνίδι για όλες τις ηλικίες.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Διαβάστε [[Beatmapping#Keyboard_Shortcuts]] για να βρείτε την λίστα με τις συντομεύσεις του editor.",
    "english": "Το #english είναι για γενικές συζητήσεις για οτιδήποτε το οποίο δεν διαθέτει αποκλειστικό κανάλι. Ναι, αυτό περιλαμβάνει anime/manga. Και τρένα.",
    "evade": "Η αποφυγή μίας σίγασης είναι λόγος για να έχετε τον λογαριασμό σας περιορισμένο για αρκετό χρονικό διάστημα, αν όχι επ' αόριστον. Μην το κάνετε.",
    "fallback": "",
    "faq": "Αυτή τη στιγμή χρησιμοποιείτε το σύστημα FAQ του osu!Bancho.\nosu!wiki: https://osu.ppy.sh/wiki",
    "feature": "Αν έχεις κάποια ιδέα για αυτό το παιχνίδι, δημοσίευσέ την στο [https://osu.ppy.sh/forum/4 Feature Requests] subforum.\r\nΒεβαιωθείτε πως έχετε διαβάσει τα [https://osu.ppy.sh/forum/t/454006 forum guidelines] πρώτα!",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Η αποφυγή των φίλτρων του chat μπορεί να (και πιθανότατα θα) οδηγήσει σε σίγαση. Μην το κάνετε.",
    "foul-play": "",
    "percolate": "Η αποφυγή των φίλτρων του chat μπορεί να (και πιθανότατα θα) οδηγήσει σε σίγαση. Μην το κάνετε.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Το άρθρο αυτό] θα σας βοηθήσει να καταλάβετε τη ροή του mapping.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Για να προσθέσετε έναν χρήστη ως φίλο, γράψτε /addfriend ακολουθώντας με το όνομα του χρήστη.\nΕπιπλέον, μπορείτε να κάνετε κλικ στο πλαίσιο του χρήστη στην λίστα με τους συνδεδεμένους χρήστες (πατήστε F9) ή το όνομά του στο chat και επιλέξτε Προσθήκη ως φίλο.\nΜπορείτε επίσης να τους προσθέσετε μέσω του προφίλ τους, κάνοντας κλικ στο Προσθήκη ως φίλο.",
    "friends-list": "Για να δείτε μια λίστα των συνδεδεμένων φίλων σας στο παιχνίδι, πατήστε το πλήκτρο F9 και στη συνέχεια, αλλάξτε το φίλτρο πάνω στους Φίλους.\r\nΜπορείτε επίσης να δείτε μια πλήρη λίστα των φίλων σας, τόσο online όσο και offline, στην ιστοσελίδα κάνοντας κλικ στις Ρυθμίσεις. (Θα πρέπει να είστε συνδεδεμένοι, φυσικά.)",
    "fullscreen": "Μπορείτε να αλλάξετε το αν το παιχνίδι παίζει σε Παράθυρο ή Πλήρη Οθόνη κάτω από την ενότητα Γραφικά στο μενού των Ρυθμίσεων.\nΜπορείτε επίσης να κάνετε εναλλαγή προς και από πλήρη οθόνη με τα Alt + Enter στο πληκτρολόγιό σας.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Μπορείτε να βρείτε άφθονες ορολογίες στο osu! [[glossary]].",
    "gmt": "Το [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team], εν συντομία [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT], είναι μια ομάδα χρηστών που βοηθούν το osu! να λειτουργήσει. Έχουν κόκκινα ονόματα στο chat και πράσινα ονόματα στα forums.These guys help moderate the forum and chat. Αυτοί οι άνθρωποι βοηθούν στην διατήρηση της ηρεμίας στο forum και στο chat.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Διάβασε, αναθεώρησε, ευχαριστήσου.]",
    "grammar": "Βάλτε τα δυνατά σας να χρησιμοποιήσετε σωστή γραμματική. Λίγα λάθη στην ορθογραφία ή στην στίξη είναι αποδεκτά, αλλά σας παρακαλώ μην χρησιμοποιείτε στενογραφία ή textspeak. Θα σας κάνει να φαίνεστε χαζοί.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Δεν ξέρεις πώς να παίξεις; Θες να εξερευνήσεις τον κόσμο του mapping και του modding; [https://osu.ppy.sh/wiki/Guides Εδώ] θα βρεις όλες τις απαντήσεις.",
    "hacked": " ",
    "hard": "",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "",
    "hitsound-library": "",
    "hl": "",
    "how-to-get-modded": "",
    "how-to-bn": "",
    "how-to-gmt": "",
    "how-to-play": "",
    "how-to-rank": "",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "",
    "ignore": "",
    "import": "",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "",
    "irc": "",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "",
    "kiai": "",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "",
    "lag": "",
    "language": "",
    "language-specific": "",
    "lazer": "",
    "level": "",
    "lines": "Παρακαλώ προσπαθήστε να κρατάτε τις φράσεις σας σε μία γραμμή για να αποφύγετε την σίγαση.",
    "link": "",
    "lobby": "Χρησιμοποιήστε το κανάλι #multiplayer του δωματίου σας για άλλες συζητήσεις. Παρακαλείστε να μην διαφημίζετε παιχνίδια για πολλούς παίκτες σε οποιοδήποτε άλλο κανάλι εκτός από το #lobby.",
    "localisation": "",
    "long-link": "",
    "long-text": "",
    "loved": "",
    "mac": "",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "",
    "mapping": "",
    "mat": "",
    "modhelp": "",
    "modqueue": "",
    "modreqs": "",
    "multi-invite": "",
    "multi-link": "",
    "multiaccounting": "",
    "multiplayer": "Παρακαλώ διαδώστε το δωμάτιό σας στο #lobby. Αν δεν υπάρχουν άλλοι παίκτες διαθέσιμοι, παίξτε λίγο μόνοι σας και δοκιμάστε αργότερα.",
    "mwc": "",
    "nat": "",
    "news": "",
    "nightcore": "",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "",
    "nsfw": "",
    "osu": "",
    "osu!tablet": "",
    "osu!talk": "",
    "osucore": "",
    "osu!droid": "",
    "osumania": "",
    "osustream": "",
    "osz": "",
    "osz2": "",
    "owc": "",
    "peppy": "",
    "perfect": "",
    "ping": "Pong!",
    "pippi": "",
    "piracy": "",
    "play-shortcuts": "",
    "pm": "",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "",
    "pp-rework-lazer": "",
    "preview": "",
    "qat": "",
    "qualified": "",
    "ranked": "",
    "ranking-criteria": "",
    "redname": "",
    "report": "",
    "report-abuse": "",
    "request": "",
    "respect": "",
    "roll-abuse": "",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "",
    "rp": "",
    "rules": "",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "",
    "sb": "",
    "scorev2": "",
    "scoring": "",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Silence (σίγαση) σημαίνει σιωπή, δηλαδή δεν θα μπορείτε να μιλήσετε σε chat ή να γράψετε σε φόρουμ, εκτός από την Τεχνική Βοήθεια (Technical Support). Οι σιγάσεις ξεκινούν από 5 λεπτά για την πρώτη ποινή και μετά διπλασιάζονται για κάθε καινούργια ποινή. Μεγάλες ποινές μπορούν να υπερδιπλασιάσουν τον χρόνο απο την προηγούμενη σίγαση. Αυτές δίνονται λόγω κακής συμπεριφοράς, οπότε ακολουθήστε τους κανόνες και θα είστε εντάξει.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "",
    "sleep": "",
    "songs-not-appearing": "",
    "spaces": "",
    "spam": "Παρακαλώ μην σπαμάρετε. Είναι ενοχλητικό και συνήθως οδηγεί σε σίγαση.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "",
    "spoiler": "Απαγορεύεται να κάνετε spoil anime, σειρές, manga, doujin, κ.λπ., η παράβαση μπορεί να οδηγήσει σε σίγαση. ",
    "status": "",
    "store": "[http://store.ppy.sh/ Καλώς ορίσατε στο μαγαζί του osu!], το μέρος στο οποίο μπορείτε να αγοράσετε φοβερά πράγματα osu! ",
    "submit": "[https://osu.ppy.sh/wiki/Submission Υποβολή Beatmap FAQ]",
    "suck": "Το osu! έχει μια μεγάλη καμπύλη εκμάθησης - θα γίνετε καλύτεροι με την πάροδο του χρόνου, γι' αυτό συνεχίστε να προσπαθείτε!",
    "supporter": "Γίνετε κι εσείς [https://osu.ppy.sh/p/support υποστηρικτής του osu!]! Θα πάρετε μια σειρά από επιπλέον παροχές, και θα βοηθήσετε στην υποστήριξη του development team έτσι ώστε να είναι πιο παραγωγικοί!",
    "supporter-please": "",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "",
    "tag": "",
    "taiko": "",
    "taiko-mapping": "",
    "taiko-maps": "",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Παρακαλώ μπορείτε να αλλάξετε θέμα και να μιλήσετε για κάτι άλλο;",
    "training": "",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "",
    "twc": "",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Παρακαλώ αποφύγετε τη χρήση Unicode/μη-τυπικών χαρακτήρων στο γενικό chat. Μπορείτε να τιμωρηθείτε με σίγαση.",
    "upload-cap": "",
    "utf8": "Παρακαλώ ορίστε το IRC client σας να χρησιμοποιεί κωδικοποίηση UTF-8, έτσι ώστε να μπορείτε επαρκώς να διαβάζετε και να στέλνετε ευανάγνωστα μηνύματα σε άλλους χρήστες.",
    "videogames": "Θέματα σχετικά με videogames μπορούν να συζητηθούν στο #osu, αλλά αν ενοχλεί το chat ή υπάρχει σε εξέλιξη παραπάνω από μια συζήτηση, παρακαλώ πηγαίντε στο #videogames. ",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Καλώς ήρθες στο osu! Αν έχεις κάποιο πρόβλημα ή ερώτηση που πρέπει να απαντηθεί, ρώτα τους καλούς ανθρώπους στο #help! Κράτα το chat φιλικό και καλή διασκέδαση! :D ",
    "when": "Όταν είναι έτοιμο.",
    "wiki": "[https://osu.ppy.sh/wiki/ Το osu! Wiki] - Κάντε το φοβερό!",
    "wiki-link": "",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 109 active FAQs (out of a possible 217) in the Greek (Ελληνικά) language.",
    "completion": "The Greek (Ελληνικά) FAQ as of last update is 50.23% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
