
strings = {
    "academy": "[http://www.youtube.com/user/osuacademy Click here] to go to the osu!academy - Tutorials on all the basics of osu!",
    "achievements": "You get achievements by performing something special during a song, like getting a huge combo or playing all the beatmaps in a theme pack. Your profile shows what achievements you've got, and what you need to get. Some of the names are clues to what you need to do to get the achievement!        ",
    "add-skin": "If the file you've downloaded is in .osk format, drag the file to the osu! window or double click it.\nFor .rar/.zip files, extract the contents into a single folder and move it to your Skins folder. Make sure to do this while osu! is closed.",
    "advertising": "Advertising content unrelated to osu! is not allowed and may get you silenced.\nThis includes third-party chat servers of any kind such as Discord and Teamspeak.",
    "answer": "If no one answers you, it's possible no one knows the answer! Try searching on the forums if it's osu!-related.",
    "appeal": "If you do end up getting silenced and think it was unfair, contact the administrators by sending an e-mail to accounts@ppy.sh explaining your situation. Just remember though, administrators are people too! If you be nice to them, they're more likely to try their best to clear the silence, if it's possible.",
    "approved": "Approved beatmaps can't be ranked for some reason or another - generally are maps with a length of 5 minutes or more with a single difficulty, sometimes 2-5, with a scoreboard and everything! They're no longer in circulation but you'll know if it's an approved beatmap if the map icon is a flame instead of a heart.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "[[https://osu.ppy.sh/wiki/Contests#aspire Aspire]] was the premier high-level osu! beatmapping contest carried out in 2016–2020.",
    "ask": "The best way to get an answer is just asking your question directly! - Can I ask something? is already a question.",
    "attention": "Can you please stop? No one really listens to what you're saying...",
    "avatar-change": "You can change your avatar [https://osu.ppy.sh/home/account/edit#avatar here].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Hello there! I'm BanchoBot! Nice to meet you.\nI'm a bot though, so I can't really have a conversation with you :(",
    "beatmapping": "Here's a few helpful tips on [https://osu.ppy.sh/wiki/Beatmapping beatmapping!]",
    "beginner": "Click [https://osu.ppy.sh/forum/t/5456 here] if you're looking for beginner maps. You may also be interested in [https://osu.ppy.sh/community/forums/topics/75291 touchscreen-friendly] beatmap packs.",
    "bn": "Members of the [https://osu.ppy.sh/wiki/en/People/The_Team/Beatmap_Nominators Beatmap Nominators] are in charge of ranking beatmaps and is responsible for managing the moderation of pending beatmaps into the ranking cycle.\nYou can talk to them if you have any questions or advice request about mapping or modding. They are busy people, so please avoid spamming them!",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY There's no point in telling others that you're bored. Take a break or try playing something else!] Being bored doesn't mean you can spam or complain of anything on osu!",
    "bug": "If you think you've found a bug, report it [https://osu.ppy.sh/forum/5 here]. Just make sure no one else posted your problem beforehand.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Please don't use a capital letter at the start of every word - it makes everything you write look like a trainwreck.",
    "caps": "Please don't write in all capital letters - it's unwanted in chat, and it can get you silenced.",
    "change-modes": "To change to the other game modes, go to the song select screen and either click on Mode at the bottom left or use Ctrl + 1-4. Keep in mind that some maps are mode-specific!",
    "change-name": "To change your username, you must first become an [https://osu.ppy.sh/p/support osu! supporter]. Then, you may change your name [https://store.ppy.sh/store/product/32 here]!\nTo request a revert to your old username, minor changes, or help, please e-mail accounts@ppy.sh with details.",
    "changelog": "All updates to the game (including Lazer), wiki, and the website can be found in the osu! [https://osu.ppy.sh/home/changelog changelog!]",
    "chars": "Please avoid using unicode/non-standard characters in general chat.",
    "charts": "osu! charts are themed packs which get released every month. You can find them [https://osu.ppy.sh/p/chart here!]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Pale Yellow: A normal user | Yellow: A [https://osu.ppy.sh/p/support Supporter] | Red: A member of [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team NAT] or [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nWhite: Yourself, or a /me message | Dark Blue: A private message | Green: A line where you are mentioned (a highlight) | Pink: BanchoBot",
    "colour": "Pale Yellow: A normal user | Yellow: A [https://osu.ppy.sh/p/support Supporter] | Red: A member of [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team NAT] or [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nWhite: Yourself, or a /me message | Dark Blue: A private message | Green: A line where you are mentioned (a highlight) | Pink: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "While chat commands are for ease of use, please don't overuse these. This is seen as spam, and may result in a silence.",
    "comment": "If you feel like making live commentary on a beatmap replay, hit the Discussion button, write something, and hit enter!\nIf there's no comments on-screen already, select the Show Comments box in the Discussion panel.",
    "comment-color": "A normal user can only comment in white. A [https://osu.ppy.sh/p/support supporter] can customize their comment color.",
    "conferencemode": "Getting flooded by Join/Quit messages on IRC? [http://wiki.xkcd.com/irc/Hide_join_part_messages This] might just help!",
    "country-ranking": "View the various [https://osu.ppy.sh/p/countryranking Country Ranking] scoreboards here.",
    "critic": "Please keep criticism constructive. Suggest alternatives or ways to fix the issues you are concerned about.",
    "ctb": "Need some help with Catch the Beat? [https://osu.ppy.sh/wiki/Catch_the_Beat Here's] the wiki page!",
    "cutting-edge": "Cutting-edge is an experimental build of osu! used to test new features before they get live in the stable build. Switch to it in the options!\nYou can [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues read this article] if you have any problems updating your client.",
    "cwc": "A worldwide osu! Catch the Beat tournament. See this [https://osu.ppy.sh/wiki/Tournaments/CWC/2019 wiki page] for more information.",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Treat others as you wish to be treated. If you're some sort of verbal masochist, assume everybody else isn't.",
    "disable-this": "Toggles are rarely added for features. You can still request one to be added via the [https://osu.ppy.sh/forum/4 Feature Requests subforum], though.",
    "distance-snap": "Distance Snap is a tool that keeps correct relative distance between the notes, based on their positions on the timeline. Details: [[Distance_Snap]]",
    "dont-ask-peppy": "Please don't ask peppy all the time - he's quite busy. Feel free to ask anyone else in this channel, though!",
    "douche": "As a catch-all safeguard, circumventing order and civility via loopholes in the rules is punishable at the sole discretion and judgment of the administrative team. An official rule stating that you should not be a douche should not be required for you to not be a douche, but just in case: don't be a douche.",
    "download": "You can download more beatmaps [https://osu.ppy.sh/p/beatmaplist?q= here] or beatmap packs [https://osu.ppy.sh/beatmaps/packs here].\nIn case you don't know how to import them, you can read [http://i.imgur.com/kpX2N3m.jpg this] to find out!",
    "drugs": "Discussion of drugs or drug use anywhere in osu! is forbidden. This is an all-ages game.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Read [[Beatmapping#Keyboard_Shortcuts]] to find the list of editor shortcuts.",
    "english": "#english is for general discussion about anything which doesn't have a dedicated channel.\nYes, this does include anime/manga. And trains.",
    "evade": "Evading a silence is grounds to have your account restricted for a large length of time, if not outright banned. Don't do it.",
    "fallback": "Stable (Fallback) is an outdated build of osu! Unlike Fallback, newest releases removes the DirectX support in order to simplify osu! framework. If you're switched to this build, your PC is low-end and won't support newest and future client versions.\nIf you want to use current osu! builds now, update your graphic card and make sure it supports OpenGL, the most required complement for those builds. [https://osu.ppy.sh/wiki/GL_Support_Issues Click here to know how].",
    "faq": "You are currently using the osu!Bancho FAQ system.\nosu!wiki: https://osu.ppy.sh/wiki",
    "feature": "If you have an idea for this game, post it in the [https://osu.ppy.sh/forum/4 Feature Requests] subforum.\nMake sure you have read the [https://osu.ppy.sh/forum/t/454006 forum guidelines] first!",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Avoiding the chat filters can lead to a silence. Don't do it.",
    "foul-play": "Please report cheaters by using the report button at their profile, located [https://i.imgur.com/GG9xlLA.png here].\nMake sure you provide as much detail as possible. You can also report their scores at the top 50 leaderboards of the beatmap's page.\nDo NOT discuss this in public chat, as it may warrant you a silence.",
    "percolate": "Avoiding the chat filters can lead to a silence. Don't do it.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 This article] will help you to understand mapping flow.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "To add a user as a friend, type /addfriend followed by the user's name.\nAdditionally, you can click on the user's panel on the Online Users list (press F9) or their name in chat and select Add as Friend.\nYou can also add them through their profile by clicking Add as Friend.",
    "friends-list": "To see a list of your online friends in-game, press F9 then change the filter on top to Friends.\nYou can also see the full list of your friends [https://osu.ppy.sh/home/friends here]. Make sure you are logged in.",
    "fullscreen": "You can change whether the game plays Windowed or Fullscreen under the Graphics section of the Options menu.\nYou can also switch to and from fullscreen with Alt+Enter on your keyboard.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "You can find plenty of terminology at the osu! [[glossary]].",
    "gmt": "The [https://osu.ppy.sh/wiki/GMT Global Moderation Team], for short GMT, is a group of users that help run osu!. They have red names in chat and green names on the forums. \nThese guys help moderate the forum and chat.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Read, revise, rejoice.]",
    "grammar": "Put forth your best effort to use good grammar. A few mistakes in spelling or punctuation are acceptable, but please don't use shorthand or textspeak. It makes you look dumb.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Don't know how to play? Want to explore the world of mapping and modding? [https://osu.ppy.sh/wiki/Guides Here] you will find all the answers.",
    "hacked": "If you believe you have been hacked, please email accounts@ppy.sh to follow up.\nFailure to do so may result in account termination.",
    "hard": "Git gud, scrub.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "If you require assistance for anything osu!-related, join the #help channel and ask your question. Also, #help is a multi-lingual channel.\nIf nobody is responding, you can post at the [https://osu.ppy.sh/forum/5 Help] forum instead.\nYou can also read [http://help.ppy.sh/ this page] for helpful articles including account related issues.",
    "hitsound-library": "Go [https://osu.ppy.sh/forum/p/164927 here] to get some custom hitsounds for your map.",
    "hl": "Please don't blame other users for highlighting you if you have a dictionary word or other common phrase as your name or in your highlights list. It's your fault anyways!\nYou can disable notifications and the sound that plays when it happens in Options if you need to.",
    "how-to-get-modded": "If you want to know how you can get your map checked out, click here: [[Getting_Your_Map_Modded]]",
    "how-to-bn": "If you want to be a BN, have a read of [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator this].",
    "how-to-gmt": "Global Moderators are hand-picked depending on how much they have contributed to the community.\nFor more details, read the team's wiki page: [https://osu.ppy.sh/wiki/People/The_Team/Global_Moderation_Team Global Moderation Team]",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#how-to-play? Click this link to learn how to play!]",
    "how-to-rank": "To find out, read [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Hyperdash will occur when you catch a fruit that is glowing red. You will dash faster than normal during this period. It will deactivate once you reach the next fruit or outright miss it.",
    "ignore": "To ignore a user, type /ignore and then their user name.\nYou cannot see lines written by users you have ignored, including any PMs they may send you.\nTyping /unignore (user name) or exiting osu! will end this effect. To ignore someone permanently, refer to [http://help.ppy.sh/article/141/how-do-i-completely-block-another-user-from-contacting-me this guide].",
    "import": "Read [http://i.imgur.com/kpX2N3m.jpg this] to find out how to import beatmaps into osu!",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "By checking the box Inherit previous timing settings in the F6 window of the Editor, the timing section won't affect the timing anymore, which is useful for sections which only change the volume or the sample of the map.\nAlso, it's possible to inherit timing sections which have doubled or halved BPM. If you find yourself using a timing section like this, please inherit!",
    "irc": "IRC server: irc.ppy.sh:6667\nPassword: https://osu.ppy.sh/p/irc\nMore details on https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "You can change your keyboard bindings at the input section in options.\nKeys and layouts in osu!mania are changed in osu!mania layout button.",
    "kiai": "Kiai mode is a style effect you can apply to timing sections using the Timing Setup Panel. Timing sections with kiai mode enabled use various visual effects to make a beatmap more epic.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Earn [https://osu.ppy.sh/wiki/Kudosu kudosu] by modding other people's beatmaps.",
    "lag": "Lag could be caused by [https://osu.ppy.sh/help/wiki/Performance_Troubleshooting anything] - most likely other processes on your machine. If you're convinced that it is osu! and only osu! that is lagging, file a support request on the [https://osu.ppy.sh/forum/5 Help forum] detailing your issue and anything you have found that may help to identify it.",
    "language": "Please be polite in the chat room. Inappropriate language might get you silenced.",
    "language-specific": "Please use the appropriate language of the channel you are visiting.\nUsing Romanized words or phrases are not an exception for non-Roman languages such as Japanese.",
    "lazer": "[https://www.youtube.com/watch?v=ut_SOreClcc what is lazer?] It is the codename given to the next major update of osu!.\nGitHub: [https://github.com/ppy/osu ppy/osu] | Download: [https://github.com/ppy/osu/releases ppy/osu/releases]",
    "level": "Your level is based on your total accumulated score. This includes any ranked score, be it a pass or fail. You will gradually increase your level just by playing osu!",
    "lines": "Please try to keep your sentences on a single line to avoid getting silenced.",
    "link": "To make text link to something, use the following format: [address text], where 'address' is the address you want to link, and 'text' is the text you want to show. [https://osu.ppy.sh/ Just like this!] Don't forget the http:// though.",
    "lobby": "Please use #lobby only for the advertising of osu! multiplayer games. Also, #lobby is a multiple-language channel.\nUse your room's #multiplayer channel for any other discussions.",
    "localisation": "Find the osu! localisation project [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 here].",
    "long-link": "Please don't paste long links in the chat! Use the [link text] formula if you really have to.",
    "long-text": "Please do not paste long texts in chat. Doing so may get you silenced.",
    "loved": "Loved is a new community-based ranking state that gives maps that are normally unrankable full scoreboards. [https://osu.ppy.sh/wiki/Project_Loved Read more about it here!]",
    "mac": "[https://osx.ppy.sh Run osu! on your Mac]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Mappers are busy people, and mapping is a lot of work. Why not try mapping it yourself?",
    "mapping": "Go [https://osu.ppy.sh/forum/p/988111 here] for mapping guides.",
    "mat": "The Mapping Assistance Team was an old user group which assisted the BAT in the ranking process. \nRIP MAT 2013-04-23",
    "modhelp": "For all your modding and mapping queries, head over to #mapping!",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modding Queues]",
    "modreqs": "Please go to #modreqs for any modding requests. Keep in mind that BN may not always have time and that they have other people who have requested first, so please be sure to also ask regular users to mod your beatmaps. To do a request, make sure to use the /np command or the [link text] format. Don't forget to say thank you!",
    "multi-invite": "In order to invite someone to your multiplayer game, click the desired user on the Online Users list (press F9) or click their name in chat and choose Invite to game.\nYou can also type /invite followed by the name of the user you want to invite.",
    "multi-link": "[https://osu.ppy.sh/community/forums/topics/338482 How to create a direct link to your multiplayer room]\n        ",
    "multiaccounting": "You really, really shouldn't make multiple accounts. You will be found, and you could get silenced for a seriously long amount of time, or even banned.",
    "multiplayer": "Please don't advertise multiplayer games in any channel other than #lobby.",
    "mwc": "A worldwide osu! Mania tournament. See [https://osu.ppy.sh/wiki/Tournaments/MWC/2019_4K this] for more information.",
    "nat": "The [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] moderate the Beatmap Nominators and oversee the Beatmap Ranking process.\nThey are responsible for evaluating current and aspiring Beatmap Nominators, as well as mediating beatmap vetoes and other mapping / modding related disputes.",
    "news": "osu! changes from time to time thanks to the people running and keeping the game lively.\nKeep yourself up to date by checking the [https://osu.ppy.sh/home/news news page]!",
    "nightcore": "Enjoy your favourite beatmaps Nightcore style!\nSimply click the DoubleTime mod again to reveal the Nightcore mod! It is functionally identical to DoubleTime for scoring.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Type /np to show others what you are currently listening to or playing on osu!",
    "nsfw": "Explicit conversation is not allowed. osu! is for all ages, so please keep the chat clean, or you'll risk getting silenced without warning.",
    "osu": "#osu is for talking about osu!. Please discuss gameplay there, not in this channel.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 The osu!tablet official thread!] - Read this for all the information about the tablet and preorder options.",
    "osu!talk": "[https://osu.ppy.sh/wiki/osu!talk osu!talk] was a talk show hosted by deadbeat and ztrot in which they interview members from the community and discuss events such as the world cups.\nIt was succeeded by the osu! coffee hour after the hosts retired from the team.",
    "osucore": "An April Fool's joke from 2011. All maps were set to DoubleTime speed by default and had their pitch raised.\nThis later returned as the Nightcore mod, which has the same effects as DoubleTime did on that day.",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] is a port of the original game on the Android platform.\nIt has been abandoned by the official developers and taken down from Google Play Store since 2016 due to inactivity and bad reviews.",
    "osumania": "Please use #osumania for osu!mania related discussions.",
    "osustream": "[http://www.osustream.com osu!stream] is osu! for iOS devices, made and maintained by peppy!",
    "osz": "The file format for beatmaps that you download for osu!. .osz files must always be extracted by osu! itself, otherwise issues can occur!",
    "osz2": "A new beatmap file format which will mean each contained file can be encrypted, updated and streamed independently of all other files.  osz2 files will not need to be extracted and will always remain as .osz2 files in your Songs folder.",
    "owc": "A worldwide osu! tournament. See this [https://osu.ppy.sh/wiki/OWC wiki page] for more information.",
    "peppy": "peppy is the lead developer and indeed, the creator of osu! and handles most of the project by himself.",
    "perfect": "Didn't get that SS? This mod automatically retries the map for you if you make a single mistake.\nYou can find it by right-clicking on SuddenDeath in the mod selection screen.",
    "ping": "Pong!",
    "pippi": "The mascot character of osu!\nPippi-don is the taiko (drum) version of Pippi.",
    "piracy": "Please don't discuss pirating copyrighted content in the general chat. It's prohibited and may get you silenced.",
    "play-shortcuts": "Full list of shortcut keys: [[Shortcut_Key_Reference]]",
    "pm": "To private message someone, click on someone's name in chat or their user panel on the Online Users screen then click Start Chat.\nYou can also use the command /msg <username> or /chat <username> or /query <username>, which will open a seperate tab in chat.\nTo quick reply to the last private message sent at you, you can use /r <message>. Remove the < >, of course.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance Points (pp) is the main ranking metric of osu! Click [https://osu.ppy.sh/wiki/Performance_Points here] to find out more info.",
    "pp-rework-lazer": "As of March 2025, [https://osu.ppy.sh/home/news/2025-03-06-performance-points-star-rating-updates a pp rework was pushed for osu!].\nChanges to the Performance Points system may experience temporary fluctuations in rankings during the calculations. \nIf you have questions, feel free to post in the [https://osu.ppy.sh/community/forums/topics/2051204?n=1 Q&A thread]",
    "preview": "The preview point is the point in the song from which it starts playing in the song selection screen.\nA proper preview point is a point in the song that represents it well, like the start of the chorus. Go to Timing in the toolbar and click Set Current Position as Preview Point to choose one. Remember to select the most representative part, example: a chorus.",
    "qat": "The Quality Assurance Team checks the recently qualified maps for quality and playability.\nAfter significant growth of the beatmap Ranking system, in April 2019, they became the Nomination Assessment Team to better reflect their current field of work.",
    "qualified": "Beatmap Nominators nominate maps as qualified as being fit for ranking where you can get ranks without performance points.\nIf these maps have no issues and is qualified for a week, it will be ranked. Else, it goes back to pending and scores will be wiped out.",
    "ranked": "A Ranked beatmap is a beatmap which has been approved by the online community.\nWhen you play a Ranked map, the score attained from it counts towards your total accumulative ranked score.\nThese maps have their own ranked leaderboard, and can be identified by an Double Arrows icon.",
    "ranking-criteria": "For information on ranking criteria, please visit the wiki: [[RC]]",
    "redname": "Users with red names are either a member of the [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team] or the [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team]",
    "report": "Use the following format to report inappropriate behaviour or foul play: !report <user_name> <reason>\nReports are not visible to other users and must be done in public channels. Avoid doing it in a PM.\nYou can also report by clicking the user's name then selecting Report User",
    "report-abuse": "Please avoid sending multiple reports in a row - it doesn't help to bring justice faster. Neither do blank or unreasonable reports.\nIn fact, you may end up silenced instead for spamming chat moderators.",
    "request": "Looking for something to mod? Click [https://osu.ppy.sh/p/beatmaplist&r=8 here] or type !request for a random map link.",
    "respect": "Please be respectful to other players.",
    "roll-abuse": "Please don't overuse the !roll command. You might get silenced.",
    "romaji": "Please do not use Romaji (Romanized Japanese) excessively. You might get silenced.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "If there's no multiplayer rooms to join, why don't you make your own? Then you can pick the songs, too!",
    "rp": "You are free to roleplay in appropriate osu! channels; however, you should make sure that you do not bother other people in the channel too much.",
    "rules": "[https://osu.ppy.sh/wiki/Rules Official game rules]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "From time to time, osu! gets DDoSed. During this time, Bancho might be unstable or unreachable.\nIf you suspect this has happened, check the [https://twitter.com/osustatus @osustatus] Twitter feed or [https://status.ppy.sh this] for more info.\nIf this happens, and you are still able to talk - continue as normal. Bringing up the topic won't make it go away faster.",
    "sb": "[[Storyboarding]]\nStoryboarding Guide: https://osu.ppy.sh/forum/t/1869\nHow to use the Storyboard Editor: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "scorev2 is a new scoring algorithm that caps the scores for all game modes to 1 million points, excluding spinners and mods.\nIt also changes the behaviour of sliders so that they require the same timing as hitcircles.",
    "scoring": "How osu! calculates score: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "A silence means that you are unable to talk in chat or post in the forums, except in Help forum.\nSilences start at 5 minutes for the first infraction, then doubles every infraction from then on. Major infractions can much more than double the previous silence, though.\nSilences are handed out for most misdemeanors, so just follow the rules and you'll be fine.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Skinning FAQ]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Don't let osu! keep you up until 4 AM. Getting sleep is important too!]",
    "songs-not-appearing": "If your songs are not appearing in the song select menu, try pressing F5.",
    "spaces": "Please don't put spaces between every letter, your aesthetics make the chat look messy and can lead to a silence.",
    "spam": "Please don't spam. It's annoying and usually leads to a silence.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "To spectate another player, type /watch <username>, or click on their name in chat or user panel and select Start Spectating.\nMake sure you have the same beatmap they are playing (and that they're actually playing)!",
    "spoiler": "Spoiling any anime, series, manga and related formats is prohibited, and may result in a silence. Please let people enjoy their favorite things in peace! (this also applies to details that their respective authors have not revealed).",
    "status": "For osu! system status updates, please refer to [http://twitter.com/osustatus @osustatus]. For server status info, see [https://status.ppy.sh this].",
    "store": "[https://osu.ppy.sh/store/listing Welcome to the osu! store], the place where you can buy awesome osu! stuff!",
    "submit": "[https://osu.ppy.sh/wiki/Submission Beatmap Submission FAQ]",
    "suck": "osu! has a large learning curve - you'll get better over time, so just keep at it!",
    "supporter": "Become an [https://osu.ppy.sh/p/support osu! supporter]! You'll get a number of extra benefits, and help support the development team to produce more!",
    "supporter-please": "Please do not ask other people to gift you a supporter tag. [https://osu.ppy.sh/p/support Get it here instead yourself!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "If your cursor is flying everywhere when you try to move it, make sure your mouse sensitivity ingame is set to 1.00x. Higher sensitivity can be achieved by lowering your tablet's active area.\nIf your cursor is not moving at all, make sure to turn off Raw Input in the options.\nFor any other tablet-related issues, [https://osu.ppy.sh/forum/t/87301 read this thread.]",
    "tag": "In tag multiplayer mode, all players take turns clicking one combo of a beatmap at a time. There is no winner or loser, as everyone plays on the same team.\nIn spinners, all players participate. If even one player fails to clear the spinner, the combo resets. Each player's spinner bonus is added to the team's score.",
    "taiko": "A Japanese drum featured in a series of games by Bandai-Namco. osu!taiko simulates these games by eliminating beat placement, forcing the player to focus solely on the rhythm of the beatmap.\n[https://osu.ppy.sh/forum/t/4363 Here's how to play!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Taiko mapping guide]",
    "taiko-maps": "You can find authentic Taiko no Tatsujin maps [https://osu.ppy.sh/forum/t/5397 here.]\nYou may also be interested in [https://osu.ppy.sh/forum/t/175867 Taiko training for beginners].",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Can you please drop the topic and talk about something else?",
    "training": "[https://osu.ppy.sh/forum/t/4280 James Training]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 List of up-to-date video tutorials on osu! and mapping.] Feel free to make your own and have it submitted to the topic. [https://osu.ppy.sh/forum/t/60228 List of useful guides for mappers/modders]",
    "twc": "A worldwide osu! Taiko tournament. See this [https://osu.ppy.sh/wiki/Tournaments/TWC/2019 wiki page] for more information.",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Please avoid using unicode/non-standard characters in general chat. You can get silenced.",
    "upload-cap": "To keep mappers dedicated to their in-progress maps, there's a small limit on the amount of maps you can have in-progress at once.\nNon-supporters can have 3-6 active, and supporters can have 5-10 active. Those previous limits will increase +1 depending of the maps you have ranked.",
    "utf8": "Please set your IRC client to use UTF-8 encoding so that you can both adequately read and send legible messages to other users.",
    "videogames": "Videogame-related topics can be discussed in #osu, but if it disturbs chat or more than one conversation is going on, please go to #videogames.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Welcome to osu! If you have a problem or question that needs answering, ask the nice people in #help! Keep the chat friendly and have fun! :D",
    "when": "When it is ready.",
    "wiki": "The [https://osu.ppy.sh/help/wiki osu!wiki] - Make it awesome!\nContributions are now done through GitHub: [https://github.com/ppy/osu-wiki/ ppy/osu-wiki]",
    "wiki-link": "You can link to wiki pages by enclosing the wiki entry's name in double brackets like this: [[...]]\nFor example, [[Kudosu]] is created by typing Kudosu in between double [[ and ]‌].",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 217 active FAQs (out of a possible 217) in the English (English) language.",
    "completion": "The English (English) FAQ as of last update is 100% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "MP timer has been set to 60 seconds!"
}
