
strings = {

    "academy": "[http://www.youtube.com/user/osuacademy Clickea aquí] para revisar los tutoriales de la osu!academy sobre todo lo básico acerca de osu!",
    "achievements": "Puedes conseguir logros haciendo algo especial en un mapa, como conseguir un gran combo, o jugar todos los mapas de un paquete. Tu perfil muestra qué logros has conseguido, y qué necesitas para conseguirlo. ¡Algunos de los nombres son pistas de lo que necesitas para conseguir el logro!",
    "add-skin": "Para añadir una nueva skin a osu!, descarga el archivo .osk y arrástralo a la ventana de osu! o haz doble clic sobre el archivo.",
    "advertising": "Está totalmente prohibido publicar anuncios de otros productos que no sean relacionados a osu!. Puedes terminar silenciado si lo haces.",
    "answer": "Si nadie te responde, ¡es posible que nadie sepa la respuesta!. Busca en los foros si se trata de algún tema relacionado con osu!.",
    "appeal": "Si te silencian y crees que fue injusto, puedes contactar a un administrador enviando un correo a accounts@ppy.sh explicando tu situación (en inglés). Recuerda que los administradores también son personas, y es más probable que levanten tu castigo si los tratas de manera amable y educada.",
    "approved": "Los mapas aprobados no pueden ser rankeados por una u otra razón - normalmente duran más de 5 minutos y tienen una sola dificultad, aunque pueden tener más. Sabrás si un mapa es aprobado si su icono es una llama en lugar de un corazón.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire, el concurso de beatmapping de osu! de alto nivel, vuelve en 2017 con una canción de Helblinde. [http://osu.ppy.sh/news/156171674413 ¡Échale un vistazo!]\n",
    "ask": "¡La mejor forma de conseguir una respuesta es preguntando directamente! - ¿Puedo preguntar algo? ya es una pregunta.",
    "attention": "¿Puedes parar? Nadie aquí te está poniendo atención...",
    "avatar-change": "Puedes cambiar tu avatar [https://osu.ppy.sh/home/account/edit#avatar aquí.]",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "¡Hola, soy BanchoBot! Es un placer conocerte. ¡Soy un bot que maneja todo el servidor de osu!\nLo malo es que soy un bot, así que no puedo tener una conversación contigo :(",
    "beatmapping": "Ve a [https://osu.ppy.sh/wiki/Beatmapping?locale=es Beatmapping] para leer una serie de consejos útiles sobre el mapping.",
    "beginner": "Pulsa [https://osu.ppy.sh/forum/t/5456 aquí] si estás buscando mapas para principiantes.",
    "bn": "El [https://osu.ppy.sh/wiki/People/Beatmap_Nomination_Group?locale=es Beatmap Nomination Group] es un grupo de personas que se encargan de calificar mapas, y son los responsables de la moderación de los 'Mapas Pendientes' en el ciclo del ranking de mapas. Puedes hablar con ellos si tienes preguntas o solicitas consejos sobre mapping o modding. ¡Son gente muy ocupada, así que evita hacerles spam!.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Si estás realmente aburrido, busca otra cosa que hacer. Hay mucho que hacer en línea.]\nEl aburrimiento no es una excusa para quejarse o hacer spam en osu!",
    "bug": "Si tienes alguna duda o problema técnico, no dudes en escribir un nuevo mensaje [https://osu.ppy.sh/forum/5 aquí] (preferiblemente en inglés).",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Por favor, no uses una letra mayúscula al inicio de cada palabra - hace que todo lo escrito parezca un tren de guerra.",
    "caps": "Por favor evita escribir todo en mayúsculas. Es totalmente innecesario y puede derivar en un silencio.",
    "change-modes": "Para cambiar a otros modos de juego, ve a la pantalla de selección de canciones y haz clic en Mode abajo a la izquierda, o usa Ctrl + 1-4. ¡Ten en cuenta que algunos mapas son específicos para un modo de juego!",
    "change-name": "Para cambiar tu nombre de usuario, primero debes hacerte [https://osu.ppy.sh/p/support osu! supporter]. Tendrás una oportunidad gratuita de cambiar tu nickname desde tu perfil. Si necesitas otro cambio, es desde [https://store.ppy.sh/store/product/32 aquí]! Para solicitar volver a tu antiguo nombre, cambios menores, o ayuda, por favor envía un e-mail al correo accounts@ppy.sh con los detalles (preferiblemente en inglés).",
    "changelog": "Puedes enterarte de las novedades de osu! en la página de [https://osu.ppy.sh/p/changelog actualizaciones].",
    "chars": "Por favor, no utilices caracteres unicode/no-estándar en un chat general.",
    "charts": "Todos los meses hay una nueva tabla de mapas en osu! Puedes encontrarlas [https://osu.ppy.sh/p/chart aquí].",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Amarillo claro: Un usuario normal | Amarillo: Un [https://osu.ppy.sh/p/support supporter] | Rojo: Un [https://osu.ppy.sh/wiki/NAT NAT] o [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Moderador]\nBlanco: Tú mismo, o un mensaje /me | Azul oscuro: Un mensaje privado | Verde: Una línea de texto que contiene tu nombre de usuario | Rosa: BanchoBot",
    "colour": "Amarillo claro: Un usuario normal | Amarillo: Un [https://osu.ppy.sh/p/support supporter] | Rojo: Un [https://osu.ppy.sh/wiki/NAT NAT] o [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Moderador]\nBlanco: Tú mismo, o un mensaje /me | Azul oscuro: Un mensaje privado | Verde: Una línea de texto que contiene tu nombre de usuario | Rosa: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Aunque los comandos de chat son fáciles de usar, por favor, no abuses de ellos. Esto se ve como spam, y puedes ser silenciado.",
    "comment": "Para escribir un comentario en un mapa, haz clic en la pestaña Discussion en la parte derecha de tu pantalla cuando estés viendo una repetición. Después elige el rango de publicación de ese comentario, escribe lo que quieras, y pulsa Enter.\nSi no puedes ver ningún comentario, haz clic en Show Comments.\n¡Algunos mapas tienen tantos comentarios que dificultan la visibilidad de la repetición!",
    "comment-color": "En los comentarios de mapa (se ven en las repeticiones), un usuario normal escribe en blanco, y un usuario [https://osu.ppy.sh/p/support supporter] puede personalizar el color del comentario.",
    "conferencemode": "Si quieres desactivar los mensajes de login/logout en tu cliente IRC, consulta [http://wiki.xkcd.com/irc/Hide_join_part_messages este artículo.]",
    "country-ranking": "[https://osu.ppy.sh/p/countryranking Ranking por países]",
    "critic": "Por favor, mantén tu crítica constructiva. Propón alternativas o formas de corregir los problemas que te preocupan.",
    "ctb": "¿Necesitas ayuda con Catch The Beat? [https://osu.ppy.sh/wiki/ES:Catch_the_Beat Aquí] está la página en la wiki!",
    "cutting-edge": "Cutting-edge (Experimental) es la versión de osu! utilizada para probar nuevas características antes de ser implementadas en la versión Estable. ¡Puedes cambiarte a ella en las opciones!\nSi tienes problemas actualizando el cliente, [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues lee este artículo] (en inglés).",
    "cwc": "El CTB World Cup, se trata de un torneo mundial de Catch the Beat en osu!. [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 Consulta esta página de la wiki para más información al respecto.]",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Trata a los demás como quieres ser tratado. Si eres una especie de masoquista verbal, asume que los demás no lo son.",
    "disable-this": "Los botones para desactivar características son rara vez añadidos. Aun así, puedes intentar solicitarlo desde el [https://osu.ppy.sh/forum/4 subforo de peticiones].",
    "distance-snap": "La mejor manera de asegurarse de que el espacio entre las notas es el correcto, consiste en activar la función Distance Snapping, que puedes encontrar en la esquina inferior derecha del editor. Más información: [[Distance_Snap]]",
    "dont-ask-peppy": "Por favor, no le preguntes cosas a peppy todo el tiempo, está muy ocupado. Siéntete libre de preguntar a alguien más en este canal.\n",
    "douche": "Como medida de seguridad, interrumpir el orden y el comportamiento cívico mediante vacíos en las reglas es castigable bajo la sola discreción y juicio del equipo administrativo. No es necesario tener una regla oficial diciendo que no seas idiota, pero por si acaso: no te comportes como un idiota.",
    "download": "[https://osu.ppy.sh/p/beatmaplist ¡Haz clic aquí para descargar mapas!] o bájalos de la [https://osu.ppy.sh/beatmaps/packs lista oficial de paquetes de mapa].\nEn caso de que no sepas cómo importarlos, puedes [http://i.imgur.com/kpX2N3m.jpg leer esto].",
    "drugs": "No están permitidas las conversaciones relacionadas con drogas en el chat de osu!. Este es un juego para todas las edades.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Lee [[Beatmapping#Keyboard_Shortcuts]] para averiguar todos los atajos del teclado en el editor.",
    "english": "En la sala de chat #english puedes hablar en inglés de cualquier tema que no tenga un canal relacionado. Sí, esto incluye anime/manga. Y trenes.",
    "evade": "Intentar evadir un silencio de tu cuenta principal puede llevar a que tu cuenta sea restringida por un largo tiempo, si es que no acaba baneada. No lo hagas.",
    "fallback": "Estable (Fallback) es una versión desactualizada de osu! A excepción de Fallback, las nuevas versiones eliminan el soporte de DirectX para simplicar el entorno del juego. Si estás en este cliente, tu PC es muy antiguo y no podrás actualizar a versiones futuras.\nSi quieres jugar en las versiones actuales, actualiza tu tarjeta gráfica y asegúrate de que soporte OpenGL, el complemento más indispensable para estas versiones. [https://osu.ppy.sh/wiki/GL_Support_Issues Haz clic aquí para saber cómo].",
    "faq": "Estás utilizando el sistema de FAQ de osu!Bancho.\nWiki de osu!: https://osu.ppy.sh/wiki/",
    "feature": "Puedes publicar tus sugerencias en el foro de [https://osu.ppy.sh/forum/4 Feature Request]. Asegúrate de leer [https://osu.ppy.sh/forum/t/454006] esto primero (en inglés).",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Si evades los filtros del chat, puedes acabar silenciado. No lo hagas.",
    "foul-play": "Por favor reporta a los tramposos utilizando el (botón de reporte)[https://i.imgur.com/GG9xlLA.png] que se encuentra en su perfil. Asegúrate de proporcionar la mayor información posible. También puedes reportar sus puntajes en la tabla de los top 50 de la página del mapa. Se ruega NO discutir este tema en ningún chat público, ya que te garantiza ser silenciado.",
    "percolate": "Si evades los filtros del chat, puedes acabar silenciado. No lo hagas.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Este artículo] te ayudará a entender el concepto de flow en un mapa.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Para añadir a un usuario como amigo escribe /addfriend seguido de su nombre de usuario.\nTambién puedes hacer clic en su panel de usuario (pulsando F9) o en su nombre en el chat y seleccionar Add as Friend.\nOtra forma es a través de la página web, accediendo a su perfil y haciendo clic en Add as Friend.",
    "friends-list": "Para ver una lista de tus amigos conectados, presiona F9 y luego cambia el filtro en la parte superior a Amigos. También puedes ver una lista de todos tus amigos, conectados o no conectados, en la página web al hacer clic en Settings. (Debes haber iniciado sesión, claro.)",
    "fullscreen": "Puedes configurar el juego en modo ventana o pantalla completa a través de la pestaña Gráficos en el menú de opciones.\nTambién puedes cambiar entre pantalla completa y modo ventana presionando Alt+Enter en tu teclado.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Puedes encontrar la terminología de osu! en el [https://osu.ppy.sh/wiki/Glossary?locale=es glosario].",
    "gmt": "El [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Equipo de moderación global], abreviado GMT, es un grupo de usuarios que colaboran con osu! Sus nombres son de color rojo en el chat, y verde en el foro.\nSu función es la de moderar las salas de chat y las distintas secciones del foro.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Léelo, Revísalo y Disfruta]",
    "grammar": "Haz tu mejor esfuerzo para escribir correctamente. Podemos tolerar algunos errores de puntuación o de gramática, pero por favor no escribas con muchas faltas ortográficas, te hace parecer un idiota.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "¿No sabes cómo jugar? ¿Quieres aprender a crear y modear mapas? [https://osu.ppy.sh/wiki/Guides Aqui] encontrarás todas las respuestas a tus dudas.",
    "hacked": "Si crees que tu cuenta ha sido hackeada envía un correo a accounts@ppy.sh.\nSi no lo haces tu cuenta puede ser eliminada.",
    "hard": "Aprende a jugar, novato.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Si necesitas ayuda para cualquier problema relacionado a osu!, puedes unirte al canal #help y preguntar libremente. También recuerda que #help es un canal multilenguaje.\nSi nadie te responde, puedes hacer un post en la sección de [https://osu.ppy.sh/forum/5 Ayuda] en el sitio web.\nTambién puedes leer [http://help.ppy.sh esta página] para encontrar artículos útiles, incluyendo problemas relacionados a las cuentas.",
    "hitsound-library": "Puedes encontrar sonidos personalizados para tu mapa [https://osu.ppy.sh/forum/p/164927 aquí.]",
    "hl": "Por favor no culpes a otros usuarios por mencionar alguna palabra o frase común que tú hayas configurado en la sección de tus palabras a notificar, al fin y al cabo es tu culpa. Puedes desactivar estas notificaciones y sonidos desde las opciones si es necesario.",
    "how-to-get-modded": "Si quieres saber como hacer que otros se fijen en tu mapa, mira [https://osu.ppy.sh/forum/t/17043 aquí]",
    "how-to-bn": "Si quieres ser un BN, tienes que tener en cuenta [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator esto]",
    "how-to-gmt": "Los moderadores son elegidos dependiendo de cuánto han contribuido a la comunidad. Puedes contribuir a la moderación reportando los abusos en cualquier canal que frecuentes, usando el comando !report.\nPara más detalles, puedes leer la página de Wiki: [https://osu.ppy.sh/wiki/People/The_Team/Global_Moderation_Team Equipo de moderación global]\n",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F ¡Haz clic aquí para aprender a jugar!]",
    "how-to-rank": "[https://osu.ppy.sh/wiki/es/How_to_Get_Your_Map_Ranked Lee esto para saber como lograr que tu mapa sea aprobado.]",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "El Hyperdash ocurre cuando recoges una fruta con un destello rojo. Tu personaje se moverá más rápido de lo normal durante un breve periodo que finalizará al recoger la siguiente fruta.",
    "ignore": "Para ignorar a un usuario en tu sesión actual escribe el comando /ignore <usuario> para no recibir mensajes de Chat y PM's. Si quieres ignorar a un usuario permanentemente usa el apartado Usuarios Ignorados desde Opciones.\nEscribe /unignore <usuario>, o sal del juego, para terminar el efecto.",
    "import": "Lee [http://i.imgur.com/kpX2N3m.jpg esto] para averiguar cómo importar mapas a osu!",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Si activas la casilla Inherit previous timing settings en la ventana F6 del editor, las siguientes secciones no afectarán el Timing del mapa (Es decir, Offset y BPM). Esto sirve para ocasiones en las que solo quieres ajustar el volumen o activar el Kiai Time.",
    "irc": "Servidor IRC: irc.ppy.sh:6667\nContraseña: https://osu.ppy.sh/p/irc\nMás detalles en: https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Puedes cambiar las teclas que usas para jugar en la sección Input de las opciones. La distribución de teclas en osu!mania se cambian con el botón de osu!mania layout.",
    "kiai": "Kiai Time es un efecto que se puede aplicar a cierta sección de un mapa usando el Panel de Tiempo (F6). Las secciones con Kiai Time activado tienen una serie de efectos visuales que resaltan esta sección haciéndola más épica. Esto es generalmente usado sólo en los coros y no debe ser usado de manera muy constante.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Puedes ganar [https://osu.ppy.sh/wiki/ES:Kudosu kudosus] cuando haces modding a los mapas de otras personas.",
    "lag": "Lag puede ser causado por muchas razones, lo más probable es que sea causa de otros procesos en tu PC. Si estás convencido de que es osu! y solamente osu! el que causa el lag, escribe en el foro de [https://osu.ppy.sh/forum/t/10931 Soporte Técnico] detallando tu problema y cualquier indicación que encuentres que ayude a identificarlo.",
    "language": "Compórtate de manera educada en la sala de chat por favor. Puedes ser silenciado por usar palabras inadecuadas.",
    "language-specific": "Por favor, utiliza el lenguaje apropiado para el canal que estas visitando.\nUsar palabras o frases romanizadas no son excepción para idiomas no romanizados como el Japonés.",
    "lazer": "[https://www.youtube.com/watch?v=ut_SOreClcc ¿Qué es Lazer?] Es el nombre dado a la próxima gran actualización de osu!.\nGitHub: [https://github.com/ppy/osu ppy/osu] | Descarga: [https://github.com/ppy/osu/releases ppy/osu/releases]",
    "level": "El nivel está basado en tu puntuación total. Esto incluye toda puntuación que obtengas sin importar si completas o fallas el mapa. Tu nivel aumentará de forma gradual jugando osu!.",
    "lines": "Intenta escribir tus oraciones en una sola linea, por favor, de ese modo evitarás ser silenciado.",
    "link": "Para crear un vínculo por medio de texto usa el siguiente formato: [dirección texto], donde 'dirección' es lo que quieres vincular y 'texto' es el texto que quieres mostrar. Por ejemplo, [http://osu.ppy.sh ¡como esto!]. No olvides el http:// al inicio del link.",
    "lobby": "Por favor usa #lobby para anunciar y discutir los juegos en multijugador. Además, recuerda que #lobby es un canal de multi idioma. Utiliza #multiplayer en tu sala de multi o #spanish para cualquier otro tema de conversación.",
    "localisation": "Encuentra el proyecto osu! Localisation [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 aquí].",
    "long-link": "¡Por favor no pegues enlaces largos en el chat!\nUsa la fórmula [enlace texto] si realmente la necesitas.",
    "long-text": "No pegues textos muy extensos en el chat. Puedes acabar silenciado.",
    "loved": "Loved es un ranking basado en la comunidad que se le da a los mapas que normalmente no suelen ser aprobados.   [https://osu.ppy.sh/news/151925254083 ¡Lee más aquí!]",
    "mac": "[https://osx.ppy.sh Cómo ejecutar osu! en un Mac].",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Los mappers son personas ocupadas y mapear requiere dedicación, trabajo y tiempo. ¿Por qué no lo mapeas tú mismo?",
    "mapping": "[https://osu.ppy.sh/forum/p/988111 Aquí] encontrarás guías para crear nuevos mapas.",
    "mat": "El MAT (Mapping Assistance Team) fue un grupo de usuarios que se ayudaba al BAT en el proceso del ranking. (QEPD MAT 23/04/2013)",
    "modhelp": "Para cualquier consulta sobre la creación de mapas, dirígete a #mapping. Recuerda que en este canal sólo se habla Inglés.",
    "modqueue": "Subforo de [https://osu.ppy.sh/forum/60 Pedidos de moderación].",
    "modreqs": "Por favor, dirígete a #modreqs para realizar una petición de moderación. Recuerda que los BNs no siempre tienen tiempo disponible, y hay otras personas que pueden haber hecho una petición antes que tú. También puedes hacer peticiones a usuarios normales. Para realizar una petición usa el comando /np o el formato [link texto]. ¡No olvides dar las gracias!",
    "multi-invite": "Para invitar a alguien a tu partida en multijugador: haz clic sobre el usuario deseado en la lista de Usuarios en Línea y elige la opción Invitar a partida (Recuadro amarillo).\nTambien puedes escribir /invite seguido del nombre del usuario que quieres invitar.",
    "multi-link": "[https://osu.ppy.sh/community/forums/topics/338482 Cómo crear un link directo a tu sala de multijugador]",
    "multiaccounting": "En serio, realmente no debes de hacerte otras cuentas. Te encontrarán y podrías ser silenciado por un largo tiempo, o incluso puedes acabar baneado.",
    "multiplayer": "Por favor, no anuncies tu partida en ningún canal que no sea #lobby. Si anuncias tu partida fuera de ese canal, podrías ser silenciado.",
    "mwc": "El torneo mundial de osu! Mania. Puedes leer la página en la [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 wiki] para más información.",
    "nat": "El [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Equipo de Evaluación de Nominaciones] se ocupa de moderar a los encargados de nominar los mapas y supervisar el proceso de rankeo de mapas.\nSon responsables de evaluar a los actuales y a los que aspiran a ser futuros nominadores de mapas, como así también pueden dar vetos a los mapas por determinadas razones, entre otras cosas.",
    "news": "osu! está en constantes cambios gracias a la gente que se ocupa de que funcione y lo mantiene con vida.\n¡Te puedes mantener al tanto revisando la [https://osu.ppy.sh/home/news sección de noticias]!",
    "nightcore": "Disfruta de tus mapas favoritos al estilo Nightcore. Simplemente haz clic derecho en el mod de DoubleTime para ¡encontrar el mod Nightcore! Es prácticamente idéntico al DoubleTime para las puntuaciones.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Usa el comando /np para publicar qué canción estás escuchando o jugando en este momento.\n",
    "nsfw": "Por favor evita hacer referencias a temas sexuales u otro tipo de temática para mayores de 18 años.\nMantén conversaciones en osu! aptas para todo público, o corres el riesgo de ser silenciado sin aviso.",
    "osu": "#osu es para hablar sobre osu!. Por favor discute sobre el juego ahí, no en este canal. (Recuerda que en ese canal sólo se habla Inglés)",
    "osu!tablet": "Lee [https://osu.ppy.sh/forum/t/169139 este hilo] para tener toda la información acerca de la osu!tablet.",
    "osu!talk": "osu!talk es un show conducido por deadbeat y ztrot en el cual entevistan a miembros destacados de la comundad y discuten sobre diferentes eventos, como los torneos mundiales.\nCada episodio toma lugar en el servidor de TeamSpeak 3 osu.corin.me, el cual está disponible para preguntas y sugerencias en la sección Q&A. Más información la puedes encontrar [https://osu.ppy.sh/forum/t/225111 aquí].",
    "osucore": "Fue una broma del Día de los Inocentes de 2011. Todos los mapas se habían establecido en velocidad de DoubleTime y con un tono alterado. La idea gustó tanto que después regresó como un mod llamado Nightcore, que fue añadido al juego con los mismos efectos que tuvo en ese día.",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] es un puerto del juego original en la plataforma Android. Ha sido abandonado por los desarrolladores oficiales y fue dado de baja de la tienda de Google Play Store desde 2016, por inactividad y críticas negativas.",
    "osumania": "Para discusiones de osu!mania, dirígete a #osumania. Recuerda que en este canal solo se habla Inglés.",
    "osustream": "[http://www.osustream.com osu!stream es osu! para dispositivos con el sistema iOS], hecho y mantenido por el mismo peppy!",
    "osz": "El archivo que te has descargado de osu! en formato .osz debe ser extraído por el cliente de osu!, de lo contrario pueden ocurrir errores.",
    "osz2": "osz2 es un nuevo formato para los mapas. Este nuevo formato cifrará el contenido de los maps para que no pueda ser modificado por ningún usuario, excepto su creador. Lo que significa que ya no podrás tener acceso a los archivos usados en un mapa.",
    "owc": "OWC, son las siglas de osu! World Cup. El torneo mundial de osu!, [https://osu.ppy.sh/wiki/OWC Revisa esta página para más información.]",
    "peppy": "peppy es el líder del equipo de desarrollo y de hecho, el creador de osu! y maneja gran parte del proyecto por sí mismo.",
    "perfect": "¿No has conseguido una SS? Este mod automáticamente reinicia el mapa por ti a la primera equivocación. Puedes buscarlo con el clic derecho sobre SuddenDeath en la pantalla de selección de mod.",
    "ping": "¡Pong!",
    "pippi": "Pippi es la mascota de osu!, Pippi-don es la versión de Pippi para Taiko.",
    "piracy": "No discutas sobre material pirata en el chat. Está prohibido y puedes resultar silenciado.",
    "play-shortcuts": "Lista completa de atajos: [[Shortcut_Key_Reference]]",
    "pm": "Para enviarle un mensaje privado a un usuario, puedes usar el comando /msg <nombre de usuario> <mensaje> o /chat <nombre de usuario>, este último abrirá una pestaña de chat individual.\nPara responder de manera rápida al último mensaje privado, puedes usar /r <mensaje>.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance Points (pp) es la medida de Ranking en osu! Haz clic [https://osu.ppy.sh/wiki/Performance_Points aquí] para más información. ",
    "pp-rework-lazer": "",
    "preview": "Un punto de vista previa es el punto de la canción desde la que comenzará a reproducirse en el menú de selección.\nPara establecer un Preview Point, en el editor, en la barra de herramientas busca el menú Timing -> Seleccionar la posición actual como punto de vista previa. Recuerda elegir una parte de la canción que sea representativa, como por ejemplo un coro.",
    "qat": "El QAT (Equipo de garantía de calidad) se ocupa de revisar los mapas reciéntemente calificados, para comprobar su calidad y jugabilidad.\nLuego de un gran crecimiento del sistema de rankeo de mapas en abril del 2019, este equipo se convirtió en NAT (Equipo de garantía de nominación), para reflejar mejor su actual campo de trabajo.",
    "qualified": "Los nominadores de mapas nominan mapas como calificados para estar rankeados en un corto tiempo, en esta etapa podrás obtener ranks sin puntos de rendimiento.\nSi esos mapas no tienen problemas y están calificados por una semana, se rankearán. De lo contrario, regresarán al estado pendiente y sus puntuaciones se borrarán.",
    "ranked": "Si un mapa está marcado como Rankeado, significa que ha sido aprobado por la comunidad. Cuando juegas un mapa rankeado, la puntuación obtenida se sumará a tu puntuación total.\nEstos mapas tienen su propia tabla de puntuaciones y están identificados con un icono con forma de Doble Flecha.",
    "ranking-criteria": "Para más información sobre el Ranking Criteria, por favor visita la wiki: [https://osu.ppy.sh/wiki/en/Ranking_Criteria Criterio de rankings]",
    "redname": "Los usuarios con nombres rojos pertenecen al [https://osu.ppy.sh/wiki/People/Global_Moderation_Team?locale=es Equipo de Moderación Global] (o GMT) o al [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team?locale=es Equipo de Evaluación de Nominaciones] (o NAT).",
    "report": "Los moderadores no siempre están disponibles, también son humanos y no pueden estar en el chat todo el día. En caso de que notes a alguien haciendo algo que no debe, por favor repórtalo usando el comando !report <usuario> <motivo del reporte>, alguien vendrá a ayudar enseguida. Abstente de usar este comando en PMs con BanchoBot.",
    "report-abuse": "Por favor no envies múltiples reportes - no ayudarás a que se actue más rápido. Tampoco hagas reportes en blanco o sin razón aparente.\nEn su lugar, terminarás silenciado por hacer spam a los moderadores de chat.",
    "request": "¿Buscas algo para moderar? Haz clic [https://osu.ppy.sh/p/beatmaplist&r=8 aquí] o escribe !request para obtener un enlace a un mapa al azar.",
    "respect": "Por favor, sé respetuoso con los demás jugadores.",
    "roll-abuse": "Por favor, no abuses del comando !roll. Podrías acabar silenciado.",
    "romaji": "Por favor, no utilices el Romaji (japonés romanizado) excesivamente. Podrías acabar silenciado.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Si no hay salas para jugar, ¿por qué no creas la tuya? ¡Así, tú también podrás escoger canciones!",
    "rp": "Eres libre de actuar como cualquier personaje en los canales apropiados de osu!; sin embargo, debes asegurarte de no ser molesto a las otras personas del canal.",
    "rules": "[https://osu.ppy.sh/wiki/es/Rules Reglas oficiales de osu!]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "De vez en cuando, osu! recibe un ataque DDoS. Durante este tiempo, Bancho podría ser inestable o no funcionar.\nSi sospechas que esto ha pasado, comprueba el twitter de [https://twitter.com/osustatus @osustatus] o esta [https://status.ppy.sh web] para más información.\nSi esto pasa, pero tú aún puedes hablar - continua normal. Con difundir el tema, no harás que se vaya más rápido.",
    "sb": "Guías de Storyboard en Español: https://osu.ppy.sh/forum/t/27106",
    "scorev2": "scorev2 es un nuevo algoritmo de puntuación que limita los puntajes de todos los modos de juego a 1 millón de puntos, excluyendo los spinners y mods.\nTambién cambia el comportamiento de los sliders por lo que requieren el mismo timing que los hitcircles.",
    "scoring": "Cómo osu! calcula el puntaje: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Estar silenciado implica que no puedes escribir en el chat o publicar mensajes en los foros, salvo en la categoría Help.\nLa primera sanción conlleva 5 minutos de silencio. Este tiempo se duplica por cada sanción posterior. Si la falta es muy grave, el tiempo de sanción puede aumentar más del doble.\nLos silencios se aplican como castigo para la mayoría de faltas leves, así que sigue las normas y estarás bien.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "Guía básica para la creación de Skins en Español: https://osu.ppy.sh/forum/t/27106",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY No dejes que osu! te mantenga despierto hasta las 4 AM. ¡Dormir también es importante!]",
    "songs-not-appearing": "Si tus mapas no aparecen en la lista de selección, presiona F5 para actualizar.",
    "spaces": "Por favor no pongas espacios entre cada letra, podría resultar desagradable para otros usuarios y que seas silenciado por ello. ",
    "spam": "Por favor no hagas spam. Es molesto y puedes resultar silenciado.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Para ver cómo juega otro jugador, escribe /watch <nombre de usuario> o haz clic sobre el usuario en la lista de usuarios conectados y selecciona la opción Empezar a espectar. Asegúrate de haber descargado el mapa que el usuario está jugando.",
    "spoiler": "Escribir detalles de la trama de algún anime, serie, manga y sus formatos relacionados está prohibido y puedes resultar silenciado. ¡Por favor deja a la gente disfrutar sus cosas favoritas en paz! (también aplica escribir detalles que sus respectivos autores no han revelado).",
    "status": "Para ver las actualizaciones del estado del sistema de osu!, consulta [http://twitter.com/osustatus @osustatus]. Para ver el estado del servidor, mira [https://status.ppy.sh esto].",
    "store": "[http://store.ppy.sh/ Bienvenido al osu! store], el lugar donde podrás encontrar diferentes productos de osu!",
    "submit": "[https://osu.ppy.sh/wiki/Submission FAQ de publicación de mapas]",
    "suck": "osu! tiene una larga curva de aprendizaje. No te preocupes, ya mejorarás con la práctica.",
    "supporter": "Siendo un [https://osu.ppy.sh/p/support osu! supporter] obtendrás varios beneficios extra, ¡y ayudarás al equipo de desarrollo para ser más productivos!",
    "supporter-please": "Por favor, no pidas supporter a los demás; es molesto y no te hace halagos. [https://osu.ppy.sh/p/support ¿Por qué no lo compras tú?]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Si el cursor está volando por todas partes cuando intentas moverlo, asegúrate de que la sensibilidad del ratón está ajustada a 1.00x dentro del juego. Una mayor sensibilidad puede lograrse reduciendo el área activa de la tableta.\nSi el cursor no se mueve en absoluto, asegúrate de desactivar el puntero directo (Raw Input) en las opciones. Si tienes algun otro problema para jugar con una tableta gráfica [https://osu.ppy.sh/forum/t/13036 Lee este tema].",
    "tag": "En el modo tag multijugador, todos los jugadores juegan un mismo mapa por turnos. No hay ganador ni perdedor, ya que todos los jugadores pertenecen al mismo equipo.\nLas ruletas se hacen en grupo. Si un jugador falla al completar una ruleta, se pierde el combo. Los bonos de las ruletas de cada jugador se añaden a la puntuación total del equipo.",
    "taiko": "Se trata de un tambor japonés utilizado en varios videojuegos de Bandai-Namco. El modo Taiko de osu! simula estos videojuegos con alguna variación para centrar al jugador en seguir el ritmo de la canción.\n[https://osu.ppy.sh/forum/t/4363 Cómo jugar]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/357592 Cómo crear un mapa para Taiko]",
    "taiko-maps": "Puedes encontrar mapas reales de Taiko no Tatsujin [https://osu.ppy.sh/forum/t/5397 aquí.]",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "¿Podrías por favor dejar el tema y hablar de algo más apropiado?",
    "training": "[https://osu.ppy.sh/forum/t/4280 Entrenamiento de James]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 Lista de vídeo tutoriales de osu! y creación de mapas.] También puedes crear tu propio vídeo tutorial y publicarlo en este hilo. [https://osu.ppy.sh/forum/t/60228 Listado de guías para creadores de mapas y moderadores]",
    "twc": "Es el Torneo mundial de osu! Taiko [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ Lee este hilo] para más información.",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Por favor abstente de usar caracteres unicode (caracteres ajenos al [https://puu.sh/yZzqu.jpg Código ASCII] ), Puedes ser silenciado.",
    "upload-cap": "Para mantener mappers dedicados en sus mapas en progreso, se estableció un pequeño límite de mapas subidos.\nLos usuarios normales pueden tener entre 3-6 mapas activos, y los donadores pueden tener de 5-10 mapas activos. Estos límites incrementarán +1 por cada mapa rankeado que tengas.",
    "utf8": "Configura tu cliente IRC para utilizar codificación UTF-8, así podrás entender a otros, leer y enviar mensajes a otros usuarios",
    "videogames": "Los temas de videojuegos pueden ser discutidos en el chat, pero si molesta al chat o interrumpe la conversación actual, por favor ve a #videogames.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Bienvenido a osu!, si tienes algún problema o duda que necesita una respuesta, pregunta a la buena gente de #help ¡Mantén el chat ordenado y diviértete! ",
    "when": "Cuando esté listo.",
    "wiki": "[https://osu.ppy.sh/wiki/ La osu! wiki] - ¡Ayuda a mejorarla!",
    "wiki-link": "Puedes crear un enlace a una página de la wiki escribiendo el nombre de la página entre corchetes dobles: [[ ]]\nPor ejemplo, [[ES:Kudosu]] se ha creado al escribir ES:Kudosu entre [[ ]].",
    "zallius": "His eyes have awakened.",
    "countfaq": "En este momento hay 216 FAQs activos (completados de unos 217 en total) en el idioma Spanish (Español)",
    "completion": "En la actualidad, los FAQs de Spanish (Español) están 99.54% completados, sumado en total con el resto de los FAQs: 80.74% completado.",
    "mptimer60": "¡El tiempo de MP fue puesto a 60 segundos!"
}
