
strings = {
    "academy": "[https://www.youtube.com/user/osuacademy Klikkaa tästä] nähdäksesi osu!akademian - Videokurssit kaikista asioista jotka liittyvät osu!",
    "achievements": "Saat saavutuksia suorittamalla jotain erikoista kappaleen aikana, kuten saamalla massiivisen kombon tai pelaamalla kaikki beatmapit teemapaketissa. Profiilisi näyttää mitkä saavutukset sinulla on, ja mitä tarvitset. Jotkin nimistä ovat vihjeitä siihen mitä sinun pitää tehdä saadaksesi saavutuksen!",
    "add-skin": "Lisätäksesi uuden skinin, lataa ja raahaa tiedosto osu!:n ikkunaan tai kaksoisklikkaa sitä.",
    "advertising": "osu!un liittymättömän sisällön mainostaminen ei ole sallittua ja saattaa saada sinut hiljennetyksi.",
    "answer": "Jos kukaan ei vastaa sinulle, on mahdollista että kukaan ei tiedä vastausta! Yritä etsiä foorumeilta onko se osu!un liittyvää.",
    "appeal": "Jos joudut hiljennetyksi ja luulet että se oli epäreilua, ota yhteyttä järjestelmänvalvojaan lähettämällä sähköpostin joka selittää tilanteesi accounts@ppy.sh. Muista kuitenkin, että järjestelmänvalvojat ovat ihmisiä myös! Jos olet mukava heille, on todennnäköisempää että he yrittävät parhaansa poistaakseen hiljennyksen, jos se on mahdollista.",
    "approved": "Hyväksytyt rytmikentät eivät voi tulla rankatuksi syystä tai toisesta - yleisimmin ovat kenttiä joiden pituus on 5 minuuttia tai enemmän yhdellä vaikeustasolla, joskus 2-5, sijoitustaulun kera ja kaikkea! Sinä tiedät onko rytmikenttä hyväksytty jos kentän kuvake on liekki eikä sydän.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire, tärkeä korkea-tasoinen osu! rytmikentän teko kilpailu tulee takaisin 2017 Helblinden biisin kera. [http://osu.ppy.sh/news/156171674413 Katso se täältä!]",
    "ask": "Paras tapa saada vastaus on vain kysyä kysymys suoraan! Saisinko kysyä jotain on jo kysymys.",
    "attention": "Voitko lopettaa kiitos? Kukaan ei oikeasti kuuntele mitä sanot...",
    "avatar-change": "Sinä voit vaihtaa avatarisi [https://osu.ppy.sh/home/account/edit#avatar täältä].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Hei! Olen BanchoBot! Hauska tavata.\nOlen kuitenkin botti, joten en voi oikeastaan käydä keskustelua kanssasi :(",
    "beatmapping": "Tässä muutama hyödyllinen vinkki  [https://osu.ppy.sh/wiki/Beatmapping beatmapping!]",
    "beginner": "Napsauta [https://osu.ppy.sh/forum/t/5456 tästä] jos olet etsimässä karttoja aloittelijoille.",
    "bn": "[[Beatmap Nomination Group]] on ryhmä ihmisiä jotka ovat vastuussa rytmikarttojen sijoittamisesta ja sijoitus jaksossa vireillä olevien rytmikarttojen moderoinnin käsittelystä. Voit puhua heille jos sinulla yhtään kysymyksiä tai jos tarvitset neuvoja kartoittamiseen tai modaamiseen. He ovat kiireellisiä ihmisiä, joten vältä heidän spämmäämistä!",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Jos sinä olet oikeasti  tylsistynyt, mene tekemään jotain muuta. Internetissä on paljon muuta. Tylsyys ei ole tekosyy vinkumiselle tai spämmäämiselle osu!ssa.]",
    "bug": "Jos luulet löytäneesi ongelman, ilmoita se [https://osu.ppy.sh/forum/5 täällä]. Varmistathan ettei kukaan muu ole jo ilmoittanut ongelmasta.\n",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Älä käytä isoa kirjainta jokaisen sanan alussa - se saa kaiken kirjoittamasi näyttämään tyhmältä.",
    "caps": "Älä kirjoita kaikkea isolla. Se ei ole toivottua chatissa, ja voi saada sinut hiljennetyksi.",
    "change-modes": "Vaihtaaksesi toiseen pelimuotoon, mene kappaleenvalintaan ja joko klikkaa Modea alavasemmalla tai käytä näppäinyhdistelmää Ctrl + 1-4. Muista, että jotkut mapit ovat pelimuoto kohtaisia!",
    "change-name": "Vaihtaaksesi käyttäjänimesi, sinusta täytyy aluksi tulla [https://osu.ppy.sh/p/support osu! tukija]. Sitten voit vaihtaa nimesi   [https://store.ppy.sh/store/product/32 täällä]! Pyytäksesi palautusta vanhaan käyttäjänimeesi, pieniin muutoksiin tai apuun lähetä sähköpostia accounts@ppy.sh yksityiskohtien kanssa.",
    "changelog": "Kaikki päivitykset peliin, Banchoon ja nettisivuun löytyy osu!n kehitys [https://osu.ppy.sh/p/changelog lokista!]",
    "chars": "Vältä unicode kirjaimien käyttöä yleisessä chatissä. ",
    "charts": "osu! chartsit ovat kuukausittain julkaistuja teemallisia pakkauksia. Löydät ne [https://osu.ppy.sh/p/chart täältä!]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Vaaleankeltainen: Tavallinen Käyttäjä | Keltainen: [https://osu.ppy.sh/p/support Tukija] | Punainen: [https://osu.ppy.sh/wiki/QAT QAT]:n tai [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]:n jäsen | Valkoinen: Sinä itse tai /me viesti | Tummansininen: Yksityisviesti | Vihreä: Rivi, jossa sinut mainitaan (highlight) | Pinkki: BanchoBot",
    "colour": "Vaaleankeltainen: Tavallinen Käyttäjä | Keltainen: [https://osu.ppy.sh/p/support Tukija] | Punainen: [https://osu.ppy.sh/wiki/QAT QAT]:n tai [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]:n jäsen | Valkoinen: Sinä itse tai /me viesti | Tummansininen: Yksityisviesti | Vihreä: Rivi, jossa sinut mainitaan (highlight) | Pinkki: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Vaikka chatti komennot ovat käytön helpottamiseksi, älä käytä niitä liika. Tämä nähdään spämmiksi ja voi johtaa hiljennykseen.",
    "comment": "Jos sinusta tuntuu että haluat tehdä live huomautuksen rytmikentän uusinnassa, paina Discussion nappia, kirjoita jotain ja paina enteriä! Jos ruudulla ei ole kommentteja valmiiksi, valitse Show Comments laatikko Discussion paneelista.",
    "comment-color": "Normaali käyttäjä voi kommentoida ainoastaan valkoisella. [https://osu.ppy.sh/p/support Tukija] voi kustomoida kommentti väriään.",
    "conferencemode": "Tulviiko Join/Quit viestit IRC:n? [http://wiki.xkcd.com/irc/Hide_join_part_messages Tämä] saattaa auttaa!",
    "country-ranking": "Katso eri [https://osu.ppy.sh/p/countryranking] maiden tulostaulu täältä.",
    "critic": "Pidä kritiikki rakentavana. Ehdota vaihtoehtoja tai tapoja korjata ongelmia joista olet huolissasi.",
    "ctb": "Tarvitsetko apua Catch the Beatissa? [https://osu.ppy.sh/wiki/Catch_the_Beat Tässä] sen wikisivu!",
    "cutting-edge": "Cutting-edge on kokeilullinen versio osu!sta jota käytetään uusien ominaisuuksien testaamiseen ennenkuin ne lisätään stable versioon. Voit vaihtaa versiota asetuksista! Voit [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues lukea tämän artikkelin] jos sinulla on ongelmia clienttisi päivittämisessä.",
    "cwc": "Maailmanlaajuinen osu! Catch The Beat turnaus. Katso tämä [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 wiki page] saadaksesi lisää infoa.",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Kohtele toisia niin kuin haluaisit itseäsi kohdeltavan. Jos olen jonkin sortin verbaalinen masokisti, oleta että kaikki muut eivät ole.",
    "disable-this": "Valinnat ovat harvoin lisätty ominaisuuksille. Voit silti pyytää jotain lisätyksi [https://osu.ppy.sh/forum/4 ominaisuuspyyntö foorumin] kautta.",
    "distance-snap": "Distance Snap on työkalu joka pitää nuottejen välisen suhteellisen etäisyyden oikeana niiden timeline sijainnin perusteella. Lisätietoja: [[Distance Snap]]",
    "dont-ask-peppy": "Älä koko ajan kysele peppyä - hän on aika kiireellinen. Olet kyllä tervetullut kysymään keltä tahansa muulta tällä kanavalla!",
    "douche": "Sääntöjen porsaanreikien hyväksikäytön estämiseksi adminit voivat rangaista tälläisestä toiminnasta oman harkintansa mukaan. Älä ole kusipää.",
    "download": "Voit ladata lisää rytmikarttoja [https://osu.ppy.sh/p/beatmaplist?q= täältä] ja rytmikartta pakkauksia [https://osu.ppy.sh/beatmaps/packs täältä]. Jos et tiedä miten siirtää niitä, lue [http://i.imgur.com/kpX2N3m.jpg tämä].",
    "drugs": "Huumeista tai huumeiden käytöstä puhuminen osu!:ssa on kiellettyä.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Lue [[Beatmapping#Keyboard_Shortcuts]] löytääksesi listan editorin pikanäppäimistä.",
    "english": "#english on yleisellä keskustelulle jolle ei ole omaa kanavaa. Kyllä, se sisältää animen/mangan. Ja junat.",
    "evade": "Hiljennysten vältteleminen voi johtaa käyttäjätilisi rajoittamiseen pitkäksi ajaksi. Älä tee sitä.",
    "fallback": "Stable (Fallback) on vanhentunut versio osu!sta. Toisinkuin Fallback, uusimmat julkaisut poistavat DirectX tuen, yksinkertaistaakseen meidän puitteet. Jos olet vaihtanut tähän versioon, sinun PC on huonolaatuinen eikä se tue uusinta tai tulevaisuuden asiakasohjelma versioita. Jos haluat pelata nykyisessä versiossa nyt, päivitä sinun grafiikkakortti sekä tee niille OpenGL tuki, kaikista tarvituin täydennys näille versioille. [https://osu.ppy.sh/wiki/GL_Support_Issues Klikkaa täältä tietääksesi miten].",
    "faq": "Käytät tällä hetkellä osu!Bancho FAQ systeemiä.\r\nosu!wiki: https://osu.ppy.sh/wiki",
    "feature": "Jos sinulla on idea tälle pelille, postaa se [https://osu.ppy.sh/forum/4 tähän subforumiin.",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Chatin filtterien vältteleminen voi johtaa hiljennykseen. Älä tee sitä.",
    "foul-play": "Ilmoita huijareista käyttämällä report user nappulaa heidän profiilissaan, joka löytyy [https://i.imgur.com/GG9xlLA.png täältä].\nAnna niin paljon tietoa kuin mahdollista. Voit myös ilmoittaa heidän pisteytyksiä top 50 tulostaulukoissa kartan sivulla.\nÄLÄ puhu tästä julkisessa chatissa, koska voit saada hiljennyksen.",
    "percolate": "Chatin filtterien vältteleminen voi johtaa hiljennykseen. Älä tee sitä.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Tämä artikkeli] auttaa sinua ymmärtämään kartoittamiseen virran.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Lisätääksesi käyttäjän kaveriksi, kirjoita /addfriend jonka jälkeen kyseisen käyttäjän nimi.\r\nLisäksi voit klikata käyttäjän nimeä chatissa tai F9:stä saatavan paneelin kautta ja valita Lisää kaveriksi.\r\nVoit myös lisätä heidät heidän profiilistaan painamalla Add as Friend.",
    "friends-list": "Nähdääksesi listan online kavereistasi pelissä, paina F9, sitten valitse ylhäällä olevasta filtteristä Kaverit.\r\nVoit myös nähdä listan kaikista kavereistasi, online ja offline, valitsemalla kohdan Settings nettisivulla. (Pitää tietenkin olla kirjautunut sisään.)",
    "fullscreen": "Voit vaihtaa peliä kokoruudun ja ikkunan välillä Grafiikat kohdasta asetuksista.\r\nVaihtoehtoisesti voit vaihtaa näiden välillä näppäinyhdistelmällä Alt+Enter.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Voit löytää paljon osu! sanastoa täältä [[glossary]]",
    "gmt": "[https://osu.ppy.sh/wiki/People/Global_Moderation_Team Globaali Moderaatio Teami], lyhyesti [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT], on joukko käyttäjiä jotka auttavat osu!n toiminnassa. Heillä on punaiset nimet chatissa ja vihreät nimet foorumilla.\nNämä henkilött auttavat moderoimaan foorumia ja chattia.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Lue, kertaa, iloitse.] ",
    "grammar": "Tee parhaasi käyttääksesi kunnon kielioppia. Muutama virhe oikeinkirjoituksessa ja välimerkeissä on ymmärrettävää, mutta älä käytä pikakirjoitusta tai paljon lyhennyksiä. Se saa sinut näyttämään tyhmältä. ",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Et tiedä miten pelata? Haluatko tutkia kartoittamisen ja modaamisen maailmaa? [https://osu.ppy.sh/wiki/Guides Täältä] löydät kaikki vastaukset.",
    "hacked": "Jos uskot, että käyttäjätilisi on hakkeroitu, laita sähköpostia asiasta osoitteeseen accounts@ppy.sh.\r\nTämän tekemättä jättäminen voi johtaa käyttäjätilin sulkemiseen.",
    "hard": "Opi pelaa skrubi.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Jos tarvitset apua jossain osu!un liittyvässä asiassa, liity #help-kanavalle ja kysy siellä kysymyksesi! #help on myös monikielinen kanava. Jos kukaan ei vastaa, voit postata [https://osu.ppy.sh/forum/5 Tuki] foorumille sen sijaan. Voit myös lukea [http://help.ppy.sh/ tämän sivun] hyödyllisten artikkelien löytämiseksi, mukaan lukien käyttäjään liittyvät ongelmat.",
    "hitsound-library": "Mene [https://osu.ppy.sh/forum/p/164927 tänne] jos haluat custom osumaääniä karttaasi.",
    "hl": "Älä syytä muita käyttäjiä sinun korostamisesta jos sinulla on nimenä jokin sanakirjasana tai muu yleinen lausahdus. Se on kuitenkin oma vikasi! Voit poistaa huomautukset käytöstä ja sen äänen pelin asetuksista.",
    "how-to-get-modded": "Jos haluat tietää miten saat karttasi tarkistetuksi, napsauta tätä: [[Getting_Your_Map_Modded]]",
    "how-to-bn": "Jos haluat olla BN, lue [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator tämä]",
    "how-to-gmt": "Jos olet kiinnostunut ylläpitäjän paikasta, niin on hyvin mahdollista ettei sinusta tule sellaista. Toisin sanottuna: Älä kysy meiltä, me kysymme sinulta.",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#how-to-play? Klikkaa tätä linkkiä oppiaksesi pelaamaan!]",
    "how-to-rank": "Selvittääksesi, lue [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Hypersyöksy tapahtuu kun nappaat punaisena hohtavan hedelmän. Syöksyt normaalia nopeammin tämän aikana. Se lakkaa toimimasta kun saavutat seuraavan hedelmän, tai kun tulee huti. ",
    "ignore": "Ignorataksesi käyttäjän, kirjoita /ignore ja sitten käyttäjän nimi.\nTäten et nää kyseisen käyttäjän viestejä chatissa etkä heidän PM:iä joita he saattavat lähettää sinulle.\nJos kirjoitat /unignore (käyttäjänimi) tai suljet osu!n, tämä vaikutus lakkaa. Ignorataksesi jonkun lopullisesti, katso [http://help.ppy.sh/article/141/how-do-i-completely-block-another-user-from-contacting-me tänne].",
    "import": "Lue [http://i.imgur.com/kpX2N3m.jpg tämä] selvittääksesi miten importata rytmikarttoja osu!n",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Tsekkaamalla laatikon Peri aiemmat ajoitusasetukset F6 ikkunassa editorissa, ajoitus sektio ei vaikuta ajoitukseen enää, mikä on hyödyllistä sektioille mitkä vaihtavat vain äänenvoimakkuutta tai kentän samplea. On myös mahdollista periä ajoitus sektioita missä on kaksinkertainen tai puolitettu BPM. Jos löydät itsesi käyttämässä ajoitus sektiota näin, peri kiitos.",
    "irc": "IRC serveri: irc.ppy.sh:6667\nSalasana: https://osu.ppy.sh/p/irc\nLisätietoja: https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Voit vaihtaa näppäinasetuksiasi pelin asetuksista. Näppäimet ja asettelut osu!maniaan vaihdetaan osu!mania asettelu painikkeesta.",
    "kiai": "Kiai moodi on tyyli efekti jonka voit asettaa ajoitus sektioon käyttämällä Ajoitus Järjestys Paneelia. Ajoitus sektiot kiai moodi käytössä käyttävät erilaisia visuaalisia efektejä tehdäkseen rytmikentästä enemmän eeppisen.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Ansaitse [https://osu.ppy.sh/wiki/Kudosu kudoja] modaamalla muiden ihmisten rytmikarttoja.",
    "lag": "Lagaaminen voi johtua [https://osu.ppy.sh/help/wiki/Performance_Troubleshooting mistä vaan] - todennäköisemmin muut prosessit koneellasi. Jos olet vakuuttunut että se on osu! ja vain osu! joku lagaa, jätä tuki pyyntö [https://osu.ppy.sh/forum/5 Apu foorumeille] jossa kuvailet ongelmasi ja jos olet löytänyt jotakin mikä voi auttaa sen tunnistamisessa.",
    "language": "Ole ystävällinen chat-kanavilla. Asiaton kielenkäyttö voi johtaa hiljennykseen.",
    "language-specific": "Käytä asianomaista kieltä käymälläsi kanavalla. Romanisoitujen sanojen tai lauseiden käyttäminen ei ole poikkeus ei-romanisoiduille kielille kuten Japanille.",
    "lazer": "",
    "level": "Levelisi perustuu Total Score valueen. Tähän sisältyy kaikki scoret, vaikket pääsisi mappia läpikään. Levelisi nousee vain pelaamalla osu!a.",
    "lines": "Yritä opetella kirjoittamaan yhdelle riville välttääksesi hiljennyksen.",
    "link": "Tehdäksesi teksimuotoisen linkin, käytä formaattia: [linkki teksti], jossa 'linkki' on se osoite jonka haluat linkata, ja teksti on se teksti minkä haluat näkyvän. [https://osu.ppy.sh/ Juuri näin!] Älä kuitenkaan unohda lisätä http://.",
    "lobby": "Käytä #lobbya vain osu! moninpeli pelien mainostamiseen. #lobby on moni-kielinen kanava. Käytä huoneesi #multiplayer kanavaa muihin keskusteluihin.",
    "localisation": "Löydät osu! lokalisointi projetkin [https://docs.google.com/spreadsheet/ccc?key=9AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 täältä]",
    "long-link": "Älä liitä pitkiä linkkejä chattiin! Käytä [linkki teksti] formaattia, jos sinun kuitenkin täytyy.",
    "long-text": "Älä liitä pitkiä tekstejä chattiin. Se voi johtaa hiljennykseen.",
    "loved": "Rakastettu on uusi yhteisöpohjainen sijoitus aste joka antaa täydet pistetaulut kartoille joita ei normaalisti sijoitettaisi. [https://osu.ppy.sh/news/151925254083 Lue lisää täältä!]",
    "mac": "[https://osx.ppy.sh Pelaa osu!a Macilla]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Kartoittajat ovat kiireisiä ihmisiä, ja mappaaminen vie paljon aikaa. Mikset kokeile mappaamista itse?",
    "mapping": "Mene [https://osu.ppy.sh/forum/p/988111 tänne] kartoittamis oppaita varten.",
    "mat": "MAT (Mapping Assistance Team) oli vanha käyttäjäryhmä joka avusti BATia sijoittelussa. Lepää rauhassa MAT 23.4.2013",
    "modhelp": "Kaikille rytmikartta modaus kyseilylle, suuntaa #mapping kanavalle!",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modaus jonot]",
    "modreqs": "Mene #modreqs kanavalle modaus pyynnöille. Muista että BNllä ei ole aina aikaa ja että heillä on muita ihmisiä jotka ovat pyytänyt ensin joten muista myös kysyä normaaleita käyttäjiä modaamaan rytmikarttasi. Luodaksesi pyynnön, muista käyttää /np komentoa tai [linkki teksti] formaattia. Älä unohda sanoa kiitos! ",
    "multi-invite": "Kutsuaksesi toisia pelaajia moninpeliisi, klikkaa haluttua käyttäjää Online-käyttäjät -valikosta (paina F9) tai klikkaa heidän nimeään chatissa ja valitse Kutsu peliin.\r\nVoit myös kirjoittaa /invite ja sen jälkeen sen käyttäjän nimi jonka haluat kutsua.",
    "multi-link": "",
    "multiaccounting": "Sinun ei todellakaan pitäisi tehdä montaa käyttäjää. Sinut löydetään, ja voit saada hiljennyksen todella pitkäksi aikaa, tai saada rajoituksen.",
    "multiplayer": "Älä mainosta moninpeli pelejä muilla kanavilla kuin #lobby.",
    "mwc": "Maailmanlaajuinen osu! Mania turnaus. Lisätietoja varten lue [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 tämä].",
    "nat": "",
    "news": "",
    "nightcore": "Nauti suosikki rytmikartoistasi Nightcore tyylillä! Klikkaa DoubleTime modia uudestaan paljastaaksesi Nightcore modin! Se on pisteytyksessä identtinen DoubleTimen kanssa.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Kirjoita /np kertoaksesi ihmisille mitä kappaletta kuuntelet tai mitä mappia sinä olet pelaamassa.",
    "nsfw": "Epäsoveltuva keskustelu on kiellettyä. osu! on tarkoitettu kaikenikäisille, joten pitäkää chatti puhtaana, tai riskaatte saavanne hiljennyksen ilman varoitusta.",
    "osu": "#osu on osu!sta puhumista varten. Mene keskustelemaan pelistä sinne, ei tänne kanavalle.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 osu!tabletin virallinen lanka!] - Lue tämä kaikkia tabletin tietoja ja ennakkotilaus vaihtoehtoja varten.",
    "osu!talk": "osu!talk on deadbeatin ja ztrotin juontama talk show jossa he haastattelevat yhteisön jäseniä ja keskustelevät tapahtumia kuten maailmanmestaruuksia. Jokainen jakso tapahtuu [https://discord.gg/014x1ACj2VdUPLU5x discord palvelimella]; voit kysyä kysymyksiä Q&A osiossa. Lisätietoja löytyy [https://osu.ppy.sh/forum/t/225111 täältä.]",
    "osucore": "2011 aprillipila vitsi. Kaikki kartat asetettiin oletuksena DoubleTime nopeudella ja niiden sävelkorkeus nostettiin. Myöhemmin tämä palasi Nightcore modina jolla on sama vaikutus kuin DoubleTimella sinä päivänä.",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] on alkuperäisestä pelistä tehty peliportti Android alustalle. Viralliset kehittäjät hylkäsi projektin ja on poistettu Google Play Storesta vuonna 2016 toimeettomuuden ja huonojen arvostelujen vuoksi.",
    "osumania": "Käytä #osumania kanavaa osu!maniaan liittyviä keskusteluja varten.",
    "osustream": "[http://www.osustream.com osu!stream] on peppyn luoma ja ylläpitämä osu! iOS laitteille!",
    "osz": "Rytmikartta tiedostomuoto jonka lataat osu!lle purettavaksi jotta voit pelata. osu!n itse täytyy aina purkaa osz tiedostot, muuten ongelmia voi muodostua.",
    "osz2": "Uusi rytmikartta tiedostomuoto joka tarkoittaa että jokainen sisäinen tiedosto voidaan salata, päivittää ja lähettää itsenäisesti muista tiedostoista. osz2 tiedostoja ei tarvitse purkaa ja ne pysyvät aina .osz2 tiedostoina Songs kansiossasi.",
    "owc": "Maailmanlaajuinen osu! turnaus. Lisätietoja saat [https://osu.ppy.sh/wiki/OWC wikisivuilta.]",
    "peppy": "peppy on pääkehittäjä, osu!n luoja ja hoitaa suurimmanosan projektista itse.",
    "perfect": "Et saanut SS suoritusta? Tämä modi automaattisesti aloittaa kartan uudelleen kun teet virheen. Löydät sen napsauttamalla SuddenDeath modia oikealla hiirenpainikkeella modi valikossa.",
    "ping": "Pong!",
    "pippi": "osu!n maskottihahmo. Pippi-don on taiko (rumpu) versio Pippistä.",
    "piracy": "Älä keskustele tekijänoikeutetun sisällön piratointia general chatissa. Se on kiellettyä ja voi johtaa hiljennykseen.",
    "play-shortcuts": "Täysi lista pikanäppäimistä: [[Shortcut_Key_Reference]]",
    "pm": "Lähettääksesi yksityisviestin jollekkin, klikkaa heidän nimeään chatissa tai käyttäjäpaneelissa (F9 valikko), ja sitten Aloita chattaaminen.\r\nVoit myös käyttää komentoa /msg <käyttäjänimi> tai /chat <käyttäjänimi> tai /query <käyttäjänimi>, joka avaa erillisen sivun chatissa.\r\nPikavastatus viimeisimpään viestiin onnistuu käyttämällä komentoa /r <viesti>. Ilman < > merkkejä tietenkin.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance Points (pp) on pää sijoitus mittayksikkö osu!lle. Lisätietoja saat napsauttamalla [https://osu.ppy.sh/wiki/Performance_Points tätä.]",
    "pp-rework-lazer": "",
    "preview": "Esikatselupiste on kohta laulussa josta se alkaa soimaan lauluvalikossa. Hyvä esikatselupiste alkaa kohdasta mikä edustaa laulua hyvin, kuten kertosäkken alku.Valitaksesi kohdan mene Ajoituksiin työkalurivissä ja klikkaa Aseta nykyinen kohta esikatselupisteeksi. Muista valita kaikista edustavin kohta, esimerkiksi: kertosäe.",
    "qat": "",
    "qualified": "Rytmikenttä Nimittäjät nimittävät kentät päteviksi rankkaamista varten missä voit saada sijoituksia ilman PP:tä. Jos näissä kentissä ei ole vikaa ja ovat päteviä viikon ajan, niistä tulee rankattuja. Muuten, ne menevät takaisin odottaviin ja pisteet pyyhitään pois.",
    "ranked": "Rankattu beatmappi on beatmappi joka on online yhteisön hyväksymä. Kun pelaat Rankattua mappia, pisteet siitä lasketaan kohti sinun kokonais ranked pisteisiin. Näillä mapeilla on omat rankatut pistetaulukot ja voidaan tunnistaa Sydän kuvalla.",
    "ranking-criteria": "Lisätietoja rankkaus kriteereistä saat wikistä: [[RC]]",
    "redname": "Käyttäjät, joilla on punaiset nimet, kuuluvat joko [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Globaaliin Moderaatio Teamiin] tai [https://osu.ppy.sh/wiki/QAT Quality Assurance Teamiin]",
    "report": "Käytä seuraavaa formaattia ilmoittaaksesi epäasiallinen käytös tai huijaaminen: !report <käyttäjänimi> <syy>\r\nIlmoitukset eivät näy tavallisille käyttäjille ja ne on tehtävä virallisissa chatti kanavissa. Vältä sen tekemistä ykskityisviesteissä.\r\nVoit myös ilmoittaa jonkun klikkaamalla heidän nimeään jonka jälkeen Ilmoita pelaajasta",
    "report-abuse": "Yritä välttää monen peräkkäisen ilmoituksen lähettämistä - se ei auta ratkaisemaan tilannetta nopeammin. Kuten eivät tyhjät tai turhat ilmoitukset.\r\nVoit jopa saada hiljennyksen moderaattorien spämmäämisestä.",
    "request": "Etsitkö jotakin modattavaksi? Klikkaa [https://osu.ppy.sh/p/beatmaplist&r=8 tästä] tai kirjoita !request satunnaista mappilinkkiä varten.",
    "respect": "Ole kunniottava muita pelaajia kohtaan.",
    "roll-abuse": "Älä ylikäytä !roll komentoa. Se voi johtaa hiljennykseen.",
    "romaji": "Älä käytä Romajia (Romanisoitu Japani) liikaa. Se voi johtaa hiljennykseen.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Jos ei ole yhtään moninpelihuoneita johon liittyä, miksei luoda oma? Sitten sinäkin voit valita laulut!",
    "rp": "Olet tervetullut roolipelaamaan tarkoituksenmukaisissa osu! kanavissa; sinun kuitenkin kannattaa varmistaa että et häiritse liikaa muita ihmisiä kanavalla.",
    "rules": "[https://osu.ppy.sh/wiki/fi/Rules Viralliset pelin säännöt]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "Aika ajoin osu! DDoSataan. Siihen aikaan Bancho saattaa olla epävakaa tai saavuttamaton. Jos epäilet että näin on tapahtunut, tarkista [https://twitter.com/osustatus @osustatus] Twitter feedi tai [https://stat.ppy.sh tämä] lisätietoja varten. Jos näin tapahtuu ja voit silti puhua niin jatka normaalisti. Asian mainitseminen ei saa sitä menemään pois nopeammin.",
    "sb": "[[Storyboarding]] Storyboardaus opas: https://osu.ppy.sh/forum/t/1869 Miten käyttää Storyboard Editoijaa: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "scorev2 on uusi pisteytys algoritmi joka rajoittaa pisteet joka peli muodossa miljoonaan pisteeseen, pois lukien spinnerit ja modit. Se myös vaihtaa sliderien käytöstä siten, että ne tarvitsevat saman ajoituksen kuin hitcirclet.",
    "scoring": "Kuinka osu! laskee pisteet: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Hiljennys tarkoittaa sitä, että et pysty puhumaan chatissa tai lähettämään viestejä foorumeille, paitsi tekniseen tukeen.\r\nHiljennykset alkavat 5 minuutista ensi kerrasta, sitten tuplaantuvat joka kerta. Isommat rikkeet voivat kuitenkin johtaa pidempiin hiljennyksiin.\r\nSiluja jaetaan lähes kaikista rikkeistä, joten tottele vain sääntöjä ja pärjäät kyllä.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Skinnaamisen FAQ]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Älä anna osu!n pitää sinua hereillä kello neljään saakka. Nukkuminen on tärkeää!]",
    "songs-not-appearing": "Jos laulusi eivät ilmesty lauluvalikossa, yritä painaa F5 näppäintä.",
    "spaces": "Älä laita välilyöntiä jokaisen kirjaimen väliin, sinun estetiikka saa chatin näyttämään sekaiselta ja voi johtaa hiljennykseen.",
    "spam": "Spämmääminen on rangaistava teko ja useimmiten johtaa hiljennykseen.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Katsellaksesi toista pelaajaa, kirjoita /watch <käyttäjänimi>, tai napsauta heidän nimeään chatissa tai käyttäjäpaneelissa ja valitse Aloita katsominen. Varmista että sinulla on sama rytmikartta kuin ketä katsot (ja että he oikeasti pelaavat sitä)!",
    "spoiler": "Minkätahansa animen, sarjan, mangan, doujinin yms spoilaaminen on kielletty ja voi johtaa hiljennykseen. Anna ihmisten nauttia heidän lempiasioista rauhassa.",
    "status": "osu! järjestelmän tilannetta varten seuraa [http://twitter.com/osustatus @osustatus]. Palvelinta varten tarkista [https://status.ppy.sh tämä].",
    "store": "[https://osu.ppy.sh/store/listing Tervetuloa osu! kauppaan], paikka missä voit ostaa mahtavia osu! juttuja!",
    "submit": "[https://osu.ppy.sh/wiki/Submission]",
    "suck": "osu!lla on suuri oppimiskaari - sinusta tulee parempi ajanmyötä, joten jatka vaan!",
    "supporter": "Rupea [https://osu.ppy.sh/p/support osu! tukijaksi]!  Saat useita hyötyjä, ja autat kehitystiimiä luomaan lisää!",
    "supporter-please": "Älä pyydä muita ihmisiä lahjoittamaan sinulle tukija tagia. [https://osu.ppy.sh/p/support Hanki se täältä itse!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Jos kursorisi lentelee kaikkialle kun yrität liikuttaa sitä, varmista että pelinsisäinen hiirenherkkyys on asetettuna 1.00x. Voit saada korkeamman herkkyyden vähentämällä tablettisi aktiivista aluetta. Jos kursorisi ei liiky yhtään, varmista että raakasyöttö on pois päältä asetuksissa. Muita tabletteihin liittyviä ongelmia varten lue [https://osu.ppy.sh/forum/t/87301 tämä lanka].",
    "tag": "Tag moninpeli moodissa kaikki pelaajat vuorotellen klikkaavat yhden combon rytmikentästä kerrallaan. Ei ole voittajaa tai häviäjää, sillä kaikki pelaavat samassa tiimissä. Spinnereissä kaikki pelaajat osallistuvat. Jos edes yksi pelaaja epäonnistuu selvittämään spinnerin, combo resetoituu. Jokaisen pelaajan spinner bonus lisätään tiimin pistemäärään.",
    "taiko": "Japanilainen rumpu joka on ollut mukana monessa pelissä Bandai-Namcolta. osu!n Taiko moodi simuloi nämä pelit eliminoimalla rytmin sijoittamisen, pakottaen pelaajan kiinnittämään huomita ainoastaan rytmikentän rytmiin. [https://osu.ppy.sh/forum/t/4363 Tässä kuinka pelata!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Taikon mappausopas]",
    "taiko-maps": "Voit löytää aitoja Taiko no Tatsujien kenttiä [https://osu.ppy.sh/forum/t/5397 täältä.]",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Voisitteko vaihtaa aihetta ja puhua jostakin muusta nyt?",
    "training": "[https://osu.ppy.sh/forum/t/4280 Jamesin Harjoitus]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 Lista viime-aikaisimmista video tutoriaaleista osu!sta ja mäppäämisestä.] Tunne olosi vapaaksi tehdä sinun omasi ja saada se laitetuksi keskusteluaiheelle. [https://osu.ppy.sh/forum/t/60228 Lista hyödyllisistä ohjeista mäppääjille/modaajille]",
    "twc": "Maailmanlaajuinen osu! taiko turnaus.  [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ Lue tämä viestiketju.]",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Vältä unicode/epäyleisiä merkkejä general chatissa. Se voi johtaa hiljennykseen.",
    "upload-cap": "Pitääksemme mäppääjät omistautuneet heidän keskeneräisien karttojen suhteen, on olemassa pieni rajoitus kenttien määrässä jotka voivat olla keskeneräisiä kerralla. Ei-supporterit saavat 3-6 aktiivista ja supporterit saavat 5-10 aktiivista. Nuo edelliset rajat kasvavat +1 riippuen kartoistasi jotka ovat rankattuja.",
    "utf8": "Aseta IRC clienttisi käyttämään UTF-8 salausta jotta voit asianmukaisesti lukea ja lähettää luettavissa olevia viestejä muille käyttäjille.",
    "videogames": "Videopeli aiheisia keskusteluja voi käydä #osu kanavall, mutta jos se häiritsee chattia tai kun useampia keskusteluja on samaanaikaan, mene #videogames kanavalle.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Tervetuloa! Jos sinulla on ongelmia tai kysymyksiä jotka tarvitsevat vastausta, käy #help-kanavalla. Pidä hauskaa!",
    "when": "Kun se on valmis.",
    "wiki": "[https://osu.ppy.sh/wiki/ The osu! Wiki] - Tee siitä mahtava! ",
    "wiki-link": "Voit linkata wikin sivuja ympäröimällä wiki kohdan nimen kaksoissuluilla: [[...]]\r\nEsimerkiksi, [[Kudosu]] luodaan kirjoittamalla Kudosu [[ ja ]] väliin.",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 211 active FAQs (out of a possible 217) in the Finnish (Suomi) language.",
    "completion": "The Finnish (Suomi) FAQ as of last update is 97.24% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
