
strings = {
    "academy": "[https://www.youtube.com/user/osuacademy לחץ כאן] כדי להעיף מבט אל תוך אקדמיית osu! - מדריכים עבור שלל דברים הנוגעים לosu!",
    "achievements": "תוכל להשיג הישגים (achievements) על ידי ביצוע דבר מיוחד בזמן שיר, כמו לקבל קומבו גדול, או משחק של כל המפות שכלולות בתוך חבילת נושא. הפרופיל שלך מראה אילו הישגים השגת, ואילו תצטרך להשיג. חלק מהשמות הם רמזים לדרך בה תוכל להרוויח את ההישג!",
    "add-skin": "כדי להוסיף סקין חדש, הורד אותו וגרור את הקובץ אל החלון של osu! או לחץ עליו פעמיים.\n",
    "advertising": "פרסום חומר שאינו קשור לosu! אינו מורשה, ועלול להביא לידי השתקה.",
    "answer": "אם אף אחד לא עונה לשאלה שלך, ייתכן שאף אחד לא יודע את התשובה! נסה לחפש בפורומים אם השאלה שלך נוגעת לosu!.",
    "appeal": "אם אכן קרה שהושתקת, ואתה חושב שזה היה לא צודק, צור קשר עם המנהלים דרך אימייל ל-accounts@ppy.sh והסבר להם את המצב שלך. אך זכור - גם מנהלים הם אנשים! אם תהיה נחמד אליהם, יש יותר סיכוי שהם ינסו כמיטב יכולתם להוריד את ההשתקה, אם ניתן.",
    "approved": "מפות שאושרו ואינן מדורגות בגלל כל סיבה שהיא, הן עדיין מפות ששחקנים יכולים לשחק בהן, יש להן לוח ניקוד והכל! אתם תדעו שזו מפה שאושרה אם האייקון של המפה הוא להבה במקום לב.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "הדרך הכי טובה לקבל תשובה היא פשוט לשאול את השאלה שלך - אין טעם לשאול האם אפשר לשאול שאלה!",
    "attention": "לאפ'חד לא אכפת על מה אתה מדבר. אולי די?",
    "avatar-change": "תוכלו לשנות את תמונת האווטאר שלכם  [https://osu.ppy.sh/home/account/edit#avatar כאן].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "אהלן! אני באנצ'ו-בוט! נעים להכיר אותך!\nאני רובוט אבל, אז אני לא ממש יכול לנהל שיחה איתך. :^( ",
    "beatmapping": "הנה כמה טיפים יעילים על  [https://osu.ppy.sh/wiki/Beatmapping יצירת מפות!]",
    "beginner": "לחץ [https://osu.ppy.sh/forum/t/5456 כאן] אם אתה מחפש מפות למתחילים.",
    "bn": "ה [[Beatmap Nominaiton Grou]] הם קבוצה של אנשים שאחראים על דירוג מפות ואחראים על ניהול של הכנסת מפות לתוך מעגל הדירוג.\nאתה מוזמן לדבר אליהם אם יש לך כל שאלה או בקשת עצה לגבי עריכת מפות.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY אין טעם להגיד לאנשים שמשעמם לך. קח הפסקה, או נסה לשחק משהו אחר!]",
    "bug": "אם אתה חושב שמצאת באג, דווח על זה [https://osu.ppy.sh/forum/5 כאן]. רק וודא שאף אחד לא כתב כבר על הבעיה הזאת לפניך.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "אנא המנעו מלהשתמש באות גדולה בתחילת כל מילה - זה גורם להכל להיראות נורא",
    "caps": "אנא המנעו מלרשום באותיות גדולות - זה לא רצוי בצ'אט, ויכול להביא להשתקה.",
    "change-modes": "על מנת להחליף למצבי משחק אחרים, עבור למסך בחירת השירים ולחץ על מצב משחק בחלק השמאלי-תחתון של המסך או השתמש בCtrl + 1-4. זכור שחלק מהמפות נוצרו ספציפית בשביל מצב משחק מסוים!",
    "change-name": "כדי לשנות את שם המשתמש שלך, קודם עליך להפוך [https://osu.ppy.sh/p/support osu! לתומך באוסו].\nלאחר מכן, תוכל לשנות את שמך [https://store.ppy.sh/store/product/32 כאן]!\nכדי לבקש אחזור של שם משתמש קודם, שינויים מינוריים, או עזרה, אנא שלח אי-מייל ל- accounts@ppy.sh עם פרטים.",
    "changelog": "כל העדכונים למשחק, באנצ'ו, והאתר, יכולים להימצא ביומן השינויים של [https://osu.ppy.sh/p/changelog צוות הפיתוח של osu!]",
    "chars": "   אנא המנע משימוש ביוניקוד / תווים שאינם סטנדרטיים בצ'אט הכללי.",
    "charts": "osu! charts הם חבילות מפות לפי נושאים אשר יוצאים מדי חודש. תוכלו למצוא אותם [https://osu.ppy.sh/p/chart כאן!]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "צהוב בהיר: משתמש רגיל | צהוב: [https://osu.ppy.sh/p/support תומך] | אדום: [https://osu.ppy.sh/wiki/QAT חבר QAT] או [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nלבן: אתה, או הודעת me/ | כחול עמוק: הודעה פרטית | ירוק: שורה בה שמך מוזכר(highlight) | ורוד: BanchoBot",
    "colour": "צהוב בהיר: משתמש רגיל | צהוב: [https://osu.ppy.sh/p/support תומך] | אדום: [https://osu.ppy.sh/wiki/QAT חבר QAT] או [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nלבן: אתה, או הודעת me/ | כחול עמוק: הודעה פרטית | ירוק: שורה בה שמך מוזכר(highlight) | ורוד: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "למרות שפקודות צ'אט הן לנוחות, אנא המנע משימוש-יתר בהן. זה נחשב לספאם, ויכול להיגמר בהשתקה.",
    "comment": "אם בא לך להגיב על הקלטה של מפה, לחץ על כפתור הדיון, כתוב משהו, ולחץ אנטר!\nאם אין תגובות על המסך, לחץ על הכפתור הראה תגובות בפאנל הדיון.",
    "comment-color": "הודעות ממשתמשים רגילים בצ'אט יופיעו בצבע לבן. משתמשים [https://osu.ppy.sh/p/support תומכים] יכולים לשנות בהתאמה את הצבע בו הם כותבים.",
    "conferencemode": "מרגיש מוצף מהודעות Join/Quit בIRC? [http://wiki.xkcd.com/irc/Hide_join_part_messages זה] יכול לעזור לך!",
    "country-ranking": "ראה את [https://osu.ppy.sh/p/countryranking דירוגי המדינות] ולוח הניקוד שלהן כאן.",
    "critic": "נא לשמור על ביקורת בונה. הצע תחלופות או דרכים לתקן את הבעיות שאתה מודאג לגביהן.",
    "ctb": "צריך עזרה עם Catch the Beat? הנה [https://osu.ppy.sh/wiki/Catch_the_Beat עמוד הויקי]!",
    "cutting-edge": "סטרימים חדשניים הם סוגי עדכונים שהחליפו את העדכונים הניסיוניים הישנים של osu!.\nניתן לקרוא  [https://https://osu.ppy.sh/wiki/Help_Center#Updater_Issues במאמר הזה] במקרה ויש בעיות עם עדכון המשחק.",
    "cwc": "טורניר osu! Catch the Beat העולמי. ראה את [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 דף הויקיפדיה הזה] לעוד מידע.",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\r\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\r\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "תתייחס אל אנשים אחרים כמו שהיית רוצה שיתייחסו אלייך - בכבוד ובנימוס. אם אתה בקטע של סאדו מאזו מילולי כזה או אחר, אז רק שתדע שאחרים... לא ממש.",
    "disable-this": "מתגים לעתים רחוקות נוספים כתכונות למשחק. ניתן לבקש אחד דרך [https://osu.ppy.sh/forum/4 הפורום הזה].",
    "distance-snap": "חיבור מרחקים(Distance Snap) הוא כלי ששומר על מרחק יחסי נכון בין התווים, בהתבסס על מיקומם על הציר זמן. פרטים: [[Distance_Snap]]",
    "dont-ask-peppy": "בבקשה אל תשאלו את peppy דברים כל הזמן - הוא בן אדם די עסוק. אבל תרגישו חופשי לשאול כל אחד אחר בערוץ!",
    "douche": "בתור מנגנון בטיחות, ניתן להיענש על הפרעה לסדר דרך ניצול פרצות בחוקים, וההענשה תהיה לפי שיקול הדעת והחלטת הצוות הניהולי. החוק הרשמי שאומר לא להיות זבל לא נחוץ בשביל שלא תהיה זבל, אבל רק למקרה: אל תהיה זבל.",
    "download": "ניתן להוריד עוד מפות [https://osu.ppy.sh/p/beatmaplist כאן] או חבילות מפות [https://osu.ppy.sh/beatmaps/packs כאן]. אם אתה לא יודע כיצד לייבא אותן, תוכל לקרוא  [http://i.imgur.com/kpX2N3m.jpg כאן] כדי לגלות!",
    "drugs": "אנא אל תנהל דיון בנושא סמים מכל סוג בשום מקום בצ'אט.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "קרא [[Beatmapping#Keyboard_Shortcuts]] כדי למצוא את רשימת קיצורי הדרך בעורך.",
    "english": "english# קיים בשביל דיון כללי על כל נושא שאין לו ערוץ ספציפי. כן, זה כולל אנימה ומנגה.",
    "evade": "התחמקות מהשתקה היא עבירה שניתן להיענש בגינה. באנים הם הרבה, הרבה יותר גרועים מהשתקות.",
    "fallback": "",
    "faq": "כעת אתה משתמש במערכת שאלות ותשובות של osu!Bancho.\nosu! ויקי: https://osu.ppy.sh/wiki",
    "feature": "אם יש לך רעיון למשחק הזה, פרסם אותו בתת פורום [https://osu.ppy.sh/forum/4 בקשות תכונות].",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "המנעות מסינונים בצ'אט עלולים להביא לידי השתקה. בבקשה אל תעשו את זה.",
    "foul-play": "",
    "percolate": "המנעות מסינונים בצ'אט עלולים להביא לידי השתקה. בבקשה אל תעשו את זה.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 הכתבה הזו] תעזור לך להבין את קצב ואופן יצירת המפות.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "כדי להוסיף משתמש כחבר, כתוב addfriend/ ולאחר מכן את שם המשתמש.\nבנוסף, ניתן ללחוץ על הפאנל של אותו משתמש ברשימת המשתמשים המחוברים(F9) או על שמו בצ'אט ולבחור הוסף כחבר.\nניתן גם להוסיף חברים דרך פרופיל המשתמש שלהם ולחיצה על הוסף כחבר.",
    "friends-list": "על מנת לראות את רשימת החברים המחוברים שלך בתוך המשחק, לחץ על F9 ולאחר מכן שנה את הגדרות הסינון בחלק העליון ל'חברים'.\nתוכלו גם לראות רשימה מלאה של החברים שלכם, גם מחוברים ולא מחוברים בתוך האתר על ידי לחיצה על ההגדרות. (אתם חייבים להיות מחוברים, כמובן.)",
    "fullscreen": "תוכלו לשנות את מצב המסך של המשחק(חלון או מסך מלא) בהגדרות הגראפיקה בתפריט האפשרויות. ניתן גם להחליף בין מצבי מסך על ידי לחיצה על Alt+Enter. הערה: לא ניתן להשתמש במסך מלא עם OpenGL.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "תוכלו למצוא שלל מונחים הקשורים לosu! ב[[glossary]].",
    "gmt": "[https://osu.ppy.sh/wiki/People/Global_Moderation_Team צוות הניהול הגלובאלי], או בקיצור, [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT], הוא קבוצה של משתמשים אשר עוזרים לנהל את osu!. יש להם שמות אדומים בצ'אט וירוקים בפורומים. הם עוזרים לנהל את הצ'אט ואת הפורומים.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 קרא, חזור, שמח]",
    "grammar": "אנא הקפידו על שימוש נכון בדקדוק. זה בסדר לעשות שגיאות כתיב פה ושם, אבל אל תשתמשו בשפה מעוותת או בקיצורים מוקצנים. זה גורם לכם להיראות לא בסדר.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "לא יודעים במה לשחק? רוצים לחקור את עולם המפות והמודינג? [https://osu.ppy.sh/wiki/Guides כאן] תוכלו למצוא את כל מה שחיפשתם.",
    "hacked": "אם אתם מאמינים שפרצו לכם, אנא פנו לaccounts@ppy.sh. במקרה של כישלון לעשות משהו בקשר לזה, התוצאה היא סגירה של אותו חשבון.",
    "hard": "",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "אם אתה זקוק לעזרה בכל דבר הקשור לosu!, הצטרף לערוץ help# ושאל את השאלה שלך.",
    "hitsound-library": "#osu est un canal de discussion où seul l'anglais est autorisé. Pour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "hl": "אנא אל תאשים משתמשים אחרים שהם הדגישו את השם שלך אם יש מילה מילונית בשם המשתמש שלך או ברשימת ההדגשות שלך. ניתן לכבות את ההתראות והצליל שמופעל כאשר זה קורה בתפריט האפשרויות במידת הצורך.",
    "how-to-get-modded": "אם אתם מעוניינים שמישהו יבדוק את המפה שלכם, לחצו כאן: [[Getting_Your_Map_Modded]]",
    "how-to-bn": "אם אתה רוצה להיות BN, קרא את [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator זה] - בדרך כלל, חברי הBN האחרים בוחרים את מי לקדם לBN בהתבסס על שלל דברים כמו כישורי מודינג ופעילות.",
    "how-to-gmt": "מנהלים גלובאליים נבחרים מקבוצה של תורמים קבועים לקהילה. רוצים לעזור? עשו כמיטב יכולתכם לעזור לסדר בערוצים בהם אתם מבקרים על ידי דיווח התנהגויות לא הולמות עם הפקודה report!",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F לחצו על הכתובת הזו כדי ללמוד כיצד לשחק!]",
    "how-to-rank": "כדי לגלות, קראו [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Hyperdash קורה כאשר תופסים פרי שזוהר באדום. אתם תאיצו מהר יותר מהרגיל בזמן הזה. זה ינוטרל כאשר תגיעו לפרי הבא או תפספסו אותו.",
    "ignore": "כדי להתעלם ממשתמש, רשמו ignore/ ולאחר מכן את הכינוי של הבן אדם שתרצו להתעלם ממנו.\nכך, לא תוכלו לראות דברים שהוא אומר, כולל כל סוג של הודעות פרטיות שהם שולחים לכם. \nעל ידי הפקודה unignore/ (כינוי) או יציאה מosu! האפקט יפוג.",
    "import": "קראו את [http://i.imgur.com/kpX2N3m.jpg זה] כדי לגלות כיצד לייבא מפות אל תוך osu!",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "על ידי סימון האפשרות ירישת הגדרות תזמון קודמות בחלון ה F6 של העורך, גזרת התזמון לא תשפיע על התזמון יותר, וזה שימושי לגזרות בהן משנים רק את הווליום או דגימה של המפה. כמו כן, זה אפשרי לרשת גזרות תזמון שיש בהם קצב פעימות לדקה מוכפל או חצוי. אם אתם מוצאים את עצמכם משתמשים בגזרת זמן כזאת, אנא השתמשו באפשרות ההורשה!",
    "irc": "שרת IRC: irc.ppy.sh:6667\nסיסמה: https://osu.ppy.sh/p/irc\nעוד פרטים ב: https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "",
    "kiai": "מצב קיאי הוא אפקט שניתן להחיל על גזרות תזמון על ידי שימוש בפאנל התזמון. גזרות תזמון עם מצב קיאי מופעל משתמשות בכל מיני אפקטים חזותיים על מנת להפוך את המפה ליותר אדיירה.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "הרוויחו  [https://osu.ppy.sh/wiki/Kudosu קודוסו] על ידי מודינג למפות של אנשים אחרים.",
    "lag": "לאג יכול להיגרם בגלל כל מיני דברים - סביר להניח שאלו תהליכים אחרים שרצים על מחשבך. אם אתם משוכנעים שosu! ורק osu! עושה לאגים, הגישו בקשת תמיכה בפורום התמיכה הטכנית עם פירוט על הבעיה וכל דבר שאולי מצאתם שיכול לעזור לאתר אותה.",
    "language": "אנא התנהגו בנימוס בצ'אט. שפה לא ראויה עלולה להביא להשתקה.",
    "language-specific": "",
    "lazer": "",
    "level": "הרמה שלך מתבססת על הניקוד הכולל שלך. זה כולל כל סוג של ניקוד ממפה מדורגת, בין אם זה עובר או נכשל. אתה בהדרגתיות תעלה רמות רק על ידי משחק בosu!",
    "lines": "אנא השתדל לשמור על המשפט שלך בשורה אחת כדי להמנע מלקבל השתקה.",
    "link": "כדי ליצור לינק טקסט למשהו, השתמש בפורמט הבא: [כתובת טקסט], כאשר 'כתובת' זה הכתובת של הלינק, ו'טקסט' זה הטקסט שברצונך להראות. [https://osu.ppy.sh/ ממש ככה!]. אל תשכח את ה //:http.",
    "lobby": "אנא השתמשו בlobby# רק בשביל לפרסם משחקי osu! מרובי משתתפים. בנוסף לכן, lobby# הוא ערוץ רב-שפתי. השתמש בערוץ הmultiplayer# של חדרך בשביל כל דיון אחר.",
    "localisation": "פרויקט הלוקליזציה של osu! נמצא [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 כאן]",
    "long-link": "בבקשה אל תדביקו לינקים ארוכים בצ'אט! השתמשו בנוסחה [link text] אם אתם באמת חייבים.",
    "long-text": "אנא אל תדביקו טקסט ארוך בצ'אט. זה עלול להביא אותכם לידי השתקה.",
    "loved": "",
    "mac": "[https://osx.ppy.sh הרץ osu! על Mac]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "יוצרי מפות הם אנשים עסוקים, ויצירת מפות דורשת הרבה עבודה. למה לא לנסות בעצמך?",
    "mapping": "לך [https://osu.ppy.sh/forum/p/988111 לכאן] בשביל מדריכים ליצירת מפות.",
    "mat": "צוות העזרה למיפוי היה קבוצה ישנה של משתמשים שעזרו לצוות הערכת המפות(BAT) בתהליך הדירוג, והיום צוות זה זל.",
    "modhelp": "ניתן לשאול כל מה שקשור ליצירת מפות ומודינג בmodhelp#!",
    "modqueue": "[https://osu.ppy.sh/forum/60 תורות מודינג]",
    "modreqs": "אנא פנו לmodreqs# בשביל כל בקשת מודינג כלשהי. זכרו שגם חברי BAT עסוקים ויכולים להיות עוד אנשים שביקשו לפניכם, אז אנא וודאו גם לשאול את המשתמשים הרגילים אם הם יכולים לבדוק את המפה שלכם. תודה.",
    "multi-invite": "על מנת להזמין מישהו לחדר המולטיפלייר שלך, בזמן אירוח החדר, לחץ על שם המשתמש הרצוי ברשימת המשתמשים המחוברים (F9) או לחץ על שמם בצ'אט ובחר הזמן למשחק. ניתן גם לרשום invite/ ולאחר מכן את שם המשתמש שברצונכם להזמין.",
    "multi-link": "",
    "multiaccounting": "ממש, אבל ממש לא כדאי לכם ליצור או לשחק בכמה חשבונות. ימצאו אתכם, ויש סיכוי שתקבלו השתקה להרבה מאוד זמן, או אפילו באן!",
    "multiplayer": "אנא אל תפרסמו משחקי מולטיפלייר בערוצים אחרים מלבד lobby#.",
    "mwc": "טורניר osu! Mania עולמי. ראה [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 עמוד זה] בשביל עוד פרטים.",
    "nat": "",
    "news": "",
    "nightcore": "תיהנו מהמפות האהובות עליכם בסגנון נייטקור! פשוט לחצו על מצב הDoubleTime עם הלחצן הימני כדי לגלות את מצב הנייטקור! מבחינת ניקוד זה אותו דבר כמו DoubleTime.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "כתבו np/ כדי להראות לאחרים למה אתם מקשיבים כרגע או משחקים בosu!",
    "nsfw": "שיחות גסות אסורות. osu! מיועד לכל הגילאים, אז אנא מכם, שמרו על הצ'אט נקי או שתסתכנו בהשתקה.",
    "osu": "ערוץ osu# נועד לדיבורים על המשחק. אנא דברו על המשחק שם, לא בערוץ הזה.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 האשכול הרשמי של הosu!tablet] - קראו כאן את כל הפרטים על הטאבלט ואפשרויות להזמנה מוקדמת.",
    "osu!talk": "osu!talk היא תוכנית פודקאסט המאוחסנת על ידי deadbeat/ztrot בדרך שהם מאריינים משתמשים מהקהילה ודנים על כל מני אירועים.\nכל פרק יוקלט בשרת הטימספיק 3 osu.corin.me; אתה תוכל לשאול שאלות באיזור המיועד לכך. עוד מידע יוכל להמצא [https://osu.ppy.sh/forum/t/225111 כאן].",
    "osucore": "בדיחת 1 באפריל מ2011. כל המפות שונו לDoubleTime בתור ברירת מחדל והטון שלהם הועלה. לאחר מכן זה התגלה כמצב הנייטקור.",
    "osu!droid": "",
    "osumania": "אנא השתמשו בערוץ osumania# בשביל דיונים הקשורים לosu!mania.",
    "osustream": "[http://www.osustream.com osu!stream] - אפליקציה של המשחק למכשירי iOS, נוצר ומתוחזק על ידי peppy.",
    "osz": "פורמט המפות שמורידים למשחק תמיד צריך להיות מחולץ על ידי osu! עצמו, אחרת יכולות להיות בעיות.",
    "osz2": "פורמט מפות חדש שבעתיד יאפשר לכל קובץ להיות מוצפן, מועלה, ומשודר ללא תלות באף קובץ אחר. קבצים אלה לא יהיה צריך לחלץ ותמיד ישארו כפורמט זה בתיקיית השירים.",
    "owc": "טורניר osu! עולמי. ראו [https://osu.ppy.sh/wiki/OWC כאן] ליותר פרטים.",
    "peppy": "peppy הוא המפתח הראשי של osu! והוא דואג לרוב הפרויקט בכוחות עצמו.",
    "perfect": "לא השגת את הSS הזה? המוד הזה מנסה מחדש את המפה בשבילך אם אתה מסוגל לא לעשות אף טעות. ניתן למצוא אותו על ידי קליק ימני על מצב הSuddenDeath במסך בחירת המודים.",
    "ping": "Pong!",
    "pippi": "הקמע של osu! \nPipp-don היא גרסת ה-Taiko של Pippi",
    "piracy": "אנא אל תדברו בפתיחות על תוכנות פיראטיות בצ'אט הכללי.",
    "play-shortcuts": "רשימה מלאה של מקשי קיצור: [[Shortcut_Key_Reference]]",
    "pm": "כדי לשלוח הודעה פרטית למישהו, לחצו על השם שלו בצ'אט או על פאנל המשתמש שלו ברשימת המשתמשים המחוברים ולחצו על התחל צ'אט. ניתן גם להשתמש בפקודה <שם משתמש> msg/ או <שם משתמש> chat/ או <שם משתמש> query/, שיפתח לשונית חדשה בצ'אט. בשביל תגובה מהירה להודעה האחרונה שנשלחה, ניתן להשתמש ב <הודעה> r/. להסיר את ה< >, כמובן.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "נקודות ביצוע (pp) הן השיטה העיקרית של osu! למדוד דירוג. לחצו [https://osu.ppy.sh/wiki/Performance_Points כאן] כדי למצוא עוד מידע.",
    "pp-rework-lazer": "",
    "preview": "נקודת התצוגה המקדימה היא הנקודה בשיר שממנה השיר יתחיל להתנגן במסך בחירת השירים. נקודת תצוגה מקדימה מתאימה היא נקודה בשיר שמייצגת אותו היטב, כמו תחילת הפזמון. בדקו בתזמון בסרגל הכלים ולחצו על קבע נקודה נוכחית כנקודת תצוגה מקדימה כדי לבחור אחת.",
    "qat": "",
    "qualified": "",
    "ranked": "מפה מדורגת היא מפה שאושרה על ידי הקהילה. כאשר אתם משחקים במפה מדורגת, הניקוד המתקבל מכך מחושב בניקוד הכללי המדורג שלכם. למפות אלו יש לוח דירוגים משלהם, וניתן לזהות אותם לפי סמל של לב.",
    "ranking-criteria": "בשביל עוד מידע על קריטריונים לדירוג, בקרו בוויקי: [[RC]]",
    "redname": "משתמשים עם שם אדום הם או [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] או [https://osu.ppy.sh/wiki/QAT QAT]",
    "report": "מנהלים אינם זמינים מדי פעם; הם סך הכל בני אנוש ולא יכולים להסתכל על הצ'אט כל היום. במידה ואתה שם לב לכך שמישהו עובר על החוקים ואף מנהל לא מטפל בו, השתמש בפקודה !report.\nהמנע מלדווח בחלון שיחה פרטית עם BanchoBot, והשתמש ב !report <user> <reason>",
    "report-abuse": "אנא המנעו משליחת דיווחים מרובים ברצף, זה לא עוזר לנו להביא צדק יותר מהר. וגם דיווחים ללא סיבה לא עוזרים. למען האמת, אתם יכולים לקבל השתקה במקום עקב הצפת מנהלי צ'אט.",
    "request": "מחפשים משהו ספציפי לעשות לו מודינג? לחצו [https://osu.ppy.sh/p/beatmaplist&r=8 כאן] או כתבו request! בשביל לינק אקראי למפה.",
    "respect": "",
    "roll-abuse": "אנא אל תשתמשו בפקודה roll! יותר מדי. אתם עלולים לקבל השתקה.",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "אם אין משחקים רבי משתתפים להצטרף אליהם, למה לא ליצור משחק משלכם? אז אתם יכולים גם לבחור שירים בעצמכם!",
    "rp": "אתם חופשיים לשחק משחקי תפקידים בערוצי osu! מתאימים, אך שימו לב שאתם לא מפריעים לאנשים אחרים בערוץ יותר מדי.",
    "rules": "[https://osu.ppy.sh/wiki/Rules חוקים רשמיים]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "מפעם לפעם, תוקפים את שרתי osu!. בזמנים כאלו, באנצ'ו יכול להיות לא יציב או לא נגיש. אם אתם חושדים שזה קרה, בדקו ב  [https://twitter.com/osustatus @osustatus] או [https://status.ppy.sh כאן]. אם זה קורה ואתם עדיין מסוגלים להתכתב, המשיכו כרגיל. העלאת הנושא לא תזרז כלום.",
    "sb": "מדריך לסיפורי-רקע: https://osu.ppy.sh/forum/t/1869\nאיך להשתמש בעורך: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "",
    "scoring": "איך osu! מחשב ניקוד: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "השתקה משמעותה שאינך יכול לדבר בצ'אט או בפורומים, למעט בפורום תמיכה טכנית. \nהשתקה מתחילה ב5 דקות או באזהרה הראשונה, ולאחר מכן מוכפלת בכל אזהרה שניתנת, אך אזהרות רציניות מסוגלות להיות הרבה יותר מרק הכפלה של האזהרה הקודמת. \nהשתקות ניתנות בעיקר לאלה העוברים על החוקים ומתנהגים באופן לא הולם. פשוט תמלאו את החוקים ואתם תהיו בסדר.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 שאלות ותשובות הנוגעות להכנת סקינים]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY אל תתן לosu! להשאיר אותך ער כל הלילה. שינה זה דבר חשוב!]",
    "songs-not-appearing": "אם השירים שלכם לא מופיעים בתפריט השירים, נסו ללחוץ על F5.",
    "spaces": "",
    "spam": "בבקשה אל תציפו את הצ'אט, זה מעצבן ולרוב מוביל להשתקה.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "כדי לצפות בשחקן אחר, כתבו <שם משתמש> watch/, או לחצו על שמם בצ'אט או על פאנל המשתמש שלהם ובחרו התחל לצפות. וודאו שיש לכם את אותה המפה שהם משחקים(ושהם באמת משחקים)!",
    "spoiler": "פרסום ספויילרים של כל אנימה, סדרה, מנגה וכו' הוא מעבר לחוק, וכנראה יוביל להשתקה.",
    "status": "בשביל עדכוני מצב מערכת osu!, אנא בדקו את [http://twitter.com/osustatus @osustatus]. למידע על מצב השרת בדוק את https://status.ppy.sh/",
    "store": "[https://osu.ppy.sh/p/market ברוכים הבאים לחנות] של osu!, המקום בו ניתן לקנות חולצות מגניבות וכל מיני דברים אדירים אחרים!",
    "submit": "[https://osu.ppy.sh/wiki/Submission שאלות ותשובות לגבי שליחת מפות]",
    "suck": "בosu! יש קשת גדולה מאוד של דברים שצריך ללמוד. אתם תשתפרו עם הזמן, אז בלי לחץ!",
    "supporter": "הפכו ל[https://osu.ppy.sh/p/support osu! supporter] ותרמו לosu! אתם \nתקבלו מגוון תוספות ויתרונות, וכמו כן תביעו תמיכה בצוות המפתחים!",
    "supporter-please": "",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "אם סמן העכבר שלכם משתגע, וודאו שרגישות העכבר שלכם בזמן המשחק מונחת על 1.00x. רגישות גבוהה יותר ניתנת לקבלה על ידי הקטנת האזור הפעיל בטאבלט שלכם.\nאם הסמן שלכם אינו זז כלל, וודאו לכבות את הRaw Input בהגדרות. \n[https://osu.ppy.sh/forum/t/87301 קראו את זה] אם אתם חווים קשיים בשימוש טאבלט ב-osu!",
    "tag": "במצב טאג במשחק מרובה משתתפים, כל השחקנים משחקים לפי תורות ועושים קומבו אחד של מפה כל פעם. אין מפסיד או מנצח, מכיוון שכולם באותה הקבוצה. בספינרים, כולם משתתפים. אפילו אם שחקן אחד נכשל לעבור את הספינר, הקומבו מתאפס. כל בונוס מהספינר של כל שחקן מתווסף לתוצאה הכוללת של הקבוצה.",
    "taiko": "משחק תופים יפני הנמצא בכמה משחקים של Bandai-Namco. מצב הטאיקו מדמה את המשחקים האלה על ידי שלילת מיקום הפעימות, ומכריח את השחקן להתמקד אך ורק בקצב המפה. [https://osu.ppy.sh/forum/t/4363 כיצד לשחק]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 מדריך מיפוי מפות בTaiko]",
    "taiko-maps": "[https://osu.ppy.sh/forum/t/5397 כאן] תוכלו למצוא מפות אותנטיות של Taiko no Tatsujin.",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "אתם יכולים בבקשה לעזוב את הנושא ולעבור למשהו אחר?",
    "training": "[https://osu.ppy.sh/forum/t/4280 האימונים של James]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 רשימה מעודכנת של סרטוני הדרכה על osu! ויצירת מפות.] תרגישו חופשי ליצור אחד משלכם ולשים אותו בנושא. [https://osu.ppy.sh/forum/t/60228 רשימה של יוצרי מפות/מודרים] ",
    "twc": "הטורניר העולמי של osu! Taiko. ראה את [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ דף הויקי] לעוד מידע.",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "   אנא המנע משימוש ביוניקוד / תווים שאינם סטנדרטיים בצ'אט הכללי.",
    "upload-cap": "כדי שאנשים שיוצרים מפות ישארו נאמנים למפות שהם עובדים עליהן, יש הגבלה קטנה בכמות המפות שהם יכולים להחזיק בתהליך עבודה. \nלא-סופורטרים יכולים להחזיק עד 3-6 מפות פעילות, וסופורטרים יכולים להחזיק עד 5-10 מפות פעילות, תלוי בכמות המפות הקודמות שלהם שקיבלו דירוג.",
    "utf8": "אנא הגדר את תוכנת הIRC שלך להשתמש בקידוד UTF-8, כך שתוכל לקרוא ולשלוח הודעות קריאות למשתמשים נוספים בצורה מספקת.",
    "videogames": "מותר לדבר על משחקי מחשב בosu#, אבל אם זה מפריע לאנשים אחרים, אנא עבור לvideogames#.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "ברוך הבא לosu! אם יש לך שאלה או נתקל בבעיה כלשהי, פנה לאנשים החביבים בhelp#! תהנה!",
    "when": "כשזה מוכן.",
    "wiki": "[https://osu.ppy.sh/wiki/ The osu! Wiki] - הויקיפדיה של osu! בואו בהמוניכם.",
    "wiki-link": "אתה יכול לקשר לדפי ויקי על ידי הקפה של שם דף הויקי בסוגריים מרובעים כפולים כמו זה: [[...]] \nלדוגמא, [[Kudosu]] נוצר על ידי הקלדת Kudosu בין [[ ו ]] כפולים.",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 197 active FAQs (out of a possible 217) in the Hebrew (עברית) language.",
    "completion": "The Hebrew (עברית) FAQ as of last update is 90.78% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
