
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy 撳呢度] 瀏覽 osu! 學園，睇片學 osu! 。",
    "achievements": "你可以透過係玩嘅時候達成某個特定嘅目標（例如好高嘅連擊數），或者玩曬一個主題包裏面啲圖。你個主頁會顯示你而家攞左邊啲成就，同埋你仲有邊啲未攞。有時個成就名就係你攞到果個成就嘅提示啦。",
    "add-skin": "",
    "advertising": "唔該唔好係呢到宣傳同Osu!冇關嘅野，否則禁言伺候！:o)\n切勿宣傳Discord或者係Teamspeak等外來Server",
    "answer": "如果無人答到你，可能係因為無人知。如果呢樣係同 osu! 有關既問題，你可以試下去 osu! 嘅論壇到搵答案。",
    "appeal": "如果你被禁言之後覺得呢個處置唔公平，可以寄封信去 accounts@ppy.sh 解釋你嘅情況。不過記得，管理員都係人，都會犯錯架！如果你對佢地好啲，佢地將更加樂意幫你解除禁言。",
    "approved": "Approved 圖有時會因為某啲原因而 Rank 唔到。但係呢啲圖有啲都幾好玩嘅，同埋佢地都有排行榜同埋完整嘅功能架！你可以係揀圖玩嘅時候留意下左上方嚟分辨圖嘅種類，Approved 左嘅圖會有舊火出現嘅，如果係心嘅就代表呢幅唔係 Approved 圖啦。",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "有咩唔明就問啦，唔使咁客氣架！",
    "attention": "其實你知唔知冇人聽緊你講野。",
    "avatar-change": "喺遊戲畫面禁自己個嘜頭，揀 2.Change Avatar，進入 [https://osu.ppy.sh/home/account/edit#avatar 呢個畫面] 禁 Browse 揀尺寸細過 128x128 、容量細過 88kb 嘅圖片上傳。",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "人稱旺角賭神，天水圍乜乜南，蘭桂坊聖手，超級無敵獎門……呀唔係，機械人 BanchoBot 就係我！:o)",
    "beatmapping": "呢個 [https://osu.ppy.sh/wiki/Beatmapping beatmapping!] 條目有好多關於作圖嘅提示。",
    "beginner": "要搵新手圖？嚟 [https://osu.ppy.sh/forum/t/13976 呢到] 睇睇 Alace 老師幫新手整理嘅圖譜清單啦！",
    "bn": "[[Beatmap Nomination Group]] 係一個負責譜面審核嘅團隊，負責監視審核已經做好嘅譜面同埋將合格者放入 Qualified 列表等待 Rank 。\n如果你有咩關於 Mapping 或者 Modding 嘅問題，都可以 R 佢地傾下計架！",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY 其實你唔使話比人聽你好悶。你可以抖下或者玩下其他遊戲。]",
    "bug": "如果你搵到 Bug，咁可以去[https://osu.ppy.sh/forum/5 呢到] 回報。不過報之前記得睇清楚有無人問過一樣嘅問題。",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "打英文全部大楷睇到傷眼，麻煩撳一下 Caps Lock 。",
    "caps": "當你打緊英文時，唔好用全大楷。因為咁樣係唔受歡迎架，而且你亦都有可能因為咁而被禁言。",
    "change-modes": "想改變遊戲模式嘅話，可以打開歌曲選單，然後禁左下角嘅 Mode 或者用快捷鍵 (Ctrl+1,2,3,4)嚟揀模式。不過記住，有啲圖係指定模式架！",
    "change-name": "要改名嘅話，你要先成為一位 [https://osu.ppy.sh/p/support osu! 贊助玩家] 。之後你就可以喺 [https://store.ppy.sh/store/product/32 呢度] 改名。如果想改返舊嘅名、進行細微的更改或者有其他問題，請將 E-Mail 寄到 accounts@ppy.sh 做詳細說明。",
    "changelog": "所有遊戲、Bancho 同網頁幾更新都可以係 osu! [https://osu.ppy.sh/p/changelog 開發歷程] 入面確認！",
    "chars": "唔好隨便喺 #osu 或者其他外國人頻道隨便打中文字同特殊符號，佢哋部機有可能頂唔順㗎。:(",
    "charts": "osu! charts 係每個月發表既主題圖包。你可以係 [https://osu.ppy.sh/p/chart 呢到] 下載！",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有啲輸入法可能揀唔到字，試下 Alt+Enter 揀 borderless 或者裝搜狗輸入法啦！",
    "chinese-pinyin": "因為唔係所以玩家都識注音或者拼音, 所以盡量避免係度用注音符號同拼音字母, 有你嘅配合, 呢度先會更舒適更健康",
    "color": "淺黃：普通使用者｜黃色：[https://osu.ppy.sh/p/support 贊助玩家]｜紅色：[https://osu.ppy.sh/wiki/QAT QAT（圖譜審核團隊成員）] 或者係 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT（社群管理團隊成員）]｜白色：你自己，或者係一行使用到 /me 指令既動作訊息｜深藍色：密語｜綠色：有人提到你個名（或者 Highlight）｜粉紅色：IRC 萌萌機器人（Banchobot）",
    "colour": "淺黃：普通使用者｜黃色：[https://osu.ppy.sh/p/support 贊助玩家]｜紅色：[https://osu.ppy.sh/wiki/QAT QAT（圖譜審核團隊成員）] 或者係 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT（社群管理團隊成員）]｜白色：你自己，或者係一行使用到 /me 指令既動作訊息｜深藍色：密語｜綠色：有人提到你個名（或者 Highlight）｜粉紅色：IRC 萌萌機器人（Banchobot）",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "唔好狂用指令調戲我，我嬲架！",
    "comment": "如果你系到睇緊人地嘅 replay 既時候想留個言，就禁個 Discussion 制，然後寫啲嘢，最後禁 Enter 制就搞掂啦！如果個熒幕上面無留言，可能你未勾選「顯示留言」姐！",
    "comment-color": "普通用戶只可以出白色既評論。如果係 [https://osu.ppy.sh/p/support 贊助玩家] 既話就可以揀自己鐘意既顏色。",
    "conferencemode": "用緊 irc ，見到成堆出出入入阻住曬火都嚟埋啦，唔使飲涼茶降火嘅，[http://wiki.xkcd.com/irc/Hide_join_part_messages 呢個] 實幫到你！",
    "country-ranking": "黎 [https://osu.ppy.sh/p/countryranking 呢到] 睇睇國家之間既排行榜啦！",
    "critic": "唔該發表一啲有建設性既意見。與其講埋曬啲廢話，不如諗下替代方案或這解決辦法啦！",
    "ctb": "對接生果有問題？黎 [https://osu.ppy.sh/forum/p/60690 呢到] 睇睇！",
    "cutting-edge": "Cutting-edge 係一種取代 osu!test 既全新更新方式。\n如果係更新既時候遇到問題，可以 [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues 參考呢篇文章] 。",
    "cwc": "CWC 係講緊 osu! 世界接生果大賽！[https://osu.ppy.sh/wiki/ZH:Catch_the_Beat_World_Cup_2015 詳細資訊可以禁呢到！]",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "你地要彼此相愛，就好似我 BanchoBot 咁愛你地。唔好係聊天室度隨便言語攻擊其他人。",
    "disable-this": "功能開關係好少加入遊戲既。不過你可以去 [https://osu.ppy.sh/forum/4 Feature Requests 版] 提出你既建議。",
    "distance-snap": "Distance Snap（間距控制）係一個可以協助你用固定間距放物件既工具，至於距離長短就由時間軸既差距黎決定。詳情可以禁 [[Distance_Snap]]  。",
    "dont-ask-peppy": "萬梓良都有講過：「阻住人哋做野，死咗之後會被人燒㗎！」，所以唔好咩都去問 peppy 大老闆，黎呢個頻問人啦，總有一個答案係你隔離。",
    "douche": "身為 osu! 既守護者，管理團隊成員係有權自行決定懲罰走法律罅既人。總之一句講曬，唔作死就唔會死。",
    "download": "[https://osu.ppy.sh/forum/t/24298 新手下載地圖教學（詳細圖解）] [https://osu.ppy.sh/forum/t/18127 多人模式載圖教學]\n[https://osu.ppy.sh/forum/t/58916 地圖包網盤下載點]",
    "drugs": "請唔好係 osu! 聊天室入面討論任何性質既藥物。",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "[[Beatmapping#Keyboard_Shortcuts]] Beatmap Editor 熱鍵列表。",
    "english": "#english 係專登畀啲揾唔到共同話題嘅人用嘅。冇錯，你都可以傾動畫同漫畫。",
    "evade": "係我呢幾十年冒險入邊，我聶過咗大石條罅，跳過咗破冰條罅，又避過咗鱷魚條牙罅，但點避都避唔過 osu! 規則條罅，被人封咗 ac 啦。",
    "fallback": "正式版（Fallback）係舊嘅osu!版本。為咗簡化框架，新版嘅客戶端唔支援DirectX（Fallback版仲留番低）。如果你畀人自動換到呢個版本，咁就應該係你部電腦太舊並唔支援而家同埋之後嘅版本。如果你用而家嘅版本，請你升級到一張支援OpenGL嘅顯卡。 [https://osu.ppy.sh/wiki/GL_Support_Issues 了解更多]",
    "faq": "[https://osu.ppy.sh/forum/t/10737 我係新手教學，請輕輕禁我。]\n[https://osu.ppy.sh/forum/t/109978 中文區精華/資料索引]由微風娘娘親手整理既索引，睇完一次之後仲係晤明既話再發問啦 !",
    "feature": "如果你對呢個 Game 有咩idea，可以去 [https://osu.ppy.sh/forum/4 Feature Requests] 版張貼，我地會聆聽你既意見。",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "鑽漏洞爆粗一樣都會被禁言，所以請三思。",
    "foul-play": "",
    "percolate": "鑽漏洞爆粗一樣都會被禁言，所以請三思。",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "咩係 Flow ? 問得好。 [https://osu.ppy.sh/news/61334266941 呢篇文] 會解答到你。",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "如果你想加 Friend ，可以禁一下 F9 或者佢地係 Chat 入面既名，然後再選擇 Add as Friend 。\n另外你都可以係線上玩家列表（禁 F9）禁玩家的框框，或者係聊天室禁人地既 ID 然後揀 Add as Friend 。\n最後一個方法由官網入去人地既 Profile 禁 Add as Friend 。",
    "friends-list": "如果你想睇下有邊啲好友在線，先禁 F9 然後將畫面上方既過濾換做「只顯示朋友」。\n你亦可以係官網右上角既 Settings 入面睇到完整既好友名單（前提當然係你登入左）。",
    "fullscreen": "你可以係主選單既 Options 當中既「畫面」將遊戲視窗設定為視窗模式或者全熒幕模式。\n你亦可以禁 KB 既 Alt+Enter 。注意： OpenGL 模式並唔支援全熒幕。",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "[[ZH:glossary]] 頁面有唔少 osu! 術語！",
    "gmt": "[https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team] 簡稱 GMT, 係一班人維持住 osu! 論壇同埋遊戲跌序嘅正義使者, 佢地係論壇個名係綠色嘅, 而係game入面個名就紅色嘅。",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 英文權威補習老師peppy，全港連續20年最多英文科A、5**學生。]",
    "grammar": "想學好 Grammar ? 與其係 osu! 學不如去搵個補習名師幫你手啦！",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "唔知點玩？想了解多啲 Mapping 同 Modding 既世界？一切答案盡在 [https://osu.ppy.sh/wiki/Guides 不言中] 。",
    "hacked": "如果你覺得你既 acc 被人盜用，請光速發個 E-Mail 去 accounts@ppy.sh。\n如果唔係咁，你個 acc 可能會被刪除。",
    "hard": "覺得好難玩? 試下玩多幾鋪，可能會好啲呢。",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "如果你需要任何關於 osu! 既幫助，請去 #help 頻道提出你既問題，梗有人幫到你。",
    "hitsound-library": "[https://osu.ppy.sh/forum/p/164927 呢到] 有個音效倉庫，歡迎提取。",
    "hl": "唔好用常用字詞做 HL 詞。\n真係唔掂就去設定閂咗佢啦。",
    "how-to-get-modded": "如果你想知道要點樣你張圖先有人 Mod ，可以禁呢到： [[Getting_Your_Map_Modded]] 。",
    "how-to-bn": "如果你想做 BN，睇睇 [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator 呢個] 。",
    "how-to-gmt": "社群管理團隊成員係由高度貢獻者中人工揀出黎既。想幫我地手？多啲利用 !report 係你既地頭頻道檢舉違規啦！",
    "how-to-play": "唔識玩？唔緊要！\n[https://osu.ppy.sh/wiki/ZH:FAQ#.E6.88.91.E8.A6.81.E6.80.8E.E4.B9.88.E7.8E.A9.E8.BF.99.E6.B8.B8.E6.88.8F.E5.95.8A.EF.BC.9F 專人指導]",
    "how-to-rank": "想知點 Rank 圖？咁你就要睇下 [[How_to_Get_Your_Map_Ranked]呢個] 啦！",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "當你接到一粒發紅光既生果，就會進入 Hyperdash（超級衝刺）既狀態。係之後既短時間你會郁得比平時快，直到接到或者 Miss 左下一粒生果為止。",
    "ignore": "用 /ignore <用戶名> 去 block 左果堆你唔想見到既人。",
    "import": "想 import 圖？得！\n[http://i.imgur.com/kpX2N3m.jpg 專業指導]",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "係 Editor 禁 F6 並剔左 Inherit previous timing settings，咁你所揀既 Timing 區段就唔會郁到 Timing 設定，係凈係想轉音量或者音效既時候好有用。\n另外，將 BPM 調整為雙倍或是減半既時候亦都可以用呢個設定。如果有 Timing 區段係咁既話，麻煩剔剔啦！",
    "irc": "IRC 伺服器：irc.ppy.sh:6667\n密碼請見：https://osu.ppy.sh/p/irc\n想知道更多可以參照：https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "",
    "kiai": "Kiai 模式是你可以在 Timing Setup 面板中套用於 Timing 區段上的特殊效果。啟用了 Kiai 模式的 Timing 區段會有能讓圖譜看起來更加「史詩」的視覺效果。",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Mod 其他人既圖就可以拎到 [https://osu.ppy.sh/wiki/Kudosu kudosu] 。",
    "lag": "Lag 既原因有好多種，最有可能會係你電腦入面開緊既程式。\n如果你 100% 肯定 Lag 係因為 osu! 同埋只有 osu! 有延遲既情況，你可以去論壇既 [https://osu.ppy.sh/forum/5 Help 版] 開帖，內容要寫你既問題同埋細節，以及其他有可能幫到工作人員確認問題原因既資訊。",
    "language": "如果你見到人就「HiHi」聲，咁抵你死被 silence 。",
    "language-specific": "",
    "lazer": "",
    "level": "你既等級係由你既總分數計算得黎既。佢包含左任何 Ranked 圖既分數，無論 Pass 定 Fail 都會計。想高 Level ？玩多啲啦！",
    "lines": "有野講就請盡量一次過打晒，避免分咁向左走向右走多行。:)",
    "link": "想放 Link 既話，可以用呢個格式：[網址 文字]，\n「網址」係你想要 link 去既網址，「文字」就係你想顯示既說明文字。\n[https://osu.ppy.sh/ 好似咁樣！] 千祈唔好唔記得加 http:// 呀。",
    "lobby": "#lobby 係用黎討宣傳 mp 房， #multiplayer 係用黎談論房間遊戲內容，如果要用廣東話吹水既話唔該用 #cantonese ，提多句 #lobby 係可以用多國語言既頻道。",
    "localisation": "[https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24  osu! 在地化計劃]",
    "long-link": "呀～條嘢太長啦～唔該用 [Link 文字] 呢種方式黎貼長 Link 啦。",
    "long-text": "請唔好係聊天室發長賴賴既野，咁樣做可能會被禁言。",
    "loved": "",
    "mac": "[https://osx.ppy.sh Mac機既你係有得玩 osu! 架！]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Mapper 係好多嘢做㗎，點解你唔去試下自己做下自己鐘意嘅歌？",
    "mapping": "[https://osu.ppy.sh/forum/p/988111 呢度] 可以幫到你做圖。",
    "mat": "Mapping Assistance Team (MAT)已經解散 請節哀\nRIP 13.04.23",
    "modhelp": "如果對作圖有任何疑難雜症，請光臨 #mapping 頻道！",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modding Queues]",
    "modreqs": "麻煩去 #modreqs 頻道求 Mod。請注意 BN 們唔係24小時全天候待機，佢地可以已經太多 Mod Request，所以唔一定搵 BN 求 Mod 既！",
    "multi-invite": "想邀請人同你 mp ，係線上使用者列表（禁 F9）禁佢既框框，或者係聊天室禁佢地個名，然後揀「邀至房間」就得架啦。\n你亦可以係聊天室中打 /invite <對方ID> 既指令。",
    "multi-link": "",
    "multiaccounting": "你唔應該開小號！法網恢恢，你走唔甩架啦，長期禁言同 Ban 既豪華套餐等緊你！",
    "multiplayer": "唔好係 #lobby 以外的地方叫人陪你玩。",
    "mwc": "一個國際性既 osu! Mania 比賽。去 [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 維基] 睇睇。",
    "nat": "",
    "news": "",
    "nightcore": "篤多下 DoubleTime 享受一下 Nightcore 為帶黎既人體低溫極限！",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "打 /np 就可以畀人睇你玩 / 聽緊咩圖。",
    "nsfw": "唔好講鹹嘢啦，會被 silence 㗎。",
    "osu": "#osu 頻道係專講 osu!，不過果到只可以用雞腸。",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 osu! 繪圖版專用帖！] 講曬同繪圖版同訂購有關既資訊。",
    "osu!talk": "osu!talk 係由 deadbeat 同 ztrot 主持既清談節目，呢兩條友會訪問 osu! 既人同埋講下世界賽之類既活動。\n每一集都會係 Teamspeak 3 的伺服器 osu.corin.me 上進行；如果想問問題，可以參與 Q&A 環節。[https://osu.ppy.sh/forum/t/225111 禁我知道更多]。",
    "osucore": "2011 年既愚人節官方節目。所有圖都預設開著 DoubleTime 同埋較到啲音高到好似外星人唱歌咁。\n無幾耐之後就變成左 Nightcore 模式，同當時的 DoubleTime 效果一模一樣。",
    "osu!droid": "",
    "osumania": "#osumania 頻道係專講 osu!mania 。",
    "osustream": "[http://www.osustream.com osu!stream] 係 iOS 版既 osu!，由 peppy 製作同維護！",
    "osz": "呢個係你下載返黎既 Map 既格式。osz 檔要用 osu! 黎解壓，唔係既話可能會發生問題！",
    "osz2": "呢個係一種新既 Map 格式，每一個檔案都可以獨立加密、上傳同埋播放等。osz2 檔案並唔需要解壓，會一直係 Songs 資料夾下用 osz2 既格式儲存。",
    "owc": "世界 osu! 大賽之一。\n[https://osu.ppy.sh/wiki/OWC 了解更多]",
    "peppy": "peppy 乃係 osu! 既永遠榮譽主席，大部份野都是佢自己搞既。",
    "perfect": "拎唔到 SS？呢個 Mod 會係打唔出 300 既時候自動 Retry。\n你可以係 Mod 選單（禁F1）禁兩下 SuddenDeath 。",
    "ping": "Pong!",
    "pippi": "佢係 osu! 既吉祥物。\nPippi-don 係佢在太鼓模式既形象。",
    "piracy": "唔好係公眾地方公開討論盜版。",
    "play-shortcuts": "[https://osu.ppy.sh/forum/t/32022 osu! 快捷鍵一覽表]",
    "pm": "要密其他人，係聊天室禁對方既 ID，或者係線上玩家列表禁人地既框框，然後禁 Start Chat 。\n你亦可以係聊天室打 /msg <對方ID> 或者 /chat <對方ID> 既指令直接密對方，或者用 /query <對方ID> 開一個新 Tab。\n想回覆上一個信息，你可以打 /r <訊息> 既然指令。",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance Points（pp）係 osu! 新既排名方式！禁 [https://osu.ppy.sh/wiki/Performance_Points 呢到] 了解更多。",
    "pp-rework-lazer": "",
    "preview": "Preview Point 可以係 Editor 設定，係歌曲選單就會又果到開始播。\n好既預覽段落應該表現到歌曲最高潮既地方，例如 Chorus 既開頭。係 Editor 上面既工具列既 Timing 選單禁 Set Current Position as Preview Point 就得架啦，係咪好容易呢？",
    "qat": "",
    "qualified": "呢個係 modding 系統既前進方向！Qualified 狀態代表呢個圖差唔多可以 Rank。打呢啲圖有排名，不過無PP。Qualified 狀態會維持一個禮拜，期間如果社會對圖有意見而 QAT 認為呢啲意見值得參考，圖就會彈回原型，分數記錄亦會被清理；相反圖保持 Qualified 狀態一個禮拜既話就會自動 Rank。",
    "ranked": "Ranked 圖係成功被審批既圖。\n打 Ranked 圖所得到既分數會計入你既總分。\n呢啲圖有各自既排行榜，係歌曲選單左上角既圖示係愛心。",
    "ranking-criteria": "如果你想知道有關 Rank 既標準，你可以睇下 Wiki 既條目：[[zh:RC]]",
    "redname": "個名係紅色既人一係 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] ，一係 [https://osu.ppy.sh/wiki/People/The_Team/Nomination_Assessment_Team NAT]。",
    "report": "管理員有時會不在，他們也是人，沒辦法全天守候。如果你發現有人在胡搞卻沒有管理員處理，請在該頻道輸入 !report <對方ID> <原因> 。\n請避免在 BanchoBot 的頻道中使用 !report。",
    "report-abuse": "請唔好一直重複 Report 同一條友，就好似禁電梯制咁，禁多兩下都唔會快啲，亦都唔好做無意義 report 。\n講真，一直係咁亂用 report 係有可能因為洗管理員版而遭禁言。",
    "request": "想搵啲圖黎 Mod 下？Click [https://osu.ppy.sh/p/beatmaplist&r=8 這裡] 或者輸入 !request ，咁就可以攞到一張隨機 gen 出黎既圖。",
    "respect": "要人哋尊重你，你都要尊重翻人哋先。",
    "roll-abuse": "唔好過度使用 !roll ，否則有可能會被禁言。",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "如果無人開多人遊戲房既話，點解你自己唔開間呢？咁樣做你重可以自己簡你鐘意隻歌添！",
    "rp": "係呢度你可以玩角色扮演扮下野，但係你要確定你唔會騷擾到呢度既人！",
    "rules": "[https://osu.ppy.sh/wiki/zh/Rules 官方守则]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "osu! 偶爾會被人 DDoS。在呢個時候，Bancho 可能會唔穩定或者連接唔到。\n如果你懷疑有呢種狀況，請係 Twitter 既 [https://twitter.com/osustatus @osustatus] 上或[https://status.ppy.sh 這裡] 攞料。\n如果真係咁唔好彩發生左，而你仍然可以用到聊天室，麻煩繼續正常傾計，因為拎出黎講並唔會令佢行得快左。",
    "sb": "[https://osu.ppy.sh/forum/t/1869 整Storyboard教學]\n[https://osu.ppy.sh/forum/t/8145 使用Storyboard編輯器教學]\n",
    "scorev2": "",
    "scoring": "osu! 計分方法 : [[Score#scoring]] 。",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "禁言唧係你唔可以係聊天室講野同埋喺論壇上 po 文（Technical Support 板塊除外）。\n第一次禁言5分鐘，之後每次都會 double 。嚴重啲嘅情況會比前一次唔單止 double 咁少。\n禁言只係會對輕犯者執行，所以基本上遵守規則就唔會發生咩事。",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 整Skin教學]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY 嘩！乜玩到咁夜呀，成四點啦！係時候去休息一下。有左充足既休息，玩osu! 先羅到高分架！]",
    "songs-not-appearing": "見唔到首歌唔駛用劍既，用F5就得啦。呢到係 osu! 唔係高登，一下就得，保證唔駛咁到佛誕。:o)",
    "spaces": "",
    "spam": "唔好洗版呀，如果唔係後果自負。",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "如果想睇其他人玩，打 /watch <ID> 或者喺聊天室點擊佢嘅 ID / 用戶框，之後揀 Start Spectating 就得。\n請確定你有佢地玩緊嘅圖（同埋佢地真係玩緊）！",
    "spoiler": "唔好公開討論動漫 / 同人劇情，睇到呢句都仲繼續講落去會被禁言。",
    "status": "想知道 osu! 系統嘅即時狀況？喺 Twitter 有得睇喇。[http://twitter.com/osustatus @osustatus]",
    "store": "[http://store.ppy.sh/ 埋黎睇埋黎揀啦喂！] ，呢到可以買到各種 osu! 周邊產品同其他好野！",
    "submit": "[https://osu.ppy.sh/wiki/Submission 圖譜上傳 FAQ]",
    "suck": "唔驚既，生命滿希望，前路由你創，聽日一定會好天嘅，打得唔好咪打第二樣囉。",
    "supporter": "簽下契約成為 [https://osu.ppy.sh/p/support osu! supporter] 啦!",
    "supporter-please": "唔該唔好周圍問人可唔可以送 supporter 比你，[https://osu.ppy.sh/p/support 要既麻煩自己買！]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "如果你用繪圖板玩 osu! 出咗咩問題，可以睇 [https://osu.ppy.sh/forum/t/87301 呢度] 。",
    "tag": "喺多人 Tag 模式入邊，玩家輪流依照 Combo（一串同顏色圈圈）順序打圖。呢個模式冇贏冇輸，因為個個都喺同一個隊伍入邊。\n轉盤係每個玩家都要轉轉轉，就算係有一條友冇轉到，Combo 數都會歸零。每個玩家嘅轉盤分數都會額外計翻落隊伍分入邊。",
    "taiko": "太鼓係日本 Bandai-Namco 所製作既一系列遊戲入面登場既一種鼓。osu! 既「太鼓模式」仿製左呢款遊戲，唔需要考慮物件既擺位，等玩家只需專注於圖既節奏。\n[https://osu.ppy.sh/forum/t/4363 睇下點玩！]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 太鼓製圖教學]",
    "taiko-maps": "[https://osu.ppy.sh/forum/t/5397 係度] 揾太鼓嘅圖。",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "不如唔好講呢個啦，講第二樣啦好嘛？",
    "training": "[https://osu.ppy.sh/forum/t/4280 James 既新手訓練]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 最新既 osu! 遊玩同埋製圖教學影片列表。] 如果你自己都拍左一部，千祈唔好客氣即管貼黎呢到。 [https://osu.ppy.sh/forum/t/60228 好用既製圖者 / Modder 教學]",
    "twc": "世界 osu! 太鼓大賽。\n[https://new.ppy.sh/wiki/Tournaments/TWC/2017/ 睇睇呢篇文啦！你將會瞭解到更多。]",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "唔好隨便喺 #osu 或者其他外國人頻道隨便打中文字同特殊符號，佢哋部機有可能頂唔順㗎。:(",
    "upload-cap": "為咗令製圖者可以專心做自己手上嘅圖，同時可以上傳嘅圖係有數量限制嘅。\n一般玩家可以同時上傳 3 至 6 張圖，贊助玩家就可以有 5 至 10 張圖，依據佢有幾多 Rank 圖而定。",
    "utf8": "請將你嘅 IRC 軟體設定成 UTF-8 編碼，咁樣可以令你正常閱讀到其他使用者嘅 / 傳送比其他使用者嘅訊息。",
    "videogames": "電玩遊戲相關既主題係可以出現喺 #osu 頻道嘅，只不過如果佢們干擾到其他人傾計嘅話，請移玉步去 #videogames 頻道。",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "歡迎嚟到 osu!！如果你有任何問題，請即管喺 #help 頻道提出！祝你玩得愉快！",
    "when": "得咪得囉...",
    "wiki": "[https://osu.ppy.sh/wiki/ 一齊嚟寫 osu! Wiki！Osu Wiki 歡迎你。]",
    "wiki-link": "你可以喺聊天室入面使用雙引號嘅格式，產生 Wiki 條目既快速連結。\n例如，[[Kudosu]] 就係將 Kudosu 放係兩個 [ 同兩個 ] 中間輸入而成嘅。",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 201 active FAQs (out of a possible 217) in the Cantonese (廣東話) language.",
    "completion": "The Cantonese (廣東話) FAQ as of last update is 92.63% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
