
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy Kliknite ovdje] da biste pogledali osu! akademiju - osu! video vodič!",
    "achievements": "Postignuća dobivate tako da odradite određene zadatke, tipa dobivanjem golemih komboa na pjesmi, ili igrajući svaku mapu neke teme. Vaša postignuća možete vidjeti na vašem profilu. Za većinu je vrlo jasno što se treba uraditi da ih osvojite, ali za neke trebate shvatiti sami što uraditi.",
    "add-skin": "[https://osu.ppy.sh/forum/t/3580 Kako dodati skinove u osu!]",
    "advertising": "Reklamiranje stvari koje nemaju veze sa osu! nije dozvoljeno i možete biti utišani zbog toga.",
    "answer": "Ako vam nitko ne odgovori, moguće je da nitko ne zna odgovor! Probajte potražiti na forumu ako je povezano s osu!.",
    "appeal": "Ukoliko budete utišani i mislite da je pogreška, pošaljite privatnu poruku [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMu] i objasnite svoju situaciju. Samo znajte da su GMi također ljudi. Budite ljubazni prema njima.",
    "approved": "",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "Postavite pitanje. Nemojte pitati dali smijete postavit pitanje.",
    "attention": "Možete li molim vas prestati? Nitko ne sluša što vi pričate...",
    "avatar-change": "Možete promjeniti vaš avatar [https://osu.ppy.sh/home/account/edit#avatar ovdje].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Zdravo! Ja sam BanchoBot! Drago mi je! Ipak sam ja robot, tako da ne mogu imati konverzaciju s vama :(",
    "beatmapping": "[https://osu.ppy.sh/?p=faq&n=5 Savijeti za pravljenje beatmapa]",
    "beginner": "Kliknite [https://osu.ppy.sh/forum/t/5456 ovdje] ako tražite mape za početnike.",
    "bn": "",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Nema smisla govoriti drugima da vam je dosadno. Uzmite pauzu, ili probajte igrati nešto drugo!]",
    "bug": "Ako mislite da ste pronašli grešku s igrom, prijavite ju [https://osu.ppy.sh/forum/5 ovdje]. Ali osigurajte se da ju nije netko pronaša prije vas.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "\nMolimo vas nemojte koristiti veliko slovo na početku svake vaše riječi - izgledali bi ste kao olupina vlaka.",
    "caps": "Molimo vas nemojte koristiti caps lock u chatu - nije željno i moglo bi vas dovesti do mute-a",
    "change-modes": "",
    "change-name": "",
    "changelog": "",
    "chars": "",
    "charts": "",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "",
    "colour": "",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "",
    "comment": "",
    "comment-color": "",
    "conferencemode": "",
    "country-ranking": "",
    "critic": "",
    "ctb": "",
    "cutting-edge": "",
    "cwc": "",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\r\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\r\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "",
    "disable-this": "",
    "distance-snap": "",
    "dont-ask-peppy": "",
    "douche": "",
    "download": "",
    "drugs": "",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "",
    "english": "",
    "evade": "",
    "fallback": "",
    "faq": "",
    "feature": "",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "",
    "foul-play": "",
    "percolate": "",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "",
    "friends-list": "",
    "fullscreen": "",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "",
    "gmt": "",
    "english-help": "",
    "grammar": "",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "",
    "hacked": "",
    "hard": "",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "",
    "hitsound-library": "",
    "hl": "",
    "how-to-get-modded": "",
    "how-to-bn": "Ako želite postati BN, pročitajte [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator ovo] - večinu vremena, drugi BN-ovi odlučuju tkoga će unaprijediti u BN bazirano na dosta stvari kao što su kvaliteta moddinga i aktivnost.",
    "how-to-gmt": "",
    "how-to-play": "",
    "how-to-rank": "",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "",
    "ignore": "",
    "import": "[http://i.imgur.com/kpX2N3m.jpg Pročitajte ovo da biste saznali kako unijeti mape u osu!]",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "",
    "irc": "",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "",
    "kiai": "",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "",
    "lag": "",
    "language": "",
    "language-specific": "",
    "lazer": "",
    "level": "",
    "lines": "",
    "link": "",
    "lobby": "",
    "localisation": "",
    "long-link": "",
    "long-text": "",
    "loved": "",
    "mac": "",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "",
    "mapping": "",
    "mat": "",
    "modhelp": "",
    "modqueue": "",
    "modreqs": "",
    "multi-invite": "",
    "multi-link": "",
    "multiaccounting": "",
    "multiplayer": "",
    "mwc": "",
    "nat": "",
    "news": "",
    "nightcore": "",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "",
    "nsfw": "",
    "osu": "",
    "osu!tablet": "",
    "osu!talk": "",
    "osucore": "",
    "osu!droid": "",
    "osumania": "",
    "osustream": "",
    "osz": "",
    "osz2": "",
    "owc": "",
    "peppy": "",
    "perfect": "",
    "ping": "Pong!",
    "pippi": "",
    "piracy": "",
    "play-shortcuts": "",
    "pm": "",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "",
    "pp-rework-lazer": "",
    "preview": "",
    "qat": "",
    "qualified": "",
    "ranked": "",
    "ranking-criteria": "",
    "redname": "",
    "report": "",
    "report-abuse": "",
    "request": "",
    "respect": "",
    "roll-abuse": "",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "",
    "rp": "",
    "rules": "",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "",
    "sb": "",
    "scorev2": "",
    "scoring": "",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "",
    "sleep": "",
    "songs-not-appearing": "",
    "spaces": "",
    "spam": "",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "",
    "spoiler": "",
    "status": "",
    "store": "",
    "submit": "",
    "suck": "",
    "supporter": "",
    "supporter-please": "",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "",
    "tag": "",
    "taiko": "",
    "taiko-mapping": "",
    "taiko-maps": "",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "",
    "training": "",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "",
    "twc": "",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "",
    "upload-cap": "",
    "utf8": "",
    "videogames": "",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "",
    "when": "",
    "wiki": "",
    "wiki-link": "",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 60 active FAQs (out of a possible 217) in the Croatian (Hrvatski) language.",
    "completion": "The Croatian (Hrvatski) FAQ as of last update is 27.65% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
