
strings = {
    "academy": "[https://www.youtube.com/user/osuacademy Kattints ide] az osu! akadémia megtekintéséhez - Videóútmutatók minden osu!-val kapcsolatos dologhoz.",
    "achievements": "Achievementeket kapsz, ha valami különleges dolgot érsz el játék közben, például: egy hatalmas kombó, vagy egy bizonyos témájú csomagban az összes beatmap végigjátszása. A profilodon megnézheted, melyeket kaptad meg, és melyeket kell még megszerezned. Néhánynak a neve megsúgja, mit kell tenned érte!",
    "add-skin": "[https://osu.ppy.sh/forum/t/3580 Így tudsz új témákat hozzáadni az osu!-hoz]",
    "advertising": "Tilos hirdetni bármit, ami nem osu!-val kapcsolatos. Ismétlődő vagy komolyabb esetek azonnali némításban részesülnek.",
    "answer": "Ha senki sem válaszol, lehet, hogy senki sem tudja a választ! Keresgélj a fórumon, ha osu!-val kapcsolatos a probléma.",
    "appeal": "Ha elnémítanak, de úgy gondolod, nem volt igazságos, küldj egy privátot egy [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GM]-nek és magyarázd el a helyzeted. Tartsd észben, hogy a GM-ek is emberek! Ha kedves vagy velük, valószínűbb, hogy segítőkészebbek lesznek a némítás feloldásával kapcsolatban, amennyiben az lehetséges.",
    "approved": "Az Approved beatmapek valami oknál fogva nem rankolhatók, viszont elég jók ahhoz, hogy az emberek játszhassanak rajtuk scoreboard-dal meg mindennel! Onnan ismerheted fel őket, hogy az ikonjuk egy láng egy szív helyett.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "Csak kérdezz. Ne kérdezd, hogy felteheted-e a kérdésed.",
    "attention": "Úgy tűnik senkit sem érdekel, hogy miről beszélsz. Jobb ha leállsz.",
    "avatar-change": "Az avatárodat [https://osu.ppy.sh/home/account/edit#avatar itt] tudod lecserélni.",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Helló! Én BanchoBot vagyok! Örvendek! Sajnálatos módon azonban én csak egy bot vagyok, szóval nem tudunk beszélgetni :(",
    "beatmapping": "Itt van pár jótanács [https://osu.ppy.sh/wiki/Beatmapping beatmap-készítéssel] kapcsolatban!",
    "beginner": "Kattints [https://osu.ppy.sh/forum/t/5456 ide] ha kezdőknek szánt beatmapeket keresel.",
    "bn": "A [[Beatmap Nomination Group]] egy olyan csoport, akik a beatmapek rankolásával, és a rankolás előtt álló pending beatmapek moderációjával foglalkoznak. Ha kérdésed van a mappeléssel vagy modolással kapcsolatban, hozzájuk fordulhatsz.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Ha nagyon unatkozol, keress valami más elfoglaltságot.]\nSok mindent csinálhatsz online.\nAz unalom nem kifogás arra, hogy osu!-n nyafogj vagy spamelj.",
    "bug": "Ha meglehetősen biztos vagy benne, hogy hibát találtál, jelentsd [https://osu.ppy.sh/forum/5 itt]! - Chatben jelentett hibák könnyen elveszhetnek más beszélgetések között!\n",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Kérlek ne használj nagy betűt minden új szó kezdetén - úgy néz ki tőle az írásod, mint egy roncs.",
    "caps": "A nagybetűkkel való írás kiabálásnak számít.\nTehát, korlátozd a nagybetűk használatát, hogy ne tűnj udvariatlannak.\n",
    "change-modes": "Más játékmód választásához menj a számválasztó képernyőre és vagy kattints alul a Mód lehetőségre, vagy használd a Ctrl + 1-4 billentyűkombót. Bizonyos mapok mód-specifikusak!",
    "change-name": "[https://osu.ppy.sh/forum/t/34694 Olvasd el ezt], ha meg akarod változtatni a nevedet!",
    "changelog": "Minden játékkal, Bancho-val és weblappal kapcsolatos frissítés megtalálható az osu! fejlesztési [https://osu.ppy.sh/p/changelog changelog]-ban!",
    "chars": "Kérlek kerüld a Unicode/nem standard karakterek használatát az általános chatben.",
    "charts": "Az osu! chartok témák szerint rendezett csomagok, amelyek havonta kerülnek kiadásra. Megtalálhatod őket [https://osu.ppy.sh/p/chart itt!]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Halványsárga: Normál felhasználó | Sárga: Egy [https://osu.ppy.sh/p/support Támogató] | Piros: Egy [https://osu.ppy.sh/wiki/QAT QAT] vagy [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nFehér: Te magad, vagy egy /me üzenet | Sötétkék: Egy privát üzenet | Zöld: Egy sor, ami tartalmazza a neved (kijelölés) | Rózsaszín: BanchoBot",
    "colour": "Halványsárga: Normál felhasználó | Sárga: Egy [https://osu.ppy.sh/p/support Támogató] | Piros: Egy [https://osu.ppy.sh/wiki/QAT QAT] vagy [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nFehér: Te magad, vagy egy /me üzenet | Sötétkék: Egy privát üzenet | Zöld: Egy sor, ami tartalmazza a neved (kijelölés) | Rózsaszín: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "A chat commandokat könnyű használni, de ne vidd túlzásba, mivel spamnek minősül és némítás járhat érte.",
    "comment": "Ha úgy érzed, kommentárt szeretnél fűzni egy visszajátszáshoz, kattints a Megbeszélés gombra, írj valamit, majd üss entert!\nHa nem látod mások kommentjeit, kattints a Kommentek mutatása dobozra a Megbeszélés panelen.",
    "comment-color": "Normál felhasználó csak fehér színnel szólhat hozzá. Egy [https://osu.ppy.sh/p/support Támogató] testreszabhatja hozzászólásának színét.",
    "conferencemode": "Elárasztanak a Join/Quit üzenetek IRC-n? [http://wiki.xkcd.com/irc/Hide_join_part_messages Ez] segíthet!",
    "country-ranking": "Nézd meg különböző [https://osu.ppy.sh/p/countryranking országok rankjait] itt.",
    "critic": "Kérlek tartsd a kritikáidat építő jellegűnek. Ajánlj alternatívákat és javítási módokat amik szerinted megoldanák a problémát.",
    "ctb": "Segítség kell Catch the Beat-tel kapcsolatban? [https://osu.ppy.sh/wiki/Catch_the_Beat Itt] a wiki oldal!",
    "cutting-edge": "A Cutting-edge egy kísérleti verziója az Osu!-nak, amibe az új fejlesztések kerülnek, mielőtt a fő kliensbe kerülnek. Az opciókban tudsz átváltani rá.Olvasd el [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues ezt] a cikket, ha problémád akad kliensed frissítésével.",
    "cwc": "Nemzetközi Catch the Beat bajnokság! Látogass el [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 ide] több infóért!",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Úgy kezelj másokat, ahogy téged is szeretnéd, hogy kezeljenek. Ha te valamiféle verbális mazochista vagy, feltételezd, hogy mások nem azok.",
    "disable-this": "Funkciókhoz ritkán kerülnek bevezetésre kapcsolók. Ettől függetlenül kérhetsz egyet a [https://osu.ppy.sh/forum/4 Feature Requests alfórumon].",
    "distance-snap": "A beatek közti megfelelő hely kihagyásának legegyszerűbb módja a szerkesztő Distance Snapping funkciójának használata, mely a jobb alsó sarokban található. A körök közti relatív távolság az egérgörgővel szabályozható. Ha az egész szám alatt Distance Snapping-et használsz, a megfelelő elválasztás garantált!",
    "dont-ask-peppy": "Kérlek ne zaklasd Peppy-t folyton - meglehetősen elfoglalt. Nyugodtan kérdezz viszont bárki mást a csatornán!",
    "douche": "Mint egyfajta védőkorlát, a rend felborításának és a kiskapuk kihasználásának büntetése az adminisztratív csapat megítélésére van bízva. Nem kéne szabályt hozni arra, hogy ne legyél seggfej, de csak, hogy biztosan minden rendben legyen: ne legyél seggfej.",
    "download": "Beatmapeket [https://osu.ppy.sh/p/beatmaplist itt] szerezhetsz be, vagy csomagok formájában [https://osu.ppy.sh/beatmaps/packs itt].",
    "drugs": "Kérlek ne beszélgess bármilyen fajta kábítószerről bárhol az osu! chatben.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "A szerkesztőben használható gyorsbillentyűk listájához olvasd el ezt: [[Beatmapping#Keyboard_Shortcuts]]",
    "english": "Minden olyan dolog megbeszélése, amihez nem tartozik saját csatorna, az #english -ben zajlik.\nIgen, ebbe az anime és manga is beletartozik.",
    "evade": "Elnémítás megkerülése kitiltással büntethető. Egy kitiltás sokkal, sokkal rosszabb, mint egy némítás.",
    "fallback": "A Stable (Fallback) egy elavult osu! build. E kiadással ellentétben az új verziók eltávolították a DirectX támogatást, az egyszerűbb framework jegyében. Ha ezen a build-en vagy, akkor a géped nagyon régi és nem fogja támogatni a új és jövőbeni kliens verziókat.\nHa a jelenlegi buildeket akarod használni most, frissítsd a videokártyáid, hogy támogassák az OpenGL-t, a legfontosabb igényt ezeknek a kiadásoknak. [https://osu.ppy.sh/wiki/GL_Support_Issues Klikk ide, hogy tudd hogyan].",
    "faq": "Jelenleg az osu!Bancho GYIK Rendszert használod. osu! wiki: https://osu.ppy.sh/wiki",
    "feature": "Új funkciókat a [https://osu.ppy.sh/forum/4 Feature Request] alfórumban kérhetsz.",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "A chat szűrők megkerülése bizonyítottan az egyik leggyorsabb módja annak, hogy némítást vagy kitiltást kapj. Ne csináld.",
    "foul-play": "Kérlek jelentsd a csalókat a jelentés gombot használva a profiljuknál, ami itt található [https://i.imgur.com/GG9xlLA.png itt].\nFigyelj arra, hogy annyi részletet adj meg amennyit csak tudsz. Jelentheted az eredményeiket is beatmap oldalának top 50 ranglistájánál.",
    "percolate": "A chat szűrők megkerülése bizonyítottan az egyik leggyorsabb módja annak, hogy némítást vagy kitiltást kapj. Ne csináld.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Ez a cikk] majd segít megérteni a mapping menetét.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Egy felhasználó barátként való hozzáadásához írd be a /addfriend <név> parancsot.\nRákattinthatsz még a paneljére az Online Felhasználók listában (F9), vagy a nevére a chatben, és kiválaszthatod a Felvétel barátnak lehetőséget.\nA profil oldalukon is megteheted ezt, a Felvétel barátnak lehetőségre kattintva.",
    "friends-list": "Online barátaid megtekintéséhez nyomd meg az F9 gombot, majd fönt a szűrőt váltsd át a Barátok lehetőségre.\nA weboldalon a barátaid teljes listáját is megtekintheted, akár online vannak, akár offline, a Beállítások menüből.\n(Persze ehhez be kell jelentkezned.)",
    "fullscreen": "Beállíthatod, hogy a játék ablakos módban vagy teljes képernyőn fusson a Beállítások menüben.\nA kettő között egyébként az Alt+Enter billentyűkombinációval is válthatsz.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "A terminológia nagyrészét itt megtalálod: [[glossary]]",
    "gmt": "A [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Globális Moderációs Csapat], vagy röviden GMT, egy olyan csoport, akik segítenek az osu! működtetésében. A chatben piros, a fórumon zöld névvel jelennek meg.\nEzek a fickók segítenek moderálni a fórumot és a chatet.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Olvasd el, nézd át, örülj.]",
    "grammar": "Próbálj helyesen írni. Néhány hiba vagy elgépelés elfogadható, de kérlek ne használj rövidítéseket vagy textspeak-et. Csak butának látszol tőle.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Nem tudod hogyan kell játszani? Fel akarod fedezni a mapelés és modolás világát? [https://osu.ppy.sh/wiki/Guides Itt] minden választ megtalálsz.",
    "hacked": "Ha úgy hiszed, feltörték a jelszavad, kérlek küldj egy emailt az accounts@ppy.sh címre.\nEnnek elmulasztása a felhasználód kitiltását vonhatja maga után.",
    "hard": "Tanulj meg játszani, Pojáca!",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Ha bármilyen osu!-val kapcsolatos segítségre van szükséged, lépj be a #help-be és kérdezz.",
    "hitsound-library": "Látogass el [https://osu.ppy.sh/forum/p/164927 ide], ha egyedi találati hangokat szeretnél a mapedhez.",
    "hl": "Kérlek ne hibáztass más felhasználókat a kijelölésekért ha szótári szó vagy gyakran használt kifejezés van a listádban.",
    "how-to-get-modded": "Ha tudni szeretnéd, hogyan láthatják többen a mapedet, kattints ide: [[Getting_Your_Map_Modded]]",
    "how-to-bn": "Ha BN szeretnél lenni, olvasd el [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator ezt] - általában a többi BN választja ki, kit léptetnek elő BN-né olyan dolgok alapján, mint modolási minőség és aktivitás.",
    "how-to-gmt": "A chat moderátorok kézzel kerülnek kiválasztásra a közösség legtöbbet segítő tagjaiból. Te is segíteni szeretnél? Moderáld az általad gyakran látogatott csatornákat azáltal, hogy jelented a szabályszegéseket a !report parancs használatával.",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F Kattints ide hogy megtudd, hogyan kell játszani!]",
    "how-to-rank": "Ha kíváncsi vagy, olvasd el ezt: [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "A Hyperdash akkor aktiválódik, amikor egy vörösen izzó gyűmölcsöt kapsz el. Ez idő alatt a normálisnál gyorsabban futsz. A következő gyümölcs elérésekor vagy eltévesztésekor deaktiválódik.",
    "ignore": "Egy felhasználó ignorálásához írd be, hogy /ignore, majd a nevüket.\nAz ignorált felhasználók által írt dolgokat nem látod, ahogy az általuk küldött privát üzeneteket sem.\nA /unignore <felhasználónév> beírása, vagy az osu!-ból történő kilépés véget vet a hatásának.",
    "import": "[http://i.imgur.com/kpX2N3m.jpg Olvasd el ezt hogy megtudd, hogyan lehet beatmapeket importálni az osu!-ba.]",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Az Előző időzítés beállítások öröklése jelölőnégyzet bejelölése a Szerkesztő F6-os ablakában azt fogja eredményezni, hogy az időzítés rész már nem lesz hatással a beatmap időzítésére. Ez hasznos lehet olyan szakaszoknál, melyek csak a beatmap hangerejét vagy mintáját változtatják meg.\nOlyan időzítési szakaszok is örökölhetők, amelyeken a BPM dupla vagy fele akkora, mint a map többi részén. Ha bárhol ilyet használsz, kérlek, használd az öröklődést!",
    "irc": "IRC szerver: irc.ppy.sh:6667\nJelszó: https://osu.ppsy.sh/p/irc\nRészletek: https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Megváltoztathatod a billentyűid kiosztását a bemeneti beállítások közt. Az osu!mania beállításait az ennek megfelelő külön menüpontban találod.",
    "kiai": "A Kiai mód egy stílushatás, amelyet az időzítési beállítások panelen helyezhetsz bizonyos szakaszokra. Az ilyen szakaszok különböző vizuális hatásokkal teszik a beatmapet epikusabbá.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Szerezz [https://osu.ppy.sh/wiki/Kudosu kudosu]-t azáltal, hogy segítesz mások beatmapjeinek fejlesztésében.",
    "lag": "Laggot (szaggatást) bármi okozhat - valószínűleg más folyamatok a számítógépeden. Ha meg vagy győződve róla, hogy az osu! hibája és csak az osu! szaggat, lépj kapcsolatba a támogatással a Technical Support fórumon. Írd le részletesen a problémádat és bármi mást, ami segíthet megtalálni a hiba okát.",
    "language": "Kérlek légy udvarias a chat szobában.",
    "language-specific": "Kérjük, használja a meglátogatott csatornának megfelelő nyelvet. A román szavak vagy kifejezések használata nem kivétel a nem-római nyelvek, például a japánok számára.",
    "lazer": "",
    "level": "A szinted a teljes összegyűjtött pontszámodtól függ. Ebbe minden rankolt pontszám beletartozik, akár teljesítetted, akár elbuktad a beatmapet. A szinted folyamatosan nő már azáltal is, hogy csak játszol.",
    "lines": "Kérlek tanulj meg egy sorban írni, hogy elkerüld a némítást.",
    "link": "Szöveges link létrehozásához használd ezt a formátumot: [cím szöveg], ahol a 'cím' a link, amit be szeretnél illeszteni, a 'szöveg' pedig a szöveg, amit meg szeretnél jeleníteni. [https://osu.ppy.sh/ Például így!] Csak ne feledkezz el a http:// részről.",
    "lobby": "Kérlek, használd a #lobby-t multiplayer meccsek hirdetéséhez. A #lobby-ban többféle nyelvet is beszélhetsz. Minden további beszélgetésre használd a #multiplayer csatornát.",
    "localisation": "Megtalálod az osu! lokalizálás projektet \n[https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24\n itt].",
    "long-link": "Kérlek ne illessz be hosszú linkeket a chatbe! Használd a [link szöveg] formulát, ha nagyon muszáj.",
    "long-text": "Kérlek ne illessz be hosszú szövegeket a chatbe! Ha mégis így teszel, az némításhoz vezethet.",
    "loved": "A Loved kategóriába kerülhetnek a közösség által kifejezetten kedvelt mapek amik az általános szabályok alatt nem lehetnének rankedek. A Loved mapok rendelkeznek ranglistával de performance pontokat nem lehet velük szerezni, bővebb információt [https://osu.ppy.sh/news/151925254083 itt találsz.]",
    "mac": "[https://osx.ppy.sh Futtasd az osu!-t a Maceden]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "A mapperek elfoglalt emberek, és egy map elkészítése rengeteg munka. Miért nem próbálod meg te magad?",
    "mapping": "Kattints [https://osu.ppy.sh/forum/p/988111 ide] mapelési útmutatóért.",
    "mat": "A Mapping Assistance Team egy régen létező csoport volt, ami a BAT-nak segített a rankolási folyamatban.\nRIP MAT 2013-04-23",
    "modhelp": "Beatmap modolással kapcsolatos kérdéseidet felteheted a #mapping csatornán.",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modding Sorok]",
    "modreqs": "Mod kérésekkel kérlek fáradj a #modreqs csatornára. Tartsd észben, hogy a BAT-ok nem mindig érnek rá, és rajtad kívül mások is vannak, szóval átlagos felhasználókat is kérj meg, hogy modolják a beatmaped. Köszönjük.",
    "multi-invite": "Ha megakarsz hívni valakit a multiplayer meccsedbe miközben te vagy a szoba gazdája, akkor kattints a kívánt felhasználóra az Online Felhasználók listáján és válaszd ki az Invite to game-et.",
    "multi-link": "",
    "multiaccounting": "Nagyon, nagyon nem kéne egynél több felhasználót csinálnod. Rá fogunk jönni, és nagyon hosszú időre el leszel némítva, de akár kitiltást is kaphatsz!",
    "multiplayer": "Kérlek a #lobby-ban hírdesd a szobádat.\nHa nincsenek más játékosok, akkor miért nem játszol egyedül és próbálod meg később?",
    "mwc": "Az osu! Mania világbajnokság. Látogass el  [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 erre] az oldarra, ha többet akarsz megtudni.",
    "nat": "",
    "news": "",
    "nightcore": "Élvezd kedvenc beatmapjeid Nightcore stílusban!\nEgyszerűen kattints duplán a DoubleTime modra, hogy felfedd a Nightcore modot! Pontozás szempontjából megegyezik a DoubleTime-mal.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Írd be, hogy /np ahhoz, hogy megmutasd másoknak mit hallgatsz vagy mit játszol.",
    "nsfw": "Trágár, vagy 18+-os beszélgetés nem engedélyezett. Az osu! minden korosztály számára készül, szóval kérünk, hogy tartsd tisztán a chatet. Ellenekező esetben figyelmeztetés nélkül némítást kaphatsz.",
    "osu": "Osu!-val kapcsolatos beszélgetésre az #osu csatorna való. Kérlek, ott beszélgess a játékról, ne itt.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 Az osu!tablet hivatalos témája!] - Olvasd el ezt a tablettel kapcsolatos minden fontos információért, és az előrendeléssel kapcsolatos kérdésekért.",
    "osu!talk": "Az osu!taklk egy műsor deadbeat és ztrot vezetésével, ahol a közösség tagjaival készítenek interjút és beszélnek meg eseményeket, mint a világbajnokságok.\nMinden epizód az osu.corin.me Teamspeak 3 szerveren készül, akár kérdést is tehetsz fel a kérdezz-felelek szekcióban. [https://osu.ppy.sh/forum/t/225111 Itt] több információt találsz.",
    "osucore": "Egy április 1-i vicc 2011-ből. Minden map DoubleTime-ra volt állítva és a hangmagasságuk meg volt emelve.\nKésőbb ez visszatért Nightcore modként, melynek hatásai ugyanezek.",
    "osu!droid": "",
    "osumania": "Kérlek, használd az #osumania csatornát osu!mania-val kapcsolatos eszmecserére.",
    "osustream": "Az [http://www.osustream.com osu!stream] az osu! iOS készülékekre, és nem más készítette és tartja karban, mint a mi peppy-nk!",
    "osz": "A beatmapek .osz fájlformátumát mindenképp csak az osu!-val csomagold ki, máskülönben hibák léphetnek fel!",
    "osz2": "Egy új beatmap fájlformátum, ami azt jelenti, minden benne lévő fájl titkosítható, frissíthető és streamelhető lesz, a többi fájltól függetlenül. Az osz2 fájlokat nem kell majd kicsomagolni, és mindig .osz2 fájlokként lesznek jelen a Songs könyvtárban.",
    "owc": "Egy világméretű osu! bajnokság. Lásd [https://osu.ppy.sh/wiki/OWC további információért.]",
    "peppy": "Hogy-hogy nem tudod? peppy az [https://osu.ppy.sh/p/team osu! csapat]  vezetője!",
    "perfect": "Nem lett SS? Ez a mod automatikusan újraindítja a beatmapet, ha egy hibát is vétesz.\nAhhoz, hogy megtaláld, kattints kétszer a SuddenDeath-re a mod kiválasztásánál.",
    "ping": "Pong!",
    "pippi": "A kabalafigurája az osu!-nak. Pippi-don a taiko (dob) verziója Pippinek.",
    "piracy": "Nem kéne a chaten kalózkodásról csevegni...",
    "play-shortcuts": "A gyorsbillentyűk teljes listája: [[Shortcut_Key_Reference]]",
    "pm": "Ha privát üzenetet szeretnél írni valakinek, kattints a nevére a chatben vagy a paneljére az Online Felhasználók képernyőn, majd válaszd a Start Chat opciót.\nHasználhatod még a /msg <felhasználónév> <üzenet> parancsot is, illetve a /chat <felhasználónév> vagy a /query <felhasználónév> parancsokat, amelyek egy új fület nyitnak a chatben.\nAz utolsó üzenetre való gyors válasz küldéséhez használd a /r <üzenet> parancsot. Természetesen a < > -t távolítsd el.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "A Performance Points (pp) az osu! fő rankolási szempontja. Kattints [https://osu.ppy.sh/wiki/Performance_Points ide], hogy többet tudj meg.",
    "pp-rework-lazer": "",
    "preview": "Az előnézeti pont az a pont a számban, ahonnan a számválasztó képernyőn a kiválasztáskor a lejátszás kezdődik.\nA megfelelő előnézeti pont egy olyan pont, ami jól megmutatja, milyen a szám, például a refrén kezdete. Menj az Időzítésre az eszköztárban és kattints a Jelenlegi pozíció beállítása előnézeti pontként lehetőségre.",
    "qat": "",
    "qualified": "Beatmap Nevezők nevezik elfogadottnak a mapokat a rankedre ahol rankot szerezhetsz teljesítmény pontok nélkül.\nHa ezek a mapok hibátlanok és elfogadottak egy hétig, ranked lesz belőlük.\nHa nem, visszamegy függőbe és az eredmények törlésre kerülnek.",
    "ranked": "Egy rankolt beatmap olyan beatmap, amelyet jóváhagyott az online közösség.\nAmikor rankolt mapen játszol, az összegyűjtött pontjaid hozzáadódnak a rankolt összpontszámodhoz.\nEzen mapeknek saját rankolt toplistájuk van, és egy szív ikonról ismerheted fel őket.",
    "ranking-criteria": "A rankolási feltételekkel kapcsolatos információkért látogasd meg a wikit: [[RC]]",
    "redname": "A piros nevű felhasználók vagy [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]-k vagy [https://osu.ppy.sh/wiki/QAT QAT]-ok",
    "report": "A moderátorok nem mindig elérhetők. Ők is csak emberek, és nem nézhetik egész nap a chat-et. Ha azt látod, hogy valaki valami hülyeséget csinál, és egy mod sem reagál rá, kérlek, használd a !report parancsot.\nKérlek ne BachoBot privát üzenetben tedd ezt, és használd a !report <felhasználó> <jelentés oka> formátumot.",
    "report-abuse": "Kérlek, kerüld több jelentés elküldését egymás után - ettől még nem oldódik meg gyorsabban a helyzet. Az ok nélküli vagy értelmetlen jelentések sem segítenek.\nIgazából az is lehet, hogy némítást kapsz a chat moderátorok zaklatásáért.",
    "request": "Modolni szeretnél valamit? Kattints [https://osu.ppy.sh/p/beatmaplist&r=8 ide], vagy írd be a !request parancsot egy véletlenszerű linkért.",
    "respect": "Kérlek tiszteld a többi játékost.",
    "roll-abuse": "Kérlek kerüld a !roll parancs túlzott használatát. Némítást is kaphatsz érte.",
    "romaji": "Ne használja a Romaji (román japán) túlságosan. Lehet, hogy elhallgat.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Ha nincsenek többjátékos szobák, miért nem hozol létre egyet te magad? Még a zenéket is te választhatod ki!",
    "rp": "A szerepjáték a megfelelő csatornákban engedélyezett, viszont légy tekintettel másokra.",
    "rules": "[https://osu.ppy.sh/wiki/hu/Rules Hivatalos Szabályok]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "Időnként az osu! DDoS támadás áldozata lesz. Ezalatt a Bancho instabillá vagy elérhetetlenné válhat.\nHa gyanítod, hogy ez történt, nézz rá az [https://twitter.com/osustatus @osustatus] Twitterre, vagy [https://status.ppy.sh erre] bővebb információért.\nHa ez történik és még tudsz chatelni, folytasd úgy, mintha mi sem történt volna. A téma felhozatala nem fogja gyorsabban megszűntetni a problémát.",
    "sb": "Storyboard-készítési útmutató: https://osu.ppy.sh/forum/t/1869\nStoryboard-szerkesztő használata: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "",
    "scoring": "Az osu! így számolja ki a pontokat:\n[[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "A némítás azt jelenti, hogy nem beszélhetsz chaten vagy nem írhatsz a fórumra, kivéve a Technical Support részre. A némítások 5 percnél kezdődnek az első alkalomnál, és minden egyes alkalommal duplázódnak. Persze durvább kihágásokért több, mint a duplájára is nőhet, mint az előző némítás. Némítást csak rossz cselekedetért kaphatsz, szóval csak kövesd a szabályokat és minden rendben lesz.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Témakészítés GYIK]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Ne engedd, hogy az osu! fent tartson hajnali 4-ig! Aludni fontos!]",
    "songs-not-appearing": "Ha a zenéid nem jelennek meg a zene választó menüben, próbálj meg F5-öt nyomni.",
    "spaces": "Kérjük, ne terjesszen szóközöket minden betű között, esztétikája miatt a csevegés rendetlen és csendet okozhat.",
    "spam": "A chat spamelése némítással járó szabálysértés. Ne csináld.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Ahhoz, hogy mást nézhess, írd be, hogy /watch <felhasználónév>, vagy kattints a nevére chaten vagy a felhasználói felületen és válaszd ki a Start Spectating-et.\nBizonyosodj meg arról, hogy neked is megvan ugyanaz a beatmap, amit játszik!",
    "spoiler": "Elrontani egy animét, sorozatot, mangát stb. azzal, hogy olyan információt közölsz ami lényeges lenne, hogy élvezhető legyen a dolog némítást vonhat maga után.",
    "status": "Az osu! rendszerével kapcsolatos állapotfrissítésekhez kövesd az [http://twitter.com/osustatus @osustatus] feedet.",
    "store": "[https://osu.ppy.sh/p/market Üdvözöllek az osu! piacon], ahol király osu! pólókat és egyéb cuccokat vásárolhatsz!",
    "submit": "[https://osu.ppy.sh/wiki/Submission Beatmap Beküldés GYIK]",
    "suck": "Ne aggódj, gyakorlással fejlődni fogsz.",
    "supporter": "Légy [https://osu.ppy.sh/p/support osu! támogató]! Jópár előnnyel jár, és a játék fejlesztését is segíted vele!",
    "supporter-please": "Légy szíves ne kérj más embereket arra, hogy támogatói tag-et ajándékozzon neked. [https://osu.ppy.sh/p/support Szerezz itt helyette!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "[https://osu.ppy.sh/forum/t/87301 Olvasd el ezt] ha problémákat tapasztalsz tablettel való játék közben.",
    "tag": "A Tag többjátékos módban a játékosok egymást felváltva kattintgatnak egy beatmap kombóira. Nincs nyertes vagy vesztes, mindenki egy csapatban játszik. Spinnereknél mindenki egyszerre pörget. Ha valaki nem teljesíti a spinnert, a kombó megtörik. Minden játékos spinner bónusza hozzáadódik a csapat pontszámához.",
    "taiko": "Egy japán dob alapú játék a Bandai-Namco által. Az osu! Taiko módja ezeket a játékokat szimulálja az ütem elhelyezéseket nem figyelve, és csak a ritmusra koncentrál. [https://osu.ppy.sh/forum/t/4363 Itt van hogyan kell játszani!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Taiko mapelési segédlet]",
    "taiko-maps": "[https://osu.ppy.sh/forum/t/5397 Itt] találhatsz Taiko no Tatsujin hivatalos beatmapeket.",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Kérlek próbáljátok meg mellőzni ezt a témát és beszélgessetek másról.",
    "training": "[https://osu.ppy.sh/forum/t/4280 James Gyakorlás]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 Frissített videó-útmutatók listája az osu!-ról és a mapelésről.] A tiéd is bekerülhet, ha készítesz egyet. [https://osu.ppy.sh/forum/t/60228 Hasznos útmutatók listája mapperek/modderek számára]",
    "twc": "Egy világméretű osu! Taiko bajnokság. [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ Lásd ezt a topicot további információért.]",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Kérlek kerüld a Unicode/nem standard karakterek használatát az általános chatben.",
    "upload-cap": "Annak érdekében, hogy a mapperek törődjenek a folyamatban lévő mapjeikkel, az egyszerre folyamatban lévő mapjeid száma korlátozott.\nNormál felhasználóknak 3-6 aktív, Támogatóknak 5-10 aktív lehet, attól függően, hány rankolt mapjuk van.",
    "utf8": "Kérlek, állítsd az IRC kliensed UTF-8 kódolásra, így mindenki üzeneteit el tudod olvasni, és mások is el tudják olvasni a te üzeneteid.",
    "videogames": "Kérlek beszélgess olyanokról, hogy Touhou, Pokémon, SC, LoL, visual novelek és más videójátékkal kapcsolatos témáról a #videogames csatornán.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Üdvözlet az osu!-ban! Ha valami bajod vagy kérdésed van, amit meg kell válaszolni, akkor látogass el #help csatornára. Jó szórakozást!",
    "when": "Majd ha kész lesz.",
    "wiki": "[https://osu.ppy.sh/wiki/ The osu! Wiki] - Legyen állati jó!",
    "wiki-link": "Úgy tudsz wiki oldalakra hivatkozni, hogy az adott szót dupla szögletes zárójelbe teszed: [[ ]] Például, [[Kudosu]] úgy készült, hogy [[ ]] közé lett írva.",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 208 active FAQs (out of a possible 217) in the Hungarian (Magyar) language.",
    "completion": "The Hungarian (Magyar) FAQ as of last update is 95.85% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
