
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy Klik di sini] untuk mengunjungi osu! academy - Tutorial seputar berbagai aspek dasar permainan osu!.",
    "achievements": "Achievement akan terbuka secara sendirinya dengan menyelesaikan hal-hal tertentu, semisal mendapatkan banyak kombo pada suatu lagu atau memainkan semua beatmap pada Theme Pack. Achievement yang telah didapatkan bisa dilihat pada profil kamu kemudian.\nUntuk sebagian besar cara mendapatkan Achievement bersangkutan cukup jelas, namun untuk sebagian kecil lainnya kamu harus menemukan sendiri bagaimana cara mendapatkannya.\n",
    "add-skin": "Jika format file yang kamu dowload adalah .osk, tarik file tersebut ke jendela osu! Anda atau klik dua kali file tersebut.\nUntuk format file .rar atau .zip, ekstrak isi file ke sebuah folder dan pindahkan folder tersebut ke folder skin Anda. Pastikan Anda telah menutup jendela osu! ketika memindahkan folder skin tersebut.",
    "advertising": "Mengiklankan konten yang tidak berhubungan dengan osu! tidak dibenarkan dan dapat membuatmu ter-silence.\nHal ini meliputi server chat pihak ketiga dalam bentuk apa pun seperti Discord, Teamspeak, dan lain sebagainya.",
    "answer": "Apabila tidak ada yang menjawab pertanyaanmu, ada kemungkinan tidak ada yang tahu jawabannya!\nCobalah cari di forum apabila pertanyaan kamu berhubungan dengan osu!.",
    "appeal": "Apabila kamu merasa bahwa kamu telah di-silence secara tidak adil dan ingin mengajukan banding, hubungi administrator kami dengan mengirimkan email ke accounts@ppy.sh beserta dengan duduk perkaramu. \nMohon diingat bahwa administrator kami juga manusia, dan bandingmu akan lebih dapat diterima apabila kamu memohon secara baik-baik.",
    "approved": "Beatmap dalam kategori Approved adalah beatmap yang secara teknis tidak memenuhi kriteria untuk menjadi beatmap Ranked, namun tetap memiliki sebuah papan skor.\nBeatmap dalam kategori Approved memiliki scoreboard tersendiri, sama seperti beatmap Ranked, dan ditandai dengan lambang Api.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "[[https://osu.ppy.sh/wiki/Contests#aspire Aspire]] merupakan kontes mapping khusus yang diselenggarakan pada tahun 2016–2020.",
    "ask": "Cara terbaik untuk memperoleh jawaban adalah dengan tidak bertele-tele saat bertanya! \nDengan menanyakan Bolehkah saya bertanya?, kamu secara tidak langsung sudah bertanya.",
    "attention": "Mohon hentikan. Tidak ada yang tertarik untuk mendengar ocehanmu.",
    "avatar-change": "Kamu dapat mengubah avatarmu [https://osu.ppy.sh/home/account/edit#avatar di sini].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Halo! Aku BanchoBot! Senang bertemu denganmu.\nSayangnya aku hanya sebuah bot, jadi aku tidak bisa mengobrol denganmu :(",
    "beatmapping": "Kunjungi [https://osu.ppy.sh/wiki/Beatmapping laman wiki ini] untuk memperoleh berbagai tips umum seputar mapping.",
    "beginner": "Klik [https://osu.ppy.sh/forum/t/5456 tautan ini] untuk memperoleh berbagai beatmap yang ramah pemula.",
    "bn": "[https://osu.ppy.sh/wiki/id/People/The_Team/Beatmap_Nominators Beatmap Nominator] adalah sebuah grup yang bertugas dalam pengurusan beatmap dan bertanggung jawab dalam mengurus beatmap pending selama proses ranking.\nAnda bisa menghubungi mereka jika Anda memiliki pertanyaan atau meminta saran tentang mapping atau modding. Mereka juga mempunyai kesibukan, jadi hindari melakukan spam ke mereka.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Tidak ada gunanya untuk berkeluh kesah seputar kebosananmu. Segarkanlah pikiranmu atau cobalah sesuatu yang baru!]\nHanya karena kamu sedang bosan, kamu tidak dibenarkan untuk bersikap risih atau membanjiri layar chat dengan spam.",
    "bug": "Apabila kamu merasa menemukan suatu bug, mohon laporkan bug tersebut [https://osu.ppy.sh/forum/5 di sini]. \nPastikan bug yang ingin kamu laporkan belum pernah dilaporkan oleh pengguna lain sebelumnya.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Mohon untuk tidak menggunakan huruf kapital pada awal setiap kata yang kamu tulis. Hal ini akan membuat tulisanmu terlihat kacau-balau.",
    "caps": "Mohon untuk tidak menggunakan huruf kapital secara berlebihan. Hal ini dapat mengganggu pengguna lain dan membuatmu ter-silence.",
    "change-modes": "Untuk mengubah mode permainan yang aktif, tuju layar pemilihan lagu dan klik tombol Mode yang tertera pada bagian bawah layar atau gunakan kombinasi tombol Ctrl + 1-4. \nIngat bahwa beberapa map hanya dapat dimainkan pada mode permainan tertentu!",
    "change-name": "Untuk mengubah nama penggunamu, kamu harus terlebih dahulu menjadi seorang [https://osu.ppy.sh/p/support osu! supporter]. Setelahnya, kamu akan dapat mengubah nama penggunamu [https://store.ppy.sh/store/product/32 di sini].\nApabila kamu ingin kembali ke nama pengguna lamamu, ingin mengubah sesuatu pada namamu (mis. karena salah ketik), atau memerlukan bantuan lebih lanjut, mohon kirimkan email ke accounts@ppy.sh beserta dengan duduk perkaramu.",
    "changelog": "Segala perubahan yang ada di osu!, baik itu yang menyangkut klien permainan (termasuk Lazer), wiki, ataupun situs web, dapat kamu lihat pada laman [https://osu.ppy.sh/p/changelog riwayat perubahan].",
    "chars": "Mohon hindari pemakaian karakter unicode/non-standar di dalam chat.",
    "charts": "osu! chart merupakan paket beatmap tematik yang dirilis setiap bulannya.\nKamu dapat melihatnya [https://osu.ppy.sh/p/chart di sini!]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Kuning Muda: Pengguna biasa | Kuning: [https://osu.ppy.sh/p/support osu! Supporter]. Merah: Anggota [https://osu.ppy.sh/wiki/id/People/The_Team/Nomination_Assessment_Team NAT] atau [https://osu.ppy.sh/wiki/id/People/The_Team/Global_Moderation_Team GMT]\nPutih: Dirimu sendiri, perintah /np, atau perintah /me | Biru Tua: Pesan pribadi\nHijau: Baris percakapan yang menyebut namamu atau kata yang terdapat pada daftar highlightmu | Pink : BanchoBot.",
    "colour": "Kuning Muda: Pengguna biasa | Kuning: [https://osu.ppy.sh/p/support osu! Supporter]. Merah: Anggota [https://osu.ppy.sh/wiki/id/People/The_Team/Nomination_Assessment_Team NAT] atau [https://osu.ppy.sh/wiki/id/People/The_Team/Global_Moderation_Team GMT]\nPutih: Dirimu sendiri, perintah /np, atau perintah /me | Biru Tua: Pesan pribadi\nHijau: Baris percakapan yang menyebut namamu atau kata yang terdapat pada daftar highlightmu | Pink : BanchoBot.",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Walaupun kamu bebas untuk memanggil perintah chat sebagaimana yang diperlukan, mohon untuk tidak menggunakan perintah ini secara berlebihan.\nTindakan ini dianggap sebagai spam dan dapat membuatmu ter-silence.",
    "comment": "Jika kamu ingin menambahkan komentar kamu pada sebuah replay, tekan tombol Discussion, tulis apa yang ingin kamu katakan, lalu tekan Enter! \nJika tidak ada komentar yang muncul pada layar, centanglah opsi Show Comments di panel Discussion. Hati-hatilah, beberapa beatmap mempunyai jumlah komentar yang sangat banyak!",
    "comment-color": "Pengguna biasa hanya dapat berkomentar dengan warna putih. [https://osu.ppy.sh/p/support supporter] dapat mengkostumisasi warna komentar mereka.",
    "conferencemode": "Dibanjiri pesan Join/Quit di IRC? [http://wiki.xkcd.com/irc/Hide_join_part_messages Ini] mungkin bisa membantu!",
    "country-ranking": "[https://osu.ppy.sh/p/countryranking Papan peringkat negara]",
    "critic": "Berikanlah kritik yang membangun. Sarankan sebuah alternatif atau pemecahan untuk memperbaiki hal-hal yang kamu risaukan.",
    "ctb": "Butuh bantuan seputar mode Catch the Beat? \nKunjungi [https://osu.ppy.sh/wiki/Catch_the_Beat laman wiki ini!]",
    "cutting-edge": "Cutting-edge merupakan versi osu! eksperimental yang digunakan untuk menguji berbagai fitur baru sebelum dirilis ke stable. Beralihlah ke versi ini melalui menu Options!\nApabila kamu menemui masalah dalam memperbarui klien permainanmu, mohon [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues baca artikel ini].",
    "cwc": "CWC adalah kompetisi tingkat dunia untuk mode Catch the Beat. \n[https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 Klik link ini] untuk informasi lebih lanjut.",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Perlakukanlah orang lain sebagaimana kamu ingin diperlakukan.",
    "disable-this": "Tombol pengalih sangat langka diadakan sebagai fitur. Walaupun demikian, kamu dapat meminta sesuatu untuk diadakan melalui [https://osu.ppy.sh/forum/4 subforum Permintaan Fitur]",
    "distance-snap": "Cara paling sederhana untuk memastikan jarak antar ketukan/not sudah tepat adalah dengan menggunakan fungsi Kunci Jarak (Distance Snapping) di editor, yang berada di kanan bawah layar editor. Jarak yang kamu inginkan dapat diatur dengan menggunakan roda penggulung pada tetikus (mouse). Jika kamu menggunakan Distance Snap selama kamu me-map seluruh lagu tersebut, jarak antar ketukan/not sudah pasti sama dari awal hingga akhir map/lagu.",
    "dont-ask-peppy": "Tolong jangan bertanya kepada peppy secara terus menerus - dia orang yang cukup sibuk. Kamu bisa bertanya kepada orang lain di dalam channel ini.",
    "douche": "Sebagai upaya perlindungan, memanfaatkan celah dalam peraturan yang berupa ketiadaan dari sesuatu yang dianggap buruk, namun tidak terdapat dalam peraturan yang ada, merupakan sebuah pelanggaran yang dapat membuat kamu terkena silence oleh tim pengelola/admin.\nPeraturan resmi yang menyatakan bahwa kamu tidak boleh menjadi seorang pengacau semestinya tidak diperlukan agar kamu tidak menjadi pengacau, tapi jika memang diperlukan: janganlah menjadi pengacau.",
    "download": "Kamu dapat mengunduh lebih banyak beatmap [https://osu.ppy.sh/p/beatmaplist?q= di sini] atau paket beatmap [https://osu.ppy.sh/beatmaps/packs di sini].\nApabila kamu tidak tahu cara untuk mengimpor beatmap, ikuti [http://i.imgur.com/kpX2N3m.jpg panduan berikut].",
    "drugs": "Pembicaraan seputar narkoba atau obat-obatan terlarang di mana pun di osu! sangat tidak dibenarkan. \nosu! merupakan permainan yang terbuka bagi segala usia.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Baca [[Beatmapping#Keyboard_Shortcuts]] untuk mendapatkan daftar dari jalan pintas dalam editor.",
    "english": "#english digunakan sebagai tempat untuk mendiskusikan segala hal yang tidak memiliki satu channel yang didedikasikan khusus untuk topik tersebut, dan ini meliputi anime/manga.",
    "evade": "Menghindari silence dapat membuat akunmu di-restrict untuk jangka waktu yang sangat lama (atau bahkan di-ban).\nJangan lakukan hal ini.",
    "fallback": "Stable (Fallback) adalah versi osu! lawas. Tidak seperti Fallback, versi yang terbaru tidak lagi mendukung DirectX untuk menyederhanakan framework kami. Jika Anda dipindahkan ke versi ini, maka komputer Anda memiliki spesifikasi yang kurang dan tidak akan mendukung versi terbaru client baik yang sekarang maupun yang akan datang.\nJika Anda ingin bermain pada versi terbaru, perbaharui kartu grafis Anda dan cek apakah kartu tersebut mendukung OpenGL, yang dipakai pada versi tersebut. [https://osu.ppy.sh/wiki/GL_Support_Issues Klik di sini untuk mengetahui bagaimana caranya]",
    "faq": "Kamu sedang mengakses sistem FAQ osu!Bancho.\nosu! wiki: https://osu.ppy.sh/wiki",
    "feature": "Apabila kamu memiliki saran, kirimkan idemu di subforum [https://osu.ppy.sh/forum/4 Feature Requests].",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Mengelak dari sensor chat yang ada dapat membuatmu ter-silence.\nJangan lakukan hal ini.",
    "foul-play": "Laporkanlah pemain yang berbuat curang melalui tombol Laporkan yang terdapat pada laman profil mereka [https://i.imgur.com/GG9xlLA.png sebagai berikut].\nKamu juga dapat melaporkan skor mereka pada papan peringkat global melalui situs web osu! secara langsung. Pastikan kamu menyertakan informasi yang selengkap-lengkapnya. \nJANGAN membahas kecurangan yang terjadi di dalam ruang chat publik, karena hal ini dapat membuatmu ter-silence.",
    "percolate": "Mengelak dari sensor chat yang ada dapat membuatmu ter-silence.\nJangan lakukan hal ini.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Artikel ini] akan membantu kamu untuk memahami konsep flow dalam mapping.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Untuk menambahkan pengguna lain sebagai teman, ketik /addfriend diikuti dengan nama dari pengguna tersebut.\nDi samping itu, kamu juga dapat mengklik panel pengguna tersebut pada daftar pengguna yang sedang online (tekan F9) atau mengklik nama mereka dalam obrolan dan pilih Tambahkan sebagai Teman (atau Add as Friend).\nKamu juga dapat menambahkan mereka melalui profil mereka di website dengan mengklik tambahkan ke daftar teman (atau add friend)",
    "friends-list": "Untuk melihat daftar teman anda yang online dalam game, tekan F9 lalu ubah filter di atas layar game menjadi Friends.\nkamu juga bisa melihat daftar lengkap dari teman-teman anda, baik yang online ataupun offline pada situs osu! dengan mengklik Settings. (kamu sudah harus log in terlebih dahulu, tentunya.)",
    "fullscreen": "Kamu dapat mengatur tampilan osu! baik Windowed atau Layar Penuh pada tab Graphics pada menu Options.\nPenggantian antar mode Windowed dan Layar Penuh juga dapat dilakukan dengan kombinasi tombol Alt+Enter.\n",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Daftar istilah yang umum digunakan di osu! beserta penjelasannya dapat dilihat pada artikel [[glossary]].",
    "gmt": "[https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team], atau biasa disingkat [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT], adalah sebuah gugus pengguna (usergroup) yang membantu menjalankan osu!. Mereka memiliki nama berwarna merah di chat serta nama berwarna hijau di forum.\nMereka bertugas mengawasi forum dan chat.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Baca, pahami, terapkan.]",
    "grammar": "Gunakanlah tata bahasa yang baik sebisa mungkin. \nKesalahan kecil dalam penulisan dan penggunaan tanda baca masih dapat ditoleransi, namun mohon jangan mempersingkat kata secara berlebihan. Hal ini akan membuatmu terlihat dungu.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Ingin mengasah kemampuan bermainmu? Atau ingin mencoba menjelajah dunia mapping dan modding? \nSegala panduan yang kamu butuhkan dapat kamu temukan [https://osu.ppy.sh/wiki/Guides di sini].",
    "hacked": "Apabila kamu merasa bahwa akunmu telah diretas, mohon kirimkan email ke accounts@ppy.sh untuk dapat kami tindak lanjuti.\nApabila kamu tidak melaporkan hal ini, akunmu beresiko untuk dinonaktifkan.",
    "hard": "Latihan makannya, dasar cupu",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Bila kamu memerlukan bantuan terhadap apa pun yang berhubungan dengan osu!,\r\nkunjungi channel #help dan tanyakan pertanyaanmu. Channel #help adalah channel multi-bahasa. Jika tidak ada orang yang meresponnya, kamu bisa tanyakan di forum [https://osu.ppy.sh/forum/5 Help].\r\nKamu juga bisa membaca [http://help.ppy.sh/ halaman ini] untuk melihat bantuan lainnya, termasuk masalah tentang akun.",
    "hitsound-library": "Kunjungi [https://osu.ppy.sh/forum/p/164927 utas forum ini] untuk memperoleh berbagai hitsound yang dapat kamu gunakan.",
    "hl": "Berhenti mengeluh tentang kata yang kamu masukkan ke dalam daftar highlight selain username kamu!\nItulah resikonya bila terkena highlight. Kamu bisa menonaktifkan notifikasi dan suara notifikasi lewat pengaturan di Option ",
    "how-to-get-modded": "Informasi lebih lanjut mengenai bagaimana agar map kamu mendapat mod dapat dilihat di sini:\n[[Getting_Your_Map_Modded]]",
    "how-to-bn": "Apabila kamu ingin menjadi seorang BN, silakan baca [https://osu.ppy.sh/wiki/id/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator artikel ini].",
    "how-to-gmt": "Global Moderator dipilih dari orang-orang yang memiliki kontribusi penting kepada komunitas ini.\nUntuk informasi lebih lanjut, silakan kunjungi laman wiki [https://osu.ppy.sh/wiki/id/People/The_Team/Global_Moderation_Team Global Moderation Team].",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#how-to-play? Klik tautan ini untuk mempelajari cara untuk bermain!]",
    "how-to-rank": "Untuk mencari tahu, baca [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Hyperdash akan aktif ketika kamu akan menangkap buah yang bersinar/berpendar kemerahan. kamu akan bisa melakukan dash lebih cepat dari biasanya ketika buah yang mengaktifkan hyperdash itu akan ditangkap. Hyperdash akan menjadi tidak aktif jika kamu telah menangkap buah tersebut atau melewatkannya.",
    "ignore": "Untuk mengabaikan pengguna lain, ketik /ignore dan nama pengguna.\nKamu tidak akan melihat chat dari pengguna yang kamu abaikan termasuk PM yang dikirim ke kamu.\nUntuk mengembalikannya ketik /unignore (nama pengguna) atau tutup program osu! maka akan kembali seperti semula.",
    "import": "Ikuti [http://i.imgur.com/kpX2N3m.jpg panduan ini] untuk mengimpor beatmap ke dalam osu!.",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Dengan mencentang kotak Inherit previous timing settings di jendela F6 dalam Editor, garis timing itu tidak akan mempengaruhi timing, yang berguna untuk garis yang hanya mengubah volume dan sampel hitsound yang dipakai.\nKemudian, garis timing bisa juga dipakai untuk menggandakan atau memotong BPM (yang artinya mempercepat atau memperlambat slider). Jika kamu mendapati bahwa kamu menggunakan sebuah garis timing untuk hal ini, tolong gunakan inherit!\n",
    "irc": "Server IRC: irc.ppy.sh:6667\nKata sandi: https://osu.ppy.sh/p/irc\nRincian pengaturan IRC selengkapnya dapat dilihat pada https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Kamu dapat mengubah pengaturan tombol inputmu melalui menu Options. \nKey dan layout untuk mode osu!mania dapat diubah dengan tombol osu!mania layout.",
    "kiai": "Kiai adalah efek yang bisa kamu munculkan pada bagian-bagian tertentu dalam pengaturan waktu dengan menggunakan Timing Setup Panel. \nBagian-bagian timing dengan Kiai yang diaktifkan akan memancarkan beragam efek visual untuk menjadikan sebuah map lebih bersemangat. \n",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Kamu dapat memperoleh [https://osu.ppy.sh/wiki/id/Modding/Kudosu kudosu] dengan cara memberikan mod kepada beatmap milik mapper lain.",
    "lag": "Lag dapat disebabkan oleh [https://osu.ppy.sh/help/wiki/Performance_Troubleshooting berbagai macam hal]. Pada umumnya, lag disebabkan oleh proses lain yang berjalan pada perangkatmu. \nApabila kamu yakin bahwa osu! merupakan satu-satunya program yang terdampak oleh lag, ajukanlah permintaan dukungan pada [https://osu.ppy.sh/forum/5 forum Help] disertai dengan rincian masalahmu dan hal apa pun yang kamu rasa dapat membantu.",
    "language": "Berperilakulah dengan sopan pada ruang chat publik. Bahasa yang tidak sopan dapat membuatmu ter-silence.",
    "language-specific": "Gunakanlah bahasa yang sesuai dengan channel yang kamu kunjungi. \nPada saat kamu mengobrol dalam bahasa yang tidak ditulis dengan aksara Latin (mis. Bahasa Jepang), gunakanlah jenis huruf yang sesuai.",
    "lazer": "[https://www.youtube.com/watch?v=ut_SOreClcc Apa itu lazer?] Lazer merupakan sebutan bagi versi rilis utama osu! yang akan datang.\nGitHub: [https://github.com/ppy/osu ppy/osu] | Unduh: [https://github.com/ppy/osu/releases ppy/osu/releases]",
    "level": "Level kamu ditentukan oleh akumulasi total skormu. Ini sudah termasuk semua skor yang didapat ketika memainkan map yang telah di-rank, tanpa peduli apakah anda berhasil atau gagal menyelesaikan map di mana kamu mendapat skor tersebut. Level kamu akan naik hanya dengan terus memainkan osu!",
    "lines": "Usahakan agar pesan yang kamu kirim tidak melebihi satu baris agar kamu tidak sampai ter-silence.",
    "link": "Untuk membuat sekumpulan teks mengarahkan kita pada sesuatu hal, gunakan format ini: [alamat teks], di mana alamat merupakan alamat dari hal yang ingin kamu perlihatkan, dan teks adalah teks yang ingin kamu tampilkan. [https://osu.ppy.sh/ Seperti ini!] Ingat, Jangan lupakan http://.",
    "lobby": "#lobby merupakan channel multi-bahasa yang dikhususkan untuk mempromosikan ruangan multiplayer. Mohon untuk tidak menggunakan channel ini untuk keperluan lainnya.\nGunakanlah chat #multiplayer yang kamu miliki untuk berdiskusi dengan pemain lainnya.",
    "localisation": "Akses dokumen osu! Localisation Project [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 di sini].",
    "long-link": "Mohon untuk tidak menyalin tautan yang teramat panjang ke dalam chat!\nPersingkat tautanmu dengan format [link teks] bila perlu.",
    "long-text": "Mohon untuk tidak menyalin teks yang teramat panjang ke dalam chat. Tindakan ini dapat membuatmu ter-silence.",
    "loved": "Loved adalah status ranking baru yang berdasarkan dari pilihan komunitas yang memberikan map-map memiliki leaderboard normal namun tidak memberikan PP. [https://osu.ppy.sh/news/151925254083 Cari tau lebih lanjut di sini!]",
    "mac": "[https://osx.ppy.sh Panduan untuk menjalankan osu! di Mac]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Mapper adalah orang yang sibuk, dan mapping itu sendiri memerlukan banyak usaha.\nKenapa kamu tidak mencobanya sendiri?",
    "mapping": "Klik [https://osu.ppy.sh/forum/p/988111 tautan ini] untuk memperoleh berbagai panduan seputar mapping.",
    "mat": "Mapping Assistance Team (MAT) merupakan kelompok pengguna yang membantu BAT dalam proses ranking beatmap pada masanya dahulu.\nRIP MAT 23 April 2013",
    "modhelp": "Kunjungilah channel #mapping untuk segala hal yang terkait dengan modding dan mapping!",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modding Queues]",
    "modreqs": "Mohon gunakan channel #modreqs untuk permintaan-permintaan terkait modding.\nMohon diingat bahwa BN tidak selalu memiliki waktu senggang dan terkadang harus melayani mapper lain terlebih dahulu, sehingga jangan lupa untuk turut meminta mod pada pengguna non-BN!\nTerima kasih.",
    "multi-invite": "Untuk mengundang seseorang ke dalam permainan multiplayer kamu, klik nama pengguna yang diinginkan pada daftar pengguna yang sedang online (tekan F9) atau klik nama mereka di chat dan memilih Undang ke Pertandingan atau Invite to game.\nKamu juga dapat mengetik /invite diikuti dengan nama pengguna yang ingin diundang.",
    "multi-link": "[https://osu.ppy.sh/community/forums/topics/1366364 Klik link ini untuk mengetahui cara membuat link undangan/invitation room multiplayer]",
    "multiaccounting": "Setiap pengguna dilarang untuk memiliki lebih dari satu akun.\nApabila kamu terbukti memiliki akun lebih dari satu, kamu akan dihukum untuk jangka waktu yang panjang atau bahkan di banned.",
    "multiplayer": "Mohon untuk tidak mempromosikan ruangan multiplayer di luar channel #lobby.",
    "mwc": "MWC adalah singkatan dari Mania World Cup; Ajang kompetisi internasional untuk mode osu!mania. Baca [https://osu.ppy.sh/wiki/Tournaments/MWC halaman wiki ini ]untuk informasi lebih lanjut.",
    "nat": "Anggota-anggota [https://osu.ppy.sh/wiki/id/People/The_Team/Nomination_Assessment_Team Nomination Assessment Team] memoderasi Beatmap Nominator dan mengawasi beatmap-beatmap yang sedang dalam proses untuk menjadi ranked.\r\nMereka bertanggung jawab untuk mengevaluasi anggota dan calon anggota Beatmap Nominator, serta memediasi beatmap veto dan perbedaan pendapat yang berhubungan dengan mapping / modding.",
    "news": "osu! berubah dari waktu ke waktu. Terima kasih kepada orang-orang yang telah menjalankan dan menjaga osu! tetap hidup.\nPastikan Anda tidak melewatkan pembaruan-pembaruan di osu! dengan mengecek [https://osu.ppy.sh/home/news halaman berita osu!].",
    "nightcore": "Nikmati lagu favoritmu dengan bunyi yang tinggi ala Nightcore!\nLakukan klik kanan atau klik ganda pada mod DoubleTime untuk mengaktifkan mod Nightcore!",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Ketik /np untuk menampilkan judul lagu atau beatmap yang sedang kamu mainkan pada layar chat.",
    "nsfw": "Percakapan yang bernada eksplisit sangat tidak dibenarkan.\nosu! merupakan komunitas yang terbuka bagi segala usia, dan oleh karenanya, mohon hindari percakapan yang tidak pantas atau kamu dapat langsung di-silence tanpa ada peringatan terlebih dahulu.",
    "osu": "#osu ditujukan untuk membicarakan segala hal tentang osu!. Tolong bahas permainan osu! di sana, bukan di channel ini.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139&start=0 Thread resmi untuk osu!tablet!] - Bacalah ini untuk seluruh informasi mengenai tablet tersebut dan untuk melakukan preorder.",
    "osu!talk": "osu!talk adalah talk show yang dipandu oleh deadbeat dan ztrot dimana para anggota wawancara dari masyarakat dan mendiskusikan acara seperti piala dunia.\nSetiap episode akan berlangsung pada TeamSpeak 3 Server osu.corin.me; Anda akan dapat mengajukan pertanyaan di bagian Q&A. Info lebih lanjut dapat ditemukan [https://osu.ppy.sh/forum/t/225111 disini.]",
    "osucore": "Berawal dari sebuah lelucon April Fool tahun 2011, osu!core memiliki efek yang sama dengan DoubleTime namun dengan pitch suara yang ditinggikan.\nLelucon ini dihadirkan kembali sebagai pengubah (modifier) tersendiri yang dinamakan Nightcore, yang berefek sama dengan osu!core.",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] adalah bagian dari permainan orisinil di dalam platform Android. osu!droid tidak dilanjutkan lagi oleh pengembang resmi dan telah dihapus dari Google Play sejak 2016 karena tidak ada aktivitas dan ulasan buruk.",
    "osumania": "Mohon gunakan channel #osumania untuk diskusi yang terkait dengan mode osu!mania.",
    "osustream": "osu!stream adalah osu! yang didesain khusus untuk perangkat iOS.\nInfo lebih lanjut dapat dilihat [http://www.osustream.com di sini]. ",
    "osz": ".osz adalah format file yang kamu unduh dari Beatmap Listing dan akan diekstrak oleh osu! agar bisa dimainkan. File .osz harus selalu dibuka oleh osu! sendiri, atau masalah bisa saja terjadi!",
    "osz2": "Format file untuk beatmap yang baru, yang berarti setiap file yang terdapat di dalamnya bisa dienkripsi, diperbaharui, dan berjalan dengan sendirinya tanpa pengaruh dari file lain. osz2 tidak perlu diekstrak/dibongkar dan akan selalu berupa file .osz2 dalam folder Songs.",
    "owc": "OWC adalah singkatan dari osu! World Cup; Ajang kompetisi internasional untuk mode osu!standard. Baca [https://osu.ppy.sh/wiki/OWC halaman wiki] ini untuk informasi lebih lanjut.",
    "peppy": "peppy adalah kepala developer/pengembang osu! dan menangani sebagian besar proyek yang berkaitan dengan osu! sendirian.",
    "perfect": "Tidak bisa mendapatkan SS? Mod ini akan mengulang mapnya jika kamu membuat satu kesalahan.\nkamu dapat mencobanya dengan klik-kanan atau double-click SuddenDeath dalam pemilihan mod.",
    "ping": "Pong!",
    "pippi": "Maskot resmi osu!. \nPippi-don adalah versi taiko (drum) dari Pippi.",
    "piracy": "Mohon untuk tidak membahas pembajakan konten berhak cipta di dalam ruang chat publik. Hal ini tidak dibenarkan dan dapat membuatmu ter-silence.",
    "play-shortcuts": "Daftar tombol shortcut selengkapnya:\n[[Shortcut Key Reference]]",
    "pm": "Untuk mengirim PM kepada seseorang, klik nama mereka pada User Panel pada layar Online Users (F9) kemudian pilih Start Chat.\nKamu juga dapat menggunakan perintah /msg <nama pemain> <pesan> serta /chat <nama pemain> atau /query <nama pemain>, yang akan membuka tab baru pada layar chat kamu.\nUntuk membalas suatu pesan secara cepat, kamu dapat menggunakan perintah /r <pesan>.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance Point (pp) merupakan sistem perhitungan peringkat utama yang berlaku di osu!.\n[https://osu.ppy.sh/wiki/id/Performance_points Klik tautan ini] untuk memperoleh informasi lebih lanjut seputar Performance Point.",
    "pp-rework-lazer": "",
    "preview": "Preview point adalah titik di mana sebuah lagu mulai dimainkan jika kita memilihnya pada layar pemilihan lagu.\nTempat yang baik untuk meletakkan preview point adalah pada titik dalam sebuah lagu yang dianggap dapat mewakilkan isi lagu tersebut, seperti awal dari chorus. Masuklah ke Timing di toolbar dan klik Pilih Posisi Sekarang sebagai Preview Point untuk memilih tempat yang pas.\n",
    "qat": "Quality Assurance Team bertugas untuk memeriksa kualitas dan kelayakan beatmap yang baru saja qualified.\nSeiring dengan berkembangnya sistem ranking beatmap, pada April 2019, nama mereka diubah menjadi Nomination Assessment Team agar sesuai dengan lingkup kerja mereka saat ini.",
    "qualified": "Ini adalah sistem modding masa depan! Kalian bisa menominasikan suatu map agar siap untuk di ranking. Kamu bisa secara instan mendapatkan ranking di map itu (tidak dengan performance points). Map tersebut berada pada status qualified untuk jangka waktu satu minggu. Selama seminggu, ada kemungkinan map akan kembali pending jika ditemukan suatu masalah. Jika map kembali pending, skor akan dihapus. Ketika beatmap tetap berada di status Qualified selama 1 minggu, maka beatmap itu akan menjadi Ranked.\n ",
    "ranked": "Beatmap dengan status Ranked menandakan bahwa beatmap tersebut telah disetujui oleh staf-staf osu!, dan sudah memiliki leaderboard-nya tersendiri.\nKetika kamu memainkan map berstatus Ranked, skor yang kamu peroleh akan ditambahkan ke dalam Ranked Score akumulatif.\nSebagai tambahan, map-map berstatus Ranked ditandai dengan ikon panah atas.",
    "ranking-criteria": "Untuk informasi lebih lanjut seputar Ranking Criteria, kunjungi laman wiki berikut: [[RC]]",
    "redname": "Pengguna yang namanya berwarna merah di chat merupakan anggota [https://osu.ppy.sh/wiki/id/People/The_Team/Global_Moderation_Team Global Moderation Team (GMT)] atau [https://osu.ppy.sh/wiki/id/People/The_Team/Nomination_Assessment_Team Nomination Assessment Team (NAT)].",
    "report": "Gunakan format berikut untuk melaporkan perilaku buruk atau kecurangan: !report <nama_pemain> <alasan>\r\nLaporan tidak dapat dilihat oleh pengguna lain dan harus dilakukan di channel publik. Hindari menggunakan perintah ini di PM.\r\nKamu juga dapat melaporkan pengguna dengan mengklik nama pengguna lalu pilih Report User atau Laporkan Pengguna",
    "report-abuse": "Mohon hindari mengirimkan laporan (report) berturut-turut - itu tidak membantu untuk menyelesaikannya lebih cepat. Juga hindari mengirim laporan kosong atau laporan yang tidak masuk akal.\nBahkan, anda mungkin dapat ter-silence karena dianggap spam oleh chat moderator.",
    "request": "Sedang mencari map untuk di-mod?\nKlik [https://osu.ppy.sh/p/beatmaplist&r=8 tautan ini] atau ketik !request untuk menampilkan map Pending yang dipilih secara acak.",
    "respect": "Mohon hormati pemain lain.",
    "roll-abuse": "Mohon jangan menggunakan perintah !roll secara berlebihan. Hal ini dapat membuatmu ter-silence.",
    "romaji": "Mohon untuk tidak menggunakan penulisan Romaji (bahasa Jepang Romawi) secara berlebihan. Hal ini dapat membuatmu ter-silence.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Kamu dapat membuat room kamu sendiri apabila tidak ada room yang sesuai. Dan juga, kamu bisa memilih lagu kesukaanmu!",
    "rp": "Kamu bebas mengunjungi dan berinteraksi pada channel-channel osu!, namun mohon dibatasi seperlunya agar orang lain tidak merasa terganggu.",
    "rules": "[https://osu.ppy.sh/wiki/id/Rules Peraturan resmi osu!]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "Dari waktu ke waktu, osu! terus mendapat serangan DDoS. Ketika ini terjadi, Bancho mungkin saja menjadi tidak stabil atau kita tidak bisa tersambung dengan Bancho.\nJika kamu merasa ini telah terjadi, periksalah [http://twitter.com/osustatus @osustatus] atau [https://status.ppy.sh ini] untuk info lebih lanjut.\nApabila hal ini terjadi, dan kamu masih bisa bercakap ria di chat - biarkan saja. Membicarakan serangan DDoS yang sedang terjadi tidak akan membuat serangan tersebut berakhir lebih cepat.",
    "sb": "[[Storyboarding]]\nPanduan Storyboarding: https://osu.ppy.sh/forum/t/1869\nCara menggunakan Storyboard Editor: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "scorev2 adalah algoritma skor baru yang memiliki maksimal skor 1 juta poin untuk semua mode permainan, tidak termasuk putaran (spinner) dan mods. scorev2 juga mengubah peraturan tentang luncuran (slider) sehingga membutuhkan ketepatan waktu seperti hitcircle.",
    "scoring": "Bagaimana osu! menghitung skor: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Pengguna yang di-silence hanya dapat membuat postingan di Technical Support.\nDurasi silence dimulai dari 5 menit untuk pelanggaran pertama, dan akan berlipat ganda seiring dengan jumlah pelanggaran yang dilakukan. Pelanggaran yang fatal dapat berdampak pada silence/pendiaman yang berdurasi panjang.\nUmumnya silence hanya digunakan untuk yang menindak user yang melanggar peraturan, jadi kamu akan aman apabila menaati peraturan.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Skinning FAQ]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Jangan bermain osu! sampai jam 4 pagi. Ingat, turu itu penting!]",
    "songs-not-appearing": "Apabila beatmap yang kamu miliki tidak muncul pada layar pemilihan lagu, cobalah untuk menekan F5.",
    "spaces": "Tolong jangan menempatkan spasi di antara tiap huruf, estetika anda membuat chat terlihat berantakan dan bisa mendapatkan hukuman.",
    "spam": "Mohon untuk tidak membanjiri layar chat dengan spam. Hal ini sangat mengganggu dan dapat membuatmu ter-silence.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Untuk menonton pemain lain, ketik /watch <username> atau klik nama mereka di chat atau user panel dan pilih Start Spectating. Pastikan kamu mempunyai beatmap yang sedang orang itu mainkan!",
    "spoiler": "Membocorkan cerita (spoiler) dari anime, serial, manga, doujin, dll itu dilarang dan Anda bisa terkena hukuman/silence. Biarkan orang lain menikmati sesuatu yang mereka sukai.",
    "status": "Untuk informasi terkini mengenai status sistem osu!, kamu dapat mengunjungi [http://twitter.com/osustatus @osustatus] di Twitter. dan untuk status server, ada [https://status.ppy.sh disini]",
    "store": "[http://store.ppy.sh/ Selamat datang di osu! store], tempat di mana kamu dapat membeli berbagai barang dan aksesoris terkait osu!.",
    "submit": "[https://osu.ppy.sh/wiki/Submission FAQ pengunggahan beatmap]",
    "suck": "Jangan khawatir, kemampuan kamu akan berkembang seiring dengan latihan!",
    "supporter": "[https://osu.ppy.sh/p/support Klik link ini] untuk informasi lebih lanjut mengenai osu! supporter. Anda akan mendapatkan fitur ekstra dan mendukung tim developer osu! untuk menambah fitur-fitur menarik lainnya!",
    "supporter-please": "Mohon untuk tidak mengemis supporter tag kepada pengguna lain. [https://osu.ppy.sh/p/support Kamu dapat membeli supporter tag milikmu sendiri di sini!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Jika kursor kamu bergerak tak terkendali coba atur sensitif mouse kamu di game menjadi 1.00x. Sensitif yang tinggi bisa dilakukan dengan mengecilkan area tablet kamu. Jika kursor tidak bergerak sama sekali, pastikan kamu sudah mematikan Raw Input di Pengaturan. untuk pertanyaan seputar tablet , [https://osu.ppy.sh/forum/t/87301 silahkan baca topik ini.]",
    "tag": "Dalam mode TAG multiplayer, semua pemain mengambil giliran setiap satu kombo pada beatmap tersebut. Tidak ada yang menang atau kalah, semua pemain saling kerja sama.\nDalam spinner, semua pemain ikut memutarnya. Jika salah satu gagal, maka kombo pecah. Setiap bonus spinner dari para pemain akan di tambahkan langsung ke nilai tim.",
    "taiko": "Taiko adalah game asal Jepang bertema drum/gendang yang dikembangkan oleh Bandai Namco. \nMode Taiko dari osu! sendiri mensimulasikan bagaimana permainan tersebut berlangsung.\n[https://osu.ppy.sh/forum/t/4363 Klik di sini untuk mengetahui bagaimana cara memainkannya!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Panduan mapping Taiko]",
    "taiko-maps": "Kamu dapat menemukan map otentik dari Taiko no Tatsujin  [https://osu.ppy.sh/forum/t/5397 di sini.]",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Bisakah Anda mengganti topik pembicaraan sekarang dan berbicara sesuatu yang lain?",
    "training": "[https://osu.ppy.sh/forum/t/4280 James Training]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 Video-video tutorial seputar dunia osu! dan mapping.] Dipersilahkan bagi kamu untuk membuat panduan kamu sendiri bila berkenan.\n[https://osu.ppy.sh/forum/t/60228 Panduan-panduan yang berguna bagi mapper/modder]\n\n",
    "twc": "TWC adalah kompetisi tingkat dunia untuk mode Taiko.\n[https://new.ppy.sh/wiki/Tournaments/TWC/2017/ Klik link ini] untuk informasi lebih lanjut.",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Mohon hindari pemakaian karakter unicode/non-standar dalam chat. Hal ini dapat membuatmu ter-silence.",
    "upload-cap": "Untuk membuat para mapper tetap mendedikasikan diri terhadap map yang sedang mereka urus, ada batasan yang diterapkan untuk jumlah map yang sedang dalam proses pengerjaan atau menuju ranking.\nPara non-supporter bisa memiliki 3-6 map yang masih dalam proses pengerjaan/ranking dalam waktu bersamaan, sementara para supporter bisa memiliki 5-10, tergantung berapa jumlah map mereka yang sudah di-rank.",
    "utf8": "Mohon gunakan Encoding UTF-8 pada IRC Client anda, agar apa yang kamu kirim dapat dilihat dan dimengerti oleh pemain osu! dan pengguna IRC yang lain.",
    "videogames": "Percakapan seputar video game bisa dilakukan di #osu, tetapi itu menganggu chat atau diskusi yang sedang berlangsung, silahkan menuju #videogames.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Selamat datang di osu!.\nApabila kamu menemui suatu masalah atau memiliki pertanyaan tertentu, jangan sungkan untuk meminta bantuan pada channel #help.\nSelamat bersenang-senang!",
    "when": "Ketika telah siap.",
    "wiki": "[https://osu.ppy.sh/wiki/ osu! Wiki] - Buatlah menjadi luar biasa!",
    "wiki-link": "Kamu dapat menautkan laman wiki dengan cara membubuhkan tanda dua kurung siku sebagai berikut: [[...]] \nSebagai contoh, untuk menautkan [[Kudosu]], tulis Kudosu dengan diawali oleh [[ dan diakhiri oleh ]].",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 216 active FAQs (out of a possible 217) in the Indonesian (Bahasa Indonesia) language.",
    "completion": "The Indonesian (Bahasa Indonesia) FAQ as of last update is 99.54% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer sudah diatur ke 60 detik!"
}
