
strings = {
    "academy": "[https://www.youtube.com/user/osuacademy Clicca qui] per vedere i video dell'osu!academy - video-tutorial per capire le basi del gioco.",
    "achievements": "Puoi ottenere achievements completandone gli obiettivi durante una canzone, come ad esempio raggiungendo una combo molto alta o giocando tutte le canzoni di un theme pack.\nPuoi vedere quelli già ottenuti sul tuo profilo o controllare gli obiettivi per sbloccarne altri. Ogni nome è un indizio per ottenere il rispettivo achievement.",
    "add-skin": "Per aggiungere una nuova skin scaricala e trascina il file nella finestra di osu!, oppure fai doppio click su di esso.",
    "advertising": "Pubblicizzare contenuti non correlati ad osu! è proibito e potresti venir silenziato.",
    "answer": "Se nessuno ti risponde è possibile che nessuno sappia la risposta!\nProva a cercare nel forum se il tuo problema ha a che fare con osu!",
    "appeal": "Se sei stato silenziato e pensi che non sia corretto, contatta gli amministratori inviando un'email ad accounts@ppy.sh, spiegando la tua situazione. Ricordati che anche gli amministratori sono persone! Se sei gentile nei loro confronti saranno più propensi a rimuovere il silence, se possibile.",
    "approved": "Le mappe approvate non possono essere rankate per un motivo o per un altro - ma sono comunque ottime da giocare, con la classifica e tutto il resto! Puoi capire che è una mappa approvata se la sua icona è un Segno di Spunta verde.\n",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire, il contest di beatmapping di alto livello su osu! ritorna nel 2017 con una canzone di Helblinde.  [http://osu.ppy.sh/news/156171674413 Guarda subito!]",
    "ask": "Il miglior modo per ricevere una risposta è chiedere direttamente. Non serve chiedere il permesso di domandare.",
    "attention": "Puoi smetterla per favore? Nessuno sta ascoltando quello che stai dicendo...",
    "avatar-change": "Puoi cambiare il tuo avatar [https://osu.ppy.sh/home/account/edit#avatar qui.]",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Ciao, sono BanchoBot! Piacere di conoscerti!\nSono un bot, quindi non posso avere una conversazione con te! :(",
    "beatmapping": "Per consigli generali sul mapping leggi [https://osu.ppy.sh/wiki/IT:Beatmapping beatmapping].",
    "beginner": "Sei un nuovo arrivato? Ecco una [https://osu.ppy.sh/forum/t/46282 guida per iniziare!]",
    "bn": "Il [[Beatmap Nomination Group]] è un gruppo di persone incaricate di rankare le beatmaps e sono responsabili della moderazione inerente alle beatmaps in processo di ranking.\nNel caso tu abbia dubbi riguardo il mapping in generale, puoi chiedere a loro per delucidazioni. Basta che non li disturbiate troppo, siccome sono persone indaffarate.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Non c'è motivo di lamentarsi in chat quando si è annoiati]. Esserlo non significa che puoi spammare o lamentarti di qualsiasi cosa su osu!",
    "bug": "Segnala eventuali bug nel [https://osu.ppy.sh/forum/5 forum Help] quando li trovi! Prima di postare, assicurati che nessuno lo abbia segnalato prima di te.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Scrivere Così Non È Figo, Corretto, Né Utile A Nessuno.\nFai un favore a tutti e smettila.",
    "caps": "Per favore non scrivere tutto in maiuscolo - non è desiderato in chat, e potresti anche essere silenziato se continui.",
    "change-modes": "Per cambiare la modalità di gioco, vai nel menù di selezione della canzone e clicca su Mode in basso a sinistra oppure usando CTRL + 1/4. Ricorda che alcune beatmap possono essere giocate in una sola modalità!",
    "change-name": "Per cambiare il tuo nome utente, devi prima diventare un [https://osu.ppy.sh/p/support osu! supporter], ma solo la prima volta. Per altri cambi di nome utente, dovrai comprarlo nello [https://store.ppy.sh store]!",
    "changelog": "[https://osu.ppy.sh/p/changelog Qui] puoi controllare gli ultimi aggiornamenti di osu!",
    "chars": "Per favore cerca di non utilizzare caratteri non-standard nelle chat pubbliche.",
    "charts": "Le Spotlights sono chart a tema che vengono rilasciati ogni mese. Puoi trovarle [https://osu.ppy.sh/p/chart qui]!",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Giallo Chiaro: Un utente normale | Giallo: Un [https://osu.ppy.sh/p/support Supporter] | Rosso: Un [https://osu.ppy.sh/wiki/QAT QAT] oppure un [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT].\nBianco: Te stesso | Blu: Un PM (Messaggio Privato) | Verde: Un messaggio che contiene il tuo username (chiamato anche highlight) | Rosa: BanchoBot",
    "colour": "Giallo Chiaro: Un utente normale | Giallo: Un [https://osu.ppy.sh/p/support Supporter] | Rosso: Un [https://osu.ppy.sh/wiki/QAT QAT] oppure un [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT].\nBianco: Te stesso | Blu: Un PM (Messaggio Privato) | Verde: Un messaggio che contiene il tuo username (chiamato anche highlight) | Rosa: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Anche se i comandi della chat sono fatti per la semplicita d'uso, per favore non abusarne. Questo è visto come spam e può portare ad un silence.",
    "comment": "Se mentre stai guardando un replay ti viene voglia di fare un commento premi il tasto Discussione, scrivi qualcosa e premi invio!\nSe nessun commento appare sullo schermo seleziona Mostra commenti sul pannello dei commenti.",
    "comment-color": "Un utente normale può soltanto scrivere commenti in bianco. Un [https://osu.ppy.sh/support supporter] può invece scegliere il colore da usare per commentare!\n",
    "conferencemode": "Per scoprire come disabilitare i messaggi di Entrata/Uscita degli utenti nella maggior parte dei client IRC, clicca qui: http://wiki.xkcd.com/irc/Hide_join_part_messages",
    "country-ranking": "[https://osu.ppy.sh/p/countryranking Ranking per nazionalità]",
    "critic": "Siete pregati di fare critiche costruttive. Suggerite alternative o modi per risolvere i problemi anziché scherzarci su e non migliorare la situazione.",
    "ctb": "Bisogno di aiuto per Catch the Beat? [https://osu.ppy.sh/wiki/Catch_the_Beat Qui] trovi la wiki!",
    "cutting-edge": "Cutting-edge è una versione del gioco che sostituisce il vecchio osu!test.\nPuoi [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues leggere questo articolo] se hai problemi ad aggiornare il client.",
    "cwc": "Torneo ufficiale di Catch the Beat a livello mondiale.\n[https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 Qui] il topic dell'ultima edizione.\n",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Tratta gli altri come vorresti essere trattato.\nSe sei un masochista verbale assumi che tutti gli altri non lo siano.",
    "disable-this": "Alternative alle caratteristiche del gioco vengono raramente aggiunte.\nPuoi comunque provare a chiederlo [https://osu.ppy.sh/forum/4 qui].",
    "distance-snap": "Il Distance Snap è uno strumento che obbliga a tenere le giuste distanze tra le note, basandosi sulle loro posizioni nella timeline. Ulteriori Dettagli: [[Distance_Snap/IT]]",
    "dont-ask-peppy": "Per favore non chiedere a peppy - è molto impegnato.\nComunque, chiedi pure in questo canale!",
    "douche": "Come linea guida generale, tentare di aggirare le regole o cercare scappatoie nel sistema è punibile a discrezione del team amministrativo.\nUna regola che dica di non fare il cretino non dovrebbe essere necessaria affinché tu non lo faccia, ma giusto per essere sicuri: non fare il cretino.",
    "download": "Puoi scaricare più canzoni [https://osu.ppy.sh/p/beatmaplist qui] o interi pacchetti [https://osu.ppy.sh/beatmaps/packs qui].\nIn caso tu non sappia come si installino, leggi [http://i.imgur.com/kpX2N3m.jpg qui].",
    "drugs": "Discussioni riguardo a droghe di ogni tipo sono vietate ovunque su osu!. Questo è un gioco per tutte le età.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "[https://osu.ppy.sh/wiki/Beatmapping#keyboard-shortcuts Qui] trovi la lista delle scorciatoie da tastiera dell'editor.\n",
    "english": "#english è il canale per parlare del più e del meno in lingua inglese. Ciò include anime e manga. E treni. Ed anche cosa hai mangiato ieri sera a cena.",
    "evade": "Evadere un silence può portarti al ban, sia temporaneo che permanente.",
    "fallback": "La versione Stable (Fallback) è una versione in disuso del gioco. A differenza di questa versione, le più recenti non hanno alcun supporto per DirectX al fine di semplificare la struttura del gioco.\nSe ti ritrovi su questa versione vuol dire che il tuo pc non supporta le versioni correnti e non sarà neppure in grado di supportare quelle future.\nSe vuoi giocare sulle versioni aggiornate del gioco aggiorna i tuoi driver grafici e fai in modo che essi supportino OpenGL, il componente richiesto per far andare queste versioni. Clicca [https://osu.ppy.sh/wiki/GL_Support_Issues qui] per scoprire come.",
    "faq": "Stai attualmente usando il sistema di FAQ di Bancho.\nLe FAQ principali di osu! possono essere trovate [https://osu.ppy.sh/p/faq qui], mentre la wiki di osu! può essere trovata [https://osu.ppy.sh/wiki qui].",
    "feature": "Se hai un'idea per migliorare il gioco, postala [https://osu.ppy.sh/forum/4 qui]!\nAssicurati di leggere le [https://osu.ppy.sh/forum/t/454006 linee guida del forum] però!",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Evitare i filtri può portare ad un silence. Non provarci.",
    "foul-play": "Per favore segnala i giocatori scorretti usando il tasto segnala sul loro profilo, situato qui [https://i.imgur.com/GG9xlLA.png qui]. Cerca di dare piu dettagli possibile. Puoi anche segnalare i loro punteggi alla classifica top 50 della pagina del beatmap.",
    "percolate": "Evitare i filtri può portare ad un silence. Non provarci.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/forum/t/86329 Qui] puoi trovare una guida per capire meglio il flow nel mapping.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Per aggiungere una persona come amico, scrivi /addfriend seguito dal nome dell'utente che si vuole aggiungere.\nPuoi anche cliccare sui loro pannelli utente premendo F9 o sui loro nomi e selezionare Add as Friend.\nInoltre puoi aggiungerli passando per il loro profilo e cliccare Add as Friend.",
    "friends-list": "Per vedere la lista dei tuoi amici che sono online premi F9 e poi cambia il filtro in alto su Amici. Puoi anche vedere la lista completa dei tuoi amici online e offline dal sito, cliccando su Settings. (Devi aver effetuato il login ovviamente)",
    "fullscreen": "Puoi cambiare la modalità di gioco (da Fullscreen a Windowed o viceversa) attraverso la scheda Grafica nel menu delle opzioni.\nPuoi anche usare Alt+Invio dalla tastiera. Nota: la modalità fullscreen è disabilitata per OpenGL",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Puoi trovare la terminologia di osu! nel [https://osu.ppy.sh/wiki/IT:Glossary glossario]",
    "gmt": "Gli utenti del [https://osu.ppy.sh/wiki/IT:GMT Global Moderation \nTeam], o GMT, aiutano a moderare il forum e la chat. Hanno il nick rosso in chat e verde sul forum.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 È così facile che persino tu puoi farcela... Credo.]",
    "grammar": "Sforzati a usare una buona grammatica. Qualche errore di ortografia, di punteggiatura o di distrazione è accettabile, ma non continuare a scrivere abbreviato o in modo sgrammaticato: ti farà sembrare stupido.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Pensi di non saper giocare bene? Vuoi Immergerti nel mondo del mapping?\n>[https://osu.ppy.sh/forum/t/33998 Qui]< troverai tutte le risposte.",
    "hacked": "Se pensi che il tuo account sia stato hackato, invia una email a accounts@ppy.sh e lo staff se ne occuperà. Non segnalare il caso può portare a una sospensione dell'account.",
    "hard": "Impara a giocare, scarsone.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Se hai bisogno di aiuto per ogni cosa relativa a osu! chiedi in #help!",
    "hitsound-library": "Se hai bisogno di custom hitsounds per la tua mappa, dirigiti >[https://osu.ppy.sh/forum/p/164927 qui]< per trovarli!",
    "hl": "Non lamentarti se ricevi tanti highlight per una parola che hai aggiunto alla lista. È solo colpa tua.\nSe non ti va bene, togli la parola dalla lista che trovi nelle opzioni.",
    "how-to-get-modded": "https://osu.ppy.sh/wiki/Getting_Your_Map_Modded Qui] trovi alcuni metodi per ottenere mods (guida in inglese).",
    "how-to-bn": "Se vuoi diventare BN, dai un'occhiata [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator qui].",
    "how-to-gmt": "I moderatori globali sono scelti manualmente tra gli utenti che si impegnano a contribuire al gioco.\nVuoi aiutarci? Fai del tuo meglio nel moderare tutti i canali che frequenti segnalando abusi usando il comando !report.",
    "how-to-play": "[https://osu.ppy.sh/?p=faq&n=2&c=2#c2 Clicca qui per imparare come giocare!]",
    "how-to-rank": "[https://osu.ppy.sh/wiki/How_to_Get_Your_Map_Ranked Leggi questo se vuoi sapere come far diventare la tua mappa rankata!]",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "In alcuni casi dei frutti potrebbero avere un alone rosso: è l'Hyperdash, che si attiva in automatico per fare in modo di raggiungere frutti che normalmente non sono raggiungibili soltanto con l'utilizzo del Dash.",
    "ignore": "Per ignore un utente scrivi /ignore seguito dal nome dell'utente.\nNon puoi vedere ciò che gli utenti ignorati scrivono, messaggi privati inclusi. Scrivendo /unignore (nome dell'utente) o uscendo da osu! questo effetto svanirà.\n",
    "import": "[http://i.imgur.com/kpX2N3m.jpg Leggi qui se vuoi sapere come importare le beatmaps su osu!]",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Un'inherited timing section è una sezione di timing che non modificherà il timing vero e proprio, ma permetterà di cambiare il volume degli hitsounds, aggiungere custom hitsounds e cambiare la velocità degli slider.\n",
    "irc": "Server IRC: irc.ppy.sh:6667\nPassword: https://osu.ppy.sh/p/irc\nPiù dettagli nella [https://osu.ppy.sh/wiki/IRC wiki]",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Puoi cambiare le combinazione della tastiera dalle opzioni.\nPuoi cambiare i tasti e i layout in osu!mania dal pulsante layout di osu!mania.",
    "kiai": "Il Kiai è un effetto che puoi applicare inserendo una sezione timing nel pannello apposito. Viene usato per enfatizzare un momento della mappa, quindi stai attento prima di inserirlo!",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Ottieni [[IT:kudosu]] moddando le mappe di altre persone, ovvero fornendo commenti costruttivi per il loro miglioramento. ",
    "lag": "Lag è una parola con diversi significati e può essere descritta anche solo per indicare un qualcosa di sbagliato.\nSe ti stai lamentando del lag, specifica DOVE è avvenuto e COSA è successo (problema di connessione, di scheda grafica, fps bassi, lag del tuo cervello?).\nInoltre, specifica quando è avvenuto e controlla se non ci sono altri programmi in uso che possano aver causato il lag.",
    "language": "Per favore, sii gentile nella chat ed evita di usare parole scurrili o potresti venir silenziato.",
    "language-specific": "Utilizza la lingua appropriata del canale che stai visitando. L'uso di parole o frasi romanizzate non costituisce un'eccezione per le lingue non romane come il giapponese.",
    "lazer": "",
    "level": "Il tuo livello è basato sul tuo score totale accumulato fino ad ora. Questo include qualsiasi score rankato, che tu abbia passato la mappa o no. Aumenterai di livello gradualmente, semplicemente giocando a osu!",
    "lines": "Scrivi sempre su una riga quando possibile per evitare di venir silenziato.",
    "link": "Per linkare qualcosa puoi fare in questo modo: [link testo]; [https://osu.ppy.sh/ ecco come uscirà!]\nNon scordarti la parte http:// nel link e di separare link e testo con uno spazio.",
    "lobby": "Per cercare giocatori per la tua partita multiplayer prova a chiedere in #lobby (questo canale è internazionale). \nPer ogni altro genere di discussione utlizza il canale #multiplayer per favore.",
    "localisation": "[https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 Qui] puoi trovare l'osu! Localisation project.",
    "long-link": "Per favore non incollare link troppo lunghi nella chat! Usa la formula [link testo] per evitare di intasare il canale.",
    "long-text": "Per favore, evita di incollare testi troppo lunghi nella chat.\nPotresti venir silenziato.",
    "loved": "Le mappe amate sono un nuovo stato di rank basato sulla comunità che da a delle mappe non rankabili una classifica. [https://osu.ppy.sh/news/151925254083 Ulteriori Informazioni qui!]",
    "mac": "[https://osx.ppy.sh Come giocare a osu! sul tuo Mac! (guida in inglese)",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "I mapper sono persone parecchio occupate ed il mapping è un lavoro lungo e laborioso. Perché non provi a mappare tu stesso invece?",
    "mapping": "[https://osu.ppy.sh/forum/t/143029 Qui] una lista di alcune guide per il mapping (in inglese).",
    "mat": "Il Mapping Assistance Team era un vecchio gruppo di utenti che assistivano i BAT nel processo di ranking.\nRIP MAT 2013-04-23",
    "modhelp": "Per tutte le tue domande riguardo il mapping/modding sei pregato di rivolgerti agli utenti di #mapping!",
    "modqueue": "Clicca [https://osu.ppy.sh/forum/60 qui] per accedere alle Modding Queues!",
    "modreqs": "Per chiedere una mod vai in #modreqs.\nRicorda che i BN non hanno sempre tempo e che altra gente può aver chiesto prima di te, quindi chiedi una mod anche agli altri utenti, grazie.",
    "multi-invite": "Per invitare qualsiasi persona nella tua partita multiplayer, clicca sull'utente desiderato nella lista di utenti online (F9) e scegli Invite to game.",
    "multi-link": "",
    "multiaccounting": "Non dovresti mai e poi mai creare più di un account. Sarai scoperto e silenziato per un lungo periodo di tempo, o addirittura bannato!",
    "multiplayer": "Per favore, pubblicizza la tua stanza multigiocatore nel canale #lobby. \nSe non ci sono altri giocatori, perchè non giochi da solo e riprovi più tardi?",
    "mwc": "Un torneo di osu! Mania a livello mondiale. Per favore visita [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 la pagina wiki (in inglese)] per ulteriori informazioni.",
    "nat": "",
    "news": "",
    "nightcore": "Goditi le tue mappe preferite nello stile Nightcore! Basta cliccare due volte sulla mod DoubleTime per abilitare la Nightcore mod! Ha lo stesso punteggio di DoubleTime.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Scrivi /np per far sapere alla gente quale canzone stai sentendo o quale mappa stai giocando.",
    "nsfw": "Contenuti o discussioni oscene sono severamente vietati nella chat. osu! è per tutte le età, quindi per piacere mantieni la chat pulita o rischierai di essere silenziato senza alcun avviso.",
    "osu": "#osu è per parlare della modalità standard e del suo gameplay.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139&start=0 Il topic ufficiale dell'osu!tablet!] - Leggi questo per tutte le informazioni sul tablet, e opzioni di preordine.",
    "osu!talk": "L'osu!talk è uno show condotto da deadbeat e ztrot nel quale si svolgono interviste ad utenti famosi o discussioni riguardo alcuni eventi, come ad esempio l'Osu World Cup.\nGli episodi verranno registrati sul [https://discord.gg/014x1ACj2VdUPLU5x discord server]. Potrai chiarire i tuoi dubbi nella sezione Q&A. Per ulteriori informazioni vai [https://osu.ppy.sh/forum/t/225111 qui.]",
    "osucore": "Il Pesce d'Aprile del 2011. Tutte le mappe avevano DoubleTime attivato e il loro pitch aumentato.\nIn seguito verrà introdotta la modalità Nightcore, con gli stessi effetti.",
    "osu!droid": "",
    "osumania": "Per favore, usa il canale #osumania per discussioni relative a osu!mania.",
    "osustream": "[http://www.osustream.com osu!stream] è osu! per i dispositivi iOS!",
    "osz": "È il formato delle beatmap che scarichi per osu!. I file osz devono essere estratti tramite osu! (trascinando il file nel gioco), altrimenti potrebbero esserci degli errori.",
    "osz2": "Un nuovo formato di file per le beatmap, ogni file può essere criptato, aggiornato e inviato indipendentemente da tutti gli altri file. I file osz2 non dovranno essere estratti e rimarranno sempre .osz2 nella cartella Songs",
    "owc": "Un torneo di osu! a livello mondiale.\n[https://osu.ppy.sh/wiki/OWC Qui] il topic dell'ultima edizione.",
    "peppy": "Come fai a non conoscerlo? peppy è a capo del [https://osu.ppy.sh/wiki/IT:The_Team team di osu!]",
    "perfect": "Non sei riuscito a prendere SS? Questa mod ti permette di rifare la mappa anche se prendi un singolo 100.\nPuoi trovare questa mod cliccando due volte su SuddenDeath.\n",
    "ping": "Pong!",
    "pippi": "La mascotte di osu! \nPippi-don è la versione taiko di Pippi.",
    "piracy": "Non chiedere o discutere materiale illegale/pirata nella chat!",
    "play-shortcuts": "Ecco una lista di scorciatoie che potrebbe farvi comodo: [[IT:Shortcut_Key_Reference]]",
    "pm": "Per mandare un PM a qualcuno, puoi usare il comando /msg [nomeutente] [messaggio] o /chat [nomeutente], che aprirà una scheda separata nella chat.\nPer rispondere velocemente all'ultimo PM ricevuto, puoi usare /r [messaggio]. Oh, e rimuovi le parentesi!",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "[https://osu.ppy.sh/wiki/IT:Performance_Points I Performance Points] (pp) sono il sistema metrico principale usato in osu! per il ranking.",
    "pp-rework-lazer": "",
    "preview": "Il preview point è il punto da cui parte una canzone quando viene scelta dalla schermata di selezione. Un preview point corretto è il punto che rappresenta meglio la canzone, come il ritornello. Vai nella toolbar su Timing > Set Current Position as Preview Point per sceglierne uno.",
    "qat": "",
    "qualified": "I Beatmap Nominator nominano le mappe che consdierano pronte per essere giocate ufficialmente come qualified.\nSe queste mappe non presentano problemi e rimangono qualified per una settimane, verrnno rankate, altrimenti torneranno in pending e i punteggi veranno cancellati.",
    "ranked": "Una mappa rankata è una mappa che è stata approvata dalla community di osu!. \nQuando giochi una mappa rankata, il punteggio ottenuto su di essa conterà sul tuo punteggio totale. \nQueste mappe hanno una propria classifica e sono identificate da una icona a forma di cuore.",
    "ranking-criteria": "Per informazioni sui ranking criteria, visita la Wiki: [[IT:RC]]",
    "redname": "Ti stai chiedendo perchè alcune persone hanno il nome in rosso? Tali utenti sono membri del [https://osu.ppy.sh/wiki/IT:GMT GMT] o del [https://osu.ppy.sh/wiki/IT;QAT QAT]",
    "report": "Utilizza il comando !report <utente> <motivo> per segnalare comportamenti inappropriati in chat o potenziali giocatori scorretti.\nPer favore evita di reportare in qualsiasi canale privato (PM). Puoi anche segnalare l'utente cliccando sul suo nome e poi selezionando Segnala Utente",
    "report-abuse": "Per favore, evita di mandare più volte lo stesso report: non ti aiuterà di certo a risolvere la questione più velocemente. \nNon fare mai dei report inutili o senza alcuna descrizione. Infatti, potresti venir silenziato a tua volta per aver abusato il comando.",
    "request": "Cerchi qualcosa da moddare? Clicca [https://osu.ppy.sh/p/beatmaplist&r=8 qui] o scrivi !request per ottenere un link casuale per una mappa.",
    "respect": "Per favore rispetta gli altri giocatori.",
    "roll-abuse": "Per favore non abusare il comando !roll - Potresti venir silenziato se non stai attento!",
    "romaji": "Per favore non usare eccessivamente Romaji (Romanized Japanese). Potresti essere messo a tacere.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Se non trovi nessuna stanza multiplayer di tuo gradimento perché non crearne una? Puoi anche scegliere le canzoni che ti piacciono.",
    "rp": "Sei libero di fare roleplaying nei canali di osu!, ma comunque assicurati che non dia fastidio alle altre persone nel canale.",
    "rules": "[https://osu.ppy.sh/wiki/it/Rules Regole Ufficiali]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "Può capitare ogni tanto che osu! venga colpito da un DDoS. Durante ciò, Bancho può essere instabile o può non funzionare come deve. Se pensi sia successo qualcosa, controlla [https://twitter.com/osustatus @osustatus] o [https://status.ppy.sh questo sito] per maggiori informazioni. Nel frattempo non ci far caso, portare avanti questo discorso non cambierà tanto le cose.",
    "sb": "[https://osu.ppy.sh/forum/t/1869 Qui] puoi trovare una guida in inglese su come creare una Storyboard.\nPer altre informazioni sull'editor delle SB, guarda [https://osu.ppy.sh/forum/t/8145 questo] topic.",
    "scorev2": "",
    "scoring": "Come osu! calcola lo score: [[Score#scoring]] (pagina in inglese)",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Un silence fa in modo che tu non possa parlare nella chat o postare qualsiasi cosa nel forum, tranne nella sezione Technical Support. \nI silence iniziano da 5 minuti per la prima infrazione, dopodichè la durata raddoppia per ogni infranzione fatta in seguito. Le infrazione più gravi però possono essere punite con un silence molto più lungo del doppio.\nI silence sono dati solo a chi infrange le regole, quindi seguile e non avrai problemi.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Informazioni sullo skinning]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Non giocare a osu! fino alle 4 di mattina, hai bisogno di dormire!]",
    "songs-not-appearing": "Se alcune delle tue mappe non compaiono nella schermata di selezione, prova a premere F5.",
    "spaces": "Per favore, non mettere spazi inutili dopo ogni lettera, rende la chat incasinata e può portare a un silence.",
    "spam": "Evita di spammare (scrivendo più righe quando non necessario) la chat, in quanto è un'azione che può essere punita con un silence. ",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Per spectare un altro player, scrivi /watch <utente>, o clicca sul loro nome nella chat o sul loro pannello utente e clicca su Start Spectating.\nRicordati che devi avere la stessa mappa di colui che stai spectando!\n",
    "spoiler": "Spoilerare un qualsiasi anime, manga, serie, doujin, ecc. e' proibito e puo' essere punito con un silence.",
    "status": "Per aggiornamenti sullo stato del server, fate riferimento a [http://twitter.com/osustatus @osustatus]. Per informazioni sullo stato dei server, controllate [https://status.ppy.sh qui].",
    "store": "[http://store.ppy.sh Benvenuto nell'osu! store], il luogo dove potrai comprare stupende t-shirt di osu! e altre cose interessanti!",
    "submit": "[https://osu.ppy.sh/wiki/IT:Submission Qui] troverai delle informazioni sul BSS (Beatmap Submission System, il sistema usato nell'upload di mappe).",
    "suck": "Non preoccuparti, migliorerai con la pratica.",
    "supporter": "Diventa un [https://osu.ppy.sh/p/support osu! supporter!] \nAvrai dei benefici extra ed aiuterai il team di sviluppatori a produrre di più!",
    "supporter-please": "Per favore non assillare la gente per ricevere il supporter. [https://osu.ppy.sh/p/support Prendilo tu stesso da qui!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Se il tuo cursore vola dappertutto quando provi a muoverlo, assicurati che la sensibilità del mouse nel gioco sia impostata a 1,00x. Puoi ridurre l'area attiva della tua tavoletta grafica per avere una sensibilità maggiore.\nSe il tuo cursore non si muove affatto, assicurati di disattivare il Raw Input dalle opzioni.\nPer ulteriori problemi relativi alle tavolette grafiche, [https://osu.ppy.sh/forum/t/87301 leggi questo tread (in inglese)]",
    "tag": "Nella modalità tag presente nel Multiplayer, tutti i giocatori devono giocare una combo a testa di una beatmap. Non ci sono né vincitori né vinti, siccome tutti giocano nello stesso team. Tutti i giocatori devono fare gli spinner, altrimenti la combo verrà resettata. Ogni bonus avuto dallo spinner verrà aggiunto al punteggio del team.",
    "taiko": "La modalità Taiko è basata sulla saga di giochi omonimi diffusi sia tramite cabinati sia su console fisse e portatili. Chi conosce il gioco non avrà alcun problema ad ambientarsi, per chi invece vuole dettagli su come giocare: i comandi predefiniti sono ZXCV (anch'essi riconfigurabili), due tasti associati ai don (i rossi) e altri due per  i kat (gli azzurri).",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Qui] ci sono informazioni sul Taiko mapping (in inglese)",
    "taiko-maps": "Puoi trovare le mappe autentiche della serie Taiko no Tatsujin [https://osu.ppy.sh/forum/t/5397 qui].",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Lascia stare questo argomento e parla di altro.",
    "training": "[https://osu.ppy.sh/forum/t/4280 James Training]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/33998 Lista dei tutorial in lingua italiana]",
    "twc": "Un torneo di Taiko a livello mondiale. [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ Qui] il topic dell'ultima edizione",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Per favore cerca di non utilizzare caratteri non-standard nelle chat pubbliche.",
    "upload-cap": "Per fare in modo che gli utenti si dedichino alle loro mappe già in corso, c'è un limite al numero di mappe inviabili al sito.\nGli slot disponibili sono da 3 a 6 per gli utenti normali e da 5 a 10 per i supporter. Ogni mappa rankata conferisce uno slot in più (per sbloccare tutti gli slot ci vogliono 5 mappe rankate)",
    "utf8": "Ricordati di usare UTF-8 e di impostare il tuo client IRC in questo modo per essere capito dagli altri giocatori di osu! e gli utenti su IRC.",
    "videogames": "Per favore, discuti di argomenti quali Touhou, Pokemon, SC, LoL, Visual Novels e altri videogiochi nel canale #videogames (in inglese).",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Benvenuto in osu! Non esitare a chiedere aiuto in chat se ti serve qualcosa. Buon divertimento!",
    "when": "Quando sarà pronto.",
    "wiki": "[https://osu.ppy.sh/Italiano/ osu! Wiki] - Se possibile prova ad aggiungere informazioni sulla wiki o a tradurre, per renderla il più completo possibile",
    "wiki-link": "Puoi linkare le pagine della wiki di osu! richiudendo il nome della pagina tra le seguenti parentesi: [[ ]]\nPer esempio, [[Kudosu]] può essere creato scrivendo Kudosu nel mezzo delle parentesi [[ ]]. \nAggiungi IT: davanti al nome dell'articolo per linkare alla versione italiana dell'articolo se presente (esempio [[IT:Kudosu]]",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 209 active FAQs (out of a possible 217) in the Italian (Italiano) language.",
    "completion": "The Italian (Italiano) FAQ as of last update is 96.31% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Il timer MP è stato impostato a 60 secondi!"
}
