
strings = {

    "academy": "osu!に関する全てのチュートリアルが盛り込まれているosu!academyを見るには[http://www.youtube.com/user/osuacademy こちらをクリック] ",
    "achievements": "特定のコンボ数を達成したり1つのテーマパックに含まれている全てのビートマップをプレイするなど特別なことを行うと実績を得られます。\nプロフィールでは、実績とその取得方法が確認できます。未取得の実績の名前は取得方法の重要なヒントになり得ます。",
    "add-skin": "[https://osu.ppy.sh/forum/t/3580 osu!にスキンを適用する方法]",
    "advertising": "osu!に関係のない宣伝内容は禁止されており、サイレンスとなる可能性があります。\nDiscordやTeamspeakなどの外部チャットサーバーもこれに含まれます。",
    "answer": "チャットで質問しても、必ず答えを知っている人がいるとは限りません。osu!関連の質問ならosu! forumsで検索してみましょう。",
    "appeal": "不当な理由でサイレンスや、不当な処置を受けたと思われる場合はaccounts@ppy.shにメールを説明文と共に送って下さい。",
    "approved": "Approvedビートマップは通常のRankedビートマップとは異なる条件を満たしてRanked状態になってます。Approvedビートマップは炎マークかチェックマークで表記されます。",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspireは枠にはまらない、自由な表現が出来るマッピングコンテストです。Aspire 2017は[http://osu.ppy.sh/news/156171674413 こちら]で詳細を確認できます。",
    "ask": "とりあえず質問してみましょう。",
    "attention": "迷惑ですので、やめてください。",
    "avatar-change": " [https://osu.ppy.sh/home/account/edit#avatar こちら]から、アバターを変更できます。",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "こんにちは！BanchoBotです。はじめまして。私は自動的に動作するBotなので、残念ながらあなたと会話はできません。",
    "beatmapping": "\n[https://osu.ppy.sh/wiki/Beatmapping ここ]ではビートマップに関して役立つヒントをいくつか紹介しています。",
    "beginner": "初心者用のビートマップを探すなら[https://osu.ppy.sh/forum/t/5456 こちら]をクリック。 ",
    "bn": "[[Beatmap Nomination Group]]は、公認ビートマップの管理を義務付けられているグループで、ビートマップのランキング入りについての議論や管理をしています。MappingやModdingに関する質問や要望がある人は連絡してみましょう。",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY 暇だ暇だと言っていても意味がありません。]休憩を取ったり、何か別のことに挑戦してみましょう。",
    "bug": "バグを発見したときは、[https://osu.ppy.sh/forum/5 こちら]に報告をお願いします。重複には気を付けましょう。",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "単語の頭文字すべてを大文字にすると見るに堪えない文章になるのでやめましょう。",
    "caps": "大文字の多用は見苦しいのでご遠慮願います。",
    "change-modes": "ゲームモードを変更するには曲の選択画面の左下の「Mode」ボタンを使うかCtrlキーを押しながら1-4キーで変更できます。ビートマップにはモードが指定されているものもあるので気をつけましょう。",
    "change-name": "ユーザネームを変更するにはまず[https://osu.ppy.sh/p/support osu! サポーター]でないと出来ません。それ以降は、[https://store.ppy.sh/store/product/32 ここ]で変えられます。細かい名前の変更や名前を元に戻したい場合はaccounts@ppy.shにお問い合わせ願います。",
    "changelog": "ゲーム、Banchoそしてウェブサイトの全てのアップデートは、osu!development　 [https://osu.ppy.sh/p/changelog 更新履歴]から見ることができます。",
    "chars": "ゲーム内チャットにおいて、unicode(UTF-8)や非標準文字を使うことは避けてください。",
    "charts": "osu! chartsは毎月リリースされているテーマ別のビートマップパックです。 [https://osu.ppy.sh/p/chart こちら]から見ることができます。",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "淡黄: 一般ユーザー、黄: [https://osu.ppy.sh/p/support osu!サポーター] | 赤: [https://osu.ppy.sh/wiki/NAT NAT] または [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]のメンバー、\n白: 自分、または /meメッセージ | 青: プライベートメッセージ | 緑: あなたが言及した部分 (ハイライト) | ピンク: BanchoBot",
    "colour": "淡黄: 一般ユーザー、黄: [https://osu.ppy.sh/p/support osu!サポーター] | 赤: [https://osu.ppy.sh/wiki/NAT NAT] または [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]のメンバー、\n白: 自分、または /meメッセージ | 青: プライベートメッセージ | 緑: あなたが言及した部分 (ハイライト) | ピンク: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "チャットコマンドは便利ですが、多用は禁物です。スパムと捉えられたり、サイレンスされることもありえます。",
    "comment": "リプレイ映像にライブコメントを書きたい時は、Discussion ボタンを押す事でニコニコ動画の様にコメントを書き込めます。スクリーン上にコメントが表示されていない場合はディスカッションパネルの、Show Commentsにチェックを入れてください。",
    "comment-color": "通常のユーザーは白でコメントが表示されます。  [https://osu.ppy.sh/p/support サポーター]であれば、コメントの色を選ぶことができます。",
    "conferencemode": "IRCが入室/退室の通知で見づらい場合は [http://wiki.xkcd.com/irc/Hide_join_part_messages こちら]が役立つかもしれません！ ",
    "country-ranking": "[https://osu.ppy.sh/p/countryranking 国別ランキング]はこちらから御覧ください。",
    "critic": "中傷的な批判は誰の為にもなりません。建設的にお願いします。",
    "ctb": "Catch the Beatに関する情報は[https://osu.ppy.sh/wiki/Catch_the_Beat こちらの]wiki pageを確認しましょう。",
    "cutting-edge": "Cutting-edgeは検証用のテストビルドです。",
    "cwc": "世界規模のosu! Catch the Beatトーナメント。詳しくは、[https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 wikiページ]を見てください。 ",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "自分がされたいと願うように、他の人たちにも接してください。",
    "disable-this": "設定の切り替えオプションなどは追加予定はほとんどありません。ただし、希望がある場合は、 [https://osu.ppy.sh/forum/4 今後の要望に関するサブフォーラム]からリクエストしてください。",
    "distance-snap": "Distance Snapは、タイムライン上の位置に基づいて、ノート間の相対距離を正しく維持させるツールです。詳しくは [[Distance_Snap]] をご覧ください。",
    "dont-ask-peppy": "peppyさんは忙しい人なのでそっとしてあげてください。",
    "douche": "包括的な安全装置として、ルールの中で、抜け道を使って、秩序を乱すようなことをした場合、管理チームの独断で処罰することができます。",
    "download": "[https://osu.ppy.sh/p/beatmaplist ここ]で好きなビートマップをダウンロードする事が出来ます。[https://osu.ppy.sh/beatmaps/packs ここ]でビートマップパッケージをダウンロードする事が出来ます。",
    "drugs": "薬物や薬物使用に関しての会話は禁止されています。",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "ショートカットのリストはこちら [[Beatmapping#Keyboard_Shortcuts]] で確認してください。",
    "english": "#englishは英語の雑談用のチャンネルです。",
    "evade": "サイレンスから逃れようと別のアカウントを作ったりすると、完全な禁止処罰とまではいかなくても、長い期間アカウントがブロックされることにもつながりますので、絶対にしないでください。",
    "fallback": "Stable(Fallback)は旧式のosu!クライアントバージョンです。DirectXに対応している最後のクライアントバージョンがFallbackです。よほど古いパソコンではない限りOpenGL対応のグラフィックドライバにアップグレードすることをお勧めします。それまではクライアントの更新などは受信できません。\n[https://osu.ppy.sh/wiki/GL_Support_Issues Click さらなる情報]",
    "faq": "今、あなたはosu!のBancho FAQシステムを利用しています。osu! wiki: https://osu.ppy.sh/wiki",
    "feature": "このゲームについて意見があれば、 [https://osu.ppy.sh/forum/4 今後の要望に関するサブフォーラム] から投稿してください。",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "チャットフィルタの回避はご遠慮ください。",
    "foul-play": "チート行為はそのユーザのプロフィールにある[https://i.imgur.com/GG9xlLA.png この]ボタンを使って報告してください。ビートマップスコアランキングの50位以内であればスコア別に報告できます。",
    "percolate": "チャットフィルタの回避はご遠慮ください。",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 こちらの記事]ではマッピングの流れを理解するのに役立つ情報を読むことができます。",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "ユーザーを友達として追加したい時は/addfriend ユーザ名 で、できます。また、(F9で表示)オンラインユーザーリスト上かチャット内でそのユーザーの名前をクリックして「フレンドに追加する」を選択する方法もあります。そのユーザのプロフィールページで Add as Friend も利用できます。",
    "friends-list": "ゲーム内でオンラインの友達はF9キーを押し、上部のフィルターをフレンドに切り替えると表示されます。フレンドすべてを表示したい場合はosu!ホームページでログイン後Settingsで見れます。",
    "fullscreen": "オプションメニューの「グラフィックス」で、ウィンドウモードか、フルスクリーンモードでプレイするかを選択することができます。\nキーボードのAlt + Enterキーを押すことでも、切り替えることができます。\n注意：フルスクリーンモードでは、 OpenGLが無効になります。",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "osu! [[glossary]]で、様々な専門用語を確認することができます。",
    "gmt": " [https://osu.ppy.sh/wiki/People/Global_Moderation_Team?locale=ja 国際管理チーム]、略して[https://osu.ppy.sh/wiki/People/Global_Moderation_Team?locale=ja GMT]は、osu!の運営を手伝うユーザーのグループです。彼らの名前は、チャット内では赤、フォーラムでは緑色で表示されます。彼らはフォーラムとチャットの管理を手伝っています。",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 読んで、学んで、楽しんで!]",
    "grammar": "丁寧な言葉遣いをこころがけましょう。対話するにおいて重要なスキルです。",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "遊び方がわからない？MappingやModdingの世界をもっと知りたい？[https://osu.ppy.sh/wiki/Guides こちらのページ] で全て確認できます。",
    "hacked": "もし自分が乗っ取りの被害に遭ったと思われる場合はaccounts@ppy.shに連絡をしましょう。報告が遅れた場合はアカウント停止処分になるおそれがあります。",
    "hard": "もっと上達してください。\n",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "osu!に関する質問があったら、#helpチャンネルで質問してみましょう。",
    "hitsound-library": "マップに使用するカスタムヒットサウンドを取得するには、[https://osu.ppy.sh/forum/p/164927 こちらのページ]へ。",
    "hl": "自分の名前によく使われる単語が入っていると、ハイライトの通知が多くなる場合がありますが、他の誰にも非はありません。設定で通知をオフにするなどの対処が可能です。",
    "how-to-get-modded": "自作のビートマップを見てもらう方法を知るには、こちらをクリック。 [[Getting_Your_Map_Modded]]",
    "how-to-bn": "BNになりたい方は、 [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator こちら]を読んでください。",
    "how-to-gmt": "モデレーターは、コミュニティにいつも貢献している人の中から選ばれます。どのチャンネルであっても、問題が起こった時は、!report コマンドで通知を送って対処しましょう。",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#how-to-play? 遊び方を知るにはこちらをクリック!]",
    "how-to-rank": "知りたい場合は、こちらを読んでください。[[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "赤く輝くフルーツを受け止めるとハイパーダッシュ状態になります。この状態の間は通常よりも速くダッシュすることができ、次のフルーツを受け取るかミスすると解除されます。",
    "ignore": "特定のプレイヤーからのメッセージを受け取り拒否したい場合や、そのプレイヤーのチャットを見たくない場合はチャットに/ignoreと打ちスペースの後にユーザ名を打ちましょう。同じく/unignoreで解除できます。",
    "import": "[http://i.imgur.com/kpX2N3m.jpg osu! にビートマップを読み込む方法についてはこれを読んでください。]",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "EditorウィンドウのF6ウィンドウで「過去のタイミング設定を引き継ぐ(Inherit previous timing settings)」ボックスにチェックを入れると、タイミング区間は以降タイミングに影響を与えません。音量やビートマップのサンプルのみを変更できる便利な項目です。また、2倍や0.5倍のBPMを持つタイミング区間を引き継ぐことも可能です。もしこのようなタイミング区間を使っているのであれば、この機能を使ってみてください。",
    "irc": "IRC サーバー: irc.ppy.sh:6667\nパスワード: https://osu.ppy.sh/p/irc\n詳細はhttps://osu.ppy.sh/wiki/IRCを読んでください。",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "オプション内でキーの配置など変更できます。osu!maniaのキー配置だけ「osu!maniaのレイアウト」ボタンから変更できます。",
    "kiai": "タイミング設定パネルで、Kiaiモードをタイミング区間に適用させると、スタイルエフェクトがかかります。\nタイミング区間にKiaiモードがオンになると、ビートマップをより「派手」なものにします。",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "他のユーザーのビートマップをModdingすることによって[https://osu.ppy.sh/wiki/Kudosu kudosu] ポイントを得ることができます。",
    "lag": "\nラグには[https://osu.ppy.sh/help/wiki/Performance_Troubleshooting いろんな]原因があり得ますが、大抵はパソコンの背景で動作しているプロセスが原因です。もしosu!独自のラグだと思われる場合、[https://osu.ppy.sh/forum/5 ヘルプフォーラム]に問題の詳細を詳しく書いて投稿するなどのご協力をお願いします。\n",
    "language": "チャットルームではマナーを守りましょう。",
    "language-specific": "チャットチャンネルにはそれぞれ専用の言語があります。専用の言語以外は使用しないでください。\nローマ字の使用も例外ではなく、禁止されています。",
    "lazer": "",
    "level": "あなたのレベルはあなたの通算スコアに基づいています。成功も失敗もどんなスコアも含みます。自然にosu!をプレイする事でレベルは上がっていきます。",
    "lines": "自動サイレンス回避のため、メッセージはなるべく行数を少なくしましょう。\n",
    "link": "何かにテキストリンクをつけたい時は、下記のフォーマットを使ってください。[URL テキスト]（スペースは半角）\n[https://osu.ppy.sh/ こんな感じ！] 「http://」 は忘れずに。",
    "lobby": "ロビーはマルチ関連のチャットです。通常の日本語での会話は #japanese チャンネルでお願い致します。",
    "localisation": "osu!翻訳プロジェクトは[https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 このページ]で確認。",
    "long-link": "長いリンクを送るのは極力避けましょう。[URL テキスト] で短縮できます。",
    "long-text": "必要以上に長いリンクやメッセージを送信するのは避けてください。",
    "loved": "「Loved」カテゴリのビートマップはランクドまで及ばなかったビートマップにランキングをつけられる様にしよう、と新しく作られたカテゴリです。[https://osu.ppy.sh/news/151925254083 詳細]",
    "mac": "[https://osx.ppy.sh Macでosu!を遊ぶ]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "ビートマップ作りは大変な作業です。自分で挑戦してみませんか？",
    "mapping": "Mappingガイドについては [https://osu.ppy.sh/forum/p/988111こちら] をご覧ください。",
    "mat": "\n\nMAT(Mapping Assistance Team)は、ランキング業務においてBATを支援していた古くからのユーザーのグループでしたが、2013年4月23日に休止しています。",
    "modhelp": "ビートマップのModdingに関するすべての問い合わせは、#mapping を使ってください。",
    "modqueue": "[https://osu.ppy.sh/forum/60 Moddingに関するお問い合わせ]",
    "modreqs": "Moddingのリクエストには、#modreqsを使ってください。ただし、BNは常に対応可能なわけではなく、順番に対応していますので、ビートマップのModしている一般のユーザーにも依頼するようにお願いいたします。",
    "multi-invite": "マルチプレイヤーゲームに他の人を招待したい時、チャットルームを開いたまま、オンラインユーザーリスト（F9を押す）上の招待したいユーザーをクリックするか、チャット内で名前をクリックしゲームに招待(Invite to game)を選択してください。\nまた、招待したいユーザー名に続けて/invite を打ち込む方法もあります。",
    "multi-link": "",
    "multiaccounting": "アカウントは一人につき１つのみ認められています。\n複数のアカウントを作ることは、絶対にしないでください。かなり長い期間のサイレンスか、停止処分となります。",
    "multiplayer": "マルチの宣伝や議論には#lobby を使用して下さい。",
    "mwc": "世界規模のosu! Mania大会。\n詳細は、 [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 こちら] からご確認ください。",
    "nat": "",
    "news": "",
    "nightcore": "お気に入りのビートマップをNightcoreスタイルで楽しめます！Double Time modを二度クリックするとNightcore modになります！スコアの倍率はダブルタイムと同じです。",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "/npでチャットに自分が選択中・プレイ中のビートマップを送信できます。",
    "nsfw": "不適切な表現を用いた会話はやめましょう。osu!は全年齢対象なので、公正なチャットを心がけてください。違反行為は警告無しにサイレンスされる可能性があります。",
    "osu": "#osu はosu!について語りあう所です。",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 osu!タブレット公式スレッド ] - タブレットや予約注文に関することは全てこちらでご確認ください。",
    "osu!talk": "osu!talkはdeadbeatとztrot主催のトークショーで、コミュニティ内のメンバーにインタビューしたり、ワールドカップなどのイベントについて話されています。各エピソードは、TeamSpeak 3サーバosu.corin.meで放送されます。Q＆Aセクションで質問をすることもできます。詳細については、 [ https://osu.ppy.sh/forum/t/225111 こちら]で確認してください。",
    "osucore": "2011年のエイプリルフールに、全てのmapにデフォルトでDoubleTimeがかかり、曲のピッチが高くなりました。この機能は、後にDoubleTimeと同じ効果を持つ、Nightcore modの始まりとなりました。",
    "osu!droid": "",
    "osumania": "osu!mania関連の話は、#osumaniaを使ってください。",
    "osustream": "[http://www.osustream.com osu!stream]はiOS端末用のosu!です。",
    "osz": "oszはosu!にビートマップをごく簡単に入れられる様に、開くだけでビートマップがosu!のライブラリに自動的に追加される便利な拡張子です。osu!以外のプログラムでoszを解凍すると問題が起きる可能性が高いので、やめておきましょう。",
    "osz2": "新しいビートマップのファイル形式「.osz2」は、暗号化、更新、ストリームを一つのファイルとして出来る様になったファイル形式です。「.osz2」は解凍する必要がなく、曲のフォルダーにそのままで使用可能です。",
    "owc": "世界規模のosu!トーナメントです。詳しくは[https://osu.ppy.sh/wiki/OWC wikiページ]をご覧ください。 ",
    "peppy": "peppyはosu!の開発者のリーダーであり、ほとんどのプロジェクトを自分で管理しています。",
    "perfect": "SSを執拗に狙っていきたい人はSudden DeathというModがオススメです。300以外の判定をとると自動的にビートマップの最初に戻ります。",
    "ping": "Pong!",
    "pippi": "Pippiはosu!のマスコットキャラクターです。Pippi-donは太鼓版のPippiです。",
    "piracy": "チャットで、著作権の侵害に関わる話はしないでください。そのような行為は禁止されており、あなたのアカウントのサイレンスにつながります。",
    "play-shortcuts": "ショートカットキーの全リスト:[[Shortcut_Key_Reference]]",
    "pm": "誰かと1:1でメッセージをやり取りしたい時は、チャット内で相手の名前をクリックするか、オンラインユーザー画面で相手のパネルをクリックし、そしてStart Chatをクリックしてください。\nもしくは、/msg <ユーザーネーム> や、 /chat <ユーザーネーム> 、 /query <ユーザーネーム>の形式でも可能で、それぞれ別のタブで開きます。\n最新の1:1のメッセージにすぐに返事したい時は、/r <message>の形式を使ってください。< >は除きましょう。\n",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "[https://osu.ppy.sh/wiki/Performance_Points Performance Points] (pp)はランキングの基準になるプレイヤーの実力の測定値です。",
    "pp-rework-lazer": "",
    "preview": "プレビューポイントとは、曲選択画面で流れる、その曲の一部分のことです。\nサビなど曲の代表的な部分が適切です。プレビューポイントを設定するにはツールバーのTimingで「現在の箇所をプレビューポイントとして設定(Set Current Position as Preview Point)」をクリックしてください。",
    "qat": "",
    "qualified": "QualifieビートマップはBeatmap Nominatorに認められた後の状態です。一週間の期間中にQATチームが問題を発見できなかった場合は、ビートマップはRanked認定され公式ビートマップになります。ランキングにスコアは残りますがPendingに戻ったりRankedになった場合は削除されます。",
    "ranked": "Rankedビートマップはオンラインコミュニティに承認されたビートマップです。このビートマップのスコアはあなたのトータルの累積スコアとして加算されます。これらのビートマップには独自のランキングがあり、ハートのアイコンで見分けることができます。",
    "ranking-criteria": "ランキングの判定基準についての情報は、wiki: [[RC]]で、確認してください。",
    "redname": "赤い名前のユーザーは、[https://osu.ppy.sh/wiki/People/Global_Moderation_Team?locale=ja GMT] または [https://osu.ppy.sh/wiki/People/The_Team/Nomination_Assessment_Team?locale=ja NAT]のメンバーです。",
    "report": "[https://osu.ppy.sh/forum/t/126811 Report機能の使い方]",
    "report-abuse": "連続でReportを送る必要はありません。悪質な場合はサイレンスの対象にもなります。",
    "request": "Modするビートマップを探している場合 [https://osu.ppy.sh/p/beatmaplist&r=8 こちら]で!requestと入力するとランダムにビートマップのリンクが開きます。",
    "respect": "他のプレイヤーには敬意を持って接してください。",
    "roll-abuse": "!rollの多用はサイレンスの対象になります。",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "もし遊べるマルチルームが見当たらないなら、自分で新しいルームを作ってみましょう。ルームを作成したホストは選曲もできます。",
    "rp": "ロールプレイは適切なosu!チャンネルでお願いします。",
    "rules": "[https://osu.ppy.sh/wiki/ja/Rules osu!のルール]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "時々、osu!はDDoS攻撃を受けることがあります。その間は、Banchoが不安定になったりダウンする事があります。\n[https://twitter.com/osustatus @osustatus] Twitterフィードや、 [https://status.ppy.sh ここ]で情報を確認できます。\nこのようなことが起こっても、チャットができているのであれば、通常通りプレイを続けてください。",
    "sb": "[[ストーリーボード]]\nストーリーボードについて: https://osu.ppy.sh/forum/t/1869\nストーリーボードEditorの使い方: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "scorev2はModやスピナー含む全モードのスコア上限が100万に設定されている新規格のスコア手法です。スライダーにも精度が適用されるようになっています。",
    "scoring": "osu!スコアの計算方: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "サイレンス状態とはプレイヤーがチャットでの発言やフォーラムでの投稿（Technical Supportを除く）などを禁止されている状態の事です。一回目のサイレンスは5分で、処罰を受ける度に期間は倍になっていきます。破ったルール次第で期間が異なる場合もあります。ルールを守っている健全なプレイヤーはサイレンス状態にされる事はありません。",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 スキンに関してのFAQ]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY 睡眠は大切です。osu!の遊びすぎで睡眠不足になる事は避けましょう。]",
    "songs-not-appearing": "もしあるはずのビートマップが見当たらない場合は、F5キーを押してライブラリを再読み込みしてみましょう。",
    "spaces": "文字の間にスペースを多用しないでください。",
    "spam": "短時間で大量のメッセージや長い文を送信するのは迷惑行為です。サイレンス処分になりますので、止めましょう。",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "他プレイヤーのプレイを観覧したい場合は、/watchの後にユーザ名を打つかユーザパネルをクリックして「Start Spectating」を押すかで観覧する事ができます。プレイヤーがプレイ中のビートマップを持っていないと観覧する事はできません。",
    "spoiler": "どんなアニメ、シリーズ、漫画、同人誌等についてもネタバレすることは禁止行為です。サイレンス対象になります。",
    "status": "osu!のシステム状態については [http://twitter.com/osustatus @osustatus] で確認できます。",
    "store": "[http://store.ppy.sh/ osu! storeへようこそ！]　こちらでosu!グッズをお買い求めいただけます！",
    "submit": "[https://osu.ppy.sh/wiki/Submission Beatmap FAQを投稿]",
    "suck": "osu!は難しく、奥の深いゲームです。根気よく練習して、上達を目指しましょう。",
    "supporter": " [https://osu.ppy.sh/p/support osu!のサポーター]になりましょう！多くの特典があります。そして開発チームがさらに良いものを作り出す支援にもなります！",
    "supporter-please": "サポータータグを他人にねだるのはやめましょう。[https://osu.ppy.sh/p/support ここでタグを入手しましょう]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "カーソル速度が速いと感じる場合は、ゲーム内のマウス感度を確認しましょう。タブレットは範囲を指定する事で感度を調節出来ます。\nカーソルが全く動かない時は、設定でRaw Inputをオフにしましょう。\nその他のタブレット関連の問題は、[ https://osu.ppy.sh/forum/t/87301こちら】をご覧ください。",
    "tag": "タッグモードでは、プレイヤーが順番に1人1コンボずつプレーします。勝者も敗者もなく、全ての人が同じチームとしてプレーします。\nですが、スピナーだけはすべてのプレイヤーが参加します。もし1人でもユーザーがスピンに失敗した場合、ミスと判定されます。各プレイヤーのスピンボーナスは、チームのスコアに追加されます。",
    "taiko": "太鼓の達人風のゲームモードです。",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/163327 太鼓マッピングガイド]",
    "taiko-maps": "太鼓の達人用の公式ビートマップは[https://osu.ppy.sh/forum/t/5397 こちら]です。",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "話題を変えましょう。",
    "training": "[https://osu.ppy.sh/forum/t/4280 ジェイムストレーニング]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 osu!とMappingに関する最新のチュートリアル動画リスト]はこちらです。ぜひ自分だけのMapを作成し、提出してみてください。[https://osu.ppy.sh/forum/t/60228 Mapperの方、Modderの方のためのお役立ちガイド]",
    "twc": "osu!taikoの公式世界大会の詳細は、[https://new.ppy.sh/wiki/Tournaments/TWC/2017/ wikiページ]をご覧ください。",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "チャット内では、Unicode (UTF-8)や非標準文字の使用を避けてください。サイレンス処分される場合があります。",
    "upload-cap": "アップロードできるビートマップの数には限りがあります。\nサポーターでない人は3～6個、サポーターの人は5～10個までで、持っているRankedビートマップ1個につき1つ上限があがります。\n墓地（Graveyard）入りしたビートマップは数に含まれません。",
    "utf8": "IRCクライアントのエンコード設定はUTF-8を使用してください。",
    "videogames": "他のゲームに関する話題は#videogamesでお願いします。",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "osu!へようこそ！もし質問や問題がある場合は、#helpチャンネルで訪ねてみましょう。",
    "when": "時は来る。",
    "wiki": "[https://osu.ppy.sh/wiki/ osu!のWikiページ] - さらに良いページにしていきましょう!",
    "wiki-link": "wikiページへのリンクを作るにはページの見出語を二重カッコでくくってください。 例：[[...]]\n例えば、[[Kudosu]] は、 [[ と ]‌]の間にKudosuを入れてリンクを作成します。",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 209 active FAQs (out of a possible 217) in the Japanese (日本語) language.",
    "completion": "The Japanese (日本語) FAQ as of last update is 96.31% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
