
strings = {
    "academy": "osu!에 관한 모든 튜토리얼 동영상이 담긴 osu! academy를 보고 싶다면 [https://www.youtube.com/user/osuacademy 여기를 눌러보세요]!",
    "achievements": "곡을 플레이하는 동안 특정한 동작을 취하거나 많은 콤보, 또는 테마 팩에 담겨있는 모든 비트맵을 플레이하는 것과 같은 특별한 조건을 충족시킨다면 업적을 달성할 수 있습니다. 프로필에서 어떤 업적을 달성했는지 볼 수 있으며, 무슨 업적이 있는지 확인할 수 있습니다. 몇몇 업적의 이름은 어떻게 그 업적을 달성할 수 있는지 알려주는 힌트가 됩니다.",
    "add-skin": "다운로드 한 스킨 파일이 .osk 파일이라면 osu! 윈도우에 드래그 하거나 더블클릭하여 추가할 수 있고, .rar/.zip 같은 파일의 경우 하나의 폴더에 압축을 풀어 Skins 폴더에 넣은 후 osu!를 재실행하세요.",
    "advertising": "osu! 와 관련이 없는 광고 콘텐츠는 허용되지 않으며, 제재를 당할 수 있습니다.\n디스코드와같이 서드파티가 제공하는 서버로의 초대 링크도 마찬가지로 제재를 당할 수 있습니다. ",
    "answer": "만약 아무도 질문에 대답하지 않는다면, 그건 아마도 사람들이 그 질문에 대한 해답을 모르는 걸 겁니다! 만약 오스와 관련된 것이라면 포럼에서 검색해보세요.",
    "appeal": "본인이 제재를 당했고 그 사유가 타당하지 않다고 생각한다면, accounts@ppy.sh 이메일 주소로 본인의 상황을 설명해주세요. 상황을 상세하게 설명해주시면 관리자들도 채팅 금지를 풀기 위해 최선을 다해 도와드릴 것입니다.",
    "approved": "Approved 비트맵은 몇몇 이유로 인해 랭크될 수 없으나, 사람들이 플레이할 만큼의 완성도는 가지고 있습니다. 랭크 맵의 하트 아이콘 대신 불꽃 아이콘이 표시됩니다.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "높은 수준을 자랑하는 매핑 대회 Aspire가 2017년, Helblinde의 곡으로 돌아왔습니다. 자세한 내용은 [http://osu.ppy.sh/news/156171674413 이곳을 확인하세요!]",
    "ask": "질문을 위한 질문을 하지 마시고 그냥 바로 물어보세요!",
    "attention": "아무도 관심이 없는것 같으니 그만해주세요.",
    "avatar-change": "아바타는 [https://osu.ppy.sh/home/account/edit#avatar 여기]에서 변경할 수 있습니다.",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "안녕! 난 BanchoBot이야! 만나서 반가워! 하지만 난 봇이라 대화는 할 수 없어 :(",
    "beatmapping": "[https://osu.ppy.sh/wiki/KO:Beatmapping beatmapping! 이곳]에서 매핑에 도움이 될만한 글을 확인해보세요! ",
    "beginner": "[https://osu.ppy.sh/forum/t/5456 이곳]에서 초보자를 위한 비트맵을 확인해보세요!",
    "bn": "[[Beatmap Nomination Group]]은 Pending된 비트맵을 책임지고 모딩하는, Ranked 비트맵을 관리하는 사람들입니다. 매핑이나 모딩에 도움이 필요하다면 이 사람들에게 질문할 수 있습니다.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY 인터넷 공간은 당신의 심심함, 지루함을 풀기에 충분히 넓습니다! 부디 게임을 켜두시고 심심하다 지루하다 하지 말아주세요. 아니면 잠깐 쉬다 오는게 어떨까요?]",
    "bug": "버그를 발견하셨다면 [https://osu.ppy.sh/forum/5 여기]로 신고해주세요. 아무도 올리지 않았다는 것을 먼저 확인한 후에 올려주시는 걸 잊지 말아주세요.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "영어로 채팅 할 때 모든 단어의 첫글자를 대문자로 쓰지 말아주세요. 열차 사고 같아 보이잖아요.",
    "caps": "모든 문자를 대문자로 쓰지 마세요. 채팅에선 이런 행위를 원하지 않으며, 심한 경우에는 채팅 제재를 당할 수도 있습니다.",
    "change-modes": "다른 게임 모드로 변경하려면 곡 선택 화면으로 가서 왼쪽 아래의 Mode를 클릭하시거나 Ctrl + 1~4를 사용하십시오. 몇몇 맵은 게임 모드가 고정되어 있습니다.",
    "change-name": "본인의 닉네임을 바꾸기 위해서는 먼저 [https://osu.ppy.sh/p/support 서포터]가 되어야 합니다. 그러면 [https://store.ppy.sh/store/product/32 이곳]에서 닉네임을 바꿀 수 있습니다.\n만약 예전의 닉네임으로 돌아가고 싶거나, 간단한 수정, 기타 닉네임에 관한 도움이 필요하시다면 accounts@ppy.sh로 연락해주세요.",
    "changelog": "게임에 대한 모든 업데이트는 Bancho 및 웹사이트의 osu!development [https://osu.ppy.sh/p/changelog 체인지 로그]에서 확인할 수 있습니다.",
    "chars": "게임 내 채팅에서 유니코드/비표준 문자의 사용을 피하세요.",
    "charts": "osu! 차트는 매달 특정 테마의 비트맵 팩을 선보이고 있습니다.  [https://osu.ppy.sh/p/chart 이곳]을 클릭하여 다양한 차트를 지금 바로 만나보세요!",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "연노랑: 일반 유저 | 노랑: [https://osu.ppy.sh/p/support 서포터] | 빨강: [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team NAT] 혹은 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\n흰색: 자기 자신, 혹은 /me 메세지 | 진한 파랑: 개인 메세지 | 초록: 자신의 닉네임이 거론된 채팅 (하이라이트) | 분홍: BanchoBot",
    "colour": "연노랑: 일반 유저 | 노랑: [https://osu.ppy.sh/p/support 서포터] | 빨강: [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team NAT] 혹은 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\n흰색: 자기 자신, 혹은 /me 메세지 | 진한 파랑: 개인 메세지 | 초록: 자신의 닉네임이 거론된 채팅 (하이라이트) | 분홍: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "채팅 명령어는 편하고 좋지만, 너무 과도하게 사용하진 말아주세요. 스팸으로 판단되어 채팅 제재를 받을 수 있습니다.",
    "comment": "리플레이 영상에 라이브 코멘트를 남기시려면, Discussion 버튼을 눌러 코멘트를 작성하세요.\n코멘트가 안 보인다면, Discussion 패널에서 맨 밑의 Show Comments 박스를 체크하세요.",
    "comment-color": "일반 유저는 오직 하얀색 글자만 적을 수 있습니다. [https://osu.ppy.sh/p/support 서포터]는 코멘트의 색상을 마음대로 지정할 수 있습니다.",
    "conferencemode": "IRC에서 입장/나가기 메세지가 쏟아진다구요? [http://wiki.xkcd.com/irc/Hide_join_part_messages 여기]에서 도움을 줄것입니다!",
    "country-ranking": "[https://osu.ppy.sh/p/countryranking 여기]에서 다양한 국가별 랭킹을 확인할 수 있습니다.",
    "critic": "맹목적인 비난을 하지 마시고, 문제 해결을 위한 방법이나 대안을 제시합시다.",
    "ctb": "캐치 더 비트와 관련된 도움이 필요하신가요? [https://osu.ppy.sh/wiki/Catch_the_Beat 위키 페이지]를 확인해보세요!",
    "cutting-edge": "Cutting-edge는 osu!의 새로운 기능을 시험하는 시험적 빌드입니다. 설정에서 바꾸실 수 있습니다. 클라이언트 업데이트에 문제가 생겼다면 [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues 여기]를 확인하세요.",
    "cwc": "전세계 osu! 캐치 더 비트 토너먼트입니다!  [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 여기]에서 더 많은 정보를 확인하세요!",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "좋은 대우를 받고 싶으면 타인에게도 좋게 대하세요. 상대를 욕하는 것이 즐겁다고, 당하는 사람도 즐거운 건 아닙니다.",
    "disable-this": "요청 사항이 있다면, [https://osu.ppy.sh/forum/4 기능 요청 서브포럼]에서 요청하세요.",
    "distance-snap": "거리 비례 스냅은 거리를 일정하게 유지시켜주는 도구로, 타임라인 위치에 따라 거리가 달라집니다. 자세한 사항은 [[Distance_Snap 여기]]를 클릭하세요.",
    "dont-ask-peppy": "peppy는 오는 질문을 전부 답해줄 정도로 여유 있는 사람이 아닙니다. 대신 다른 사람들에게 질문해보세요!",
    "douche": "보호 활동이 뜸할 때, 질서와 예의를 회피하는 일은 규칙에 허점을 내며 이는 관리 팀의 판단 재량에 따라 처벌받을 수 있습니다. 공식 규칙은 당신이 얼간이가 되어서도 안되고, 얼간이가 될 필요가 없다고 알립니다. 결론은, 얼간이가 되지 맙시다.",
    "download": "비트맵은 [https://osu.ppy.sh/p/beatmaplist 이곳]이나 [https://osu.ppy.sh/beatmaps/packs 이곳]에서 다운로드 받을 수 있습니다. 비트맵을 불러오는 방법은 [http://i.imgur.com/kpX2N3m.jpg 이 이미지]를 보시면 알 수 있습니다.",
    "drugs": "이 게임은 전체 이용가 게임이므로 마약과 관련된 채팅은 금지되어 있습니다.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "[[Beatmapping#Keyboard_Shortcuts 단축키]]를 눌러 에디터에서 쓸 수 있는 단축키 리스트를 볼 수 있습니다.",
    "english": "#english 는 모든 주제를 다루는 일반 대화 채널입니다.\n네, 그 주제 안에는 애니/만화도 포함되어 있지요.",
    "evade": "채팅이 금지되었다고 해서 다른 아이디로 접속하면 계정이 제한될 수 있습니다. 장기간 동안 계정이 정지되므로 절대로 하지 마세요.",
    "fallback": "정식 버전(Fallback)은 오래된 버전의 오스 클라이언트입니다. 새로운 버전에서는 프레임워크의 최적화를 위해 DirectX를 지원하지 않으므로, 당신의 컴퓨터가 새로운 기능을 지원하지 않는다면 이 빌드로 변경하세요.\n만약 최신 버전으로 플레이하고 싶다면, OpenGL이 정상적으로 지원되는 그래픽카드로 바꾸세요. [https://osu.ppy.sh/wiki/GL_Support_Issues 자세한 내용은 이곳을 클릭하여 확인할 수 있습니다].",
    "faq": "현재 osu!Bancho FAQ 시스템을 사용중입니다.\nosu! 위키: https://osu.ppy.sh/wiki",
    "feature": "만약 이 게임에 대해 좋은 아이디어가 떠오른다면, [https://osu.ppy.sh/forum/4 기능 요청] 항목에 글을 써보세요.\n반드시 [https://osu.ppy.sh/forum/t/454006 포럼 가이드라인]을 먼저 읽고 작성하도록 합시다.",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "채팅 필터를 회피하려는 행동은 채팅 제한으로 이어질수 있습니다.",
    "foul-play": "핵 사용자를 발견했을 때에는 [https://i.imgur.com/GG9xlLA.png 프로필에 있는 신고 버튼]을 눌러 신고하세요.\n확실한 증거가 필요하므로 사유를 자세하게 적어서 신고해주세요. 비트맵 페이지의 순위표에서도 신고가 가능합니다.\n공용 채널에서는 밴이나 핵에 관한 이야기는 자제해주시기 바랍니다.\n",
    "percolate": "채팅 필터를 회피하려는 행동은 채팅 제한으로 이어질수 있습니다.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 여기]를 눌러 매핑의 흐름을 이해하는데 도움을 받을 수 있습니다.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "상대방의 닉네임을 채팅 창에서 클릭하거나 F9에서 검색하여 누른 후 친구 추가를 누르시면\n친구 목록에 추가됩니다. /addfriend 닉네임으로도 가능합니다.",
    "friends-list": "게임 내에서 접속한 친구의 목록을 보시려면 F9를 누른 후 상단의 필터를 친구들로 바꿔주세요. 홈페이지에서 보시려면 로그인 후 설정을 누르시면 됩니다.",
    "fullscreen": "설정의 '그래픽' 항목에서 창 모드나 전체화면 모드를 선택할 수 있습니다.\n혹은 키보드의 Alt+Enter를 눌러 간편하게 전환할 수도 있습니다.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "osu! [[glossary]]에서 osu!의 많은 용어들을 찾을 수 있습니다.",
    "gmt": "[https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team], 줄여서 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]는 osu!의 원활한 운영을 돕습니다. 게임 내에서 빨간색으로, 포럼에선 초록색 이름을 갖습니다. 게임 내에서의 채팅과 포럼 등의 관리를 맡습니다.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 읽고, 고치고, 기뻐하세요.]",
    "grammar": "좋은 문법을 사용하기 위해 최선을 다하세요. 철자 또는 문장 부호의 실수는 용인될 수 있지만 줄임말과 통신체의 사용을 자제해주세요. ",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "어떻게 해야할지 막막하세요? 매핑과 모딩의 세계를 알아보고 싶나요?  [https://osu.ppy.sh/wiki/Guides 여기]에서 모든 답을 얻을 수 있습니다.",
    "hacked": "본인의 아이디가 해킹되었다고 생각하시면 accounts@ppy.sh로 예전 이메일 주소, 닉네임, 마지막 접속날짜, 해킹 발견한 날짜를 써서 문의바랍니다. 어필에 실패했을 경우 계정이 삭제될 수 있습니다.",
    "hard": "잘 좀 해봐요!",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "osu!와 관련된 질문이 있다면, #help 채널에서 물어보세요. #help 채널에서는 여러 언어를 사용할 수 있습니다.\n아무도 대답하지 않는다면, [https://osu.ppy.sh/forum/5 Help] 포럼을 이용하는 방법도 있습니다.\n또한 [http://help.ppy.sh/ 이 페이지]에서 계정 관련 문제를 포함한 다른 정보를 얻을수도 있습니다.",
    "hitsound-library": "[https://osu.ppy.sh/forum/p/164927 여기]에서 맵에 사용할 커스텀 히트사운드들을 얻으세요.",
    "hl": "자꾸 호출된다고 다른 이들에게 불만을 표하진 마세요. 쓸데없이 호출하는 것도 잘못입니다만, 본인이 선택한 닉네임에, 하이라이트 문구도 본인이 선택해서 등록하셨을 겁니다. 호출이 거슬린다면 알림을 끄는 방법도 있습니다.",
    "how-to-get-modded": "만약 당신의 맵이 채택되는 방법을 알고 싶다면, [[Getting_Your_Map_Modded]]을 알아보세요.",
    "how-to-bn": "만약 BN이 되고 싶다면, [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator 이 글]을 읽어보세요.",
    "how-to-gmt": "모더레이터는 커뮤니티에 기여를 한 정도를 보고 선택됩니다. 어느 채널이든 중재가 필요하거나 문제가 발생하였다면 !report 명령어로 보고해주세요!\n자세한 내용은 [https://osu.ppy.sh/wiki/en/People/The_Team/Global_Moderation_Team Global Moderation Team] 위키 페이지를 참조하세요.",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#how-to-play? 링크를 클릭해서 플레이 방법을 알아보세요!]",
    "how-to-rank": "확인하려면, [[How_to_Get_Your_Map_Ranked]]을 읽어보세요.",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "하이퍼대시는 캐치 더 비트를 할때, 빨간 빛의 과일을 받으면 발생합니다. 평소보다 빠르게 대시할 수 있으며, 다음 과일을 받거나 미스가 나기 전까지 유지됩니다.",
    "ignore": "특정 사용자의 채팅을 무시하기 위해서는 /ignore 닉네임 명령어를 사용하세요 이는 해당 유저와의 1:1채팅도 해당되며, 해제는 /unignore <닉네임>으로 가능합니다.",
    "import": "[http://i.imgur.com/kpX2N3m.jpg osu!로 비트맵을 불러오는 방법]",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "\n에디터 창에서 초록 이전 타이밍 섹션 박스에 체크했다면, 타이밍 구간은 더 이상 타이밍에 영향을 주지 않습니다. 어느 섹션들은 오직 볼륨 변경이나 맵 샘플에만 유용합니다.\n또한, 초록 타이밍 구간들이 2배, 0.5배 BPM을 가지는 것이 가능합니다. 이같은 타이밍 구간을 찾게 된다면, 한번 이 기능을 사용해보세요.",
    "irc": "IRC 서버: irc.ppy.sh:6667\n비밀번호: https://osu.ppy.sh/p/irc\n자세한 사항은 https://osu.ppy.sh/wiki/IRC 를 참조하세요.                                         ",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "옵션에서 키보드의 설정을 변경할 수 있습니다. osu!mania 모드의 키와 레이아웃을 변경하시려면 osu!mania 키 배치 버튼을 클릭하세요.",
    "kiai": "Kiai 모드는 타이밍 섹션에 적용시 이펙트를 보여줍니다. 타이밍 구간에 Kiai 모드가 켜지면, Kiai 효과는 비트맵을 좀 더 화려하게 보여줍니다.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "다른 사람들의 비트맵을 모딩해서 [https://osu.ppy.sh/wiki/KO:Kudosu Kudosu]를 얻으세요.",
    "lag": "[https://osu.ppy.sh/help/wiki/Performance_Troubleshooting 어떠한 것이든] 렉의 이유가 됩니다. 대부분은 컴퓨터의 다른 프로세스들 때문입니다. 그것들 때문이 아니라면, osu! 때문이겠죠. 만약 렉이 osu! 자체의 문제라고 여겨지신다면, 문제 해결에 도움이 될만한 무엇이든 적어 [https://osu.ppy.sh/forum/5 기술 지원 포럼]에 지원 요청을 해주세요.",
    "language": "채팅을 할 때 서로 예의를 지켜주세요. 부적절한 용어 사용으로 채팅 제한이 될 수 있습니다.",
    "language-specific": "해당 채널에 맞는 언어를 사용해 주세요.",
    "lazer": "",
    "level": "레벨은 당신의 총계 점수를 기준으로 합니다. 모든 랭크 스코어, 성공 혹은 실패를 포함합니다. osu!를 플레이하면서 점점 레벨이 상승할 것입니다.",
    "lines": "도배와 단타 채팅은 빈도에 따라 채팅 제한에 걸릴 수 있으니, 한번 엔터키를 칠 때마다 한 문장씩 쓴다는 생각으로 채팅해주세요.",
    "link": "텍스트에 링크를 포함하고 싶다면, 다음 형식을 사용해보세요: [링크 텍스트]\n'링크'는 클릭시 이동할 URL이며, '텍스트'는 보여지는 텍스트를 뜻합니다. [https://osu.ppy.sh/ 이것처럼요!] http://를 포함하는것을 잊지 마세요.",
    "lobby": "#lobby 는 오직 멀티플레이어 방 홍보를 위한 곳입니다. 또한, #lobby 는 사용 언어 제한이 없습니다. 한국어를 쓰셔도 되지만,\n일반적인 채팅은 #korean 이나 #multiplayer 을 이용해 주시기 바랍니다.",
    "localisation": "[https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 osu! 현지화 프로젝트]를 도와주세요!",
    "long-link": "채팅 창에 너무 긴 링크을 붙여넣지 말아주세요. 꼭 필요하다면 [link text] 수식어를 사용해주세요.",
    "long-text": "채팅 창에 너무 긴 문장을 붙여넣지 말아주세요. 채팅 제한이 될 수도 있습니다.",
    "loved": "Loved 카테고리는 보통이라면 랭크될수 없는 맵에 스코어보드를 추가하는, 커뮤니티 기반의 랭크 상태입니다. [https://osu.ppy.sh/news/151925254083 자세한 사항은 이곳을 참조하세요! ]",
    "mac": "[https://osx.ppy.sh Mac에서 osu!를 플레이하세요.]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "매퍼들은 바쁜 사람들입니다, 매핑은 정말 많은 작업을 해야합니다. 스스로 매핑 해보는 것은 어떨까요?",
    "mapping": "[https://osu.ppy.sh/forum/p/988111 여기]를 눌러 매핑 가이드를 확인해보세요.",
    "mat": "BAT를 도와 비트맵 랭크를 보조했던 그룹인 Mapping Assistance Team은 2013년 4월 23일부로 폐지되었습니다.",
    "modhelp": "맵 모딩에 관한 요청 사항은 #mapping 를 이용해주세요.",
    "modqueue": "[https://osu.ppy.sh/forum/60 모딩 대기열]은 여기입니다.",
    "modreqs": "모딩 요청들은 #modreqs 채널에서 해주세요. BN들은 언제나 여유롭지 않고, 먼저 다른 사람들이 요청한 것을 먼저 진행할 수도 있습니다, 그러니 비트맵을 모드하는 일반 유저들에게도 모딩 요청을 해보세요.\n요청을 하실때는 /np 명령어를 사용하거나 [link text] 형식을 사용하시면 됩니다. 감사 인사도 잊지 마시고요.",
    "multi-invite": "멀티플레이에서 자신의 방에 상대를 초대하려면 F9를 누르고 상대의 닉네임을 누른뒤에 게임 초대를 누르세요.\n/invite 닉네임 명령어로도 초대가 가능합니다.",
    "multi-link": "",
    "multiaccounting": "당신은 정말, 정말로 다중 계정을 만들면 안됩니다. 이는 반드시 적발될 것이며, 아주 긴 기간동안 채팅 제한이 되거나, 차단될 수도 있습니다!",
    "multiplayer": "#lobby 이외의 다른 채널에서 멀티플레이어 방을 홍보하지 말아주세요.",
    "mwc": "전세계 osu!mania 대회. [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 위키 페이지]에서 더 많은 정보를 확인하세요.",
    "nat": "",
    "news": "",
    "nightcore": "좋아하는 비트맵을 나이트코어 스타일로 즐겨보세요! 더블타임 모드를 건 상태로 한번 더 클릭하면 나이트코어 모드가 출현합니다! 점수 배수는 더블타임과 동일합니다.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "/np를 입력하면 현재 osu!에서 플레이 중인 음악이 다른 사람들에게 보여집니다.",
    "nsfw": "이곳은 여러 연령층이 대화하는 곳으로 미성년자들도 많습니다.\n성적인 단어의 사용이나 장난은 자제해주세요. 예고 없이 채팅이 제한될 수 있습니다.",
    "osu": "#osu 는 osu!에 대해 이야기 하는 곳입니다. #osu 채널에서 게임플레이 관련 대화를 나눠주세요.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 osu!tablet 공식 스레드]에서 타블렛과 예약 주문에 대한 모든 정보를 확인하세요.",
    "osu!talk": "osu!talk는 deadbeat와 ztrot가 커뮤니티 인원을 인터뷰하거나 월드 컵 같은 이벤트를 논의하는 토크쇼입니다. 각 에피소드는 [https://discord.gg/014x1ACj2VdUPLU5x Discord 서버]에서 서비스됩니다.\nQ&A 섹션에서 질문을 하실 수도 있습니다. 자세한 정보는 [https://osu.ppy.sh/forum/t/225111 여기]서 확인하세요.",
    "osucore": "2011년 만우절 특전! 모든 맵들이 모두 더블타임이 걸렸으며, 곡의 피치가 높아졌습니다.\n이 기능은 후에 나이트코어 모드의 효시가 되었습니다.",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] 는 Android 플랫폼에 맞게 이식된 osu! 입니다. 개발 부재와 공식 개발자의 의도, 나쁜 리뷰로 인해 2016년부터 Google Play Store에서 내려갔습니다.",
    "osumania": "osu!mania에 관한 채팅은 #osumania 채널에서 하세요.",
    "osustream": "[http://www.osustream.com osu!stream]은 iOS 기기를 위한 osu!입니다. peppy가 만들고 관리하고 있습니다!",
    "osz": "비트맵 파일 포맷 .osz 파일은 osu!가 자동으로 압축을 풀게 해야 합니다. 그 외 방법으로 시도시 오류가 발생할 수 있습니다!",
    "osz2": "새로운 비트맵 파일 포맷인 .osz2는 암호화가 가능해졌으며, 업데이트와 스트림을 다른 파일로 관리하는 것이 가능해졌습니다. osz2는 압축을 풀 필요가 없어졌으며, 곡 폴더에 늘 남아있게 됩니다.",
    "owc": "전세계 osu! 대회, OWC에 대해 알고 싶다면 [https://osu.ppy.sh/wiki/OWC 위키 페이지]를 참조하세요.",
    "peppy": "peppy는 osu!의 개발 리드와 많은 프로젝트들을 스스로 담당하고 있습니다.",
    "perfect": "SS를 받기 힘드나요? 퍼펙트 모드는 노트 정확도가 100%로 유지될 때 계속 진행되는 모드이며, 실수를 하게 된다면 자동으로 재시작하게 됩니다.\n서든데스 모드를 더블 클릭 하시면 퍼펙트 모드가 나옵니다.",
    "ping": "Pong!",
    "pippi": "osu!의 마스코트 캐릭터입니다! Pippi-don 은 Pippi의 태고(드럼) 버전입니다.",
    "piracy": "저작권이 있는 콘텐츠 도용에 대해 공개 채널에서 논의하지 마세요.\n그것에 대해 대화하는것은 금지되어 있으며, 채팅금지를 당하실 수 있습니다.",
    "play-shortcuts": "단축키의 전체 항목: [[Shortcut_Key_Reference]]",
    "pm": "1:1 채팅을 위해서는 해당 유저(온라인 상태)의 닉네임을 클릭하여 나오는 항목 중 'Start Chat' 을 클릭합니다.\n또는 /msg <닉네임> <메시지> , /chat <닉네임> , /query <닉네임> 의 형식을 쓰셔도 됩니다.\n최근 받은 1:1챗에 관해 답하기 위해서는 /r <메시지> 를 쓰셔도 됩니다. 괄호는 안써도 되는거 아시죠?",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "퍼포먼스 점수(pp)는 osu!의 주 랭킹 측정 요소입니다. [https://osu.ppy.sh/wiki/Performance_Points 여기]를 눌러 자세히 알아보세요.",
    "pp-rework-lazer": "",
    "preview": "프리뷰 포인트는 곡 선택 화면에서 들려주는 음악의 시작 부분입니다. 후렴구의 시작과 같은 적절한 프리뷰 포인트는 곡을 잘 표현해줍니다. 상단 툴바의 타이밍에서 현재 지점을 프리뷰 포인트 설정을 눌러 설정할 수 있습니다. ",
    "qat": "Quality Assurance Team, 줄여서 QAT은 최근에 퀄리파이 된 맵이 플레이의 가능 여부와 퀄리티를 확인합니다.\n랭킹 시스템에 큰 변화가 생긴 2019년 4월 이후, 작업하는 영역을 잘 표현하기 위해 Nomination Assessment Team으로 변경되었습니다.",
    "qualified": "비트맵 노미네이터들이 랭크되기에 적합하다고 판단하면 Qualifed 상태가 됩니다. 그 동안은 랭킹 등록이 가능하지만, 퍼포먼스 포인트를 획득할 수 없습니다.\n만약 1주일간 맵에 아무런 문제가 없다면, Ranked 상태로 전환됩니다. 또한 Pending 상태로 돌아갈 수 있으며, 상태가 변하면 스코어가 제거됩니다.",
    "ranked": "Ranked 비트맵은 온라인 커뮤니티에 의해 승인된 것입니다. 만약 랭크된 맵을 플레이하면, 곡의 점수가 최종 합계 점수에 누적됩니다. 이 맵들은 순위표를 가지고 있으며, 하트 아이콘으로 구분할 수 있습니다.",
    "ranking-criteria": "랭킹 기준 정보는 [https://osu.ppy.sh/wiki/Ranking_Criteria 여기]를 참고해주세요,",
    "redname": "빨간색 닉네임은 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team] 혹은 [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] 입니다.",
    "report": "부적절한 행동 및 부정행위를 하는 유저를 신고하기 위해서는 다음과 같이 입력하세요: !report <유저이름> <사유>\n신고 명령어는 다른 유저에게는 보이지 않으므로 PM 내에서 할 필요 없이 공용채널에서 하면됩니다.\n또한 유저를 클릭하여 신고...버튼을 누르는 것으로도 신고가 가능합니다.",
    "report-abuse": "연속으로 신고를 보내지 마세요. 빠른 처리에 도움이 안됩니다. 텅 비거나 불합리적인 신고도 안됩니다.\n위와 같은 행위는 스팸 채팅 관리자의 눈에 띄어 오히려 신고자가 채팅이 차단될 수도 있습니다.",
    "request": "모드할 맵이 필요한가요? [https://osu.ppy.sh/p/beatmaplist&r=8 여기]나 !request 를 입력하여 임의의 맵 링크를 열 수 있습니다.",
    "respect": "다른 유저를 존중해주세요.",
    "roll-abuse": "과도한 !roll 명령어 사용은 자제해주세요. 채팅이 제한될 수 있습니다.",
    "romaji": "일본어 로마자 표기법을 과도하게 사용하지 마세요. 채팅이 제한될 수 있습니다.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "멀티플레이에 들어갈 방이 없다면, 직접 만들어보세요. 곡도 직접 고를 수 있습니다!",
    "rp": "해당되는 osu! 채널에서 역할극을 마음껏 할 수는 있습니다. \n하지만, 다른 사람들을 너무 귀찮게 하진 마세요.",
    "rules": "[https://osu.ppy.sh/wiki/ko/Rules 공식 규칙]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "때때로, osu!가 DDoS 공격을 받을 때가 있습니다. 그러면 Bancho는 불안정해지거나 다운될 수도 있습니다.\n만약 이런 일이 발견되었다면, [https://twitter.com/osustatus @osustatus] 트위터 채널을 확인하거나 [https://status.ppy.sh osu!stat]에서 서버 상태를 확인하세요.\n위와 같은 상황이 발생해도, 계속 채팅을 할수 있다면 - 평상시처럼 플레이하세요. 서버 다운에 대한 주제 언급은 복구 속도를 빠르게 해주진 않습니다.",
    "sb": "[[Storyboarding]]\n스토리보드 가이드: https://osu.ppy.sh/forum/t/1869\n스토리보드 편집기를 사용하는 방법: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "scorev2는 모든 게임모드에서 적용가능한, 스피너와 모드를 제외하고 100만점으로 상한이 정해져있는 새로운 스코어 방식입니다.\r\n또한 슬라이더의 동작을 바꾸어 서클을 치는것과 동일한 타이밍이 필요하도록 합니다.",
    "scoring": "osu!가 점수를 계산하는 방법: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "채팅 제한이 되면 기술 지원 포럼을 제외한 채팅 방이나 포럼에 글을 작성할 수 없습니다.\n첫 위반인 경우 5분이며, 다음 위반 사항마다 두 배씩 늘어납니다. 주요 위반 사항인 경우 차단 시간이 두 배보다 더 길어질 수 있습니다.\n채팅 차단은 가벼운 조치이며, 앞으로 규칙을 지킨다면 괜찮을 것입니다.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 스킨 제작 FAQ]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY 오전 네 시가 넘도록 osu!를 하진 마세요. 얼른 주무세요! 잠은 중요합니다!]",
    "songs-not-appearing": "곡이 곡 선택 화면에 없다면, F5를 눌러보세요.",
    "spaces": "모든 문자 사이마다 공백을 넣지 마세요. 당신의 미학이 채팅을 더럽게 만들 수 있고, 채팅이 제한될 수 있습니다.",
    "spam": "도배나 의미 없는 말의 나열은 채팅 제한의 원인이 될 수 있으니 삼가주세요.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "특정 플레이어 관전을 하려면 채팅 창의 닉네임을 클릭하거나, /watch <닉네임> 명령어를 사용하거나, F9의 유저 패널을 선택하여 관전 시작을 누르세요. 플레이어가 플레이하고 있는 똑같은 곡이 필요합니다.",
    "spoiler": "어떠한 애니메이션, 시리즈, 만화, 동인지 등에 대해 쓰거나 묘사하는 것은 금지되며 이를 강행할 경우 사일런스 제재 혹은 밴에 해당하는 제재를 받을 수 있습니다.",
    "status": "osu!의 시스템 상태 업데이트는 트위터 [http://twitter.com/osustatus @osustatus]를 참고하세요. 서버 상태 정보는 [https://status.ppy.sh 이곳]을 참고해주세요.",
    "store": "[https://osu.ppy.sh/p/market osu! market]에서 멋진 osu! 티셔츠와 멋진 것들을 구매할 수 있습니다!",
    "submit": "[https://osu.ppy.sh/wiki/Submission 비트맵 제출 FAQ]",
    "suck": "실력 향상에 좋은 방법은 꾸준한 연습입니다.",
    "supporter": "[https://osu.ppy.sh/p/support osu! 서포터]가 되세요! 개발팀이 개발을 할 수 있는 원동력이 되며, 서포터에게는 몇몇 특별한 혜택이 주어집니다.",
    "supporter-please": "다른 사람에게 서포터를 선물해달라고 하지 말고 [https://osu.ppy.sh/p/support 이곳에서 직접 구입하세요!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "만약 커서가 사방천지를 날아다녀 조절하기 힘들다면, 게임 내 마우스 감도를 1.00x로 설정해보세요. 타블렛을 작게 쓴다면 감도가 높아집니다. 만약 커서가 움직이지 않는다면, 설정에서 직접 입력을 꺼보세요. 다른 타블렛 관련 문제는 [https://osu.ppy.sh/forum/t/87301 여기]를 참조하세요.",
    "tag": "태그 멀티플레이어 모드에서는, 모든 플레이어가 돌아가며 비트맵에서 1콤보씩 클릭하게 됩니다. 승자도, 패자도 없으며 모든 사람이 같은 팀으로 플레이하게 됩니다. 스피너는 모든 플레이어가 돌려야 합니다. 만약 한 유저가 스핀에 실패한다면, 콤보는 초기화됩니다. 각 플레이어의 스핀 보너스는 팀 점수에 추가됩니다.",
    "taiko": "일본 반다이-남코의 드럼 게임시리즈에서 영감을 받은, osu!의 태고(Taiko) 모드는 4개의 키로 리듬에 맞춰 북을 치는 모드입니다. 플레이 방법은 [https://osu.ppy.sh/forum/t4363 여기]를 참조하세요.",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 태고 매핑 가이드]",
    "taiko-maps": "공식 태고의 달인 맵들은 [https://osu.ppy.sh/forum/t/5397 이곳]에서 찾아보실 수 있습니다.  ",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "이 주제는 별로 바람직하지 않은 것 같네요. 다른 이야기는 어떨까요?",
    "training": "[https://osu.ppy.sh/forum/t/4280 제임스 트레이닝]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 osu! 및 매핑 최신 튜토리얼 목록]입니다. 당신만의 맵을 만들고 제출해보세요. [https://osu.ppy.sh/forum/t/60228 매퍼/모더를 위한 유용한 가이드]",
    "twc": "전세계 osu! 태고 대회. \n[https://new.ppy.sh/wiki/Tournaments/TWC/2017/ 위키 페이지]에서 자세한 정보를 확인하세요.",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "게임 내 채팅에서 유니코드/비표준 문자를 사용을 피하세요.",
    "upload-cap": "매퍼들에게 동기부여를 하기 위해, 작업중인 맵 저장에 조그만 제한이 있습니다.\n올릴 수 있는 활성화된 작업중 맵은 서포터가 아니라면 3-6개, 서포터는 5-10개까지 입니다. 전에 랭크된 맵들의 개수에 따라 이는 달라질 수 있습니다.",
    "utf8": "IRC 클라이언트에서는 인코딩을 UTF-8로 설정해주어야 글이 깨지지 않습니다.",
    "videogames": "비디오 게임 관련 주제는 #osu 채널에서 이야기 할 수 있습니다. 하지만 주제가 두 개 이상이라면, #videogames 채널을 이용해주세요.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "osu!에 오신 것을 환영합니다! 만약 문제가 생겼거나 질문이 있는 경우에는 #help 에서 물어보세요. (영어 사용)\n즐거운 시간 되세요!",
    "when": "준비가 되었을 때요.",
    "wiki": "[https://osu.ppy.sh/wiki/ osu! Wiki]는 현재 [https://github.com/ppy/osu-wiki/ ppy/osu-wiki]로 이동되었습니다.",
    "wiki-link": "이중 대괄호를 넣어 위키 페이지로 연결할 수 있습니다 : [[ ]]\n예를 들어 [[ ]] 사이에 Kudosu를 넣으면 링크가 만들어집니다. -> [[Kudosu]]",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 212 active FAQs (out of a possible 217) in the Korean (한국어) language.",
    "completion": "The Korean (한국어) FAQ as of last update is 97.7% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp 타이머가 60초로 설정되었습니다!"
}
