
strings = {
    "academy": "[https://www.youtube.com/user/osuacademy Tekan sini] untuk memaparkan osu! academy - Video tutorial untuk segala hal berkaitan osu!",
    "achievements": "Anda akan memperoleh achievement jika anda berjaya menyelesaikan sesuatu, seperti mencapai kombo tertinggi dalam sesebuah lagu atau melengkapkan semua beatmap dalam Theme Pack. Profail anda akan menunjukkan achievement yang telah diperoleh, dan apa yang anda perlu peroleh. Sesetengah nama achievement itu sendiri ialah pembayang mengenai cara memperoleh achievement berkenaan.",
    "add-skin": "[https://osu.ppy.sh/forum/t/3580 Cara-cara untuk menambahkan koleksi skin anda di dalam osu!]",
    "advertising": "Pengiklanan sesuatu yang tidak berkenaan dengan osu! adalah tidak dibenarkan dan anda akan disenyapkan jika didapati bersalah.",
    "answer": "Jika soalan anda tidak dijawab, barangkali mereka juga tidak tahu jawapannya! Cuba cari di forum jika soalan anda berkaitan dengan osu!",
    "appeal": "",
    "approved": "",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "",
    "attention": "Wahai tuan hamba yang budiman, tiada siapa yang mahu mendengar ucapan kamu. Maka berhentilah dengan sebaiknya.",
    "avatar-change": "",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Hello! Sayalah BanchoBot! Gembira bertemu anda! Saya seorang bot, jadi saya tidak boleh bersembang dengan awak. :(",
    "beatmapping": "",
    "beginner": "",
    "bn": "",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Tiada guna memberitahu orang lain jika anda bosan. Sesungguhnya itu ialah perbuatan yang sia-sia dan tiada manfaat. Berehatlah, atau lakukan perkara yang lebih berfaedah!]",
    "bug": "",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "",
    "caps": "Elakkan menaip kesemua ayat dalam huruf besar secara keterlaluan kerana anda boleh disenyapkan.",
    "change-modes": "",
    "change-name": "",
    "changelog": "",
    "chars": "Elakkan penggunaan unikod/non-standard characters di ruang chat awam.",
    "charts": "",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Kuning Muda: Pengguna biasa | Kuning: [https://osu.ppy.sh/p/support osu! Supporter]. Merah: [https://osu.ppy.sh/wiki/QAT QAT] atau [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] | Putih: Diri anda sendiri, atau mesej /me | Biru Tua: Private Message (PM) | Hijau: Baris yang mengandungi nama anda (highlight) | Pink : BanchoBot.",
    "colour": "Kuning Muda: Pengguna biasa | Kuning: [https://osu.ppy.sh/p/support osu! Supporter]. Merah: [https://osu.ppy.sh/wiki/QAT QAT] atau [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] | Putih: Diri anda sendiri, atau mesej /me | Biru Tua: Private Message (PM) | Hijau: Baris yang mengandungi nama anda (highlight) | Pink : BanchoBot.",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Chat command ialah kemudahan untuk semua, mohon elakkan pengunaan secara berlebihan. Hal ini dikategorikan sebagai spam, dan mampu menyebabkan anda disenyapkan.",
    "comment": "",
    "comment-color": "",
    "conferencemode": "",
    "country-ranking": "",
    "critic": "",
    "ctb": "",
    "cutting-edge": "",
    "cwc": "Pertandingan untuk pemain Catch the Beat dari seluruh pelosok dunia. Untuk maklumat lanjut, sila ke [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 sini].",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\r\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\r\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Adab itu penting, kerana orang-orang yang anda sedang berinteraksi ini juga ialah manusia sebagaimana anda. Amalkan sikap berbudi bahasa dan hormat-menghormati jika anda mahu menerima layanan yang sama seperti yang diungkapkan.",
    "disable-this": "",
    "distance-snap": "",
    "dont-ask-peppy": "",
    "douche": "",
    "download": "",
    "drugs": "",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "",
    "english": "",
    "evade": "",
    "fallback": "",
    "faq": "",
    "feature": "",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "",
    "foul-play": "",
    "percolate": "",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "",
    "friends-list": "",
    "fullscreen": "",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "",
    "gmt": "",
    "english-help": "",
    "grammar": "",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "",
    "hacked": "",
    "hard": "",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "",
    "hitsound-library": "",
    "hl": "",
    "how-to-get-modded": "",
    "how-to-bn": "",
    "how-to-gmt": "",
    "how-to-play": "",
    "how-to-rank": "",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "",
    "ignore": "",
    "import": "",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "",
    "irc": "Server IRC: irc.ppy.sh:6667\nKata laluan: https://osu.ppy.sh/p/irc\nUntuk mengetahui lebih lanjut, sila ke https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "",
    "kiai": "",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "",
    "lag": "",
    "language": "Jagalah tatasusila anda di ruang saluran. Bahasa kesat mampu menyebabkan anda disenyapkan.",
    "language-specific": "",
    "lazer": "",
    "level": "",
    "lines": "Sila pastikan ayat anda tidak mempunyai baris yang banyak bagi mengelakkan penyenyapan.",
    "link": "Untuk membuat pautan teks yang merujuk kepada sesuatu, gunakan format seperti berikut: [address text], yang mana address merupakan sesuatu yang ingin anda tujukan, dan text ialah teks yang ingin anda paparkan. [https://osu.ppy.sh/ Contohnya begini!] Jangan lupa sertakan http://.",
    "lobby": "Sila gunakan #lobby untuk mengiklankan permainan multiplayer osu!. Perlu diingatkan bahawa #lobby merupakan saluran pelbagai bahasa. Gunakan #multiplayer untuk perbincangan selanjutnya. ",
    "localisation": "",
    "long-link": "",
    "long-text": "",
    "loved": "",
    "mac": "",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Mapper juga sibuk dengan hal mereka sendiri, dan proses mapping memerlukan daya usaha yang tinggi. Mengapa anda tidak cuba mengemap lagu itu sendiri?",
    "mapping": "",
    "mat": "",
    "modhelp": "",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modding Queues]",
    "modreqs": "",
    "multi-invite": "",
    "multi-link": "",
    "multiaccounting": "",
    "multiplayer": "Diminta agar tidak mengiklankan permainan multiplayer anda di channel lain kecuali #lobby sahaja.",
    "mwc": "Pertandingan untuk pemain osu! Mania dari seluruh pelosok dunia. Untuk maklumat lanjut, sila ke [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 sini].",
    "nat": "",
    "news": "",
    "nightcore": "",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Taip /np untuk memaparkan lagu yang anda sedang dengar atau map yang anda sedang main kepada pemain lain di osu!",
    "nsfw": "Perbincangan keterlaluan (Not Safe For Work) adalah tidak dibenarkan. Perlu diingatkan bahawa osu! adalah untuk semua peringkat usia, sila pastikan ruang chat ini bebas daripada hal berkenaan. Atau anda akan disenyapkan tanpa amaran dengan serta-merta. ",
    "osu": "#osu dikhususkan untuk perbincangan mengenai osu!. Sila bincang perkara berkaitan gameplay di sana, bukan di channel ini.",
    "osu!tablet": "",
    "osu!talk": "",
    "osucore": "",
    "osu!droid": "",
    "osumania": "Sila ke #osumania untuk sebarang perbincangan mengenai osu!mania.",
    "osustream": "",
    "osz": "",
    "osz2": "",
    "owc": "Pertandingan untuk pemain osu! dari seluruh pelosok dunia. Untuk maklumat lanjut, sila ke [https://osu.ppy.sh/wiki/OWC sini].",
    "peppy": "",
    "perfect": "",
    "ping": "Pong!",
    "pippi": "",
    "piracy": "",
    "play-shortcuts": "",
    "pm": "",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "",
    "pp-rework-lazer": "",
    "preview": "",
    "qat": "",
    "qualified": "",
    "ranked": "",
    "ranking-criteria": "",
    "redname": "Pengguna yang mempunyai nama merah ialah seorang [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] atau [https://osu.ppy.sh/wiki/QAT QAT]",
    "report": "",
    "report-abuse": "",
    "request": "",
    "respect": "",
    "roll-abuse": "",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "",
    "rp": "",
    "rules": "",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "",
    "sb": "",
    "scorev2": "",
    "scoring": "",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "",
    "sleep": "",
    "songs-not-appearing": "",
    "spaces": "",
    "spam": "Elakkan spam kerana anda telah mengganggu ketenteraman awam dan biasanya mengundang kesenyapan jika berterusan.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "",
    "spoiler": "",
    "status": "",
    "store": "",
    "submit": "",
    "suck": "",
    "supporter": "",
    "supporter-please": "",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "",
    "tag": "",
    "taiko": "",
    "taiko-mapping": "",
    "taiko-maps": "",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Untuk keamanan sejagat, berhentilah berbicara mengenai topik ini dan bincanglah topik baru yang ada manfaatnya.",
    "training": "[https://osu.ppy.sh/forum/t/4280 Topik mengenai James Training]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "",
    "twc": "Pertandingan untuk pemain Taiko dari seluruh pelosok dunia. Untuk maklumat lanjut, sila ke [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ sini].",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Elakkan daripada penggunaan unikod/non-standard characters di ruang chat awam.",
    "upload-cap": "",
    "utf8": "",
    "videogames": "",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "",
    "when": "Apabila sudah siap sedia.",
    "wiki": "[https://osu.ppy.sh/wiki/ The osu! Wiki] - Jadikan ia lebih hebat!",
    "wiki-link": "",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 79 active FAQs (out of a possible 217) in the Malaysian (Bahasa Malaysia) language.",
    "completion": "The Malaysian (Bahasa Malaysia) FAQ as of last update is 36.41% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
