
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy Klik hier] om naar de osu! academy te gaan - Video instructies voor alle dingen die te maken hebben met osu!",
    "achievements": "Je krijgt achievements door het doen van iets speciaals tijdens een liedje, zoals het halen van een lange combo of het spelen van alle beatmaps in een beatmap thema pack. Op je profiel staan de achievements die je al hebt en die je nog moet. Sommige namen geven tips over wat je moet doen om de achievement te halen!",
    "add-skin": "Download een skin en sleep het bestand in het osu! venster of dubbelklik erop om deze toe te voegen.",
    "advertising": "Reclame maken voor iets anders dan osu! is verboden. Herhaaldelijke en zware overtreders worden op z'n minst met silence gestraft.",
    "answer": "Als niemand reageert op je vraag, dan weten de mensen waarschijnlijk niet wat het antwoord is. Als het met osu! te maken heeft kan je het forum checken.",
    "appeal": "Als je uiteindelijk toch gesilenced wordt, en je denkt dat het niet eerlijk was, stuur dan een PM naar een [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GM] of stuur een e-mail naar accounts@ppy.sh en leg het uit. Onthoud wel, dat GM's ook gewoon mensen zijn. Als je dus aardig tegen ze bent, zullen ze meer hun best doen om je silence weg te halen.",
    "approved": "Approved beatmaps kunnen niet ranked worden, om wat voor reden dan ook - maar zij zijn wel goed genoeg dat mensen ze kunnen spelen, met scoreboard en zo! Je merkt dat een map approved is als het icoontje een vlam is in plaats van een hart.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire, Het hoogste niveau van de osu! beatmapping competitie keert terug in 2017 met een liedje van Helblinde. [http://osu.ppy.sh/news/156171674413 Bekijk het hier!]",
    "ask": "Stel gewoon je vraag. Vraag de mensen niet of je een vraag mag stellen voor je de vraag stelt.",
    "attention": "Het lijkt erop dat het niemand iets uitmaakt wat je zegt. Stop er nu maar mee en ga over op een ander onderwerp.",
    "avatar-change": "Je kan [https://osu.ppy.sh/home/account/edit#avatar hier] je avatar toevoegen/veranderen.",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Hallo, ik ben een bot. Ik kan niet echt een gesprek met je voeren :(\nBancho is de centrale server van osu!",
    "beatmapping": "Lees [https://osu.ppy.sh/wiki/Beatmapping beatmapping] om wat algemene tips over het maken van maps te vinden.",
    "beginner": "[https://osu.ppy.sh/forum/t/5456 Training voor Beginners!]",
    "bn": "De [[Beatmap Nomination Group]] is een group mensen die verantwoordelijk zijn voor het ranken van beatmaps en het matigen van pending beatmaps in de rankings-cyclus. Je kan met hun praten als je vragen hebt of advies wilt in verband met het maken van of modden van beatmaps.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Het heeft geen nut om mensen te vertellen dat je je verveelt.\nNeem een pauze of ga iets anders doen.]",
    "bug": "Gelieve bugs op het [https://osu.ppy.sh/forum/5 forum] te melden ipv in de chat.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Typen met een hoofdletter bij elk woord zorgt er alleen voor dat mensen denken dat je gestoord bent.",
    "caps": "Typen in hoofdletters (caps) is ongewenst en kan bestraft worden met silence.",
    "change-modes": "Om een andere game modus te kiezen, ga je naar het Song Select menu en klik je op 'mode' linksonderin. Je kunt ook Ctrl + 1-4 gebruiken. Onthoud wel dat sommige maps mode-specifiek zijn.",
    "change-name": "Om je schermnaam te veranderen, moet je eerst een [https://osu.ppy.sh/p/support osu! supporter] worden. Je kan dan [https://store.ppy.sh/store/product/32 hier] je schermnaam veranderen. Verzoeken om je oude naam terug te krijgen of om een kleine verandering aan je naam te maken dienen naar accounts@ppy.sh gemailed te worden.",
    "changelog": "Een log met alle updates aan het spel, aan Bancho en aan de website kunnen gevonden worden in osu! development [https://osu.ppy.sh/p/changelog changelog!]",
    "chars": "Probeer alsjeblieft geen unicode/abnormale tekens te gebruiken in de gewone chat.",
    "charts": "osu! charts zijn gethematiseerde pakketen die elke maand uitkomen. Je kan ze [https://osu.ppy.sh/p/chart hier!] vinden.",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Lichtgeel: Een gewone gebruiker. Geel: Een [https://osu.ppy.sh/p/support \nSupporter] Rood: Een [https://osu.ppy.sh/wiki/QAT QAT] of \n[https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] .\nWit: Jij, of een /me bericht. Blauw: Een PM. Groen: Een regel waarin je schermnaam (een highlight) staat. Roze: BanchoBot",
    "colour": "Lichtgeel: Een gewone gebruiker. Geel: Een [https://osu.ppy.sh/p/support \nSupporter] Rood: Een [https://osu.ppy.sh/wiki/QAT QAT] of \n[https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] .\nWit: Jij, of een /me bericht. Blauw: Een PM. Groen: Een regel waarin je schermnaam (een highlight) staat. Roze: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Hoewel chat commando's makkelijk te gebruiken zijn, moet je dit niet te vaak doen. Dit word gezien als spam en kan leiden tot een silence.",
    "comment": "Als je zin hebt om live commentaar te geven op een beatmap replay, druk je op de 'Discussion' knop, type je iets en druk je op enter! Als er geen reacties op het scherm zijn, selecteer dan 'Show Comments' in het 'Discussion' paneel.",
    "comment-color": "Een gewone gebruiker kan alleen maar in het wit berichten sturen. Een [https://osu.ppy.sh/p/support supporter] kan zijn bericht kleur veranderen.",
    "conferencemode": "Als je wordt overspoeld met berichten van mensen die inloggen of uitloggen op IRC? Dan kan [http://wiki.xkcd.com/irc/Hide_join_part_messages dit] je helpen. ",
    "country-ranking": "Bekijk de verschillende landelijke rankings [https://osu.ppy.sh/p/countryranking hier].",
    "critic": "Geef alleen kritiek als het opbouwend is. Suggereer alternatieven of oplossingen om de problemen waar je je zorgen om maakt op te lossen.",
    "ctb": "Heb je wat hulp nodig met CtB? [https://osu.ppy.sh/wiki/Catch_the_Beat Hier] is de wiki pagina",
    "cutting-edge": "Cutting-Edge is een nieuwe experimentele versie van osu!, die wordt gebruikt om niewe functies te testen voor dat ze naar naar Stable gaan. Lees [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues dit artkel] als je problemen hebt met het bijwerken van osu!.",
    "cwc": "Het wereldwijde osu! Catch the Beat toernooi! Voor meer informatie kijk [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 hier]",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Behandel anderen zoals jij behandeld zou willen worden, behalve als je een soort verbale masochist bent.",
    "disable-this": "Toggles worden bijna nooit toegevoegd voor dingen. Je kan er trouwens wel een aanvragen via het [https://osu.ppy.sh/forum/4 Feature Requests subforum]",
    "distance-snap": "Distance Snap is een hulpmiddel dat een juiste relatieve afstand behoudt tussen de noten, gebaseerd op hun plek op de tijdlijn. Informatie: [[Distance_Snap]]",
    "dont-ask-peppy": "A.U.B. niet constant vragen stellen aan peppy. Hij heeft het vaak nogal druk. Er zijn genoeg andere mensen om je te helpen!",
    "douche": "Een officiele regel die zegt dat je geen eikel moet zijn ter bescherming tegen loopholes in het reglement zou niet nodig moeten zijn, maar voor de zekerheid: wees geen eikel.",
    "download": "Je kan meer beatmaps [https://osu.ppy.sh/p/beatmaplist hier] downloaden of download beatmap packs [https://osu.ppy.sh/beatmaps/packs hier].\nAls je niet weet hoe je ze moet importeren, lees [http://i.imgur.com/kpX2N3m.jpg dit] om erachter te komen!",
    "drugs": "Gespreksonderwerpen gerelateerd aan drugs of andere narcotica zijn niet toegestaan. Dit is een spel voor alle leeftijden.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Lees [[Beatmapping#Keyboard_Shortcuts]] om een lijst te vinden met de editor shortcuts.",
    "english": "Het engelse kanaal is voor alles wat geen eigen kanaal heeft, dus ook anime en manga. Verwacht veel drama.",
    "evade": "Probeer geen silences te ontwijken, hiervoor kan je namelijk gebanned worden.",
    "fallback": "Stable (Fallback) is een verouderde build van osu! In tegenstelling tot Fallback, verwijderen de nieuwste uitgaves DirectX support om onze framework te simplificeren. Als je omgeschakeld bent naar deze build, is je PC low-end en zal het de nieuwste en latere versies niet ondersteunen. Als je nu met de actuele builds wilt spelen, moet je jouw grafische kaart updaten en ervoor zorgen dat het OpenGL ondersteunt, het meest benodigde aanvulling voor deze builds. [https://osu.ppy.sh/wiki/GL_Support_Issues Klik hier om te leren hoe.]",
    "faq": "Je gebruikt nu het osu!Bancho FAQ Systeem.\nCentrale osu! FAQ: https://osu.ppy.sh/p/faq\nosu! wiki: https://osu.ppy.sh/wiki",
    "feature": "Als je een idee hebt voor het spel, plaats het in het [https://osu.ppy.sh/forum/4 Feature Requests] subforum.",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Het ontwijken van chatfilters zorgt er hoogstwaarschijnlijk voor dat je word gesilenced.",
    "foul-play": "Als je een cheater ziet, kan je deze reporten met de report knop op hun profiel, die je [https://i.imgur.com/GG9xlLA.png hier] kunt vinden. Probeer in je report zo veel mogelijk details te geven. Je kunt hun scores ook reporten bij de top 50 leaderboards van een beatmap's pagina.",
    "percolate": "Het ontwijken van chatfilters zorgt er hoogstwaarschijnlijk voor dat je word gesilenced.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Dit artikel] zal je helpen om flow in je beatmaps te begrijpen",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Als je een gebruiker als vriend wilt toevoegen, type je /addfriend en daarna zijn naam. Wat je ook kan doen is op het paneel van iemand klikken in het Online gebruikers menu (F9), of op zijn naam in chat klikken. Klik daarna op 'Voeg toe als vriend'. Je kan ook iemand toevoegen door op zijn profielpagina te klikken op de 'Add as Friend'-knop.",
    "friends-list": "Om in het spel een lijst van je online vrienden te zien, druk op F9 en verander de filter naar vrienden. Je kan ook een volledige lijst van je vrienden zien, online en offline, op de website door op 'Settings' te klikken. (Je moet wel ingelogd zijn)",
    "fullscreen": "Je kan kiezen of je het spel fullscreen speelt of niet in het 'Grafisch' gedeelte in de opties. Je kan ook naar fullscreen gaan door Alt+Enter in te drukken op je toetsenbord.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Check [[glossary]] als je niet alle gebruikte termen begrijpt.",
    "gmt": "Het [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team], of in het kort [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT], is een groep gebruikers die helpen osu! te laten lopen. Ze hebben rode namen in de chat en groene namen op de forums. Deze mensen zorgen ervoor dat het forum en de chat netjes blijven.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Zo gemakkelijk, zelfs jij kan het! Hoop ik...]",
    "grammar": "Probeer goede grammatica en spelling aan te houden. Een paar fouten zijn niet erg, maar gebruik geen sms-taal, dat ziet er stom uit.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Weet je niet hoe je moet spelen? Wil je de modding- en mapping-wereld verkennen? [https://osu.ppy.sh/wiki/Guides Hier] vind je alle antwoorden.",
    "hacked": "Als je denkt dat je gehacked bent, stuur een mail naar accounts@ppy.sh om het af te handelen.\nDoe je dit niet dan kan je account verwijderd worden.",
    "hard": "Wordt dan beter, stumper.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Ga naar het #help kanaal als je hulp nodig hebt met osu!-gerelateerde dingen. Let wel dat #help een kanaal is waar meerdere talen gesproken mogen worden.",
    "hitsound-library": "Klik [https://osu.ppy.sh/forum/p/164927 hier] om wat aangepaste hitsounds voor je map te krijgen.",
    "hl": "Geef anderen niet de schuld als je gehighlighted wordt, als je een normaal woord in je highlight lijst hebt staan. Als het nodig is kan je de notificaties en het geluid dat afspeelt uitschakelen bij de opties.",
    "how-to-get-modded": "Als je wilt weten hoe je je map gemodded kan krijgen, klik hier: [[Getting_Your_Map_Modded]]",
    "how-to-bn": "Als je een BN wil worden, lees dan [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator dit] eens door - de andere BN's kiezen meestal wie er wordt gepromoveerd tot BN aan de hand van een aantal dingen, zoals mod-kwaliteit en activiteit.",
    "how-to-gmt": "Moderators worden gekozen uit de actieve mensen die verschillende dingen doen voor de community. Wil je mod worden? Help ons door je best te doen met het schoonhouden van channels waar je vaak in zit, door misbruik te melden met het !report command.",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F Klik op deze link om te leren hoe je moet spelen!]",
    "how-to-rank": "Om meer te weten te komen, lees [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Hyperdash zal ontstaan als je fruit vangt met een rode gloed. Je krijgt daarna een snellere dash. Deze stopt als je het volgende fruitstuk vangt of mist.",
    "ignore": "Om een gebruiker te negeren, type je /ignore en dan hun naam. Je zal geen regels zien van gebruikers die jij hebt genegeerd, dat geldt ook voor PM's die ze jou sturen. Als je /unignore (naam) typt, is dit effect weg, net als als je osu! sluit.",
    "import": " Lees [http://i.imgur.com/kpX2N3m.jpg dit] om te ontdekken hoe je beatmaps kan importeren in osu!",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Als je het vakje 'Inherit previous timing settings' in het F6 scherm van de editor aanvinkt, zal een timing sectie de timing niet veranderen, wat handig is voor secties die alleen het volume of iets dergelijks aanpassen. Ook is het mogelijk om timing secties te plaatsen die een verdubbeld of een gehalveerd BPM hebben. Als je zoiets gebruikt, vraag het even na.",
    "irc": "IRC server: irc.ppy.sh:6667\nWachtwoord: https://osu.ppy.sh/p/irc\nMeer details op https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Je kan je toetsen veranderen bij input in options. Voor mania is er een apparte 'osu!mania layour' knop om je toetsen aan te passen.",
    "kiai": "Kiai mode is een style-effect die je kan toevoegen via je het Timing Setup Panel. Timing secties met Kiai mode aan gebruiken verschillende visuele effecten om een beatmap nog  'epischer' te maken.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Je verdient [https://osu.ppy.sh/wiki/Kudosu kudosu] door het modden van andermans maps.",
    "lag": "Lag kan overal door komen - het vaakst door andere processen op je machine. Als je er zeker van bent dat osu!, en alleen osu! lagt, zeg het op het Help forum en leg je situatie uit. Leg ook alles uit wat erbij kan helpen om erachter te komen waar de lag vandaan komt.",
    "language": "Wees alsjeblieft beleefd in de chat. Ongepast taalgebruik kan ervoor zorgen dat je wordt gesilenced.",
    "language-specific": "Gebruikt alsjeblieft de geschikte taal voor het kanaal dat je bezoekt. Het gebruikt van geromaniseerde woorden of uitspraken zijn geen uitzondering voor niet Romeinse talen zoals Japans.",
    "lazer": "",
    "level": "Je level is gebaseerd op je totale cumulatieve score. Dit is elke ranked score, zij het een pass, of een faal. Je level gaat dus geleidelijk omhoog, door alleen maar te spelen.",
    "lines": "Houd je zinnen op een regel, als je je zin in te veel stukken breekt kan je gesilenced worden.",
    "link": "Om teksten naar een link te leiden, doe dat zo: [link tekst], waarbij link het adres is die je wilt linken, en tekst de tekst die je wilt laten zien. [https://osu.ppy.sh/ Zoals dit!] Vergeet de http:// alleen niet.",
    "lobby": "Gebruik #lobby alleen voor het adverteren van multiplayer games, onthoud wel dat #lobby een meertalig kanaal is. Gebruik het #multiplayer kanaal van jouw match voor andere discussies.",
    "localisation": "Vind het osu! lokalisatieproject [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 hier].",
    "long-link": "Plak geen lange links in de chat! Gebruik de [link tekst] formule als het moet.",
    "long-text": "Plak geen lange teksten in de chat. Je kan gesilenced worden als je het wel doet.",
    "loved": "Loved' is een rankingstatus waar de community zorgt dat maps die eigenlijk unrankable zijn een ranglijst krijgen. [[https://osu.ppy.sh/news/151925254083 Lees hier meer!]",
    "mac": "[https://osx.ppy.sh Zorg dat osu! runt op je Mac]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Mappers zijn drukke mensen en beatmaps maken is veel werk. Waarom probeer je het niet zelf?",
    "mapping": "Ga [https://osu.ppy.sh/forum/p/988111 hierheen] voor mapping tips.",
    "mat": "De Mapping Assistance Team was een oude groep die de BAT's hielp bij het ranken. RIP MAT 23-04-2013",
    "modhelp": "Voor al je vragen over het modden van maps ga je naar #mapping.",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modding Queues]",
    "modreqs": "Ga naar #modreqs voor mod-verzoeken. Houd in je achterhoofd dat BAT's niet altijd tijd hebben en dat andere mensen het misschien wel eerder vroegen, dus vraag ook aan gewone mensen om je beatmaps te modden. Bedankt.",
    "multi-invite": "Om iemand uit te nodigen voor je multiplayer game als jij de host bent, klik je op de gebruiker die je wilt toevoegen in de Online Users list (F9) of klik op hun naam in de chat, en klik je op 'Invite to game'. Je kan ook '/invite' gevolgd door de username van de gebruiker die je wil toevoegen typen.",
    "multi-link": "",
    "multiaccounting": "Je moet absoluut, maar dan ook echt absoluut geen meerdere accounts maken. Je wordt gevonden, je wordt gesilenced voor een hele lange tijd of zelfs gebanned.",
    "multiplayer": "Je mag je multiplayer match niet adverteren in de chat, behalve in #lobby.",
    "mwc": "Een wereldwijd osu!Mania toernooi. Zie [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 deze pagina] voor meer informatie.",
    "nat": "",
    "news": "",
    "nightcore": "Heb plezier van je favoriete maps in Nightcore style! Klik nog een keer op de DoubleTime mod om de Nightcore mod te krijgen. Het functioneert hetzelfde als DoubleTime qua punten.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Type /np om anderen te laten zien wat je luistert of wat je speelt in osu!",
    "nsfw": "osu! is voor alle leeftijden, dus probeer de chat schoon te houden en niets wat NSFW is te posten, doe je dit toch dan riskeer je een silence.",
    "osu": "#osu is voor praten over osu!. Praat daar over het spel, niet in dit kanaal.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 De officiele osu!tablet] - Lees dit voor alle infromatie over de tablet en preorder opties.",
    "osu!talk": "osu!talk is een talkshow gehost door deadbeat en ztrot waarin ze leden van de community interviewen en praten over evenementen zoals de wereldkampioenschappen. Elke aflevering zal plaats nemen op de TeamSpeak 3 server osu.corin.me; je zal er vragen kunnen stellen in het Q&A (vraag en antwoord) deel. Meer informatie kan [https://osu.ppy.sh/forum/t/225111 hier] gevonden worden.",
    "osucore": "Een 1 april grap in 2011. Alle maps werden gezet op DoubleTime en verhoogd qua toon. Dit kwam later terug als Nightcore, wat dezelfde effecten had als DoubleTime die dag.",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] is een port van het originele spel on het Android platform.\nHet is verlaten door de officiele ontwikkelaars en het is van de Google Play Store afgehaald sinds 2016 door inactiviteit en slechte revieuws.",
    "osumania": "Gebruik #osumania voor dingen gerelateerd aan osu!mania.",
    "osustream": "[http://www.osustream.com osu!stream] is osu! voor iOS apparaten, gemaakt en onderhouden door onze eigen peppy!",
    "osz": "Het bestandsoort van beatmaps dat je moet downloaden voor osu!. Om ze te spelen, moet osu! zelf die bestanden uitpakken, anders kunnen er problemen ontstaan.",
    "osz2": "Een nieuw beatmap file soort, wat betekent dat elk bestand kan worden gelezen, geüpdated, enzovoort, onafhankelijk van alle andere files. osz2 files hoeven niet 'uitgepakt' te worden, en zullen altijd als .osz2 files in je song map blijven.",
    "owc": "Een wereldwijd osu! tournooi. Bekijk [https://osu.ppy.sh/wiki/OWC deze draad] voor meer informatie.",
    "peppy": "peppy is de leider van het [https://osu.ppy.sh/p/team osu! team] en maker van osu!.",
    "perfect": "Probeer je een SS te krijgen? Deze mod herstart de map automatischals je een fout maakt. Je krijgt hem door nog een keer op SuddenDeath te klikken.",
    "ping": "Pong!",
    "pippi": "De mascotte van osu!\nPippi-don is de taiko (drum) versie van Pippi.",
    "piracy": "Zeg en vraag niets over het 'piraten' van gecopyrightte content in de chat, dit is namelijk verboden en kan in tot een silence leiden.",
    "play-shortcuts": "Volledige lijst van sneltoetsen: [[Shortcut_Key_Reference]]",
    "pm": "Om iemand een privébericht te sturen, klik je op zijn/haar naam in de chat of klik op zijn/haar paneel in het Online Users screen (F9) en klik op start chat. Je kan ook de commands /msg <username>, /chat <username> of /query <username> gebruiken, die een apart tabblad opent in de chat. Om snel te reageren op je laatst binnen gekregen prive bericht, gebruik je /r <message>. Haal natuurlijk wel eerst even de < > weg.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance points (pp) is het ranking systeem van osu! Klik [https://osu.ppy.sh/wiki/Performance_Points hier] voor meer info.",
    "pp-rework-lazer": "",
    "preview": "Het preview punt is het punt in een liedje vanwaar het lied begint in het beatmapkeuze-menu. Een goed punt is een punt in het lied dat het lied goed weergeeft, zoals het begin van het refrein. Ga naar Timing in de menu balk en klik op 'Set current position as previeuw Point' om er een te kiezen.",
    "qat": "",
    "qualified": "Beatmap nominatoren nomineren beatmaps als gekwalificeerd, klaar om gerankt te worden waarbij je een rank op de leaderboard kan behalen zonder er Performance Points voor te krijgen. Als deze maps geen problemen hebben en een week gekwalificeerd staan worden ze gerankt. Anders gaan ze terug naar pending en worden alle scores gewist.",
    "ranked": "Een Ranked map is een map die is goedgekeurd door de mensen online. Als je een ranked map speelt, wordt de score opgeslagen en telt mee voor je Ranked Score. De maps hebben een scorebord en worden geindentificeerd met een 'Hart' symbool.",
    "ranking-criteria": "Voor informatie over de Ranking criteria, ga naar de wiki [[RC]].",
    "redname": "Gebruikers met een rode naam zijn of een [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] of een [https://osu.ppy.sh/wiki/QAT QAT].",
    "report": "Soms is er geen moderator beschikbaar. Het zijn ook maar gewoon mensen die niet de hele dag de chat in de gaten kunnen houden. Als je iemand iets ziet doen dat tegen de regels is en er geen mod is die er iets aan doet, gebruik dan !report. Iemand zal je dan zo snel mogelijk te hulp schieten.\nGebruik geen BanchoBot PM om iemand aan te geven, en gebruik het format !report <gebruiker> <reden>.",
    "report-abuse": "Probeer niet meerdere keren achter elkaar te reporten - het helpt niet. Net als lege of onredelijke reports sturen. Je kan dan zelf gesilenced worden voor het spammen van de moderators.",
    "request": "Op zoek naar iets om te modden? Klik [https://osu.ppy.sh/p/beatmaplist&r=8 hier] of typ !request voor een willekeurig link naar een map.",
    "respect": "Wees alsjeblieft respectvol tegenover andere spelers.",
    "roll-abuse": "Gebruik het !roll command niet te vaak. Je kan hiervoor gesilenced worden.",
    "romaji": "Gebruik alsjeblieft Romaji (geromaniseerd Japans) niet te veel. Je kan het zwijgen opgelegd krijgen.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Zijn er geen multiplayer rooms beschikbaar? Waarom maak geen eigen room? Je mag dan zelfs zelf de liedjes kiezen!",
    "rp": "Je mag best rollenspellen spelen in gepaste osu! kanalen; maar je moet er wel voor zorgen dat je de andere mensen in het kanaal niet te erg lastig valt.",
    "rules": "[https://osu.ppy.sh/wiki/nl/Rules De officiële Regels]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "Van tijd tot tijd wordt osu! ge-DDoSed. Tijdens dit kan Bancho onstabiel of onbereikbaar zijn. Als je denkt dat dit het geval is, bekijk de [https://twitter.com/osustatus @osustatus] Twitter feed of [https://status.ppy.sh deze site] for meer info. Als dit gebeurt, en je kunt gewoon chatten - ga gewoon door. Het onderwerp ter sprake brengen zorgt niet dat het sneller weggaat.",
    "sb": "[[Storyboarding]] Storyboarding Guide: https://osu.ppy.sh/forum/t/1869\nHoe gebruik je de Storyboard Editor: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "Scorev2 is een nieuw scoringsalgoritme dat de scores voor alle spelmodi tot 1 miljoen punten verlaagt, exclusief spinners en mods.\nHet verandert ook het gedrag van sliders zodat ze dezelfde timing als hitcircles nodig hebben.",
    "scoring": "Hoe osu! score berekent: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Een silence betekent dat je niet mag praten in de chat of iets op het forum mag posten, behalve in Technical Support.\nDe duur van silences begint bij 5 minuten bij de eerste overtreden en verdubbelt bij iedere overtreding daarna. Zware overtredingen kunnen de vorige silence echter meer dan verdubbelen.\nSilences worden toegekend bij de meeste misdrijven, dus je hoeft niets te vrezen als je de regels volgt.\n",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "Lees [https://osu.ppy.sh/forum/t/51694 hier] de meestgestelde vragen over Skinning.",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Niet tot 4 uur 's nachts opblijven om osu! te spelen, slaap is belangrijk!]",
    "songs-not-appearing": "Als je maps niet verschijnen, probeer de F5 knop in het keuzemenu.",
    "spaces": "Stop eens met spaties tussen elke letter zetten, je aesthetics verpesten de chat en je kan er voor gesilenced worden.",
    "spam": "Spammen kan bestraft worden met een silence, want het is vervelend. Niet doen.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Om een andere speler te bekijken typ /watch <username>, of klik op hun naam en klik op Start Spectating. Zorg wel dat je de beatmap hebt die de ander speelt! (Supporters kunnen deze automatisch downloaden).",
    "spoiler": "Skriv og detaljer enhver anime , serie , manga , doujin mv er forbudt, og det kan straffes med en tavshed eller forbud.",
    "status": "Voor osu! systeemstatus updates kan je [http://twitter.com/osustatus @osustatus] raadplegen. Zie [https://status.ppy.sh deze site] voor de serverstatus.",
    "store": "[https://osu.ppy.sh/p/market Welkom in de osu!markt], de plek waar je te gekke dingen kan kopen, zoals osu!t-shirts en andere coole dingen.",
    "submit": "[https://osu.ppy.sh/wiki/Submission Beatmap Submission FAQ]",
    "suck": "Maak je geen zorgen, oefening baart kunst. Iedereen was ooit een beginner.",
    "supporter": "Word een [https://osu.ppy.sh/p/support osu! supporter] voor wat leuke extra's, ook help je om osu! draaiende te houden!",
    "supporter-please": "Vraag alsjeblieft niet om supporter aan mensen die dat niet willen, je komt slecht en irriterend over. [https://osu.ppy.sh/p/support Waarom koop je in plaats daarvan het niet zelf?]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "[https://osu.ppy.sh/forum/t/87301 Lees dit] als je moeilijkheden hebt met het spelen van osu! met een tablet.",
    "tag": "In tag multiplayer mode, klikken alle spelers een combo van een beatmap per keer. Er is geen winnaar, omdat iedereen samen speelt. In Spinners doet iedereen mee. Als zelfs maar één iemand de spinner mist, zal de combo resetten. Elke speler zijn spinner bonus wordt bij elkaar geteld voor de totale score.",
    "taiko": "Een Japanse drum die in sommige series van spellen zit van Bandai-Namco. osu!'s 'Taiko mode' simuleert deze spellen om de locatie van de beats weg te halen, en de speler dwingen om alleen op het rhytme van de map te letten. [https://osu.ppy.sh/forum/t/4363 Hier is te vinden hoet je moet spelen!] ",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Taiko map hulp]",
    "taiko-maps": "Je vind authentieke Taiko no Tatsujin maps [https://osu.ppy.sh/forum/t/5397 hier].",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Kunnen jullie nou eens stoppen over dit onderwerp en het over iets anders hebben?",
    "training": "[https://osu.ppy.sh/forum/t/4280 James Training]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "https://osu.ppy.sh/forum/t/109137 Een lijst van up-to-date video tutorials in osu! en mapping]. Maak er gerust zelf een, en plaats het in de topic. [https://osu.ppy.sh/forum/t/60228 Een lijst voor handige gidsen voor mappers/modders].",
    "twc": "Een wereldwijd osu! Taiko toernooi. Zie [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ deze pagina] voor meer info.",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Probeer alsjeblieft geen unicode/abnormale tekens te gebruiken in de gewone chat.",
    "upload-cap": "Om mappers bezig te houden met hun map, zit er een kleine limiet op het aantal maps die je kan hebben waar je mee bezig bent. Niet-supporters kunnen 3-6 actieve maps hebben, en supporters 5-10, dat ligt aan het aantal ranked maps dat je hebt.",
    "utf8": "Zet je IRC client zo dat het UTF-8 codering gebruikt, zodat je normaal berichten kan lezen en kan versturen naar anderen. ",
    "videogames": "Praten over onderwerpen zoals Touhou, Pokemon, StarCraft, League of Legends en andere videogames is toegestaan, maar ga naar #videogames als je er mensen in dit kanaal mee lastig valt.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Welkom bij osu! Als je een probleem hebt of een vraag hebt en antwoord wil kan je het aan de aardige mensen in #help vragen! Veel plezier!",
    "when": "Als het klaar is.",
    "wiki": "[https://osu.ppy.sh/wiki/ De osu! Wiki] - Maak het fantastisch!",
    "wiki-link": "Je kan naar wiki pagina's linken door de naam van de pagina tussen dubbele haken te zetten: [[ ]]. Bijvoorbeeld, [[Kudosu]] wordt gemaakt door Kudosu te typen tussen [[ ]].",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 211 active FAQs (out of a possible 217) in the Dutch (Nederlands) language.",
    "completion": "The Dutch (Nederlands) FAQ as of last update is 97.24% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
