
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy Klikk her] for å vise osu!academy - Opplæringsvideoer for alt som har med osu! å gjøre!",
    "achievements": "Du kan oppnå prestasjoner ved å gjøre noe spesielt i løpet av en sang, som for eksempel å få en høy combo, eller ved å spille alle beatmappene i en temapakke. Profilen din viser hvilke prestasjoner du har oppnådd, og hva du fremdeles mangler. Noen av navnene er ledetråder angående hva som må gjøres for å oppnå prestasjonen!",
    "add-skin": "For å legge til nye skins, last ned og dra filen inn til osu! vinduet eller dobbelklikk filen.",
    "advertising": "Det å reklamere for ting som ikke er relatert til osu! er ikke tillatt og kan få deg brakt til taushet.",
    "answer": "Dersom ingen svarer deg, så er det mulig at ingen kjenner til svaret! Prøv å søke på forumene dersom det er osu!-relatert.",
    "appeal": "Dersom du ender opp med å bli brakt til taushet, og du synes det var urettferdig, send en privatmelding til en [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GM] hvor du forklarer situasjonen din. Bare husk at GMer er mennesker, de også! Dersom du er snille mot dem, er det mer trolig at de vil forsøke sitt beste for å fjerne forstummelsen, dersom det er mulig.",
    "approved": "Approved beatmaps kan ikke rankes av en eller annen grunn - men er fremdeles god nok til at folk kan spille dem, med en poengtavle og alt! Du vil vite om det er et approved beatmap ved at mapikonet vises som en flamme i stedet for et hjerte.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire, den fremste toppnivå osu! beatmapping konkurransen vender tilbake i 2017 med en sang fra Helblinde. [http://osu.ppy.sh/news/156171674413 Sjekk det ut her!]",
    "ask": "Den beste måten å få svar på er ved å stille spørsmålet ditt - det er ikke noe stort poeng i å stille et spørsmål uten å ha stilt et spørsmål!",
    "attention": "Kan du være så snill og stoppe nå? Ingen følger egentlig med på det du sier...",
    "avatar-change": "Vil du endre profilbildet ditt? Ikke noe problem! Bare gå [https://osu.ppy.sh/home/account/edit#avatar hit!]",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Hei der! Jeg er BanchoBot! Hyggelig å møte deg!\nMen jeg er en robot, så jeg kan ikke faktisk holde en samtale med deg. :(\nI fritiden min så hjelper jeg til med å drive osu! og tar lange turer langs stranden.",
    "beatmapping": "Her finnes noen hjelpsomme tips angående [https://osu.ppy.sh/wiki/Beatmapping beatmapping]!",
    "beginner": "[https://osu.ppy.sh/forum/t/5456 Her] finner du en hjelpsom guide for nybegynnere, hvis du føler du trenger det!",
    "bn": "[[Beatmap Nomination Group]] er en gruppe folk som har ansvar for rangering av beatmap og er ansvarlige for å håndtere og moderere ventende beatmap inn til rangering syklusen. Du kan snakke med dem hvis du har spørsmål eller trenger hjelp til å lage beatmap eller moderere.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Hvis du kjeder deg, så er internettet et magisk sted for å bli kvitt den følelsen! Det å fortelle andre folk at du kjeder deg hjelper ingenting, du må være aktiv! Gå og se en YouTube-video, eller utforsk verden med Google Earth!]",
    "bug": "Dersom du er ganske sikker på at du har funnet en feil, rapporter det [https://osu.ppy.sh/forum/5 her]! - Feil rapportert i chatten går bort i all annen chat som foregår.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Vennligst ikke bruk stor forbokstav i hvert eneste ord - det er simpelthen ikke riktig.",
    "caps": "Å skrive i allcaps kan føre til at du blir fratatt din rett til å skrive i chatten. Ikke gjør sånt, vær så snill.",
    "change-modes": "For å endre til en av de andre spillemodusene, gå til skjermen for valg av sang og enten klikk på Modus nederst til venstre eller bruk Ctrl + 1-4. Husk at noen maps er modus-spesifikke!",
    "change-name": "For å endre brukernavnet ditt så må du først være en [https://osu.ppy.sh/p/support osu!-supporter!]\nEtterpå kan du [https://osu.ppy.sh/forum/t/34694 lese dette] for å lære mer om navneendringer!",
    "changelog": "Nylige endringer av meg og osu! i seg selv er funnet i osu!-utviklingens [https://osu.ppy.sh/p/changelog endringslogg!] Pass på, den er veldig lang!",
    "chars": "Vennligst bare bruk vanlige/standard symboler i denne chatten. Takk!",
    "charts": "osu! charts er tematiserte pakker som utgis hver måned. DU kan finne dem [https://osu.ppy.sh/p/chart her!]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Blekgul: En normal bruker | Gul: En [https://osu.ppy.sh/p/support Supporter] | Oransje-rød: En [https://osu.ppy.sh/wiki/BAT BAT] eller [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nHvit: Deg selv, eller en /me-melding | Mørkeblå: En PM | Grønn: En linje som inneholder brukernavnet ditt (eller en highlight) | Rosa: BanchoBot",
    "colour": "Blekgul: En normal bruker | Gul: En [https://osu.ppy.sh/p/support Supporter] | Oransje-rød: En [https://osu.ppy.sh/wiki/BAT BAT] eller [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nHvit: Deg selv, eller en /me-melding | Mørkeblå: En PM | Grønn: En linje som inneholder brukernavnet ditt (eller en highlight) | Rosa: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Samtale komandoene er til for å gjøre livet ditt enklere, venligst ikke bruk dem for mye. Det kan bli sett på som søppel meldinger, og kan føre til at du blir brakt til taushet.",
    "comment": "Hvis du skulle ønske å lage en live kommentar på en replay av et beatmap, trykk på Diskusjon-knappen, skriv noe, og trykk enter!\nDersom det ikke finnes noen kommentarer på skjermen allerede, merk Vis kommentarer-boksen i diskusjonspanelet.",
    "comment-color": "En normal bruker kan kun kommentere med hvit tekst.\nEn [https://osu.ppy.sh/p/support supporter] kan velge en egendefinert farge for kommentarene deres.",
    "conferencemode": "Blir du overveldet av Join/Quit-meldinger på IRC? [http://wiki.xkcd.com/irc/Hide_join_part_messages Dette] kan kanskje hjelpe!",
    "country-ranking": "Vis de forskjellige poengtavlene for [https://osu.ppy.sh/p/countryranking landsrankingen] her.",
    "critic": "Prøv å gi konstruktiv kritikk. Foreslå alternativer til hvordan en kan fikse problemene du er bekymret over.",
    "ctb": "Trenger du litt hjelp med Catch the Beat? [https://osu.ppy.sh/wiki/Catch_the_Beat Her] er wiki-siden!",
    "cutting-edge": "Cutting-edge er en eksperimentell versjon av osu! som brukes til å teste nye funksjoner før de blir lagt til i den stabile versjonen. Bytt til dette i alternativene!\r\nDu kan [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues lese denne artikkelen] hvis du har problemer med å oppdatere klienten.",
    "cwc": "Det er en verdensomspennende osu! Catch the Beat-turnering! Se [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 her] for mer info!",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Behandle andre slik du ønsker å bli behandlet selv. Dersom du er en slags form for verbal masochist, anta at alle andre ikke er det.",
    "disable-this": "Brytere blir sjeldent lagt til for funksjoner. Du kan allikevel legge inn en forespørsel om at en skal legges til via [https://osu.ppy.sh/forum/4 sub-forumet for funksjonsforespørsler].",
    "distance-snap": "Den enkleste måten å forsikre seg om at avstand mellom beats blir korrekt i dine beatmaps er å benytte deg av redigeringsverktøyets avstandssnapping-funksjon, som befinner seg nederst til høyre innenfor redigeringsverktøyet. Den relative distansen mellom noter kan justeres ved hjelp av musehjulet. Dersom du holder deg til å bruke avstandssnapping gjennom hele sammen, vil korrekt avstand mellom beats være garantert!",
    "dont-ask-peppy": "Vennligst ikke spør peppy hele tiden - han er en travel mann. Men du kan gjerne spørre hvem som helst annen i denne kanalen!",
    "douche": "Som en idiotsikker beskyttelsesteknikk, vil det å unngå orden og høflighet via smutthull i reglene være straffbart etter det administrasjonsteamets eget skjønn. En offisiell regel som tilsier at du ikke skal oppføre deg som en idiot burde ikke behøves for at du ikke skal oppføre deg som en idiot, men bare for sikkerhetens skyld: ikke oppfør deg som en idiot.",
    "download": "Du kan laste ned flere beatmaps [https://osu.ppy.sh/p/beatmaplist her] eller beatmap-pakker [https://osu.ppy.sh/beatmaps/packs her].\nOm du er usikker på hvordan man skal importere disse, kan du lese [http://i.imgur.com/kpX2N3m.jpg dette] for å finne ut av det!",
    "drugs": "Vennligst ikke diskuter narkotika av hvilket som helst slag i osu!-chat.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Les [[Beatmapping#Keyboard_Shortcuts]] for å finne listen over snarveier innenfor redigeringsverktøyet.",
    "english": "#english er for generell diskusjon om alt som ikke har noen dedikert kanal.\nJa, dette inkluderer anime/manga.",
    "evade": "Å prøve å unngå en forstummelse er en utestengelsesverdig krenkelse. Utestengelser er mye, mye verre enn forstummelser.",
    "fallback": "Stable (Fallback) er en utdatert build av osu! I forskjell av Fallback, Blir DirectX fjernet for å forenkle rammeverket. Vis du har bytta til denne builden, så er PCen din low-end og vil ikke støtte den nyeste eller fremtidige klientversjoner. Vis du vil spille i den nåværande builden, oppdater grafikk kortet ditt og vær sikker på at den støtter OpenGL som da er nødvending for de nye buildene. [https://osu.ppy.sh/wiki/GL_Support_Issues Klikk her for å vite hvordan].",
    "faq": "Du benytter deg nå av osu!Bancho FAQ-systemet.\nosu! wiki: https://osu.ppy.sh/wiki",
    "feature": "Funksjonsforespørsler hører hjemme i sub-forumet for [https://osu.ppy.sh/forum/4 funksjonsforespørsler].",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Det å unngå chattefiltrene er en av de raskeste bekreftede måtene å ende opp forstummet eller utestengt på. Ikke gjør det.",
    "foul-play": "Vær så snill og rapporter juksere ved å bruke rapporter knappen i profilen til den spiller, den er [https://i.imgur.com/GG9xlLA.png her]. Det hjelper om du fyller in så mye detaljer som muligt. Du kan også rapportere poengsummene deira i topp 50 ledertavlen på siden av en beatmap.",
    "percolate": "Det å unngå chattefiltrene er en av de raskeste bekreftede måtene å ende opp forstummet eller utestengt på. Ikke gjør det.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Denne artikkelen] vil hjelpe deg med å forstå flyten innenfor mapping.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "For å legge til en bruker som en venn, skriv /addfriend fulgt av brukerens navn.\nI tillegg så kan du klikke på brukerpanelet deres i listen over påloggede brukere (trykk F9) eller på navnet deres i chatten, for så å velge Add as Friend.\nDu kan også legge dem til gjennom profilen deres ved å klikke på Add as Friend.",
    "friends-list": "For å se en liste over vennene dine som er på nett innenfor spillet, press F9 for deretter å endre filteret på toppen til Venner.\nDu kan også se en fullstendig liste over vennene dine, både de som er på nett og frakoblet, på nettsiden ved å klikke på Settings. (Du må være innlogget, selvfølgelig.)",
    "fullscreen": "Du kan endre om spillet skal spilles i et vindu eller i fullskjerm via Grafikk-fanen under innstillinger.\nDu kan også bytte mellom fullskjerm og vindu ved å trykke Alt+Enter på tastaturet ditt.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Du kan finne masser av terminologi i osu! [[glossary]].",
    "gmt": "Det [https://osu.ppy.sh/wiki/People/Global_Moderation_Team globale moderasjonsteamet], eller GMT, er en gruppe med brukere som hjelper til med å drive osu!. De har røde navn innenfor chatten, og grønne navn på forumene.\nDisse folkene hjelper med å moderere forumet og chatten.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Les den, lær den, og bruk den.]",
    "grammar": "Prøv å benytte så godt som mulig, grammatisk sett. Noen få feiltakelser i staving eller tegnsetting er akseptabelt, men vær så snill, ikke bruk unødvendige forkortelser eller SMS-språk. Det får deg til å se dum ut.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Vet du ikke hvordan man spiller? Vil du utforske verdenen av mapping og modding?\n[https://osu.ppy.sh/wiki/Guides Her] vil du finne alle svarene.",
    "hacked": "Dersom du mener at du har blitt hacket, vennligst send en e-post til accounts@ppy.sh for oppfølgning.\nDersom dette ikke gjøres kan det føre til at kontoen din elimineres.",
    "hard": "Bli god, skrubb.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Hvis du trenger assistanse for noe osu!-relatert, gå til #help kanalen for å stille spørsmål du måtte ha.",
    "hitsound-library": "Gå [https://osu.ppy.sh/forum/p/164927 hit] for å få tak i noen egendefinerte hitsounds for mappet ditt.",
    "hl": "Ikke skyld på andre brukere for at de highlighter deg dersom du har et vanlig ord eller annen vanlig frase i listen over termer som highlighter deg.",
    "how-to-get-modded": "Hvis du vil vite hvordan du kan få mappet ditt til å bli sjekket av andre, klikk her: [[Getting_Your_Map_Modded]]",
    "how-to-bn": "Dersom du ønsker å bli en BN, sjekk ut [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator dette] - mesteparten av tiden så vil andre BN-folk velge hvem som skal forfremmes til BN basert på en haug av ting, slik som kvalitet av moderering og aktivitet.",
    "how-to-gmt": "Chat moderatorer er håndplukket ut fra faste bidragsytere i samfunnet. Vil du hjelpe til? Gjør ditt beste med å moderere de kanaler du går til ved å rapportere misbruk ved hjelp av !report-kommandoen.",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F Klikk denne linken for å lære hvordan du spiller!]",
    "how-to-rank": "For å vite hvordan, les [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Hyperdash skjer når du fanger en frukt som lyser rødt. Du vil fly raskere enn normalt i løpet av denne perioden. Det vil deaktiveres så snart du treffer den neste fruken, eller om du bommer på den.",
    "ignore": "For å ignorere en bruker, skriv /ignore og deretter brukernavnet deres.\nDu kan ikke se linjer skrevet av brukere du har ignorert, som inkluderer privatmeldinger de kanskje måtte sende deg. Ved å skrive /unignore (brukernavn) eller avslutte osu! vil stoppe denne effekten.",
    "import": "Les [http://i.imgur.com/kpX2N3m.jpg dette] for å finne ut hvordan du importerer beatmaps inn i osu!",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Ved å krysse av i boksen Inherit previous timing settings i F6-vinduet innenfor redigeringsverktøyet, vil ikke timing-seksjonen ha noen virkning på timingen lenger, som er nyttig for deler som kun endrer volum eller samplet til mappen.\nDet er også mulig å arve timing-seksjoner som har doblet eller halvert BPM. Dersom du finner ut at du bruker en timing-seksjon som denne, vennligst kryss av i boksen!",
    "irc": "\n\nIRC server: irc.ppy.sh:6667\nPassord: https://osu.ppy.sh/p/irc \nMer detaljer her \nhttps://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Du kan endre tastatur bindinger på input seksjonen på instillinger. Taster og oppsett til osu!mania endres i osu!mania oppsett knappen.",
    "kiai": "Kiai-modus er en stileffekt du kan legge til i timing-seksjoner ved hjelp av panelet for oppsetting av timing. Timing-seksjoner med kiai-modus slått på vil bruke forskjellige visuelle effekter for å gjøre et beatmap mer episk.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Tjen [https://osu.ppy.sh/wiki/Kudosu kudosu] ved å modde andres beatmaps.",
    "lag": "Lag kan forårsakes av alt mulig - mest sannsynlig av andre prosesser som kjører på datamaskinen din. Dersom du er overbevist over at det er osu! og bare osu! som lagger, legg inn en støtteforespørsel på forumet for teknisk støtte hvor du legger ut detaljer angående ditt problem og alt du har funnet som kan hjelpe til med å identifisere dette.",
    "language": "Vennligst vær høflige i chatrommet. Upassende språk kan gjøre deg forstummet.",
    "language-specific": "",
    "lazer": "",
    "level": "Nivået ditt er basert på din totale akkumulerte poengtelling. Dette inkluderer hvilken som helst rangert poengtelling, måtte det være seier eller tap. Du vil gradvis øke nivået ditt ved bare å spille osu!",
    "lines": "Vennligst prøv å holde setningene dine på én enkel linje for å unngå forstumming.",
    "link": "For å gjøre tekst om til en lenke til noe, bruk følgende format: [adresse tekst], hvor adresse er adressen du ønsker å koble til, og tekst er teksten du ønsker skal vises. [https://osu.ppy.sh/ Slik som dette!] Glem ikke å få med http://-delen.",
    "lobby": "Vennligst bruk #lobby for å annonsere for osu! flerspillerspill. Dessuten så er #lobby en flerspråklig kanal.\nBruk ditt roms #multiplayer kanal for all annen diskusjon.",
    "localisation": "Finn osu!-lokaliseringsprosjektet [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 her].",
    "long-link": "Vennligst ikke lim inn lange lenker i chatten! Bruk [lenke tekst]-formlen dersom du virkelig er nødt.",
    "long-text": "Vennligst ikke lim inn lange tekster i chatten.",
    "loved": "Loved er en ny sammfuns-basert rangeringssystem som gir maps som normalt ikke kan bli rangert en toppskår liste. [Https://osu.ppy.sh/news/151925254083 Les mer om det her!]",
    "mac": "[https://osx.ppy.sh Kjør osu! på Mac]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Mappere er travle folk, og det ligger en masse arbeid i mapping. Hvorfor ikke forsøke å mappe det selv?",
    "mapping": "Gå [https://osu.ppy.sh/forum/p/988111 hit] for guider om mapping.",
    "mat": "Mapping Assistanseteamet var en gammel brukergruppe som hjalp BAT i rankingsprosessen.\nRIP MAT 23.04.2013",
    "modhelp": "For alle dine spørsmål angående modding av beatmaps, gå over til #mapping!",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modding-køer]",
    "modreqs": "Vennligst gå til #modreqs for alle modding-forespørsler. Husk at BAT-medlemmer ikke alltid har tid og at de har andre folk som har sendt inn forespørsler først, så forsøk også å spørre normale brukere om å modde beatmaps du har laget. På forhånd takk.",
    "multi-invite": "For å invitere noen til flerspillerspillet ditt mens du er vert, kan du klikke på den ønskede brukeren innen for listen over brukere på nett (trykk F9) eller klikk på navnet deres i chatten og velg Inviter til spill",
    "multi-link": "",
    "multiaccounting": "Du burde virkelig, virkelig ikke lage flere kontoer. Du vil bli oppdaget, og du kan bli forstummet i en skikkelig lang period, eller til og med bannlyst!",
    "multiplayer": "Vennligst hold romannonser i #lobby.\nDersom det ikke finnes noen andre spillere som vil, hvorfor ikke spille solo og forsøke på nytt senere?",
    "mwc": "En verdensomspennende osu! Mania-turnering. Se denne [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 wiki-siden] for mer informasjon.",
    "nat": "",
    "news": "",
    "nightcore": "Kos deg med dine favoritt-beatmaps, på Nightcore vis!\nBare dobbeltklikk DoubleTime-modifikatoren for å avdekke Nightcore-modifikatoren! Den er funksjonsmessig identisk med DoubleTime så langt poengtelling angår.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Skriv /np for å fortelle folk hva slags sang du hører på eller hvilket map du spiller.",
    "nsfw": "Upassende samtaler tillates ikke. osu! er for folk av alle aldre, dermed ønskes det at du holder chatten ren, ellers kan du bli forstummet uten videre advarsel.",
    "osu": "#osu er for å snakke om osu!. Vennligst diskuter spillemåter der, og ikke i denne kanalen.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 Den offisielle tråden for osu!tablet!] - Les dette for all informasjon angående tegnebrettet, samt muligheter for forhåndsbestillinger.",
    "osu!talk": "osu!talk er et talkshow av deadbeat og Ztrot hvor de intervjuer medlemer av felleskapet og diskuterer hendelser som blant annet verdensmesterskapet. Hver episode er på teamspeak 3 serveren osu.corin.me; Q&A section. Mer information finner du  [https://osu.ppy.sh/forum/t/225111 her.]",
    "osucore": "En aprilspøk fra 2011. Alle maps ble satt til DoubleTime-fart som standard og fikk tonehøyden satt opp.\nDette kom senere tilbake some Nightcore-modifikatoren, som har de samme effektene som DoubleTime hadde den dagen.",
    "osu!droid": "",
    "osumania": "Vennligst benytt #osumania for osu!mania-relatert diskusjon.",
    "osustream": "[http://www.osustream.com osu!stream] er osu! for iOS-enheter, skapt og opprettholdt av vår alles kjære peppy!",
    "osz": "Beatmap-filformatet som du laster ned for at osu! skal pakke opp for spilling. osz-filer må alltid pakkes opp av osu! selv, ellers kan problemer oppstå!",
    "osz2": "Et nytt beatmap-filformat som vil bety at hver fil vil være kryptert, oppdatert og strømmet uavhengig av alle andre filer. osz2-filer vil ikke behøve å pakkes opp og vil alltid bevares som .osz2-filer i din sangmappe.",
    "owc": "En verdensomspennende osu!-turnering. [https://osu.ppy.sh/wiki/OWC Se denne tråden for mer informasjon.]",
    "peppy": "peppy er den ledende utvikleren av osu! og håndterer mesteparten av prosjektet på egenhånd.",
    "perfect": "Fikk du ikke den SS-ranken? Denne modifikatoren forsøker mappet igjen for deg hvis du gjør en eneste liten feil.\nDu kan finne den ved å høyreklikke eller dobbeltklikke på SuddenDeath i skjermen for valg av modifikatorer.",
    "ping": "Pong!",
    "pippi": "osu! sin maskott-figur!\nPippi-don er taiko (tromme)-versjonen av Pippi.",
    "piracy": "Du burde virkelig ikke diskutere piratkopier i chatten.\nDet er forbudt og du kan bli forstummet. ",
    "play-shortcuts": "Fullstendig liste over snarveistaster: [[Shortcut_Key_Reference]]",
    "pm": "For å sende en privat melding til noen, klikk på navnet til noen i chatten eller deres brukerpanel på skjermen med visning av brukere som er tilkoblet, deretter klikk Start Chat.\nDu kan også benytte deg av kommandoen /msg <brukernavn> <melding> eller enten bruke /chat <brukernavn> eller /query <brukernavn>, som vil åpne en separat fane i chatten. For raskt å svare på den siste private meldingen som ble sendt til deg, kan du bruke /r <melding>. Fjern < >, så klart.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance Points (pp) er hovedberegningen av ranking for osu! Klikk [https://osu.ppy.sh/wiki/Performance_Points her] for å finne ut mer info.",
    "pp-rework-lazer": "",
    "preview": "Et forhåndsvisningspunkt er punktet i sangen hvor den starter å spilles fra i skjermen for valg av sang.\nEt riktig forhåndsvisningspunkt er et punkt i sangen som representerer det godt, slik som starten på refrenget. Gå til Timing i verktøylinjen og klikk Set Current Position as Preview Point for å velge en.",
    "qat": "",
    "qualified": "Beatmap Nominators nominerer maps som kvalifiserte som er klar for rangering som du kan spille uten å få performance points.\nOm disse mappene ikkje har problemer og er kvalifisert for en veke, vil den bli rangert. Ellers så går det tilbake til pending og poengsummene vil bli fjerna.",
    "ranked": "En ranket beatmap er et beatmap som har blitt godkjent av samfunnet på nett.\nNår du spiller et ranket beatmap, vil poengsummen som skaffes fra den telles mot din totale akkumulerte rankede poengtelling.\nDisse maps har deres egne rankede ledertavler, og kan identifiseres ved et Hjerte-ikon.",
    "ranking-criteria": "For informasjon angående kriterier for ranking, vennligst sjekk ut wiki-artikkelen: [[RC]]",
    "redname": "Brukere med røde navn er enten fra [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] eller [https://osu.ppy.sh/wiki/QAT QAT].",
    "report": "Moderatorer er ikke alltid tilgjengelige; de er bare mennesker, så de kan ikke se på chatten hele dagen. I tilfellet du skulle se at noen gjør noe dumt og ingen moderator trer i handling, vennligst bruk !report.\nVennligst unngå å rapporter i en privatmelding til BanchoBot; bruk heller !report <bruker> <grunn>.",
    "report-abuse": "Vennligst unngå å sende flere rapporter på rad, det hjelper ikke med å bringe rettferdighet noe fortere. Blanke eller urimelige rapporter gjør heller ikke det. Faktisk er det slik at du kan ende opp forstummet i stedet siden du spammer chat-moderatorene.",
    "request": "Ser du etter noe å modde? Klikk [https://osu.ppy.sh/p/beatmaplist&r=8 her] eller skriv !request for en tilfeldig map-lenke.",
    "respect": "Vær respektfull for andre spillere.",
    "roll-abuse": "Vennligst ikke bruk !roll-kommandoen for ofte - det er meget trolig at det vil ende med at du blir forstummet!",
    "romaji": "Vennligst ikke bruk Romaji (Romanized Japanese) overdreven. Du kan bli tyst.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Dersom det ikke er noen flerspillerrom å delta i, hvorfor ikke lage din egen? Da kan du selv velge sangene, også!",
    "rp": "Du står fritt til å utføre rolespill i passende osu!-kanaler; men du burde forsikre deg om at du ikke forstyrrer andre folk i kanalen for mye.",
    "rules": "[https://osu.ppy.sh/wiki/no/Rules Offisielle regler]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "Det skjer til tider at osu! blir utsatt for DDoS-angrep. I løpet av denne tiden kan Bancho være ustabil eller umulig å nå.\nDersom du mistenker at dette har skjedd, sjekk [https://twitter.com/osustatus @osustatus] Twitter-feeden eller [https://status.ppy.sh/ dette] for mer informasjon.\nOm dette skjer, og du fremdeles kan snakke - fortsett som normalt. Det å bringe det opp som samtaleemne vil ikke få det til å forsvinne fortere.",
    "sb": "Guide for storyboarding: https://osu.ppy.sh/forum/t/1869\nHvordan en benytter seg av redigeringsverktøyet for storyboard: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "scorev2 er en ny poengsummeringsalgoritme som har en øvre poenggrense for alle spillmoduser på 1 million poeng, ekskludert spinnere og modifikasjoner.\nDen endrer også alle glidere slik at de krever samme timing som vanlige sirkler.",
    "scoring": "Hvordan osu! kalkulerer resultater: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "En forstummelse vil si at du vil være ute av stand til å snakke eller publisere innlegg på forumet, utenom i teknisk støtte.\nForstummelser starter med 5 minutter for første brudd, deretter fordobles det for hvert brudd etterpå. Særlig alvorlige brudd kan gjøre mye mer enn bare å fordoble den forrige forstummelsen, dog.\nForstummelser deles ut for de fleste eksempler på dårlig oppførsel, så bare følg reglene, så vil du være trygg.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Vanlige spørsmål om skinning]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Ikke la osu! holde deg oppe til klokka 4 om natta. Søvn er viktig for deg!]",
    "songs-not-appearing": "Hvis sangene dine ikke vises i menyen for valg av sang, prøv å trykke F5.",
    "spaces": "",
    "spam": "Vennligst ikke spam chatten - det er irriterende og kan gjøre deg forstummet...",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "For å se på at en annen spiller spiller, skriv /watch <brukernavn>, eller klikk på navnet deres i chatten eller på brukerpanelet deres og velg Start Spectating.\nForsikre deg om at du har det samme beatmappet som de spiller!",
    "spoiler": "Å avsløre handlingen i en anime, serie, manga, doujin, etc er forbudt, og kan få deg brakt til taushet.",
    "status": "For statusoppdateringer om osu!-systemet, vennligst referer til [http://twitter.com/osustatus @osustatus]. For server status information, se [https://status.ppy.sh her].",
    "store": "https://osu.ppy.sh/p/market Velkommen til osu!-markedet], stedet hvor du kan kjøpe kjempeflotte t-skjorter av osu!-design og andre kule ting!",
    "submit": "[https://osu.ppy.sh/wiki/Submission Vanlige spørsmål om innsending av beatmap]",
    "suck": "Ikke ta det så ille opp, osu! krever mye øvelse for å gjøre det bra! Det er nesten som et musikkinstrument...",
    "supporter": "Bli en [https://osu.ppy.sh/p/support osu!-supporter]",
    "supporter-please": "Ikkje spør andre personer om å gi deg supporter tag. [https://osu.ppy.sh/p/support Skaff deg det her i stedet!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Hvis muspekeren flyr riundt omkring i hytt og pine når du prøver å flytte rundt på den, sørg for at du har satt sensitiviteten i spillet til 1.00x. høyere sensitivitet kan du få ved å sette et mindre område på tegnebrettets område. Hvis muspekeren ikke flytter seg i det hele tatt, sørg for at direkte mus-input er skrudd av i instillinger. For flere relaterte problemer, [https://osu.ppy.sh/forum/t/87301 les dette.]",
    "tag": "I tag flerspillermodus, vil alle spillere bytte på å klikke på én combo på et beatmap av gangen. Det finnes ingen vinner eller taper, siden alle spiller på samme laget.\nVed spinnere så deltar alle spillere. Dersom til og med én spiller ikke klarer å fullføre spinneren, vil comboen startes på nytt. Hver spiller sin spinner-bonus blir lagt til i lagets resultat.",
    "taiko": "En japansk tromme omtalt i en spillserie laget av Bandai-Namco. osu! sin Taiko-modus simulerer disse spillene ved å eliminere beat-plasseringer, som tvinger spilleren til å fokusere kun på rytmen til beatmappet. [https://osu.ppy.sh/forum/t/4363 Her ser du hvordan man spiller!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Taiko-mapping guide]",
    "taiko-maps": "Du kan finne autentiske Taiko no Tatsujin maps [https://osu.ppy.sh/forum/t/5397 her.]",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Kunne du være så snill å droppe emnet og snakke om noe annet, nå?",
    "training": "[https://osu.ppy.sh/forum/t/4280 James trening]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "https://osu.ppy.sh/forum/t/109137 Liste over oppdaterte video-veiledninger angående osu! og mapping.] Du er velkommen til å skape dine egne og legge det til i tråden. [https://osu.ppy.sh/forum/t/60228 Liste over nyttige guider for mappere/moddere]",
    "twc": "En verdensomspennende osu! Taiko-turnering. [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ Se denne tråden for mer informasjon.]",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Vennligst bare bruk vanlige/standard symboler i denne chatten. Takk!",
    "upload-cap": "For å holde mappere dedikert til de maps de jobber på til enhver tid, er det en grense på hvor mange maps du kan ha under utvikling på en gang.\nIkke-supportere kan ha 3-6 aktive, og supportere kan ha 5-10 aktive, avhengig av mengden tidligere rangerte maps de har.",
    "utf8": "Vennligst sett IRC-klienten din til UTF-8 kodesettet slik at teksten din blir forstått av osu!-spillere og andre IRC-brukere.",
    "videogames": "Vennligst diskuter temaer som Touhou, Pokemon, SC, LoL, visuelle noveller og andre videospill-relaterte emner i #videogames.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Velkommen til osu! Dersom du har et problem eller et spørsmål som trenger et svar, spør de snille personene i #help! Ha det gøy!",
    "when": "Når det er klart.",
    "wiki": "[https://osu.ppy.sh/wiki/ osu!-Wiki] - Gjør den kjempebra!",
    "wiki-link": "Du kan linke til wiki-sider ved å omslutte wiki-oppføringens navn i dobbel parentes: [[ ]]\nSom eksempel: en lenke til [[Kudosu]] skapes ved å skrive Kudosu imellom [[ ]].",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 208 active FAQs (out of a possible 217) in the Norwegian (Norsk) language.",
    "completion": "The Norwegian (Norsk) FAQ as of last update is 95.85% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "MP-timer har blitt satt til 60 sekunder!"
}
