
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy pindutin ito] para makita ang \nosu! academy -  Dito makikita ang mga video tutorials tungkol sa osu!",
    "achievements": "Makakamit mo ang mga achievements sa pamamagitan ng mga espesyal na gawain tulad ng pagkuha ng matataas na combo sa isang kanta, o sa paglaro sa bawat beatmap ng isang theme pack. Makikita mo ang iyong mga achievements sa loob ng iyong profile. Ang ibang pangalan ng mga achievement ay maaaring gamitin bilang bakas sa pagkamit ng mga ito!",
    "add-skin": "Para magdagdag ng panibagong skin, i-download mo ito at idrag sa loob ng osu! window o kung di ay pindutin ito ng dalawang beses.",
    "advertising": "Ang pag-aadvertise ng kahit ano na walang kinalaman sa osu! ay pinagbabawal; pwede kang masilence.",
    "answer": "Kapag walang sumasagot sa iyong tanong, maaaring walang may alam! Kung may kinalaman ito sa osu!, subukan mong hanapin ito sa forums.",
    "appeal": "Para mag-apila ng silence, magpadala ng PM sa kahit sinumang admin kasama ng dahilan kung bakit nararapat ang pagpataw ng parusa. Kung ito'y tinanggap, matatanggal ito mula sa iyong profile at mawawala ang bisa ng pagka-silence. Paki-tandaan na ang pakaka-silence ay pinag-iisipang mabuti, kaya ang pag-aapila ay hindi nakakasiguro na ang parusa ay mawawala. Siguraduhin lamang na mayroong magandang rason o ebidensiya bago ito gawin.",
    "approved": "Ang Approved beatmap ay mga hindi rankable na beatmap (dahil sa haba, iskor, atbp.), ngunit nabatid itong maayos ng miyembro ng Beatmap Approval Team. Ang mga beatmaps na na-aprubahan na ay may sariling leaderboard, tulad ng ranked maps. Ang mga Approved maps ay makikita na may simbolong apoy at hindi puso.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "Marapating wag tanungin kung puwedeng magtanong. Sabihin kaagad dahil walang namang katuturang gawin mo ito.",
    "attention": "Tigilan mo yan at walang interesado sa sinasabi mo.",
    "avatar-change": "Mapapalitan mo ang iyong avatar [https://osu.ppy.sh/home/account/edit#avatar dito]",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Kamusta! Ako pala si BanchoBot!\nDahil bot ako, hindi ako makakapag-usap sa iyo. :(",
    "beatmapping": "Basahin ang [https://osu.ppy.sh/wiki/Beatmapping beatmapping!] para makakuha ng ilang payo.",
    "beginner": "Pindutin [https://osu.ppy.sh/forum/t/5456 ito] kung ikaw ay naghahanap ng beatmaps para sa mga baguhan.",
    "bn": "Ang [[Beatmap Nomination Group]] ay isang grupo ng mga tao na ang kanilang gawain ay nagrarank ng mga beatmaps at ang may responsibilidad sa moderation ng mga pending beatmaps sa ranking cycle.\nPwede mo silang kausapin kung may tanong kayo o kailangan ninyo ng mga payo tungkol sa mapping o modding.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Walang kwenta ang pagsasabi na ikaw ay tinatamad.]\nHuminto ka muna, o iba ang laruin mo.\n",
    "bug": "Kung sa tingin mo na meron kang natagpuang bug, puwede mo i-report [https://osu.ppy.sh/forum/5 dito].\nSiguraduhin muna na wala pang nag-post ng iyong problema.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Pakiusap na huwag gumamit palagi ng malaking letra sa unahan ng bawat salita. Hindi maganda tingnan ang puro malaking letra.",
    "caps": "Ang pag-gamit ng malalaking letra ay ipinagbabawal sa ingame chat at maaari kang ma-silence.",
    "change-modes": "Para magpalit sa ibang game modes, pumunta sa song selection screen at pindutin ang Mode sa timog-kanluran o kundi pindutin ang Ctrl tapos 1-4. Tandaan na merong mga maps na mode-specific!",
    "change-name": "Para mapalitan ang iyong username, dapat maging [https://osu.ppy.sh/p/support osu!supporter] ka muna. Tapos, pwede mo nang palitan [https://store.ppy.sh/store/product/32 dito]!\nKung gusto mong ibalik ang iyong lumang username, o magpagawa ng maliit na pagbabago, o tulong, magbigay ng mensahe sa accounts@ppy.sh kasama ang mga detalye.",
    "changelog": "Lahat ng mga pagbabago sa laro, Bancho at ang website ay makikita sa osu! development [https://osu.ppy.sh/p/changelog changelog!]",
    "chars": "Gumamit lang ng mga karaniwan titik sa general chat.",
    "charts": "Ang osu! charts ay nilalabas kada buwan. Ang mga ito ay pinagsama-sama na mapa na pinipili kada buwan o sumasangayon sa isang theme. Makikita mo ang mga ito [https://osu.ppy.sh/p/chart dito].",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Maputlang dilaw: Isang Karaniwang na user. Dilaw: Isang [https://osu.ppy.sh/p/support Supporter] Pula: Isang miyembro ng [https://osu.ppy.sh/wiki/NAT NAT] o [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT].\nPuti: Ikaw, o isang /me message. Bughaw: PM. Berde: Isang linyang kung saan nabanggit ang iyong username (highlight). Pink: BanchoBot",
    "colour": "Maputlang dilaw: Isang Karaniwang na user. Dilaw: Isang [https://osu.ppy.sh/p/support Supporter] Pula: Isang miyembro ng [https://osu.ppy.sh/wiki/NAT NAT] o [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT].\nPuti: Ikaw, o isang /me message. Bughaw: PM. Berde: Isang linyang kung saan nabanggit ang iyong username (highlight). Pink: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Habang ang mga chat commands ay madaling gamitin, huwag itong iabuso. \nIto ay isinasaalang-alang bilang spam, at pwedeng maaaring magresulta sa isang silence.",
    "comment": "Para mag-comment sa beatmap, i-click ang tab na Discussion sa kanan habang nasa replay mode. Pindutin ang box kung saan mo gustong gumawa ng comment mo, tapos lagay mo kung ano gusto mong sabihin tapos pindutin mo yung Enter. Pag hindi mo kita yung comments, click mo yung Show Comments. Ingat kapatid, may mga map na maraming comments baka hindi mo makita yung gameplay.",
    "comment-color": "Ang normal na user ay pwede lang mag comment gamit ang puting kulay. Ang mga [https://osu.ppy.sh/p/support supporter] ay pwedeng gumamit ng ibang kulay.\n",
    "conferencemode": "Ikaw ba ay nalulunod na sa mga Join/Quit na mensahe sa IRC? Baka makatulong [http://wiki.xkcd.com/irc/Hide_join_part_messages ito].",
    "country-ranking": "[https://osu.ppy.sh/p/countryranking Country Ranking tingin lang baka natalo mo pa pro natin]",
    "critic": "Tandaan na ang pamumuna ay dapat nagbibigay ng liwanag. Magbigay ng paraan para maayos ang mga isyu kung saan ka nag-aalala",
    "ctb": "May tanong ka tungkol sa Catch the Beat? Subukan mong [https://osu.ppy.sh/forum/p/60690 basahin ang wiki.]",
    "cutting-edge": "Ang Cutting-edge ay ang update stream na pumalit sa lumang osu!test build.\nPwede mong [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues basahin itong article] kung may problema ka sa pag-update ng iyong client.",
    "cwc": "Isang worldwide osu! Catch the Beat Tournament. [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 Basahin to para sa ibang impormasyon].",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Huwag manggulo sa iba. ",
    "disable-this": "Bihirang magkaroon ng toggle para sa bagong feature. Pwede kang humiling ng toggle sa  [https://osu.ppy.sh/forum/4 Feature Requests].",
    "distance-snap": "Ang relatibong distansiya sa pagitan ng nota ay ma-iaayos gamit ang Distance Snap. May karagdagang impormasyon dito: [[Distance Snap]]",
    "dont-ask-peppy": "Pakiusap, wag mo tanungin si peppy. May ibang tao na makakasagot sa tanong mo.",
    "douche": "Bilang isang catch-all safeguard, ang paghanap ng loopholes sa batas ay pinagbabawalan. Ang opisyal na batas na nagsasabi na huwag maging isang douche ay dapat hindi mo kailangan maging isang douche. Pero just in case: huwag maging isang douche.",
    "download": "Pwede kang magdownload ng beatmaps [https://osu.ppy.sh/p/beatmaplist dito] at beatmap packs [https://osu.ppy.sh/beatmaps/packs dito].\nKung hindi alam kung paano mag-import, [http://i.imgur.com/kpX2N3m.jpg basahin ito.]",
    "drugs": "Pagtalakay sa droga o paggamit ng droga saanman sa osu! ay ipinagbabawal. Ang larong ito ay para sa pangkalahatang edad.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Basahin ang [[Beatmapping#Keyboard_Shortcuts]] para mahanap ang listahan ng editor shortcuts",
    "english": "Ang #english channel ay para sa mga general discussion tungkol sa kahit ano na walang dedicated na channel.\nKasama dito ang anime o manga.",
    "evade": "Ang pag-iwas sa pag-silence ay isang bannable na offense. Wag mo itong gawin! Use your kokote!",
    "fallback": "Ang Stable (Fallback) ay makalumang gawa na ng osu! Di gaya ng Fallback, ang mga bagong releases ay walang suporta sa DirectX upang maging mas simple ang ating framework. Kung ikaw ay nagpalit sa gawa na ito, ang PC mo ay low-end at hindi kayang i-suporta ang pinakabago at susunod pang client versions. Kung gusto mo maglaro gamit ang mga kasalukuyang gawa ngayon, update mo ang iyong graphic cards at gawing itong may suporta sa OpenGL, ang pinaka-kailangan na pamuno sa mga gawa na iyon. [https://osu.ppy.sh/wiki/GL_Support_Issues Pindutin ito para malaman kung paano.]",
    "faq": "Ginagamit mo ngayon ang osu!Bancho FAQ system.\nosu!wiki: https://osu.ppy.sh/wiki",
    "feature": "Kung may naisip kang idea para sa laro na ito, ipost mo ito sa [https://osu.ppy.sh/forum/4 Feature Requests] subforum.\nSiguraduhin mong nabasa mo na ang [https://osu.ppy.sh/forum/t/454006 forum guidelines] nito!",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Ang pag-iwas sa mga chat filters ay ipinagbabawal. Huwag mo itong gawin.\n",
    "foul-play": "I-report ang mga manduruga gamit ang report button sa kanilang profile, makikita [https://i.imgur.com/GG9xlLA.png dito].\nSiguraduhin na makapagbibigay ka ng malaking detalye. Pwede ka rin magreport sa top 50 leaderbords ng pahina ng beatmap.",
    "percolate": "Ang pag-iwas sa mga chat filters ay ipinagbabawal. Huwag mo itong gawin.\n",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Ang artikulong ito] ay makakatulong sa iyo para maunawaan ang mapping flow.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Upang magdagdag ng manlalaro bilang isang kaibigan, i-type mo ang /addfriend at sinusundan ng pangalan ng manlalaro.\nMaaari mo ring pindutin ang panel ng manglalaro sa loob ng Online Users list (pindutin ang F9) o ang kanyang pangalan sa chat at pindutin ang Add as Friend.\nIsa pang maaari mong gawin ay ang pagpindot ng Add as Friend sa loob ng kanilang profile.",
    "friends-list": "Upang makita ang online friends mo in-game, pindutin ang F9 at palitan yung filter sa taas at i-click ang Friends.\nMaaari mo ring makita ang buong listahan ng iyong mga kaibigan [https://osu.ppy.sh/home/friends dito]. Siguraduhin na ikaw ay naka-log in.",
    "fullscreen": "Maaari mong baguhin kung ang laro ay naglalaro ng Windowed o Fullscreen sa ilalim ng seksyong Graphics ng Options.\nMaaari mo ring lumipat sa o mula sa fullscreen gamit ang Alt + Enter ng iyong keyboard.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Hindi mo ba maintindihan ang mga terminolohiyo na sinasabi dito? Basahin mo ang glossary sa wiki: [[glossary]]",
    "gmt": "Ang [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team] o GMT, ay isang grupo na tumutulong mapagana ang osu!. Pula ang pangalan nila sa chat, habang luntian naman sa forums. Sila din ay tumutulong magmoderate sa forum at chat.",
    "english-help": "[http:osu.ppy.sh/forum/t/12016 Napakadali, kahit ikaw kaya mo...Sa tingin ko.]",
    "grammar": "Panatiliing maayos ang iyong gramatika sa loob ng chat. Kaunting mali sa pagkakabaybay o sa bantas ay maaaring tanggapin, ngunit iwasang gumamit ng shorthand o textspeak (kilala bilang jejemon, leet, et al.) Magmumukha ka lamang katawa-tawa.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Hindi ka ba marunong maglaro? Gusto mo bang maranasan ang mapping at modding? May mga gabay [https://osu.ppy.sh/wiki/Guides dito]",
    "hacked": "Kung sa tingin mo ay nahack ang iyong account, mag-email sa accounts@ppy.sh.\nKapag hindi ito nagawa, maaaring mawala ang account mo.",
    "hard": "Galingan mo, scrub.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Kung ikaw ay nangangailangan ng tulong sa kahit anong tungkol sa osu! punta ka sa #help channel at doon magtanong.",
    "hitsound-library": "Bisitahin mo [https://osu.ppy.sh/forum/p/164927 ito]para makakuha ka ng custom na mga hitsound para sa iyong beatmap.",
    "hl": "Wag kang magreklamo sa highlighted na salitang idinagdag mo sa iyong username. Kasalanan mo na naha-highlight ka. Kung hindi mo ito gusto, tanggalin mo na lang ang salita.",
    "how-to-get-modded": "Para malaman mo kung pano makita ang iyong map, basahin ito: [[Getting_Your_Map_Modded]]",
    "how-to-bn": "Kung gusto mo maging BN, basahin [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator ito].\n",
    "how-to-gmt": "May proceso kung paano pinipili ang GMT, base sa nagawa nila para sa komunidad. Basahin ito:  [https://osu.ppy.sh/wiki/People/The_Team/Global_Moderation_Team Global Moderation Team]",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#how-to-play? Basahin ito para malaman kung pano maglaro!]",
    "how-to-rank": "Basahin mo ang [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Ang Hyperdash ay mangyayari kung nakuha mo yung prutas na may pulang ilaw. Bibilis ang dash mo dito. Mawawala ito pagkakuha mo ng susunod na prutas o na-miss mo ito.",
    "ignore": "Kung ayaw mong makita ang mga mensahe galing sa isang user, i-type ang /ignore username. Hindi mo rin makikita ang mga PM nila sayo. Para makita ulit ang mensahe nila, i-type ang /unignore username, o isara ang osu!. Para hindi makarinig mula sa isang user habang-buhay, basahin [http://help.ppy.sh/article/141/how-do-i-completely-block-another-user-from-contacting-me ito].",
    "import": "[http://i.imgur.com/kpX2N3m.jpg Basahin ito para malaman kung paano mag-import ng mga beatmap sa osu!]",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Kapag tsinek ang box na Inherit previous timing settings in F6 window ng Editor, ang timing session ay hindi makaka-apekto sa timing, magandang gamitin ito sa seksyon na nagbabago ang volume o sample ng mapa. At, ito'y possible na ma-inherit ang timing sections kung saan doble o kalahati ang BPM. Kung sanay ka gumamit ng timing section sa gantong paraan, gamitin ito!.",
    "irc": "IRC server: irc.ppy.sh\nPort: 6667\nPassword: https://osu.ppy.sh/p/irc",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Pwede mong palitan ang iyong keyboard bindings sa input section ng options.\nAng mga pindutan at layout para sa osu!mania ay mapapalitan sa osu!mania layout",
    "kiai": "Ang Kiai mode ay isang style ng effect na pwede mong gamitin sa timing sections gamit ang Timing Setup Panel. Timing sections na may kiai mode ay maaring makapaglagay ng maraming biswal na epekto para magawa ang beatmap na mas epik. Pakisiguro na gamitin ito ng maayos.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Magipon ng [https://osu.ppy.sh/wiki/Kudosu kudosu] sa pamamagitan ng pag-mod sa beatmap ng ilang manlalaro.",
    "lag": "Ang lag ay isang termino na magagamit upang masabi kung ano ang problema kahit saan sa kahit anong bagay. Kung magrereklamo tungkol sa lag, sabihin kung saan eksakto kung saan yung lag nanyayari at ano ang pinagmulan(internet lag? walang matinong ISP. graphical freeze? slow framerate? upgrade pc na yan or laptop upgrade na yan~. input lag? brain lag? I-memoplus gold mo yan) At paki sabi kailan nanyari yung lag, kung may espesyal na kondisyon para nanyari iyon at kung may idea ka kung ano ang pinagmulan nun. Pakisiguro na walang problema sa PC mo(kung bulok ba o ano), na maaring maka-apekto sa CPU/memory/disk usage.",
    "language": "Maging magalang sa chat room.",
    "language-specific": "",
    "lazer": "",
    "level": "Ang iyong level ay nakabatay sa iyong total accumulated score. Kasali na rito ang lahat na nakaranggong iskor, pumasa man o hindi. Tataas ang level mo sa pamamagitan ng paglalarao ng osu!",
    "lines": "Pakiusap, matutong magtype sa isang linya lamang para maiwasang masilence.",
    "link": "Para makagawa ng link sa isang bagay gamitin ang ganitong pormat: [address text], kung saan ang address ay ang link at text kung ano ang gusto mong text na ipakita [https://osu.ppy.sh/ Tulad nito!] Huwag kalimutan ang http://. Ang maling gamit ng ganitong feature tulad ng paglilink sa maling nilalaman o pag hihilight ng mga tao gamit ang hidden text ay may parusa",
    "lobby": "\nGamitin ang #lobby para sa pag-aanunsiyo ng inyong mga laro at ito ay isang channel na pwede ang iba't ibang wika.\nGamitin ang inyong #multiplayer channel sa iba pang mga tema.\n",
    "localisation": "[https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 Nandito] ang osu! Localisation project. ",
    "long-link": "Huwag maglagay ng mahahabang links sa chat! Gamitin ang [link text] formula kapag kailangan.",
    "long-text": "Pakiusap, wag mag-paste ng mahahabang sulat sa chat.\nMauuwi ito sa isang silence kapag ipinagpatuloy mo ito",
    "loved": "Loved ay isang community-based na ranking status na nagbibigay ng buong scoreboards sa mapang hindi pwede irank. [https://osu.ppy.sh/news/151925254083 Basahin dito para sa iba pang detalye!]",
    "mac": "[https://osx.ppy.sh Patakbuhin ang osu! sa iyong Mac]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Ang mga mappers ay mga abalang tao, at ang pagma-map ay isang mabigat na bagay. Ang mga requests ay hindi agad mapupuno.",
    "mapping": "Pumunta [https://osu.ppy.sh/forum/p/988111 rito] para sa mga gabay sa mapping.",
    "mat": "Ang Mapping Assistance Team (MAT) ay isang lumang grupo na tumulong sa mga BAT sa proseso ng pagra-rank ng beatmap.\nRIP MAT 2013-04-23",
    "modhelp": "Para sa lahat ng mga beatmap modding queres, pumunta ka lang sa #mapping!",
    "modqueue": "[https://osu.ppy.sh/forum/60 Mga Modding Queues]",
    "modreqs": "Pumunta sa #modreqs para sa kahit anong modding requests mo. Pakitandaan ang mga BN ay hindi lagi may oras at may mga nauna pang tao na nagrequest, Pakisigurado na magpa-mod sa mga regular na manlalaro ang iyong mga beatmap. Salamat.",
    "multi-invite": "Para maimbitahan ang isang tao sa iyong multiplayer game habang ikaw ay host ng room, i-click mo sila sa online users list at piliin ang Invite to game.",
    "multi-link": "",
    "multiaccounting": "Talagang hindi ka dapat gumawa ng maraming mga account. Mahahanap ka, at maaari kang ma-silence sa isang seryosong mahabang oras, o kahit na pinagbawalan. ",
    "multiplayer": "Huwag mag-anunsiyo ng inyong mga multiplayer rooms sa kahit anong channel maliban sa #lobby.\n",
    "mwc": "Isang worldwide osu! Mania tournament. Tignan itong [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 pahina ng wiki] sa iba pang impormasyon.",
    "nat": "Ang [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] ay nag-moderate sa Beatmap Nominators at nangangasiwa sa proseso ng Beatmap Ranking.\nSila ang responsable para sa pagsusuri ng kasalukuyan at naghahangad na mga Beatmap Nominators, pati na rin ang pamamagitan ng mga mediam na beatmap vetoe at iba pang hindi pagkakaunawaan sa mapping / modding.  ",
    "news": "",
    "nightcore": "Enjoy mo ang iyong paboritong beatmaps Nightcore style! Simpleng i-double click ang DoubleTime mod para ipakita ang Nightcore mod!",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "I-type ang /np upang ipaalam sa iba kung anong kanta ang iyong pinakikinggan o kung anong map ang iyong nilalaro.",
    "nsfw": "Pinagbabawalan dito sa osu! ang mga usapang hindi pwede sa mga bata kaya dapat gawing malinis ang chat o kayo ay mabibigyan ng silence na walang warning.",
    "osu": "Ang #osu ay para sa mga talakayan tungkol sa osu!. Doon mag-usap tungkol sa mga gameplay, hindi dito.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 Ang osu!tablet official thread!] - Basahin ito para sa lahat ng impormasyon tungkol sa tablet at ang preorder options.",
    "osu!talk": "Ang osu!talk ay isang talk show na pinaghandaan nila deadbeat at ztrot kung saan sila ay kumukuha ng panayam sa mga miyembro ng komyunidad at pag-usapan ang mga pagligsahan katulad ng mga world cups.\nKada episode ay ginaganap sa teamspeak 3 server osu.corin.me; pwede kang magtanong sa loob ng Q&A section. Marami pang impormasyon na mahahnap [https://osu.ppy.sh/forum/t/225111 dito.]",
    "osucore": "Isang April Fool's joke noong 2011. Lahat ng maps ay na set sa DoubleTime speed ng kusa at tumaas ang mga pitch nito. \nIto ay bumalik bilang Nightcore mod kung saan kaparehas na epekto ng DoubleTime noon.",
    "osu!droid": "",
    "osumania": "Gamitin ang #osumania para sa usapan tungkol sa osu!mania.",
    "osustream": "[http://www.osustream.com Ang osu!stream] ay osu! para sa iOS devices, gawa at pinapanatili ng natatangi nating peppy!",
    "osz": "Ang beatmap file format na dinadownload mo para sa osu! para i-extract at laruin ito. Ang .osz files ay laging ine-extract ng osu! at sarili nito o baka magkaproblema ito!",
    "osz2": "Ang bagong beatmap file format kung saan nangangahulugang may laman na file na encrypted, updated at streamed na magkakahiwalay sa ibang files. Ang mga osz2 files ay hindi nangangailangang na mai-extracted at laging maiiwan bilang .osz2 files sa iyong Songs folder.",
    "owc": "Isang malawakang osu! tournament [https://osu.ppy.sh/wiki/OWC Tingan mo to para sa ibang impormasyon.]",
    "peppy": "Si peppy ang lead developer ng osu! at siya ang humahawak sa halos lahat ng mga proyekto nang mag-isa.",
    "perfect": "Hindi mo na-SS? Ang mod na ito ay magreretry para sayo kung ikaw ay nagkamali kahit isa. \nMakikita mo ito kung ido-double click mo ang SuddenDeath sa mod selection screen.",
    "ping": "Pong!",
    "pippi": "Ang maskot ng osu! \nSi Pippi-don ay ang (drum) version ni Pippi.",
    "piracy": "Huwag pag-usapan ang mga piratang materyal sa chat.",
    "play-shortcuts": "Listahan ng mga shortcut keys : [[Shortcut_Key_Reference]]",
    "pm": "Para magpadala ng pribadong mensahe sa isang tao, i-click ang taong iyon sa chat o sa kanilang user panel sa Online Users at I-click ang Start Chat. \nPwede mo ring gamitin ang command na /msg <username> <message> o gamitin ang /chat <username> o /query <username>, na ito'y magbubukas sa nakahiwalay na tab sa chat. \nPara magreply sa nakaraang mensahe na pinadala sayo, pwede mong gamitin ang /r <message> . Tanggalin ang < >, siyempre.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "[https://osu.ppy.sh/wiki/Performance_Points Performance Points] (pp) ang pangunahing ranking na binabase sa osu!",
    "pp-rework-lazer": "",
    "preview": "Ang preview point ay point na kung saan sa isang kanta na ito'y magu-umpisang tumugtog sa iyong song selection screen. \nAng tamang  preview point  ay point sa kanta na mapapakita ito ng maayos, tulad ng paglabas ng chorus. Pumunta sa timing toolbar at i-click ang Set Current Position as Preview Point para pumili ang isa.",
    "qat": "",
    "qualified": "Ito nang kinabukasan ng modding system! Itong mga maps ay pinili ng mga tao na handa para sa ranking. Pwede ka agad makakuha ng ranks (na walang performance points) pero ito ay nasa qualified na status hanggang isang linggo. \nHabang nasa oras na ito, merong malaking pagkakataon na ito ay babalik sa pending kung may nahanap na isyu na may epekto sa paglalaro at ang mga scores ay malilinis. Kung walang, ito ay magiging ranked na kapag lumipas ng isang linggo.",
    "ranked": "Ang isang ranked na beatmap ay isang beatmap kung saan na aprubahan ng online community. \nKapag ika'y naglaro ng isang Ranked map, ang score mo ay makukuha dito at mabibilang sa total na nakuhang ranked score. \nAng mga map na ito ay may sariling ranked leaderboard at mapapansin na may Heart o Puso na icon.",
    "ranking-criteria": "Para malaman ang impormasyon sa ranking criteria, visitahin ang wiki: [[RC]]",
    "redname": "Ang mga user na may pulang pangalan ay maaaring isang miyembro ng [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] o miyembro ng [https://osu.ppy.sh/wiki/NAT NAT]. ",
    "report": "Gamitin ang sinusunod na format para magreport ng hindi kanais nais na bagay o panduruga: !report <pangalan> <rason>\nAng mga report ay hindi makikita ng ibang tao at dapat gamitin sa publikong channel Huwag itong gamitin sa PM.\nPwede ka rin magreport sa pamamagitan ng pagclick sa pangalan ng tao at pipiliin ang Report User",
    "report-abuse": "Paki-iwasan ang pagpapadala ng maramihang report, hindi ito makakatulong ng pagpapabilis ng hustiya. Kahit blanko o walang kwentang report. Sa bagay, sa huli masa-silene ka sa pagspam ng chat moderator. ",
    "request": "Naghahanap ng pwedeng i-mod? Click [https://osu.ppy.sh/p/beatmaplist&r=8 mo ito] o i-type ang !request para makakuha ng random na map link.",
    "respect": "Magbigay galang sa mga ibang manlalaro.",
    "roll-abuse": "Huwag lang po abusuhin ang !roll. Maaari kang ma-silence dahil diyan.",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Kung walang multiplayer room na pwedeng masalihan, bakit ayaw mong gumawa ng sarili mo? Tapos makakapili ka pa ng songs!",
    "rp": "Malaya kang mag-roleplay sa tamang osu! channel; ngunit, siguraduhin mo na hindi ka masyadong makakaabala sa iba.",
    "rules": "[https://osu.ppy.sh/wiki/Rules Opisyal na batas]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "Habang tumatakbo ang oras, nakakakuha ng DDoS ang osu!. Sa ngayong oras, ang Bancho ay pwede maging unstable at hindi mahanap. Kung naiisip mo na ito ay nangyayari, tignan ang [https://twitter.com/osustatus @osustatus] Twitter feed o [https://status.ppy.sh ito] para sa impormasyon. Kung ito ay nangyari, at nakakapagsalita ka pa rin sa chat, ituloy mo lang. Wala ka ring magagawa kung ito ay pinagsabi mo sa chat.",
    "sb": "Mga gabay para sa Storyboarding: https://osu.ppy.sh/forum/t/1869 Paano gumamit ng Storyboard Editor: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "ang scorev2 ay isang bagong algorihm na lahat ng scores para sa lahat ng game modes ay hindi hihigit sa isang milyong puntos. Hindi kasama rito ang spinners at mods.\nPinapalit rin nito ang ugali ng mga sliders para kailangan nito ang timing na parehas sa hit circles.",
    "scoring": "Paano nagkakalkula ang osu! [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Ang silence ay nangangahulugang hindi ka pwedeng mag-chat o magpost sa forum, maliban sa Technical Support. Ang mga silences ay nagtatagal ng limang (5) minuto sa unang paglabag, at ito'y dodoble kung ipagpapatuloy. Ang malaking infraction ay mas higit pa sa double ng nakaraang silence. Ang mga silence ay nabibigay sa di wastong pag-uugali.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Ang Skinning FAQ]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Huwag pagpuyatan ang osu! hanggang alas kwatro ng madaling araw. Mahalaga ang tulog.]",
    "songs-not-appearing": "Kung ang iyong mga kanta ay hindi lumalabas sa song select menu, subukan mong pindutin ang F5",
    "spaces": "Huwag maglagay ng espasyo sa gitna ng kada letra, ang chat ay nagiging magulo dahil sa iyong aesthetics at mapupunta sa silence.",
    "spam": "Ang pagsa-spam sa chat ay isang paglabag na maaaring mauwi sa isang silence. 'Wag mo itong gawin.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Para manood ng ibang player, i-type sa chat ang /watch <pangalan ng panonooran> o i-click ang pangalan nila sa chat o sa user panel (F9 mode) at i-select ang Start Spectating Siguraduhin meron ka din ng beatmap nila.",
    "spoiler": "Ang pagspoil ng kahit anong anime, series, manga, atbp. ay pinagbabawal at pwedeng mauwi sa silence.\n",
    "status": "Para sa osu! system status updates, pumunta sa [http://twitter.com/osustatus @osustatus]",
    "store": "[http://store.ppy.sh/ Welcome sa osu! store], ang lugar kung saan mo mahahanap ang astig na kagamitan ng osu!",
    "submit": "[https://osu.ppy.sh/wiki/Submission Mga katanungan sa Beatmap Submission FAQ]",
    "suck": "Gagaling din kayo, practice lang.",
    "supporter": "Maging isang [https://osu.ppy.sh/p/support osu! supporter]! Makakakuha ka ng extra benefits, at makakatulog sa pagsuporta sa development team!",
    "supporter-please": "Pakiusap lang na huwag magtanong sa mga ibang tao na i-regalo ka ng supporter tag. [https://osu.ppy.sh/p/support Embes, kunin mo nalang dito!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Kung ang iyong cursor ay lumilipad kung saan saan kung ito ay galawin mo, siguraduhin na ang iyong sensitivity sa laro ay 1.00x. Malalaking sensitivity ay pwede mong makuha sa pamamagitan ng pagliit ng active area ng iyong tablet.\nKung ang iyong curor ay hindi talaga gumagalaw, siguraduhin na nakapatay ang Raw Input sa options.\nPara sa mga iba pang isyu sa tablet, [https://osu.ppy.sh/forum/t/87301 basahin itong thread].",
    "tag": "Sa tag multiplayer mode, lahat ng manlalaro ay salit-salitan sa pag click ng isang combo ng beatmap. Walang mananalo o matatalo dahil lahat ay naglalaro sa isang team, Sa spinners lahat ay magpaparticipate. Kung ang isa ay pumalya sa pag-clear ng spinner, magre-reset ang combo. Lahat ng spinner bonus ng mga manlalaro ay na-aadd sa team score.",
    "taiko": "Isang Hapong tambol na ibinida sa isang serye ng mga laro ng Bandai-Namco. Ang Taiko Mode ng osu! ay nagsi-simulate nga mga larong ito sa pamamagitan ng pagtatangal ng beat placement, upang pwesahan ang pagpo-pokus ng mga manlalaro sa ritmo ng beatmap.\n[https://osu.ppy.sh/forum/t/4363 Ganito kung paano maglaro!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Taiko mapping guide ba kamo?]",
    "taiko-maps": "Makakakita ka ng mga karagdagang Taiko no Tatsuijin maps [https://osu.ppy.sh/forum/t/5397 dito]",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Pwede bang iba nalang pag-usapan niyo?",
    "training": "[https://osu.ppy.sh/forum/t/4280 Training ni James]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 List ng up-to-date video tutorials sa osu! at pagma-map.] Try mo gumawa ng sarili mo at i-submit sa topic. [https://osu.ppy.sh/forum/t/60228 Listahan ng nakakatulong na direksyon para sa mga mappers/modders]",
    "twc": "Isang pandaigdigang osu! Taiko tournament [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ Tingnan mo ito para sa iba pang impormasyon]",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Gumamit lang ng mga normal na characters sa general chat.",
    "upload-cap": "May nakalaang bilang ng mga puwedeng i-upload na maps para mahayaan ang mappers na maging tiyak sa kanilang ginawang map. Ang hindi supporter ay mula 3 at 6 na hindi ranked maps. Ang mga supporter/subscriber naman ay may mas malaki; mula 5 hanggang 10 na hindi ranked maps",
    "utf8": "Paki-set yung IRC client mo sa UTF-8 codepage para maintindihan ang iyong sinasabi ng mga manlalaro ng osu! at iba pang IRC users.",
    "videogames": "Ang mga usapan tungkol sa videogames ay pwedeng gawin sa #osu pero kung nakakaistorbo ito o may ibang pinag-uusapan, doon ka na lang sa #videogames\n",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Maligayang pagdating sa osu! Kung may tanong o problema ka, bisitahin ang #help. Magsaya ka!",
    "when": "Kapag handa na.",
    "wiki": "[https://osu.ppy.sh/wiki/ The osu! Wiki] - Gawin itong astig!",
    "wiki-link": "Pwede ka mag-link ng pages sa pamamagitan ng wiki entry name sa pagitan ng [[...]‌] Halimbawa: ang [[Kudosu]] ay nagagawa sa pamamagitan ng pagsulat ng Kudosu sa gitna ng double [[ at ]‌].",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 208 active FAQs (out of a possible 217) in the Filipino (Tagalog) language.",
    "completion": "The Filipino (Tagalog) FAQ as of last update is 95.85% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
