
strings = {

    "academy": "[http://www.youtube.com/user/osuacademy Kliknij tutaj] Aby przejść do Akademii osu! - poradników dotyczących podstaw osu!",
    "achievements": "Osiągnięcia uzyskiwane są poprzez wykonanie pewnych zadań, takich jak osiągnięcie odpowiednio wysokiego combo lub zagranie każdej beatmapy z paczki tematycznej. \nOsiągnięcia możesz obejrzeć na swoim profilu. Dla większości osiągnięć wymagania są z góry wiadome, niektóre musisz rozpracować samemu.",
    "add-skin": "Aby dodać do gry nową skórkę, pobierz ją i przeciągnij do okna gry albo kliknij na nią dwukrotnie.",
    "advertising": "Reklamowanie rzeczy niezwiązanych z osu! jest zabronione i może się zakończyć uciszeniem.",
    "answer": "Jeśli nikt nie odpowiada na twoje pytanie to może oznaczać, że nikt nie zna na nie odpowiedzi. Poszukaj na forum jeżeli pytanie jest związane z grą.",
    "appeal": "Jeśli uważasz, że uciszono cię niesłusznie, skontaktuj się z administratorami wysyłając e-mail wyjaśniający sytuację na accounts@ppy.sh. Przy tym pamiętaj, że admini to też ludzie! Bycie dla nich miłym na pewno pomoże w rozwiązaniu twojego problemu.",
    "approved": "Jeśli uważasz, że uciszono cię niesłusznie, skontaktuj się z administratorami wysyłając e-mail wyjaśniający sytuację na accounts@ppy.sh. Przy tym pamiętaj, że admini to też ludzie! Bycie dla nich miłym na pewno pomoże w rozwiązaniu twojego problemu.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire, dawny, wysokopoziomowy beatmappingowy konkurs, powraca w 2017 wraz z piosenką od Hellblinde. [http://osu.ppy.sh/news/156171674413 Dowiedz się więcej tutaj!]",
    "ask": "Najlepszym sposobem na uzyskanie odpowiedzi jest po prostu zapytanie - nie pytaj, czy możesz pytać!",
    "attention": "Czy mógłbyś przestać? Naprawdę nikt Cię nie słucha...",
    "avatar-change": "Możesz zmienić swój avatar [https://osu.ppy.sh/home/account/edit#avatar tutaj].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Witaj! Jestem BanchoBot! Miło mi cię poznać! Niestety jestem tylko robotem, więc nie mogę z tobą rozmawiać :(",
    "beatmapping": "Przydatne porady dotyczące mapowania znajdziesz [https://osu.ppy.sh/wiki/Beatmapping tutaj].",
    "beginner": "Kliknij [https://osu.ppy.sh/forum/t/5456 tutaj], jeżeli szukasz map dla nowicjuszy.",
    "bn": "[[PL:Beatmap Nomination Group]] to grupa ludzi, którzy czuwają nad procesem rankingowania map. Do ich zadań należy moderowanie beatmap, które rozpoczynają swój proces rankingowania.\nMożesz z nimi porozmawiać, jeżeli chcesz zapytać o mappowanie i moddowanie, albo jeśli potrzebujesz zasięgnąć co do tego rady.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Jeśli naprawdę Ci się nudzi, znajdź sobie inne zajęcie. Nuda to nie powód do marudzenia lub spamowania na osu!].",
    "bug": "Zgłaszaj błędy na [https://osu.ppy.sh/forum/5 forum], nie na czacie. Tylko upewnij się najpierw, że ktoś nie zgłosił ich już wcześniej.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Nie pisz każdego słowa wielką literą. Tego się nie da czytać.",
    "caps": "Staraj się nie używać wielkich liter w całym wyrazie, gdyż może skończyć się to uciszeniem.",
    "change-modes": "Aby zmienić tryb gry, przejdź do menu wyboru beatmapy i kliknij przycisk Mode'' w dolnej części ekranu lub użyj kombinacji klawiszy Ctrl + 1-4. Pamiętaj, że niektóre beatmapy grać można tylko w określonym trybie. ",
    "change-name": "Aby zmienić swój nick, najpierw musisz wykupić usługę [https://osu.ppy.sh/p/support osu! supporter]. Zmiany możesz dokonać [https://store.ppy.sh/store/product/32 tutaj]. Jeśli chcesz odzyskać swój dawny nick, wprowadzić jakieś małe zmiany lub po prostu potrzebujesz pomocy, napisz o tym na adres accounts@ppy.sh",
    "changelog": "Informacje o wszystkich aktualizacjach gry, Bancho i strony internetowej znajdziesz\n[https://osu.ppy.sh/p/changelog tutaj].",
    "chars": "Unikaj korzystania ze znaków niestandardowych, nie należących do alfabetu czatu, w którym rozmawiasz.",
    "charts": "Listy przebojów osu! (osu! charts) to tematyczne paczki beatmap, które publikowane są co miesiąc. Znajdziesz je [https://osu.ppy.sh/p/chart tutaj]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Jasnożółty: Normalny użytkownik | Żółty: [https://osu.ppy.sh/p/support Donator] | Pomarańczowo-czerwony:  Członek [https://osu.ppy.sh/wiki/NAT NAT] lub [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] | Biały: Twój tekst lub komenda /me | Ciemnoniebieski: Prywatna wiadomość | Zielony: Linia zawierająca twój nick (podświetlenie) | Różowy: BanchoBot",
    "colour": "Jasnożółty: Normalny użytkownik | Żółty: [https://osu.ppy.sh/p/support Donator] | Pomarańczowo-czerwony:  Członek [https://osu.ppy.sh/wiki/NAT NAT] lub [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] | Biały: Twój tekst lub komenda /me | Ciemnoniebieski: Prywatna wiadomość | Zielony: Linia zawierająca twój nick (podświetlenie) | Różowy: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Komendy są użyteczne, lecz nadużywanie ich może zostać uznane za spam i może być podstawą do uciszenia!",
    "comment": "Jeśli chcesz zostawić komentarz na powtórce z beatmapy, kliknij przycisk „Discussion”, wybierz sekcję, do której chcesz się odnieść, napisz coś i wciśnij enter. Jeśli komentarze nie są wyświetlane (o ile jakieś są), zaznacz opcję „Show Comments”.",
    "comment-color": "Zwykli użytkownicy mogą komentować tylko na biało, a [https://osu.ppy.sh/p/support supporterzy] mogą dostosować sobie kolor komentarza.",
    "conferencemode": "IRC zalewa cię powiadomienami typu Join/Quit? Spróbuj [http://wiki.xkcd.com/irc/Hide_join_part_messages tego].",
    "country-ranking": "Rankingi z wielu krajów całego świata znajdziesz [https://osu.ppy.sh/p/countryranking tutaj].",
    "critic": "Staraj się krytykować konstruktywnie, najlepiej po prostu dając propozycje, jak naprawić coś, co ci nie pasuje.",
    "ctb": "Potrzebujesz pomocy z Catch the Beat? [https://osu.ppy.sh/wiki/PL:Catch_the_Beat Tutaj] jest odpowiednia strona na osu!wiki.",
    "cutting-edge": "Stare osu!test build zostało zastąpione przez Tryb Eksperymentalny.\nMożesz [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues przeczytać ten artykuł], jeśli masz jakiekolwiek problemy z aktualizacją swojej gry.",
    "cwc": "CWC to międzynarodowy turniej trybu Catch the Beat. Zobacz [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 to], by dowiedzieć się więcej.",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Traktuj innych tak, jak sam chciałbyś być traktowanym. Jeżeli jesteś jakimś masochistą, zostaw to dla siebie.",
    "disable-this": "Różnorakie żądania, pomysły realizowane są rzadko, jednak wciąż możesz zgłosić swoje [https://osu.ppy.sh/forum/4 tutaj].",
    "distance-snap": "Distance Snap to narzędzie, które pozwala zachować odpowiednią odległość między notkami na mapie, bazując na ich odległości na linii czasu. Szczegóły: [[Distance_Snap]]",
    "dont-ask-peppy": "Nie pytaj ciągle peppy'ego, jest dość zajęty.\nSpytaj się kogoś innego na kanale.",
    "douche": "Jako uniwersalne zabezpieczenie, zespołowi administracyjnemu przysługuje wyłączne prawo do osądzania oraz karania jakiegokolwiek nieporządku, który wyniknął z użycia luk w regułach. Oficjalna zasada mówiąca byś nie był palantem nie powinna istnieć byś nie był palantem, ale na wszelki wypadek - nie bądź palantem. ",
    "download": "Dodatkowe beatmapy możesz pobrać [https://osu.ppy.sh/p/beatmaplist tutaj] lub jako paczki beatmap [https://osu.ppy.sh/beatmaps/packs tutaj].",
    "drugs": "Rozmowy o jakichkolwiek narkotykach są niedozwolone na czacie osu!.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Przeczytaj [[Beatmapping#Keyboard_Shortcuts]], aby poznać listę skrótów klawiszowych edytora.",
    "english": "Kanał #english został stworzony, aby prowadzić dyskusję na każdy (nieomawiany na innym kanale) temat. I tak, manga i anime też się liczą. Pociągi też.",
    "evade": "Omijanie uciszenia jest karane banem. A z kolei bany są znacznie, znacznie gorsze od uciszeń, więc po co?",
    "fallback": "Fallback jest przestarzałym buildem osu!. Nie licząc Fallback, nowsze wersje nie obsługują DirectX by uprościć środowisko. Jeśli ten tryb jest włączony, twój komputer jest za słaby, aby używać najnowszych wersji. Jeśli chcesz grać na nowych wersjach, wymień kartę graficzną, aby obsługiwała ona OpenGL, najważniejszy składnik dla tych wersji. [https://osu.ppy.sh/wiki/GL_Support_Issues Kliknij, aby dowiedzieć się jak].",
    "faq": "Teraz używasz osu!Bancho FAQ System.\nosu! wiki: https://osu.ppy.sh/wiki",
    "feature": "Swoje pomysły i/lub usprawnienia zgłaszaj [https://osu.ppy.sh/forum/4 tutaj].",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Unikanie filtrów czatu może prowadzić do uciszenia. Nie rób tego.",
    "foul-play": "Jeżeli widzisz, że ktoś oszukuje w grze, zgłoś go za pomocą odpowiedniego [https://i.imgur.com/GG9xlLA.png przycisku] na jego profilu. Podaj tyle szczegółów, ile tylko możesz. Zgłoszenie możesz również przesłać z poziomu listy najlepszych 50 wyników na stronie beatmapy. NIE ROZMAWIAJ NA TEN TEMAT PUBLICZNIE, ponieważ może to zakończyć się uciszeniem.",
    "percolate": "Unikanie filtrów czatu może prowadzić do uciszenia. Nie rób tego.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Ten artykuł] pomoże ci zrozumieć, jak ważny jest odpowiedni układ obiektów przy tworzeniu beatmapy oraz pokaże, jak to robić dobrze.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "By dodać użytkownika do znajomych, wpisz /addfriend i jego nazwę użytkownika.\nMożesz także kliknąć na jego panelu na liście użytkowników online (wciśnij F9) albo na jego nicku na czacie i kliknąć Dodaj do znajomych albo\ndodać ich poprzez kliknięcie Add as Friend na ich profilu na stronie.",
    "friends-list": "Żeby zobaczyć listę twoich przyjaciół online, wciśnij \nF9 a następnie zmień filtr na górze na filtr Znajomych.\nMożesz także zobaczyć pełną listę twoich znajomych,\nzarówno online i offline, na stronie dzięki kliknięciu na\nOpcje (będąc zalogowanym).",
    "fullscreen": "W sekcji „Grafika” w opcjach możesz wybrać, czy gra ma działać w trybie pełnoekranowym, czy w oknie (gra pełnoekranowa jest niedostępna dla rendereru OpenGL).\nMożesz również przełączać między tymi trybami, używając kombinacji klawiszy Alt+Enter.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Wszystkie ważne słowka związane z osu! znajdziesz [https://osu.ppy.sh/wiki/Glossary tutaj]",
    "gmt": "[https://osu.ppy.sh/wiki/People/Global_Moderation_Team Ci użytkownicy] stanowią Global Moderation Team (w skrócie GMT). Posiadają czerwone nicki na czacie i zielone na forum. Do ich obowiązków należy utrzymywanie porządku na czacie jak i na forum.",
    "english-help": " [https://osu.ppy.sh/forum/t/12016 Przeczytaj, wykuj, rozraduj nasze dusze].",
    "grammar": "Staraj się pisać poprawnie gramatycznie. Kilka literówek czy błędów w interpunkcji jest dopuszczalnych, ale nie używaj całkowicie niepotrzebnych skrótów, a tymbardziej nie pisz tak zwanym „pismem pokemonów”. Pisanie w ten sposób nie świadczy o tobie dobrze.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "[https://osu.ppy.sh/forum/t/68346 Tu znajdziesz poradnik dla początkującego gracza].",
    "hacked": "Jeżeli uważasz, że twoje konto zostało shackowane, koniecznie zgłoś to na accounts@ppy.sh.\nW innym przypadku może ono zostać usunięte. ",
    "hard": "Naucz się grać, noobie.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Jeśli szukasz pomocy w śwecie osu!, i naszukałeś się już wszędzie, to jeśli znasz angielski, możesz spróbować swoich sił na kanale #help.",
    "hitsound-library": "[https://osu.ppy.sh/forum/p/164927 Tutaj] znajdziesz efekty dźwiękowe (nazywane zwykle ''hitsounds''), które na pewno uatrakcyjnią twoją beatmapę. ",
    "hl": "Nie oskarżaj innych o to, że ciągle wyskakują ci powiadomienia o czacie, jeśli do swej kolekcji wyróznianych słów dodałeś popularną w mowie frazę. \nZarówno powiadomienia te jak i odtwarzany razem z nimi dźwięk możesz wyłączyć w opcjach.",
    "how-to-get-modded": "Jeśli chcesz się dowiedzieć, jak sprawić, aby ktoś przyjrzał się twojej beatmapie, zapoznaj się z tym: [[Getting_Your_Map_Modded]].",
    "how-to-bn": "Jeśli chciałbyś zostać BN'em - zapoznaj się z [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator tym] - w większości przypadków inni BNowie wybierają, kogo przyjąć w swe szeregi. Zwracają uwagę na rzeczy takie jak aktywność i jakość twego modowania.",
    "how-to-gmt": "Moderatorzy są wybierani spośród społeczności. Jeżeli również chcesz pomagać pamiętaj by używać komendy !report by usprawnić moderację na kanale",
    "how-to-play": "[https://osu.ppy.sh/forum/t/68346 Kliknij, żeby nauczyć\nsię grać!]",
    "how-to-rank": "Chcesz, aby twoja mapa stała się rankingowa? Sprawdź [https://osu.ppy.sh/wiki/How_to_Get_Your_Map_Ranked to].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "„Hyperdash” uaktywnia się wtedy, gdy w trybie CTB złapiesz świecący się na czerwono owoc. Gdy „Hyperdash” jest aktywny, dash jeszcze bardziej cię przyspieszy. Stan ten minie, gdy złapiesz inny owoc, lub missniesz.  ",
    "ignore": "Wpisz na czacie komendę /ignore oraz nazwę użytkownika by całkowicie zignorować wiadomości jednego z graczy (w tym rownież prywatne).\n/unignore lub ponowne uruchomienie osu! powoduje odignorowanie użytkownika.",
    "import": "Jeśli nie wiesz, jak załadować beatmapy do osu, zapoznaj się z [https://osu.ppy.sh/forum/t/68346 tym] poradnikiem. Sprawdź również [http://i.imgur.com/kpX2N3m.jpg tę] grafikę.",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Po zaznaczeniu Inherit previous timing settings w menu sekcji timingu (F6) w Edytorze żadna sekcja nie wpłynie na zmianę timingu. Dzięki temu łatwo jest operować sekcjami, w których zmienia się tylko głośność albo sampel.\nMożliwe jest użycie tej opcji również w przypadku sekcji z zmniejszonym lub zwiększonym BPM. Jeśli znajdziesz się w takiej sytuacji, użyj jej!",
    "irc": "Serwer IRC: irc.ppy.sh:6667\nHasło: https://osu.ppy.sh/p/irc\nWięcej informacji na https://osu.ppy.sh/wiki/IRC.",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Ustawienia klawiszy możesz zmienić w sekcji Sterowanie w opcjach.\nKlawisze używane w osu!manii zmienisz klikając Styl osu!mania.",
    "kiai": "Kiai mode to efekt, który możesz nałożyć na określone partie twojej beatmapy w edytorze (timing>Timing Setup Panel). Kiai time aktywuje przeróżne efekty wizualne, które sprawiają, że twoja beatmapa jest jeszcze bardziej epicka. ",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Zdobywaj [[Kudosu]]\ndzięki modowaniu map innych graczy.",
    "lag": "Lag może być spowodowany przez wiele czynników, najczęściej przeciążeniem twojego komputera. Jednak jeśli jesteś przekonany, że to na pewno wina osu! - poszukaj wątku opisującego twój problem [https://osu.ppy.sh/forum/5 tutaj], a jeśli takowego nie znajdziesz - zacznij nowy. Opisz tam najdokładniej jak możesz swój problem, ułatwi to rozwiązanie go. ",
    "language": "Bądź miły na czacie. Używanie nieodpowiedniego języka może doprowadzić do tego, że zostaniesz uciszony.",
    "language-specific": "Używaj odpowiedniego języka na kanale, na któym się znajdujesz. Używanie rzymskiego alfabetu nie jest wyjątkiem dla takich krajów, jak na przykład Japonia.",
    "lazer": "",
    "level": "Twój poziom bazowany jest na całkowitej zgromadzonej liczbie punktów z gier rankingowych, niezależnie od zaliczenia mapy. Poziom wzrasta po prostu poprzez grę!",
    "lines": "Staraj się nie pisać w wielu liniach w krótkich odstępach czasu, inaczej możesz otrzymać automatyczną blokadę czatu.",
    "link": "Jeśli chcesz podpiąć do czegoś link, to postępuj według wzoru: [adres tekst], gdzie „adres” to link, który podpinasz, a „tekst” to słowa, do których ten link podpinasz. [http://osu.ppy.sh O tak!]\nNie zapomnij o http:// bądź https:// przed linkiem.",
    "lobby": "Używaj kanału #lobby do zapraszania innych graczy do gier wieloosobowych. Kanał ten nie posiada restrykcji co do języka.\nNatomiast do rozmów w trakcie i pomiędzy meczami służy kanał #multiplayer",
    "localisation": "Projekt tłumaczenia osu! na różne języki znajdziesz [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 tutaj].",
    "long-link": "Nie wklejaj długich linków na czat! Użyj formuły [link tekst], jeśli jest to naprawdę konieczne.",
    "long-text": "Nie wklejaj długich tekstów w czat, ponieważ może się to skończyć uciszeniem.",
    "loved": "Loved to nowy status beatmapy, który może zostać przyznany przez społeczność dla mapy. Dzięki niemu mapa, która normalnie nie spełniałaby warunków bycia rankingową, może posiadać tabelę wyników.  [https://osu.ppy.sh/news/151925254083 Poczytaj więcej o tym tutaj.]",
    "mac": "[https://osx.ppy.sh Instrukcja instalowania osu! na komputerze Mac].",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Mapperzy są często zajęci, a tworzenie map jest trudne i zajmuje dużo czasu. Może spróbujesz stworzyć coś własnoręcznie?",
    "mapping": "Odwiedź [https://osu.ppy.sh/forum/p/988111 tę stronę], jeśli szukasz porad dot. tworzenia beatmap.",
    "mat": "Grupa MAT była niegdyś grupą, która pomagała BAT-om w procesie rankingowania.\nRIP MAT 2013-04-23",
    "modhelp": "Wszystkie pytania związane z modowaniem kieruj do innych na kanale #mapping.",
    "modqueue": "Kolejki do modowania beatmap znajdziesz [https://osu.ppy.sh/forum/60 tutaj]. ",
    "modreqs": "Pisz na kanale #modreqs, jeśli chcesz kogoś poprosić, aby zmodował twoją beatmapę. Pamiętaj, że członkowie grupy BAT to zajęci ludzie i nie zawsze będą mieć dla ciebie czas. Inni mogli poprosić pierwsi. Zawsze możesz poprosić więc o pomoc w modowaniu zwykłych użytkowników!",
    "multi-invite": "Aby zaprosić kogoś do twojej gry wieloosobowej, kliknij na danego użytkownika na liście graczy online (wciśnij F9) lub kliknij jego nick na czacie i wybierz opcję „Zaproś do gry”. ",
    "multi-link": "",
    "multiaccounting": "Nie należy tworzyć wielu kont. Osoby posiadające więcej niż jedno konto zostaną ukarane długotrwałym uciszeniem lub nawet banem.",
    "multiplayer": "Nie rozgłaszaj swoich gier wieloosobowych na innych kanałach niż #lobby.",
    "mwc": "Więcej informacji o Światowym Turnieju osu!manii (MWC) znajdziesz [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 wiki page tutaj].",
    "nat": "",
    "news": "",
    "nightcore": "Graj swoje ulubione beatmapy w trybie „Nightcore”. Aby go aktywować - wciśnij klawisz F1, a potem dwukrotnie kliknij na mod „DoubleTime”. Tryb ten daje taką samą premię do zdobywanych punktów, co „DoubleTime”.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Wpisz /np, by pokazać innym której piosenki słuchasz lub jaką mapę obecnie grasz.",
    "nsfw": "Rozmowy na tematy przeznaczone dla dorosłych są zakazane. Czat przeglądają też młodsi! Łamanie tego zakazu poskutkuje uciszeniem bez ostrzeżenia.",
    "osu": "Kanał #osu jest od rozmów o osu!. O grze pisz więc tam, a nie na tym kanale.",
    "osu!tablet": "[[https://osu.ppy.sh/forum/t/169139 Tutaj] znajdziesz wszystkie informacje na temat oficjalnego tabletu osu!",
    "osu!talk": "osu!talk to prowadzone przez deadbeata i ztrota talkshow, w którym przeprowadzają wywiady z osobami ze społeczności osu! i rozmawiają o wydarzeniach wokół gry, np. o turniejach.\nKażdy odcinek jest nagrywany na [https://discord.gg/014x1ACj2VdUPLU5x serwerze Discord], dzięki czemu każdy chętny może zadawać pytania w wyznaczonym czasie.\nWięcej infromacji można znaleźć [https://osu.ppy.sh/forum/t/225111 tutaj].",
    "osucore": "Żart na Prima Aprillis z roku 2011: wszystkie beatmapy zostały domyślnie ustawione, by były odtwarzane w trybie „DoubleTime” i miały zwiększoną wysokość.\nEfekt ten został przywrócony do gry w postaci moda „Nightcore”.\n",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] to port orginalnej gry na urządzenia z systemem Android.\nZostał porzucony przez developerów i zdjęty ze Sklepu Play w 2016 ze względu na nieaktywność i niskie oceny.",
    "osumania": "Jeśli chcesz rozmawiać na tematy związane z osu!manią, rób to na kanale #osumania.",
    "osustream": "[http://www.osustream.com osu!stream] jest to osu! na urządzenia z systemem iOS, stworzone i rozwijane przez peppy'ego.",
    "osz": "Pliki .osz to pliki beatmap, które pobierasz ze strony osu! i rozpakowujesz w celu gry w nowe beatmapy. Muszą być one zawsze rozpakowywane przez samo osu!, inaczej mogą pojawić się problemy.",
    "osz2": "Osz2 jest nowym formatem beatmap. Każdy plik spakowany do tego formatu będzie mógł być zaszyfrowany, zaktualizowany i przesyłany niezależnie od reszty plików. Pliki .osz2 nie muszą być rozpakowywane i zawsze pozostaną plikami .osz2 w twoim folderze Songs.",
    "owc": "OWC, czyli osu! World Cup to ogólnoświatowy turniej osu!.\n[https://osu.ppy.sh/wiki/OWC wiki page W tym temacie znajdziesz więcej informacji].",
    "peppy": "peppy to główny deweloper osu!, zajmujący się większością projektu samodzielnie.",
    "perfect": "Nie udało ci się wbić SS? Spróbuj użyć trybu „Perfect”. Ten tryb auromatyczne powtarza beatmapę, jeśli popełnisz choć jeden błąd. Aby go uaktywnić, kliknij dwukrotnie na ikonę modu „Sudden Death”.",
    "ping": "Pong!",
    "pippi": "Pippi to oficjalna maskotka osu!. Pippi-don to jej odpowiedniczka w trybie Taiko.",
    "piracy": "Dyskusja na temat piractwa jest zabroniona.",
    "play-shortcuts": "Pełna lista skrótów klawiszowych: [[Shortcut_Key_Reference]]",
    "pm": "Aby wysłać do kogoś prywatną wiadomość - kliknij na nick tej osoby na czacie lub na liście użytkowników online. Możesz również użyć komendy /msg <nazwa użytkownika> <wiadomość>, /chat <nazwa użytkownika> lub /query <nazwa użytkownika>, która to otworzy nową kartę na twoim czacie. Aby szybko odpowiedzieć na prywatną wiadomość wysłaną do ciebie, możesz użyć komendy /r <nazwa użytkownika>. Przy używaniu tych komend pomiń znaki < i >.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance Points (pp) to główny system ustalania rankingów w osu! Więcej informacji o nich znajdziesz [https://osu.ppy.sh/wiki/Performance_Points tutaj]",
    "pp-rework-lazer": "",
    "preview": "„Podgląd” (ang. preview point) to moment piosenki, od którego zaczyna się odtwarzanie jej w menu wyboru beatmap.\nJest to moment reprezentujący piosenkę, np. rozpoczęcie się refrenu. Aby wybrać aktualny moment piosenki jako podgląd, przejdź do zakładki „Timing” i wybierz Ustaw tę pozycję jako podgląd.",
    "qat": "",
    "qualified": "Nominatorzy beatmap nominują mapy jako zakwalifikowane, gdzie można zdobyć miejsce w rankingu, ale nie można zdobyć pp. Jeżeli mapa ta jest już idealna i zakwalifikowana przez tydzień, staje się rankingowa. Jeżeli nie, wraca z powrotem do fazy modowania, a wyniki są usuwane.",
    "ranked": "Rankingowa beatmapa to taka beatmapa, która została zatwierdzona przez społeczność osu!.\nDzięki graniu rankingowych map zmieniasz swoje statystyki na profilu osu!.\nTakie mapy posiadają swoją własną listę wyników. Można je rozpoznać przez ikonkę serca.",
    "ranking-criteria": "Aby dowiedzieć się więcej o kryteriach rankingowania, odwiedź stronę wiki: [[RC]].",
    "redname": "Użytkownik z czerwonym nickiem to [https://osu.ppy.sh/wiki/People/The_Team/Global_Moderation_Team GMT] albo [https://osu.ppy.sh/wiki/People/The_Team/Nomination_Assessment_Team NAT].",
    "report": "Moderatorzy to też ludzie; nie mogą siedzieć na czacie cały czas. Zatem jeżeli zauważysz kogoś robiącego coś nieodpowiedniego, na co moderator nie reaguje, użyj komendy „!report <nazwa użytkownika> <powód>” (nie używaj tej komendy w konwersacji z BanchoBotem).",
    "report-abuse": "Nie wysyłaj w jednej chwili zbyt wielu zgłoszeń - nie przyspieszy to rozwiązania problemu. Same zgłoszenia powinny mieć też treść i uzasadnienie.",
    "request": "Chcesz coś zmodować? Sprawdź [https://osu.ppy.sh/p/beatmaplist&r=8 to] lub użyj komendy !request, a dostaniesz link do losowej beatmapy.",
    "respect": "Zachowaj szacunek względem innych graczy.",
    "roll-abuse": "Nie nadużywaj komendy !roll, gdyż możesz otrzymać za to uciszenie.",
    "romaji": "Proszę nie używać nadmiernie Romaji (Romanized Japanese). Możesz zostać uciszony.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Jeśli żadne pokoje do gry wieloosobowej nie są dostępne, stwórz swój własny! Teraz to ty wybierasz piosenki!",
    "rp": "Na kanałach do rozmów możesz robić co chcesz, ale upewnij się, że nie przeszkadzasz tym zbytnio innym użytkownikom czatu.",
    "rules": "[https://osu.ppy.sh/wiki/pl/Rules Oficjalne zasady]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "Od czasu do czasu serwery osu! są atakowane przez DDoS. W ich trakcie Bancho może być niestabilne lub niedostępne. \nJeśli podejrzewasz taką sytuację, wejdź na [https://twitter.com/osustatus @osustatus] - nasz profil na Twitterze lub [https://status.ppy.sh specjalną stronę], aby dowiedzieć się więcej.\nJeśli w trakcie ataku możesz w dalszym ciągu swobodnie rozmawiać - niczym się nie przejmuj. Przywoływanie tego tematu nie rozwiąże szybciej problemu.",
    "sb": "Poradnik dot. storyboardingu: https://osu.ppy.sh/forum/t/1869\nJak używać edytora storyboardu: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "Scorev2 to nowy algorytm zliczania punktów, w którym maksymalna liczba punktów (nie licząc spinnerów i włączonych modów) wynosi 1 milion.\nZmienia też sposób zachowywania się sliderów - teraz wymagany jest w nich taki sam poziom trafności, jak w kółkach.",
    "scoring": "Jak ustalany jest wynik? Dowiesz się tutaj: [[Score#scoring]].",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Uciszenie oznacza niemożność rozmawiania na czacie lub publikowania postów na forum, z wyjątkiem działu Technical Support.\nUciszenie za pierwsze wykroczenie trwa 5 minut, a potem każde kolejne trwa 2 razy dłużej od poprzedniego. W przypadku poważniejszych wykroczeń wartość ta może być większa.\nUciszenia otrzymuje się za większość wykroczeń, także dopóki przestrzegasz zasad, wszystko będzie w porządku. ",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Podstawy tworzenia skórek].",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Nie zasiedź się do czwartej nad ranem, wyśpij się porządnie!]",
    "songs-not-appearing": "Jeśli twoje beatmapy nie pojawiają się w menu wyboru piosenki, wciśnij klawisz F5.",
    "spaces": "Nie wstawiaj spacji pomiędzy każdą literę, nie jest to estetyczne i może doprowadzić do uciszenia.",
    "spam": "Nie rób spamu na czacie - to denerwujące i może być powodem uciszenia.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Jeśli chcesz oglądać grę innego gracza, wpisz /watch <nick> lub kliknij na jego nick na czacie albo user panel'u, a następnie wybierz Start Spectating.\nUpewnij się, że posiadasz grane przez gracza mapy!",
    "spoiler": "Spoilerowanie anime, mang, doujinów i innych tworów jest zakazane i może być powodem uciszenia.",
    "status": "Żeby być na bieżąco ze stanem systemu osu!, śledź profil [http://twitter.com/osustatus @osustatus] na Twitterze.",
    "store": "Gadżety związane z osu! kupisz [http://store.ppy.sh/ tutaj].",
    "submit": "[https://osu.ppy.sh/wiki/Submission Informacje o rankingowaniu map].",
    "suck": "Nie martw się, jeśli na początku nie będzie ci wychodzić - wszystko przyjdzie z czasem, po prostu ćwicz!",
    "supporter": "[https://osu.ppy.sh/p/support Wspomóż osu!] - dostaniesz w zamian możliwość pobierania map w grze, żółty nick i inne!",
    "supporter-please": "Nie pytaj się innych, czy podarują ci status donatora. [https://osu.ppy.sh/p/support Zdobądź go tutaj!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Jeżeli twój kursor porusza się po całym ekranie kiedy starasz się nim poruszać, upewnij się, że czułość myszy w grze jest ustawiona na 1.00x. Większą czułość można osiągnąć poprzez zmniejszenie obszaru roboczego tabletu. Jeżeli kursor w ogóle się nie rusza, upewnij się, że wyłączyłeś sygnał bezpośredni w opcjach. W przypadku innych problemów związanych z tabletem [https://osu.ppy.sh/forum/t/87183 przeczytaj ten temat].",
    "tag": "W trybie wieloosobowym istnieje tryb tag, w którym gracze grają na przemian, po jedno combo na gracza. Nie ma wygranych ani przegranych - wszyscy grają w jednej drużynie.\nSpinnery kręcą wszyscy gracze jednocześnie. Jeśli jeden gracz nie ukończy spinnera, drużyna traci combo. Punkty bonusowe sumują się i zostają dodane do wyniku drużyny.",
    "taiko": "Tryb Taiko w osu! to symulator serii gier z japońskim bębenkiem, tworzonych przez Bandai-Namco. Jednak w Osu! został wyeliminowany element ruchu, pozwalając graczowi całkowicie skupić się na rytmie beatmapy.\n[https://osu.ppy.sh/forum/t/4363 Tu dowiesz się, jak grać!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 poradnik tworzenia beatmap do trybu Taiko].",
    "taiko-maps": "[https://osu.ppy.sh/forum/t/5397 Tutaj] znajdziesz autentyczne mapy z gry Taiko no Tatsujin.",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Skończcie ten temat i porozmawiajcie o czymś innym.",
    "training": "[https://osu.ppy.sh/forum/t/4280 James Training]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 Lista aktualnych wideo-tutoriali dotyczących osu! i mappingu]. Śmiało, zrób swój własny filmik i podziel się nim w tym temacie. \nZobacz także [https://osu.ppy.sh/forum/t/60228 listę poradników dla mapperów/modderów].",
    "twc": "Międzynarodowe zawody taiko. [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ Zobacz ten temat by dowiedzieć się więcej.]",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Unikaj korzystania ze znaków niestandardowych, nie należących do alfabetu czatu, w którym rozmawiasz.",
    "upload-cap": "Żeby mieć pewność, że mapperzy skupiają się na wszystkich swoich tworzonych mapach, istnieje limit map, które możesz tworzyć jednocześnie.\nZwykli użytkownicy mogą mieć ich 3-6, a supporterzy 5-10, w zależności od ilości rankingowych map, które stworzyli wcześniej.",
    "utf8": "Aby wysyłać i odbierać czytelne wiadomości, ustaw swojego klienta IRC na system kodowania UTF-8.",
    "videogames": "Tematy związane z grami komputerowymi mogą być podejmowana na kanale #osu, ale jeśli przeszkadzają innym czatującym lub więcej niż jedna taka rozmowa jest prowadzona, przenieś się na kanał #videogames.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Witaj w osu!. Jeżeli masz jakiś problem lub pytanie wymagające odpowiedzi, spróbuj zapytać w #help. Miłej zabawy!",
    "when": "Wtedy, kiedy będzie.",
    "wiki": "[https://osu.ppy.sh/wiki/ osu! Wiki] - Spraw, by była świetna!",
    "wiki-link": "Możesz tworzyć linki do stron na wiki, wpisując nazwę jej hasła w podwójnych nawiasach kwadratowych: [[ ]]\nNp. [[Kudosu]] został utworzony przez wpisane Kudosu między [[ ]].",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 211 active FAQs (out of a possible 217) in the Polish (Polski) language.",
    "completion": "The Polish (Polski) FAQ as of last update is 97.24% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mecz rozpocznie się za 60 sekund!"
}
