
strings = {
    "academy": "[http://www.youtube.com/user/osuacademy Clique aqui] para ver a osu!academy - Aqui vocé encontra tutoriais para todas as coisas no osu!",
    "achievements": "Você conseguirá achievements (conquistas) completando tarefas específicas, como conseguindo um combo alto numa música ou jogando todos os beatmaps de um pack. Você pode ver suas conquistas no seu perfil. Alguns dos nomes são dicas para o quê você precisa fazer para conseguí-lo!",
    "add-skin": "Para adicionar uma nova skin (tema), transfira-a e arraste-a até a janela do osu! ou clique no arquivo .osk baixado pelo site.",
    "advertising": "Divulgar qualquer coisa não relacionada ao osu! é proibido e você pode levar um silence. Isso inclui servidores de Discord ou TeamSpeak.",
    "answer": "Se ninguém respondeu a sua pergunta, é provavelmente porque as pessoas não sabem como responder! Tente pesquisar nos fóruns do osu!",
    "appeal": "Se você acabar levando um silence, e acha que foi injusto, entre em contato com os administradores mandando um e-mail para accounts@ppy.sh explicando o ocorrido. Lembre-se que os administradores também são pessoas! Se você for amigável, é mais provável que tentem ao máximo limpar seu silence, caso seja possível.",
    "approved": "Approved beatmaps não podem receber o status de ranqueado por uma determinada razão - geralmente são mapas com duração de 5 minutos ou mais com uma única dificuldade. Vocé saberá se um beatmap é aprovado quando o ícone dele for uma chama no lugar de um coração",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "O Aspire é uma competição de alto nível de beatmapping e retorna em 2017, com uma música do Helblinde. [https://osu.ppy.sh/home/news/2017-01-21-aspire-returns-for-2017 Confira aqui!]",
    "ask": "A melhor maneira de conseguir uma resposta é fazer sua pergunta diretamente! - Posso fazer uma pergunta? já é uma pergunta.",
    "attention": "Ninguém te perguntou :)",
    "avatar-change": "Você pode trocar seu avatar [https://osu.ppy.sh/home/account/edit#avatar aqui].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Eae! Meu nome é BanchoBot! Prazer em conhecê-lo. Ainda assim, eu sou um bot, então eu não posso ter uma conversa real contigo :(",
    "beatmapping": "Leia [[PT:Beatmapping]] para achar algumas dicas legais sobre Beatmapping.",
    "beginner": "[https://osu.ppy.sh/forum/t/5456 Treino para novatos!]",
    "bn": "Os [[Beatmap_Nominators]] são um grupo de pessoas que qualificam beatmaps e são responsáveis pela moderação de beatmaps pendentes no processo de ranking.\nVocê pode falar com eles se tiver qualquer pergunta relacionada à mapping ou modding.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Se está realmente entediado, ache algo para fazer.] Tem muitas coisas para se fazer online. Tédio não é motivo para reclamar ou spammar no osu!",
    "bug": "Se você acha que encontrou um bug, reporte-o [https://osu.ppy.sh/forum/5 aqui]. Apenas tenha certeza de que ninguém postou nada relacionado antes de você.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Por Favor Pare De Escrever Desse Jeito. Aprende a tirar o dedo do Shift.",
    "caps": "Por favor não escreva tudo em letras maiúsculas. Não é agradável no chat, e você pode acabar levando um silence.",
    "change-modes": "Para mudar para outros modos de jogo, vá para a tela de selção e clique em Modo no canto inferior esquerdo ou pressione Ctrl + 1-4. Lembre-se que algum mapas são específicos de um modo!",
    "change-name": "Para mudar seu username, primeiro você precisa ter sido um [https://osu.ppy.sh/p/support supporter]. Em seguida, caso já tenha sido, clique [https://store.ppy.sh/store/product/32 aqui]!\nPara voltar ao seu username antigo, mudar poucas coisas, ou caso precise de ajuda, por favor mande um e-mail para accounts@ppy.sh com os detalhes.",
    "changelog": "Todas as adições e correções ao jogo, Bancho, e ao website são listadas no log de [https://osu.ppy.sh/p/changelog desenvolvimento] - leia e se emocione.",
    "chars": "Por favor evite usar caracteres unicode/especiais no chat.",
    "charts": "osu! charts são lançados todos os meses. São compilações de mapas que foram os nomeados daquele mês ou se inserem num certo tema. Você poderá encontrar eles [https://osu.ppy.sh/p/chart aqui].",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Amarelo claro: Um usuário comum | Amarelo forte: Um [https://osu.ppy.sh/p/support Supporter] | Vermelho: Um [https://osu.ppy.sh/wiki/People/The_Team/Nomination_Assessment_Team NAT] ou [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nBranco: Você ou uma ação /me | Azul escuro: Uma mensagem privada| Verde: Uma linha com seu nickname (um highlight) | Rosa: BanchoBot",
    "colour": "Amarelo claro: Um usuário comum | Amarelo forte: Um [https://osu.ppy.sh/p/support Supporter] | Vermelho: Um [https://osu.ppy.sh/wiki/People/The_Team/Nomination_Assessment_Team NAT] ou [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nBranco: Você ou uma ação /me | Azul escuro: Uma mensagem privada| Verde: Uma linha com seu nickname (um highlight) | Rosa: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Mesmo que os comandos do chat sejam fáceis de usar, por favor, não abuse deles. Isso é considerado spam e pode resultar em silence.",
    "comment": "Se você quiser falar algo sobre um replay de algum beatmap ao vivo, clique no botão Discussão, escreva algo e pressione enter! Se não houver comentários na tela, ligue a opção Mostrar Comentários no botão Discussão.",
    "comment-color": "Um usuário normal pode somente comentar em branco. Um [https://osu.ppy.sh/p/support supporter] pode customizar a sua cor de comentário.",
    "conferencemode": "Para aprender como desativar as mensagens de Entrada/Saida na maior parte dos clientes IRC, clique [http://wiki.xkcd.com/irc/Hide_join_part_messages aqui].",
    "country-ranking": "Veja os rankings regionais [https://osu.ppy.sh/p/countryranking aqui!]",
    "critic": "Por favor mantenha suas críticas construtivas! Sugira alternativas ou caminhos de solucionar os problemas. Não seja babaca com os outros.",
    "ctb": "[https://osu.ppy.sh/forum/p/60690 Catch The Beat FAQ]",
    "cutting-edge": "O cutting-edge é uma versão do osu! feita para testar novos recursos antes que esses recursos tornem-se oficiais, indo para a build estável (stable). Você pode mudar no menu de opções! [https://osu.ppy.sh/wiki/Help_Center Leia este artigo] caso tenha algum problema na atualização do seu client.",
    "cwc": "Um torneio mundial de osu! Catch the Beat. [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 Veja esse tópico para mais informações.]",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\r\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\r\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Trate as pessoas do chat da mesma forma que você deseja ser tratado. Ninguém quer ver você sendo tóxico, intencionalmente agindo de forma não-inteligente ou falando coisas só para parecer legal. Memes e emojis repetitivos não são bem-vindos e podem resultar em silence.\n\n",
    "disable-this": "Toggles para desativar funções raramente são criados. Se você realmente achar necessário, pode pedir por um usando o [https://osu.ppy.sh/forum/4 fórum de Feature Requests].",
    "distance-snap": "A maneira mais simples de garantir espaçamento de batidas é utilizando a função Distance Snapping, encontrada no canto-direito do editor. A distância relativa entre as notas pode ser ajustada com a rodinha do mouse. Se você se prender a usar Distance Snap para toda a música, um espaço de notas correto é garantido!",
    "dont-ask-peppy": "Não fique perguntando coisas ao peppy toda hora, ele pode estar bem ocupado. Pode ficar tranquilo em perguntar às pessoas deste canal.",
    "douche": "Tentar quebrar a ordem e civilidade do canal usando brechas nas regras é punível a critério e julgamento da administração. Uma regra oficial declarando que você não deve ser um idiota não deve ser necessária para você não ser um idiota, mas só em caso de isso acontecer: Não seja um idiota.",
    "download": "[https://osu.ppy.sh/p/beatmaplist Faça download dos mapas aqui!]\n[https://osu.ppy.sh/beatmaps/packs Lista oficial de packs.]",
    "drugs": "Por favor não discuta nada sobre drogas, ou coisas relacionadas a isso, em nenhum canal do osu!. Pense nas crianças...",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Leia [[Beatmapping#Keyboard_Shortcuts]] para encontrar uma lista de atalhos do editor.",
    "english": "O #english é destinado a uma discussão geral sobre tudo que não tem um canal dedicado. Sim, isso inclui anime/mangá. E trens.",
    "evade": "Burlar um silence é uma ofensa banível. Ser banido é muito, muito pior do que levar um simples silence.",
    "fallback": "Stable (Fallback) é uma versão desatualizada do osu!. Diferentemente do Fallback, as versões mais recentes removem suporte ao DirectX para simplificar nossa estrutura.\nSe você foi colocado nesta versão, seu PC é fraco e não suportará as recentes e futuras versões do cliente.\nCaso queira jogar nas versões atuais agora, atualize sua placa de video para que suporte OpenGL, o complemento mais necessário para estas versões. [https://osu.ppy.sh/wiki/GL_Support_Issues Clique aqui para saber como].",
    "faq": "Você está usando o sistema de FAQ do osu!Bancho.\nWiki do osu!: https://osu.ppy.sh/wiki",
    "feature": "Se você tiver alguma sugestão nova para o jogo, poste ela no subfórum [https://osu.ppy.sh/forum/4 Feature Requests].",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Burlar os filtros de chat pode acabar em silence. Por favor não faça isso.",
    "foul-play": "Por favor, reporte cheaters usando o botão report no perfil deles, localizado [https://i.imgur.com/GG9xlLA.png aqui].\nTenha certeza de fornecer o máximo possivel de detalhes. Você também pode reportar seus scores no top 50 da página do beatmap.",
    "percolate": "Burlar os filtros de chat pode acabar em silence. Por favor não faça isso.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/forum/t/86329 Esse] tópico poderá te ajudar a teoria do fluxo de mapping.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Para adicionar um usuário como amigo, digite /addfriend seguido do nome do usuário.\nVocê também poderá clicar no painel de usuário no modo F9 ou seu nome no chat e selecionar Add as Friend.\nAdicionalmente, você poderá adicionar eles através dos seus perfis clicando Add as Friend.",
    "friends-list": "Para ver uma lista com seus amigos online in-game, pressione F9 e mude o filtro no topo para Amigos.\nVocê também poderá ver a lista de seus amigos completa, ambos online e offline, no site, clicando em Settings (Você deve estar logado, claro.)",
    "fullscreen": "Você pode decidir se quer jogar em Modo Janela ou Tela Cheia na sessão Graphics (Gráficos) no menu de Opções.\nVocê também pode mudar para Tela Cheia pressionando Alt+Enter no seu teclado.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Você poderá encontrar várias terminologias em [[glossary]].",
    "gmt": "O [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team], ou GMT, é um grupo de usuários que ajudam a moderar o osu!. Eles posuem nome vermelho no chat e nome verde no fórum. Eles ajudam tanto o fórum quanto o chat.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Tão fácil... até você consegue fazer... acho.]",
    "grammar": "Derrepente não existe. Agente é o James Bond. Chingar não é uma palavra correta. Lembre-se disso. Não precisa ter um bilhão de QI, mas por favor, fale de um jeito que os outros o entendam.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Não sabe como jogar? Deseja explorar o mundo de mapping e modding? [https://osu.ppy.sh/wiki/Guides Aqui] você irá encontrar todas as respostas.",
    "hacked": "Se acredita que foi hackeado, por favor mande um e-mail para accounts@ppy.sh para tentar recuperar sua conta.\nCaso acabe em fracasso, poderá resultar no fechamento da mesma.",
    "hard": "Aprende a jogar e pega a visão, seu noob.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Se você requisitar assistência para qualquer coisa relacionada ao osu!, junte-se a #help. Você pode falar em português em #help - mas talvez não haja alguém que fale português disponível para te ajudar!",
    "hitsound-library": "Vá  [https://osu.ppy.sh/forum/p/164927 aqui] para adquirir alguns hitsounds custom para seu mapa.",
    "hl": "Não culpe os outros usuários por darem highlight em você se você tiver uma palavra comum na sua lista de highlights. O problema é totalmente seu! Você pode desabilitar as notificações e o som delas sempre que quiser no menu de Opções.",
    "how-to-get-modded": "Se você quer saber como pode ter seu mapa modado, clique aqui: [[Getting_Your_Map_Modded]]",
    "how-to-bn": "Se você quiser se tornar um BN, dê uma olhada [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator nisso].",
    "how-to-gmt": "Os GMT são selecionados por vários contribuidores da comunidade. Quer ajudar? Faça sempre seu melhor ajudando seu canal e reportando sempre que necessário usando o comando !report. Mas é claro, sem abusar do comando. Mais detalhes em: [https://osu.ppy.sh/wiki/pt-br/People/The_Team/Global_Moderation_Team GMT]",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F Clique aqui para aprender como jogar!]\n",
    "how-to-rank": "Para descobrir, leia [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Hyperdash vai ocorrer quando você apanhar uma fruta que está brilhando em vermelho. Você irá produzir um dash mais rapido que o normal durante este período. O hyperdash será desativado depois de chegar na próxima fruta, ou quando a errar.",
    "ignore": "Para ignorar um usuário, digite /ignore e seu username.\nVocê não poderá ver o texto digitado por usuários que você ignorou, incluindo qualquer mensagem privada que eles poderam eventualmente enviar.\nDigitando /unignore (username) ou saindo do osu! irá cancelar o mesmo. (Se o ignore não tiver sido colocado no menu de Opções, nessa caso ele será permanente independentemente de sair do jogo ou não.)",
    "import": "[http://i.imgur.com/kpX2N3m.jpg Leia isso para descobrir como importar beatmaps para o osu!!]",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Ao selecionar a caixa inherit previous timing sections na janela F6 no Editor, a secção não irá mais afetar o timing, o que é útil para secções que a única coisa que muda é o volume ou o sample do mapa.\nAdicionalmente, é possível criar secções de timing inherit que possuem o dobro ou metade do BPM. Se você achar que está usando uma secção de timing como essa, por favor use inherit!",
    "irc": "Servidor IRC: irc.ppy.sh\nPorta: 6667\nPassword: https://osu.ppy.sh/p/irc",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Você pode mudar a combinação de teclas no menu de input nas opções. Teclas e layouts do osu!mania podem ser mudadas no menu osu!mania layout.",
    "kiai": "O modo Kiai é um efeito de estilo que poderá ser aplicado em secções de timing usando o Timing Setup Panel (Painel de configuração de timings).\nSecções de timing com o modo kiai ativo usam vários efeitos visuais para fazer, a certa altura, o mapa mais épico. Por favor use com moderação!",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Ganhe [https://osu.ppy.sh/wiki/Kudosu kudosu] modando mapas de outras pessoas",
    "lag": "Lag pode ser causado por conta de [https://osu.ppy.sh/wiki/Help_Center#Experiencing_lag qualquer coisa] - é causado principalmente por outros processos abertos em sua máquina. Se você está convencido que é o osu!, e apenas ele mesmo, que está laggando, mande um support request no [https://osu.ppy.sh/forum 5 Fórum de Ajuda] mostrando os detalhes do seu problema.",
    "language": "Por favor seja educado no chat. Tanto linguagem ofensiva ou inapropriada podem terminar em silence.",
    "language-specific": "Por favor, utilize o idioma apropriado do canal que está conversando.\nUsar palavras ou frases romanizadas não é permitido em canais de língua específica, como o #japanese.",
    "lazer": "osu!lazer é o codinome dado à futura versão open-source do osu!. Veja mais sobre isso [https://github.com/ppy/osu aqui]!",
    "level": "Seu nível é baseado no total de seus pontos acumulados. Isso inclui qualquer ponto ranked, seja falhando ou completado. Você irá aumentar seu level gradualmente apenas jogando osu!",
    "lines": "Tente manter suas frases em uma única linha quando possível, evitando assim tomar um silence.",
    "link": "Para fazer seu texto com ligação a alguma coisa, use o seguinte formato: [endereço texto], onde o endereço é onde você colocará o url, e o texto o texto que você quer que seja mostrado. [https://osu.ppy.sh/ Desse jeito!]. Não esqueça do http://.\nAbusando dessa funcionalidade, como fazer ligação para material inapropriado ou notificar pessoas usando seu nome escondido, poderá ser punível.",
    "lobby": "Por favor utilize apenas o #lobby para divulgar ou convidar pessoas para suas partidas multiplayer. Além disso, o #lobby é um canal multi-idiomas.\nCaso deseje conversar sobre qualquer coisa dentro de sua partida, utilize apenas o canal #multiplayer.",
    "localisation": "Encontre o projeto de localização do osu! [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 aqui]",
    "long-link": "Por favor não cole links longos no chat!\nUse o [link texto] se realmente precisar.",
    "long-text": "Por favor, não cole textos longos no chat. Fazer isto pode resultar em um silence.",
    "loved": "Loved é um novo sistema de ranking baseado na comunidade que dá placares para mapas que não são ranqueados! [https://osu.ppy.sh/news/151925254083 Leia mais sobre isso aqui!]\n",
    "mac": "[https://osx.ppy.sh Execute o osu! no seu Mac]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Mappers são pessoas ocupadas, e mapear requer tempo e trabalho. Pedidos normalmente não são correspondidos. Por que você mesmo não tenta mapear?",
    "mapping": "Vá [https://osu.ppy.sh/forum/p/988111 here] para guias sobre mapping.",
    "mat": "O Mapping Assistance Team era um antigo grupo de usuários que ajudavam o BAT no processo de ranking.\nRIP MAT 23-04-2013\n",
    "modhelp": "Se você está procurando ajuda em algo relacionado a beatmapping, se pronuncie no #mapping! Mas lembre-se, o #mapping é um canal em Inglês.",
    "modqueue": "[https://osu.ppy.sh/forum/60 Aqui] ficam as Modding Queues. Caso precise de algum mod em seu mapa sempre tente procurar por uma Queue aberta! Lembre-se que a maioria fala inglês.",
    "modreqs": "Por favor vá para o #modreqs para pedir mods em seus mapas. Tenha em mente que os BNs nem sempre tem tempo para te atender, e até estão cuidando de pedidos prévios. Então tenha certeza de pedir também aos usuários comuns para modarem seu map.",
    "multi-invite": "Para convidar alguem para sua sala multiplayer, clique no usuário desejado na sua lista de usuários online (F9) e clique na opção Convidar para jogar.\nVocê também pode digitar /invite seguido pelo username daquele que você deseja convidar.",
    "multi-link": "[https://osu.ppy.sh/community/forums/topics/1362982 Como criar um link direto para sua sala de multiplayer]",
    "multiaccounting": "Você realmente, realmente não deve criar múltiplas contas. Você será descoberto e tomará um silence imenso ou será banido, estamos de olho.",
    "multiplayer": "Por favor divulgue suas salas no #lobby, e em nenhum outro lugar.\nSe não tem outros usuários ativos, por que não jogar solo e tentar novamente mais tarde?",
    "mwc": "Um torneio mundial de osu! Mania. Leia [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 wiki isto aqui] para mais informação.",
    "nat": "O [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] administra os Beatmap Nominators e supervisiona o sistema de ranking no geral. \nEles também são responsáveis em avaliar os atuais e futuros Beatmap Nominators, assim como mediar vetos e outras disputas relacionadas ao mapping.",
    "news": "osu! muda de tempos em tempos graças à comunidade que o mantém funcionando e vivo. Se mantenha informado checando a [https://osu.ppy.sh/home/news página de notícias]!",
    "nightcore": "Aproveite seus mapas favoritos em estilo Nightcore!\nSimplesmente clique duas vezes sobre o mod DoubleTime para revelar o mod Nightcore!",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Digite /np para mostrar para os outros que música você está ouvindo ou jogando.",
    "nsfw": "Comentários de conteúdo explicitamente sexual não são permitidos. osu! é um jogo livre para todas as idades, então por favor, mantenha o chat limpo. Caso desrespeite essa regra, poderá ser silenciado sem nenhum aviso prévio.",
    "osu": "#osu é para discutir sobre osu!. Por favor discuta jogabilidade lá, não neste canal.\n",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 O tópico oficial do osu!tablet.] - Leia isso para obter mais informações sobre o osu!tablet e suas opções de pré-compra.",
    "osu!talk": "osu!talk é um talk show feito pelo deadbeat e pelo ztrot, onde eles entrevistam membros da comunidade e discutem eventos como as World Cups. Ele foi substituído pelo osu! coffee hour após os hosts se aposentarem da staff.",
    "osucore": "É uma piada de Primeiro de Abril feita em 2011. Todos os mapas ficaram em velocidade DoubleTime e tiveram seu tom alterado.\nRetornou mais tarde como Nightcore mod, que tem os mesmos efeitos que o DoubleTime naquele dia.",
    "osu!droid": "O [https://osu.ppy.sh/home/news/2017-01-21-aspire-returns-for-2017 osu!droid] é um porte do jogo original para a plataforma Android.\nO projeto foi abandonado pelos desenvolvedores e retirado da Google Play Store desde 2016 por sua inatividade e avaliações negativas.",
    "osumania": "Por favor use #osumania para discussões relacionados com esse modo de jogo.\n",
    "osustream": "[http://www.osustream.com osu!stream] é a versão iOS do osu!, feito e atualizado pelo peppy!",
    "osz": "O formato do beatmap que você baixou para jogar no osu. Arquivos osz precisam ser extraidos pelo próprio osu!, se não poderá ocorrer problemas",
    "osz2": "Um novo formato de beatmap que significa que cada arquivo contido pode ser criptografado, atualizado e transmitido independente de todos os outros arquivos. Arquivos osz2 não precisaram ser extraídos e sempre serão mantidos como .osz2 em sua pasta de músicas.",
    "owc": "Um torneio mundial de osu!. [https://osu.ppy.sh/wiki/OWC Clique aqui] para mais informações.\n",
    "peppy": "peppy é o desenvolvedor do osu! e cuida da maior parte do projeto sozinho.",
    "perfect": "Não pegou aquele SS que tanto queria? Esse mod irá automaticamente recomeçar o mapa para você se você fizer um único erro.\nVocê poderá encontrá-lo ao clicar duas vezes sobre o mod SuddenDeath (morte súbita) no menu de seleção de mods.",
    "ping": "Pong!",
    "pippi": "O personagem mascote do osu!\nPippi-don é a versão taiko (tambor) da Pippi.",
    "piracy": "Por favor não discuta sobre softwares pirateados no chat. É proibido e pode acabar em silence.",
    "play-shortcuts": "Lista completa de teclas de atalho: [[Shortcut_Key_Reference]]",
    "pm": "Para falar em privado com algúem, clique no nome desejado no chat ou no painel de usuário na tela de usuários online (F9) e em seguida clique em começar conversa.\nVocê também poderá usar o comando /msg <username> <mensagem> ou usar /chat <username> ou /query <username>, que criará uma nova aba separada no chat.\nPara rapidamente respondar á última mensagem privada recebida, poderá simplesmente digitar /r <mensagem>. Remova os < >, claro.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "[https://osu.ppy.sh/wiki/PT:PP Pontos de Perfomance] (pp) são a principal métrica de ranking do osu!",
    "pp-rework-lazer": "",
    "preview": "O ponto de preview (prévia) é o ponto na música onde começará a tocar no menu de seleção de música.\nUma preview apropriada no ponto onde a música é bem representada, como no começo do refrão. Vá no Timing na barra de ferramentas e clique Set Current Position as Preview Point para escolher um.",
    "qat": "O Quality Assurance Team supervisionava a qualidade e jogabilidade de mapas recém qualificados.\r\nApós grande mudança no sistema de ranking, em abril de 2019, eles tornaram-se o Nomination Assessment Team, focando em outras áreas.",
    "qualified": "Beatmap Nominators nominam mapas qualificados como sendo adequados para ranking onde você pode conseguir ranks sem performance points.\nSe um mapa não tem problema algum e está qualificado por uma semana, o mesmo será rankeado. Caso contrário, ele volta aos pendentes e os scores são apagados.",
    "ranked": "Um mapa Ranked é um beatmap que foi aprovado pela comunidade. \nQuando você joga um mapa Ranked, os pontos adquiridos contam em seu total de pontos ranked acumulados. Esses mapas são idenficados por um ícone de Duas setas pra cima.",
    "ranking-criteria": "Para informação sobre os critério de ranking, clique [https://osu.ppy.sh/wiki/Ranking_Criteria aqui].",
    "redname": "Usuários com nome vermelho pertencem ao [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team] ou ao [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team]",
    "report": "Use o formato abaixo para reportar comportamento inapropriado: !report <nome_de_usuário> <razão>\nReports NÃO são vistos por outras pessoas no chat e precisam ser feitos em canais públicos. Evite usá-los em uma mensagem privada (PM).\nVocê também pode reportar clicando no nome de um usuário e no comando Reportar Usuário...",
    "report-abuse": "Por favor evite enviar muitos reports de uma só vez, isso não ajudará a trazer justiça mais rápido. Evite também reports brancos ou sem razão.\nNa verdade, você poderá acabar silenciado por fazer spam no chat dos moderadores.",
    "request": "Tentando encontrar algo para fazer mod? Clique [https://osu.ppy.sh/p/beatmaplist&r=8 aqui] ou digite !request para um link random de um mapa.",
    "respect": "\nPor favor, seja respeitoso com os outros jogadores.",
    "roll-abuse": "Por favor não abuse do comando !roll - é bastante provável que você acabe silenciado!",
    "romaji": "Por favor, não utilize Romaji (japonês romanizado) de forma constante. Você pode acabar sendo silenciado.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Você poderá fazer sua própria sala se não existe nenhuma disponível.",
    "rp": "Você está livre para fazer roleplay nos canais apropriados do osu!, no entanto, você deve manter em mente que não deve incomodar outras pessoas no canal.",
    "rules": "[https://osu.ppy.sh/wiki/pt-br/Rules Regras oficiais do osu!]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "De tempos em tempos, osu! sofre ataques DDoS.\nDurante esse tempo, o Bancho poderá ficar instável ou impossivel de estabelecer uma conexão.\nSe você suspeita que isso aconteceu, veja o [https://twitter.com/osustatus @osustatus] no twiiter ou venha [https://status.ppy.sh aqui] para mais informações.",
    "sb": "Guia de Storyboarding: https://osu.ppy.sh/forum/t/1869\nComo usar o editor de Storyboard: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "scorev2 é o novo algorítmo de pontuação que limita todo o placar em 1 milhão de pontos, excluindo spinners e mods.\nTambém modifica o comportamento dos sliders para que exijam a mesma precisão que os hitcircles.",
    "scoring": "Como o osu! calcula o score: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Um silence significa que você está impedido de falar no chat ou postar no fórum, exceto nos fóruns de Suporte Técnico.\nSilences começam em 5 minutes pela primeira infração, e então duplica para cada infração após a mesma. Infrações mais graves poderão fazer muito mais que apenas duplicar o silence anterior.\nSilences são aplicados por atos conflituosos ou contra as regras, então por favor siga as regras e você ficará bem.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 FAQ de Skinning]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Não deixe o osu! te manter acordado até as 4 da madrugada. Dormir é importante!]",
    "songs-not-appearing": "Se suas músicas não estão aparecendo no menu de seleção, tente pressionar F5.",
    "spaces": "Por favor, não fique adicionando espaços entre cada letra ou palavra. Isso deixa o canal bagunçado e pode resultar em um silence.",
    "spam": "Por favor, não fique spammando no chat. É irritante e geralmente termina em silence.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Para spectar outro jogador, digite /watch <username>, ou clique no seu nome no chat ou painel de usuário e clique em Começar a assistir.\nTenha certeza que você tem o mesmo mapa que ele/ela está jogando!",
    "spoiler": "Dar spoilers (escrever algo significativo sobre um enredo) de algum anime, seriado, mangá, etc... é proibido e punível com silence.",
    "status": "Para atualizações no estado do sistema do osu!, por favor vá ao [http://twitter.com/osustatus @osustatus]. Para informações sobre o estado do servidor, veja [https://status.ppy.sh isso].",
    "store": "[http://store.ppy.sh/ Bem-vindo(a) a loja do osu!], aqui você pode comprar várias coisas bem legais relacionadas ao osu!.",
    "submit": "[https://osu.ppy.sh/wiki/Submission Beatmap FAQ de Entrada.]",
    "suck": "Não se preocupe, a prática leva à perfeição! Play more.",
    "supporter": "Se torne um [https://osu.ppy.sh/p/support supporter]! Você terá diversos benefícios, além de ajudar no desenvolvimento e manutenção do próprio jogo.",
    "supporter-please": "Por favor, não fique pedindo aos outros usuários para que lhe comprem supporter. [https://osu.ppy.sh/p/support Ao invés disso, adquira aqui!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Se seu cursor fica voando por toda a tela quando você tenta movê-lo, tenha certeza de que sua sensibilidade está em 1.00x.\nSe seu cursor não se move de maneira alguma, tenha certeza de desativar a opção Raw Input no menu de opções.\nPara qualquer outro tipo de duvida, clique [https://osu.ppy.sh/t/87301 aqui].",
    "tag": "No modo de tag no multiplayer, todos os jogadores têm turnos clicando num dos combos do mapa de cada vez. Não existe vitorioso ou perdedor, visto que todos jogam na mesma equipe.\nEm spinners, todos os jogadores participam. Se algum jogador fracassar em completar o spinner, o combo é resetado. Cada bônus de spinner de cada jogador é adicionado ao score total da equipe.",
    "taiko": "Um tambor Japonês destacado pelas séries de jogos da Bandai-Namco. o Modo Taiko do osu! simula esses jogos ao eliminar a colocação de batida, forçando o jogador a focar somente no ritmo do mapa. \n[https://osu.ppy.sh/forum/t/4363 Aprenda a jogar aqui!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Guia de mapping de Taiko]",
    "taiko-maps": "Você poderá encontrar mapas autênticos de Taiko no Tatsujin [https://osu.ppy.sh/forum/t/5397 aqui.]",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Você poderia parar de conversar sobre esse assunto e falar sobre outra coisa?",
    "training": "[https://osu.ppy.sh/forum/t/4280 Treinamento]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 Lista de vídeo tutoriais no osu! e mapping atualizados.] Sinta-se livre para fazer um e colocá-lo no tópico. [https://osu.ppy.sh/forum/t/60228 Lista de guias úteis para mappers/modders]",
    "twc": "Um torneio de osu! Taiko global.\n[https://new.ppy.sh/wiki/Tournaments/TWC/2017/ wiki page] Veja esse tópico para mais informações.]",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Por favor evite usar caracteres unicode/especiais no chat em geral.",
    "upload-cap": "Para manter os mappers dedicados aos seus mapas em progresso, há um limite na quantia de mapas que pode-se ter em progresso de uma só vez.\nÉ permitido entre 3 e 6 mapas ativos para não-supporters e 5 a 10 para supporters, dependendo da quantia de mapas préviamente rankeados que eles possuem.\n",
    "utf8": "Por favor defina seu cliente IRC para código-pagina UTF-8, desse jeito seu texto será entendido pelos jogadores de osu! e os outros usuários de IRC.",
    "videogames": "Assuntos sobre Videogames podem ser discutidos no #osu, mas se isso incomodar o chat ou mais de uma conversa esta acontecendo, por favor vá para o chat #videogames",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Bem-vindo(a) ao osu! Se tiver algum problema ou alguma dúvida, por favor não hesite em perguntar no #portuguese ou no #help! Divirta-se!",
    "when": "Quando estiver pronto.",
    "wiki": "A [https://osu.ppy.sh/wiki/ osu!wiki] está sendo movida para o GitHub: [https://github.com/ppy/osu-wiki/ppy/osu-wiki]",
    "wiki-link": "Você pode criar um link para páginas da wiki, colocando o nome da página entre dois colchetes como este: [[...]]\nPor exemplo, [[Kudosu]] é criado digitando Kudosu entre dois colchetes [[...]].",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 216 active FAQs (out of a possible 217) in the Portuguese (Português) language.",
    "completion": "The Portuguese (Português) FAQ as of last update is 99.54% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
