
strings = {

    "academy": "",
    "achievements": "Achievementele pot fi obţinute prin efectuarea unei anumite acțiuni, cum ar fi obţinerea unui combo mare în cadrul unei mape sau jucarea fiecărei mape dintr-un set de mape. Vă puteţi vedea achievementele in profilul dumneavoastră. Pentru majoritatea achievementuri-lor e destul de clar ce trebuie să faci pentru a le obţine, însă pentru unele trebuie sa vă daţi seama singuri ce e de făcut.",
    "add-skin": "[https://osu.ppy.sh/forum/t/3580 Cum să adaugi skin-uri.]",
    "advertising": "A face publicitate unui produs ce nu are legatură cu osu! este interzis. Repetarea acestei acţiuni sau persoanele care ofensează regula vor primi cel puţin un silence.",
    "answer": "Dacă nu există reacţie la răspunsul dumneavoastră asta înseamnă că persoanele probabil nu ştiu răspunsul sau nu vor să raspundă cu Da.",
    "appeal": "Pentru a face o contestare a silence, trimiteţi un mesaj privat pe forum unui [[admin]] ce include motivele din cauza cărora aţi fost silenţionaţi pe nedrept. Un recurs cu succes vă va şterge infracţiunea de pe profil si vă va anula silence-ul, daca este incă in efect. Vă rugăm să reţineţi că silence-urile sunt de obicei bine gândite si meritate, aşa că recursul nu vă garantează că infracţiunea va fi ştearsă. Să fiţi siguri că aveţi motive bune sau evidenţă înainte să contestaţi decizia.",
    "approved": "O mapă Aprobată este tehnic unrank-abilă (din cauza lungimii, a scorului,etc.), dar care e considerată în regula de catre membrii din Echipa de Aprobare a Mapelor. Mapele care sunt aprobate au propria lot tabela cu scoruri, ca şi cele ranked. Mapele aprobate pot fi distinse după faptul că au icon-ul ce reprezintă o Flacară in loc de o icon-ul ce reprezintă o Inimă.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "Adresaţi-vă doar întrebarea. Nu-i puneţi pe alţii să vă raspundă la ea.",
    "attention": "Se pare că nimanui nu ii pasă de ce ziceţi. Ar fi bine să vă opriţi acum.",
    "avatar-change": "Vă puteţi schimba avatarul [https://osu.ppy.sh/home/account/edit#avatar aici].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Sunt un bot. De asemenea, Bancho este serverul principal al osu!.",
    "beatmapping": "Citeşte [[Beatmapping]] pentru a găsi sfaturi generale.",
    "beginner": "[https://osu.ppy.sh/forum/t/5456 Antrenamentul incepătorului!]",
    "bn": "",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Dacă sunteţi foarte plictisit, gasiţi-vă altceva de facut.] Sunt destule de făcut online. Plictiseala nu este o scuză pentru a te plânge sau a spama în chat.",
    "bug": "Vă rugăm să raportaţi bug-urile pe [https://osu.ppy.sh/forum/5 forum], nu în chat.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "\n\nScrisul În\nAcest Fel Nu Este Grozav, Corect, Sau Înspre Beneficiul Cuiva. Fă-ți un favor\nsi oprește-te din scrisul în acel fel (capping) acum. Înlătură tastele shift și\ncaps lock de pe tastatura ta. \n\n",
    "caps": "Folosirea literelor mari se considera ţipăt. Vă rugăm să controlaţi numărul literelor mari din mesajele dumneavoastră pentru a arăta respect faţă de restul membrilor chat-ului.",
    "change-modes": "",
    "change-name": "„Pentru a îți schimba username-ul, prima dată trebuie să devii un [https://osu.ppy.sh/p/support osu! supporter!]„Pentru a îți schimba username-ul, prima dată trebuie să\ndevii un [https://osu.ppy.sh/p/support osu! supporter!]\n\nDupă aceea, [https://osu.ppy.sh/forum/t/34694 citește asta] pentru a afla mai\nmulte despre schimbările de nume!”",
    "changelog": "Adiţiile recente si rezolvările bug-urilor pot fi gasite pe [https://osu.ppy.sh/p/changelog changelog].",
    "chars": "Vă rugam să folosiți doar litere standard in\ncanalele cu limba maternă nedefinită.",
    "charts": "",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "",
    "colour": "",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "",
    "comment": "",
    "comment-color": "A normal user can only comment in white.  A [https://osu.ppy.sh/p/support supporter] can customize their comment color.",
    "conferencemode": "",
    "country-ranking": "",
    "critic": "Te rog ţine criticile într-un mod constructiv. Oferă sugestii alternative sau metode de a rezolva probleme de care eşti sigur că există.",
    "ctb": "",
    "cutting-edge": "",
    "cwc": "",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Tratează aşa cum vrei să fi tratat. Dacă eşti un fel de masochist verbal, asumă-ţi că restul persoanelor nu sunt.",
    "disable-this": "",
    "distance-snap": "",
    "dont-ask-peppy": "Te rog nu îl întreba pe peppy tot timpul - el este destul de ocupat. Simte-te liber şi întreabă pe oricine altcineva de pe canal!",
    "douche": "",
    "download": "",
    "drugs": "",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "",
    "english": "#english este pentru disctuţii generale despre orice lucru care nu are un canal dedicat. Da, asta include anime/manga. Şi trenuri.",
    "evade": "",
    "fallback": "",
    "faq": "Tu foloseşti acum sistemul FAQ osu!Bancho. osu!wiki: https://osu.ppy.sh/wiki",
    "feature": "Dacă ai idei pentru joc, postează-le in subforumul [http://osu.ppy.sh/forum/4 Cereri Pentru Viitor]",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "",
    "foul-play": "",
    "percolate": "",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "",
    "friends-list": "",
    "fullscreen": "",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "",
    "gmt": "",
    "english-help": "",
    "grammar": "",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "",
    "hacked": "Dacă credeți că ați\nfost hack-uit, vă rugăm să ne trimiteți un e-mail la adresa accounts@ppy.sh pentru a vă putea ajuta.\nEșecul în a face asta poate rezulta în închiderea cont-ului.",
    "hard": "",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "",
    "hitsound-library": "",
    "hl": "",
    "how-to-get-modded": "",
    "how-to-bn": "BNii sunt promovați bazat pe calitatea de modare si activitate. Dacă ceri să fii un BN, șansele sunt de a nu devenii unul. Dar, daca ești interesat, citește [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator this].",
    "how-to-gmt": "",
    "how-to-play": "\n\n[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F\nDă click pe acest link pentru a invăța cum să joci!]\n\n",
    "how-to-rank": "",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "",
    "ignore": "",
    "import": "",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "",
    "irc": "",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "",
    "kiai": "",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Câștigă [https://osu.ppy.sh/wiki/Kudosu kudosu] prin modarea mapelor celorlalți.",
    "lag": "",
    "language": "Vă rugăm să fiți politicos în camera de chat",
    "language-specific": "",
    "lazer": "",
    "level": "",
    "lines": "Vă rugăm să vă păstraţi mesajul în cât mai puţine linii pentru a nu fi silenţiaţi.",
    "link": "",
    "lobby": "",
    "localisation": "",
    "long-link": "",
    "long-text": "",
    "loved": "",
    "mac": "",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "",
    "mapping": "",
    "mat": "",
    "modhelp": "",
    "modqueue": "",
    "modreqs": "",
    "multi-invite": "",
    "multi-link": "",
    "multiaccounting": "",
    "multiplayer": "",
    "mwc": "",
    "nat": "",
    "news": "",
    "nightcore": "",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "",
    "nsfw": "",
    "osu": "",
    "osu!tablet": "",
    "osu!talk": "",
    "osucore": "",
    "osu!droid": "",
    "osumania": "",
    "osustream": "",
    "osz": "",
    "osz2": "",
    "owc": "",
    "peppy": "",
    "perfect": "",
    "ping": "Pong!",
    "pippi": "",
    "piracy": "",
    "play-shortcuts": "",
    "pm": "",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "",
    "pp-rework-lazer": "",
    "preview": "",
    "qat": "",
    "qualified": "",
    "ranked": "",
    "ranking-criteria": "",
    "redname": "",
    "report": "",
    "report-abuse": "",
    "request": "",
    "respect": "",
    "roll-abuse": "",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "",
    "rp": "",
    "rules": "",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "",
    "sb": "",
    "scorev2": "",
    "scoring": "",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "",
    "sleep": "",
    "songs-not-appearing": "",
    "spaces": "",
    "spam": "",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "",
    "spoiler": "",
    "status": "",
    "store": "",
    "submit": "",
    "suck": "",
    "supporter": "",
    "supporter-please": "",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "",
    "tag": "",
    "taiko": "",
    "taiko-mapping": "",
    "taiko-maps": "",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "",
    "training": "",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "",
    "twc": "",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Vă rugam să folosiți doar litere standard in\ncanalele cu limba maternă nedefinită.",
    "upload-cap": "",
    "utf8": "",
    "videogames": "",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Bine ai venit pe osu! Dacă aveți vreo problemă sau întrebare care necesită\nun răspuns, vă rog să vizitați #help. Distrați-vă!",
    "when": "Când este gata.",
    "wiki": "",
    "wiki-link": "",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 77 active FAQs (out of a possible 217) in the Romanian (Română) language.",
    "completion": "",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
