
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy Кликни овде] да пронађеш osu! академију - Видео лекције, за све везано за osu!",
    "achievements": "Достигнућа се добијају постизањем нечег специјалног у току песме, рецимо, ако добијеш велики комбо или пређеш све мапе у одређеном тематском пакету. Ваш профил показује достигнућа које сте постигли, и оне које би тек требали. Понекад само име достигнућа говори шта треба урадити да би га добио.",
    "add-skin": "[https://osu.ppy.sh/forum/t/3580 Погледај како да додаш теме у osu!]",
    "advertising": "Рекламирање невезано за osu! није дозвољено и можда добијете искључење из чета. Ово укључује third-party чет сервере као што су Discord или Teamspeak.",
    "answer": "Ако ти нико није одговорио, постоји шанса да нико не зна одговор! Покуша да потражиш по форуму, ако је везано за osu!.",
    "appeal": "Ако сте кажњени, а мислите да је то грешка, контактирајте админа слањем мејла на accounts@ppy.sh и објасните вашу ситуацију. Али запамтите, администатори су такође људи! Ако будете пристојни, имате више шанси да дају све од себе да вам уклоне казну.",
    "approved": "Потвђене битмапе из неког разлога не могу бити ранковане, али ипак су довољно добре да их људи могу играти са скорбордом и свиме осталим! Знаћете да је битмапа потвђена ако има икону пламена уместо срца.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "[[https://osu.ppy.sh/wiki/Contests#aspire Aspire]] је било премиерно битмапинг такмичење које се одржавало од 2016–2020.",
    "ask": "Најбољи начин за добијање одговора је да само питаш своје питање - нема много смисла питати питање о питању питања!",
    "attention": "Можеш ли да престанеш? Нико не слуша твоје брбљање...",
    "avatar-change": "[https://osu.ppy.sh/home/account/edit#avatar Овде] можеш променити свој аватар.",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Ћао! Ја сам BanchoBot! Драго ми је! Али ипак, ја сам бот па не могу имати конверзацију са тобом. :(",
    "beatmapping": "Овде су неки савети о [https://osu.ppy.sh/wiki/Beatmapping битмаповању!]",
    "beginner": "Кликните [https://osu.ppy.sh/forum/t/5456 овде] ако тражите почетничке мапе.",
    "bn": "[[Група за номинацију битмапа]] је група људи који су одговорни за ранковање битмапа и управљање модерације битмапа које су на чекању у ранкинг циклус. Можете да причате са њима ако имате било каква питања или савет о маповању или модовању.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Нема потребе причати осталима да сте сморени. Направите паузу, или пробајте да играте нешто друго!]",
    "bug": "Ако мислите да сте нашли квар,пријавите га [https://osu.ppy.sh/forum/5 овде]. Само се уверите да нико други није истакнуо ваш проблем пре вас.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Молимо вас да не користите велико слово на почетку сваке речи - то чини све што напишете катастрашно",
    "caps": "Молимо вас да не пишете све великим словима - то је нежељено на чету и можете бити кажњени.",
    "change-modes": "Да би променио режим игре, изабери жељену песму, кликни на мод дугме на дну екрана или користите контрол + типке од 1 до 4. Имајте у виду да се поједине мапе могу играти само у одређеним модовима.",
    "change-name": "Да би променио корисничко име, прво мораш да постанеш [https://osu.ppy.sh/p/support osu! супортер]. Након тога можеш да промениш име [https://store.ppy.sh/store/product/32 овде]!\nЗа заxтењање промене имена назад на старо,молим вас пошаљите е-мајл accounts@ppy.sh са детаљима.",
    "changelog": "Сви апдејти (надоградње) игре, Банчо и веб сајт могу се пронаћи на\n osu! development [https://osu.ppy.sh/p/changelog changelog!]",
    "chars": "Молимо да избегавате коришћење уникод знакова у главном чету.",
    "charts": "osu! chart-ови су тематски пакети који се објављују једном месечно. Можете их пронаћи [https://osu.ppy.sh/p/chart овде!]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Светложута: Обични корисник | Жута: [https://osu.ppy.sh/p/support \nСупортер] | Црвена: Члан [https://osu.ppy.sh/wiki/QAT QAT-а] или\n[https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT-]\nБела: Ви, или /me порука | Тамно плава: Приватна порука | Зелена: Линија (текста) где сте ви поменути. | Розе: BanchoBot",
    "colour": "Светложута: Обични корисник | Жута: [https://osu.ppy.sh/p/support \nСупортер] | Црвена: Члан [https://osu.ppy.sh/wiki/QAT QAT-а] или\n[https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT-]\nБела: Ви, или /me порука | Тамно плава: Приватна порука | Зелена: Линија (текста) где сте ви поменути. | Розе: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "И ако су команде лаке за коришћење, молимо да их не користите превише. Тада се то сматра спамом и можете бити кажњени.",
    "comment": "Ако желиш да коментаришеш мапу уживо, кликни Discussion дугме, напиши нешто, и кликни ентер. Ако не видиш коментаре на екрану, изабери Show Comments дугме у панелу за дискусију.",
    "comment-color": "Нормалан корисник може само да коментарише у белој боји. [https://osu.ppy.sh/p/support супортер] може да модификује боју коментара.",
    "conferencemode": "Преплављен си Ушао/Изашао порукама на IRC-у? [http://wiki.xkcd.com/irc/Hide_join_part_messages Ово] може бити од помоћи!",
    "country-ranking": "Погледај различите резултате [https://osu.ppy.sh/p/countryranking Државниx рангова] овде.",
    "critic": "Молимо те да критике буду конструктивне. Предложи алтернативе или начине да се поправе проблеми за које си забринут.",
    "ctb": "Треба ли ти помоћ са Catch the Beat? [https://osu.ppy.sh/wiki/Catch_the_Beat Овде је] вики страница!",
    "cutting-edge": "Cutting-edge је експериментална верзија Osu!-a користи се како би се новитети испобали пре него што буду објављени у стабилној верзији. Можете је изабрати у опцијама! [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues Прочитајте,] ако имате проблема са апдејтовањем вашег клијента.",
    "cwc": "Светски osu! Catch the Beat турнир. Погледај ову [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 вики страницу] за више информација.",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\r\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\r\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Третирај друге као што ти желиш да будеш третиран. Ако сте нека врста вербалног мазохисте, претпоставите да сви други нису.",
    "disable-this": "Новине се додају ретко, међутим можете тражити да нешто буде додано путем [https://osu.ppy.sh/forum/4 Feature Requests форума], ",
    "distance-snap": "Distance snap је алатка која држи тачну релативну удаљеност између нота на основу њихових позиција на временској линији. Детаљи: [[Distance_Snap]]",
    "dont-ask-peppy": "Молим вас немојте питати Пепија сваки час - он је веома заузет. Али, слободно питајте било кога другог у овом каналу!",
    "douche": "Као свеобухватно правило, избегавање реда и цивилности користећи рупе у правилима је кажњавајуће од стране административног тима, који задржавају право на дискрецију током кажњавања. Не би требало да постоји правило које говори да не будеш кретен, али за сваки случај: немој да будеш кретен.",
    "download": "Можеш преузети више битмапа[https://osu.ppy.sh/p/beatmaplist овде] или битмап паковања [https://osu.ppy.sh/beatmaps/packs овде]. У случају да не знаш како да их унесеш, можеш да прочиташ [http://i.imgur.com/kpX2N3m.jpg ово] да би сазнао/ла!",
    "drugs": "Молим вас, не разговарајте о било којим врстама дрога било где у осу! чету.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Прочитај [[Beatmapping#Keyboard_Shortcuts]] да би пронашао/ла листу пречица за едитор.",
    "english": "#english је за генералну дискусију о било чему што нема сопствени канал. Да, у ово спада и аниме/манга.",
    "evade": "Избегавање искључења је прекршај који може довести до бана. Банови су много, много гори од искључења.",
    "fallback": "Stable (Fallback) је стара верзија osu!-а која уклања подршку за DirectX да би поједноставио osu! framework. Ако сте промењени на ову верзију, Ваш компјутер је стар и не подржава новије и будуће верзије клијента. Ако желите да користите нову верзију клијента, ажурирајте Вашу графичку картицу и уверите се да подржава OpenGL, најбитнију ставку нових верзија. [https://osu.ppy.sh/wiki/GL_Support_Issues Кликните овде да сазнате како].",
    "faq": "Тренутно користите осу!Банчо FАQ систем. osu! wiki: https://osu.ppy.sh/wiki",
    "feature": "Ако имаш идеју за ову игрицу,постави је у  [https://osu.ppy.sh/forum/4 Feature Requests] подфорум.",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Избегавање чат филтера може довести до искључења. Молимо да поштујете то.",
    "foul-play": "Молимо Вас да пријавите људе који варају преко report дугмета на њиховом профилу, лоцирано [https://i.imgur.com/GG9xlLA.png овде]",
    "percolate": "Избегавање филтера може довести до казне. Молимо да поштујете то.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Овај чланак] ће вам помоћи да разумете ток маповања.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Да би сте додали некога за пријатеља, укуцајте /addfriend и затим његово корисничко име. Такође, можете кликнути на корисников панел у листи тренутно присутних играча (притисните F9) или стисните на њихово име у чету и кликните Add as friend. Такође их можете додати преко њиховог профила, кликом на опцију Add as friend",
    "friends-list": "Да видите листу ваших пријатеља на мрежи, притисните F9, и затим промените филтер на Friends. Такође можете видети целу листу пријатеља, и оних на мрежи, о оних ван ње кликом на опције на сајту. Уверите се да сте улоговани.",
    "fullscreen": "Можете да промените да ли ће игрица бити преко целог екрана или у прозору у Graphics секцији менија са опцијама. Такође можете да мењате режим рада са пречицом Alt+Enter.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Можете да нађете доста терминологије у osu! [[glossary]].",
    "gmt": "The [https://osu.ppy.sh/wiki/GMT Глобални Тим Модератора], укратко ГМТ, је група корисника који помажу да osu! ради. Они имају црвена имена у чету и зелена на форумима. Ова група помажу мониторингу форума и чета.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Прочитај, преради, радуј се.]",
    "grammar": "Пазите на граматику. Ситне грешке у писању и изговору су допустљиве. Не користите се клетвама, нити псовкама, то вас чини простим.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Не знате да играте? Желите да истражите свет маповања и модовања?\n[https://osu.ppy.sh/wiki/Guides Овде] можете наћи одговоре.",
    "hacked": "Ако мислите да сте хаковани, молимо вас контактирајте нас на accounts@ppy.sh. Ако то не учините, ваш налог може бити банован.",
    "hard": "Па јебига брате, вежбај још.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Уколико вам је потребна помоћ везана за osu!, питајте овде: #help",
    "hitsound-library": "Идите [https://osu.ppy.sh/forum/p/164927 here] да би сте нашли оригиналне звукове за вашу мапу.",
    "hl": "Молимо Вас да не кривите друге кориснике ако вас нотификују ако имате реч која се често користи као ваше корисничко име. То је ваша кривица! Можете искључити нотификације и звук који се чује када се она деси у опцијама.",
    "how-to-get-modded": "Ако желите да знате како да вам неко погледа мапу, кликните овде: [[Getting_Your_Map_Modded]]",
    "how-to-bn": "Ако хоћете постати BN, прочитајте [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator ово].",
    "how-to-gmt": "Глобални модератори су ручно изабрани у зависности од тога колико су допринели заједници. За више детаља, прочитајте вики страницу тима: [https://osu.ppy.sh/wiki/People/The_Team/Global_Moderation_Team Global Moderation Team]",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F Кликните на овај линк, ако желите да научите играти]",
    "how-to-rank": "Да би сазнала/о,прочитај [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Hyperdash се дешава када ухватите воће које сија црвеном бојом. Након хватања вашa dash брзина је повећана докле год не ухватите следеће воће или омашите. ",
    "ignore": "Да игноришете кориника укуцајте /ignore па име корисника. Нећете видети линије написане од корисника које игноришете, укључујући приватне пируке које вам можда шаљу, унесите /unigrnore па име, или само напустите игру и то ће поништити овај ефекат.",
    "import": "Прочитајте [http://i.imgur.com/kpX2N3m.jpg ово] да сазнате како убацити мапе у osu!",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Чекирањем Inherit previous timing settings кутије у F6 прозору едитора, та тајминг секција неће утицати на тајминг мапе, што може бити корисно за секције где се мења само јачина звука или звук који се користи. Такође је могуће да се наследи тајминг секција које имају или дуплиран или преполовљен BPM. Ако се нађете у ситуацији где овако користите тајминг секцију, молимо Вас да користите ову опцију.",
    "irc": "IRC сервер: irc.ppy.sh:6667\nЛозинка: https://osu.ppy.sh/p/irc\nВише детаља на https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Можете променити Ваше контроле у Input секцији у опцијама. Типке и њихова подешавања за osu!mania се мењају преко osu!mania layout дугмета.",
    "kiai": "Kiai мод је стилски ефекат који можете активирати у тајминг секцијама користећи Timing Setup Panel опције. Тајминг секције са kiai модом укљученим користе разне визуелне ефекте да би сте дочарали ефекте песме или мапу.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Заслужи [https://osu.ppy.sh/wiki/Kudosu кудосу] са помагањем другим људима око њихових мапа.",
    "lag": "Лоше перформансе могу бити изазване због [https://osu.ppy.sh/help/wiki/Performance_Troubleshooting разних проблема] - већина од њих вероватно изазвани процесима који раде на вашем рачунару. Ако сте сигурни да само osu! има проглема, питајте за помоћ преко [https://osu.ppy.sh/forum/5 форума за помоћ] са детаљима Вашег проблема и све што сте нашли и мислите да може бити разлог проблема.",
    "language": "Молимо Вас будите формални у чету. Неприкладно понашање може довести до казне.",
    "language-specific": "Молимо Вас да користите одговарајући језик у односу на канал у коме се налазите. Користећи романизоване речи или фразе нису изузетак за језике као што су јапански.",
    "lazer": "[https://www.youtube.com/watch?v=ut_SOreClcc шта је lazer?] То је име дато новој верзији osu! игрице.\nGitHub: [https://github.com/ppy/osu ppy/osu] | Преузмите: [https://github.com/ppy/osu/releases ppy/osu/releases]",
    "level": "Ваш ниво је базиран на тоталној скупљеној количини поена. Ово укључује сваки рангирани резултат, без обзира да ли сте изгубили или завршили ниво. Повећаваћете ниво део по део тако што ћете играти osu!",
    "lines": "Потрудите се да ваше реченице стану у једну линију, у супротном можете бити кажњени.",
    "link": "Да би линк на нешто личио, користите следећи формат: [линк\nтекст], где је 'линк' адреса коју желите линковати, и 'текст' је текст који желите приказати. [https://osu.ppy.sh/ Као ово, например!] Немојте заборавити на http:// .",
    "lobby": "Молимо Вас да користите #lobby за рекламирање мултиплејер лобија. Такође, #lobby је билингуална соба. Користите Вашу собу у #multiplayer за било какву даљу дискусију.",
    "localisation": "Пронађите osu! локализацијски пројекат \n[https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24\n овде].",
    "long-link": "Молимо вас немојте лепити предугачак линк у чет. Користите форумулу [линк текст], ако баш морате ставити линк. ",
    "long-text": "Молимо вас немојте лепити предугачак текст у чету. Превише текста може довести до казне.",
    "loved": "Loved је нови пројекат заједнице који даје мапама ранг листу иако не могу да добију ranked статус. [https://osu.ppy.sh/wiki/Project_Loved Можете наћи још информација овде!]",
    "mac": "[https://osx.ppy.sh Покрените osu! на вашем Mac-у]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Мапери су заузети људи, и маповање захтева много посла. Зашто не пробаш да мапујеш сам/а?",
    "mapping": "Идите [https://osu.ppy.sh/forum/p/988111 овде] за помоћ око маповања.",
    "mat": "",
    "modhelp": "За сва питања везана за модовање и маповање, упутите се на #mapping!",
    "modqueue": "[https://osu.ppy.sh/forum/60 Редови за модовање]",
    "modreqs": "Молимо Вас да користите #modreqs да би сте захтевали модове. Имајте на уму да BN можда неће увек имати времена и да имају људи који су их питали за исто то пре вас, тако да питајте и честе кориснике канала да модују ваше мапе. Да би сте тражили мод, користите /np команду или [линк текст] формат. Не заборавите да кажете хвала!",
    "multi-invite": "Да би сте позвали некога у ваш мулти лоби, кликните на корисника у F9 менију или кликните на њихово име у чету и изаберите Invite to game. Такође можете користити /invite команду пропраћеном са именом играча кога желите позвати.",
    "multi-link": "[https://osu.ppy.sh/community/forums/topics/338482 Како направити директан линк до Ваше мултиплејер собе]",
    "multiaccounting": "Стварно не би сте требали да правите вишеструке налоге. Бићете пронађени, можете бити кажњени на веома дугачак период, или чак бановани.",
    "multiplayer": "Молимо вас немојте рекламирати ваше мултиплејер игре у било ком другом каналу који није #lobby.",
    "mwc": "Светски osu!мania турнир. Погледајте [https://osu.ppy.sh/wiki/Tournaments/MWC/2019_4K ово] за више информација.",
    "nat": "[https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] надгледа номинаторе мапа (Beatmap Nominators) и воде рачуна о процесу рангирања мапа. Они су одговорни за процену тренутних и будућих номинатора мапа, као и решавање вето ситуација и других спорова везано за маповање и сличних тема.",
    "news": "osu! се мења са времена на време захваљујући људима који одржавају игру и учествују у заједници. Да би сте остали ажурни погледајте [https://osu.ppy.sh/home/news најновије вести]!",
    "nightcore": "Уживајте у вашим омиљеним мапама у Nightcore стилу! Једноставно кликните DoubleTime мод поново да би сте открили Nightcore мод! Nightcore мод је идентичан DoubleTime моду што се тиче бодовања.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Напиши ''/np'' да би показао/ла другима шта тренутно слушаш или играш у оsu!",
    "nsfw": "Експлицитан разговор није дозвољен. оsu! је за све узрасте, зато одржавајте чет чистим, или ћете ризиковати кажну без упозорења.",
    "osu": "#osu је за разговор о osu!. Молимо вас да дискусујете игрицу тамо, а не у овом каналу.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 Официјална страница!] - Прочитајте ово за све информације о таблету и опцијама за наручивање.",
    "osu!talk": "",
    "osucore": "",
    "osu!droid": "",
    "osumania": "Молим вас користите #osumania за дискусије везане ѕа осу!маниа.",
    "osustream": "[http://www.osustream.com осу!stream] је осу! за iOS уређаје,направљен и одржаван од стране Пепија.",
    "osz": "",
    "osz2": "",
    "owc": "Светски осу! турнир. Погледај ову [https://osu.ppy.sh/wiki/OWC вики страницу] за више информација.",
    "peppy": "Пепи је главни девелопер осу!-а и сређује већину пројекта сам.",
    "perfect": "Нисте добили тај SS? Овај мод аутоматски рестартује мапу за вас ако направите једну грешку. Можете га наћи тако што ће те кликнути десним кликом на SuddenDeath у ",
    "ping": "Pong!",
    "pippi": "Маскота осу!-а Пипи-дон је таико (бубањ) верзија Пипија.",
    "piracy": "Молимо вас немојте отворено дискусовати око пиратерије или садржаја заштићениx ауторским правима у генералном чету.",
    "play-shortcuts": "Цела листа дугмића за пречице: [[Shortcut_Key_Reference]]",
    "pm": "За слање приватне поруке некоме,кликни на нечије корисничко име у чету или на њихов кориснички панел на екрану за Доступне Кориснике и онда кликни Започни Чет. Такође можеш да користиш команду /msg <username> или /chat <username> или /query <username>, који ће отворити посебан језичак у чету.За брзо одговарање последње приватне поруке послате теби,можеш користити /r <message>. Наравно,избриши < >.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Поени перформансе (pp) је соновна мера ранковања у osu! Кликните овде [https://osu.ppy.sh/wiki/Performance_Points here] да сазнате више",
    "pp-rework-lazer": "",
    "preview": "",
    "qat": "",
    "qualified": "",
    "ranked": "\n",
    "ranking-criteria": "",
    "redname": "Корисници са црвеним именима су [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] или [https://osu.ppy.sh/wiki/QAT QAT].",
    "report": "Модератори понекад нису доступни; они су само људи и не могу читати чет цео дан. У случају да приметите да неко ради нешто глупо и нико ништа не предузима, молимо вас користите !report. Молимо вас да избегавате тужакање у банчоботовим приматним порукама, користите !report <user> <reason>.",
    "report-abuse": "Избегавајте слање више пријава за редом - то не помаже да се среди брже. Ито важи за слање празних или неразумних пријава. Заправо можете бити кажњени за спамовање модераторског чета.",
    "request": "",
    "respect": "",
    "roll-abuse": "Молимо вас немојте користити превише !ролл команду. Мозете добити силенце.",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Уколико нема доступне мултиплејер собе, зашто не бисте направили вашу. Можете да бирате песме!\n",
    "rp": "",
    "rules": "",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "\nС времена на време, Osu! бива DDos-ован. Током овог периода, Bancho може бити недоступан или нестабилан. Ако претпостављате да се то десило, проверите [https://twitter.com/osustatus @osustatus] Твитер. или [https://status.ppy.sh ово] за више информација. Ако се ово деси, и даље ће те бити у могућности да говрите - као да је нормално. Отварање нове теме, неће помоћи бржем решењу.",
    "sb": "",
    "scorev2": "",
    "scoring": "Како осу! рачуна резултате: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "",
    "sleep": "",
    "songs-not-appearing": "",
    "spaces": "",
    "spam": "Немојте спамовати. То смара и углавном доводи до казне.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "",
    "spoiler": "",
    "status": "",
    "store": "[http://store.ppy.sh/ Добро дошли у osu! продавницу],место где можете купити кул osu! стварчице!",
    "submit": "",
    "suck": "",
    "supporter": "",
    "supporter-please": "",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "",
    "tag": "",
    "taiko": "",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Водич за мапирање Таико]",
    "taiko-maps": "",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Да ли можете да одустанете од теме и да причате о нечему другом сада?",
    "training": "[https://osu.ppy.sh/forum/t/4280 Џејмс тренинг]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "",
    "twc": "Светски осу! Таико турнинг. Погледај ову   [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ вики страницу] за више информација.",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Молимо да избегавате коришћење уникод знакова у главном чету.",
    "upload-cap": "",
    "utf8": "",
    "videogames": "Теме везане за видео игрице могу бити дискусоване у #osu,али ако узнемирује чет или ако има више од једног разговора,молим вас идите у #videogames.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Добродошли у осу! Ако имате проблем или питање које треба одговорити, питајте добре људе у #help! Забавите се!",
    "when": "Када је спремно.",
    "wiki": "[https://osu.ppy.sh/wiki/ осу! Вики] - Учини је феноменалном!",
    "wiki-link": "",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 179 active FAQs (out of a possible 217) in the Serbian (Српски) language.",
    "completion": "The Serbian (Српски) FAQ as of last update is 82.49% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
