
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy osu!academy] — сборник обучающих видео по osu! (на английском)",
    "achievements": "Достижения даются за определённые игровые действия, например, набор большого комбо, или прохождение определённых наборов карт.\nСписок достижений можно увидеть у себя в профиле; названия некоторых из них намекают на требуемые действия.",
    "add-skin": "Если вы скачали файл формата .osk, дважды кликните по нему или перетащите в окно osu!.\nЕсли он формата .rar или .zip, извлеките содержимое в отдельную директорию и перенесите её в <место установки osu!>/Skins.\nПосле этого нажмите Ctrl-Alt-Shift-S в osu!.",
    "advertising": "Пожалуйста, не рекламируйте в чате вещи, которые не относятся к osu!, иначе вы можете получить сайленс.\nСюда относится реклама посторонних чатов и серверов Discord, Teamspeak, и так далее.",
    "answer": "Если реакции на вопрос нет, наверное, никто не знает ответ, либо не хочет в сотый раз проговаривать очевидные вещи. Попробуйте поискать по форуму.",
    "appeal": "Чтобы обжаловать (не)заслуженный сайленс или бан, напишите подробное письмо на английском на accounts@ppy.sh, стараясь не искажать факты.",
    "approved": "Категория Approval содержит карты повышенной сложности, либо с продолжительностью более 5 минут, не попавшие по этой причине под стандартные ограничения на ранк.\nРаньше такие карты попадали в отдельную категорию и имели в клиенте иконку пламени, но начиная с конца февраля 2014 их объединили с ранкнутыми картами.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire — конкурс нестандартных карт, проводившийся с 2016 по 2018. Подробности: [[Contests#aspire]] ",
    "ask": "Просто задайте вопрос, а не спрашивайте, можно ли спросить.",
    "attention": "Ваши сообщения никому не интересны. Пора остановиться.",
    "avatar-change": "Аватарку можно поменять [https://osu.ppy.sh/home/account/edit#avatar здесь].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Привет, я БанчоБот! Рад знакомству. Увы, поскольку я бот, у нас не получится поговорить по душам.",
    "beatmapping": "Вся информация о том, как сделать карту, находится на вики: [[Beatmapping]].",
    "beginner": "Тысячи лет назад новички играли [https://osu.ppy.sh/forum/t/5456 эти карты], но сейчас подойдёт любая сложность с названием Easy.\nВозможно, вам также пригодятся карты, которые [https://osu.ppy.sh/community/forums/topics/75291 удобно играть на тачскрине].",
    "bn": "[[Beatmap Nominators]] — группа, отвечающая за продвижение и номинацию карт на ранк.\nВы можете попросить номинаторов о совете или помощи в маппинге или моддинге.",
    "bored": "Если вам скучно, займитесь чем-нибудь другим, в интернетах много интересного. Скука — не повод писать в канал всякую чушь.",
    "bug": "Сообщайте о найденных багах не в чат, а [https://osu.ppy.sh/forum/5 на форум], проверив, что до вас этого никто не сделал.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Писать Каждое Слово С Большой Буквы ИлИ зАбоРчИкОм — некрасиво. Окажите нам услугу, вытащите Shift и Caps Lock из клавиатуры.",
    "caps": "Не пишите всё капсом, не засоряйте чат. Избыток капса может привести к сайленсу.",
    "change-modes": "Чтобы выбрать другой режим игры, откройте экран выбора песен, затем кликните по кнопке Mode в нижнем левом углу или используйте комбинации клавиш Ctrl+1–4.\nУчтите, что некоторые карты сделаны лишь для определенных режимов.",
    "change-name": "Изменить свой ник [https://store.ppy.sh/store/product/32 можно за деньги].\nЕсли вы хотите вернуть ник или внести небольшие изменения, напишите на accounts@ppy.sh с подробностями на английском.",
    "changelog": "Все обновления игры, серверной части и сайта описаны [https://osu.ppy.sh/p/changelog здесь].",
    "chars": "Пожалуйста, не злоупотребляйте спецсимволами, это может быть расценено как спам.",
    "charts": "Чарт — подборка карт, выпускаемая каждый месяц, либо подходящая под единую тематику, и имеющая свой топ.\nСписок чартов можно просмотреть [https://osu.ppy.sh/p/chart здесь].",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Бледно-жёлтый: обычный пользователь | Жёлтый: [https://osu.ppy.sh/p/support саппортер] | Красный: [https://osu.ppy.sh/wiki/NAT NAT] или [https://osu.ppy.sh/wiki/GMT GMT] | Белый: вы сами | Синий: личное сообщение | Зелёный: в строке содержится ваше имя | Розовый: БанчоБот",
    "colour": "Бледно-жёлтый: обычный пользователь | Жёлтый: [https://osu.ppy.sh/p/support саппортер] | Красный: [https://osu.ppy.sh/wiki/NAT NAT] или [https://osu.ppy.sh/wiki/GMT GMT] | Белый: вы сами | Синий: личное сообщение | Зелёный: в строке содержится ваше имя | Розовый: БанчоБот",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Пожалуйста, не злоупотребляйте командами чата. Это считается спамом и может привести к сайленсу.",
    "comment": "Реплеи можно комментировать, нажав при просмотре на кнопку Discussion с правой стороны.\nЧтобы отобразить комментарии, нажмите Show Comments на панели обсуждения.",
    "comment-color": "У обычных пользователей комментарии к реплеям могут быть только белого цвета, у [https://osu.ppy.sh/p/support саппортеров] — любого.",
    "conferencemode": "О том, как убрать сообщения о входе/выходе на канал в IRC, читайте [http://wiki.xkcd.com/irc/Hide_join_part_messages здесь].",
    "country-ranking": "[https://osu.ppy.sh/p/countryranking Топ стран].",
    "critic": "Пожалуйста, критикуйте конструктивно. Отзываться о человеке и его работе плохо только потому, что вам не нравится, — грубо, некрасиво и может привести к сайленсу.",
    "ctb": "Краткая справка по режиму osu!catch: [[Catch_The_Beat]].",
    "cutting-edge": "С веткой обновлений Cutting Edge вы всегда будете на острие прогресса osu!, опережая пользователей стабильной сборки.\nЕсли у вас возникли проблемы с обновлением, прочтите [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues справку на английском].",
    "cwc": "CWC — мировой турнир между игроками Catch the Beat. Информация о турнире находится [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 здесь].",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Не надо надоедать другим людям или неадекватно себя вести. То, что вам так нравится, не значит, что другие тоже так считают.",
    "disable-this": "Большинство возможностей osu! нельзя выключить, но вы можете попросить [https://osu.ppy.sh/forum/4 здесь] о добавлении настройки.",
    "distance-snap": "Distance Snap — это инструмент, позволяющий сохранить определённую дистанцию между объектами в зависимости от их положения на временной шкале. Подробнее: [[Distance_Snap]].",
    "dont-ask-peppy": "Не мучайте пеппи, у него и так много работы. Спросите лучше у кого-нибудь другого.",
    "douche": "Использование лазеек в правилах наказывается по усмотрению модерации.\nЕсли вам для того, чтобы хорошо себя вести, нужны правила и человек с палкой, это повод задуматься.",
    "download": "Отдельные карты можно скачивать [https://osu.ppy.sh/p/beatmaplist отсюда], а архивы с картами — [https://osu.ppy.sh/beatmaps/packs отсюда].",
    "drugs": "Разговоры о наркотиках и их употреблении запрещены.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Список горячих клавиш, используемых в редакторе: [[Beatmapping#Keyboard_Shortcuts]]",
    "english": "Чтобы общаться на английском на темы, для которых нет отдельных каналов, проследуйте в #english.\nДа, к этим темам относятся аниме и манга. И поезда.",
    "evade": "Попытки уклонения от сайленса приводят либо к длительному сайленсу, либо к бану. Подумайте, нужно ли вам это.",
    "fallback": "Stable (Fallback) — это устаревшая сборка osu!, где всё ещё применяется DirectX. В новых релизах он убран ради упрощения исходного кода, но для некоторых слабых компьютеров может быть необходим.\nЕсли вы хотите пользоваться новыми версиями osu!, обновите вашу видеокарту и/ли её драйвера и убедитесь, что они поддерживают OpenGL. [https://osu.ppy.sh/wiki/GL_Support_Issues Подробности здесь].",
    "faq": "Вы используете справочную систему osu!Bancho. Более подробную справку по osu! можно найти в [https://osu.ppy.sh/wiki вики].",
    "feature": "Чтобы попросить о нововведении, напишите в [https://osu.ppy.sh/forum/4 соответствующий форум].",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Пожалуйста, не пытайтесь обходить фильтры чата, это наказуемо.",
    "foul-play": "Если вы увидели читера, то отправьте на него жалобу с помощью [https://i.imgur.com/GG9xlLA.png кнопки в профиле] или трёх точек около рекорда на странице карты.\nНе нужно писать о читерах и их действиях в чат — это запрещено.",
    "percolate": "Пожалуйста, не пытайтесь обходить фильтры чата, это наказуемо.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Эта статья] поможет вам разобраться, что такое флоу в маппинге и как с ним обращаться.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Чтобы добавить друга, напишите /addfriend ник_друга или нажмите F9 и найдите пользователя по нику.\nЧтобы добавить друга через сайт, нужно открыть его профиль и кликнуть по ссылке Add as Friend.",
    "friends-list": "Чтобы посмотреть список друзей в сети, нажмите F9 и выберите сверху фильтр «Друзья». Полный список друзей можно увидеть [https://osu.ppy.sh/home/friends здесь].",
    "fullscreen": "Переключиться из полноэкранного режима в окно можно, нажав Alt+Enter или поискав в настройках слово Fullscreen.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "В [https://osu.ppy.sh/wiki/Glossary словарике (на английском)] можно найти расшифровку некоторых терминов.",
    "gmt": "[https://osu.ppy.sh/wiki/ru/GMT Global Moderation Team], или коротко GMT, — группа глобальных модераторов. Они отличаются от других пользователей цветом ника: он красный в чате, а на форуме — зелёный.\nМодераторы следят за порядком на форуме и в чате.",
    "english-help": "Чтобы повысить свои знания английского, прочтите [https://osu.ppy.sh/forum/t/12016 эту тему].",
    "grammar": "Старайтесь писать грамотно. Все допускают ошибки время от времени, но не надо намеренно искажать речь.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Ищете руководства по всему на свете, связанному с osu!? [https://osu.ppy.sh/wiki/Guides Вот они].",
    "hacked": "Если вы уверены, что вас взломали, напишите на accounts@ppy.sh. В противном случае, вас могут забанить за действия другого человека.",
    "hard": "Учись играть, салага.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Если вам внезапно нужна помощь, а тут никто почему-то не помог, попросите помощи в #help (лучше на английском) или напишите в [https://osu.ppy.sh/forum/t/9668 специальную тему] на форуме.",
    "hitsound-library": "Нестандартные хитсаунды для своей карты можно раздобыть [https://osu.ppy.sh/forum/p/164927 здесь].",
    "hl": "Не жалуйтесь, что вас хайлайтят, если в вашем нике или списке хайлайтов есть распространённое слово или фраза.\nВ случае чего, вы можете отключить в настройках уведомления о хайлайтах (или переименоваться)",
    "how-to-get-modded": "О том, как найти моды на карту, можно узнать [https://osu.ppy.sh/wiki/Guides/Getting_Your_Map_Modded?locale=ru здесь.]",
    "how-to-bn": "Если вы хотите стать номинатором, прочитайте [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator этот тред].",
    "how-to-gmt": "Вы можете стать модератором, если вы активны в официальном коммьюнити осу и не совершали серьёзных проступков. Подробности на вики: [[GMT]].\nКроме этого, вы можете облегчить работу другим модераторам, используя команду !report.",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#how-to-play? Нажмите сюда, чтобы узнать, как играть!].",
    "how-to-rank": "О том, как ранкнуть свою карту, можно прочитать в [https://osu.ppy.sh/wiki/Guides/How_To_Get_Your_Map_Ranked?locale=ru этой статье].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Гипердэш включается в моменты, когда вы ловите светящийся красным фрукт, и даёт огромное преимущество в скорости.\nОн выключится после того, как вы дойдёте до следующего фрукта или упустите его.",
    "ignore": "Чтобы добавить кого-нибудь в игнор-лист, напишите /ignore ник. Для отмены — /unignore ник.\nЭто — временный список, сбрасывающийся при выходе из игры, а постоянный можно найти в настройках osu!.",
    "import": "Чтобы узнать, как импортировать карты в osu!, просмотрите [http://i.imgur.com/kpX2N3m.jpg короткую справку]. ",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "После включения настройки Inherit previous timing settings в окошке редактора, которое появляется после нажатия F6, эти секции больше не будут влиять на сам тайминг. ",
    "irc": "IRC: irc.ppy.sh:6667\nПароль: https://osu.ppy.sh/p/irc\nПодробности: https://osu.ppy.sh/wiki/ru/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Вы можете поменять назначение клавиш в разделе настроек «Клавиатура».\nКлавиши и раскладка в osu!mania меняются нажатием на кнопку «Раскладка osu!mania».",
    "kiai": "Киаи (киай) — визуальный эффект, который вы можете добавить в свою карту в настройках тайминга. Секция с киаи включает различные эффекты, делающие карту более эпичной.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "[https://osu.ppy.sh/wiki/Kudosu Кудосу] — то, что зарабатывается за [https://osu.ppy.sh/wiki/Modding моддинг] карт других мапперов.",
    "lag": "Если у вас что-то лагает, сначала выясните, что именно и при каких условиях. Попробуйте написать об этом в [https://osu.ppy.sh/forum/5 саппорт].\nТакже перед тем, как писать о лагах, попробуйте закрыть ненужные программы и убедитесь, что ничего больше не нагружает процессор и память.",
    "language": "Будьте вежливы и старайтесь воздерживаться от оскорблений.",
    "language-specific": "Пожалуйста, используйте именно тот язык, на канале которого вы находитесь. \nИспользование романизации японского языка или транслитерации русского не отменяет это правило.",
    "lazer": "",
    "level": "Ваш уровень зависит от того, сколько всего вы получили очков на ранкнутых картах, включая даже зафейленные прохождения. Уровень будет повышаться просто от игры в osu!",
    "lines": "Умещайте свои мысли в меньшее количество строк, чтобы не получить сайленс за захламление чата.",
    "link": "Для создания ссылки используйте этот шаблон: [ссылка текст] (адрес и текст разделяются пробелом). В начале ссылки должен быть протокол http:// или https://.\n[https://osu.ppy.sh Вот так!] Учтите, что использование ссылок не по назначению наказуемо.",
    "lobby": "Используйте #lobby только для рекламы комнат. В #lobby можно использовать любой язык. \nДля всех остальных разговоров используйте #multiplayer.",
    "localisation": "Не устраивает перевод игры? Нашли опечатку? Вы можете помочь [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 здесь].",
    "long-link": "Пожалуйста, не постите в чат длинные ссылки. Для этого существует конструкция [ссылка текст].",
    "long-text": "Не копируйте объёмные куски текста в чат: это чревато сайленсом за спам.",
    "loved": "Loved — это новая категория для карт, в которую отправляются любимые сообществом карты, не подходящие под критерии ранкинга. У них есть таблица рекордов, которую может сбросить автор карты.\nПодробнее об этом можно узнать на вики: [[ru/Project Loved]]",
    "mac": "[https://osx.ppy.sh Запуск osu! на Mac]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Замапать песню самому — самый лучший вариант, потому что у других, как правило, нет ни времени, ни желания.",
    "mapping": "Всевозможного рода информацию о маппинге можно найти [https://osu.ppy.sh/forum/t/440360 здесь.]",
    "mat": "MAT — Mapping Assistance Team, группа пользователей, помогавших BAT с ранкингом карт. \nRIP MAT 2013-04-23",
    "modhelp": "Если у вас есть вопрос о маппинге, а в #russian почему-то никто не отвечает, спросите на английском в #mapping.",
    "modqueue": "Список очередей для получения модов: [https://osu.ppy.sh/forum/60 Modding Queues].",
    "modreqs": "Все просьбы о моддинге карт должны направляться на английском в #modreqs или на форум в раздел Work In Progress → Modding Queues. Но попросить о плейтесте или критике можно и тут.",
    "multi-invite": "Чтобы пригласить кого-то в свою комнату, найдите имя пользователя в списке (F9) или в чате, кликнув по нему и выбрав пункт «Пригласить в мульти».\nПомимо этого, можно написать /invite ник_игрока.",
    "multi-link": "На форуме есть [https://osu.ppy.sh/community/forums/topics/338482 пошаговое руководство] по созданию ссылки на свою комнату.",
    "multiaccounting": "Создание мультиаккаунтов является нарушением правил и наказуемо.",
    "multiplayer": "Рекламируйте комнаты и зовите в них людей только в #lobby (там можно общаться на любом языке).",
    "mwc": "MWC — турнир между игроками в osu!mania. Подробности можно узнать на вики: https://osu.ppy.sh/wiki/Tournaments/MWC/2018/4K/.",
    "nat": "[https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] контролирует номинаторов (BN) и следит за процессом ранкинга карт.\nОни оценивают работу текущих и будущих номинаторов, а также выполняют роль посредников при различных спорах касательно маппинга или моддинга, включая вето на карты.",
    "news": "",
    "nightcore": "Нравится найткор? Теперь его можно применить к любой песне; достаточно зайти в меню модов и два раза кликнуть на DoubleTime.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Отправив /np в чат, вы покажете, какую песню слушаете или играете.",
    "nsfw": "osu! — это игра для всех возрастов, поэтому разговаривать на темы недетского характера запрещено. За это вы можете получить сайленс без предупреждения.",
    "osu": "osu! — это аббревиатура для [http://osu.ru/ Оренбургского Государственного Университета!] Хороший вуз, поступайте, не пожалеете!",
    "osu!tablet": "Узнать о планшете с логотипом osu! можно [https://osu.ppy.sh/forum/t/169139 здесь], а заказать — [https://osu.ppy.sh/p/tablet здесь].",
    "osu!talk": "osu!talk — серия подкастов, которую выпускали ztrot и deadbeat\nСодержание: интервью с другими игроками и администрацией, обсуждение игровых событий (например, [[OWC]])\nПодробности: https://osu.ppy.sh/forum/t/225111",
    "osucore": "osu!core — привет из далёкого-далёкого 2011, когда на первое апреля все карты по умолчанию игрались с ДТ и звучали как найткор.\nПозднее этот эффект вернулся в виде полноценного мода с таким же эффектом, к которому были добавлены техно-хитсаунды.",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] — относительно старый порт osu! на андроид.\nОн был заброшен официальными разработчиками и убран из Play Store в 2016 из-за плохих отзывов и отсутствия активности.",
    "osumania": "Для обсуждения режима osu!mania на английском вы можете использовать #osumania.",
    "osustream": "[http://www.osustream.com osu!stream] — osu! для iOS. Это самостоятельная игра, но сходство видно сразу.",
    "osz": ".osz — формат хранения карт. osu! умеет распаковывать эти файлы, но если что-то вдруг пойдёт не так, то можно попытаться сделать это вручную любым архиватором.",
    "osz2": "Новый формат карт, файлы в котором будут храниться зашифрованными и обновляться независимо друг от друга.\nИх также не понадобится распаковывать — карты в формате .osz2 всегда будут храниться в папке с песнями в виде одного файла.",
    "owc": "OWC — турнир между игроками osu! со всего мира, проводящийся раз в год.\nСсылки: [http://www.twitch.tv/osulive трансляция матчей], подробная [https://osu.ppy.sh/forum/t/160181 информация о турнире], русская статья [https://osu.ppy.sh/wiki/OWC на вики], [https://osu.ppy.sh/forum/t/369906 тема на форуме].",
    "peppy": "pеppy — создатель и ведущий разработчик osu!, сделавший и до сих пор делающий многие вещи в одиночку.",
    "perfect": "Не смогли получить SS? Включите мод Perfect, который автоматически перезапускает карту, если вы собьёте SS. Чтобы включить его, достаточно зайти в меню модов и два раза нажать на мод SuddenDeath.",
    "ping": "Pong!",
    "pippi": "Пиппи — маскот osu!, а Пиппи-дон — её версия для тайко.",
    "piracy": "Пожалуйста, не обсуждайте цифровое пиратство и нелегальный контент. Это запрещено, и вы можете получить сайленс.",
    "play-shortcuts": "Список горячих клавиш: [[Shortcut_Key_Reference]].",
    "pm": "Чтобы написать кому-то сообщение, откройте список пользователей онлайн (F9) и нажмите на «Начать разговор».\nТакже вы можете использовать команды /msg ник_игрока, /chat ник_игрока или query ник_игрока.\nЧтобы быстро ответить на последнее личное сообщение, вы можете использовать /r сообщение. Все команды надо использовать без кавычек.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance points (pp) — то, в чём измеряется ранк игрока в osu!. Подробнеe на английском: [[PP]].",
    "pp-rework-lazer": "",
    "preview": "Превью — это момент, с которого начинает играть песня при её выборе в списке. Чтобы установить его в своей карте, в редакторе в верхнем меню Timing выберите пункт Set Current Position as Preview Point.",
    "qat": "Quality Assurance Team занимается проверкой карт, номинированных на ранкинг, определяя их качество и играбельность.\nВ апреле 2019-го, после значительных изменений в системе ранкинга, QAT были переименованы в Nomination Assessment Team для отражения их деятельности.",
    "qualified": "Номинаторы добавляют заслуживающие ранкинга карты в категорию Qualified.\nЕсли в такой карте не нашли проблем в течение недели, она будет ранкнута, в противном случае — вернётся в секцию Pending. В обоих случаях все недельные рекорды удаляются. ",
    "ranked": "Ранкнутая карта — это карта, которая была одобрена [http://osu.ppy.sh/wiki/BN номинаторами]. Вы получаете очки и пп, если играете ранкнутые карты. Отличить их можно по иконке сердца в левом верхнем углу и наличию таблицы рекордов.",
    "ranking-criteria": "Актуальные критерии ранкинга могут быть найдены здесь: [[RC]].",
    "redname": "Пользователи с красными никами — это либо [https://osu.ppy.sh/wiki/People/Global_Moderation_Team модераторы] (GMT), либо [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team NAT].",
    "report": "Если вы заметили нарушение правил игры, чата или форума, используйте следующую команду: !report ник_игрока причина.\nРепорты не видны другим пользователям и должны быть отправлены в чате, не отправляйте их в личных сообщениях.\nТакже вы можете нажать на чей-нибудь ник и выбрать из списка Отправить жалобу.",
    "report-abuse": "Пожалуйста, не надо репортить одно и то же много раз, это не поможет, равно как и пустые или беспричинные репорты.\nБолее того, вам могут выдать сайленс за злоупотребление системой репортов.",
    "request": "Если нечего моддить, выберите карту [https://osu.ppy.sh/p/beatmaplist&r=8 отсюда] или напишите !request, чтобы получить случайную карту для моддинга.",
    "respect": "Пожалуйста, уважайте других игроков.",
    "roll-abuse": "Пожалуйста, не используйте команду !roll слишком часто, иначе вы можете получить сайленс.",
    "romaji": "Пожалуйста, не используйте слишком часто ромадзи (японский, который написан латиницей). Вы можете получить сайленс.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Если в лобби нет нужной комнаты, почему бы не создать новую — с такими картами, какими только захочется?",
    "rp": "Вы можете заниматься ролеплеем, если это не мешает и не надоедает остальным.",
    "rules": "[https://osu.ppy.sh/wiki/ru/Rules Официальные правила] чата и игры. Их краткая выжимка: https://osu.ppy.sh/forum/t/51989",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "К сожалению, иногда сервера osu! досят, поэтому в это время Bancho может работать нестабильно или вообще быть недоступен.\nЕсли вам кажется, что что-то не так, проверьте [https://twitter.com/osustatus твиттер @osustatus] или [https://status.ppy.sh здоровье серверов].",
    "sb": "Сторибординг делает вашу карту эффектнее. О том, как научиться делать сториборды, читайте здесь: [[Storyboarding]].\nСтарые гайды: [https://osu.ppy.sh/forum/t/1869 основной], [https://osu.ppy.sh/forum/t/8145 о работе в редакторе].",
    "scorev2": "scorev2 — это новый алгоритм подсчёта очков, который ограничивает максимальное количество очков во всех режимах одним миллионом (без учёта спиннеров и модов).\nscorev2 также меняет механику слайдеров: они начинают требовать такой же точности нажатий, как и ноты.",
    "scoring": "О подсчёте очков можно прочитать здесь: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Сайленс, или сало, означает, что человек не может писать в чате и на форуме.\nДлина сайленса начинается с пяти минут и обычно увеличивается в два раза за каждое последующее нарушение, но возможны и резкие скачки в зависимости от нарушений.\nЧтобы избежать получения сайленса, постарайтесь не нарушать [https://osu.ppy.sh/wiki/ru/Rules правила].",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 FAQ по скинам]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Чем дольше вы не спите из-за osu!, тем сильней вы будете проклинать её, когда проснётесь.]",
    "songs-not-appearing": "Если новые карты не появляются в списке песен, нажмите F5 или перезапустите osu!.",
    "spaces": "Пожалуйста, не пишите пробелы после каждой буквы, иначе вы можете получить сайленс.",
    "spam": "Пожалуйста, не надо спамить в чат, иначе вы можете получить сайленс.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Чтобы смотреть за другим игроком, напишите /watch ник или кликните по имени игрока и нажмите «Наблюдать за игрой».\nДля успешного просмотра у вас должна быть в точности такая же карта. Убедитесь, что человек действительно играет.",
    "spoiler": "Не надо сообщать спойлеры к аниме, сериалам, фильмам и прочим видам медиа — за это можно получить сайленс. Не лишайте людей удовольствия.\nЭто относится к подробностям любого рода, о которых не сообщили связанные с ними лица.",
    "status": "Для получения информации о состоянии серверов osu! подпишитесь на [http://twitter.com/osustatus @osustatus] или загляните [https://status.ppy.sh сюда].",
    "store": "Всякие товары с логотипом osu! можно купить [http://store.ppy.sh/ в магазине].",
    "submit": "Справка по загрузке карт на сайт: [[Submission]].",
    "suck": "Не грустите: для хорошей игры в osu! нужно потратить очень много времени. Не сдавайтесь!",
    "supporter": "Если приобрести [https://osu.ppy.sh/p/support osu!supporter], то osu! получит материальную поддержку, а вы — ряд полезных возможностей.",
    "supporter-please": "Пожалуйста, не просите других людей подарить вам саппорт, лучше [https://osu.ppy.sh/p/support купите его сами].",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Если курсор «летает» при движении, поставьте в настройках osu! чувствительность мыши, равную 1. «Чувствительность» планшета настраивается с помощью его активной области.\nЕсли курсор не двигается, отключите в настройках прямой ввод.\nЕсли проблема не решилась, поищите решение [https://osu.ppy.sh/forum/t/87301 на форуме].",
    "tag": "Tag Coop — режим мультиплеера, в котором все игроки проходят одну карту, по очереди нажимая только на ноты своего цвета.\nЗдесь нет ни победителей, ни проигравших, так как все играют в одной команде.\nСпиннеры вращают все игроки. Если кто-то не успевает заполнить шкалу спиннера, команда теряет комбо.\nБонус каждого игрока, полученный на спиннерах, суммируется с общим результатом команды.",
    "taiko": "Тайко — японские барабаны, появившиеся в играх Bandai-Namco. В этом режиме игрокам следует концентрироваться на ритме карты.\n[https://osu.ppy.sh/forum/t/124083 Здесь] можно почитать, как играть в тайко.",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Как мапать тайко]",
    "taiko-maps": "Оригинальные карты Taiko no Tatsujin можно найти [https://osu.ppy.sh/forum/t/5397 здесь].",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Поменяйте тему разговора на что-нибудь другое.",
    "training": "[https://osu.ppy.sh/forum/t/4280 James Training]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "Немного обучающих видео можно найти [https://osu.ppy.sh/forum/t/109137 здесь], а более полный список руководств находится [https://osu.ppy.sh/wiki/Guides на вики].",
    "twc": "TWC — мировой турнир между игроками в тайко.\nСсылки: [http://www.twitch.tv/taikoworldcup трансляция матчей], [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ информация о турнире].",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Пожалуйста, не злоупотребляйте спецсимволами, это может быть расценено как спам.",
    "upload-cap": "Существует ограничение на количество залитых на сервер карт.\nОбычные пользователи могут залить от 3 до 6 карт, саппорты — от 5 до 10, в зависимости от количества ранкнутых ранее карт.",
    "utf8": "Pozhalujsta, postav'te kodirovku v svoyom IRC-kliente na UTF-8, chtoby i vas mogli ponimat', i vy mogli ponimat'.",
    "videogames": "Обсуждение других игр в чате не запрещено, но, пожалуйста, не зовите людей играть в них.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Чтобы быстрее освоиться в osu!, прочитай [https://osu.ppy.sh/wiki/Welcome?locale=ru эту статью].",
    "when": "Когда будет готово.",
    "wiki": "Примите участие в заполнении [https://osu.ppy.sh/wiki вики]!",
    "wiki-link": "Чтобы вставить ссылку на страницу в вики, напишите её заголовок в двойных квадратных скобках. Образец: [[GMT]]",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 214 active FAQs (out of a possible 217) in the Russian (Русский) language.",
    "completion": "The Russian (Русский) FAQ as of last update is 98.62% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Таймер был изменён на 60 секунд!"
}
