
strings = {
    "academy": "[https://www.youtube.com/user/osuacademy Klikni tukaj] za ogled osu! akademije - Videi za pomoč o igri osu!",
    "achievements": "Dosežke dobiš tako da narediš nekaj posebnega med pesmijo, na primer dobiš ogromen combo ali pa igraš vse beatmape v paketu. Na tvojem profilu so prikazani vsi dosežki ki si jih dobil, pa tudi tisti ki jih še lahko dobiš. Nekaj imen je namigov o tem kaj je treba storiti da dosežek dobiš!",
    "add-skin": "Da dodaš nov skin, ga prenesi in povleči datoteko v osu! okno ali jo dvoklikni.",
    "advertising": "Oglaševanje vsebin, ki niso povezane z osu!, niso dovoljene in si zaradi tega lahko utišan.",
    "answer": "Če ti nihče ne odgovori, je mogoče, da nihče ne ve odgovora na vprašanje! Poiskusi poiskati odgovor na forumu, če je povezan z igro osu!",
    "appeal": "Če te nekdo utiša, in misliš, da si bil utišan po krivem, sporoči to administratorjem z e-mail sporočilom na accounts@ppy.sh in razloži situacijo. Samo zapomni si, da so administratorji tudi ljudje! Če si prijazen do njih, je bolj verjetno, da bodo odstranili utišanje, če je to le mogoče. ",
    "approved": "Odobrene beatmape zaradi določenih razlogov ne smejo biti uvrščene - ampak so dovolj dobre, da igralci lahko igrajo na njih z doseganjem rezultatov in ostalimi stvermi! Vedel boš, da je mapa odobrena, če ima ikono Ognja namesto Srca.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "Najboljši način, da izveš odgovor, je da kar uprašaš - ni veliko smisla v uprašati za uprašanje o uprašanju!",
    "attention": "Lahko prosim nehaš?! Nihče te ne posluša...",
    "avatar-change": "Svoj avatar lahko spremeniš [https://osu.ppy.sh/home/account/edit#avatar tukaj].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Pozdravljen! Jaz sem BanchoBot! Lepo, da sva se spoznala! Ampak jas sem robot, tako da se res ne morem pogovarjati s tabo :(",
    "beatmapping": "Tukaj je nekaj koristnih nasvetov o [https://osu.ppy.sh/wiki/Beatmapping beatmapanju!]",
    "beginner": "Klikni [https://osu.ppy.sh/forum/t/5456 tukaj] če iščeš začetniške mape.",
    "bn": " [[Beatmap Nomination Group]]  je skupina ljudi ki so zadolženi za uvrščanje beatmap in so odgovorni za upravljanje moderationa neuvrščenih beatmap v uvrstitveni cikel. Lahko govoriš z njimi v primeru da imaš kakšno vprašanje ali potrebuješ kakšen nasvet o delajnu ali urejanju beatmap.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Nima smisla povedati drugim, da ti je doljčas. Vzemi si odmor ali pa poiskusi igrati kaj drugega!]",
    "bug": "Če misliš, da si odkril napako, jo prijavi [https://osu.ppy.sh/forum/5 tukaj]. Samo prepričaj se, da jo ni že kdo drug pred tem odkril.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Prosim ne uporabljaj velikih začetnic na začetku vsake besede - to izgleda tako, kot da bi vse kar si napisal povozil vlak. ",
    "caps": "Prosim ne piši z velikimi črkami - to v pogovoru ni zaželjeno in zaradi tega te lahko tudi utišajo.",
    "change-modes": "Če hočeš spremeniti igralni način, pojdi v meni izbire pesmi in klikni na gumb Mode na spodnji levi strani ali pa pritisni Ctrl + 1-4. V mislih imej, da so nekatere mape specifične za določen način!",
    "change-name": "Če si hočeš spremeniti uporabniško ime, moraš najprej postati [https://osu.ppy.sh/p/support osu! podpornik].Potem si lahko uporabniško ime spremeniš  [https://store.ppy.sh/store/product/32 tukaj]!\nČe hočeš povrniti svoje staro uporabniško ime, majhne spremembe ali pomoč, prosim pošlji e-mail na accounts@ppy.sh z vsemi podatki..",
    "changelog": "Vse posodobitve igre, Bancho in spletne strani lahko najdeš na osu! development [https://osu.ppy.sh/p/changelog changelog!]\n",
    "chars": "Prosim izogibaj se uporabi unikode/ne-standardnih znakov v generalnem pogovornem oknu.",
    "charts": "osu! lestvica je tematski paket map, ki so objavljene vsak mesec. lahko jih najdeš [https://osu.ppy.sh/p/chart tukaj!]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Bledo Rumeno: Normalen uporabnik | Rumena: A\n[https://osu.ppy.sh/p/support Podpornik] | Rdeča: A\n[https://osu.ppy.sh/wiki/QAT QAT] ali\n[https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nBela: Ti sam, ali /me sporočilo | Temo Modra: A PM | Zelena: Vrstica v pogovoru, ki vsebije tvoje uporabniško ime (poudarek) | Roza: BanchoBot",
    "colour": "Bledo Rumeno: Normalen uporabnik | Rumena: A\n[https://osu.ppy.sh/p/support Podpornik] | Rdeča: A\n[https://osu.ppy.sh/wiki/QAT QAT] ali\n[https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nBela: Ti sam, ali /me sporočilo | Temo Modra: A PM | Zelena: Vrstica v pogovoru, ki vsebije tvoje uporabniško ime (poudarek) | Roza: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Kljub temu, da so ukazi pogovornega okna zelo lahki za uporabo, jih prosim ne uporabljaj preveč. To je lahko vidno kot spam in te lahko utišajo.",
    "comment": "Če želiš pustiti komentar na ponovitvi beatmape, klikni Discussion gumb, nekaj napiši in pritisni enter!\nČe trenutno ni komentarjev na zaslonu, izberi Show Comments možnost v Discussion vrstici.",
    "comment-color": "Noramlen uporabnik lahko komentira samo v beli barvi. [https://osu.ppy.sh/p/support podpornik] si lahko barvo komentarja spremeni.",
    "conferencemode": "Postajaš preplavljen z Join/Quit sporočili v IRC? [http://wiki.xkcd.com/irc/Hide_join_part_messages To] ti lahko pomaga!",
    "country-ranking": "Poglej različne [https://osu.ppy.sh/p/countryranking Državna Uvrstitev] rezultate tukaj.",
    "critic": "Prosim te naj bodo kritike konstruktivne. Predlagaj alternative ali načine za popravilo napak, ki te motijo.",
    "ctb": "Potrebuješ nekaj pomoči z Catch the Beat? [https://osu.ppy.sh/wiki/Catch_the_Beat Tukaj je] wiki stran!",
    "cutting-edge": "Vrhunski je eksperimentalna različica osu!, uporablja se za testiranje novih možnosti preden so izdane v stabilni raličici. Preklopi na ta način v možnostih! Preberi [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues tole] če imaš kakršenkoli problem pri posodobitvi osu!",
    "cwc": "Svetovni osu! Catch the Beat turnir. Poglej to [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 wiki stran] za več informacij.",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\r\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\r\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "",
    "disable-this": "",
    "distance-snap": "",
    "dont-ask-peppy": "Prosim ne sprašuj vedno peppyja - zelo je zaposlen.\nVprašaj kogarkoli drugega v tem kanalu!",
    "douche": "",
    "download": "Veče beatmap lahko preneseš [https://osu.ppy.sh/p/beatmaplist tukaj] ali paket beatmap [https://osu.ppy.sh/beatmaps/packs tukaj]. V primeru, da jih ne znaš vnesti, lahko prebereš [http://i.imgur.com/kpX2N3m.jpg tole] in izveš več!\n",
    "drugs": "Prosim ne razpravljaj o katerih koli drogah kjerkoli v osu! pogovornem oknu.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Preberi [[Beatmapping#Keyboard_Shortcuts]] da najdeš seznam bljižnic urejevalnika.",
    "english": "#english je namenjen za splošno razpravo, ki nima namenjenega kanala.\nDa, to vsebuje anime/manga. In vlake.",
    "evade": "",
    "fallback": "",
    "faq": "Tenutno uporabljaš osu!Bancho FAQ Sistem.\n",
    "feature": "Če imaš idejo za to igro, jo ovjavi v [https://osu.ppy.sh/forum/4 Feature Requests] podforumu.",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Izogibanje filtrov pogovora lahko (in verjetno bo) prišlo do utišanja. Ne delaj tega.",
    "foul-play": "",
    "percolate": "Izogibanje filtrov pogovora lahko (in verjetno bo) prišlo do utišanja. Ne delaj tega.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Ta članek] ti bo pomagal pri razumevanju toka mappanja.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "",
    "friends-list": "",
    "fullscreen": "",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Veliko terminologije lahko najdeš v osu! [[glossary]].",
    "gmt": "",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Beri, preglej, veseli se.]",
    "grammar": "",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Ali ne veš kako igrati? Želiš raziskati svet mappanja in moddanja? [https://osu.ppy.sh/wiki/Guides Tukaj] boš našel vse odgovore.",
    "hacked": "Če misliš,da so ti vdrli v račun, prosim pošlji email na accounts@ppy.sh.\nČe tega ne boš storil, lahko pride do ukinjenja tvojega računa.\n",
    "hard": "",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "",
    "hitsound-library": "Pojdi [https://osu.ppy.sh/forum/p/164927 tukaj] če želiš dobiti posebno narejene hitzvoke za tvojo mapo.",
    "hl": "",
    "how-to-get-modded": "Če hočeš izvedeti, kako ti lahko pregledajo tvojo mapo, klikni tukaj:\n[[Getting_Your_Map_Modded]]",
    "how-to-bn": "Če hočeš postati BN, preberi [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator to] - večino časa bodo drugi BN-i izbrali kdo napreduje v BN glede na stvari kot so moddanje in dejavnost.",
    "how-to-gmt": "",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F Klikni tole povezavo, če se hočeš naučiti igrati]",
    "how-to-rank": "Če želiš izvedeti, preberi [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "",
    "ignore": "",
    "import": "Preberi [http://i.imgur.com/kpX2N3m.jpg to] da izveš kako vneseš  beatmape v osu!",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "",
    "irc": "",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "",
    "kiai": "",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Zasluži [https://osu.ppy.sh/wiki/Kudosu kudosu] z moddanjem map od drugih uporabnikov.",
    "lag": "",
    "language": "Prosim bodi vljuden v pogovornih sobah.Zaradi neprimerenega jezik te lahko utišajo. ",
    "language-specific": "",
    "lazer": "",
    "level": "",
    "lines": "Prosim poiskušaj pisati stavke v eni vrstici, da se izogneš utišanju.",
    "link": "",
    "lobby": "",
    "localisation": "osu! localisation projekt se nahaja [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 tukaj].",
    "long-link": "Prosim ne prilepi daljših povezav v pogovoru! Uporabi [link text], formulo če že res moraš.",
    "long-text": "Prosim ne prilepi daljših povezav v pogovoru! Uporabi [link text], formulo če že res moraš.",
    "loved": "",
    "mac": "[https://osx.ppy.sh Zaženi osu! na tvojem Mac-u]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Ustvarjalci map so zelo zaposleni ljudje in mappanje je zelo tezko delo. Zakaj ne poiskusiš mappati tudi ti?",
    "mapping": "Klikni [https://osu.ppy.sh/forum/p/988111 tukaj] nasvete o mappanju.",
    "mat": "",
    "modhelp": "Za vsa vprašanja o moddanju beatmap pojdi v #mapping!",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modding Vrste]",
    "modreqs": "",
    "multi-invite": "",
    "multi-link": "",
    "multiaccounting": "",
    "multiplayer": "Prosim ne oglašuj multiplayer iger na kateremkoli kanalu razen #lobby ",
    "mwc": "Svetovni osu! Mania turnir. poglej to [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 wiki stran] za več informacij.",
    "nat": "",
    "news": "",
    "nightcore": "",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Napiši /np, če želiš pokazati drugim kaj tenutno poslušaš ali igraš v osu!",
    "nsfw": "",
    "osu": "#osu je za pogovor o osu!. Prosim ne razpravljajte tam in ne v tem kanalu.",
    "osu!tablet": "",
    "osu!talk": "",
    "osucore": "",
    "osu!droid": "",
    "osumania": "Prosim uporabljaj #osumania za osu!mania povezane razprave.",
    "osustream": "[http://www.osustream.com osu!stream] je osu! za iOS naprave, ki ga je naredil in vzdržuje peppy!",
    "osz": "",
    "osz2": "",
    "owc": "Svetovni osu! turnirt. Poglej to [https://osu.ppy.sh/wiki/OWC wiki stran] za več informacij.",
    "peppy": "peppy je vodilni razvijalec igre osu! in sam upravlja z večino projekti.",
    "perfect": "Nisi dobil tisti SS? Ta mod samodejno zate ponovi poiskus na mapi, če narediš kakršnokoli napako.\nNajdeš ga z dsnim klikom na SuddenDeath v izbiri modov.",
    "ping": "Pong!",
    "pippi": "osu! maskota\nPippi-don je taiko (boben) verzija od Pipi",
    "piracy": "Prosim ne razpravljate o deljenju vsebine z avtorskimi pravicami v glavnem pogovornem oknu.",
    "play-shortcuts": "Cel seznam tipk bljižnic: [[Shortcut_Key_Reference]]",
    "pm": "",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Točke uspešnosti (pp) so glavne enote za uvrščanje v osu! Klikni [https://osu.ppy.sh/wiki/Performance_Points tukaj] za več informacij.",
    "pp-rework-lazer": "",
    "preview": "",
    "qat": "",
    "qualified": "",
    "ranked": "",
    "ranking-criteria": "Za informacije o kriteriju za uvrstitev mape prosim obišči wiki: [[RC]]",
    "redname": "Uporabniki z rdečimi imeni so ali [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] ali [https://osu.ppy.sh/wiki/QAT QAT]",
    "report": "",
    "report-abuse": "",
    "request": "",
    "respect": "",
    "roll-abuse": "Prosim ne pretiravaj z !roll ulazom. Lahko te utišajo.",
    "romaji": "",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "",
    "rp": "",
    "rules": "[https://osu.ppy.sh/wiki/Rules Uradna Pravila]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "",
    "sb": "",
    "scorev2": "",
    "scoring": "kako osu! izračuna rezultat: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Skinning FAQ]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Ne dovoli, da te osu! drži pokonci do 4 zjutraj. Spanec je zelo pomemben!]",
    "songs-not-appearing": "Če se pesmi ne pojavijo v meniju izbire pesmi, poiskusi pritisniti F5",
    "spaces": "",
    "spam": "Prosim ne spamaj. To je zelo nadležno in lahko privede do utišanja.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "",
    "spoiler": "",
    "status": "Za osu! posodobitve statusa sistema prosim poglej [http://twitter.com/osustatus @osustatus]",
    "store": "[http://store.ppy.sh/ Dobrodošel v osu! trgovino], kraj, kjer lahko kupiš super osu! stvari!",
    "submit": "[https://osu.ppy.sh/wiki/Submission Beatmap Predložitve FAQ]",
    "suck": "osu! ima veliko učno krivuljo - čez čas boš postal vedno boljši zato kar poiskušaj naprej!",
    "supporter": "",
    "supporter-please": "",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "",
    "tag": "",
    "taiko": "",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Taiko mapping vodič]",
    "taiko-maps": "Pristne Taiko in Tatsujin mape lahko najdeš [https://osu.ppy.sh/forum/t/5397 tukaj.]",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Opusti to temo in govori o nečem drugem.",
    "training": "[https://osu.ppy.sh/forum/t/4280 Jamesov trening]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "",
    "twc": "Vsesvetovni osu! Taiko turnir. Poglej [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ wiki page] za več informacij",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Prosim izogibaj se uporabi unikode/ne-standardnih znakov v generalnem pogovornem oknu.",
    "upload-cap": "",
    "utf8": "",
    "videogames": "",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Dobrodošli v osu! Če imaš kakšne težave ali vprašanja, vprašaj prijazne ljudi v #help! Zabavaj se!",
    "when": "Ko je pripravljeno.",
    "wiki": "[https://osu.ppy.sh/wiki/ The osu! Wiki] - Naredi jo super!",
    "wiki-link": "",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 142 active FAQs (out of a possible 217) in the Slovenian (Slovenščina) language.",
    "completion": "The Slovenian (Slovenščina) FAQ as of last update is 65.44% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
