
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy Klicka här] för att se osu! academy - Video tutorial för allt relaterat till osu!",
    "achievements": "Du kan få prestationer genom att genomföra något speciellt i en låt, så som att få en gigantisk kombo, eller att spela alla låtarna i ett tema-paket. Din profil visar vilka prestationer du har fått, och vad du behöver skaffa. Några av namnen är ledtrådar för vad du behöver göra får att få prestationen!",
    "add-skin": "För att lägga till nya skins, ladda ner det och dra in filen till osu! fönstret eller dubbelklicka på den.",
    "advertising": "Annonsering av saker och ting orelaterat till osu! är inte tillåtet och kan få dig silencad.",
    "answer": "Om ingen svarar dig, så är det möjligt att ingen vet svaret! Testa att söka på forumet om det är osu!-relaterat.",
    "appeal": "Om du i slutändan blir silencad och tycker att det var orättvist, kontakta administratörerna genom att skicka ett e-postmeddelande till accounts@ppy.sh och förklara din situation. Kom bara ihåg dock administratörer är människor också! Om du är vänlig mot dem, så de är mer benägna att göra sitt bästa för att ta bort silencen, om det är möjligt dvs.",
    "approved": "Approved beatmaps kan inte bli rankade av en eller en annan anledning - men den är fortfarande bra nog för att folk kan spela på den, med en rankningslista och allt! Ifall ikonen bredvid beatmappen är en flamma istället för ett hjärta, då är det en approved beatmap.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "",
    "ask": "Det bästa sättet att få ett svar är att bara fråga din fråga - det finns ingen vits med att fråga en fråga om att fråga en fråga. - Får jag fråga en sak? är redan en fråga.",
    "attention": "Kan du snälla sluta? Ingen lyssnar riktigt på vad du säger...",
    "avatar-change": "Du kan byta din profilbild [https://osu.ppy.sh/home/account/edit#avatar här].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Hej! Jag är BanchoBot! Trevligt att råkas! \nJag är en bot dock, så jag kan inte riktigt hålla en konversation med dig :(",
    "beatmapping": "Här är några hjälpsamma tips på [https://osu.ppy.sh/wiki/Beatmapping beatmapping!]",
    "beginner": "Klicka [https://osu.ppy.sh/forum/t/5456 här] om du letar efter nybörjar maps.",
    "bn": "Gruppen [[Beatmap Nomination Group]] består av personer som bestämmer och övervakar rankade beatmaps. De är ansvariga för att hantera vilka beatmaps som ska vara med i ranking-processen. Kontakt dem gärna om du har några frågor, eller behöver råd, angående mapping eller modding. ",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Det finns ingen anledning att berätta för andra att du är uttråkad. Ta en paus, eller prova att spela något annat!]",
    "bug": "Om du tror att du har hittat en bugg, rapportera det [https://osu.ppy.sh/forum/5 här]. Var bara säker på att ingen har rapporterat ditt problem innan!",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Använd inte en stor bokstav i början av varje ord - det gör så att allt du skriver ser ut som en tågkrasch.",
    "caps": "Skriv inte allt i caps - det är oönskat i chatten, och du kan bli silencad för det.",
    "change-modes": "För att ändra mellan de olika spellägena, gå till song select och klicka antingen på Mode längst ner eller använd Ctrl + 1-4. Kom ihåg att vissa maps bara fungerar i specifika spellägen!",
    "change-name": "För att kunna ändra ditt användarnamn, så måste du först bli en [https://osu.ppy.sh/p/support osu! supporter]. Sen så kan du ändra ditt användarnamn [https://store.ppy.sh/store/product/32 här]!\nFör att be om att få ditt gamla användarnamn tillbaka, små ändringar, eller hjälp, skicka ett e-mail till accounts@ppy.sh med detaljer.",
    "changelog": "Alla uppdateringar till spelet, Bancho och hemsidan kan du hitta i osu!s [https://osu.ppy.sh/p/changelog ändringslog!]",
    "chars": "Undvik att använda unicode/icke-standard tecken i allmän chatt.",
    "charts": "osu! charts är temapaket som släpps varje månad. Du kan hitta dem [https://osu.ppy.sh/p/chart här!]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Ljusgul: En normal användare | Gul: En [https://osu.ppy.sh/p/support Supporter] | Röd: En [https://osu.ppy.sh/wiki/QAT QAT] eller [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nVit: Du, eller ett /me meddelande | Mörk Blå: Ett PM | Grön: En linje som innehåller ditt användarnamn (en highlight) | Rosa: BanchoBot",
    "colour": "Ljusgul: En normal användare | Gul: En [https://osu.ppy.sh/p/support Supporter] | Röd: En [https://osu.ppy.sh/wiki/QAT QAT] eller [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nVit: Du, eller ett /me meddelande | Mörk Blå: Ett PM | Grön: En linje som innehåller ditt användarnamn (en highlight) | Rosa: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Även om chat kommandon är för enkel användning, var god och överanvänd dem inte. Detta anses som spam, och kan resultera med en silence.",
    "comment": "Om du känner för att göra en live commentary på en beatmap replay, klicka på Discussion knappen, skriv något, och klicka på enter!\nOm det inte är några kommentarer på skärmen redan, välj Show Comments boxen i diskussionspanelen.",
    "comment-color": "En vanlig användare kan bara kommentera i vitt. En [https://osu.ppy.sh/p/support supporter] kan ändra sin kommentarsfärg.",
    "conferencemode": "Blir du översvämmad av Join/Quit meddelanden på IRC? [http://wiki.xkcd.com/irc/Hide_join_part_messages Detta] kanske hjälper!",
    "country-ranking": "Titta på toplistan över [https://osu.ppy.sh/p/countryranking Nationell Rankning] här.",
    "critic": "Håll kritik konstruktivt. Föreslå alternativ eller sätt att lösa problemen som du är bekymrad över.",
    "ctb": "Behöver du lite hjälp med Catch the Beat? [https://osu.ppy.sh/wiki/Catch_the_Beat Här] är wikisidan!",
    "cutting-edge": "Cutting-edge är en uppdateringsström som ersätter den gamla osu!test builden.\nDu kan läsa [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues denna artikel] om du har några problem med att uppdatera din klient.",
    "cwc": "Det är en global osu! Catch the Beat turnering! Se [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 här] för mer info!",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Behandla andra som du själv vill bli behandlad. Om du är någon sorts verbal masochist, anta att alla andra inte är det.",
    "disable-this": "Toggles är sällan tillagda som funktioner. Du kan fortfarande begära att en blir tillagd genom [https://osu.ppy.sh/forum/4 Feature Request subforumet] dock.",
    "distance-snap": "Distance Snap är ett verktyg som håller korrekt relativ distans mellan noter baserat på deras position på tidslinjen. Detaljer: [[Distance_Snap]]",
    "dont-ask-peppy": "Fråga inte peppy hela tiden - han är väldigt upptagen. Men du kan gärna fråga vem som helst i den här kanalen dock!",
    "douche": "Som en säkerhetsåtgärd: kringående av ordning och artighet via kryphål i reglerna är straffbart genom diskretion och bedömning av det administrativa teamet. En officiel regel som framför att du inte ska vara en douche borde inte behövas för att du inte ska vara en douche, men utifall att: var inte en douche.",
    "download": "Du kan ladda ner fler beatmaps [https://osu.ppy.sh/p/beatmaplist här] eller paket med beatmaps [https://osu.ppy.sh/beatmaps/packs här].\nI fall du inte vet hur man importerar dom, kan du läsa [http://i.imgur.com/kpX2N3m.jpg detta] för att ta reda på!",
    "drugs": "Diskutera aldrig någonsin droger av något slag i osu! chatter.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Läs [[Beatmapping#Keyboard_Shortcuts]] för att hitta listan av editor genvägar.",
    "english": "#english är för generel diskussion om vad som helst som inte har en dedikerad kanal.\nJa, detta inkluderar anime/manga. Och tåg.",
    "evade": "Att kringgå en silence är skäl att ha ditt konto begränsat under en lång tidperiod, om inte helt och hållet bannad. Gör det inte.",
    "fallback": "Stable (Fallback) är en utdaterad build av osu! Till skillnad från Fallback , nyaste releasen avlägsnar stöd för DirectX för att förenkla vår struktur. Om du har bytt till denna builden, så är datorn low-end och kommer inte att stödja nyaste och framtida klientversioner .\nOm du vill spela i nuvarande build just nu, uppdatera dina grafikkort och gör so att dom stödjer OpenGL, den mest behövande komplement till dessa builds. [https://osu.ppy.sh/wiki/GL_Support_Issues Klicka här för att veta hur].",
    "faq": "Du använder just nu osu!Bancho FAQ systemet.\nosu! wiki: https://osu.ppy.sh/wiki",
    "feature": "Funktionsförslag lämnar du i [https://osu.ppy.sh/forum/4 Feature Request] subforumet.",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Undvikande av chattfilters är en av det snabbaste bekräftade sätten att sluta upp silencad eller bannad. Gör det inte.",
    "foul-play": "Vänligen rapportera fuskare genom att använda rapportknappen på deras profil som ligger [https://i.imgur.com/GG9xlLA.png här].\nSe till att du ger så mycket information som möjligt. Du kan också rapportera deras resultat på top 50 topplistorna i beatmap sida.",
    "percolate": "Undvikande av chattfilters är en av det snabbaste bekräftade sätten att sluta upp silencad eller bannad. Gör det inte.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Den här artikeln] kommer hjälpa dig förstå dig på mapping flow.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "För att lägga till en användare som vän, skriv /addfriend följt av användarens namn.\nDärutöver så kan du klicka på användarens panel i Online Users-listan (klicka F9) eller deras namn i chatten och klicka på Add as Friend.\nDu kan också lägga till dem via deras profil genom att klicka på Add as Friend.",
    "friends-list": "För att se en lista av dina vänner in-game, klicka F9 och ändra filtret högst upp till Vänner.\nDu kan också se en full lista av dina vänner, både online och offline, på hemsidan genom att klicka på Settings. (Du måste vara inloggad, såklart.",
    "fullscreen": "Du kan ändra huruvida spelet är i Fönster- eller Fullskärmsläge under Grafik sektionen i options menyn.\nDu kan också ändra till och från fullskärmsläge med Alt+Enter på ditt tangentbord. Note: fullskärmsläge är avstängt för OpenGL.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Du kan hitta många olika termer i osu! [[glossary]].",
    "gmt": "[https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team], förkortat [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT], är en grupp av användare som hjälper till i osu!. De har röda namn i chatten och gröna namn på forumet. Dessa användare hjälper till att hålla chatterna och forumet rent.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Läs, revidera, jubla.]",
    "grammar": "Gör det bästa du kan för att använda bra grammatik. Några små misstag i stavning och skiljetecken är acceptabelt, men snälla använd inte snabbskrift eller textskrift. Det får dig att se dum ut.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Vet inte hur man spelar? Vill du utforska världen av beatmapping och moddande? [https://osu.ppy.sh/wiki/Guides Här] hittar du alla svaren.",
    "hacked": "Om du  tror du blivit hackad, var god skicka ett epost meddelande till accounts@ppy.sh för uppföljning.\nMisslyckande av detta kan leda till att kontot tas bort.",
    "hard": "Du ska banne mig lära dig spela först, scrub.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Om du behöver assistans med något osu!-relaterat, gå med i #help kanalen och ställ din fråga.",
    "hitsound-library": "Gå [https://osu.ppy.sh/p/164927 hit] för att skaffa speciella hitsounds för din beatmap.",
    "hl": "Skyll inte på andra användare som highlightar dig ifall du har ett lexikon ord eller någon annan vanlig fras som namn eller i din highlight-lista. Det är ditt fel ändå!\nDu kan inaktivera aviseringar och ljud som spelas upp när det händer i Options om du behöver.",
    "how-to-get-modded": "Om du vill veta hur du kan få din beatmap kollad av någon, klicka här: [[Getting_Your_Map_Modded]]",
    "how-to-bn": "Om du vill bli BN, ta och läs igenom [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator detta] - i de flesta fall är det BNsen som väljer vilka som ska få möjligheten att bli BN baserat på en mängd saker som moddingkvallité och aktivitet.",
    "how-to-gmt": "Chat moderatorer är handvalda från regelbundna bidragsgivare till communityn. Vill du hjälpa till? Gör ditt bästa att moderata vilken kanal du vill som du ofta är i genom att raportera missbruk med !report kommandot.",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F Klicka på denna länken för att lära dig spelet]",
    "how-to-rank": "För att få reda på det, läs [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Hyperdash inträffar när du fångar en frukt som har en röd glöd. Du kommer röra dig snabbare under denna period. Det kommer deaktiveras så fort du når nästa frukt, eller missar den.",
    "ignore": "Om du vill ignorera en användare, skriv /ignore och sedan deras användarnamn.\nDu kan inte se rader skrivna av personer du har ignorerat, det gäller också PM de skickar till dig. Att skriva /unignore och deras användarnamn eller avsluta osu! kommer att häva denna effekt.",
    "import": "Läs [http://i.imgur.com/kpX2N3m.jpg detta] för att få reda på hur du importerar beatmaps till osu!",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Genom att trycka på rutan Ärv tidigare timing inställningar i F6 fönstret av Editor, så ändrar inte timing sektionen timingen längre, vilket är användbart för sektioner som bara ändrar ljudet eller exemplet av mappen. Det är också möjligt att ärva timing sektioner som har dubbel eller halv BPM. Om du använder sådana timing sektioner, snälla ärv dom!",
    "irc": "IRC server: irc.ppy.sh:6667\nLösenord: https://osu.ppy.sh/p/irc\nMer detaljer här https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Du kan ändra dina tangentbindings på input sektionen i options.\nTangeter och layouter i osu!mania ändras i osu!mania layout! -knappen.",
    "kiai": "Kiai läget är en stileffekt som du kan lägga till i timing sektioner genom att använda Timing Setup panelen. Timing sektioner med kiai läget aktiverat använder olika visuella effekter för att göra beatmappen mer episk",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Tjäna [https://osu.ppy.sh/wiki/Kudosu kudosu] genom att modda andra personers mappar.",
    "lag": "Lagg kan orsakas av vad som helst - mest troligt en annan process på din maskin. Om du är övertygad om att det är osu!, och bara osu! som laggar, skicka in en support förfrågan på Technical Support forumet där du detaljerar ditt problem och allt som du har hittat som kan hjälpa identifiera det.",
    "language": "Var trevlig i chatt rummet. Ohövligt språk kan leda till att du blir silencad.",
    "language-specific": "Vänligen använd rätt språk för den kanal du besöker. Att använda Romanized ord eller fraser är inte ett undantag för icke-romerska språk som japanska. ",
    "lazer": "",
    "level": "Din level är baserad på din totala ackumulerade poäng. Detta inkluderar alla rankade poäng, även om du klarade banan eller inte. Du kommer att gradvis öka din level bara genom att spela osu!",
    "lines": "Håll dina meningar på en rad för att undvika bli silencad.",
    "link": "För att göra en länk till någonting, skriv på följande sätt: [adress text], där adress är web adressen du vill länka till och text är vad du vill ska synas. [https://osu.ppy.sh/ precis såhär!] Glöm inte http://",
    "lobby": "Använd endast #lobby för annonsering av osu! multiplayerspel. Dessutom är #lobby en flerspråklig kanal.\nAnvänd ditt rums #multiplayer kanal för alla andra diskussioner.",
    "localisation": "Hitta osu!s lokalisations projekt [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 här].",
    "long-link": "Kopiera inte in långa länkar i chatten! Använd [länk text] formulan om du verkligen måste.",
    "long-text": "Klistra inte in långa texter i chatten. Om du gör det riskerar du att bli silencad.",
    "loved": "Loved är en ny communitybaserad rankingstillstånd som ger maps som normalt är unrankable fulla toplistor. [https://osu.ppy.sh/news/151925254083 Läs mer om det här!]",
    "mac": "[https://osx.ppy.sh Kör osu! på din Mac]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Mappare är upptagna personer, och att mappa tar mycket tid och arbete. Varför inte försöka mappa själv istället?",
    "mapping": "Gå [https://osu.ppy.sh/forum/p/988111 hit] för mapping guides.",
    "mat": "Mapping Assistance Teamet var en äldre användar grupp som assisterade BAT i rankning systemet. ViF MAT 2013-04-23",
    "modhelp": "För alla dina beatmap modding frågor, stick över till #mapping!",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modding Köer]",
    "modreqs": "Gå till #modreqs för några modding förfrågningar. Tänk på att BN kanske inte alltid har tid och att de har andra folk som har frågat först, så kom ihåg att även be vanliga användare att modda dina beatmaps. För att göra en förfrågan, se till att använda / np kommandot eller [länk text] formatet. Glöm inte att säga tack!",
    "multi-invite": "För att bjuda in någon till ditt multiplayer spel, medan du hostar ett rum, klicka på den önskade spelarens namn i Online Users listan (tryck på F9) eller tryck på deras namn i chatten och välj Bjud in till spel.",
    "multi-link": "",
    "multiaccounting": "Du borde verkligen, verkligen inte göra fler än ett konto. Du kommer att bli hittad, och du kan möjligen bli silencad i en väldigt lång tid, eller till och med bannad!",
    "multiplayer": "Gör reklam för ditt rum i #lobby. Om det inte är några andra spelare, varför inte spela solo och försöka igen senare?",
    "mwc": "Det är en global osu! Mania turnering! Se [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 här] för mer info!",
    "nat": "",
    "news": "",
    "nightcore": "Avnjut dina favorit-beatmaps Nightcore style! Dubbelklicka bara DoubleTime modden för att hitta Nightcore modden! Den funkar exakt likadant som DoubleTime när det gäller poäng.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Skriv /np för att visa för andra vad du lyssnar på eller spelar just nu.",
    "nsfw": "Explicita konversation är inte tillåtna. osu! är för alla åldrar, så håll chatten ren, annars så riskerar du att bli silencad utan varning!",
    "osu": "#osu är för att prata om osu!. Diskutera gameplay där, och inte i den här kanalen.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 osu!tablets officiela tråd!] - Läs den här för all information om tablet, och förbeställningsval.",
    "osu!talk": "Osu!talk är en pratshow som hålls av deadbeat och ztrot\ndär de intervjuar medlemmar i Osu!gemenskapen och\ndiskuterar event som till exempel världskupperna.\nVarje avsnitt kommer hållas på [https://discord.gg/014x1ACj2VdUPLU5x discord servern]\n och du kommer att kunna ställa frågor i\nfrågor-och-svar delen. Mer info kan du hitta\n[https://osu.ppy.sh/forum/t/225111 här.]",
    "osucore": "Ett aprilskämt ifrån 2011. Alla beatmaps sattes till DoubleTime farten som standard och hade deras pitch höjd. Detta återvände senare som Nightcore modden, som har samma effekt som DoubleTime hade på den dagen.",
    "osu!droid": "",
    "osumania": "Använd #osumania för osu!mania relaterade diskussioner",
    "osustream": "[https://www.osustream.com osu!stream] är osu! för iOS enheter, gjord och underhålls av vår helt egna peppy! ",
    "osz": "Filformatet för beat maps som du laddar ner för osu! att extahera för att kunna spela. .osz filer måste alltid bli extraherade av osu! själv, annars kan fel uppstå!",
    "osz2": "Ett nytt filformat för beatmaps som menar att varje innehållen fil kan bli enkrypterad, uppdaterad och streamad självständigt från alla andra filer. .osz2 filer behöver inte bli extraherade och kommer alltid att stanna som .osz2 filer i din låt mapp.",
    "owc": "Det är en global osu! turnering! Se [https://osu.ppy.sh/wiki/OWC här] för mer info!",
    "peppy": "peppy är huvud-utvecklaren av osu! och hanterar det mesta av projektet själv.",
    "perfect": "Fick du inte det där SSet? Det här moddet startar automatisk om mappen för dig om du gör ett enda fel. Du kan hitta den genom att höger-klicka eller dubbel-klicka på SuddenDeath i mod-vals skärmen.",
    "ping": "Pong!",
    "pippi": "Maskotten för osu! Pippi-don är taiko (trum) version av Pippi.",
    "piracy": "Diskuttera inte piratkopierat innehåll öppet i den gemensamma chatten. Det är förbjudet och du kan bli silencad.",
    "play-shortcuts": "Fullständig lista av alla genvägsknappar: [[Shortcut_Key_Reference]]",
    "pm": "För att skicka ett privat meddelande till någon, klicka på deras namn i chatten eller på deras användarpanel i Online Users skärmen och tryck på Start Chat. Du kan också använda /msg <användarnamn> <meddelande> eller avända /chat <användarnamn> eller /query <användarman>, som öppnar en seperat flik. För att snabbt svara på det senate privata meddelandet skickat till dig, så kan du använda /r <meddelande>. Ta bort < > så klart.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance Points (pp) är den huvudsakliga ranknings metoden för osu!. Klicka [https://osu.ppy.sh/wiki/performance_points här] för att hitta mer info.",
    "pp-rework-lazer": "",
    "preview": "Förvisningspunkten är den punkt i låten där den börjar spela på låtvals skärmen. En ordentlig förvisningspunkt är den punkt i låten som representar den väl, så som starten av versen. Gå till Timing i verktygsfältet och tryck på Set Current Position as Preview Point för att välja en.",
    "qat": "",
    "qualified": "Beatmap Nominators nominerar mappar som kvalificerade som är redo för ranking där du kan spela utan att få pp.\nOm dessa mappar inte har några problem och stannade på denna status i en vecka, kommer det slutligen bli ranked . Annars går det tillbaka till pending och poängen försvinner.",
    "ranked": "En Ranked beatmap är en beatmap som har blivit godkänd av communityn. När du spelar en Ranked beatmap så gå poängen ifrån den till din totalt ackumulerade rankade poäng. Dessa kartor har sin egna rankade poängtavla, och kan bli identifierade via deras hjärt ikon.",
    "ranking-criteria": "För information på ranknings kriterier, besök gärna wikin: [[RC]]",
    "redname": "Användare med röda namn är antingen en [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] eller en [https://osu.ppy.sh/wiki/QAT QAT]",
    "report": "Använd rapportfunktionen för att rapportera olämpligt beteende eller fusk. Dessutom ska du undvika att rapportera i ett BanchoBot PM, och använd !report <användare> <anledning>.",
    "report-abuse": "Undvik att skicka flera anmälningar i rad - det frambringar inte rättvisa snabbare. Det gör inte heller tomma eller överdrivna anmälningar. Du kan faktiskt bli silencad om du spammar moderatorerna.",
    "request": "Letar du efter något att modda? Tryck [https://osu.ppy.sh/p/beatmaplist&r=8 här] eller skriv in !request för att få en slumpmässig länk till en beatmap.",
    "respect": "Var respektfull mot andra spelare.",
    "roll-abuse": "Överanvänd inte !roll kommandot. Du kan bli silencad.",
    "romaji": "Använd inte Romaji (Romanized Japanese) för mycket. Du kan bli tyst.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Om det inte finns några multiplayer rum att gå med i, varför gör du inte ditt eget? Då kan du också välja låtarna själv!",
    "rp": "Du har fritt fram att rollspela i rätt osu! kanaler; dock så borde du se till att du inte irriterar andra folk i kanalen för mycket.",
    "rules": "[https://osu.ppy.sh/wiki/sv/Rules Officiella Regler]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "Det händer att osu! utsätts för DDoS attacker. När detta pågår, kan Bancho vara ostabilt eller oåtkommligt. Om du misstänker att detta pågår, besök [https://twitter.com/osustatus @osustatus] Twitter-flöde eller [https://status.ppy.sh detta] för mer info. Om detta inträffar, och du fortfarande kan prata - fortsätt som vanligt. Att ta upp ämnet gör inte att det slutar snabbare.",
    "sb": "Guide till storyboarding: https://osu.ppy.sh/forum/t/1869 Hur man använder storyboard editorn: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "Scorev2  är en ny poängalgoritm för alla spellägen som maxar på 1 miljon poäng, exkluderat spinners och mods.\r\nDet ändrar också beteendet för sliders så att de kräver samma timing som cirklar",
    "scoring": "Hur osu! beräknar poäng: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "En silence betyder att du inte kan prata i chatten eller skriva något på forumet, förutom i Technical Support. Silences börjar på 5 minuter från första regelbrytningen, och dubblas varje gång du bryter en regel därefter. Större brott kan mer än dubbla den förra silencen dock. Silences ges ut för de flesta förseelser, så följ bara reglerna så kommer du att vara helt okej.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Vanliga frågor och svar om att göra skin",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Låt inte osu! hålla dig vaken till 4 på natten. Sömn är viktigt!]",
    "songs-not-appearing": "Om dina låtar inte kommer fram testa att tryck på F5.",
    "spaces": "Använd inte mellanslag mellan varje bokstav, det får chatten att se stökig ut och kan leda till att du tystas.",
    "spam": "Spamma inte. Det är irriterande, och det leder oftast till en silence.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "För att kolla på när en annan spelare spelar, skriv /watch <användarnamn>, eller tryck på deras namn i chatten eller användarpanel och välj Start Spectating. Var säker på att du har samma beatmap som de spelar (och att de faktiskt spelar)!",
    "spoiler": "Förbjudet att avslöja handlingen i anime,serie,manga,doujin,etc. Det straffas med silence. Låt folk njuta av deras favoritsaker i lugn o ro.",
    "status": "För status uppdateringar för osu!, gå gärna till [http://twitter.com/osustatus @osustatus]. För serverstatus, gå till https://status.ppy.sh",
    "store": "[https://osu.ppy.sh/p/market Välkommen till osu! marknaden], stället där du kan köpa fantastiska osu! t-shirts och andra coola grejer!",
    "submit": "[https://osu.ppy.sh/wiki/Submission Beatmap Framläggning FAQ]",
    "suck": "osu! har en hög lärningskurva - du blir bättre med tiden, så ge inte upp!",
    "supporter": "Bli en [https://osu.ppy.sh/p/support osu! supporter]",
    "supporter-please": "Be inte andra personer att ge dig supporter tag. [https://osu.ppy.sh/p/support Skaffa det här stället!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Om ditt sikte inte beter sig som det borde, dubbelkolla att muskänsligheten i options är satt till exakt 1.00x. Högre sensitivity på tablet kan bli uppnåt genom att sänka din tablets aktiva area istället.\nOm ditt sikte inte rör sig alls, dubbelkolla att du inte har Raw Input på i inställningar.\nFör alla andra tablet relaterade problem, [https://osu.ppy.sh/forum/t/87301 läs den här tråden.]",
    "tag": "I tag multiplayer läget så tar alla spelare var sin tur att trycka en kombo av en beatmap åt gången. Det finns ingen förlorare eller vinnare, då alla spelare på samma lag. På spinners så är alla spelare med. Även om det bara är en spelare som misslyckas med spinnern så startas kombon om. Alla spelares bonusar läggs till på poängen.",
    "taiko": "En japansk trumma som används i en serie spel av Bandai-Namco. osu!s Taiko Läge simulerar dessa spel genom att eleminera beat placering, vilket tvingar spelaren att fokusera bara på beatmappens rytm. [https://osu.ppy.sh/forum/t/4363 Här är hur du spelare!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Taiko mapping guide]",
    "taiko-maps": "Du kan hitta autentiska Taiko no Tatsujin beatmaps [https://osu.ppy.sh/forum/t/5397 här.[",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Kan du vara snäll och släppa det ämnet och prata om något annat nu?",
    "training": "\n[https://osu.ppy.sh/forum/t/4280 James Träning]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 Lista av uppdaterade video tutorials på osu! och mapping.] Känn dig fri att göra din egen och lägg upp den på tråden. [https://osu.ppy.sh/forum/t/60228 Lista av användbara guider för mappers/modders]",
    "twc": "Det är en global osu! Taiko turnering. Se [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ här] för mer info!",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Undvik att använda unicode/icke-standard tecken i allmän chatt.",
    "upload-cap": "För att hålla mappers dedikerade till deras pågående maps, så finns det en liten gräns för hur många beatmaps du kan arbeta på samtidigt. Icke-supporters kan ha 3-6 aktiva och supporters kan ha 5-10 aktiva, beroende på hur många föregående rankade maps de har.",
    "utf8": "Sätt din IRC klient till att använda en UTF-8 kodning så att du kan både läsa och skriva ordentliga meddelanden till andra användare.",
    "videogames": "Datorspels-relaterade saker kan diskuteras i #osu, men om det stör chatten eller mer än en konversation är igång, gå gärna till #videogames.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Välkomen till osu! Om du har problem eller frågor som behöver besvaras, fråga dom snälla människorna i #help! Ha kul!",
    "when": "När det är klart. ",
    "wiki": "[https://osu.ppy.sh/wiki/ osu! wikin] - Gör den otrolig!",
    "wiki-link": "Du kan länka till wiki sidor genom att skriva wiki inläggens namn i dubbla klammrar: [[...]]\nSom exempel: [[Kudosu]] är skapat genom att skriva Kudosu mellan [[ och ]].",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 209 active FAQs (out of a possible 217) in the Swedish (Svenska) language.",
    "completion": "The Swedish (Svenska) FAQ as of last update is 96.31% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
