
strings = {
    "academy": "[https://www.youtube.com/user/osuacademy กดที่นี้] เพื่อดู osu! academy - วิดีโอฝึกหัดทุกอย่างใน osu!",
    "achievements": "คุณจะได้รับ Achievement ซึ่งเป็นป้ายแสดงความสำเร็จเมื่อคุณทำอะไรพิเศษๆ ได้ระหว่างการเล่น เช่น ทำคอมโบได้สูงๆ หรือเล่น Beatmap ครบทุกแมพในธีมแพคหนึ่งๆ\nคุณสามารถดู Achievement ได้ที่ Profile ของคุณได้เลย ส่วนใหญ่แล้วจะสามารถรู้ได้ว่าคุณจะต้องทำอย่างไรถึงจะได้มา แต่ถึงบางอย่างจะไม่มีบอก ชื่อก็ถือเป็นคำใบ้อย่างหนึ่งนะ!",
    "add-skin": "หากไฟล์ที่คุณดาวน์โหลดมีนามสกุล .osk ลากไฟล์มาที่หน้าต่าง osu! หรือกดไฟล์สองครั้ง\nสำหรับไฟล์ .rar/.zip ให้ extract ไปที่โฟลเดอร์อันเดียว และย้ายไปที่โฟลเดอร์ osu! โดยให้ทำตอนไม่ได้เปิด osu! อยู่",
    "advertising": "การโฆษณา content ที่ไม่เกี่ยวกับ osu! ไม่ได้รับการอนุญาต และอาจทำให้คุณถูกใบ้\nนี่รวมถึงเซอร์เวอร์แชทนอก osu! ทุกชนิด เช่น Discord หรือ Teamspeak",
    "answer": "หากไม่มีใครตอบคำถามของคุณ อาจเป็นไปได้ว่าไม่มีคนที่รู้คำตอบเลยก็ได้นะ ถ้าเป็นเรื่องเกี่ยวกับ osu! สามารถลองค้นหาโพสต์ในฟอรัม",
    "appeal": "ถ้าคุณคิดว่าคุณโดนใบ้อย่างไม่เป็นธรรม ให้ติดต่อแอดมินโดยส่งอีเมลที่อธิบายสถานการณ์ของคุณไปที่ accounts@ppy.sh\nโปรดจำไว้ว่าแอดมินก็เป็นคนเช่นกัน ถ้าคุณทำตัวสุภาพเขาก็คงไม่มีปัญหาและปลดใบ้ให้คุณ ถ้าเป็นไปได้",
    "approved": "Approved Beatmap คือ Beatmap ที่ไม่สามารถ Ranked ได้ด้วยข้อจำกัดบางประการ โดยทั่วไปคือเพลงยาวเกิน 5 นาทีและมี difficulty เดียว, บางครั้ง 2-5 นาที โดยมีตารางคะแนนทุกอย่าง คุณสามารถรู้ถึงแมป approved ได้จากสัญลักษณ์ของบีทแมปซึ่งเป็นรูปไฟแทนที่จะเป็นรูปหัวใจ",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "[[https://osu.ppy.sh/wiki/Contests#aspire Aspire]] คือการแข่งขันสร้างบีทแมพที่ซับซ้อนมาก ได้ถูกจัดขึ้นในปี 2016-2018",
    "ask": "วิธีที่ดีที่สุดในการได้คำตอบก็คือการถามคำถามเลย - ขอถามได้ไหม ก็เป็นคำถามแล้ว",
    "attention": "คุณสามารถหยุดได้ไหม? ดูเหมือนว่าไม่มีใครสนใจที่คุณพูดเลย...",
    "avatar-change": "คุณสามารถเปลี่ยนภาพอวตาร์ของคุณได้ที่นี่ [https://osu.ppy.sh/home/account/edit#avatar].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "สวัสดี! ฉันคือ BanchoBot ยินดีที่ได้รู้จัก!\nแต่ฉันเป็นแค่บอทตัวหนึ่ง ฉันเลยคุยเล่นกับคุณไม่ได้ น่าเสียใจจริงๆ :(",
    "beatmapping": "อ่าน [https://osu.ppy.sh/wiki/Beatmapping Beatmapping] เพื่อหาเคล็ดลับในการทำบีทแมพ",
    "beginner": "[https://osu.ppy.sh/forum/t/5456 กดที่นี่]หากคุณกำลังหาแมปสำหรับมือใหม่ โดยคุณอาจจะสนใจใน[https://osu.ppy.sh/community/forums/topics/75291แมปที่เล่นดีบน touchscreen] อีกด้วย",
    "bn": "[[Beatmap Nomination Group]] คือกลุ่มของคนที่อยู่ในความดูแลเรื่องการแร้งบีทแมพ และเป็นผู้รับผิดชอบในการบริหารจัดการบีทแมพ pending ที่กำลังเข้า ranking cycle \nคุณสามารถพูดคุยกับพวกเขาหากมีคำถามหรือต้องการคำแนะนำเกี่ยวกับการทำแมป หรือ modding โดยพวกเข้าเป็นคนที่ยุ่ง จึงโปรดหลีกเลี่ยงการสแปมพวกเขา",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY ไม่มีสาเหตุในการบอกคนอื่นว่าคุณกำลังเบื่อ คุณสามารถลองพักผ่อนหรือเล่นอย่างอื่นนะครับ] โดยการที่เบื่อไม่ได้แปลว่าคุณสามารถสแปมหรือบ่นเกี่ยวกับอะไรก็ได้ใน osu!",
    "bug": "ถ้าคุณคิดว่าคุณค้นพบ bug กรุณาแจ้ง[https://osu.ppy.sh/forum/5 ที่นี่] โปรดตรวจสอบว่าไม่มีใครได้โพสต์ปัญหาเดียวกับคุณไว้แล้ว",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "อย่าพิมพ์อังกฤษขึ้นต้นด้วยตัวใหญ่ทุกคำ มันคล้ายๆ กับภาษาวิบัติน่ะ",
    "caps": "อย่าพิมพ์อังกฤษตัวใหญ่ทุกตัว มันไม่มีใครต้องการในแชท และมันสามารถทำให้คุณถูกสั่งใบ้",
    "change-modes": "สำหรับการเปลี่ยนโหมดการเล่นนั้น ให้เข้าไปยังหน้าจอเลือกเพลงและคลิกที่ไอคอนโหมดเกมปัจจุบันที่ด้านล่างซ้ายหรือกดปุ่ม Ctrl + 1-4",
    "change-name": "ในการที่จะเปลี่ยนชื่อผู้เล่น คุณต้องเป็น [https://osu.ppy.sh/p/support supporter] ก่อน ถัดจากนั้น คุณสามารถเปลี่ยนชื่อของคุณที่ [https://store.ppy.sh/store/product/32 ลิงค์นี้]!\nสำหรับการขอย้อนกลับไปใช้ชื่อเก่า, การเปลี่ยนแปลงเล็กน้อย, หรือความช่วยเหลือ โปรดส่งอีเมลไปที่ accounts@ppy.sh โดยเขียนรายละเอียดไปด้วย",
    "changelog": "คุณสามารถอ่านบันทึกอัพเดตของเกม, Bancho, และเว็บไซต์ได้[https://osu.ppy.sh/p/changelog ที่นี่]!\n",
    "chars": "กรุณาหลีกเลี่ยงการใช้ตัวอักษร unicode หรือตัวอักษรที่ไม่ใช่มาตรฐาน ในแชททั่วไป",
    "charts": "Chart เป็นเซ็ตของ Beatmap ที่จัดออกมาทุกเดือน โดยจะเป็นการรวมแมพที่ได้รับการเสนอชื่อมาในเดือนนั้นๆ หรือแมพที่อยู่ในธีมใดธีมหนึ่ง สามารถดูได้[https://osu.ppy.sh/p/chart ที่นี่]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "สีเหลืองอ่อน: ผู้เล่นทั่วไป | สีเหลืองเข้ม: [https://osu.ppy.sh/p/support Supporter]\nสีแดง: [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team NAT] หรือ [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nสีขาว: ตัวเองหรือข้อความ /me | สีน้ำเงิน: ข้อความส่วนตัว\nสีเขียว: บรรทัดที่มีชื่อของคุณ (ไฮไลท์) | สีชมพู: BanchoBot\n",
    "colour": "สีเหลืองอ่อน: ผู้เล่นทั่วไป | สีเหลืองเข้ม: [https://osu.ppy.sh/p/support Supporter]\nสีแดง: [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team NAT] หรือ [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT]\nสีขาว: ตัวเองหรือข้อความ /me | สีน้ำเงิน: ข้อความส่วนตัว\nสีเขียว: บรรทัดที่มีชื่อของคุณ (ไฮไลท์) | สีชมพู: BanchoBot\n",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "ในขณะที่ที่คุณกำลังใช้คำสั่งเพื่อความสะดวกในการใช้งานโปรดอย่าใช้มากเกินไป อาจจะถูกมองว่าเป็นสแปมและอาจส่งผลให้โดนใบ้ได้นะ ",
    "comment": "สำหรับการพิมพ์ความเห็นใน Beatmap ให้คลิกแท็บ Discussion ทางด้านขวาในขณะที่กำลังชม Replay จากนั้นให้คลิกที่กล่องเพื่อให้ข้อความที่ต้องการพิมพ์แสดง ณ จุดที่หยุดอยู่ แล้วพิมพ์ความเห็นที่คุณต้องการพิมพ์และกด Enter\nถ้าความเห็นยังไม่แสดงขึ้นมา ให้คลิกปุ่ม Show Comments ในช่อง Discussion",
    "comment-color": "ถ้าเป็นแค่ผู้เล่นธรรมดา ความเห็นในรีเพลย์จะเป็นสีขาวเท่านั้น แต่ถ้าเป็น [https://osu.ppy.sh/p/support Supporter] จะสามารถเปลี่ยนสีของความเห็นได้ตามใจชอบ~",
    "conferencemode": "หากคุณใช้ IRC และต้องการปิดข้อความเข้าห้อง/ออกห้อง (Join/Quit) ก็[http://wiki.xkcd.com/irc/Hide_join_part_messages ลองอ่านวิธีได้ที่นี่]",
    "country-ranking": "สามารถดูตารางคะแนน[https://osu.ppy.sh/p/countryranking อันดับของประเทศ]ได้ที่นี่",
    "critic": "กรุณาวิจารณ์อย่างสร้างสรรค์ แนะนำทางเลือกหรือวิธีการที่จะแก้ไขปัญหาที่คุณมีความกังวลเกี่ยว",
    "ctb": "ต้องการความช่วยเหลือเกี่ยวกับโหมดเก็บผลไม้? [https://osu.ppy.sh/wiki/Catch_the_Beat นี่]เป็นหน้าวิกิ!",
    "cutting-edge": "Cutting-edge ​​คือ ตัวเกมที่กำลังถูกพัฒนา ใช้เพื่อทดสอบคุณสมบัติใหม่ๆ ก่อนที่จะขึ้นไปอยู่บนบนเกมที่สเถียร ในการสร้าง คุณสามารถเสลับเปลี่ยนได้ที่การอับเดทใน Option\nคุณสามารถ [ https://osu.ppy.sh/wiki/Help_Center#Updater_Issues อ่านบทความนี้] ถ้าคุณมีปัญหาใดๆ ในการอัพเดต client ของคุณได้นะ",
    "cwc": "การแข่งขันทัวร์นาเม้นท์ osu! Catch the Beat ระดับโลก [https://osu.ppy.sh/wiki/Tournaments/CWC/2019 อ่านหน้านี้สำหรับรายละเอียดเพิ่มเติม]",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\r\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\r\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "โปรดให้เกียรติคนอื่นเหมือนที่คุณถูกยึดถือโดยผู้อื่น หากคุณเป็นคนที่ใช้คำเฉลียวฉลาด คิดซะว่าคนอื่นไม่ใช่",
    "disable-this": "มันดูไม่ดีเลยที่จะสร้างตัวปิดคุณสมบัติบางอย่างที่คุณไม่ต้องการ รู้หรือเปล่า... มันยากนะกว่าจะสร้างคุณสมบัติแบบนี้ได้",
    "distance-snap": "วิธีการที่ง่ายที่สุดที่จะทำให้ระยะห่างระหว่างจังหวะถูกต้องเหมาะสมคือการใช้ Distance Snap ของตัวแก้ไข Beatmap ซึ่งจะอยู่ที่มุมขวาล่างของหน้าจอ สามารถปรับระยะห่างระหว่างโน้ตได้ด้วยการใช้ลูกกลิ้งเมาส์ ถ้าคุณใช้ Distance Snap ทั้งแมพ คุณก็ไม่ต้องมาพะวงถึงความถูกต้องตรงจุดนี้อีกต่อไป เพราะ Distance Snap จัดการให้คุณเรียบร้อยแล้ว!",
    "dont-ask-peppy": "โปรดอย่าถาม peppy ตลอด - เขายุ่งอยู่พอสมควรเลย สามารถถามคนอื่นในห้องพูดคุยนี้ได้นะครับ",
    "douche": "เพื่อเป็น safeguard การที่หลีกเลี่ยงกฎและความสงบโดยช่องโหว่ในกฎ สามารถถูกทำโทษได้โดยดุลยพินิจของทีมบริหาร กฎอย่างเป็นทางการที่บอกว่าคุณไม่ควรเป็น douche ไม่น่าจะต้องมีสำหรับที่คุณจะไม่เป็น douche แต่ว่าเพื่อกันไว้: อย่าเป็น douche",
    "download": "[https://osu.ppy.sh/p/beatmaplist ดาวน์โหลดแมพที่นี่]\n[https://osu.ppy.sh/beatmaps/packs ดาวน์โหลดแบบแพ็ค]",
    "drugs": "ห้ามพูดคุยเกี่ยวกับยาเสพติด สิ่งมึนเมาหรือสิ่งที่เกี่ยวข้องทุกชนิดในทุกห้องแชท",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "อ่าน [[Beatmapping#Keyboard_Shortcuts]] สำหรับดูคำสั่งย่อในโหมด Editor",
    "english": "#english เป็นห้องแชทสำหรับคุยจิปาถะต่างๆ ที่ไม่ได้เกี่ยวข้องกับห้องคุยอื่นๆ รวมถึงการ์ตูนและอนิเมะ\nกรุณาใช้ภาษาอังกฤษในการพูดคุยเท่านั้น\n",
    "evade": "การหลีกเลี่ยงการถูกสั่งใบ้อาจทำให้คุณถูก restrict เป็นเวลายาวนาน โปรดอย่าทำ",
    "fallback": "",
    "faq": "คุณกำลังใช้ระบบ osu!Bancho FAQ\nosu! wiki: https://osu.ppy.sh/wiki",
    "feature": "ถ้าคุณอยากได้คุณสมบัติใหม่ที่คุณต้องการให้มีในเกม osu! กรุณาเข้าไปยังฟอรั่มนี้ [https://osu.ppy.sh/forum/4 Feature Request]",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "โปรดอย่าหลีกเลี่ยงระบบกรองคำไม่สุภาพในแชท",
    "foul-play": "เวลารายงานคนโกงในเกม กรุณาใช้ปุ่มรายงานที่หน้าโปรไฟล์คนนั้น [https://i.imgur.com/GG9xlLA.png ดูตามภาพ] และบอกข้อมูล (การโกง) มาให้มากที่สุดเท่าที่จะทำได้ นอกจากนี้ยังสามารถรายงานผ่านทาง scoreboard (50 อันดับแรก) ของบีตแมปนั้น ๆ ได้. และกรุณาอย่าพูดในช่องแชตสาธารณะด้วย เพราะอาจทำให้เราโดนใบ้ได้",
    "percolate": "โปรดอย่าหลีกเลี่ยงระบบกรองคำไม่สุภาพในแชท",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "อ่าน[https://osu.ppy.sh/forum/t/86329 กระทู้นี้]เพื่อศึกษาการ Mapping เพลงของคุณให้ลื่นไหลตามจังหวะมากขึ้น",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "สำหรับการเพิ่มเพื่อนในเกม ให้กด F9 แล้วคลิกที่ User panel ที่คุณต้องการเป็นเพื่อนด้วยแล้วเลือก Add as friend\nและคุณยังสามารถเพิ่มเพื่อนได้ผ่านทาง Userpage ในเว็บโดยเข้าไปยัง Userpage ของผู้ที่ต้องการเพิ่มเพื่อนและคลิกคำว่า Add as Friend\nหรือคุณก็สามารถพิมพ์ /addfriend แล้วตามด้วยชื่อผู้เล่นที่ต้องการในแชทก็ได้เช่นกัน",
    "friends-list": "ถ้าจะดูรายชื่อเพื่อนให้กด F9 แล้วเลือก Filter ที่ด้านบนสุด\nและคุณยังสามารถดูรายชื่อเพื่อนทุกคนที่ออนไลน์ และออฟไลน์ได้ในเว็บ โดยกดที่ Setting (จะทำได้ก็ต่อเมื่อล็อคอินแล้วเท่านั้น)",
    "fullscreen": "คุณสามารถเปลี่ยนหน้าต่างเกมให้ด้วยโหมดเต็มหน้าจอหรือโหมด Window ได้โดยเข้าไปที่ Options > แท็บ Graphics\nหรือคุณก็สามารถกด ALT+Enter ได้เช่นกัน",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "อ่าน [[Glossary]] เพื่อหาความหมายของศัพท์เฉพาะที่ใช้ในเกม osu!",
    "gmt": " [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team] หรือเรียกสั้นๆ คือ GMT เป็นกลุ่มผู้เล่นที่ช่วยทำให้ osu! ไปต่อได้ พวกเขามีชื่อสีแดงในเกมส์ และสีเขียวในฟอรัม \nพวกเขาช่วยดูแลแชทและฟอรั่ม\n",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 ง่ายนะ ขนาดคุณยังทำได้เลย... คิดว่านะ...]",
    "grammar": "พยายามใช้ภาษาให้ถูกหลัก พิมพ์ผิดเป็นเรื่องเล็กน้อย แต่การพิมพ์ภาษาวิบัติจะทำให้ไม่มีใครเข้าใจที่คุณจะสื่อ มันทำให้คุณดูประหลาดอีกด้วย",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "อยากรู้ว่าเกมนี้เล่นยังไง ? อยากเข้าสู่วงการ Modding และ Mapping ? อ่าน [https://osu.ppy.sh/wiki/Guides ที่นี่] แล้วคุณจะเจอคำตอบที่คุณต้องการ",
    "hacked": "ถ้าคุณคิดว่าคุณถูกแฮคบัญชี โปรดรีบอีเมล์แจ้ง accounts@ppy.sh เพื่อติดตามปัญหา\nหากไม่ทำตาม หรือแจ้งข้อมูลผิดพลาด อาจทำให้บัญชีของคุณถูกสั่งปิด",
    "hard": "",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "ถ้าคุณต้องการความช่วยเหลือเกี่ยวกับเกม osu! กรุณาเข้าห้อง #help แล้วถามมาได้เลยครับ (ภาษาอังกฤษ)",
    "hitsound-library": "อ่านกระทู้ [https://osu.ppy.sh/forum/p/164927] ถ้าต้องการ Hitsound แบบอื่นๆ สำหรับ Beatmap ของคุณ",
    "hl": "เลิกบ่นเกี่ยวกับคำที่คุณเพิ่มไว้ในชื่อเล่นหรือฉายาแล้วถูกไฮไลท์เป็นประจำ คุณผิดเองที่เอาคำทั่วไปมาตั้งแล้วถูกไฮไลท์ ถ้าคุณไม่ชอบ ก็ลบคำนั้นออกไป",
    "how-to-get-modded": "หากคุณอยากรู้ว่าจะหาคนตรวจแมพของคุณได้อย่างไร คลิก [[Getting_Your_Map_Modded]]",
    "how-to-bn": "หากคุณต้องการเป็น BN โปรดอ่าน [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator บทความนี้].",
    "how-to-gmt": "ผู้ดูแลได้รับการคัดเลือกจากปริมาณที่พวกเขาได้ช่วยเหลือ community \nสำหรับรายละเอียดเพิ่มเติม อ่านได้ที่หน้าวิกิ: [https://osu.ppy.sh/wiki/People/The_Team/Global_Moderation_Team Global Moderation Team]",
    "how-to-play": "ศึกษาวิธีการเล่น [https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F คลิกที่นี่]",
    "how-to-rank": "อยากให้ Beatmap ของคุณได้ Ranked อ่าน [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "ไฮเปอร์แดชจะเกิดขึ้นเมื่อคุณเก็บผลไม้สีแดงได้ คุณจะสามารถแดชได้เร็วกว่าปกติชั่วระยะเวลาหนึ่ง และผลจะหายไปเมื่อคุณเก็บผลไม้ลูกต่อไป หรือเก็บไม่ทัน",
    "ignore": "สำหรับการเพิกเฉยผู้เล่น ให้พิมพ์ /ignore แล้วตามด้วยชื่อผู้เล่น\nคุณก็จะไม่ได้รับข้อความที่คุณได้ตั้งค่าเพิกเฉยไว้ ทั้งในห้องแชทและข้อความส่วนตัว\nสำหรับการยกเลิกการเพิกเฉยให้พิมพ์ /unignore ตามด้วยชื่อผู้เล่นหรือออกจากเกม osu! เพื่อยกเลิกคำสั่งเพิกเฉย",
    "import": "ดู [http://i.imgur.com/kpX2N3m.jpg] วิธีเพิ่ม Beatmap เข้าสู่ osu!",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "การเลือก Inherit previous timing settings ในหน้าต่าง F6 ของ Beatmap Editor จะทำให้ส่วนดังกล่าวไม่แก้ไขค่า Timing ก่อนหน้า มีประโยชน์มากในการปรับเปลี่ยนเสียง\nนอกเหนือจากนั้นสามารถเลือกได้ว่าจะใช้ BPM เท่าก่อนหน้า น้อยกว่าก่อนหน้าครึ่งหนึ่ง หรือสองเท่าจากก่อนหน้า ดังนั้นถ้าจะให้ไวสองเท่า ช้าสองเท่า อย่าลืมเลือก inherit!",
    "irc": "เซิร์ฟเวอร์ IRC: irc.ppy.sh:6667\nรหัสผ่าน: https://osu.ppy.sh/p/irc\nข้อมูลเพิ่มเติม: https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "คุณสามารถเปลี่ยนคีย์ที่ใช้เล่นในหน้า input ใน options\nคีย์และการจัดเรียงใน osu!mania สามารถเปลี่ยนได้ที่ปุ่ม osu!mania layout",
    "kiai": "โหมด Kiai คือรูปแบบเอฟเฟคที่คุณสามารถตั้งได้ใน Timing setup panel จุดไทม์มิ่งที่เปิดโหมด Kiai ไว้จะแสดงผลเอฟเฟคเพื่อให้ Beatmap มีความ เจ๋ง! มากขึ้น และควรใช้โหมด Kiai ให้เหมาะสมกับเพลง",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "[https://osu.ppy.sh/wiki/Kudosu] คุณสามารถรับ Kudosu ได้จากการ Modding Beatmap ของผู้อื่นและให้ความเห็นที่เป็นประโยชน์",
    "lag": "แลคสามารถเกิดขึ้นได้จาก[https://osu.ppy.sh/help/wiki/Performance_Troubleshooting อะไรก็ได้] - ส่วนใหญ่น่าจะเกิดจาก process อื่นบนคอมของคุณ หากคุณเชื่อว่ามีแค่ osu! ที่แลคอยู่ สามารถขอความช่วยเหลือได้ที่[https://osu.ppy.sh/forum/5 ฟอรัมช่วยเหลือ] โดยบอกปัญหาของคุณและอะไรก็ได้ที่คุณเจอที่อาจจะสามารถทำให้รู้ถึงมันได้",
    "language": "กรุณาพิมพ์ข้อความอย่างสุภาพในห้องแชทนะครับ วาจาไม่สุภาพอาจทำให้คุณถูกใบ้ได้",
    "language-specific": "",
    "lazer": "",
    "level": "เลเวลของคุณคิดจากคะแนนสะสมทั้งหมดของคุณ รวมถึงคะแนน Ranked ไม่ว่าเล่นผ่านหรือไม่ผ่าน\nเลเวลของคุณจะเพิ่มขึ้นเองเมื่อเล่น osu! ไปเรื่อยๆ",
    "lines": "โปรดพยายามพิมพ์ประโยคของคุณในบรรทัดเดียวเพื่อหลีกเลี่ยงในการถูกใบ้",
    "link": "ในการทำลิงค์ข้อความไปบางอย่าง ให้ใช้ format ดังนี้: [address text] โดย 'address' คือ URL ที่คุณต้องการลิงค์ และ 'text' คือข้อความที่อยากให้แสดง\n[https://osu.ppy.sh/ แบบนี้เลย!] อย่าลืมใส่ http:// นะ",
    "lobby": "ห้อง #lobby เป็นห้องสำหรับหาเพื่อนเล่น Multiplayer เท่านั้น และเป็นห้องหลายภาษา หากจะพูดคุยทั่วไป กรุณาใช้ห้อง #thai หรือ #multiplayer",
    "localisation": "ค้นหาโปรเจ็คท์แปลภาษาเกม osu! ได้ที่นี่ [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 ที่นี่]",
    "long-link": "อย่าวางลิงก์ที่ยาวมากๆ ใส่แชทโดยตรง ถ้าคุณต้องการวางลิงก์ยาวๆ กรุณาใส่ [ลิงก์ที่ต้องการ ข้อความ]\n",
    "long-text": "กรุณาอย่าวางข้อความยาว ๆ ลงในแชท การทำเช่นนี้อาจทำให้คุณถูกใบ้",
    "loved": "Loved เป็นสถานะ ranking ใหม่ ที่ให้ตารางคะแนนกับแมพที่ปกติจะไม่สามารถ rank ได้ \n[https://osu.ppy.sh/wiki/Project_Loved อ่านต่อได้ที่นี่]",
    "mac": "[https://osx.ppy.sh วิธีเล่น osu! บน OSX]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "ผู้ทำ Beatmap ก็ยุ่งพออยู่แล้ว การ Mapping ก็เป็นงานที่ยุ่งยาก การขอให้แมพเพลงที่ชอบคงไม่ดีเท่าไหร่",
    "mapping": "อ่านกระทู้ [https://osu.ppy.sh/forum/p/988111] สำหรับการทำ Beatmap เบื้องต้น",
    "mat": "MAT คือกลุ่มคนที่มีฝีมือในการ Modding และช่วยเหลือเกี่ยวกับการสร้าง Beatmap และปรับแต่งจุดผิดพลาดต่างๆ\nและวันที่ 23 เมษายน 2013 ได้ยุติบทบาทหน้าที่ของกลุ่ม MAT ทั้งหมด [https://osu.ppy.sh/forum/p/2258963]\n",
    "modhelp": "ถ้ามีข้อสงสัยในการ Modding ให้เข้าไปยังห้อง #mapping",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modding Queues]",
    "modreqs": "กรุณาเข้าไปยังห้อง #modreqs สำหรับการขอช่วยให้ Modding Beatmap และจำไว้ว่าทั้ง BAT อาจไม่ว่างหรือพวกเขาอาจกำลังช่วย Modding ให้ผู้ที่ขอก่อนหน้านั้น ดังนั้นลองถามผู้เล่นทั่วไปให้ช่วย Modding ดูก่อนนะครับ",
    "multi-invite": "ถ้าคุณต้องการเชิญผู้เล่นเข้าห้อง Multiplayer ของคุณ ขณะที่คุณเป็นเจ้าของห้อง ให้คลิกที่ User panel ของผู้เล่นที่ต้องการเชิญบน Online user list (F9) แล้วเลือก Invite to game",
    "multi-link": "[https://osu.ppy.sh/community/forums/topics/338482 วิธีสร้างลิงค์ไปที่ห้องเล่นหลายคนของคุณโดยตรง]\n",
    "multiaccounting": "คุณไม่ควรที่จะสมัครหลายไอดีอันเด็ดขาด เพราะถ้าหากถูกจับได้ คุณจะโดนใบ้นานมากๆ หรือโทษสูงสุดคือไอดีคุณจะถูกแบนทั้งหมดเลยล่ะ",
    "multiplayer": "กรุณาประกาศหาเพื่อนเล่นที่ #lobby เท่านั้น",
    "mwc": "การแข่งขัน osu! Mania ทั่วโลก\nดู[https://osu.ppy.sh/wiki/Tournaments/MWC/2019_4K ที่นี่]สำหรับข้อมูลเพิ่มเติม",
    "nat": "[https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] ดูแล Beatmap Nominator และดูถึงกระบวนการแร้งแมพ\nพวกเขามีหน้าที่ในการประเมิน Beatmap Nominator ปัจจุบัน และที่จะเข้าในอนาคต รวมทั้งพูดคุยถึงเรื่อง beatmap veto และการขัดแข้งอื่น ๆ เกี่ยวกับการแมป / modding",
    "news": "",
    "nightcore": "สนุกกับ Beatmap ที่คุณโปรดปรานด้วย Nightcore style!\nเพียงแค่คลิกสองครั้งที่ DoubleTime Mod ก็จะเข้าสู่โหมด Nightcore!",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "พิมพ์ /np เพื่อให้คนอื่นเห็นว่าคุณกำลังฟังเพลงหรือกำลังเล่นเพลงอะไรอยู่",
    "nsfw": "พยายามหลีกเลี่ยงการใช้ภาษาไม่สุภาพ osu! เป็นเกมสำหรับทุกอายุ ดังนั้นโปรดอย่าทำให้แชทไม่สะอาด คุณอาจจะถูกใบ้โดยไม่มีการเตือน",
    "osu": "#osu มีไว้สำหรับคุยเรื่องเกม osu! กรุณาคุยเรื่องเกมในห้องนั้นเท่านั้น",
    "osu!tablet": "อ่าน[https://osu.ppy.sh/forum/t/169139&start=0 กระทู้นี้] สำหรับรายเอียดสเปคต่างๆ และการพรีออเดอร์ osu!tablet",
    "osu!talk": "",
    "osucore": "เอพริลฟูลส์เดย์ (วันเมษาหน้าโง่) ประจำปี 2011\nBeatmap ทุกเพลงถูกใส่ DoubleTime mod และถูกปรับเสียงอัตโนมัติ\nโดยภายหลังได้เรียกว่า Nightcore Mod\nซึ่งมีผลเช่นเดียวกันกับ DoubleTime ในวันนั้น",
    "osu!droid": "",
    "osumania": "กรุณาเข้าห้อง #osumania สำหรับการพูดคุยเกี่ยวกับโหมด osu!mania",
    "osustream": "[http://www.osustream.com - osu!stream คือ osu! สำหรับระบบปฎิบัติการ iOS โดยผลิตจากทีมพัฒนาของคุณ peppy เอง!]",
    "osz": "รูปแบบไฟล์ปัจจุบันที่เกมใช้ในการเล่น Beatmap เมื่อคุณดาวน์โหลดจากในเว็บ เมื่อนำเข้าเกมแล้วต้องแตกไฟล์ทุกครั้งและบางครั้งอาจก่อให้เกิดปัญหาได้",
    "osz2": "รูปแบบไฟล์ Beatmap ชนิดใหม่ที่จะรวมไฟล์ของ Beatmap ทั้งหมดอยู่ในไฟล์เดียว (ลักษณะคล้ายๆ ไฟล์ซิป) ได้รับการเข้ารหัส อัพเดทและใช้ได้ตลอดเวลา\nไฟล์ .osz2 ยังไม่จำเป็นต้อง แตกไฟล์ เพื่อใส่เข้าเกมอีกด้วยและโฟลเดอร์ songs ของคุณก็จะมีเพียงไฟล์ .osz2 อยู่เท่านั้น",
    "owc": "การแข่งขันทัวร์นาเม้นต์ osu! ระดับโลก [https://osu.ppy.sh/wiki/OWC อ่านหน้านี้สำหรับรายละเอียดเพิ่มเติม]",
    "peppy": "คุณ peppy คือผู้ที่อยู่เบื้องหลังและผลักดันเกม osu! จนถึงทุกวันนี้ ",
    "perfect": "ทำ SS ไม่ได้เหรอ ? Mod ตัวนี้สามารถให้คุณเริ่มเกมใหม่ได้ทันทีเมื่อคุณกดพลาดเพียงเสี้ยววินาที\nคุณสามารถเลือก Mod นี้ได้ด้วยการคลิกสองครั้งที่ Mod SuddenDeath",
    "ping": "Pong!",
    "pippi": "มาสคอทประจำเกม osu!\nPippi-don คือ Pippi ในเวอร์ชั่นไทโกะ",
    "piracy": "อย่าถามหรือพูดคุยเกี่ยวกับสิ่งของผิดกฎหมายและละเมิดลิขสิทธิ์ในห้องแชท ไม่อนุญาตให้ทำเช่นนั้น อาจจะทำให้คุณถูกใบ้ได้",
    "play-shortcuts": "ปุ่มช็อตคัททั้งหมดในเกม : [[Shortcut_Key_Reference]]",
    "pm": "สำหรับการส่งข้อความส่วนตัวให้ผู้เล่นอื่น ให้คลิกที่ชื่อของเขาในแชทหรือ User panel ของเขาในหน้าจอ F9 จากนั้นให้คลิก Start Chat\nคุณยังสามารถใช้คำสั่ง /msg <ชื่อผู้เล่น> <ข้อความ> หรืออีกวิธี /chat <ชื่อผู้เล่น> หรือ /query <ชื่อผู้เล่น> ก็จะเป็นการเปิดหน้าต่างพูดคุยแยกเพิ่มมาในช่องแชท\nและการพิมพ์ตอบแบบไวของข้อความที่คุณได้รับล่าสุดนั้น ให้พิมพ์ /r <ข้อความ> อ้อ! อย่าลืมเอาเครื่องหมาย <> ออกก่อนกด Enter นะครับ ^^",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "[https://osu.ppy.sh/wiki/Performance_Points Performance Points] (pp) คือตัวกำหนด ranking ของ osu!",
    "pp-rework-lazer": "",
    "preview": "Preview point คือจุดที่เอาไว้โชว์เพลงเวลาเลือกเพลง หรือกดฟังในเว็บ\nส่วนมากในการเลือก Preview point จะเลือกจากท่อนเพลงที่น่าสนใจ จุดที่นิยมคือท่อนฮุก\nในการตั้งค่า Preview point ให้ไปที่จุดที่ต้องการจะเริ่มก่อน ต่อจากนั้นให้ไปทีเมนู Timing ตรงด้านบนสุด และเลือก Set Current Position as Preview Point\n",
    "qat": "",
    "qualified": "Beatmap Nominator สามารถเสนอแมปให้ไปใน qualified สำหรับการแร้ง โดยคุณสามารถได้แร้งโดยไม่ได้ performance points\nหากแมพพวกนี้ไม่มีปัญหาใดๆ และอยู่ใน qualified เป็นเวลาหนึ่งสัปดาห์ แมปจะถูกแร้ง นอกเหมือนจากนั้น มันจะกลับไปสู่ pending และคะแนนทั้งหมดจะถูกลบ",
    "ranked": "Ranked Beatmap คือ Beatmap ที่ได้รับการยอมรับและอนุมัติจากทีมตรวจสอบและผู้เล่นอื่นๆ เรียบร้อยแล้ว\nเมื่อคุณเล่น Beatmap ชนิดนี้ คะแนนที่คุณทำได้จะถูกนำไปรวมกับคะแนนสะสมทั้งหมดของคุณ\nBeatmap เหล่านี้จะมี Leaderboard เป็นของตนเอง และมีสัญลักษณ์คือไอคอนรูปหัวใจ",
    "ranking-criteria": "สำหรับข้อมูลเกี่ยวกับกฏของบีทแมพ ให้ไปที่ wiki: [[RC]]",
    "redname": "คนที่มีชื่อสีแดงในแชทเป็นได้ทั้ง [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] และ [https://osu.ppy.sh/wiki/QAT QAT]",
    "report": "กรุณาใช้ format ต่อไปนี้เพื่อรายงานพฤติกรรมที่ไม่เหมาะสม หรือการขี้โกง: !report <ชื่อผู้เล่น> <สาเหตุ>\nผู้เล่นคนอื่น ๆ จะไม่เห็นการรายงาน และกรุณาใช้คำสั่งในช่อง channel สาธารณะ หลีกเลี่ยงการใช้ใน PM\nทั้งนี้ คุณสามารถรายงานผู้เล่นได้อีกทาง คือการกดที่ชื่อของชื่อผู้ใช้ และเลือก Report User หรือ แจ้งรายงาน",
    "report-abuse": "กรุณาอย่า !report ถี่จนเกินไปในครั้งเดียว มันไม่ช่วยให้แก้ปัญหาได้ไวขึ้น\nแต่อาจจะทำให้คุณโดนใบ้เสียเอง เนื่องจาก สแปมห้องแอดมิน\n",
    "request": "กำลังมองหาแมพที่จะม็อดอยู่หรอ? [https://osu.ppy.sh/p/beatmaplist&r=8 ลองนี่สิ] หรือพิมพ์ !request เพื่อสุ่มแมพ",
    "respect": "กรุณาเคารพผู้เล่นคนอื่นด้วย",
    "roll-abuse": "โปรดอย่าใช้คำสั่ง !roll ถี่จนเกินไป เพราะคุณอาจโดนสั่งใบ้",
    "romaji": "โปรดอย่าใช้ romaji อย่างมากเกินไป คุณอาจถูกสั่งใบ้ได้",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "ไม่มีห้องให้เข้าไปเล่นเหรอ ? ถ้างั้นคุณก็สร้างห้องใหม่สิ แล้วคุณก็จะเลือกเพลงเองได้ด้วยนะ!",
    "rp": "คุณสามารถเล่นโรลเพลย์ในห้องแชท osu! ได้ตามความเหมาะสม แต่ถึงอย่างนั้น ควรดูให้แน่ใจว่าไม่ได้ทำให้คนอื่นที่อยู่ในห้องรำคาญนะ",
    "rules": "[https://osu.ppy.sh/wiki/th/Rules กฎทางการของเกม]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "ในบางครั้ง เซิฟเวอร์ osu! ก็โดน DDoS อยู่บ้าง (โดนยิงจนเซิฟล่ม) ในเวลาดังกล่าว Bancho อาจไม่สามารถเชื่อมต่อเข้ากับผู้เล่นหรือไม่มีเสถียรภาพ\nถ้าคุณคิดว่าเกิดกรณีนี้ขึ้น ให้เข้าไปดูที่ [https://twitter.com/osustatus ทวิตเตอร์@osustatus] หรือ[https://status.ppy.sh ที่นี่] สำหรับรายละเอียดเพิ่มเติม\nถ้าเกิดเหตุการณ์นี้และคุณยังพูดคุยกับคนอื่นได้ ก็ทำตัวตามปกติครับ การไปตั้งกระทู้ไม่ได้ช่วยแก้ปัญหาไวขึ้นนะ\n",
    "sb": "[[Storyboarding]]\nคำแนะนำในการทำ Storyboard: https://osu.ppy.sh/forum/t/1869\nทำ Storyboard อย่างไร: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "scorev2 เป็น algorithm ในการให้คะแนนแบบใหม่ ซึ่งจำกัดคะแนนในเกมโหมดทั้งหมดที่ 1 ล้านแต้ม ไม่รวมถึง spinner หรือ mod ต่าง ๆ\nพฤติกรรมของ slider ได้ถูกเปลี่ยนแปลงอีกด้วย โดยต้องกดแม่นยำให้เหมือน hitcircle",
    "scoring": "osu! ใช้ระบบคำนวณคะแนนยังไง: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "การถูกสั่งใบ้หมายความว่าคุณจะไม่สามารถพูดคุยหรือโพสต์ใดๆ ได้ในฟอรั่ม แต่ยกเว้นหมวด Technical Support ที่สามารถโพสต์ได้\nระยะเวลาการใบ้จะทำงานที่ 5 นาทีเมื่อทำผิดกฎครั้งแรก จากนั้นผลจะเพิ่มเป็นเท่าตัวเมื่อทำผิดกฎครั้งต่อไป และการทำผิดกฎที่รุนแรงจะมีผลมากกว่าหลายเท่าตัว\nระบบสั่งใบ้มีไว้สำหรับป้องกันและรับมือพวกป่วนแชท สแปมหรืออื่นๆ ดังนั้นแค่ทำตามกฎ คุณก็จะไม่เป็นไรครับ",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 คำถามที่พบบ่อยเกี่ยวกับการทำสกิน]",
    "sleep": "คุณเล่นเกมจนดึกมากแล้ว ไปนอนพักผ่อนเพื่อสุขภาพของคุณเองนะครับ",
    "songs-not-appearing": "ถ้าคุณเพิ่มเพลงใหม่แล้วยังไม่พบในหน้าเลือกเพลง ลองกดปุ่ม F5 เพื่อทำการรีเฟรช",
    "spaces": "โปรดอย่าเว้นวรรคในทุก ๆ ตัวอักษร มันทำให้แชทดูแกะกะและสามารถนำไปสู่การใบ้ได้",
    "spam": "โปรดอย่าสแปม มันน่ารำคาญและมักจะนำไปสู่การใบ้",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "สำหรับการชมการเล่นเกมของผู้อื่น ให้พิมพ์ /spectate ตามด้วยชื่อของผู้เล่นที่จะเข้าไปชม\nหรือคลิกที่ User panel ของผู้เล่นนั้นๆแล้วเลือก Start Spectating\nโปรดตรวจสอบว่าคุณมี Beatmap ที่เขากำลังเล่นอยู่ด้วย",
    "spoiler": "การสปอยล์อนิเมะ ละคร มังงะ หรือแม้แต่โดจิน เป็นเรื่องต้องห้าม และคุณอาจจะโดนใบ้ก็ได้",
    "status": "คุณสามารถดูสถานะของเซิฟเวอร์ osu! และการอัพเดทล่าสุดได้ที่ [http://twitter.com/osustatus @osustatus] สำหรับสถานะเซอร์เวอร์ ดูที่[https://status.ppy.sh นี่]",
    "store": "[https://osu.ppy.sh/store/listing ยินดีต้อนรับสู่ร้าน osu!] ซึ่งเป็นที่ที่คุณสามารถซื้อผลิตภัณฑ์ osu! ที่ดี",
    "submit": "[https://osu.ppy.sh/wiki/Submission คำถามที่พบบ่อยของระบบ Beatmap Submission]",
    "suck": "อย่ากังวลไปเลย เล่นเกมไม่เก่งก็สามารถฝึกฝนไปได้เรื่อยๆ มันก็เหมือนกับเล่นดนตรีแหละนะ :)",
    "supporter": "มาเป็น[https://osu.ppy.sh/p/support ผู้สนับสนุน]เกม osu! กันเถอะ! คุณจะได้สิ่งตอบแทนหลายอย่าง และช่วยสนับสนุนทีมผู้พั​ฒนาให้ทำเพิ่มขึ้น",
    "supporter-please": "โปรดอย่าถามคนอื่นให้ซื้อ supporter tag ให้\n[https://osu.ppy.sh/p/support คุณสามารถซื้อได้ที่นี่]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "[https://osu.ppy.sh/forum/t/87301 อ่านกระทู้นี้เมื่อคุณประสบปัญหาในการเล่นเกม osu! ด้วย Tablet หรือเมาส์ปากกา]",
    "tag": "ในโหมด Tag ของ Multiplayer ผู้เล่นทุกคนจะได้เล่นเกมแบบผลัดตาตามสีคอมโบโน็ตของ Beatmap ที่กำหนดไว้\nโหมดนี้จะไม่มีผู้แพ้ผู้ชนะ ทุกคนจะได้เล่นในทีมเดียวกัน และสปินเนอร์ ทุกคนจะได้มีส่วนร่วมเล่น\nหากผู้เล่นคนใดคนหนึ่งหมุนสปินเนอร์ไม่ผ่าน จำนวนคอมโบจะเริ่มนับใหม่ และคะแนนโบนัสสปินเนอร์ของทุกคนจะถูกนำไปรวมกับคะแนนทีม",
    "taiko": "กลองไทโกะคือกลองญี่ปุ่นและมีส่วนร่วมในซีรี่ย์เกม Taiko no Tetsujin โดยบริษัท Bandai-Namco ซึ่งโหมดไทโกะในเกม osu! จะเป็นการจำลองระบบเกม\nและให้เราตี (กด) ตามจังหวะที่วางเอาไว้ ให้ผู้เล่นได้โฟกัสในส่วนของ จังหวะ ของ Beatmap เพียงอย่างเดียว และฝึกฝนเรื่องการกดจังหวะให้แม่นยำและถูกต้อง\n[https://osu.ppy.sh/forum/t/4363 เล่นยังไงเหรอ อ่านสิ!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 วิธีทำ Beatmap สำหรับโหมดไทโกะ]",
    "taiko-maps": "คุณสามารถหา Beatmap ที่เหมือนเกม Taiko no Tetsujin ได้โดยเข้าไปที่ [https://osu.ppy.sh/forum/t/5397 กระทู้นี้]",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "ช่วยหยุดคุยเรื่องนี้ซักพักแล้วหันไปคุยเรื่องอื่นดีกว่าไหมครับ?",
    "training": "[https://osu.ppy.sh/forum/t/4280 James Training]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 ลองดูที่นี่สำหรับวีดีโอสอนเล่นและสอนการทำแมพ] หากคุณรู้ภาษาอังกฤษ มีฝีมือ และอยากทำไกด์แนะนำ ก็ลงมือได้เลย [https://osu.ppy.sh/forum/t/60228 ไม่แน่ ไกด์ของคุณอาจได้มาอยู่ในกระทู้นี้ก็เป็นได้]",
    "twc": "การแข่งขันทัวร์นาเม้นท์ osu! Taiko ระดับโลก [hhttps://new.ppy.sh/wiki/Tournaments/TWC/2017/ อ่านกระทู้นี้สำหรับรายละเอียดเพิ่มเติม]",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "กรุณาหลีกเลี่ยงการใช้ตัวอักษร unicode หรือตัวอักษรที่ไม่ใช่มาตรฐานในแชทรวม คุณอาจจะถูกใบ้",
    "upload-cap": "การจำกัด Beatmap ที่อัพโหลดเข้าไปในเกม ก็เพื่อให้ผู้ทำ Beatmap ทุ่มเทกับงาน Mapping ของตนให้ Beatmap ของเขาเล่นได้สนุก\nผู้ที่ไม่ได้เป็น Supporter จะสามารถอัพโหลด Beatmap ที่กำลังทำไปได้พร้อมกันสูงสุด 3-6 แมพ (Supporter ได้สูงสุด 5-10 แมพ) โดยจำนวนอัพโหลดสูงสุดจะขึ้นอยู่กับจำนวนแมพที่ได้ Ranked ของคุณ",
    "utf8": "กรุณาตั้ง Codepage โปรแกรมไคลเอนท์ IRC ของคุณให้เป็น UTF-8 เพื่อให้อักษรที่คุณพิมพ์สามารถอ่านเข้าใจได้กับผู้เล่นที่อยู่ในเกมและผู้ใช้ IRC คนอื่นๆ",
    "videogames": "ถ้าต้องการพูดคุยเกี่ยวกับเกมอื่นๆ ที่ไม่ใช่เกม osu! ให้เข้าไปยังห้อง #videogames",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "ยินดีต้อนรับสู่เกม osu! หากท่านมีปัญหาหรือข้อสงสัยใด ๆ โปรดเข้าไปถามใน #help ขอให้สนุกนะครับ :)",
    "when": "ก็เมื่อพร้อมนั่นแหละ",
    "wiki": "[https://osu.ppy.sh/wiki/ The osu! Wiki] - ทำให้มันเจ๋งเป้งไปเลย",
    "wiki-link": "คุณสามารถทำลิงก์โดยตรงไปที่ osu! wiki โดนการใส่หัวข้อหลักไว้ตรงกลาง [[ ]]\nเช่น [[Kudosu]] ทำได้โดยพิมพ์ Kudosu ไว้ตรงกลางระหว่าง [ 2 อัน และ ] 2 อัน\n",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 208 active FAQs (out of a possible 217) in the Thai (ภาษาไทย) language.",
    "completion": "The Thai (ภาษาไทย) FAQ as of last update is 95.85% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
