
strings = {
    "academy": "osu!academy'e gitmek için [http://www.youtube.com/user/osuacademy buraya tıklayın.] - Oyunun temelleri ile ilgili birçok bilgiyi burada bulabilirsiniz.",
    "achievements": "Başarıları şarkı içinde büyük bir kombo yapmak, bir tema paketinin içerdiği bütün beatmapleri oynamak gibi bazı özel şeyler yaparak elde edebilirsiniz. Sahip olduğunuz ve olmadığınız başarıları profilinizde görebilirsiniz. Başarı isimlerinden bazıları onu nasıl elde edeceğiniz hakkında ipucu verir!",
    "add-skin": "Yeni bir tema eklemek için dosyayı indirin ve osu! penceresine sürükleyin ya da dosyaya çift tıklayın.\n.rar/.zip dosyaları için, içindekileri bir klasöre çıkartın ve Skins klasörüne sürükleyin. Bunu osu! kapalıyken yaptığınızdan emin olun.",
    "advertising": "osu! ile alakası olmayan şeylerin reklamını yapmak yasaktır ve susturulmanıza sebep olabilir. Bu Discord, Teamspeak gibi her türlü üçüncü parti sohbet yazılımları için de geçerlidir.",
    "answer": "Sorunuza hiç kimseden cevap alamıyorsanız muhtemelen cevabı kimse bilmediği içindir. osu! ile alakalı bir konuysa forumda aramayı deneyin.",
    "appeal": "Eğer haksız yere susturulduğunuzu düşünüyorsanız accounts@ppy.sh adresine e-mail göndererek durumunuzu anlatın. Bunu yaparken yetkililerin de birer insan olduğunu aklınızdan çıkarmayın. Eğer durumunuzu uygun bir üslup ile anlatırsanız mümkün olduğu takdirde cezanızı temizlemek için ellerinden geleni yapacaklardır.",
    "approved": "Approved mapler bazı sebeplerden dolayı genel sıralamanıza etki etmez ancak yine de onu oynayabilir ve diğer oyuncularla yarışabilirsiniz. Approved maplerin ikonlarında kalp yerine ateş vardır.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire, osu! nun en yüksek seviyeli beatmap yarışması 2017'de Helblinde'den bir şarkıyla geri dönüyor.[http://osu.ppy.sh/news/156171674413 Buradan bakabilirsin!]",
    "ask": "Sorunuza cevap almanın en iyi yolu direkt olarak soruyu sormaktır. Bir şey sorabilir miyim? demenin pek de bir anlamı yok.",
    "attention": "Yazmayı bırakır mısın? Kimse senin söylediklerini dinlemiyor...",
    "avatar-change": "Avatarınızı [https://osu.ppy.sh/home/account/edit#avatar buradan] değiştirebilirsiniz.",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Selam! Ben BanchoBot! Tanıştığımıza memnun oldum! \nGerçi ben bir botum, bu yüzden sizinle bir insan gibi sohbet edemem :(",
    "beatmapping": "[https://osu.ppy.sh/wiki/Beatmapping Burada] beatmap yapmak ile ilgili işinize yarayacak bazı tavsiyeler bulabilirsiniz.",
    "beginner": "Yeni başlayanlar için ideal beatmaplere [https://osu.ppy.sh/forum/t/5456 buradan] ulaşabilirsiniz.",
    "bn": "[[Beatmap Nomination Group]], beatmapleri dereceli yapmak, beklemede olan beatmaplerin derecelendirme sırasına alınmasını sağlamak gibi işler ile ilgilenen takımdır. Mapping ve modding ile ilgili sorularınız varsa veya tavsiye istiyorsanız onlar ile konuşabilirsiniz.",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Diğer oyunculara sıkıldığınızı söylemenin bir anlamı yok. Oyuna ara verin ya da başka bir şeyler oynamayı deneyin.]",
    "bug": "Eğer oyun içinde bir hata -bug- bulduğunuzu düşünüyorsanız [https://osu.ppy.sh/forum/5 buradan] rapor edin. Tabii ki hatayı daha önce kimsenin paylaşmadığından emin olun.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Lütfen her kelimenin başında büyük harf kullanmayın. Yazdıklarınızın bir tren kazası gibi görünmesine sebep oluyor.",
    "caps": "Lütfen tamamen büyük harflerle yazmayın - chat içerisinde istenmeyen bir harekettir ve susturulmanıza sebep olabilir.",
    "change-modes": "Değişik oyun modlarında oynamak için şarkı seçme ekranına gidin, sol alttaki Mode/Mod tuşuna tıklayın ya da Ctrl tuşuna basılı tutarak 1 ila 4 arasında tercih yapın. Bazı beatmaplerin tek bir oyun moduna özel olduğunu aklınızdan çıkarmayın.",
    "change-name": "Kullanıcı adınızı değiştirmek için öncelikle [https://osu.ppy.sh/p/support osu! supporter] olmalısınız. Eğer supporter iseniz kullanıcı adınızı [https://store.ppy.sh/store/product/32 buradan] değiştirebilirsiniz. Eğer eski kullanıcı adınıza dönmek istiyorsanız, ufak değişiklikler yapmak istiyorsanız ya da başka bir konuda yardıma ihtiyacınız varsa lütfen accounts@ppy.sh adresine detaylar ile birlikte bir e-mail gönderin.",
    "changelog": "Oyun, Bancho ve internet sitesi ile ilgili bütün değişiklikleri [https://osu.ppy.sh/p/changelog burada] bulabilirsiniz.",
    "chars": "Lütfen sohbet içerisinde standart olmayan karakterleri (unicode) kullanmaktan kaçının.",
    "charts": "osu! charts, her ay yayınlanan, belirli bir temaya sahip paketlerdir. [https://osu.ppy.sh/p/chart Buradan ulaşabilirsiniz.]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Soluk Sarı: Normal kullanıcı | Sarı: [https://osu.ppy.sh/p/support Supporter] | Kırmızı: [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team NAT] veya [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] üyesi \nBeyaz: Kendiniz ya da /me mesajı | Lacivert: Özel mesaj | Yeşil: İsminizin geçtiği bir satır (highlight) | Pembe: BanchoBot",
    "colour": "Soluk Sarı: Normal kullanıcı | Sarı: [https://osu.ppy.sh/p/support Supporter] | Kırmızı: [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team NAT] veya [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] üyesi \nBeyaz: Kendiniz ya da /me mesajı | Lacivert: Özel mesaj | Yeşil: İsminizin geçtiği bir satır (highlight) | Pembe: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Sohbet komutları kullanışlı olsa da lütfen gereğinden fazla kullanmayın. Bu, spam olarak algılanır ve susturulma ile sonuçlabilir.",
    "comment": "Bir beatmapin tekrarına yorum yapmak istiyorsanız Discussion tuşuna tıklayın, bir şeyler yazın ve enter tuşuna tıklayın. Eğer ekranda yorumları göremiyorsanız Discussion panelindeki Show Comments kutusunu işaretleyin.",
    "comment-color": "Normal bir kullanıcı tekrarlara yorum yaparken sadece beyaz rengi kullanabilirken bir [https://osu.ppy.sh/p/support supporter] yorumunun rengini değiştirebilir.",
    "conferencemode": "IRC'de Join/Quit mesajlarının çok olması ile ilgili sorun mu yaşıyorsunuz? [http://wiki.xkcd.com/irc/Hide_join_part_messages Bu] size yardımcı olabilir.",
    "country-ranking": "Ülke sıralamasına [https://osu.ppy.sh/p/countryranking buradan] ulaşabilirsiniz.",
    "critic": "Lütfen eleştirilerin yapıcı olmasına özen gösterin. Sorunlarınızı çözüme kavuşturmak için alternatif yollar önerin.",
    "ctb": "Catch the Beat ile ilgili yardıma mı ihtiyacınız var? Wiki sayfasına [https://osu.ppy.sh/wiki/Catch_the_Beat buradan] ulaşabilirsiniz.",
    "cutting-edge": "Cutting-edge, osu!nun en yeni özelliklerini barındıran ve henüz yayınlanmayan sürümünden oluşan bir test sürümüdür. Ayarlar sekmesinden değiştirebilirsiniz. Eğer oyununuzu güncellerken sorun yaşıyorsanız [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues Bu makaleyi ouyun]",
    "cwc": "osu!nun dünya çapındaki Catch the Beat turnuvasıdır! Daha fazlası için [https://osu.ppy.sh/wiki/Tournaments/CWC/2019 buraya] tıklayın!",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Size nasıl davranılmasını istiyorsanız başkalarına da öyle davranın. Eğer bir çeşit mazoşistseniz, diğerlerinin öyle olmadığını farzedin.",
    "disable-this": "Toggle'lar nadiren özellik olarak eklenir. Yine de bir tanesinin eklenmesi için şurdan [https://osu.ppy.sh/forum/4 Özellik Talepleri yanforumunda] isteğinizi belirtebilirsiniz.",
    "distance-snap": "Distance Snap notaların zaman çizgisindeki yerleştirmesini kolaylaştırmak aracılığı ile geliştirilmiş bir sistemdir. Detaylar: [[Distance_Snap]]",
    "dont-ask-peppy": "Lütfen sürekli peppy'e sormayın - kendisi epey meşgul. Bu kanaldaki diğer kişilere sormaktan çekinmeyin tabii!",
    "douche": "Kurallarda bulunan açıkları kullanarak kuralları çiğnemek moderatör ekibinin yargısına göre cezalandırılabilir. Kurallar böyle aptallıklar yapmamanız gerektiğini söylemektedir, ancak tekrarlamaktan zarar gelmez: aptal biri olmayın.",
    "download": "Beatmapleri [https://osu.ppy.sh/p/beatmaplist buradan] ve beatmap paketlerini [https://osu.ppy.sh/beatmaps/packs buradan] indirebilirsiniz! Beatmaplerin oyuna nasıl aktarıldığını bilmiyorsanız [http://i.imgur.com/kpX2N3m.jpg buradan] öğrenebilirsiniz.",
    "drugs": "Lütfen osu!'nun hiçbir yerinde uyuşturucu hakkında konuşmayın.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "\nEditör modunda klavye kısayollarını [[Beatmapping#Keyboard_Shortcuts]] burada bulabilirsin.",
    "english": "#english özel bir kanal değildir ve her şey hakkında konuşulabilecek bir kanaldır. \nEvet, anime/manga buna dahildir. Trenler de.",
    "evade": "Susturulmaktan kaçmak hesabınızın uzun bir süreliğine kısıtlanmasına ve hatta banlanmasına neden olabilecek bir harekettir. Yapmayın.",
    "fallback": "Stabil (Fallback) osu!'nun eski bir sürümüdür. Fallback sürümünün aksine, yeni sürümlerde framework'ü basitleştirmek adına DirectX desteği kaldırılmıştır. Eğer bu sürüme geçtiyseniz, bilgisayarınız düşük segmenttir, güncel ve gelecek sürümleri desteklemeyecektir.\nŞayet güncel sürümde oynamak isterseniz, grafik kart(lar)ınızı güncelleyin ve bu sürümler için en gerekli tümleyici olan OpenGL'i destekleyecek hale getirin. [https://osu.ppy.sh/wiki/GL_Support_Issues Nasıl olduğunu öğrenmek için buraya tıklayın].",
    "faq": "Şu anda osu!Bancho SSS sistemini kullanıyorsunuz. osu!wiki: https://osu.ppy.sh/wiki",
    "feature": "Oyun için yeni bir fikriniz var ise [https://osu.ppy.sh/forum/4 Feature Requests] forumunda paylaşabilirsiniz.",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Sohbet filtrelerinden kaçınmak susturulmanıza neden olabilir - ve olacaktır da. Yapmayın.",
    "foul-play": "Hile yapanları profillerindeki [https://i.imgur.com/GG9xlLA.png şu] butonu kullanarak şikayet edin. \nLütfen olabildiğince detay sağlayın. Ayrıca top 50 skorlarını beatmap sayfasından şikayet edebilirsiniz.\nLütfen topluluk sohbetlerinde bu konu hakkında KONUŞMAYIN, susturulmanıza sebep olabilir.",
    "percolate": "Sohbet filtrelerinden kaçınmak susturulmanıza neden olabilir - ve olacaktır da. Yapmayın.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Bu makale] size mapping'te flow'u anlamanızda yardımcı olacaktır.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Bir kullanıcıyı arkadaş olarak eklemek için, /addfriend kullanıcı adı şeklinde yazın.\nAyrıca, Çevrimiçi Kullanıcılar (F9'a basın) listesinde kullanıcıya veya chat'te kullanıcının ismine tıklayıp Arkadaş Ekle butonundan ekleyebilirsiniz.\nKullanıcı profillerindeki Add Friend butonuna tıklayarak da arkadaş ekleyebilirsiniz.",
    "friends-list": "Oyun içerisindeki çevrimiçi arkadaşlarınızın listesini görmek için, F9'a basın ve en üstteki filtreyi Friends/Arkadaşlar'a çevirin.\nTüm arkadaşlarınızın bulunduğu bir liste de görebilirsiniz, hem çevrimiçi hem çevrimdışı, sadece web sayfasında Settings'e tıklamanız yeterli. (Giriş yapmış olmanız gerek, tabii.)",
    "fullscreen": "Oyunun tam ekran veya pencere olarak çalıştırılmasını Ayarlar'daki Grafik sekmesinden ayarlayabilirsiniz.\nTam ekran-Pencere arası geçişi Alt+Enter yaparak da sağlayabilirsiniz.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "[[glossary]]'de osu! ile ilgili bolca terminoloji bulabilirsin.",
    "gmt": "[https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team] yani kısaca [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] osu!'nun çalışmasına yardımcı olan kullanıcıları barındırır. Sohbet içerisinde kırmızı, forumlarda ise yeşil renkli isimleri vardır. Sohbetin ve forumun kullanım amacının dışına çıkmaması için uğraşırlar.",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Oku, öğren, neşelen.]",
    "grammar": "Mesajlaşırken dilbilginizin doğru olmasına özen gösterin. Bazı küçük hatalar göz ardı edilebilir, fakat SMS dili ve saçma sapan kısaltmalar kullanmanız sizi salak gibi gösterecektir.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Oynamayı bilmiyor musun? Mapping ve modding dünyasını keşfetmek mi istiyorsun? Cevaplarını [https://osu.ppy.sh/wiki/Guides buradan] alabilirsin.",
    "hacked": "Eğer hesabının başkası tarafından ele geçirildiğini düşünüyorsan lütfen accounts@ppy.sh adresine mail at. \nBunu yapmaman hesabının kapatılmasına yol açabilir.",
    "hard": "Oynamayı öğren de gel low.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "osu! hakkında yardıma ihtiyacın varsa #help kanalına katılıp sorununu belirtebilirsin. Ayrıca, #help kanalı çok dilli bir kanaldır.\nEğer kimse cevap vermiyorsa, [https://osu.ppy.sh/community/forums/5 Help] forumunda sorununa ilişkin bir gönderi hazırlayabilirsin.\nHesabınla ilgili sorunları da içeren faydalı makaleler için [http://help.ppy.sh/ bu sayfayı] da okuyabilirsin.",
    "hitsound-library": "[https://osu.ppy.sh/forum/p/164927 Buraya] tıklayarak beatmaplerinize özel hitsoundlar elde edebilirsiniz.",
    "hl": "Lütfen isminizde veya highlight kelimeleriniz arasında günlük kullanımda çok kullanılan kelimeler varsa diğer kullanıcıları highlight ile rahatsız edilmenizden dolayı suçlamayın. Ayarlar kısmından, gelen bildirimleri ve bildirim sesini eğer ihtiyacınız yoksa devre dışı bırakabilirsiniz.",
    "how-to-get-modded": "Beatmapinizin nasıl gözden geçirildiğini görmek için şuraya tıklayın: [[Getting_Your_Map_Modded]]\n",
    "how-to-bn": "Eğer bir BN olmak istiyorsanız, [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator şunu] okuyun.",
    "how-to-gmt": "Moderatörler, topluluğa ciddi anlamda katkıda bulunan kişilerden teker teker seçilmiştir. \nDaha fazla bilgi için wiki sayfasına göz atabilirsiniz: [https://osu.ppy.sh/wiki/People/The_Team/Global_Moderation_Team Global Moderation Team]",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F Oynamayı öğrenmek için buraya tıkla!]",
    "how-to-rank": "Cevabını [[How_to_Get_Your_Map_Ranked]]'da bulabilirsin.",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Kırmızı renginde parlayan meyveleri yakaladığında hyperdash meydana gelir. Bu, bir sonraki meyveyi daha çabuk yakalamanı sağlar. Sonraki meyveyi kaçırdıktan/yakaladıktan sonra etkisi kaybolur.",
    "ignore": "Bir kullanıcıyı engellemek için, /ignore + kullanıcı adı yazınız. \nEngellediğiniz kullanıcı tarafından yazılan satırları göremezsiniz, size gönderebilecekleri PM'ler de dahil.\n/unignore (kullanıcı adı) yazmak ya da osu!dan çıkmak, engeli kaldıracaktır.",
    "import": "[http://i.imgur.com/kpX2N3m.jpg Beatmap'lerin osu!'ya nasıl aktarıldığını öğrenmek için bunu okuyun!]",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Editörün F6 penceresinde inherit previous timing settings kutusunu işaretlerseniz, timing kısmı artık timing'i etkilemeyecektir. Bu, beatmapin sadece ses yüksekliği ya da sample'ı değişen kısımlar için kullanışlıdır. \nAyrıca, ikiye katlanmış ya da yarılanmış BPM'i olan kısmların timing'ini inherit'lemek mümkündür. Eğer böyle bir timing bölümünü kullanıyorsanız, lütfen inherit özelliğini kullanın!",
    "irc": "IRC server: irc.ppy.sh:6667\nŞifre: https://osu.ppy.sh/p/irc\nDaha fazla ayrıntı için https://osu.ppy.sh/wiki/IRC adresine gidebilirsiniz.",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Klavye ayarlarınızı ayarlardaki input kısmından değiştirebilirsiniz. osu!mania için bu ayarlar osu!mania layout tuşu altındadır.",
    "kiai": "Kiai modu bir stil efektidir. Zaman Ayarı Panel'inde (Timing Setup Panel) Kiai'yi seçtiğiniz zaman noktasında aktif edebilirsiniz. Kiai modu açık olduğunda beatmap biraz daha destansı gözükür.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Diğer insanların beatmaplerini modlayarak [https://osu.ppy.sh/wiki/Kudosu kudosu] kazanabilirsiniz.",
    "lag": "Lag [https://osu.ppy.sh/help/wiki/Performance_Troubleshooting herhangi bir şey] sonucunda ortaya çıkabilir - cihazınızdaki diğer işlemlerin bunda etkisinin olması ihtimali yüksek. Eğer sadece osu!'yu çalıştırdığınızda lag sorunu yaşadığınızdan eminseniz, sorununuzu detaylı bir şekilde [https://osu.ppy.sh/forum/5 Help] forumunda paylaşabilirsiniz.",
    "language": "Lütfen sohbetteki konuşmalarınıza dikkat ediniz. Uygun olmayan konuşmalar silence almanıza sebep olacaktır.",
    "language-specific": "Lütfen bulunduğunuz kanalın dilini kullanın.\nJaponca gibi Latin harfleri kullanmayan dillerdeki sözcükleri Latin harfleriyle yazmak bir istisna değildir.",
    "lazer": "osu!lazer, osu!'nun gelecek açık kaynak versiyonuna verilen kod adıdır. Detaylara [https://github.com/ppy/osu buradan] ulaşabilirsiniz!",
    "level": "Seviyeniz, total skorunuz temel alınarak hesaplanır. Bu, her çeşit ranked skorunuzu kapsar. İster başarılı ister başarısız olun. Seviyeniz osu! oynadıkça giderek artar.",
    "lines": "Yazacaklarınızı tek satırda yazmaya çalışın. Satır satır yazmanız susturulmanıza sebep olabilir.",
    "link": "Eğer mesajlarınızda linkleri yazı halinde göndermek istiyorsanız formatımız şudur: [link yazı], link yerine linkinizi yapıştırıp boşluk bırakıp yazınızı yazın. [https://osu.ppy.sh/ Bunun gibi!] Linkleri doğru yazdığınızdan emin olun ve başına http:// koymayı unutmayın.",
    "lobby": "Lütfen multiplayer reklamlarınızı #lobby kanalında yapın. Ayrıca #lobby, çok-dilli bir kanaldır. #lobby kanalı dışında oda reklamınızı yapmamanız önerilir.\nMultiplayer oynarken yazışmak için odanıza ait #multiplayer kanalını kullanın.",
    "localisation": "osu! yerelleştirme projesini [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 burada] bulabilirsiniz!",
    "long-link": "Lütfen sohbette çok uzun linkler paylaşmayın! Eğer gerekiyorsa [link metin] formülünü kullanın.",
    "long-text": "Lütfen çok uzun yazıları kopyala-yapıştır yapmayın. Yapmanız halinde susturulabilirsiniz.",
    "loved": "Sevilen kategorisi, ranked olamayacak beatmaplere bir skor tablosu kazandıran, topluluk-tabanlı yeni bir beatmap kategorisidir. Sevilen kategorisi hakkında daha fazla bilgiyi [https://osu.ppy.sh/wiki/Project_Loved burada] bulabilirsiniz.",
    "mac": "[https://osx.ppy.sh osu!'yu Mac'inizde kullanın]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Mapperlar meşgul insanlardır. Herhangi bir şarkının mapini yapmak çok fazla efor gerektirebilir. Neden kendin yapmıyorsun?",
    "mapping": "Mapping rehberleri için [https://osu.ppy.sh/forum/p/988111 buraya] gidebilirsin.",
    "mat": "Mapping Assistance Team, BAT'lerin ranking süreçlerine yardımcı olan eski kullanıcılardan oluşan bir gruptur. RIP MAT 2013-04-23",
    "modhelp": "Beatmap modding ile ilgili sorularınızı #mapping kanalında sorabilirsiniz!",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modding Queues]",
    "modreqs": "Lütfen modding istekleri için #modreqs kanalına gidiniz. BN'lerin her an için zamanı olmayabileceğini ve sizden önce mod isteğinde bulunanların öncelikli olduğunu aklınızda bulundurun. Beatmaplerinizi modlaması için sıradan kullanıcılara da istekte bulunabilirsiniz. Bir istekte bulunmak için /np komutunu ya da [link yazı] formatını kullandığınızdan emin olun, teşekkür etmeyi unutmayın!",
    "multi-invite": "Çok oyunculu modda oynarken odanıza birisini davet etmek istiyorsanız, Çevrimiçi Oyuncular listesinden (F9'a basın) istediğiniz kullanıcının üzerine tıklayın veya chatteki isimlerinin üzerine tıklayın ve Davet et seçeneğini seçin. \nAynı zamanda chat kısmına /invite <kişinin ismi> yazarak da oyuncuyu davet edebilirsiniz.",
    "multi-link": "[https://osu.ppy.sh/community/forums/topics/338482 Multi odasına giden davet linki nasıl oluşturulur]\n",
    "multiaccounting": "Gerçekten, ama gerçekten birden fazla hesap açmamalısınız. Bulunacak, ciddi bir süre susturulacak, hatta banlanacaksınız!",
    "multiplayer": "Lütfen çok oyunculu oyun odalarınızı #lobby kanalı dışında duyurmayın.",
    "mwc": "Dünya çapında osu! Mania turnuvası. Daha fazla bilgiye [https://osu.ppy.sh/wiki/Tournaments/MWC/2019_4K buradan] ulaşabilirsiniz.",
    "nat": "[https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] Beatmap Nominator'larını modere eder ve Beatmap Ranking sürecini izler. Beatmap vetoları ve mapping / modding ile ilgili konular ile ilgili tartışmaların arabulucuları olmaları yanı sıra, mevcut Beatmap Nominator'ların değerlendirilmesinden de sorumlular.",
    "news": "",
    "nightcore": "Favori beatmaplerinizi Nightcore stilinde oynamayı deneyin! \nDoubleTime'a çift tıklayıp Nightcore'a geçiş yapabilirsiniz. DoubleTime ile aynı skoru verir.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Ne dinlediğinizi duyurmak için sohbette /np yazın.",
    "nsfw": "Cinsel muhabbet yasaktır. osu! her yaştan kullanıcıyı barındırdığı için lütfen sohbeti mümkün olduğunca temiz tutmaya çalışın, yoksa uyarılmadan susturulursunuz.",
    "osu": "#osu kanalı osu! hakkında sohbet etmek içindir. Lütfen oyun hakkındaki muhabbetinizi orada sürdürün, bu kanalda değil.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 osu!tablet resmi konusu!] -Tablet ve erken sipariş seçenekleri için burdaki bilgilerin hepsini okuyun.",
    "osu!talk": "[https://osu.ppy.sh/wiki/osu!talk osu!talk] deatbeat ve ztrot'un ev sahipliği yaptığı, topluluktan kişilerin davet edilerek dünya kupaları gibi olayların tartışıldığı bir talk show etkinliğiydi.\nProgramı sunan kişilerin emekliliğe ayrılması sonucu, yerine osu! coffee hour devam etmiştir.",
    "osucore": "2011 yılından bir 1 Nisan şakası. Bütün maplerin default hızları DoubleTime hızına ayarlandı ve sesleri inceltildi. \nDaha sonra, o günkü DoubleTime'ın karşılığı olan Nightcore moduna dönüştürüldü.",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] - orjinal oyunun Android platformu için bir versiyonu.\nosu! geliştiricileri tarafından olumsuz yorumlar ve inaktiflik nedeniyle proje 2016'da askıya alınıp Goodle Play Store üzerinden de erişim kaldırılmıştır.",
    "osumania": "osu!mania sorunlarınız için #osumania kanalını kullanın.",
    "osustream": "[http://www.osustream.com osu!stream] - osu!'nun iOS cihazları için olan versiyonudur ve peppy tarafından yürütülmektedir!",
    "osz": "osu!'da oynamak için indirdiğiniz .osz uzantılı dosyalar daima osu! ile açılmalıdır. Aksi halde herhangi bir hatayla karşılaşabilirsiniz!",
    "osz2": "İçerisinde bulunan her türlü dosyanın birbirinden bağımsız bir şekilde şifrelenmesini, güncellenmesini ve aktarılmasını sağlayan yeni bir dosya formatı anlamına gelir. osz2 dosyaları çıkarılmaz ve her zaman sizin Songs klasörünüzde .osz2 dosyası biçiminde kalır.",
    "owc": "Dünya çapında osu! turnuvası. Detaylı bilgi için [https://osu.ppy.sh/wiki/OWC bu wiki sayfasını] ziyaret edin.",
    "peppy": "peppy, osu!'nun kurucusu ve baş geliştiricisidir. Projelerin çoğunu kendisi yürütüyor.",
    "perfect": "SS'i alamadınız mı? En ufak bir hata yaptığınızda, bu mod otomatik olarak mapi yeniden başlatır.\nBu modu, mod seçme ekranında SuddenDeath moduna sağ-tık ya da çift-tıklayarak bulabilirsiniz.",
    "ping": "Pong!",
    "pippi": "osu!nun maskot karakteri! \nPippi-don, Pippi'nin taiko (davul) versiyonudur.",
    "piracy": "Sohbet kanallarında telif hakkı olan dosyaların korsancılığı hakkında konuşmayın, yasadışıdır ve susturulmanıza neden olabilir.",
    "play-shortcuts": "Bütün kısayol tuşlarının listesi: [[Shortcut_Key_Reference]]",
    "pm": "Birisine özel mesaj göndermek için, chatte kullanıcının isminin üzerine veya Çevrimiçi Kullanıcılar ekranında kullanıcı panellerinin üzerine tıklayın ve Start Chat butonuna basın. \nAyrıca /msg <kullanıcı_adı> <mesaj> komutunu ya da /chat <kullanıcı_adı> komutunu ya da /query <kullanıcı_adı> komutunu kullanabilirsiniz. \nEn son gelen özel mesaja hızlı cevap verebilmek için, /r <mesaj> komutunu kullanabilirsiniz. < > sembollerini silin tabii ki.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance Points (pp) osu!'nun temel derecelendirme ölçütüdür. Detaylı bilgiyi [https://osu.ppy.sh/wiki/Performance_Points burada] bulabilirsiniz.",
    "pp-rework-lazer": "",
    "preview": "Preview point, şarkı seçim ekranında şarkının seçildiği zaman sizin duyduğunuz önizleme kısmıdır.\nİyi bir preview point şarkıyı iyi temsil eden bir kısımdan seçilmelidir, nakarat bölümü gibi. Editör > Timing kısmında Set Current Position as Preview Pointe basarak seçebilirsiniz.",
    "qat": "Quality Assurance Team, Qualified statüsüne geçen maplerin kalitesini ve oynanabilirliğini kontrol eder.\nBeatmap Ranking sisteminin ciddi anlamda büyümesi sonucu, Nisan 2019'da, halihazırdaki işlerini daha iyi yansıtmak için Nomination Assessment Team adını aldılar.",
    "qualified": "Beatmap Nominator'ları, ranking için yeterince kaliteli olan mapleri sıralaması olup pp kazandırmayan Qualified statüsüne yükseltirler.\nEğer bu maplerin herhangi bir kusuru yoksa ve 1 hafta boyunca Qualified kalmışlarsa, Ranked statüsüne geçerler. Aksi halde, Pending statüsüne geri çevrilir ve skorlar silinir. ",
    "ranked": "Ranked beatmapler, topluluk tarafından onaylanmış beatmaplerdir. \nRanked bir beatmap oynadığınızda, elde ettiğiniz skor sizin toplam ranked skorunuza eklenir. \nBu maplerin kendi özel sıralama tabloları vardır, ve Çift Ok işaretinden ranked olup olmadığını anlayabilirsiniz. ",
    "ranking-criteria": "Ranking kriterleri için şu wikiyi ziyaret edin: [[RC]]",
    "redname": "Kırmızı ismi bulunan kullanıcılar ya [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team] ya da [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] üyesidir.",
    "report": "Eğer birisinin uygunsuzca davrandığını veya hile yaptığını görürseniz, lütfen !report <kullanıcı> <sebep> komutunu kullanarak yetkililere bildirin, ancak PM içerisinde bunu yapmaktan kaçının.\nAynı zamanda kullanıcının ismine tıkladıktan sonra Kullanıcıyı Bildir seçeneğini seçerek kullanıcıyı bildirebilirsiniz.",
    "report-abuse": "Lütfen kullanıcı bildirme özelliğini arka arkaya kullanmaktan kaçının. Boş veya anlamsız bildiri göndermeniz de süreci hızlandırmayacaktır. Hatta böyle yaparak chat moderatörlerini spamladığınız için susturulabilirsiniz.",
    "request": "Modlayacak bir şeyler mi arıyorsun? [https://osu.ppy.sh/p/beatmaplist&r=8 Buraya] tıkla veya !request yazarak rastgele bir beatmap linki al.",
    "respect": "Lütfen diğer oyunculara saygı gösterin.",
    "roll-abuse": "Lütfen !roll komutunu kullanırken aşırıya kaçmayın. Susturulmanıza sebep olabilir.",
    "romaji": "Lütfen Romaji kullanırken aşırıya kaçmayın. Susturulmanıza sebep olabilir.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Multiplayer'da katılcak bir oda yoksa neden sen bir tane oluşturmuyorsun? Üstelik şarkıları da sen seçebilirsin!",
    "rp": "osu! chat kanallarında roleplay yapmakta diğer insanları rahatsız etmemek kaydıyla özgürsünüz!",
    "rules": "[https://osu.ppy.sh/wiki/tr/Rules Resmî kurallar]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "Zaman zaman, osu! DDoS saldırılarına maruz kalır. Bu süre içerisinde, Bancho kararsız veya erişilemez hale gelebilir. Eğer bunun olduğunu farkederseniz, daha fazla bilgi için [https://twitter.com/osustatus @osustatus]'u ya da [https://status.ppy.sh burayı] kontrol edin. Eğer bu gerçekleşir ve hala konuşabiliyorsanız - hiçbir şey olmamış gibi devam edin. Konusunu açmak sorunun çözüm aşamasını hızlandırmayacak.",
    "sb": "[[Storyboard Yapımı]]\nStoryboard Rehberi: https://osu.ppy.sh/forum/t/1869\nStoryboard Editörü nasıl kullanılır?: https://osu.ppy.sh/forum/t/8145\n",
    "scorev2": "scorev2 bütün oyun modlarında spinnerların ve ekstra modların getirdiği puanların 1 milyon puanda toplanmasıdır.\nAynı zamanda slider'ların davranışını da değiştirerek hitcircle'lar ile aynı timing'e sahip olmasını sağlar.",
    "scoring": "osu! skorları nasıl hesaplıyor: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Susturma (silence) demek, chatte konuşamamanız veya forumda post atamamanız anlamına gelir, Teknik Destek hariç. \nSilence süreleri ilk seferde 5 dakikadan başlar, daha sonra her silence yediğinizde süre ikiye katlanır. Bazı durumlarda sürenin ikiye katlanmasından fazlası gerçekleşebilir. \nSilence sadece yanlış hareketlerde kullanılır, sadece kurallara uyun ve bir probleminiz olmayacaktır.",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Temalar hakkında SSS]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY osu!'nun sizi sabah dörtlere kadar ayakta tutmasına izin vermeyin. Uykunuzu almanız sağlığınız için önemlidir!]",
    "songs-not-appearing": "Şarkınız şarkı seçiminde belirmiyorsa F5'e basmayı deneyin.",
    "spaces": "Lütfen her harfin arasında boşluk bırakmayın, bu şekilde yazmanız sohbeti dağınık gösteriyor ve susturulmanıza neden olabilir.",
    "spam": "Lütfen spam yapmayın. Sinir bozucudur ve genelde susturulmanıza neden olur.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Başka bir oyuncuyu izlemek için, /watch <kullanıcı_adı> komutunu yazın, ya da chatte veya kullanıcı panelinde isimlerinin üzerine tıklayın ve Start Spectating butonuna tıklayın. \nOynadıkları beatmaplerin sizde de olduğundan (ve oynadıklarından) emin olun!\n",
    "spoiler": "Animeler, mangalar, diziler vb. şeyler hakkında spoiler vermek yasaktır ve susturulmanıza sebep olabilir.",
    "status": "osu! sistem durumu için [http://twitter.com/osustatus @osustatus]'u kontrol edin. Server durumu hakkında bilgi için [https://status.ppy.sh buraya] göz atın.",
    "store": "[http://store.ppy.sh/ osu! mağzası] - mükemmel osu! ürünlerini satın alabileceğin yer!",
    "submit": "[https://osu.ppy.sh/wiki/Submission Beatmap Submission SSS]",
    "suck": "osu!'nun uzun bir kavrama süreci vardır - zamanla daha iyi olacaksın, sadece oynamaya devam et! ",
    "supporter": "Hemen bir [https://osu.ppy.sh/p/support osu! supporter] olun! Çeşitli ekstra özellikler kazanabilir ve oyun geliştiricilerinin daha iyi çalışmasına katkıda bulunabilirsiniz!",
    "supporter-please": "Lütfen başkalarından supporter dilenmeyin. Tam da [https://osu.ppy.sh/p/support şuradan] kendiniz için satın alabilirsiniz!",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Eğer imleciniz siz hareket ettirince sağa sola uçuyorsa fare hassaslığınızın 1.00x olduğundan emin olun. Eğer imleciniz hiç hareket etmiyorsa ayarlardan Raw Input'u kapatın. Sorununuzu çözemediyseniz [https://osu.ppy.sh/forum/t/87301 şu konuya göz atın.]",
    "tag": "Tag-Multiplayer modunda, tüm oyuncular sırayla mapteki bir comboya tıklar. Kazanan ya da kaybeden yoktur, herkes aynı takımda oynar. Spinner'larda, tüm oyuncular çevirir. Sadece bir oyuncu bile yapamazsa, combo sıfırlanır. Her oyuncunun spinner bonusu takımın skoruna eklenir.",
    "taiko": "Bandai-Namco'nun oyun serilerindeki Japon davulu, osu!'da Taiko Modu olarak simüle edilmiştir. Bu oyunlardaki ritim düzenini eleyip taklit ederek, oyuncuyu yalnızca beatmapin ritmine odaklanmaya zorlar.                                                                                                                                [https://osu.ppy.sh/forum/t/4363 İşte nasıl oynayacağın tam burada!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Taiko mapleme rehberi] (ingilizce)",
    "taiko-maps": "Otantik Taiko no Tatsujin maplerini [https://osu.ppy.sh/forum/t/5397 burada] bulabilirsiniz.",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Bu konuyu kapatıp başka bir şey hakkında konuşabilir misiniz lütfen?",
    "training": "[https://osu.ppy.sh/forum/t/4280 James Alıştırması]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 osu! oynayış ve beatmap oluşturma rehber videolarının güncel listesi.] Kendine bir tane yapmaktan ve paylaşmaktan çekinme. [https://osu.ppy.sh/forum/t/60228 Mapper/modder'lar için kullanışlı rehberler]",
    "twc": "Dünya çapında osu! Taiko turnuvası. Ayrıntılı bilgi için [https://osu.ppy.sh/wiki/Tournaments/TWC/2019 tıklayın].",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Lütfen unicode/standard-olmayan karakterleri kullanmaktan kaçının, yoksa susturulursunuz.",
    "upload-cap": "Map sahiplerinin kendi mapleri üzerinde yoğunlaşmaları için, yükleyebileceğiniz map sayısı için ufak bir limit vardır.\nSupporter olmayanlar 3-6 aktif mape sahip olabilir, supporter olanlar ise 5-10 aktif mape sahip olabilir, bu değer sahip olduğu ranked map sayısına göre değişebilir.",
    "utf8": "Diğer kullanıcıların yazdıklarını doğru bir şekilde okuyabilmek ve doğru mesajlar gönderebilmek için IRC clientinizin kodlamasını UTF-8'e çevirin.",
    "videogames": "Video oyun-içerikli konular (Touhou, Pokémon, SC, LoL gibi) #osu kanalında konuşulabilir, fakat eğer chati rahatsız ediyorsa veya birden fazla konu konuşuluyorsa, lütfen #videogames kanalına gidin.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "osu!'ya hoş geldiniz! Eğer cevaplanması gereken bir probleminiz varsa, #help kanalındaki nazik insanlara sorabilirsiniz! İyi eğlenceler! :D",
    "when": "Hazır olduğunda.",
    "wiki": "[https://osu.ppy.sh/wiki/ osu!wiki] - Onu mükemmelleştirmek senin elinde!\nGitHub üzerinden katkıda bulunabilirsiniz: [https://github.com/ppy/osu-wiki/ ppy/osu-wiki]",
    "wiki-link": "Wiki sayfalarını çift köşeli-parantezler arasına wiki başlığını yazarak link yapabilirsiniz: [[...]] şeklinde.                                                                   Örnek olarak, [[Kudosu]] [[ ve ]] arasına 'Kudosu' yazılarak yapılmıştır.",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 215 active FAQs (out of a possible 217) in the Turkish (Türkçe) language.",
    "completion": "The Turkish (Türkçe) FAQ as of last update is 99.08% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp zamanlayıcısı 60 saniyeye ayarlandı."
}
