
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy 點選此處] 瀏覽 osu! 學園，看影片學 osu!。",
    "achievements": "你可以透過在打歌的時候達成某項特定目標（像是得到很高的連擊數），或是把一個主題包的圖通通打遍來獲得成就。你的個人檔案（Profile）會顯示你已經獲得的成就，以及你還沒獲得的成就。有些成就會用名字來提示你怎麼獲得哦！",
    "add-skin": "如果想匯入 Skin，下載完後將該檔案拖曳到 osu! 的視窗，或是點擊兩下打開即可。",
    "advertising": "請勿宣傳與 osu! 無關的東西，屢犯者會被禁言。\n這包括Discord或是Teamspeak的宣傳。",
    "answer": "如果沒有人回答你，可能是沒人知道答案！可以試試看在論壇中搜尋（如果跟 osu! 有關）。",
    "appeal": "如果你被禁言後覺得這個處置不公平，向 accounts@ppy.sh 寄封私訊告知你的情況。不過記得，管理員也是人，也是會犯錯的！如果你待他們好一些，他們將更樂意盡力替你消除禁言。",
    "approved": "Approved 圖因為一些原因而無法被 Rank ── 不過它們還是有一定品質和可玩性，且同樣擁有排行榜和所有功能！你可以在選圖時看左上角的圖案來分辨圖的種類，Approved 圖會是火焰而非愛心。",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire，首屈一指的Osu!作圖比賽在2017年回歸，曲目來自Helblinde。 [http://osu.ppy.sh/news/156171674413 查看詳情]",
    "ask": "想問什麼就直接問吧，不用這麼客氣還問自己是否能問問題啦！",
    "attention": "別再說了，你離題了啦。",
    "avatar-change": "在遊戲畫面點自己，選取 2.Change Avatar，進入 [https://osu.ppy.sh/home/account/edit#avatar 這個畫面] 點擊 Browse 選取尺寸小於 128x128 、容量小於 88kb 的圖片上傳。",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "哈囉！我是 Banchobot！很高興認識你！不過我是個機器人，所以沒有辦法真的跟你交談啦。:(",
    "beatmapping": "請閱讀 [https://osu.ppy.sh/wiki/Beatmapping Beatmapping] 以取得更多關於作圖的相關提示。",
    "beginner": "在找新手圖嗎？來 [https://osu.ppy.sh/forum/t/13976 這裡] 看看 Alace 老師為新手們整理的圖譜清單！",
    "bn": "[[Beatmap Nomination Group]] 是一個負責譜面審核的團隊，負責檢視審核已完成的譜面並將質量合格者放入 Qualified 列表等待 Rank 。\n如果你有任何關於 Mapping 或者 Modding 的問題，都可以找他們談談哦！",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY 告訴別人你很無聊是有什麼意義啦。休息一下，不然就去玩別的遊戲！]",
    "bug": "如果你找到 Bug 了，那就來 [https://osu.ppy.sh/forum/5 這裡] 回報吧。只是要先確認前面沒人發過同樣的問題。",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "打英文的時候別讓每個單字的開頭都是大寫，這樣會讓別人覺得你怪怪的。",
    "caps": "打英文時請不要全部用大寫，這在聊天室裡不受歡迎，且是足以讓你被禁言的。",
    "change-modes": "要改變為其他遊戲模式的話，打開歌曲選單，並按左下角的 Mode 或是用 Ctrl+1,2,3,4 來選擇模式。不過記得有些圖是特定模式的喔！",
    "change-name": "要改名的話，你得先成為一位 [https://osu.ppy.sh/p/support osu! 贊助玩家] 。之後你就可以在 [https://store.ppy.sh/store/product/32 這裡] 改名囉！\n若是想要改回舊的名字、欲進行細微的更改或是有什麼問題，請寄 E-Mail 到 accounts@ppy.sh 詳細說明。",
    "changelog": "所有遊戲、Bancho 和網頁的更新都可以在 osu! [https://osu.ppy.sh/p/changelog 開發歷程] 中確認！",
    "chars": "請不要在聊天室中使用 Unicode 字元或非標準文字。",
    "charts": "osu! charts 是每個月發表的主題圖包。你可以在 [https://osu.ppy.sh/p/chart 這裡] 下載！",
    "chinese": "中文用戶請點擊 #chinese 以進入中文頻道進行交流。\n#osu 是英文專屬頻道，如果接獲此訊息後繼續在 #osu 內以中文交談，管理員有權利禁言。",
    "chinese-input": "全屏有些輸入法可能不能選字喲，試試 Alt+Enter 選用 borderless 或者使用新酷音輸入法。",
    "chinese-pinyin": "由於並非所有玩家都了解拼音或注音，因此請盡量避免使用注音符號跟拼音字母及其縮寫，有你的配合，中頻才能更舒服更健康。",
    "color": "淺黃：普通使用者｜黃色：[https://osu.ppy.sh/p/support 贊助玩家]｜紅色：[https://osu.ppy.sh/wiki/QAT NAT] 或是 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT（社群管理團隊成員）]｜白色：你自己，或是一行使用了 /me 指令的動作訊息｜深藍色：密語｜綠色：有人提到你的名字（或是 Highlight）｜粉紅色：IRC 萌萌機器人（Banchobot）",
    "colour": "淺黃：普通使用者｜黃色：[https://osu.ppy.sh/p/support 贊助玩家]｜紅色：[https://osu.ppy.sh/wiki/QAT NAT] 或是 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT（社群管理團隊成員）]｜白色：你自己，或是一行使用了 /me 指令的動作訊息｜深藍色：密語｜綠色：有人提到你的名字（或是 Highlight）｜粉紅色：IRC 萌萌機器人（Banchobot）",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "用指令真的很方便，可是不要玩指令哦！被當作洗頻還有可能被禁言呢。",
    "comment": "看重播時想留下評論的話，按下 Discussion 按鈕，寫點東西，然後按 Enter 就好！\n如果螢幕上沒有任何評論，那就在 Discussion 的面板中勾選 Show Comments 。",
    "comment-color": "普通使用者只能發白色的評論。如果是 [https://osu.ppy.sh/p/support 贊助玩家] 的話則可以選自己喜歡的顏色。",
    "conferencemode": "用 IRC 時被「加入」和「退出」訊息洗得不勝其擾？ [http://wiki.xkcd.com/irc/Hide_join_part_messages 這個] 應該可以幫到你！",
    "country-ranking": "來 [https://osu.ppy.sh/p/countryranking 這裡] 看看各國之間的排行榜吧！",
    "critic": "請發表有建設性的意見。為你看見的問題想一些替代方案或是解決方式吧！",
    "ctb": "對接水果有問題？來 [https://osu.ppy.sh/forum/p/60690 這裡] 看看！",
    "cutting-edge": "Cutting-edge 是一種取代 osu!test 的新的更新方式。\n若在更新時遇到問題， [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues 參考這篇文章] 。",
    "cwc": "那是指 osu! 世界接水果大賽！ [https://osu.ppy.sh/wiki/ZH:Catch_the_Beat_World_Cup_2015 詳細資訊請點我！]",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "己所不欲，勿施於人。就算你被言語羞辱會得到特殊的快感，其他人也不一定跟你一樣。",
    "disable-this": "功能開關是很少加進遊戲的。不過你還是可以到 [https://osu.ppy.sh/forum/4 Feature Requests 版] 來提出建議。",
    "distance-snap": "Distance Snap（間距控制）是能協助你以一定間距放物件的工具，至於距離長短則由時間軸的差距來決定。詳情請點 [[Distance_Snap]] 。",
    "dont-ask-peppy": "請別老求 peppy 回答你──他超忙的。別客氣，在這個頻道裡問問其他人吧！",
    "douche": "身為一個全能的 osu! 管理員，是有權利自行懲罰那些鑽規則漏洞的人的。因為有時官方的規則也不能涵蓋所有混蛋的不當所為。總之以防萬一：不作死就不會死。",
    "download": "你可以在 [https://osu.ppy.sh/p/beatmaplist 這裡] 下載更多圖，或是在 [https://osu.ppy.sh/beatmaps/packs 這裡] 下載圖譜包。",
    "drugs": "請不要在 osu! 聊天室中討論任何性質的藥物。有小孩在看的！",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "[[Beatmapping#Keyboard_Shortcuts]] 裡有編輯器的熱鍵列表。",
    "english": "#english 是給想討論但是找不到相關主題頻道的人使用的。是的，那邊也可以討論動漫！",
    "evade": "鑽漏洞避免禁言同樣是會被 Ban 的。Ban（封鎖）比禁言來得更嚴重多了！",
    "fallback": "正式版（Fallback）是過時的Osu!版本。為了簡化我們的框架，新版的客戶端移除了DirectX的支持（Fallback版仍然保留）。如果你被自動切換到這個版本，這說明你的電腦太低端並不支持當前和未來的版本。\n如果你要使用當前版本，請升級你的顯卡使其支持OpenGL。 OpenGL是這些新版本最需要的組件。 [https://osu.ppy.sh/wiki/GL_Support_Issues 了解更多]",
    "faq": "[https://osu.ppy.sh/forum/t/10737 我是新手教學，請輕輕的點我。] [https://osu.ppy.sh/forum/t/109978 中文區精華/資料索引] 由微風娘娘親手整理的索引，看過一遍還是不懂的話再發問吧。",
    "feature": "對遊戲有什麼點子，可以把它貼到 [https://osu.ppy.sh/forum/4 Feature Requests 版] 。",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "鑽漏洞來罵髒話同樣是會被禁言的，請不要這麼做。",
    "foul-play": "請使用個人檔案的[https://i.imgur.com/GG9xlLA.png 檢舉按鈕]檢舉使用外掛的玩家。最好提供詳細資料喔。你也可以到圖譜頁面的前50名列表檢舉外掛玩家。",
    "percolate": "鑽漏洞來罵髒話同樣是會被禁言的，請不要這麼做。",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 這篇文章] 會幫助你理解作圖中的 Flow 概念。",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "要把人加進好友名單，就打 /addfriend <對方ID> 。\n另外，你也可以在線上玩家列表（按 F9 打開）中點擊其玩家框，或是在聊天室裡點擊其 ID 並選擇 Add as Friend。\n你也可以在他們的個人檔案（Profile）裡面點擊 Add as Friend 來加好友。",
    "friends-list": "要看你的好友現在誰在線上，按 F9 然後把畫面上方的過濾改為「只顯示朋友」。\n你也可以在官方網站的 Settings 中確認完整的朋友名單（不過當然你得先登入）。",
    "fullscreen": "你可以在主選單的 Options 當中的「畫面」設定把遊戲調整為視窗模式或是全螢幕模式。\n你也可以按鍵盤上的 Alt+Enter 來調整。注意：OpenGL 模式並不支援全螢幕。",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "[[ZH:glossary]] 頁面包含了不少 osu! 術語！",
    "gmt": "[https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team（社群管理團隊）] ，或簡稱為 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] ，是一群協助 osu! 運作的人。他們在聊天室中有紅色名字，在論壇上則有綠色名字。這些人幫忙管理論壇和聊天室。",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 學而時習之，不亦樂乎。]",
    "grammar": "請盡量使用正確的文法。稍微有些拼字或標點符號的錯誤是可以接受的，但請不要用非通用縮寫或是 [http://en.wikipedia.org/wiki/SMS_language Textspeak] 。那會讓你看起來很蠢。",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "不知道怎麼玩？想更了解作圖和 Modding 的世界？一切答案都在 [https://osu.ppy.sh/wiki/Guides 這裡] 。",
    "hacked": "如果你認為你的帳號被盜了，請馬上 E-Mail 到 accounts@ppy.sh。\n若不如此可能會造成帳號被刪除。",
    "hard": "多加練習是提高水平的必要條件之一。",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "如果你需要任何關於 osu! 的幫助，請至 #help 頻道提出你的問題。#help 不限制使用任何語言，但通常使用英文詢問會更容易獲得解答。",
    "hitsound-library": "來 [https://osu.ppy.sh/forum/p/164927 這裡] 為你的圖抓一些打擊音效。",
    "hl": "如果你的 Highlight 列表裡有常用單詞，請別怪人家不小心 Hightlight 到你。\n如果真的有需要，可以在選項中關閉提醒音效。",
    "how-to-get-modded": "如果你想知道要怎麼讓你的圖被 Mod，點擊這裡：[[Getting_Your_Map_Modded]]。",
    "how-to-bn": "如果你想當 BN，來讀讀[https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator 這個]。",
    "how-to-gmt": "社群管理團隊成員是從高度貢獻者中人工選出的。想要幫忙我們嗎？多利用 !report 在你常看的頻道裡檢舉違規吧！",
    "how-to-play": "[https://osu.ppy.sh/wiki/ZH:FAQ#.E6.88.91.E8.A6.81.E6.80.8E.E4.B9.88.E7.8E.A9.E8.BF.99.E6.B8.B8.E6.88.8F.E5.95.8A.EF.BC.9F 點擊這裡來學怎麼玩！]",
    "how-to-rank": "想知道的話，請讀這個 [[How_to_Get_Your_Map_Ranked]] 。",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "當你接到一顆發著紅光的水果，就會進入 Hyperdash（超級衝刺）狀態。在之後的一段期間內你會衝的比平時快，直到接到或是 Miss 掉下一顆水果為止。",
    "ignore": "想忽略一個玩家，輸入 /ignore <對方ID> 即可。\n你將不會接收到已忽略使用者的發言及密語。\n輸入 /unignore <對方ID> 或是關閉 osu! 即可解除忽略。",
    "import": "看看 [http://i.imgur.com/kpX2N3m.jpg 這個] 來瞭解該怎麼替 osu! 匯入圖譜！",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "在編輯器中按下 F6 並勾選 Inherit previous timing settings，則選取的 Timing 區段就再也不會對 Timing 設定造成影響，在只想改變音量或是打擊音效時很有用。\n另外，將 BPM 調整為雙倍或是減半時，亦可使用這個設定。如果你有 Timing 區段是這樣的話，就請勾選該選項吧！",
    "irc": "IRC 伺服器：irc.ppy.sh:6667\n密碼請見：https://osu.ppy.sh/p/irc\n更多資訊請見：https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "你可以在“輸入”部分更改鍵盤快捷鍵，在“osu!mania鍵位排列”按鈕中調整osu!mania的按鍵和佈局。",
    "kiai": "Kiai 模式是你可以在 Timing Setup 面板中套用於 Timing 區段上的特殊效果。啟用了 Kiai 模式的 Timing 區段會有能讓圖譜看起來更加「史詩」的視覺效果。",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Mod 其他人的圖就可以獲得 [https://osu.ppy.sh/wiki/Kudosu kudosu] 。",
    "lag": "延遲的原因有非常多種，最有可能的就是你電腦中正在運行的其他程式。如果你確信肇因是 osu! 並且只有 osu! 有延遲情況，請在論壇中的 [https://osu.ppy.sh/forum/5 Help 版] 發文，內容需包含問題細節，以及其他任何有可能幫助我們確認問題原因的資訊。",
    "language": "在聊天室中請與他人以禮相待。不適當的發言可能會讓你被禁言。",
    "language-specific": "在頻道中請使用適合該頻道的語言。使用拉丁化的表達方式（如日文羅馬拼音、漢語拼音及注音）也不行。",
    "lazer": "",
    "level": "你的等級是由你的總分數計算而來的。這包含了任何 Ranked 圖的分數，無論有沒有通過都會計入。只要你多玩就會升級囉！",
    "lines": "可以打成一行的字，就不要打一整個畫面洗頻，謝謝。:)",
    "link": "要把文字連結到一個網址，請使用這個格式：[網址 文字]，\n「網址」處自然就填入你想要連結到的網址，而「文字」處則是你想要顯示的說明文字。\n[https://osu.ppy.sh/ 就像這樣！] 別忘了 http:// 哦。",
    "lobby": "#lobby 是用來宣傳多人遊戲相關事項的頻道，#multiplayer 頻道則用來談論房間遊戲內容，如果要用中文聊非多人遊戲話題的話請使用 #chinese <-（請點擊進入），還有 #lobby 頻道在語言上並無限制。",
    "localisation": "[https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 點我查看 osu! 在地化計劃]",
    "long-link": "請不要在聊天室裡發很長的連結！如果真的有需要，請使用 [連結 文字] 格式來發。",
    "long-text": "請不要在聊天室中發很長的文字，這麼做可能會讓你被禁言。",
    "loved": "Loved是一個基於社區的新的譜面狀態，它讓一些無法正常 Rank 的譜面也能擁有完整的排行榜。 [https://osu.ppy.sh/news/151925254083 了解更多]",
    "mac": "[https://osx.ppy.sh 如何讓 osu! 在 Mac 上跑？]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "作圖者（Mapper）都是大忙人，而作圖則是大工程。何不試試自己作作看？",
    "mapping": "來 [https://osu.ppy.sh/forum/p/988111 這裡] 看看作圖指南。",
    "mat": "Mapping Assistance Team （製圖協助團隊）是以前負責幫忙 BAT 們進行 Rank 工作的團隊。現已停止使用，並完全併入圖譜審核團隊。\n安息吧，MAT 13.04.23 ",
    "modhelp": "若對作圖上有什麼疑難雜症，請至 #mapping 頻道！",
    "modqueue": "[https://osu.ppy.sh/forum/60 Modding Queues （Modding 請求版）]",
    "modreqs": "請至 #modreqs 頻道提出 Mod 請求。請注意 BN 們並非總是有空，他們也有其他人先請求 Mod 了，所以你也可以找其他使用者來 Mod 你的圖。謝謝配合！",
    "multi-invite": "想邀請人加入你的多人遊戲，於線上使用者列表（按 F9 打開）中點擊其用戶框，或是在聊天室中點擊他們的名字，然後選擇「邀至房間」即可。\n你也可以在聊天室中輸入 /invite <對方ID> 。",
    "multi-link": "",
    "multiaccounting": "你真的不應該註冊多個帳號！法網恢恢，你是躲不過的。你會被長期禁言，甚至被 Ban！",
    "multiplayer": "請不要在 #lobby 以外的頻道宣傳多人遊戲。",
    "mwc": "一個國際性的 osu! Mania 比賽。 請到 [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 維基] 瞭解詳細資訊。",
    "nat": "[https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] 管理BN並監督Beatmap Ranked流程。他們負責評估目前的BN与有志成為BN的候選人，以及調解Beatmap veto和其他map/修改相關的爭議。",
    "news": "",
    "nightcore": "享受一下你最愛的圖的 Nightcore 版本吧！只要在 Mod 選單中按兩次 DoubleTime 就可以啟用 Nightcore 囉！這個 Mod 在計分上和 DoubleTime 相同。",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "輸入 /np 就可以讓人家看到你正在聽或玩什麼圖！",
    "nsfw": "色情討論是不被允許的。osu! 是全年齡層向遊戲，所以請讓聊天室保持純潔，否則你可能會馬上被禁言。",
    "osu": "#osu 頻道是專門討論 osu! 話題的頻道，不過那裡只能用英文喔！",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 osu! 繪圖版討論串！] 這其中包含了所有關於該繪圖版以及訂購的資訊。",
    "osu!talk": "osu!talk 是由 deadbeat 和 ztrot 主持的談話節目，兩人會訪問 osu! 社群的成員並討論像是世界賽之類的活動。\n每一集都會在 Teamspeak 3 的伺服器 osu.corin.me 上進行；若想發問問題，可以參與 Q&A 環節。[https://osu.ppy.sh/forum/t/225111 更多訊息請參考這裡]。",
    "osucore": "2011 年的愚人節彩蛋。所有圖都預設開著 DoubleTime 並且調高音調。\n在不久之後這就成為了 Nightcore 模式，和當時的 DoubleTime 效果一模一樣。",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] 曾經是 osu! 的安卓版本，但該項目早已被廢棄，也已經於2016年因差評從 Google Play 商店下架。",
    "osumania": "請使用 #osumania 頻道來討論關於 osu!mania 模式的話題。",
    "osustream": "[http://www.osustream.com osu!stream]是 iOS 版的 osu!，由我們的 peppy 製作和維護！",
    "osz": "這是指你下載的圖譜的格式。osz 檔需由 osu! 來進行解壓縮，否則可能會發生問題！",
    "osz2": "是一種新的圖譜格式，可以讓其中任何一個檔案獨立加密、上傳和播放等。osz2 檔案不需要解壓縮，會一直在 Songs 資料夾下以 osz2 格式儲存。",
    "owc": "世界 osu! 大賽之一。\n[https://osu.ppy.sh/wiki/OWC 看看這個了解更多！]",
    "peppy": "peppy 乃是 osu! 的創建者，大部份工作都是他自己來處理的。",
    "perfect": "拿不到 SS？這個 Mod 會在你沒有打出 300 時自動重新開始。\n你可以在 Mod 選單中右鍵點擊 SuddenDeath 以啟用它。",
    "ping": "Pong!",
    "pippi": "她是 osu! 的吉祥物。\nPippi-don 是她在太鼓模式中的形象。",
    "piracy": "請不要在聊天室中公開討論盜版。",
    "play-shortcuts": "[https://osu.ppy.sh/forum/t/32022 osu! 快捷鍵一覽表]",
    "pm": "要私密其他人，在聊天室中點擊對方的 ID ，或是在線上玩家列表點擊對方的用戶框，然後點擊 Start Chat 即可。\n你也可以在聊天室中輸入 /msg <對方ID> 或是 /chat <對方ID> 來直接密語，或用 /query <對方ID> 打開一個新標籤。\n要回覆上一件密語，你可以輸入 /r <訊息> 。當然，要把 < > 去除掉。",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance Points（pp）是 osu! 新的排名方式！按[https://osu.ppy.sh/wiki/Performance_Points 這裡]查看更多資訊。",
    "pp-rework-lazer": "",
    "preview": "Preview Point（預覽段落）可以圖譜中設定，在歌曲選單中就會從該處開始播放歌曲。\n好的預覽段落應該能夠表現出歌曲好的部份，例如副歌的起點。在編輯器中工具列的 Timing 選單點擊 Set Current Position as Preview Point 即可設定預覽段落。",
    "qat": "QAT負責檢查最近qualified map的質量和可玩性。在2019年4月ranked system改版後，他們更名為NAT以更好的反映他們目前的工作領域。",
    "qualified": "這是 modding 系統的前進方向！Qualified 狀態代表這個圖差不多可以 Rank 了。在這些圖當中，你可以獲得排名，不過没有PP。這些圖會維持 Qualified 狀態一周，期間如果社會對圖有意見而 QAT 認為這些意見值得參考，圖就會打回重改，分數記錄也會抹去；相反圖在 Qualified 狀態保持一周的話就會被 Rank。",
    "ranked": "Ranked 圖是由線上社群成員核可的圖譜。\n在 Ranked 圖中獲得的分數會計入你的總分。\n這些圖有各自的排行榜，在歌曲選單左上角的圖示是愛心。",
    "ranking-criteria": "關於 Rank 標準的資訊，請看看 Wiki 條目：[[zh:RC]]",
    "redname": "有紅色名字的人乃是 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] 或是 [https://osu.ppy.sh/wiki/People/The_Team/Nomination_Assessment_Team NAT]。",
    "report": "管理員有時會不在，他們也是人，沒辦法全天守候。如果你發現有人在胡搞卻沒有管理員處理，請在該頻道輸入 !report <對方ID> <原因> 。\n請避免在 BanchoBot 的頻道中使用 !report 。",
    "report-abuse": "請避免連續檢舉，這不會讓處理來得更快。也不要做空白或是無意義的檢舉。\n你會因為洗聊天室管理員的頻而被禁言的。",
    "request": "在找圖 Mod 嗎？點擊[https://osu.ppy.sh/p/beatmaplist&r=8 這裡]或是輸入 !request 以取得一張隨機的圖譜。",
    "respect": "請尊重其他玩家，不要作出人身攻擊等令人困擾的行為。",
    "roll-abuse": "請不要過度使用 !roll 。你可能會被禁言。",
    "romaji": "請勿使用日文羅馬拼音。否則你可能會被禁言。",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "沒有多人遊戲房間的話，何不自己開一個？如此一來你還能自己選歌呢！",
    "rp": "你可以在適當的頻道中角色扮演，不過你得確定自己並沒有打擾到在同一頻道中的其他人。",
    "rules": "[https://osu.ppy.sh/wiki/zh/Rules 官方守则]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "osu! 偶爾可能會被 DDoS 攻擊。在這種時候，Bancho 可能會不穩定或無法連接。\n如果你懷疑有這種狀況，請在 Twitter 的 [https://twitter.com/osustatus @osustatus] 上或 [https://status.ppy.sh 這裡] 獲得更多資訊。\n如果真的發生了，而你仍然能夠使用聊天室，請繼續正常聊天。把這拿出來講並不會讓它走得更快。",
    "sb": "[https://osu.ppy.sh/forum/t/1869 Storyboard 製作教學]\n[https://osu.ppy.sh/forum/t/8145 如何使用 Storyboard 編輯器]",
    "scorev2": "Scorev2是一種新的得分算法，在該算法下所有遊戲模式的最大得分為100萬（轉盤和Mods除外）。\n它也會更改滑條的工作方式，使其和打擊圈有相同的時間準確度要求。",
    "scoring": "想知道 osu! 是怎麼計分的？：[[Score#scoring]] 。",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "禁言代表你不能在聊天室發言或是在論壇上貼文，不過 Help（技術支援）版塊不在此限。\n首次禁言會是 5 分鐘，之後每次都會翻倍。不過重大違規的處罰會比前一次禁言時間的兩倍來得長上許多。\n禁言只會對輕微犯規者執行，所以只要遵守規則你就不會怎樣了。",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 皮膚製作 FAQ]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY 別玩 osu! 玩到凌晨四點都還沒睡！充足睡眠是很重要的！]",
    "songs-not-appearing": "如果你的歌曲沒有出現在歌曲選單，試著按下 F5 。",
    "spaces": "請勿在每個字中間加入空格，這會讓頻道看起來很混亂。",
    "spam": "請勿洗頻，否則我們將適當剝奪你的發言權利。謝謝。:)",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "要觀察其他玩家，在聊天室中輸入 /watch <對方ID> ，或是在聊天室中點擊其 ID 或點擊其用戶框，然後點擊「開始觀察」即可。\n請確定你有他們正在玩的圖（然後他們真的有在玩！）。",
    "spoiler": "不要公開討論動漫 / 同人劇情，違規時可能被禁言 / 封號。",
    "status": "關於 osu! 系統狀態資訊，請查看 [http://twitter.com/osustatus @osustatus]。即時伺服器狀態則請參考[https://status.ppy.sh 這裡]。",
    "store": "[http://store.ppy.sh/ 歡迎來逛逛 osu! 商店] ，這裡可以買到超讚的 osu! 周邊商品和其他好東西！",
    "submit": "[https://osu.ppy.sh/wiki/Submission 圖譜上傳 FAQ]",
    "suck": "熟練 osu! 的過程是很漫長的，時間一過你自然就會變觸，所以繼續努力吧！",
    "supporter": "成為一位 [https://osu.ppy.sh/p/support 贊助玩家] 吧！你會獲得許多好處，也可以幫助開發團隊做更多事情！",
    "supporter-please": "請勿在公眾頻道尋求能送你 supporter 的人，[https://osu.ppy.sh/p/support 需要的請自己買吧！ ]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "如果你用繪圖版玩 osu! 時遇上什麼問題，[https://osu.ppy.sh/forum/t/87301 請讀我]。",
    "tag": "在 Tag 模式多人遊戲中，所有玩家輪流依 Combo（即圈圈顏色）順序上陣。因為所有人都在同一個隊伍，所以不分輸贏。\n轉盤則是每個玩家都參與。就算只有一個玩家沒有轉過，連擊數也會歸零。每個玩家的轉盤額外加分都會計入隊伍分數中。",
    "taiko": "太鼓是在日本 Bandai-Namco 所製作的一系列遊戲中登場的一種鼓。osu! 的「太鼓模式」仿製了這些遊戲，不考慮物件的擺放，讓玩家只需專注於圖中的節奏。\n[https://osu.ppy.sh/forum/t/4363 看看怎麼玩！]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 太鼓製圖教學]",
    "taiko-maps": "你可以在 [https://osu.ppy.sh/forum/t/5397 這裡] 找到太鼓達人的圖。",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "先別說這個了，你有聽過安麗嗎？",
    "training": "[https://osu.ppy.sh/forum/t/4280 James 的新手訓練]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 最新的 osu! 遊玩及製圖教學影片列表。] 如果你自己拍了一部，別客氣儘管貼來這裡。[https://osu.ppy.sh/forum/t/60228 好用的製圖者 / Modder 教學]",
    "twc": "世界 osu! 太鼓大賽。\n[https://new.ppy.sh/wiki/Tournaments/TWC/2017/ 看這篇文瞭解更多。]",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "請不要在聊天室中使用 Unicode 字元或非標準文字。",
    "upload-cap": "為了讓製圖者專心做自己手上的圖，你同時可以上傳的圖是有數量限制的。\n一般玩家可以同時上傳 3 至 6 張圖，贊助玩家則可以有 5 至 10 張圖，依其 Rank 圖的數量而定。",
    "utf8": "請把你的 IRC 軟體設定成 UTF-8 編碼好讓你可以正常閱讀其他使用者的 / 傳送給其他使用者訊息。",
    "videogames": "電玩遊戲相關的主題是可以出現在 #osu 頻道的，不過如果它們干擾到其他人聊天的話，請移駕至 #videogames 頻道。",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "歡迎來到 osu!！如果你有任何問題，請儘管在 #help 頻道提出！祝你玩得愉快！",
    "when": "時機一到就有了啦。",
    "wiki": "[https://osu.ppy.sh/wiki/ osu! Wiki]，歡迎一起編輯！",
    "wiki-link": "你可以在聊天室中使用雙引號的格式，產生 Wiki 條目的快速連結。\n例如，[[Kudosu]] 就是把 Kudosu 放在兩個 [ 跟兩個 ] 中間輸入而成的。",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 213 active FAQs (out of a possible 217) in the Traditional Chinese (中文(繁體)) language.",
    "completion": "The Traditional Chinese (中文(繁體)) FAQ as of last update is 98.16% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
