
strings = {

    "academy": "[https://www.youtube.com/user/osuacademy osu!academy]  - Більшість навчальних відео по osu! (англійською)",
    "achievements": "Досягнення даються за деякі дії під час гри, наприклад, досягнення великого комбо або проходження певних паків мап.\nСписок досягнень можна побачити у себе в профілі. Увага: обговорювати досягнення категорії Hush-Hush заборонено.",
    "add-skin": "Щоб додати новий скін, завантажте його і двічі клацніть по завантаженому файлу, або перетягніть у вікно osu!.",
    "advertising": "Будь ласка, не рекламуйте в чаті речі, не пов'язані з osu!, інакше вам можуть дати сайленс.",
    "answer": "Якщо реакції на питання немає, напевно, ніхто не знає відповідь, або не хоче в сотий раз повторювати очевидні речі. Використайте пошук по форуму.",
    "appeal": "Щоб поскаржитися, на Вашу думку, на незаслужений сайленс або бан, докладно напишіть англійською на accounts@ppy.sh, намагайтесь не спотворювати факти.",
    "approved": "Аппрув - мапа підвищеної складності, або з тривалістю більше 5 хвилин, що не потрапила з цієї причини під стандартні обмеження на ранк.\nРаніше аппруви потрапляли в окрему категорію і мали в клієнті іконку полум'я, але, починаючи з кінця лютого 2014 року, їх об'єднали з ранкнутими мапами.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire, головний конкурс маппингу osu!, повернувся у 2017 з піснею з Helblinde. [http://osu.ppy.sh/news/156171674413 Перевірте це тут!]",
    "ask": "Просто задайте питання, а не питайте, чи можна запитати.",
    "attention": "Будь ласка, припиніть, не треба писати нікому нецікаву маячню.",
    "avatar-change": "Аватарку можна змінити [https://osu.ppy.sh/home/account/edit#avatar тут].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Привіт, я БанчоБот! Радий знайомству. На жаль, оскільки я бот, у нас не вийде побалакати відверто. У вільний час я допомагаю команді osu! або байдикую.",
    "beatmapping": "Вся інформація про те, як зробити мапу, знаходиться [https://osu.ppy.sh/wiki/Beatmapping тут!]",
    "beginner": "До цього часу новачки грали [https://osu.ppy.sh/community/forums/topics/5456 ці мапи], але зараз підійде будь-яка мапа зі складністю Easy.",
    "bn": "[Https://osu.ppy.sh/wiki/RU:BNG Beatmap Nomination Group] - група, що відповідає за просування і номінацію мап на ранк. Ви можете попрохати пораду або допомогу у номінаторів у маппінгу або моддінгу.",
    "bored": "Якщо вам нудно, займіться чимось іншим, в інтернеті багато цікавого. Нудьга - не привід писати в канал всяку нісенітницю.",
    "bug": "Повідомляйте про знайдені баги не в чат, а [https://osu.ppy.sh/community/forums/5 на форум], перевіривши, що до Вас цього ніхто не зробив.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "Писати Кожне Слово З великої букви чи ПаРкАнЧиК - неправильно і некласно. Надайте нам послугу, витягніть Shift і CapsLock з клавіатури.",
    "caps": "Не пишіть все капсом, це небажано. Надлишок капсу може призвести до сайленсу.",
    "change-modes": "Щоб змінити режим гри, перейдіть до вікна вибору мап, потім клацніть на кнопку Mode в нижньому лівому кутку або використовуйте комбінації клавіш Ctrl + 1-4. Врахуйте, що деякі мапи зроблені лише для певних режимів.",
    "change-name": "Щоб змінити свій нік, потрібно зайти [https://store.ppy.sh/store/product/32 сюди] і оплатити зміну. Якщо Ви хочете скасувати або внести невеличкі зміни, напишіть на accounts@ppy.sh з подробицями на англійському.",
    "changelog": "Всі оновлення гри, серверної частини і сайту описані [https://osu.ppy.sh/p/changelog тут].",
    "chars": "Будь ласка, не зловживайте спецсимволами, це може бути розцінено як спам.",
    "charts": "Чарт - вибірка мап, що випускається кожен місяць, або відповідна під єдину тематику, і має свій топ.\nСписок чартів можна переглянути [https://osu.ppy.sh/p/chart тут].",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Блідо-жовтий: звичайний користувач | Жовтий: [https://osu.ppy.sh/p/support саппорт] | Червоний: [https://osu.ppy.sh/wiki/QAT QAT] або [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] | Білий: Ви самі | Синій: особисте повідомлення | Зелений: в рядку міститься Ваше ім'я | Рожевий: Банчобот",
    "colour": "Блідо-жовтий: звичайний користувач | Жовтий: [https://osu.ppy.sh/p/support саппорт] | Червоний: [https://osu.ppy.sh/wiki/QAT QAT] або [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] | Білий: Ви самі | Синій: особисте повідомлення | Зелений: в рядку міститься Ваше ім'я | Рожевий: Банчобот",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Будь ласка, не зловживайте командами чату. Це вважається спамом і може привести до сайленсу.",
    "comment": "Реплеї можна коментувати, натиснувши при перегляді на кнопку Discussion з правого боку.\nЩоб відобразити коментарі, натисніть Show Comments на панелі обговорення. Обережно, деякі мапи мають ДУЖЕ багато коментарів.",
    "comment-color": "У звичайних користувачів коментарі можуть бути тільки білого кольору, у [https://osu.ppy.sh/p/support саппортерів] - будь-якого.",
    "conferencemode": "Про те, як прибрати повідомлення про вхід/вихід на канал в IRC, читайте [http://wiki.xkcd.com/irc/Hide_join_part_messages тут].",
    "country-ranking": "[Https://osu.ppy.sh/p/countryranking Топ країн]",
    "critic": "Будь ласка, критикуйте конструктивно. Сварити людину та її роботу погано тільки тому, що Вам не подобається, - грубо, некрасиво і може призвести до сайленсу.",
    "ctb": "Коротка довідка з режиму [https://osu.ppy.sh/wiki/Catch_the_Beat Catch The Beat].",
    "cutting-edge": "Експериментальна версія оновлень - новий спосіб користуватися тестовим клієнтом osu!. Детальніше можна прочитати [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues тут] (на англ. мові).",
    "cwc": "CWC - світовий турнір між гравцями Catch the Beat. Інформація про турнір знаходиться [https://osu.ppy.sh/wiki/Catch_the_Beat_World_Cup_2015 тут].",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\r\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\r\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Не набридайте іншим людям, не постіть купу посилань, не спамте інвайтами і не робіть речі подібні до цих.",
    "disable-this": "Ні, це не можна вимкнути, але Ви можете попрохати цього [https://osu.ppy.sh/community/forums/4 тут].",
    "distance-snap": "Інструмент для фіксації відстані між об'єктами, робота якого заснована на відстані між нотами в музиці. Детальніше: [[Distance_Snap]].",
    "dont-ask-peppy": "НЕ переслідуйте peppy, у нього і так багато роботи. Запитайте краще у кого-небудь іншого.",
    "douche": "Використання лазівок в правилах карається на розсуд модерації.\nЩоб добре себе вести, Вам не потрібно офіційне правило, що вимагає, щоб Ви добре себе поводили. Але все ж, будь ласка, поводьтеся добре.",
    "download": "Мапи завантажувати [https://osu.ppy.sh/p/beatmaplist тут], а паки - [https://osu.ppy.sh/beatmaps/packs тут]",
    "drugs": "Розмови про наркотичні речовини у нас заборонені.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Список хоткеїв, які використовуються в редакторі: [[Beatmapping#Keyboard_Shortcuts]]",
    "english": "Щоб спілкуватися англійською на теми, для яких немає окремих каналів, Ви повинні зайти в #english.",
    "evade": "Спроби ухилення від cайленсу призводять або до САЙЛЕНСУ, або до бану.",
    "fallback": "Стабільна (запасна) версія - це застаріла версія osu!.\nУ нових релізах була прибрана підтримка DirectX для спрощення нашого фреймворка.\nЯкщо Вас переключили на цю збірку, Ваш комп'ютер застарів і не підтримує можливості нових релізів osu!\nЯкщо Ви хочете грати на поточних збірках зараз, поновіть Вашу графічну карту з можливістю використання OpenGL, так як це найважливіша деталь для цих версій.\n[Https://osu.ppy.sh/wiki/GL_Support_Issues натисніть тут щоб дізнатися як вирішити проблему].",
    "faq": "Ви використовуєте довідкову систему osu!Bancho. Більш докладну довідку по osu! можна знайти у [https://osu.ppy.sh/wiki вікі].",
    "feature": "Щоб попрохати нововведення, напишіть у [https://osu.ppy.sh/community/forums/4 відповідний форум].",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Будь ласка, не намагайтеся обходити фільтри чату, це карається.",
    "foul-play": "Будь ласка, репортуйте чітера, використовуючи кнопку репорт в профілі, розташовану [https://i.imgur.com/GG9xlLA.png тут]\nПереконайтеся, що Ви надаєте стільки інформації, скільки можливо. Також Ви можете зарепортити гравця на сторінці з рекордами мапи.",
    "percolate": "Будь ласка, не намагайтеся обходити фільтри чату, це карається.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[Https://osu.ppy.sh/news/61334266941 Ця стаття] допоможе вам зрозуміти, що таке флоу в маппинзі і як його використовувати.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Щоб додати друга, потрібно написати /addfriend <ім'я_друга>. Також можна натиснути F9, знайти користувача за ім'ям і додати, клацнувши на панель з його ім'ям.\nЩоб додати друга через сайт, потрібно відкрити його профіль і натиснути по посиланню Add as Friend.",
    "friends-list": "Щоб подивитися список друзів, які онлайн, натисніть F9 і виберіть зверху фільтр «Друзі».\nПовний список можна побачити [https://osu.ppy.sh/home/friends тут].",
    "fullscreen": "Переключитися з повноекранного режиму у вікно можна, натиснувши Alt + Enter або пошукавши в налаштуваннях. Ця опція відключена для OpenGL.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Заглянувши в [https://osu.ppy.sh/wiki/Glossary словничок], можна знайти розшифровку деяких термінів.",
    "gmt": "[Https://osu.ppy.sh/wiki/GMT Global Moderation Team], або коротко GMT - група глобальних модераторів. Відрізняються від інших користувачів кольором ім'я - він червоний в чаті, а на форумі - зелений.",
    "english-help": "Щоб підвищити своє знання англійської на десяток відсотків, прочитайте [https://osu.ppy.sh/forum/t/12016 цю тему].",
    "grammar": "Намагайтеся не допускати граматичних помилок, а то іншим може набриднути розбиратися у Вашій неграмотності.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Ви просите гайдів? Вони в мене є! [https://osu.ppy.sh/wiki/Guides Ось список], правда, вони всі чомусь англійською.",
    "hacked": "Якщо Ви впевнені, що Вас хакнули, напишіть на accounts@ppy.sh. В іншому випадку, Вас можуть забанити за дії іншої людини.",
    "hard": "Стань сильніше, нікчема.",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Якщо вам раптово потрібна допомога, а тут ніхто чомусь не допоміг, запитайте допомоги у #help (англійською) або напишіть у [https://osu.ppy.sh/forum/t/9668 спеціальну тему] на форумі.",
    "hitsound-library": "Нестандартні хітсаунди для своєї мапи можна роздобути [https://osu.ppy.sh/forum/p/164927 тут.]",
    "hl": "Досить говорити про те, що Вас хайлайтнуло, якщо в списку Ваших Хайлайт є поширене слово або фраза.",
    "how-to-get-modded": "Про те, як отримати моди на мапу, можна дізнатися тут: [[Getting_Your_Map_Modded]]",
    "how-to-bn": "Якщо Ви хочете стати BN (Beatmap Nominator), прочитайте [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator це].",
    "how-to-gmt": "Якщо Ви хочете стати модератором, скоріш за все, Ви їм не будете. Іншими словами: не шукайте нас, ми самі Вас знайдемо.",
    "how-to-play": "[[FAQ]] - osu! для новачків. Більш докладна і детальна [https://osu.ppy.sh/wiki/FAQ#how-to-play довідка].",
    "how-to-rank": "Про те, як ранкнути свою мапу, можна прочитати в статті [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Гіпердеш змушує ловця фруктів світитися червоним. Під час гіпердеша Ваш персонаж рухається набагато швидше, ніж зі звичайним дешем. Гіпердеш відключається після наступного фрукта (навіть якщо Ви його пропустите).",
    "ignore": "Щоб додати когось в ігнор-лист, напишіть /ignore <ім'я_користувача>. Для скасування - /unignore <ім'я_користувача>.\nЦе - тимчасовий список, який оновлюється при виході з гри, а постійний можна знайти в налаштуваннях osu!.",
    "import": "Подивіться [http://i.imgur.com/kpX2N3m.jpg сюди], щоб дізнатися, як імпортувати карти в osu!.",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Позначивши прапорець Inherit previous timing settings у вікні редактора F6, проміжки більше не будуть впливати на час, що корисно для проміжків, у яких змінюється лише гучність або вигляд мапи. Також це дозволяє успадкувати проміжки, у яких BPM збільшений або зменшений удвічі. Якщо ви зіткнулися саме з таким проміжком, будь ласка, успадкуйте його!",
    "irc": "Сервер IRC: irc.ppy.sh:6667\nПароль: https://osu.ppy.sh/p/irc\nДетальніше: https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Ви можете змінити бінди своєї клавіатури в розділі Клавіатура.\nКлавіші та розкладка в osu!Mania змінюється натисканням на кнопку Розкладка osu!Mania.",
    "kiai": "Кіай - візуальний ефект, який Ви можете додати до своєї мапи в налаштуваннях таймінгу. Розділ з кіаєм включає різні ефекти, що робить мапу більш епічною. Використовуйте його з розумом.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "[[Kudosu]] - те, що заробляється за моддінг карт інших мапперов ([[Modding]]).",
    "lag": "Якщо у Вас щось підлагує, спочатку з'ясуйте, що саме і за яких умов. Спробуйте написати про це до [https://osu.ppy.sh/community/forums/5 саппорту].\nТакож перед тим, як писати про лаги, спробуйте закрити непотрібні програми і переконатися, що ніщо більше не навантажує процесор і пам'ять.",
    "language": "Будьте ввічливі і намагайтеся утримуватися від образ.",
    "language-specific": "Будь ласка, спілкуйтеся мовою каналу, який відвідуєте. Романізовані слова або фрази не є винятками неримсьских мов, так як японська.",
    "lazer": "",
    "level": "Рівень у цій грі вже нічого не означає, крім міри кількості зіграних мап, тому краще орієнтуватися на [[PP]].",
    "lines": "Намагайтеся вміщати свої думки у меншу кількість рядків, щоб не отримати сайленс.",
    "link": "Для створення посилання використовуйте цей шаблон: [посилання текст] (адреса і текст розділяються пробілом). На початку посилання повинен бути протокол http:// або https://.\n[Https://osu.ppy.sh Ось так!] Врахуйте, що використання посилань не за призначенням карається.",
    "lobby": "Будь ласка, використовуйте #lobby тільки для реклами ігрових кімнат, для всіх інших розмов під час гри використовуйте канал #multiplayer.",
    "localisation": "Не влаштовує переклад гри? Знайшли друкарську помилку? Ви можете допомогти [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 тут].",
    "long-link": "Будь ласка, не постіть у чат довгі посилання. Для цього існує конструкція [посилання текст].",
    "long-text": "Будь ласка, не копіюйте об'ємні шматки тексту у чат, це може привести до їх зникнення (простіше кажучи, Ви отримаєте сайленс).",
    "loved": "Loved - базується на смаках спільноти категорії мап, яка дає анранкнутим мапам скорборд.\n[Https://osu.ppy.sh/news/151925254083 Детальніше про це можеш дізнатися тут!]",
    "mac": "[https://osx.ppy.sh Запуск osu! на Mac]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Замаппати пісню самому - найкращий варіант, тому що у інших, як правило, немає ні часу, ні бажання.",
    "mapping": "Всілякого роду інформацію щодо маппингу можна знайти [https://osu.ppy.sh/forum/t/440360 тут] і на вікі: https://osu.ppy.sh/wiki",
    "mat": "MAT - Mapping Assistance Team, група користувачів, які допомагали Батам з ранкінгом мап. Покинула нас 23 квітня, 2013.",
    "modhelp": "Якщо є питання щодо маппінгу, а у #russian ніхто нічого не говорить, запитаєте англійською у #mapping.",
    "modqueue": "[https://osu.ppy.sh/community/forums/60 Список черг для отримання модів]",
    "modreqs": "Усі прохання про моддінг мап повинні направлятися англійською у #modreqs або на форум у розділ Work In Progress → Modding Queues. Але попрохати щодо плейтесту можна і тут.",
    "multi-invite": "Щоб запросити когось у свою гру у мульті, знайдіть ім'я користувача у списку (F9) або у чаті, клацніть по ньому і виберіть пункт Запросити в мульті.",
    "multi-link": "",
    "multiaccounting": "Створення мультіаккаунтів є порушенням правил і карається.",
    "multiplayer": "Будь ласка, рекламуйте ігрові кімнати та кличте до мультіплеєру тільки у #lobby.\nПід час гри у мульті не треба спілкуватися тут, для цього є #multiplayer.",
    "mwc": "MWC - турнір між гравцями у osu!Mania. Подробиці можна дізнатися на вікі: [[Osu! Mania_7K_World_Cup_2016 ]].",
    "nat": "",
    "news": "",
    "nightcore": "Подобається найткор? Тепер його можна застосувати до будь-якої пісні; досить зайти у меню модів і два рази натиснути на DoubleTime.",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Щоб написати у чат, яку пісню Ви зараз слухаєте або граєте, введіть /np.",
    "nsfw": "Тут не можна постити еротику, порнографію і вміст з позначкою 18+, так само як і розмовляти на подібні теми.",
    "osu": "Для розмов про osu! у нас є канал #osu. Будь ласка, обговорюйте геймплей не тут, а там.",
    "osu!tablet": "Дізнатися про планшет з логотипом osu! можна [https://osu.ppy.sh/forum/t/169139 тут], а замовити - [https://osu.ppy.sh/p/tablet тут].",
    "osu!talk": "osu!talk - серія подкастів, яку випускають ztrot і deadbeat\nЗміст: інтерв'ю з іншими гравцями і адміністрацією, обговорення ігрових подій (напр., [[OWC]])\nПодробиці: https://osu.ppy.sh/forum/t/225111",
    "osucore": "osu!core - привіт з далекого 2011 року, коли на перше квітня всі карти за замовчуванням гралися з ДТ і звучали як найткор. Пізніше цей ефект повернувся у вигляді повноцінного мода з таким же ефектом, до якого були додані техно-хітсаунди.",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] це порт оригінальної гри на платформі Android. Офіційні розробники відмовилися від гри та у 2016 році вона була знята з магазину Google Play через неактивність користувачів та погані відгуки.",
    "osumania": "У каналі #osumania можна отримати більш детальну інформацію про все, що відноситься до osu!mania.",
    "osustream": "[Http://www.osustream.com osu!Stream] - osu! для iOS. Це окрема гра, але схожість видно відразу.",
    "osz": ".osz - формат, у якому зберігаються мапи на сайті. Гра сама розпаковує ці файли при відкритті, але якщо щось раптом піде не так, то можна спробувати зробити це вручну будь-яким архіватором.",
    "osz2": "Новий формат мап, файли у якому будуть зберігатися зашифрованими і оновлюватися незалежно один від одного.\nЇх також не знадобиться розпаковувати - мапи у форматі .osz2 завжди будуть зберігатися у папці з піснями у вигляді одного файлу.",
    "owc": "OWC - турнір між гравцями osu! з усього світу, який проводиться раз на рік.\nПосилання: [http://www.twitch.tv/osulive трансляція матчів], детальна [https://osu.ppy.sh/forum/t/160181 інформація про турнір], російська стаття [https: //osu.ppy .sh/wiki/OWC на вікі], [https://osu.ppy.sh/forum/t/369906 тема на форумі].",
    "peppy": "pеppy - провідний розробник osu!, який зробив, і до сих пір, робить багато речей самотужки.",
    "perfect": "НЕ можете взяти SS? Цей мод автоматично перезапускає карту, якщо Ви помиляєтеся. Щоб увімкнути його, досить зайти у меню модів і натиснути два рази на мод SuddenDeath.",
    "ping": "Pong!",
    "pippi": "Піппі - маскот osu!, а Піппі-дон - її версія для тайко.",
    "piracy": "Обговорення або поширення ламаних програм краще винести за межі цього каналу.",
    "play-shortcuts": "Список хоткеїв: [[Shortcut_Key_Reference]]",
    "pm": "Щоб комусь написати повідомлення, введіть /msg <ім'я_користувача> або /chat <ім'я_користувача>.\nДля швидкої відповіді на останнє отримане повідомлення можна написати /r <відповідь>. Звичайно без < >.",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance Points (pp) - те, у чому вимірюється ранк гравця в osu! Детальніше: [[PP]].",
    "pp-rework-lazer": "",
    "preview": "Прев'ю - це момент, з якого починає грати пісня при її виборі у списку. Щоб встановити його у своїй мапі, у редакторі у верхньому меню Timing виберіть пункт Set Current Position as Preview Point.",
    "qat": "",
    "qualified": "Номінатори номінують мапи, після цього вони позначаються як qualified\nНа цих мапах Ви можете отримати ранк, але без PP. Якщо ці мапи не мають\nпроблем і вони протримаються у qualified режимі тиждень, вони будуть ранкнуті.\nВ іншому випадку вони повернуться у режим pending і всі результати на них будуть видалені.",
    "ranked": "Ранкнутими називають мапи, схвалені модерацією. На таких мапах Ви можете заробляти ранк і накопичувати загальну кількість балів.\nВсі ранкнуті мапи мають свій список рекордів і іконку з сердечком у верхньому лівому кутку у меню вибору пісні.",
    "ranking-criteria": "Поточні критерії ранкінга можуть бути знайдені у статті [[RC]].",
    "redname": "Користувачі з червоними ніками - це або [[GMT]], або [[QAT]]",
    "report": "Щоб повідомити про неадекватну поведінку або нечесну гру, використовуйте наступну форму: !report <ім'я_користувача> <причина_репорту>. Репорти не відображаються в інших користувачів. Репорти повинні бути зроблені у публічних каналах. Також ви можете це зробити натиснувши на ім'я порушника та вибравши Поскаржитися.",
    "report-abuse": "Будь ласка, не треба репортити одне і те ж багато разів, це не допоможе, як і порожні або безпричинні репорти.\nБільш того, вам можуть видати сайленс за зловживання системою репортів.",
    "request": "Якщо нема чим зайнятися, виберіть мапу [https://osu.ppy.sh/p/beatmaplist&r=8 звідси] або напишіть !request, щоб отримати випадкову мапу для моддінгу.",
    "respect": "Будь ласка, поважайте інших гравців.",
    "roll-abuse": "Будь ласка, не кидайте кубик занадто часто, інакше Ви можете отримати сайленс за спам.",
    "romaji": "Будь ласка, не використовуйте Romaji (романізований японський) надмірно. Це може призвести до сайленсу.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Якщо у мультіплеєрі немає кімнат, у яких Ви хотіли б пограти, чому б Вам не спробувати створити свою?",
    "rp": "Можна відігравати чию завгодно роль, якщо це не заважає і не набридає іншим відвідувачам каналу.",
    "rules": "Правила чату знаходяться [https://osu.ppy.sh/forum/t/51989 тут]. Повна версія: https://osu.ppy.sh/wiki/ru/Rules",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "На жаль, іноді сервера osu! ДДОСять, тому у цей час Банчо може працювати нестабільно або взагалі не запускатись автоматично.\nЯкщо вам здається, що щось не так, перевірте [https://twitter.com/osustatus твіттер] або [https://status.ppy.sh статистику серверів].",
    "sb": "Сторібордінг робить Вашу карту ефектніше. Про те, як навчитися робити сторіборди, читайте тут: [[Storyboarding]].\nСтарі гайди: [https://osu.ppy.sh/forum/t/1869 основний], [https://osu.ppy.sh/forum/t/8145 про роботу у редакторі].",
    "scorev2": "scorev2 - це новий алгоритм підрахунку балів, який обмежує максимальну кількість балів у всіх режимах за мапу 1 мільйоном, не рахуючи спіннерів та модів.\nА ще scorev2 змінює те, як працюють слайдери, вони починають вимагати такої ж точності натискань, як і ноти.",
    "scoring": "Про підрахунок балів можна прочитати тут: [[Score]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Сайленс, або сало, означає, що отримавши його людина не може постити на форумі і у чаті. Довжина сайленсу починається з п'яти хвилин і зазвичай збільшується вдвічі кожен наступний раз; можливі і різкі скачки, у залежності від порушень. Щоб уникнути отримання сайленсу, намагайтеся не порушувати [https://osu.ppy.sh/wiki/Rules правила.]",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[Https://osu.ppy.sh/forum/t/51694 FAQ по скінам]",
    "sleep": "[Https://www.youtube.com/watch?v=y61v2QCHlpY Чим довше Ви не спите через osu!, тим сильніше Ви будете проклинати її, коли прокинетеся.]",
    "songs-not-appearing": "Якщо нові мапи не відображаються у списку пісень, натисніть F5 або перезапустіть osu!.",
    "spaces": "Будь ласка, не розміщуйте пробіли між кажною літерою, ваша естетика забруднює чат і може призвести до сайленсу.",
    "spam": "Будь ласка, не треба спамити у чат, інакше Ви можете на деякий час втратити дар мови.",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Щоб дивитися за іншим гравцем, введіть /watch <ім'я_користувача> або Клацніть на ім'я гравця і натисніть зелену кнопку.\nДля перегляду потрібно мати таку ж мапу, як і у людини, що грає, і щоб людина грала, а не байдикувала!",
    "spoiler": "Спойлери заборонені і можуть привести до сайленсу.",
    "status": "Для отримання новітньої інформації про стан серверів osu! стежте за [http://twitter.com/osustatus @osustatus] або загляньте [https://status.ppy.sh сюди].",
    "store": "Всякі дрібниці з логотипом osu! можна купити [http://store.ppy.sh/ тут].",
    "submit": "Для довідки по завантаженню мап прочитайте статтю [[Submission]]",
    "suck": "Не сумуйте, просто вам потрібно грати більше, щоб грати краще.",
    "supporter": "Про те, хто такі саппорти, можна прочитати [http://bit.ly/VM7rfe тут], а стати одним з них можна [https://osu.ppy.sh/p/support тут].",
    "supporter-please": "Будь ласка, не прохайте інших людей подарувати вам supporter tag.\n[Https://osu.ppy.sh/p/support Замість цього купуйте його тут!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Якщо у Вас виникли проблеми при використанні планшета, прочитайте [https://osu.ppy.sh/forum/p/2128519 цей пост (Windows 8)] або [https://osu.ppy.sh/forum/t/87301 цю тему.] Також можна вбити процес wisptis.exe, щоб планшет перестав глючити.\nВтім, спершу спробуйте виставити швидкість руху курсору у 1x і вимкнути режим безпосереднього введення.",
    "tag": "Граючи у мультіплеєрі у режимі Tag Co-Op, гравці по черзі натискають тільки на задані кола (від одного комбо до іншого).\nУ цьому режимі немає ні переможців, ні переможених, так як всі грають у одній команді.\nСпіннери обертають всі гравці. Якщо хтось не встигає заповнити шкалу спіннера, команда втрачає комбо.\nБонус кожного гравця, отриманий на спіннері, підсумовується із загальним результатом команди.",
    "taiko": "Тайко - японські барабани, що з'явилися у іграх Bandai-Namco. У режимі тайко гравцям слід концентруватися на ритмі мапи.\n[Https://osu.ppy.sh/forum/t/124083 Тут] можна почитати, як грати у тайко",
    "taiko-mapping": "[Https://osu.ppy.sh/forum/t/152263 Як замапати тайко]",
    "taiko-maps": "Аутентичні мапи Taiko no Tatsujin можна знайти [https://osu.ppy.sh/forum/t/5397 тут].",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Будь ласка, змініть тему розмови на що-небудь інше.",
    "training": "[https://osu.ppy.sh/forum/t/4280 James Training]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "Деякі навчальні відео можна знайти [https://osu.ppy.sh/forum/t/109137 тут], а більш повний список посібників знаходиться [https://osu.ppy.sh/wiki/Guides у вікі].",
    "twc": "TWC - світовий турнір між гравцями Тайко.\nПосилання: [http://www.twitch.tv/taikoworldcup трансляція матчів], [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ інформація про турнір].",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Будь ласка, не зловживайте спецсимволами, це може бути розцінено як спам.",
    "upload-cap": "Існує обмеження на кількість завантажених на сервер мап. Звичайні користувачі можуть завантажити від 3 до 6 мап, саппортери - від 5 до 10, у залежності від кількості ранкнутих раніше мап.",
    "utf8": "Будь ласка, налаштуйте Ваш IRC клієнт на систему кодування UTF-8, щоб Ви могли одночасно адекватно читати та надсилати розбірливі повідомлення іншим користувачам. ",
    "videogames": "Обговорення інших ігор у чаті не заборонено, але, будь ласка, не кличте людей грати у них.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Щоб швидше освоїтися в osu!, прочитай [https://osu.ppy.sh/wiki/Welcome цю статтю].",
    "when": "Коли буде готове.\r\n",
    "wiki": "Візьміть участь у заповненні [https://osu.ppy.sh/wiki вікі]!",
    "wiki-link": "Щоб вставити посилання на сторінку у вікі, напишіть її заголовок у подвійних квадратних дужках. Зразок: [[Kudosu]]",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 211 active FAQs (out of a possible 217) in the Ukrainian (Українська) language.",
    "completion": "The Ukrainian (Українська) FAQ as of last update is 97.24% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
