
strings = {
    "academy": "[https://www.youtube.com/user/osuacademy Dành cho những người mới bắt đầu chơi osu!]",
    "achievements": "Bạn sẽ nhận được những thành tựu bằng cách thể hiện những điều đặc biệt trong một bài hát, như đạt được combo cao hay chơi hết các beatmap trong một gói beatmap theo chủ đề riêng. Trang thông tin tài khoản của bạn sẽ lưu lại những thành tựu mà bạn đã đạt được cũng như những thành tựu mà bạn chưa hoàn thành. Tên của một số thành tựu cũng chính là gợi ý cách để bạn đạt được chúng.",
    "add-skin": "Nếu tập tin bạn đã tải về có đuôi là .osk, hãy kéo tập tin đó vào osu! hoặc đúp chuột hai lần tập tin đó. Đối với tập tin .rar/.zip, hãy giải nén nó vào một thư mục rồi chuyển nó vào thư mục Skin của bạn. Bạn nên thực hiện khi điều này khi osu! đang được tắt.",
    "advertising": "Không được phép quảng cáo nội dung không liên quan tới osu! \nBạn có thể bị chặn chat nếu vi phạm. Nó cũng bao gồm việc quảng bá link các nhóm chat khác như Discord và Teamspeak.",
    "answer": "Nếu không ai trả lời bạn thì, rất có thể đến cả họ không biết câu trả lời! Hãy thử tìm câu trả lời đó trên forums nếu nó liên quan tới osu!",
    "appeal": "Nếu bạn liên tục bị chặn chat và cho rằng nó không công bằng, hãy gửi email cho Admin qua địa chỉ: accounts@ppy.sh và trình bày tình hình của bạn. Hãy nhớ rằng, ban quản trị cũng là con người! Nếu bạn đối xử tốt với họ, có thể họ sẽ cố gắng hết sức để thu hồi lại quyết định, nếu có thể.",
    "approved": "Approved beatmap không thể được ranked vì một số lí do - thường thường là những map có độ dài từ 5 phút trở lên và chỉ với một độ khó, đôi khi từ 2-5, và có bảng điểm như ranked. Chúng không còn được lưu hành nữa. nhưng bạn sẽ biết nó là một Approved beatmap khi nó có biểu tượng là ngọn lửa thay vì là trái tim.",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "[[https://osu.ppy.sh/wiki/Contests#aspire Aspire]] là cuộc thi làm beatmap cấp cao được lưu hành vào năm 2016–2020.",
    "ask": "Cách tốt nhất để có được một câu trả lời là bạn nên hỏi thẳng câu hỏi đó. - Tôi có thể hỏi cái này được không? cũng đã là một câu hỏi rồi.",
    "attention": "Bạn có thể dừng lại được không? Thực sự mà nói thì không có ai đang nghe bạn nói hết cả...",
    "avatar-change": "Đổi avatar của bạn [https://osu.ppy.sh/home/account/edit#avatar ở đây].",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": "Xin chào! Tôi là BanchoBot! Hân hạnh được gặp bạn. À mà tôi là bot, nên tôi không thể trò chuyện với các bạn được :(.",
    "beatmapping": "Hãy tham khảo [https://osu.ppy.sh/wiki/Beatmapping Beatmapping!] để biết thêm những thông tin hữu ích đối với việc mapping. ",
    "beginner": "Nhấp vào [https://osu.ppy.sh/forum/t/5456 đây] nếu bạn đang tìm kiếm những beatmap dành cho tân thủ. Bạn có thể tìm thêm về các gói beatmap dành cho người chơi màn hình cảm ứng tại [https://osu.ppy.sh/community/forums/topics/75291 đây].",
    "bn": "[[Beatmap Nomination Group]] (hay Nhóm Đề Cử Beatmap, gọi tắt là BN) là nhóm những người quản lý việc rank beatmap và có trách nhiệm đối với việc đưa những beatmap ở trạng thái pending vào trạng thái rank.\nBạn có thể nói chuyện với họ nếu bạn có bất kỳ câu hỏi gì hay cần lời khuyên gì về mapping hay modding. Họ thường là những người rất bận rộn, nên xin bạn vui lòng né việc spam họ!",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY Không có lí do gì để bạn bảo với người khác rằng bạn đang chán cả. Hãy nghỉ ngơ hoặc chơi một game nào khác!] Nhàm chán không phải là một cái cớ để spam đâu nhé.",
    "bug": "Báo lỗi osu tại [https://osu.ppy.sh/forum/5 đây]. Hãy đảm bảo rằng không ai khác đã đăng nó trước đó trước khi bạn đăng về vấn đề đó.",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "\nĐừng viết hoa những chữ cái đầu của tất cả các từ, câu nói của bạn - nó sẽ chẳng khác gì một đoàn tàu trật ray cả.",
    "caps": "Xin đừng viết hoa tất cả các chữ cái - việc đấy thật sự rất là không cần thiết, và bạn có thể bị chặn chat đấy!",
    "change-modes": "Để thay đổi sang chế độ game khác, đến màn hình chọn nhạc và click vào Mode ở dưới bên trái hoặc Ctrl + 1-4. Đừng quên rằng có một vài beatmap có chế độ chơi riêng biệt!",
    "change-name": "Để thay đổi tên người sử dụng của bạn, trước hết bạn phải cần trở thành [https://osu.ppy.sh/p/support osu! supporter!] trước. Sau đó, bạn hãy truy cập vào [https://store.ppy.sh/store/product/32 đây] để đổi tên!\nĐể yêu cầu chuyển về tên cũ, thực hiện những thay đổi nhỏ hay cần sự giúp đỡ, bạn hãy gửi e-mail về accounts@ppy.sh với những chi tiết mà bạn cần yêu cầu.",
    "changelog": "Xem những thay đổi và cập nhật của Osu! (bao gồm cả Lazer), wiki, trang web và Bancho tại [https://osu.ppy.sh/p/changelog đây]",
    "chars": "Xin hãy hạn chế sử dụng dấu và kí tự đặc biệt (các ký tự có dấu trong bảng chữ cái Việt Nam) trên kênh chat chung như #osu.",
    "charts": "osu! charts là các gói theo chủ đề và được phát hành hàng tháng. Cập nhật osu! charts [https://osu.ppy.sh/p/chart tại đây]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "Vàng nhạt: Người chơi binh thường | Vàng: [https://osu.ppy.sh/p/support osu! Supporter] | Đỏ: [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team NAT] hoặc [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] | Trắng: Bạn hoặc một tin nhắn /me | Xanh dương: tin nhắn riêng | Xanh lá: Đoạn chat được nhắc đến tên của bạn (một highlight) | Hồng: BanchoBot",
    "colour": "Vàng nhạt: Người chơi binh thường | Vàng: [https://osu.ppy.sh/p/support osu! Supporter] | Đỏ: [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team NAT] hoặc [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] | Trắng: Bạn hoặc một tin nhắn /me | Xanh dương: tin nhắn riêng | Xanh lá: Đoạn chat được nhắc đến tên của bạn (một highlight) | Hồng: BanchoBot",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "Các lệnh chat có thể được sử dụng rất dễ dàng, nhưng đừng lạm dụng nó. Việc này được coi là spam, và bạn có thể bị cấm chat.",
    "comment": "Nếu bạn muốn bình luận của mình xuất hiện trên replay của một beatmap, nhấn Discussion, hãy để lại nhận xét và nhấn enter. Nếu không nhìn thấy comment nào thì hãy tích ô Show Comments trong bảng Discussion.",
    "comment-color": "Người chơi thường chỉ có thể hiển thị dòng nhận xét bằng màu trắng. Còn [https://osu.ppy.sh/p/support osu!Supporter] có thể đổi màu nhận xét tùy ý.",
    "conferencemode": "Bạn bị choáng ngợp bởi các tin nhắn Join/Quit trên kênh IRC? Hướng dẫn [http://wiki.xkcd.com/irc/Hide_join_part_messages này] sẽ có thể giúp đỡ bạn!",
    "country-ranking": "Xem các bảng xếp hạng Quốc gia tại  [https://osu.ppy.sh/p/countryranking Country Ranking đây]",
    "critic": "Hãy tranh luận có tính xây dựng! Đưa ra những phương thức khác hay những cách giải quyết vấn đề mà bạn đang thắc mắc.",
    "ctb": "Mới chơi Catch the Beat? [https://osu.ppy.sh/wiki/Catch_the_Beat Trang này] có thể giúp đỡ bạn! ",
    "cutting-edge": "Cutting-edge là phiên bản osu! thử nghiệm để kiểm tra các chức năng mới trước khi đưa chúng vào hoạt động ở bản stable.\nBạn có thể tham khảo tại [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues trang này] nếu bạn gặp vấn đề về việc update game.",
    "cwc": "CWC là giải Catch the Beat với quy mô toàn thế giới! [https://osu.ppy.sh/wiki/en/Tournaments/CWC/2023 Đọc bài viết này] để biết thêm thông tin chi tiết.",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\r\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\r\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "Hãy đối xử với mọi người cách bạn muốn được đối xử nhé! Hãy trò chuyện có chừng mực, còn nếu bạn muốn bản thân mình bị chửi thì hãy nhớ rằng không phải ai cũng vậy đâu...",
    "disable-this": "Các nút bấm hiếm khi được thêm vào để trở thành một tính năng mới. Bạn vẫn có thể yêu cầu để thêm tính năng vào trò chơi tại [https://osu.ppy.sh/forum/4 đây].",
    "distance-snap": "Distance Snap (Điều chỉnh khoảng cách giữa các note) là một công cụ giúp việc căn lại khoảng cách giữa các note, dựa vào vị trí của chúng trên dòng thời gian. Thông tin chi tiết: [[Distance_Snap]]",
    "dont-ask-peppy": "Đừng hỏi peppy quá nhiều - anh ta cũng khá bận. Bạn hãy hỏi những người khác trong cùng kênh chat.",
    "douche": "Để bảo vệ an toàn cho mọi người, việc vi phạm trật tự và thiếu lễ phép thông qua những kẽ hở trong các quy tắc có thể bị trừng trị theo quyết định và phán xét của đội ngũ quản lý.\nLuật chính thức của trò chơi có nêu lên rằng bạn đừng biến mình thành một con người tồi tệ trong mắt người khác, và cũng không cần thiết phải trở thành một người như vậy. Nhưng dù sao thì cũng đừng là một con người tồi tệ, như vậy là trái với luật và bạn có thể bị trừng trị.",
    "download": "Tải beatmap [https://osu.ppy.sh/p/beatmaplist ở đây].\nTải nhiều beatmap với cùng chủ đề [https://osu.ppy.sh/beatmaps/packs ở đây]. Nếu bạn không rõ thêm beatmap vào trong game như thế nào, bạn có thể đọc [http://i.imgur.com/kpX2N3m.jpg tại đây] để biết thêm thông tin.",
    "drugs": "Thảo luận về các chất cấm trên osu! là điều cấm kỵ. Đây là game cho mọi độ tuổi.",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "Hãy đọc [[Beatmapping#Keyboard_Shortcuts]] để tìm kiếm dãy những phím tắt thuận tiện cho việc chỉnh sửa beatmap.",
    "english": "#english là kênh chung dành cho những chủ đề không có kênh chat riêng biệt, và ừ, nó bao gồm cả anime/manga (và tàu nữa, vì lí do nào đó).",
    "evade": "Trốn tránh việc chặn chat là nền tảng để khiến tài khoản của bạn bị hạn chế (restricted) một thời gian khá lâu, nặng hơn là bị hạn chế tài khoản hoàn toàn đấy. Đừng.",
    "fallback": "Stable (Fallback) là một phiên bản osu! lỗi thời. Khác Fallback, phiên bản mới nhất đã loại bỏ hỗ trợ DirectX để đơn giản hóa framework. Nếu bạn bị chuyển sang phiên bản này, máy tính của bạn sẽ là máy tính cấp thấp và không hỗ trợ những phiên bản hiện tại và tương lai.\nNếu bạn muốn chơi ở phiên bản hiện tại, nâng cấp card đồ họa và đảm bảo rằng nó hỗ trợ OpenGL, thứ cần thiết nhất cho những phiên bản này. [https://osu.ppy.sh/wiki/GL_Support_Issues Bấm vào đây để biết cách làm]",
    "faq": "Bạn đang sử dụng hệ thống Hỏi và Đáp (FAQ) của osu!Bancho.\nosu! wiki: https://osu.ppy.sh/wiki",
    "feature": "Nếu bạn có bất kỳ ý tưởng gì cho trò chơi, hãy đăng nó lên tại subforum [https://osu.ppy.sh/forum/4 yêu cầu chức năng].\nÀ, hãy nhớ đọc kỹ [https://osu.ppy.sh/forum/t/454006 hướng dẫn diễn đàn] trước nhé!",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "Tránh bộ lọc của chat có thể dẫn đến việc bị chặn chat. Đừng làm vậy.",
    "foul-play": "Hãy báo cáo cheater bằng cách sử dụng nút báo cáo (report) ở profile của họ, ở [https://i.imgur.com/GG9xlLA.png đây].\nĐảm bảo bạn cung cấp càng nhiều thông tin càng tốt. Bạn cũng có thể báo cáo thành tích tài bảng xếp hạng top 50 của trang beatmap.\nĐỪNG bàn luận về vấn đề này công khai, bạn sẽ bị chặn chat.",
    "percolate": "Tránh bộ lọc của chat có thể dẫn đến việc bị chặn chat. Đừng làm vậy.",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/news/61334266941 Bài viết này] sẽ giúp bạn hiểu về các pattern cũng như khắc phục những lỗi sai khi mod hay tạo ra một beatmap.",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "Để thêm một người chơi khác làm bạn, gõ /addfriend sau đó là tên người chơi cần thêm vào danh sách bạn bè, hay bạn cũng có thể click vào tên của người chơi đó trong danh sách những người chơi đã đăng nhập (bấm F9) hoặc tên họ trong bảng chat và chọn Add as Friend (Thêm bạn).\nBạn cũng có thể thêm họ vào danh sách bạn bè thông qua việc truy cập trang thông tin của người chơi bạn muốn thêm và nhấn Add as Friend",
    "friends-list": "Để xem danh sách nhũng người bạn đang online, bấm F9 sau đó thay đổi bộ lọc ở trên cùng là Friends.\nBạn cũng có thể xem danh sách bạn bè đầy đủ của mình, online hay offline trên trang chủ tại [https://osu.ppy.sh/home/friends đây](bạn sẽ cần phải đăng nhập trước khi truy cập được).",
    "fullscreen": "Bạn có thể thay đổi cách trò chơi hiển thị qua chế độ Cửa sổ hay Toàn màn hình dưới dòng Đồ Họa trong bảng Options (thiết lập).\nBạn cũng có thể chuyển qua lại chế độ Toàn màn hình bằng cách nhấn tổ hợp phím Alt+Enter trên bàn phím.\nChế độ toàn màn hình không hỗ trợ trên trình render OpenGL.",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "Bạn có thể xem hết các thuật ngữ của trò chơi tại osu! [[glossary]].",
    "gmt": "[https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team], hay viết tắt là [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT], là một nhóm những người chơi giúp đỡ trong việc vận hành osu!. Tên của họ có màu đỏ trong bảng chat và màu xanh trên forum.\nHọ giúp đỡ trong việc quản lý forum và chat.\n",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 Đọc, ngẫm nghĩ và hãy sửa ngữ pháp của mình.]",
    "grammar": "Hãy cố gắng sử dụng ngữ pháp đúng cách. Một vài lỗi nhỏ trong việc đánh vần hay chính tả đều có thể chấp nhận được, nhưng đừng viết tắt hay sử dụng ngôn ngữ nói trong khi viết. Nó khiến bạn trông thật đần độn.",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "Bạn không biết cách chơi? Bạn muốn khám phá thêm về việc mod và map? Hãy truy cập vào [https://osu.ppy.sh/wiki/Guides đây] để tìm những câu trả lời.",
    "hacked": "Nếu bạn tin rằng tài khoản của bạn đã bị hack, hãy email accounts@ppy.sh để báo cáo về việc này, nếu không, tài khoản của bạn sẽ có nguy cơ biến mất vĩnh viễn.",
    "hard": "Non, play more đi!",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "Nếu bạn cần sự trợ giúp cho bất cứ những gì có liên quan đến osu!, hãy gia nhập kênh #help và hỏi câu hỏi của bạn. Nhân tiện, #help là 1 kênh đa ngôn ngữ.\nNếu không có ai phản hồi, bạn có thể đăng ở [[https://osu.ppy.sh/forum/5 Help] forum nếu cần thiết.\nBạn cũng có thể tham khảo [http://help.ppy.sh/ trang này] để tìm những bài viết hữu ích cho bạn, bao gồm cả những vấn đề liên quan đến tài khoản của bạn.",
    "hitsound-library": "Truy cập vào [https://osu.ppy.sh/forum/p/164927 đây] để có thêm được các hitsound cho map của bạn.",
    "hl": "Xin đừng đổ lỗi cho người chơi khác nếu họ highlight tên bạn khi tài khoản của bạn hay danh sách những tên có highlight của bạn có những từ được sử dụng phổ biến. Bạn có thể tắt thông báo và âm thanh thông báo khi việc này xảy ra trong mục Options (Cài Đặt) nếu cần thiết.",
    "how-to-get-modded": "Nếu bạn muốn biết cách để khiến beatmap của mình được nhiều người chú ý hơn nữa, bấm vào đây: [[Getting_Your_Map_Modded]] để tham khảo.",
    "how-to-bn": "Nếu bạn muốn trở thành một BN, hãy đọc kĩ hướng dẫn tại [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator đây] . Việc lựa chọn BN mới sẽ được thực hiện bởi các BN khác và dựa theo chất lượng hoạt động của bạn.",
    "how-to-gmt": "Các Chat Moderator (điều hành viên) là những người được lựa chọn rất cẩn thận từ những con người có đóng góp to lớn trong cộng đồng. Để biết thêm thông tin chi tiết, hãy đọc trang wiki của nhóm:  [https://osu.ppy.sh/wiki/People/The_Team/Global_Moderation_Team Global Moderation Team]",
    "how-to-play": "[https://osu.ppy.sh/wiki/FAQ#How_do_I_play.3F Cách chơi!]",
    "how-to-rank": "Để hiểu, hãy đọc [[How_to_Get_Your_Map_Ranked]].",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "Hyperdash (Dash với tốc độ cực nhanh) sẽ xảy ra khi bạn đỡ được hoa quả tỏa ra màu đỏ. Bạn sẽ dash nhanh hơn trong khoảng thời gian này. Nó sẽ kết thúc khi bạn tới được quả rơi sau đó hoặc đỡ trượt nó.",
    "ignore": "Để phớt lờ một người chơi khác, gõ /ignore sau đó là tên người cần lờ đi.\nBạn sẽ không thể nhìn thấy các dòng chat của người bạn vừa lờ đi, kể cả những tin nhắn riêng mà họ có thể gửi bạn.\nGõ /uningnore (tên người chơi) hoặc thoát osu! sẽ dừng việc chặn này lại. Để hoàn toàn chặn một người chơi, hãy tham khảo [http://help.ppy.sh/article/141/how-do-i-completely-block-another-user-from-contacting-me bài viết này].",
    "import": "[http://i.imgur.com/kpX2N3m.jpg Cách đưa beatmap vào Osu!]",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "Bằng cách tích vào ô Inherit previous timing settings (Sử dụng thiết lập thời gian lúc trước) ở cửa sổ F6 trình Editor, các phân đoạn thời gian sẽ không ảnh hưởng tới thời lượng, sẽ rất hữu ích cho những phân đoạn chỉ chuyển âm lượng hay các đoạn nhạc mẫu của map. Hơn nữa, ta cũng có thể sử dụng thiết lập này cho những bài nhạc có BPM gấp đôi hay bằng một nửa. Nếu bạn cũng sử dụng các phân đoạn thời gian như vậy, hãy sử dụng các thiết lập mặc định!",
    "irc": "Server IRC: irc.ppy.sh:6667\nMật khẩu: https://osu.ppy.sh/p/irc\nĐể biết thêm thông tin, truy cập https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "Bạn có thể thay đổi thiết lập bàn phím trong phần Options > Input.\nPhím và layout trong osu!mania có thể thay đổi bằng cách bấm nút osu!mania layout.",
    "kiai": "Kiai là một hiệu ứng mà bạn có thể thêm vào phần dòng thời gian sử dụng Bảng Thiết Lập Thời Gian. Các thời điểm mà kiai được thiết lập sẽ có các hiệu ứng khiến beatmap thêm ngầu.",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "Kiếm [https://osu.ppy.sh/wiki/Kudosu kudosu] bằng cách mod beatmap của người khác.",
    "lag": "Lag có thể xảy ra từ [https://osu.ppy.sh/help/wiki/Performance_Troubleshooting mọi thứ] - hầu hết thường là do các chương trình khác được chạy (ngầm) trên máy của bạn. Nếu bạn tin rằng chỉ có osu! bị lag, hãy nộp một đơn xin trợ giúp trên forum Technical Support (Hỗ trợ kỹ thuật), giải thích rõ ràng vấn đề và bất cứ những bằng chứng gì mà bạn biết để có thể nhận biết được lỗi.",
    "language": "Hãy cư xử lịch sự trong room chat. Sử dụng ngôn từ không phù hợp sẽ khiến bạn bị chặn chat.",
    "language-specific": "Hãy sử dụng ngôn ngữ thích hợp trong kênh bạn tham gia.\nKhông sử dụng từ và ngôn ngữ la-tinh trong những kênh ngôn ngữ không dùng chữ la-tinh, ví dụ như kênh Tiếng Nhật.",
    "lazer": "[https://www.youtube.com/watch?v=ut_SOreClcc Lazer là gì?] Đó là tên gọi cho dự án lớn sắp tới của osu!\nGitHub: [https://github.com/ppy/osu ppy/osu] | Tải về: [https://github.com/ppy/osu/releases ppy/osu/releases]",
    "level": "Cấp (level) của bạn dựa vào tổng số điểm bạn đạt được. Nó gồm điểm rank, kể cả pass hay fail. Bạn sẽ từ từ lên level chỉ bằng việc chơi osu!",
    "lines": "Hãy giữ cho câu nói của bạn nằm trên cùng 1 dòng thay vì nhiều dòng cùng lúc để tránh bị cấm chat nhé.",
    "link": "Để lồng lời muốn nói vào link, bạn hãy sử dụng cấu trúc sau: [link lời-nói], trong đó 'link cần chia sẻ' sẽ là link trang web bạn muốn chia sẻ, và 'lời nói' là câu mà bạn muốn chia sẻ. [https://osu.ppy.sh Nó sẽ hiện ra giống như thế này!] Đừng quên thêm đầu http:// vào trước link và nhớ cách link và thứ muốn nói ra nhé!",
    "lobby": "Xin hãy sử dụng kênh #lobby để quảng cáo phòng chơi osu! multiplayer. À, #lobby là một kênh đa ngôn ngữ, nên bạn có thể sử dụng nhiều ngôn ngữ giao tiếp khác nhau.\nNhớ sử dụng kênh #multiplayer trong phòng chơi của bạn để bàn luận về những chuyện khác nhé.",
    "localisation": "[https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 Đây] là dự án osu! localisation, hay nói đơn giản dự án dịch osu! sang nhiều ngôn ngữ ",
    "long-link": "Xin đừng copy những link dài trong khung chat, hãy sử dụng cấu trúc [link lời-nói] nếu cần thiết.",
    "long-text": "Xin đừng copy paste nguyên cả một tường chữ vào trong khung chat. Bạn có thể bị chặn chat nếu làm vậy.",
    "loved": "Yêu thích (Loved) là 1 trạng thái rank mới (được phụ thuộc từ cộng đồng) nhằm thêm bảng điểm vào những map không thể rank. Bạn có thể đọc và tìm hiểu thêm [https://osu.ppy.sh/news/151925254083 tại đây!]",
    "mac": "[https://osx.ppy.sh Chạy osu! trên máy tính Mac của Apple]",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Các mapper là những người bận rộn và mapping đòi hỏi nhiều kĩ năng và công sức. Hãy là bản thân bạn hãy thử mapping xem?",
    "mapping": "Truy cập vào [https://osu.ppy.sh/forum/p/988111 đây] để xem các hướng dẫn về mapping.",
    "mat": "Mapping Assistance Team (Đội hỗ trợ map) là một nhóm các người chơi cũ giúp BAT (Beatmap Approval Team) trong việc hoàn thành quá trình rank map.\nR.I.P MAT 23/4/2013",
    "modhelp": "Đối với tất cả những câu hỏi và/hoặc thắc mắc về modding/mapping beatmap, hãy gia nhập kênh #mapping!",
    "modqueue": "[https://osu.ppy.sh/forum/60 Hàng chờ Modding]",
    "modreqs": "Sử dụng kênh chat #modreqs đối với tất cả các nhu cầu mod beatmap. Lưu ý rằng các BN (Beatmap Nominator) không phải lúc nào cũng có thời gian và họ phải hoàn thành các yêu cầu của những người khác đã yêu cầu và đăng ký sớm hơn, vậy nên hãy hỏi thêm cả những người chơi khác về việc này. Để làm một yêu cầu, nhớ dùng lệnh /np hoặc cấu trúc [link lời-nói], và đừng quên cám ơn họ sau đó!",
    "multi-invite": "Để mời ai đó vào phòng multiplayer của bạn khi đang host một phòng multiplayer, nhấn vào tên người cần mời trong bảng Online Users (bấm F9) hay bấm vào tên họ trong khung chat và chọn Invite to game (Mời vào phòng).\nBạn cũng có thể gõ lệnh /invite theo sau đó là tên người chơi cần mời.",
    "multi-link": "[https://osu.ppy.sh/community/forums/topics/338482 Cách để tạo một đường link dẫn vào phòng multiplayer của bạn]\n        ",
    "multiaccounting": "Bạn thật sự, thật sự không nên tạo nhiều tài khoản khác nhau. Bạn sẽ bị phát hiện, và có thể sẽ bị chặn chat trong một thời gian khá là dài, hoặc thậm chí là bị ban!",
    "multiplayer": "Xin đừng quảng cáo phòng multiplayer trong bất kỳ kênh nào ngoài #lobby.",
    "mwc": "Giải đấu osu! Mania quy mô trên toàn thế giới. [https://osu.ppy.sh/wiki/en/Tournaments/MWC/2022_4K Đọc bài viết này để có thêm thông tin chi tiết.].",
    "nat": "Nhóm [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] đảm nhiệm sự giám sát nhóm đề cử beatmap (BN - Beatmap Nominator) và bảo đảm quá trình rank của beatmap. Họ có trách nhiệm về việc đánh giá những BN hiện tại và những người đang mong muốn trở thành BN, hơn thế nữa là làm trung gian cho việc phủ quyết beatmap và những việc cần được giải quyết liên quan đến mapping / modding.",
    "news": "osu! thay đổi theo thời gian là nhờ công đóng góp của những người luôn đang đồng hành và giúp cho game ngày càng phát triển hơn. Hãy cập nhật thông tin bằng cách xem [https://osu.ppy.sh/home/news trang tin tức của osu!].",
    "nightcore": "Thưởng thức các beatmap dưới dạng NightCore(NC)!\nNó rất đơn giản, bạn hãy bấm chuột phải vào biểu tượng DoubleTime(DT) để kích hoạt chế độ NightCore! Nó hoạt động giống y hệt DoubleTime khi tính điểm. ",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "Gõ /np để chia sẻ với những người khác bạn đang nghe hay chơi gì trong osu!",
    "nsfw": "Những cuộc trò chuyện với ngôn ngữ đồi trụy hay bẩn thỉu là điều cấm kỵ. Osu! là trò chơi dành cho mọi lứa tuổi, nên hãy giữ cho khung chat sạch, hoặc bạn sẽ bị chặn chat mà không cần báo trước",
    "osu": "Kênh #osu là kênh dành để nói về osu!. Hãy bàn luận về trò chơi ở đó, không phải tại kênh này.",
    "osu!tablet": "[https://osu.ppy.sh/forum/t/169139 Thread chính thức dành cho osu!tablet!] - Đọc thread này để biết thêm chi tiết về chiếc tablet và các phương thức đặt trước.",
    "osu!talk": "osu!talk là chương trình talkshow được dẫn bởi deadbeat và ztrot, phỏng vấn những thành viên trong cộng đồng và bàn luận về những sự kiện như osu! World Cup.\nNó đã được điều hành tiếp bởi osu! Coffee Hour sau khi những người dẫn chương trình trước đó nghỉ hưu khỏi team.",
    "osucore": "Một trò đùa về ngày Cá Tháng Tư năm 2011. Tất cả các map đều được mặc định với mod DoubleTime và cao độ đều được chỉnh lại.\nSau này nó trở lại dưới dạng mod NightCore, và nó cũng có hiệu ứng giống hệt DoubleTime vào ngày hôm đó.",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] là bản port của osu! trên Android.\nPhiên bản này không còn được phát triển và đã bị gỡ khỏi Google Play Store từ 2016 do không hoạt động và những review không tốt.",
    "osumania": "Hãy sử dụng kênh #osumania đối với những thảo luận về chế độ Mania.",
    "osustream": "[http://www.osustream.com osu!stream] là osu! dành cho các thiết bị iOS, được tạo ra và duy trì bởi chính peppy!",
    "osz": "Dạng file của beatmap mà bạn tải về cho osu! để giải nén và chơi (.osz) luôn phải được giải nén bởi chính osu!, nếu không những trục trặc sẽ có thể xảy ra!",
    "osz2": "Một dạng file beatmap mới sẽ có thể được mã hóa, cập nhật và chuyển đi một cách độc lấp so với những file khác. File osz2 sẽ không cần giải nén và sẽ luôn có dạng .osz2 trong thư mục Songs.",
    "owc": "Một giải đấu osu! toàn thế giới.  [https://osu.ppy.sh/wiki/OWC Đọc thread này để biết thêm chi tiết.]",
    "peppy": "peppy là trưởng nhóm phát triển osu! và phần lớn dự án đều do anh tự tay làm.",
    "perfect": "Không được rank SS sao? Mod này sẽ tự động retry map cho bạn nếu bạn thực hiện bất cứ lỗi nào.\nBạn có thể kích hoạt nó bằng cách bấm chuột phải vào mod SuddenDeath trong mục lựa chọn mod.",
    "ping": "Pong!",
    "pippi": "Là linh vật của osu!\nPippi-don là phiên bản taiko (trống) của Pippi.",
    "piracy": "Xin đừng bàn luận một cách công khai về những nội dung được đăng ký bản quyền ở kênh chung. Đây là điều cấm kỵ và bạn có thể bị cấm chat.",
    "play-shortcuts": "Danh sách tất cả các phím tắt: [[Shortcut_Key_Reference]]",
    "pm": "Để chat riêng với một ai đó, nhấn vào tên họ trong khung chat hoặc trong bảng Online Users rồi bấm Start Chat (Bắt đầu Chat).\nBạn cũng có thể sử dụng lệnh /msg <tên người chơi> hoặc /chat <tên người chơi> hoặc /query <tên người chơi>, osu! sẽ mở ra một khung chat riêng.\nĐể trả lời ai đó một cách nhanh chóng đối với tin nhắn riêng gần nhất, bạn có thể sử dụng lệnh /r <tin nhắn>. Dĩ nhiên là bạn sẽ phải bỏ dấu < > đi rồi!",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "Performance Point (pp) là cách tính rank chính của osu! Nhấn vào [https://osu.ppy.sh/wiki/Performance_Points đây] để biết thêm chi tiết.",
    "pp-rework-lazer": "",
    "preview": "Điểm bắt đầu nghe trước là điểm mà bài hát sẽ bắt đầu phát khi người chơi chọn nó trong màn chọn bài.\nĐiểm nghe trước đúng sẽ là điểm mà thể hiện tốt về bài hát, ví dụ như bắt đầu của đoạn điệp khúc. Vào phần Timing trên thanh công cụ và nhấn Set Current Position as Preview Point để chọn một điểm bắt đầu.",
    "qat": "Đội ngũ Quality Assurance Team (QAT) kiểm tra những map mới được đề cử để đảm bảo về chất lượng và tính toàn vẹn của beatmap.\nSau sự phát triển ngoài mong đợi của hệ thống ranking, từ tháng 4/2019, nhóm đã đổi tên thành Nomination Assessment Team (NAT) để có thể họ dễ dàng thực hiện công việc họ nên làm hơn.",
    "qualified": "Beatmap Nominators (BN) đề cử map vào trạng thái qualified, có nghĩa là đã đủ điều kiện điều kiện để đăng điểm mà không có pp.\nNếu những map này không có vấn đề gì và đã qualified được 1 tuần, nó sẽ được rank. Còn không thì sẽ quay trở lại trạng thái pending và tất cả điểm đều bị xóa.",
    "ranked": "Một beatmap Ranked (được xếp hạng) sẽ là một beatmap được chấp thuận bởi cộng đồng online.\nKhi bạn chơi một map Ranked, điểm số bạn đạt được sẽ được cộng vào tổng điểm số rank.\nNhững map này có một bảng xếp hạng riêng, và có thể được nhận diện bởi biểu tượng 2 dấu mũi tên đi lên.",
    "ranking-criteria": "Để biết thêm thông tin về tiêu chí rank, hãy truy cập wiki: [[RC]]",
    "redname": "Những người dùng có tên màu đỏ là [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team(GMT)] hoặc [https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team(NAT)]",
    "report": "Điều hành viên không phải lúc nào cũng có mặt; họ cũng là những con người và họ không thể trông coi cái khung chat cả ngày được. Trong trường hợp bạn phát hiện ai đó làm điều gì đó ngu ngốc và không có mod nào có hành động gì, hãy sử dụng cấu trúc !report <Tên_Người_Dùng> <Lí do> (Mọi dấu cách trong tên đều được thay thế bằng _)\nLệnh report phải được dùng trong những kênh chat công khai và những người khác sẽ không thể thấy report của bạn, tránh report trong chat riêng của người bạn muốn báo cáo.\nBạn cũng có thể report bằng cách ấn vào tên người dùng chọn Report User...",
    "report-abuse": "Xin đừng báo cáo sai phạm liên tiếp nhiều lần - nó không giúp bạn thực thi công lý nhanh hơn đâu. Kể cả báo cáo trống hay các lý do không chính đáng cũng vậy.\nBạn sẽ có thể bị chặn chat vì spam các điều hành viên đấy!",
    "request": "Bạn đang tìm kiếm thứ gì đó để mod sao? Nhấn vào [https://osu.ppy.sh/p/beatmaplist&r=8 đây] hoặc gõ lệnh !request và hệ thống sẽ đưa ra link các map ngẫu nhiên.",
    "respect": "Hãy lịch sự đối với những người chơi khác.",
    "roll-abuse": "Đừng sử dụng lệnh !roll quá nhiều. Bạn có thể sẽ bị chặn chat đấy!",
    "romaji": "Đừng sử dụng Romaji (tiếng Nhật phiên âm ra tiếng la-tinh) quá nhiều. Bạn có thể bị chặn chat đấy.",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "Nếu không có phòng multiplayer nào, sao bạn không tự lập một phòng của riêng mình nhỉ? Bạn cũng có thể tự chọn các bài hát nữa mà!",
    "rp": "Bạn có thể thoải mái roleplay trong các kênh của osu!, tuy nhiên, bạn nên chắc chắn rằng mình đang không làm phiền người khác trong kênh đó nữa.",
    "rules": "[https://osu.ppy.sh/wiki/Rules Luật lệ trong cách hoạt động của Osu!]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "Có một vài thời điểm mà osu! bị DDoS (Tấn công từ chối dịch vụ). Trong khoảng thời gian này, Bancho có thể sẽ không ổn định hoặc bạn sẽ không thể truy cập được tới Bancho.\nNếu bạn nhận biết được rằng chuyện này đã xảy ra, kiểm tra kênh twitter [https://twitter.com/osustatus @osustatus] hoặc [https://status.ppy.sh trang này] để biết thêm thông tin.\nNếu điều này xảy ra, và bạn vẫn có thể chat được - hãy tiếp tục như bình thường. Quan trọng hóa vấn đề này sẽ không khiến nó trôi qua nhanh đâu!",
    "sb": "Hướng dẫn về Storyboard: https://osu.ppy.sh/forum/t/1869\nCách chỉnh sửa Storyboard trong trình chỉnh sửa: https://osu.ppy.sh/forum/t/8145",
    "scorev2": "ScoreV2 (gọi tắt là SV2) là một thuật toán tính điểm mới, giới hạn điểm cho tất cả chế độ chơi về 1 triệu điểm, không bao gồm điểm từ spinner và mods.\nNó cũng thay đổi cách hoạt động của slider để timing của chúng giống với timing của hitcircle.",
    "scoring": "Cách osu! tính điểm: [[Score#scoring]]",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "Bị cấm chat(silence) đồng nghĩa với việc bạn không thể nói chuyện trong chat hay post trong fourm, ngoại trừ tại bộ phận hỗ trợ kĩ thuật.                                                                            \nSilence sẽ bắt đầu từ 5 phút cho lần vi phạm đầu tiên, sau đó sẽ tăng gấp đôi mỗi vi phạm từ đó. Vi phạm nặng sẽ tăng nhiều hơn gấp đôi so với vi phạm trước đó                                                                                   Silence thường được nhận khi vi phạm những lỗi nhẹ, do đó chỉ cần tuân thủ những quy tắc và bạn có thể trở lại bình thường",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 Hỏi và Đáp(FAQ) về Skin]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY Đừng để osu! khiến bạn chơi thâu đêm nhé. Giấc ngủ vẫn rất là quan trọng đấy!]",
    "songs-not-appearing": "Nếu những bài hát của bạn không xuất hiện trên màn hình chọn nhạc, hãy thử bấm F5.",
    "spaces": "Đừng thêm dấu cách quá nhiều vào sau mỗi chữ cái. Cái thẩm mỹ của bạn sẽ làm loạn chat và có thể bị chặn chat.",
    "spam": "Đừng spam khi chat. Nó rất là khó chịu và bạn có thể sẽ bị cấm chat (silence).",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "Để quan sát người chơi khác chơi, gõ /watch <Tên người chơi>, hoặc nhấn vào tên họ trong khung chat hoặc khung Online Users và chọn Start Spectating (Bắt đầu quan sát).\nHãy chắc chắn rằng bạn đang có beatmap mà họ đang chơi (và chắc chắn rằng đúng thật sự là họ đang chơi nữa)!",
    "spoiler": "Spoil bất kì anime, series, manga, doujin, v.v và mây mây đều bị cấm và có thể khiến bạn bị chặn chat. Hãy để mọi người được thưởng thức những thứ họ thích trong yên bình! (Điều này cũng áp dụng cho các chi tiết mà tác giả tương ứng chưa tiết lộ)",
    "status": "Với những cập nhật mới về hệ thống osu!, hãy tham khảo tại [http://twitter.com/osustatus @osustatus]. Còn về tình trạng của máy chủ, hãy xem tại [https://status.ppy.sh đây].",
    "store": "[https://osu.ppy.sh/p/market Chào mừng tới osu! market], nơi bạn có thể mua những chiếc áo phông đẹp tuyệt vời và nhiều thứ khác hay hơn nữa!",
    "submit": "[https://osu.ppy.sh/wiki/Submission Thông tin hỏi đáp về việc tải beatmap lên.]",
    "suck": "Có rất nhiều những kĩ năng và kiến thức khác nhau ở osu! - bạn sẽ chơi tiến bộ hơn theo thời gian thôi, vậy nên hãy cố gắng lên nhé!",
    "supporter": "Hãy trở thành một [https://osu.ppy.sh/p/support osu! supporter]! Bạn sẽ có được thêm những lợi ích, và giúp đỡ đội phát triển hơn nữa!",
    "supporter-please": "Đừng đòi hỏi người khác tặng bạn tag supporter.\n[https://osu.ppy.sh/p/support Hãy tự mua ở đây này!]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "Nếu con trỏ của bạn bay tứ tung khi bạn cố di chuyển nó, hãy chắc chắn rằng độ nhạy của chuột đang là 1.00x. Để đạt được độ nhạy lớn hơn, bạn có thể chỉnh tablet area bé lại.\nNếu con trỏ của bạn không di chuyển chút nào, hãy chắc chắn rằng bạn đã tắt Raw Input trong mục Options.\nĐối với bất kỳ những sự cố nào khác liên quan đến tablet, [https://osu.ppy.sh/forum/t/87301 hãy đọc thread này.]",
    "tag": "Trong chế độ multiplayer tag, mỗi người chơi phải lần lượt nhấn vào từng combo của beatmap cùng một lúc. Không có ai thắng hay thua nếu như mọi người đều chơi cùng một đội. \nKhi quay spinner, ai cũng phải spin. Kể cả chỉ một người không clear được spinner, chỉ số combo sẽ trở lại như ban đầu. Điểm thưởng spinner của mỗi người sẽ được thêm vào tổng điểm của đội.                                                                                                                                                              ",
    "taiko": "Trống Nhật từng là biểu tượng trong loạt trò chơi của Bandai-Namco. Taiko Mode của osu! mô phỏng lại những trò chơi ấy bằng cách loại bỏ vị trí phách, bắt buộc người chơi chỉ tập trung vào nhịp điệu beatmap.\n[https://osu.ppy.sh/forum/t/4363 Hướng dẫn cách chơi Taiko!]",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 Hướng dẫn Taiko mapping ]",
    "taiko-maps": "Bạn có thể tìm beatmap của Taiko no Tatsujin [https://osu.ppy.sh/forum/t/5397 ở đây.]\nCó thể bạn cũng sẽ có hứng thứ để [https://osu.ppy.sh/forum/t/175867 luyện chơi Taiko cho người mới chơi].",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "Bạn có thể bàn luận về một chủ đề khác được không?\n",
    "training": "[https://osu.ppy.sh/forum/t/4280 Bí quyết luyện tập của James]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/forum/t/109137 Cập nhật các video hướng dẫn chơi nói chung và mapping mới nhất tại đây.] Hãy thoải mái sáng tạo và đăng những beatmap bạn làm tại đây. [https://osu.ppy.sh/forum/t/60228 Cập nhật hướng dẫn dành cho các mapper và modder tại đây.]",
    "twc": "Giải đấu osu! Taiko quy mô toàn thế giới. [https://osu.ppy.sh/wiki/en/Tournaments/TWC/2023 Đọc bài viết này để có thêm thông tin chi tiết.]",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "Hãy hạn chế sử dụng dấu và kí tự đặc biệt (các ký tự có dấu trong bảng chữ cái Việt Nam) trên kênh chính.",
    "upload-cap": "Để giúp các mapper tiếp tục hoàn thành những map còn đang dang dở, một giới hạn nhỏ đã được đặt ra với số lượng map mà bạn có thể thực hiện cùng một lúc.\nVới những người không phải osu!supporter thì có thể có 3-6 map cùng lúc, supporter là 5-10 map, tùy thuộc vào lược map đã được rank trước đó của họ.",
    "utf8": "Bạn hãy chỉnh cho client IRC của mình sử dụng hệ mã hõa UTF-8 để có thể gửi và nhắn tin cho những người chơi khác.",
    "videogames": "Các chủ đề liên quan đến trò chơi điện tử có thể được bàn luận ở kênh #osu, nhung nếu nó gây ảnh hưởng tới kênh chat hoặc có nhiều cuộc thảo luận trong cùng một lúc, hãy sử dụng kênh #videogames.",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "Chào mừng đến với Osu! Nếu bạn có bất cứ vấn để hoặc có câu hỏi thắc mắc, hãy hỏi những người tốt bụng trong #help và nhớ giữ chat thân thiện nhé :D",
    "when": "Khi nó đã sẵn sàng.",
    "wiki": "[https://osu.ppy.sh/wiki/ The osu!wiki] - Hãy làm cho nó trở nên tuyệt vời! Bây giờ bạn có thể đóng góp thêm từ GitHub: [https://github.com/ppy/osu-wiki/ ppy/osu-wiki]",
    "wiki-link": "Bạn có thể dẫn link tới trang wiki bằng cách gõ danh mục wiki trong dấu ngoặc vuông kép như thế này: [[...]]\nVí dụ, [[Kudosu]] được tạo ra bởi việc gõ Kudosu vào giữa [[ và ]].",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 216 active FAQs (out of a possible 217) in the Vietnamese (Tiếng Việt) language.",
    "completion": "The Vietnamese (Tiếng Việt) FAQ as of last update is 99.54% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
