
strings = {

    "academy": "[http://www.youtube.com/user/osuacademy Haga clic aquí] para ir a osu!academy - Tutoriales sobre todos los aspectos básicos de osu!",
    "achievements": "通过完成特定的任务你可以解锁成就，比如说某首歌得到很高的连击，或者一个主题包里的谱面都玩过一次。很多成就通过字面意思你就可以知道怎么取得，而另外一些就需要你动脑筋想想了。",
    "add-skin": "如果想添加新皮肤，只需下载后将皮肤文件拖进osu!游戏窗口，或者双击皮肤文件即可。",
    "advertising": "在 osu! 所包含区域给任何东西打广告都是禁止的。重复或严重违反将会至少被禁言。",
    "answer": "如果没有人回答你的问题，有可能是大家不知道答案，或者他们不想回答“是”。",
    "appeal": "如果你被禁言后觉得这个处置不公平，向 accounts@ppy.sh 发送邮件告知你的情况。不过记得，管理员也是人，也是会犯错的！如果你对他们的态度好一些，他们会更愿意为你解除禁言。",
    "approved": "Approved 谱面因为一些原因而无法被 Rank ── 不过它们还是有一定品质和可玩性，且同样拥有排行榜和所有功能！你可以在选图时通过左上角的图案來分辨谱面的种类，Approved 谱面的图标是火焰而不是爱心。",
    "arabic": "للتحدث بالعربية يرجى الدخول إلى #arabic، تستطيع التحدث بالإنجليزية فقط في #osu.",
    "aspire": "Aspire，最首要的高等级Osu!制图比赛在2017年回归，曲目来自Helblinde。[http://osu.ppy.sh/news/156171674413 查看详情]",
    "ask": "查询 irc 指令列表请输入 /help ，查询 faq 列表请输入 !faq list\n新手常见问题请来 [https://osu.ppy.sh/forum/t/10737 这里] ，精华文章导览请来 [https://osu.ppy.sh/forum/t/14364 这里] 或 [https://osu.ppy.sh/forum/t/109978 这里]。\n还有什么不懂的地方吗请随便问不用客气哦。",
    "attention": "看来你的存在感低得连阻止你的人都沒有。求您了，別说了。",
    "avatar-change": "在游戏画面点自己的名字，选择 2.Change Avatar ，进入 [https://osu.ppy.sh/home/account/edit#avatar 这个页面] 点击 browse 选择图片尺寸小于 128x128 ，且大小小于 88kb 的图片上传。",
    "bahasa": "Jika anda mahu berbicara sepenuhnya dalam bahasa Inggeris, sila gunakan #english. Penggunaan bahasa Inggeris yang minimum adalah dibenarkan, tetapi perlu diingatkan bahawa channel ini dikhaskan untuk bahasa Malaysia.",
    "balkan": "Za Jugoslovenski jezik, molim te koristi kanal #balkan.\nNa ovom kanalu se samo sme govoriti engleski. Ako nastaviš da govoriš na Jugoslovenskom, možeš biti kažnjen.",
    "banchobot": " 你好！ 我是BanchoBot！ 很高兴见到你。\n不过我是一个机器人，所以我不能真的和你聊天 :(",
    "beatmapping": "请阅读 [https://osu.ppy.sh/wiki/Beatmapping Beatmapping] 以取得更多与作图相关的提示。",
    "beginner": "找适合新手的图？ [https://osu.ppy.sh/forum/t/13976 这里] 就对啦！\n来看看 Alace 老师为新手们整理的谱面清单！",
    "bn": "[[Beatmap Nomination Group]] 是一个负责谱面审核的团队，负责检视审核已完成的谱面并将质量合格者放入Qualified列表等待Rank。\n如果你有任何关于 Mapping 或者 Modding 的问题，都可​​以找他们谈谈哦！",
    "bored": "[https://www.youtube.com/watch?v=y61v2QCHlpY 告诉别人自己无聊是没有意义滴！适当休息，做些别的事吧。（本链接需要科学上网）]",
    "bug": "请在 [https://osu.ppy.sh/forum/5 这里] 提交bug，而不是在游戏内的聊天室内。并且请确保不要提出其他人提出过的问题。",
    "bulgarian": "B #osu се говори само на английски! Моля, преместете се в #bulgarian.",
    "cantonese": "識講廣東話嘅朋友麻煩用 #cantonese 頻道。 係選擇+ Channels之後， 再選擇 #cantonese 。\n注意 #osu 淨係比用英文， 如果收到呢條信息之後繼續喺 #osu 入面用廣東話傾計， 管理員有權利作禁言處理。",
    "capping": "每个词开头都用大写并不好玩，也对其他人毫无益处。请做些利己利人的事，打字时淡定点。",
    "caps": "聊天请勿全部使用大写字母，这很不受欢迎且可能导致你被禁言。",
    "change-modes": "如要切换游戏模式（标准，太鼓，接水果，下落式），请回到歌曲选择页面下方，点击 Mode 或者使用快捷键 ctrl+ 1~4 来进行选择。需要注意的是有些谱面是限定模式的！",
    "change-name": "要改名的话，你得先成为一位 [https://osu.ppy.sh/p/support osu!支持者] 。之后你就可以在 [https://store.ppy.sh/store/product/32 这里] 改名了！\n要是将来要改回旧名字，或者想进行小的修正，又或是想要获得帮助，请发电子邮件到 accounts@ppy.sh 进行说明。",
    "changelog": "所有游戏、Bancho 和网页的更新都可以在 osu! [https://osu.ppy.sh/p/changelog 开发记录] 中查看！",
    "chars": "请勿在聊天室使用 Unicode 字符或非标准文字。",
    "charts": "osu! charts 是一种主题音乐包，每月发布，你可以在这里找到： [https://osu.ppy.sh/p/chart here!]",
    "chinese": "中文用户请点击 #chinese 以进入中文频道进行交流。\n#osu 是英文专属频道，如果接获此讯息后继续在 #osu 内以中文交谈，管理员有权利禁言。",
    "chinese-input": "全屏有些输入法可能不能选字哟，试试 Alt+Enter 选用 borderless 或者安装搜狗输入法。",
    "chinese-pinyin": "由于并非所有玩家都了解拼音或注音，因此请尽量避免使用注音符号跟拼音字母及其缩写，有你的配合，中频才能更舒服更健康。",
    "color": "浅黄：普通用户｜黄色：[https://osu.ppy.sh/p/support 捐赠玩家]｜红色：[https://osu.ppy.sh/wiki/NAT Nomination Assessment Team] 或是 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT（社群管理团队）]｜白色：你自己，或是一行使用 /me 指令的动作讯息｜深蓝色：私信｜绿色：有人提到你的名字（或是 Highlight）｜粉红色：IRC 萌萌机器人（Banchobot）",
    "colour": "浅黄：普通用户｜黄色：[https://osu.ppy.sh/p/support 捐赠玩家]｜红色：[https://osu.ppy.sh/wiki/NAT Nomination Assessment Team] 或是 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT（社群管理团队）]｜白色：你自己，或是一行使用 /me 指令的动作讯息｜深蓝色：私信｜绿色：有人提到你的名字（或是 Highlight）｜粉红色：IRC 萌萌机器人（Banchobot）",
    "conmigo": "Los pronombres personales conmigo, contigo y consigo se deben escribir en una sola palabra.",
    "command-abuse": "虽然用指令真的很方便，可是不要乱玩它！会被当成刷屏的，而且还有可能会被禁言哦！",
    "comment": "如果想为谱面添加弹幕，请在播放录像的时候点击屏幕右上的 Discussion 标签，\n并且勾选你想要显示的评论项目，之后直接输入自己的评论回车即可。\n如果弹幕没有显示，请点击 Show Comments 。\n注意：某些谱面的弹幕数量较多，可能会影响到你正在观看的谱面或者造成播放延迟。\n",
    "comment-color": "普通用户只能发布白色弹幕，成为 [https://osu.ppy.sh/p/supporter 捐赠玩家] 之后，就能发布自定义颜色的弹幕。",
    "conferencemode": "被聊天室的「加入」和「退出」消息所困扰？？ [http://wiki.xkcd.com/irc/Hide_join_part_messages 这个] 也许可以帮助你！",
    "country-ranking": "来围观[https://osu.ppy.sh/p/countryranking 国家和地区分数排行]吧！",
    "critic": "提供评论时，请同时提供有用的建议，能帮助改善问题。",
    "ctb": "[https://osu.ppy.sh/forum/p/60690 接水果模式 FAQ ]",
    "cutting-edge": "Cutting-edge 是 osu! 的实验性版本，用来在正式版本之前测试新特性。你可以在选项中切换版本。\n更新碰到问题的话请 [https://osu.ppy.sh/wiki/Help_Center#Updater_Issues 参照这个文章]。",
    "cwc": "cwc 指的是国际 osu! 接水果大赛！如果想知道更多，请 [https://osu.ppy.sh/wiki/ZH:Catch_the_Beat_World_Cup_2015 猛戳我！]",
    "czechoslovak": "Jestli mluvíš česky nebo slovensky tak se připoj do #czechoslovak",
    "danish": "Vær venlig at bruge #skandinavian hvis du ønsker at tale Dansk. Klik på “+ Channels” fanen og vælg #skandinavian.\n#osu er den eneste universelle standard kanal. I denne kanal, må du kun tale engelsk!",
    "dasdass": "Das ist ein Artikel oder Pronomen und wird in Zusammenhang mit Substantiven verwendet.\nDass hingegen ist eine Konjunktion und leitet Nebensätze, Subjektsätze oder Attributsätze ein.",
    "de-ki": "Bağlaç olan de/da ve ki iki sözcüğü ya da cümleyi bağlama görevinde kullanıldığı için ayrı yazılır.\nEk olan -de/-da bulunma halini, -ki ise duruma göre ilgi zamirini ya da isimden sıfat türeten yapım ekini belirttiği için bitişik yazılır.\nSoru ekleri ve şey sözcüğü her zaman ayrı yazılır.",
    "decency": "请在聊天频道内自重。子曾曰：己所不欲，勿施于人。",
    "disable-this": "别随便请求增加功能，请求了也不一定能加上去。实在需要的话，再考虑要不要去 [https://osu.ppy.sh/forum/4 功能增加请求论坛] 说一下吧。",
    "distance-snap": "最简单的纠正 note 间距的方法是打开「间距控制」功能。你可以在编辑器的右下角找到它（distance snap）。你可以通过鼠标滚轮来调整 note 间距的大小。但是最好不要通篇用一个间距，除非你确定这样做很好。详情：[[Distance_Snap]]",
    "dont-ask-peppy": "别总是想找 peppy 回答问题，他超忙的。问问频道里的其他人吧！",
    "douche": "身为一个全能的 osu! 管理员，是有权利自行惩罚那些钻规则漏洞的人的。因为有时官方的规则也不能涵盖所有混蛋的不当所为。总之以防万一：不作死就不会死。",
    "download": "[https://osu.ppy.sh/p/beatmaplist 这里]可以让你下载更多谱面。你还可以在[https://osu.ppy.sh/beatmaps/packs 这里]下载谱面包。如果你不知道如何导入谱面，请查看[http://i.imgur.com/kpX2N3m.jpg 这里]。",
    "drugs": "请勿在 osu! 聊天室中讨论任何性质的药物。",
    "dutch": "In dit kanaal mag je geen Nederlands praten. Ga naar #dutch als je toch Nederlands wilt praten!",
    "editor-shortcuts": "你可以在 [[Beatmapping#Keyboard_Shortcuts]] 里找到编辑器的快捷键。",
    "english": "#english 是一个全能的频道，专为一些找不到共同话题的人而设的。当然，这也包含了漫画和动画。",
    "evade": "钻空子逃避禁言的行为依旧是可以被封号的。请不要这样做，因为封号比禁言严重多了。",
    "fallback": "正式版（Fallback）是过时的Osu!版本。为了简化我们的框架，新版的客户端移除了DirectX的支持（Fallback版仍然保留）。如果你被自动切换到这个版本，这说明你的电脑太低端并不支持当前和未来的版本。\n如果你要使用当前版本，请升级你的显卡使其支持OpenGL。OpenGL是这些新版本最需要的组件。 [https://osu.ppy.sh/wiki/GL_Support_Issues 了解更多]",
    "faq": "[https://osu.ppy.sh/forum/t/10737 我是新手教学，请轻轻地点我。]\n[https://osu.ppy.sh/forum/t/109978 中文区精华/资料索引] 由微风娘娘亲手整理的索引，看过一遍还是不懂的话再发问吧。",
    "feature": "任何关于游戏改进的建议请在 [https://osu.ppy.sh/forum/4 Feature Request]版面提出你的需求。发帖之前请务必阅读[https://osu.ppy.sh/forum/t/454006 论坛规则]！",
    "filipino": "Pwede kang magsalita ng tagalog sa #filipino pero magsalita lamang ng wikang Ingles sa loob ng #osu\nMaari kang bigyan ng silence ng mga moderators kung ipagpapatuloy mo yan.",
    "filter": "不要想着用「草X马」之类的任何钻漏洞方法来绕过词汇检测系统，该怎么死还是会怎么死。",
    "foul-play": "请使用个人档案的[https://i.imgur.com/GG9xlLA.png 举报按钮（查看链接需要科学上网）]来举报涉嫌使用非法手段的玩家。并且尽量提供详细资料和证据。你也可以到谱面页面的前五十名列表举报涉嫌的游玩记录。",
    "percolate": "不要想着用「草X马」之类的任何钻漏洞方法来绕过词汇检测系统，该怎么死还是会怎么死。",
    "finnish": "Puhuaksesi suomea, mene #finnish - kanavalle (Klikkaa + Channels -> #finnish)",
    "flow": "[https://osu.ppy.sh/forum/t/141227 这个主题] 会帮助你理解什么是 Flow 。",
    "french": "#osu est un canal de discussion où seul l'anglais est autorisé. \nPour accéder au canal francophone, cliquez sur le bouton jaune « + » puis sur « #french ».",
    "friend": "要加好友请打 /addfriend <对方ID> 。\n另外，你也可以按 F9 调出用户选单然后找到你需要找的人来加好友。\n你也可以点所要加的好友的 ID 然后点 Add as Friend 。 \n除此之外，你也可以到他的Profile点 Add as Friend 。",
    "friends-list": "若要查看当前在线好友，请按 F9 ，然后在最上方的 filter 左边选择「好友」。\n你也可以通过在官网上点击 Settings 来查看所有的好友名单（当然你必须要先登录）。",
    "fullscreen": "「窗口模式」或「全屏模式」可以在设置里面的「图像」选项卡下更改。\n当然你也可以通过按键盘上的 Alt+Enter 键来切换窗口模式和全屏幕模式。注意：OpenGL模式下无法支持全屏模式。",
    "german": "Bitte benutze den #german Channel, um Deutsch zu reden.\nIn diesem Channel darf nur Englisch gesprochen werden. Solltest du weiterhin Deutsch sprechen, kannst du bestraft werden.",
    "glossary": "[[ZH:glossary]] 你可以在这里找到 osu! 的术语。",
    "gmt": "GMT 是 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team Global Moderation Team] 的简称，是 osu! 的社群管理团队。他们在游戏里用红名显示，在论坛上用绿名显示。\n他们的工作是帮助管理论坛和游戏内的各个聊天室。",
    "english-help": "[https://osu.ppy.sh/forum/t/12016 其实很容易的, 你也可以做到...大概...]",
    "grammar": "请尽量使用正确的语言进行交流。当然，少量的拼写或者标点错误可以接受，但是求求你不要使用钱语或者某些只有你自己能看懂的缩写。那会让你看上去很智障。",
    "greek": "Το #osu είναι κανάλι στο οποίο ομιλούνται μόνο αγγλικά, παρακαλώ χρησιμοποιήστε το #greek για να μιλήσετε ελληνικά.",
    "guide": "不知道这游戏怎么玩？想要进入作图和摸图的世界？ [https://osu.ppy.sh/wiki/Guides 这里] 有你想要的一切！",
    "hacked": "如果你觉得你被盗号了，请立即电邮至 accounts@ppy.sh 举报。\n如果不这样做，你很有可能会被封号。",
    "hard": "多加练习是提高水平的必要条件之一。",
    "hebrew": "בערוץ זה מדברים אנגלית בלבד. לדיונים בעברית גשו לערוץ #hebrew.",
    "help": "请点击加入 #help 频道来获取所需的帮助信息。此外，#help频道是多语言的。\n如果没有人响应，你可以在论坛的[https://osu.ppy.sh/forum/5 帮助]板块发帖提问。\n你也可以查看[http://help.ppy.sh 这个页面]阅读帮助文档，包括关于账号的问题。",
    "hitsound-library": "在[https://osu.ppy.sh/forum/p/164927 这里] 可以为你的谱面找到好听的音效。",
    "hl": "如果你的Highlight列表里有常用字词的话，不要因为被无意中被Highlight到而生气哟！你如果你不想被Highlight到的话，可以关掉提醒功能。",
    "how-to-get-modded": "如果你希望为你的谱面寻找 mod 的话，请点击 [[Getting_Your_Map_Modded]] 。",
    "how-to-bn": "想加入 BN 的话的请看 [https://osu.ppy.sh/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator 这里] 。",
    "how-to-gmt": "频道管理员是从对社群有着高度贡献的人们中人工选出的。\n如果你想帮助我们，多在各个频道及时的用 !report 命令来举报违规行为吧。",
    "how-to-play": "[https://osu.ppy.sh/wiki/ZH:FAQ#.E6.88.91.E8.A6.81.E6.80.8E.E4.B9.88.E7.8E.A9.E8.BF.99.E6.B8.B8.E6.88.8F.E5.95.8A.EF.BC.9F 点击这里来学习游戏的玩法。]",
    "how-to-rank": "看这里 [[ZH:How_to_Get_Your_Map_Ranked]] 。",
    "hungarian": "Kérlek, hogy a magyar nyelv használatára a #hungarian csatornát használjátok. Ha más nyelveknek fenntartott csatornákban használjátok a saját nyelveteket, akkor egy ideig nem írhattok.",
    "hyperdash": "你接到一个红色的果子之后你会进入超级跳跃（Hyperdash）状态。在这种状态下，你会跑的更快，直到下一个水果完全落下来。",
    "ignore": "如果想要屏蔽某个用户的发言，请在聊天频道中输入 /ignore <用户名>，这样你就不会再看到该用户的所发送的所有信息，包括私人聊天。\n如果要解除屏蔽，请输入 /unignore <用户名>。\n如果你想永久屏蔽某人，请查看 [http://help.ppy.sh/article/141/how-do-i-completely-block-another-user-from-contacting-me 这里].",
    "import": "[http://i.imgur.com/kpX2N3m.jpg 点击这里] 来查询如何将谱面导入 osu! 。",
    "indonesian": "Pembicaraan di #osu dikhususkan dalam Bahasa Inggris. \nUntuk mengobrol dalam Bahasa Indonesia, silakan kunjungi #indonesian dengan cara mengklik tombol (+) dan memilih #indonesian pada daftar pilihan yang muncul.",
    "inheriting": "如果在 Timing control points（按F6）窗口勾选 Inhert previous timing settings（绿线）选项，会使你当前选中的时间点的 BPM 值与前一个保持一致。这可以使你方便的改变音效的大小，音效组的选择， kiai 的起始或结束等等。\n另外，他也可以使你的 bpm 在 0.5~2.0 范围内变化。请在可能的情况下全部使用绿线。",
    "irc": "IRC服务器：irc.ppy.sh:6667 密码请见：https://osu.ppy.sh/p/irc 更多资讯请见：https://osu.ppy.sh/wiki/IRC",
    "italian": "Per favore entra nel canale #italian per parlare italiano.\nIl canale #osu è solo per la lingua inglese. I moderatori hanno il diritto di silenziarti se continui a parlare la lingua sbagliata nel canale sbagliato.",
    "japanese": "日本語での会話の場合、#japanese を利用してください。クリックで開きます。",
    "keys": "你可以在“输入”部分更改键盘快捷键，在“osu!mania键位排列”按钮中调整osu!mania的按键和布局。",
    "kiai": "Kiai 模式是一个特殊效果，你可以在 Timing Setup Panel 里面的 style 选项卡来把它添加到时间段内。\n添加了 Kiai 模式的时间段最开开始会有喷泉的效果，并且之后的 note 会有闪光效果。这些效果使这个时间段变得与众不同。\n请不要滥用 Kiai 。",
    "korean": "한국어로 채팅하시려면 #korean 을 클릭하여 한국 채팅 창에서 해 주십시오.\n이 글을 보신 후에도 이곳에서 계속 한국어를 쓰실 경우 제재를 받으실 수 있습니다.",
    "kudosu": "[https://osu.ppy.sh/wiki/ZH:Kudosu Kudosu] 是对他人谱面进行 modding 后的奖励。",
    "lag": "卡顿和延迟的原因有[https://osu.ppy.sh/help/wiki/Performance_Troubleshooting 很多种] —— 很多时候是因为有后台进程在抢占资源。如果你确认是 osu! 自己在卡而且只有 osu! 会卡，请在 [https://osu.ppy.sh/forum/5 帮助论坛]详细描述你遇到的问题并附带任何可能有帮助的信息。",
    "language": "请注意言辞，保持礼貌，不然的话，你很可能会被禁言。",
    "language-specific": "在频道中请使用适合该频道的语言。使用拉丁化的表达方式（如日语罗马字或 hàn yǔ pīn yīn）也不行。",
    "lazer": "",
    "level": "你的等级是由你的总分数计算而来的，不仅仅是 pass 一张图才有分，即使 fail 也是有分的。所以只要你坚持打图，等级就会一点一点升上去。",
    "lines": "可以打成一行的字，就不要打一整个屏幕刷屏，谢谢。:)",
    "link": "请用这种格式发送链接 [地址 文字] 。「地址」是你要发的链接网址，「文字」是你要说明的文字。\n[https://osu.ppy.sh/ 就像这样！]（不要忘记 http:// 以及地址和文字中间的英文空格哟！）。",
    "lobby": "#lobby 是一个不限制语言的用来宣传多人游戏的房间，而要讨论你的房间内的事请用 #multiplayer ，除此之外要用中文聊天请用 #chinese 。",
    "localisation": "在 [https://docs.google.com/spreadsheet/ccc?key=0AlsSAL_F7-xDdHhUUjNSa19QendtcTdYUjE2S2hnVHc#gid=24 这里] 可以查看 osu! 本地化翻译文本。",
    "long-link": "最好不要发送长的网址。如要发送，请用这种格式发送链接[地址 文字]。「地址」是你要发的链接网址，「文字」是你要说明的文字。",
    "long-text": "请不要把长文本贴入频道，否则你很有可能会被禁言。",
    "loved": "Loved是一个基于社区的新的谱面状态，它让一些无法正常 Rank 的谱面也能拥有完整的排行榜。[https://osu.ppy.sh/news/151925254083 了解更多]",
    "mac": "[https://osx.ppy.sh 点击这里] 来查询如何在 Mac OS X 上运行 osu! 。",
    "malaysian": "Perbualan di #osu dikhususkan untuk berbahasa inggeris. Jika mahu menggunakan bahasa melayu, sila pergi ke #malaysian\nUntuk memasuki ke channel #malaysian, klik + Channels kemudian pilih kotak yang mempunyai ayat #malaysian.",
    "map-this": "Mapper 是一群大忙人，作图是一个大工程。求作图基本上不会有人理的。这么喜欢那首歌的话为何不自己动手呢？",
    "mapping": "可以在 [https://osu.ppy.sh/forum/p/988111 这里] 找到作图帮助。",
    "mat": "MAT（Mapping Assistance Team）曾经是辅助 BAT 进行谱面审核的用户组，现在已经停止使用，且所有成员都已并入 BAT 。\n安息吧，MAT 13.04.23",
    "modhelp": "谱面制作的一般向问题请加入 #mapping 频道进行咨询和讨论。",
    "modqueue": "玩家可以在 [https://osu.ppy.sh/forum/60 Modding Queues] 版面建立自己的 Modding 队列从而为他人提供 Mod 服务。",
    "modreqs": "你可以随时在 #modreqs 频道中发布你的谱面来请求他人进行 Mod 。当然，BN 们因为一般都很忙，也有其他人先行提交了 Mod 请求，所以你也可以找普通玩家来帮你 Mod 图。请求 mod 时请使用 /np 命令或者 [链接 文本] 格式。最后别忘了表示感谢。",
    "multi-invite": "如果想要邀请其他玩家加入你的多人游戏，只需要在聊天栏中点击对方的姓名，或者直接按 F9 点击对方姓名板，然后在弹出的对话框中选择「邀请玩家至房间」即可。\n除此，你也可以靠输入 /invite <玩家ID> 进行邀请。",
    "multi-link": "",
    "multiaccounting": "别开小号，别开小号。因为很重要所以说两遍。你必然会被抓到，然后被禁言很长一段时间，甚至直接被 ban 。别开小号。",
    "multiplayer": "请勿在 #lobby 以外的任何频道宣传多人游戏。",
    "mwc": "一个国际性的 osu! Mania 比赛。请移步到 [https://osu.ppy.sh/wiki/Osu!mania_7K_World_Cup_2016 维基页面] 查看更多资讯。",
    "nat": "[https://osu.ppy.sh/wiki/People/Nomination_Assessment_Team Nomination Assessment Team] 管理BN并监督Beatmap Ranked流程。他们负责评估目前的BN與有志成为BN的候选人，以及调解Beatmap veto和其他map/修改相关的争议。",
    "news": "",
    "nightcore": "点击 DoubleTime Mod的图标即可切换至 Nightcore Mod！来享受动感的鼓点和音调吧。这个 Mod 在计分上与 DoubleTime 相同。",
    "noel": "N'utilisez pas « :noel: », « :hap: » ou toute autre expression similaire, vous risquez de vous faire cataloguer comme un boulet et d'attirer la haine de tout #french sur vous.",
    "norwegian": "Vær så snill å bruke #skandinavian for å snakke norsk. Klikk på fanen som heter “+ Channels” og velg #skandinavian. \n#osu er serverens standardkanal. Den er også bare engelsk-språklig!",
    "np": "输入 /np 就可以告诉别人你正在听什么或者在玩什么歌。",
    "nsfw": "R18 向讨论是不被允许的。 osu! 是全年龄向的游戏，所以请让聊天室保持纯洁，否则你会在不被提醒的情况下被禁言。",
    "osu": "#osu 频道是 osu! 的综合聊天频道，可以讨论一切和 osu! 有关的话题。同时，#osu 是英文专用频道，请不要在其中使用中文。",
    "osu!tablet": "点击阅读 [https://osu.ppy.sh/forum/t/169139 osu! 绘图板官方论坛] 来获取相关信息及订货！",
    "osu!talk": "osu!talk 是由 deadbeat 和 ztrot 主持的访谈节目，两人会访问 osu! 社群的成员并讨论像是世界赛之类的活动。\n每一集都会在 [https://discord.gg/014x1ACj2VdUPLU5x discord服务器] 上进行；若想发问，可以参与 Q&A 环节。 [https://osu.ppy.sh/forum/t/225111 点此] 查看详情。",
    "osucore": "2011 年的愚人节彩蛋。所有谱面默认开启 Double Time 模式，并且声调变高。\n不久之后就变成了 Nightcore 模式，和当年的效果一样。",
    "osu!droid": "[https://osu.ppy.sh/wiki/osu!droid osu!droid] 曾经是 osu! 的安卓版本，但该项目早已被废弃，也已经于2016年因差评从 Google Play 商店下架。",
    "osumania": "如果你想讨论 osu!mania 的话可以使用 #osumania ，当然是用英文。",
    "osustream": "[http://www.osustream.com osu!stream] 是 iOS 上的一个osu!版本，由我们的 peppy 制作和维护！",
    "osz": "osz 是 osu! 谱面歌包的文件格式。你可以通过下载 osz 歌包并双击/拖入 osu! 主界面/放入 osu! 的 songs 文件夹等方式来解压并将其导入 osu! 中。",
    "osz2": "旧的 osz 文件是可以解压缩的。这意味着你可以自己编辑，删改里面的文件。\n但新的可以被独立加密、上传、使用的 osz2 文件不需要被解压，会一直作为 osz2 文件放在你的 songs 文件夹下。",
    "owc": "osu! 世界杯大赛之一， [https://osu.ppy.sh/wiki/OWC 请点击这里查询更多讯息] 。",
    "peppy": "peppy 是 osu! 的创建者，换而言之，他就是有着高贵淡蓝色名字的皮老板。当然了，不要在公开聊天时随意提及他的名字哦，不过，好像提了也没什么。。。\n",
    "perfect": "打不到 SS ？这个模式可以让你打不到 300 的时候自动重新开始。\n你可以在模式选择界面右击 SuddenDeath 图标来切换至该模式。",
    "ping": "Pong!",
    "pippi": "她是 osu! 的吉祥物。Pippi-don 是她的太鼓形象。",
    "piracy": "请勿在谈话中公开讨论盗版。盗版内容是被禁止的，你可能会因为谈论这些内容而被禁言。",
    "play-shortcuts": "[https://osu.ppy.sh/forum/t/32022 osu! 快捷键一览表]",
    "pm": "如果要与其他人进行私聊，请在在聊天栏中点击对方的名字，或者直接点击对方的姓名版，然后点击 Start Chat ，就可以在弹出的新标签页中进行私聊了。\n另外，你也可以直接在聊天栏中输入指令 /msg <对方ID> <你要发送的信息> 或者 /chat <对方ID> <你要发送的信息> 或者 /query <对方ID> <你要发送的信息> 三种方式来进行私聊。\n要快速回复别人发来的消息，你可以用 /r <你要发送的信息> 。\n当然，在实际使用聊天栏指令中请不要加入 <> 标签。\n",
    "polish": "Dla rozmowy z innymi graczami z Polski użyj kanału #polish. Na kanałach bez określonego języka mów po angielsku, inaczej możesz otrzymać tymczasową blokadę czatu. ",
    "portuguese": "#osu é somente para a língua inglesa. [osu://chan/#portuguese Para falar português, clique aqui]\nSe você continuar falando português no #osu, os moderadores têm o direito de silenciar você.",
    "pp": "[https://osu.ppy.sh/wiki/Performance_Points Performance Points（pp）]是 osu! 现行的排名系统",
    "pp-rework-lazer": "",
    "preview": "当你在谱面列表中选择了一张谱面时，歌曲会从「预览时间点」开始播放。\n谱面的作者（即 Mapper）可以在制作的时候通过选择 Timing 菜单里的 Set Current Position as Preview Time 来设置预览点。合适的预览点设置将会令你的谱面更具吸引力。",
    "qat": "QAT负责检查最近qualified map的质量和可玩性。在2019年4月审图系统改版后，他们更名为NAT以更好的反映他们目前的工作领域。",
    "qualified": "这是 modding 系统的前进方向！ Qualified 状态代表这个图差不多可以 Rank 了。在这些图当中，你可以获得排名，不过没有PP。这些图会维持Qualified 状态一周，期间如果社会对图有意见而 QAT 认为这些意见值得参考，图就会打回重改，分数记录也会抹去；相反图在 Qualified 状态保持一周的话就会被 Rank。",
    "ranked": "Ranked 谱面即已通过社群审核的谱面。当你玩一张 Ranked 谱面时，你的成绩——包括 PP 点数，准确度以及分数等——都会被记录并且加入到全球的排行榜中。\n每张 Ranked 谱面都会有独立的分数榜单，并且会以“桃心”标记。",
    "ranking-criteria": "点击 [[RC]] 查询谱面 Rank 守则。",
    "redname": "osu! 聊天室里带有红名字的用户是 [https://osu.ppy.sh/wiki/People/Global_Moderation_Team GMT] 或者 [https://osu.ppy.sh/wiki/People/The_Team/Nomination_Assessment_Team NAT]。",
    "report": "管理员并不是每时每刻都在关注这个频道。如果有人在这个频道作死，请举报他们，管理员会立刻看到你的举报并采取行动的。请使用 !report <用户名> <举报原因> 的格式进行举报。另外请避免在 BanchoBot 的 PM 里举报。",
    "report-abuse": "请不要滥用举报功能，这样不但会降低管理员处理举报的效率，而且有可能会让你因滥用该功能而被禁言。",
    "request": "点击[https://osu.ppy.sh/p/beatmaplist&r=8 这里]建立属于自己的modding队列以提供mod服务，或者输入!request指令以获得一张随机的谱面进行mod",
    "respect": "请尊重其他玩家，不要作出人身攻击等令人困扰的行为。",
    "roll-abuse": "请不要连续输入 !roll 指令除非你想被禁言。",
    "romaji": "（对于日语）请不要过多使用罗马字，否则你可能会被禁言。",
    "romanian": "Te rog să intri pe canalul #romanian dacă vrei să vorbești în română.\nÎn canalul de chat #osu se vorbește doar în limba engleză. Dacă continui să vorbești în oricare altă limbă, în afară de engleză, operatorii îți vor da Silence.",
    "room": "自己动手，丰衣足食，没房间进的话那就自己建呗。",
    "rp": "你可以在适当的频道中角色扮演（语C），不过你得确定自己并没有打扰到在同一频道中的其他人。",
    "rules": "[https://osu.ppy.sh/wiki/zh/Rules 官方守则]",
    "russian": "Здесь запрещено общаться на русском языке, перейдите в #russian. Это не хэштег, кликните на синюю надпись.",
    "sauce": "有些时候服务器不稳定是因为被某些坏蛋DDoS攻击了，如果你能上 twitter 就请关注 [https://twitter.com/osustatus @osustatus] 获取最新情报。或者 [https://status.ppy.sh 这里] 也可以。实在不行的话就去 [http://tieba.baidu.com/osu osu贴吧]。",
    "sb": "Storyboard的相关教程请 [https://osu.ppy.sh/forum/t/109978 点击这里进行查阅] 。",
    "scorev2": "Scorev2是一种新的得分算法，在该算法下所有游戏模式的最大得分为100万（转盘和Mods除外）。\n它也会更改滑条的工作方式，使其和打击圈有相同的时间准确度要求。",
    "scoring": "想了解 osu! 分数的计算方式请点击 [[Score#scoring]] 。",
    "seitseid": "Seit ist eine temporale Präposition und wird bei Zeitangaben verwendet.\nHingegen ist seid die 2. Person Plural im Präsens von sein und wird als Verb verwendet.",
    "silence": "禁言的意思是你不能在聊天室里聊天或者不能在论坛发帖（在 Help 区除外）。第一次被禁言是 5 分钟，然后逐次翻倍。如果情况严重，那可能就不是翻倍那么简单了。\n禁言只会对初犯者 / 情节轻微者实施，所以只要好好守规矩就不会有事了。",
    "skandinavian": "Please use the #skandinavian Channel to talk Scandinavian languages. Click on the + Channels tab and select #skandinavian. \n#osu is a universal default channel. In this channel, you shall only talk English!",
    "skinning": "[https://osu.ppy.sh/forum/t/51694 制作皮肤常见问题]",
    "sleep": "[https://www.youtube.com/watch?v=y61v2QCHlpY 别玩太晚了快睡啦！（本链接需要翻墙）]",
    "songs-not-appearing": "歌曲丢了？试试按 F5吧 。",
    "spaces": "聊天时请不要在每一个汉字之间插入空格。",
    "spam": "请不要刷屏，否则你将会被禁言。",
    "spanish": "En este canal no se habla español, si quieres hablar español, [osu://chan/#spanish haz clic en este cuadro azul.]\nSi continuas hablando fuera del canal designado, podrías ser silenciado.",
    "spectate": "若要观看其他玩家，请输入 /watch <对方ID> ；或者按F9，找到你要观看的人并点击，选择第一项（Start Spectating）即可。",
    "spoiler": "不要公开剧透动漫 / 同人作品，违规时可能被禁言/封号。",
    "status": "要查询系统当前的状态信息，请在推特上关注 [http://twitter.com/osustatus @osustatus] （自备梯子）。如果需要查询服务器状态，可以看 [https://status.ppy.sh 这里] 。",
    "store": "[http://store.ppy.sh/ 欢迎来到osu!市场] ，在这里你可以买各种 osu! 的商品，比如T恤和其他有趣的东西！",
    "submit": "[https://osu.ppy.sh/wiki/Submission 点击这里了解谱面上传的相关说明]",
    "suck": "熟练 osu! 的过程是很漫长的，苦练终成触哟。",
    "supporter": "来成为 [https://osu.ppy.sh/p/support osu!赞助用户] 吧！你会获得许多好处，也可以帮助开发团队做更多的事哦！",
    "supporter-please": "请勿在公众频道寻求能送你 supporter 的人，[https://osu.ppy.sh/p/support 需要的请自己买吧！ ]",
    "swedish": "Använd endast kanalen #skandinavian för svenska. Klicka på fliken + och välj #skandinavian\n#osu är en universell standardkanal. Här inne får du endast tala engelska!",
    "tablet": "如果你在使用绘图板玩 osu! ，如果你的光标到处乱跳，请保证游戏中鼠标敏感度为 1.00x。请通过改变绘图板映射来提高“敏感度”。\n如果你的光标动不起来，请在选项中关闭 Raw Input 。\n其他绘图板相关问题请 [https://osu.ppy.sh/forum/t/87301 点击阅读] 。",
    "tag": "Tag 即多人游戏中的合作模式。在 Tag 模式下，所有玩家会被要求按照谱面 Combo 的顺序轮流参与，并要同时挑战转盘。 Tag 模式并无胜负之分。",
    "taiko": "osu! 的太鼓模式借鉴了著名日本音乐游戏 [http://baike.baidu.com/view/1112214.htm 太鼓达人] 的玩法，其游戏内容专注于节奏本身，而区别于 osu! 模式下同时要注重节奏和移动。",
    "taiko-mapping": "[https://osu.ppy.sh/forum/t/152263 太鼓制作教程]",
    "taiko-maps": "[https://osu.ppy.sh/forum/t/5397&st=0&sk=t&sd=a 你可到这里寻找太鼓达人的图]",
    "thai": "ขอความร่วมมือคนไทยทุกท่านพูดคุยกันในแชนเนลไทยด้วยครับ  คลิกเข้าห้องไทยได้จาก ⇒  #thai",
    "topic": "别说这个了，说点别的好吗？",
    "training": "[https://osu.ppy.sh/forum/t/4280 老詹的新手调教课程]",
    "tsya": "Чтобы определить, писать глагол с «-тся» или «-ться» в конце, спросите себя, на какой вопрос отвечает этот глагол: «что делать?» или «что делает?».\nЕсли в вопросе есть мягкий знак, значит, он есть и в глаголе. Примеры: https://tsya.ru/examples.html",
    "turkish": "Bulunduğunuz sekmede Türkçe konuşmak yasaktır. Lütfen Türkçe konuşmak için #turkish sekmesine gidiniz.",
    "tutorial": "[https://osu.ppy.sh/wiki/ZH:FAQ 点击这里] 来开始你的 osu! 之旅！\n[https://osu.ppy.sh/forum/t/60228 点击这里] 从零开始学习谱面制作。",
    "twc": "osu! 太鼓世界杯， [https://new.ppy.sh/wiki/Tournaments/TWC/2017/ 请点击这里获取详细信息] 。",
    "ukrainian": "Будь ласка, спілкуйтеся українською мовою в #ukrainian, інакше можете отримати сайленс.",
    "unicode": "请勿在聊天室使用 Unicode 字符或非标准文字。你可能会被禁言。",
    "upload-cap": "为了让作图者可以专心做自己手上的图，你上传的图的数量是有限制的。\n普通玩家上传的图最多可以有 3 到 6 张，赞助玩家上传的图则最多可以有 5 至 10 张，具体的数量限制与用户制作的Rank 图的数量有关。",
    "utf8": "请把你的 IRC 客户端的文字编码设置为 UTF-8 ，以免收到或是发出乱码。",
    "videogames": "电子游戏相关内容是可以在频道里讨论的，但是如果讨论干涉了正常的聊天的话，请移步 #videogames 哦（英文限定）。",
    "vietnamese": "Đừng sử dụng Tiếng Việt ở bất kì kênh nào khác. Hãy tham gia kênh #vietnamese để có thể nói chuyện bằng Tiếng Việt nhé.",
    "welcome": "欢迎来到 osu! ，如果你有问题需要解答欢迎访问 #help 频道提问，祝游戏愉快！",
    "when": "短剑重铸之日，骑士归来之时。\n",
    "wiki": "勇敢的少年快去编辑[https://osu.ppy.sh/wiki/ wiki]创造奇迹。",
    "wiki-link": "把条目名写在双中括号 [[ ]] 中，可以发出 wiki 页的链接。\n例如， 把 Kudosu 写在 [[ ]] 中间可以发出 [[Kudosu]] 。",
    "zallius": "His eyes have awakened.",
    "countfaq": "There are 213 active FAQs (out of a possible 217) in the Simplified Chinese (中文(简体)) language.",
    "completion": "The Simplified Chinese (中文(简体)) FAQ as of last update is 98.16% complete, with the overall FAQ completion at 80.74%.",
    "mptimer60": "Mp timer has been set to 60 seconds!"
}
